### ISSUE TITLE
Staged changes don't show up in `git blame` view

### ISSUE THREAD

**Issue by rowillia** [zed-industries/zed#15456] opened 2024-07-30 02:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I make a change and stage it, if I hover over the line I don't get any `git blame` information.

Also: Per https://github.com/zed-industries/zed/issues/8665 it looks like the intended behavior is for `staged` changes to not show up in the gutter, but we've had some requests from engineers who would prefer if it was configurable.

### Environment

Zed: v0.146.1 (Zed Preview)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-07-30 07:39
Duplicate of https://github.com/zed-industries/zed/issues/10178

**Closed by SomeoneToIgnore** 2024-07-30 07:39 UTC
Labels: defect, triage, admin read
