### ISSUE TITLE
cmd+P search files should accept space instead of forward slash

### ISSUE THREAD

**Issue by lucasreppewelander** [zed-industries/zed#7077] opened 2024-01-30 13:37 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

On non-english keyboards the forward slash key is only accessible through a modifier key and this makes the search files feature tedious to work with, on nordic/german keyboards its accessible through <kbd>shift</kbd> + <kbd>7</kbd>.

To accept <kbd>space</kbd> as the same as a <kbd>/</kbd> in the search will increase my productivity a lot

**Comment by SomeoneToIgnore** [comment] 2024-01-30 21:30
Duplicate of https://github.com/zed-industries/zed/issues/5324

**Closed by SomeoneToIgnore** 2024-01-30 21:30 UTC
Labels: enhancement, triage, admin read
