### ISSUE TITLE
JSDoc: Documentation when hovering the element to see docs not well positioned

### ISSUE THREAD

**Issue by BrianIto** [zed-industries/zed#8395] opened 2024-02-25 16:45 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When hovering a **not used** class, method or anything else in JavaScript or related (svelte, react, nodejs, etc) the positioning of the hint is overflowing it to top. (Figure 1) It works when it's really close to top, (Figure 2) but when scrolled down it doesn't work as expected.

This happens beacuse the _"js: value is never read"_ is maybe positioned on top. And only when it doesnt fit above he goes down. If I use the value the _"js: value is never read"_ goes away and then the hint position itself normally.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Figure 1 👇
<img width="864" alt="Captura de Tela 2024-02-25 às 12 34 17" src="https://github.com/zed-industries/zed/assets/6891093/3c0b35c8-4f76-4c94-8fca-875958309444">

Figure 2 👇
<img width="949" alt="Captura de Tela 2024-02-25 às 12 39 38" src="https://github.com/zed-industries/zed/assets/6891093/9ea97180-1824-4ab2-a967-e4ff15c99a00">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-27 20:21
Hey @BrianIto,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5015

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-27 20:21 UTC
Labels: defect, popovers
