### ISSUE TITLE
Syntax recognition toml array table name

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12186] opened 2024-05-23 08:16 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see on zed the name of the table is the same color as the key, even if the theme changes it remains the same color, however on vscode the color is different to highlight it better.

See the build wording.

Another problem is the double bracket on vscode is highlighted in a different color on zed it doesn't happen.

Vscode:
<img width="623" alt="Screenshot 2024-05-23 alle 10 13 50" src="https://github.com/zed-industries/zed/assets/20476002/3c760adc-a9c8-4c62-985b-fbb200ba6b45">

<img width="373" alt="Screenshot 2024-05-23 alle 10 17 46" src="https://github.com/zed-industries/zed/assets/20476002/2b836c0a-a58e-4c56-bd84-f64766a8a3de">

Zed:
<img width="617" alt="Screenshot 2024-05-23 alle 10 13 58" src="https://github.com/zed-industries/zed/assets/20476002/afeee028-9d93-4b0b-aa9f-b872985d9408">

<img width="367" alt="Screenshot 2024-05-23 alle 10 17 54" src="https://github.com/zed-industries/zed/assets/20476002/0a4de125-7960-4e45-8fe8-ce310d5a83ad">

**Comment by notpeter** [comment] 2024-12-16 07:59
Zed cannot currently highlight individual brackets distinctly as is shown in vscode unless new captures for inner/outer brackets for were explicitly added to the upstream [tree-sitter-toml](https://github.com/ikatyang/tree-sitter-toml).

Closing as duplicate of: 
- #5259 
- #5345 

Since either would support the coloration requested here.
Thanks for reporting.

**Closed by notpeter** 2024-12-16 07:59 UTC
Labels: enhancement, language, toml
