### ISSUE TITLE
Show errors in scrollbar

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#6898] opened 2024-01-27 22:05 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

A red tick in the scrollbar area allows for quick awareness and navigation to a new error.

**Comment by jansol** [comment] 2024-01-27 22:15
also known as #4866

**Comment by diocletiann** [comment] 2024-01-27 22:18
> also known as #4866

Sorry, I searched for errors vs diag.

**Comment by jansol** [comment] 2024-01-27 22:32
No problem, the search can be very picky about the exact wording. Anyway, LSP diagnostics include errors so I think this can be closed as a duplicate of the older issue?

**Closed** 2024-01-27 22:37 UTC
Labels: enhancement, triage, admin read
