### ISSUE TITLE
Sign in with GitLab for collaborative editing

### ISSUE THREAD

**Issue by Zipdox2** [zed-industries/zed#14270] opened 2024-07-11 21:53 UTC
### Check for existing issues

- [x] Completed

### Describe the feature

Currently it's only possible to sign in with GitHub for collaborative editing. I would like to be able to sign in with GitLab.

**Comment by SomeoneToIgnore** [comment] 2024-07-11 21:58
Duplicate of https://github.com/zed-industries/zed/issues/13296

**Closed by SomeoneToIgnore** 2024-07-11 21:58 UTC
Labels: enhancement, triage, admin read

**Comment by samstride** [comment] 2024-07-11 22:14
@SomeoneToIgnore , so signing in with Gitlab, Gittea or another auth provider will never be supported?

**Comment by SomeoneToIgnore** [comment] 2024-07-11 22:23
This is an odd sentence, I have not stated anything like that.

**Comment by samstride** [comment] 2024-07-11 22:42
The reason I ask is because the issue was closed with a `not planned` label.

**Comment by SomeoneToIgnore** [comment] 2024-07-11 22:48
Yes, with the words

> Duplicate of 

That did not say "will never do" and had left https://github.com/zed-industries/zed/issues/13296 open.
I got the impression, that issue requests the same?


There's not that many options I can use when closing the issue so I've picked the most appropriate 

<img width="363" alt="image" src="https://github.com/user-attachments/assets/710ffa79-6de6-406a-8dc6-ab5aafa7bd65">

**Comment by samstride** [comment] 2024-07-11 23:22
Ahhh, I see. Got it. Thanks for clarifying.

**Comment by Zipdox2** [comment] 2024-07-12 01:57
The other issue wasn't clear in the use so I thought I should open another issue. Never mind.
