### ISSUE TITLE
Add debugging with dbgp protocol, a common debugging protocol ... https://xdebug.org/docs/dbgp 

### ISSUE THREAD

**Issue by davidbuzz** [zed-industries/zed#9480] opened 2024-03-18 05:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

https://xdebug.org/docs/step_debug#clients
it works with Eclipse,NetBeans,PhpStorm,VSCode,VIM,Sublime, etc and for Zed to replace vscode for me, its an essential. :-)

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/174009/0f838963-a710-4312-ab5e-6727c97ae4fa)
Xdebug uses this protocol for debugging php apps fopr example, and as a comparison, in vscode I have a configuration that looks like this: 
![image](https://github.com/zed-industries/zed/assets/174009/43c535f4-8230-4da1-955c-925b5a6e907c)

**Comment by davidbuzz** [comment] 2024-03-18 06:06
https://xdebug.org/docs/step_debug
xdebug and the dbgp protocol are pretty much inseparable, so its made for people who edit php files, and zed is an editor that edits php files.  :)

**Comment by davidbuzz** [comment] 2024-03-18 06:14
there's a more specific 'debug all the things' ticket at https://github.com/zed-industries/zed/issues/5065, but no-one there mentioned PHP/dbgp specifically, just noting the similarities.

**Comment by Moshyfawn** [comment] 2024-03-19 18:09
I believe this can be merged with #5307 for DAP support, but feel free to state otherwise. Be sure to +👍 and add any additional information you think it's missing.

Duplicate of
- #5307

**Closed by Moshyfawn** 2024-03-19 18:09 UTC
Labels: enhancement, triage, admin read
