### ISSUE TITLE
Missing field in themes JSON Schema

### ISSUE THREAD

**Issue by bobuk** [zed-industries/zed#21335] opened 2024-11-29 15:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

[Zed's json schema said](https://zed.dev/schema/themes/v0.1.0.json) that there's only three properties in `HighlightStyleContent`: `color`, `font_style` and `font_weight`. [in the code](https://github.com/zed-industries/zed/blob/69c761f5a5e8a33e86966fa59d2a58622b5cda62/crates/theme/src/schema.rs#L1362)  there's also a `background_color` that is really important for nice themes like [FlatWhite](https://github.com/biletskyy/flatwhite-syntax/issues/37).

### Environment

Zed: v0.164.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-12-02 22:52
Duplicate of: 
- https://github.com/zed-industries/zed/issues/12319

**Closed by notpeter** 2024-12-02 22:52 UTC
Labels: bug, triage, admin read
