### ISSUE TITLE
Eslint not working and doesn't show errors

### ISSUE THREAD

**Issue by OverVlad** [zed-industries/zed#7650] opened 2024-02-10 08:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't see any eslint diagnostics issues.

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Logs from `cat ~/Library/Logs/Zed/Zed.log`
```
{
  "scope": "local",
  "uri": "file:////PaymentMethodsList.tsx",
  "libraryPath": "/Users/uladzislauramanovich/Development/brand-app/node_modules/eslint/lib/api.js"
}
2024-02-10T09:12:18+01:00 [INFO] 18 unhandled notification eslint/confirmESLintExecution:
{
  "scope": "local",
  "uri": "file:///Player.tsx",
  "libraryPath": "/Users/uladzislauramanovich/Development/brand-app/node_modules/eslint/lib/api.js"
}
2024-02-10T09:12:20+01:00 [INFO] Node runtime install_if_needed
2024-02-10T09:12:22+01:00 [INFO] Node runtime install_if_needed
2024-02-10T09:12:23+01:00 [WARN] timed out waiting for formatting
2024-02-10T09:13:17+01:00 [ERROR] crates/gpui/src/window.rs:404: window not found
2024-02-10T09:13:17+01:00 [ERROR] crates/lsp/src/lsp.rs:624: oneshot canceled
2024-02-10T09:13:17+01:00 [ERROR] crates/lsp/src/lsp.rs:624: oneshot canceled
2024-02-10T09:13:17+01:00 [ERROR] crates/lsp/src/lsp.rs:624: oneshot canceled
2024-02-10T09:13:17+01:00 [ERROR] crates/lsp/src/lsp.rs:624: oneshot canceled
2024-02-10T09:15:06+01:00 [INFO] build git repository ".git"
2024-02-10T09:15:06+01:00 [INFO] starting language server "typescript-language-server", path: "/Users/uladzislauramanovich/Development/brand-app", id: 21
2024-02-10T09:15:06+01:00 [INFO] starting language server "eslint", path: "/Users/uladzislauramanovich/Development/brand-app", id: 22
2024-02-10T09:15:06+01:00 [INFO] 22 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "ESLint server running in node v18.15.0"
}
2024-02-10T09:15:06+01:00 [INFO] 21 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Using Typescript version (user-setting) 5.3.2 from path \"/Users/uladzislauramanovich/Development/brand-app/node_modules/typescript/lib/tsserver.js\""
}
2024-02-10T09:15:06+01:00 [INFO] 21 unhandled notification $/typescriptVersion:
{
  "version": "5.3.2",
  "source": "user-setting"
}
2024-02-10T09:15:06+01:00 [INFO] 22 unhandled notification eslint/confirmESLintExecution:
{
  "scope": "local",
  "uri": "file:///Users/uladzislauramanovich/Development/brand-app/api/storyblok.ts",
  "libraryPath": "/Users/uladzislauramanovich/Development/brand-app/node_modules/eslint/lib/api.js"
}
2024-02-10T09:15:06+01:00 [INFO] 22 unhandled notification eslint/confirmESLintExecution:
{
  "scope": "local",
  "uri": "file:///Users/uladzislauramanovich/Development/brand-app/types/api/storyblok/paymentMethods.ts",
  "libraryPath": "/Users/uladzislauramanovich/Development/brand-app/node_modules/eslint/lib/api.js"
}
```

**Comment by vaidotasp** [comment] 2024-02-10 12:34
Same issue here, tried multiple repos for eslint + typescript combo. Yet none works to show eslint diagnostics, tried on latest Zed (0.121.7) and Zed Preview (0.122.2).

**Comment by vaidotasp** [comment] 2024-02-12 22:40
> Looking at [some screenshots](https://github.com/zed-industries/zed/issues/4743), it looks like Zed supports eslint? But I can't get it working, also there is 0 option to configure it or troubleshoot it. How to get eslint working?

I believe it used to work, most of the config problems were to do with eslint --fix options and how it integrates with prettier fix on save. I think this is new-ish problem with Eslint LSP server not producing diagnostics in Zed at all.

**Comment by N8th8n8el** [comment] 2024-02-17 09:38
Investigated this a bit. What I found:
- The eslint LS starts correctly and sends a `eslint/confirmESLintExecution` afterwards.
- The client sends `didChange` and `didSave` to the LS as expected.
- Changing the `.eslintrc.js` file doesn't trigger the LS to do anything.

**Comment by merisbahti** [comment] 2024-02-22 09:16
Any ideas for a workaround?

**Comment by SomeoneToIgnore** [comment] 2024-02-22 14:33
Apologies for the breakage, https://github.com/zed-industries/zed/pull/8197 fixes that and will be released as a patch to both Preview and Stable in a couple of hours today.

**Closed** 2024-02-22 14:33 UTC
Labels: defect, typescript, javascript, language, eslint, tooling

**Comment by SomeoneToIgnore** [comment] 2024-02-22 15:56
Zed 0.123.3 and Zed Preview 0.124.1 now have the fix.

Please note that current eslint support is very sketchy still and will silently fail due to npm dependencies not installed.
But not it is able to show something when everything is set up in the project:
![image](https://github.com/zed-industries/zed/assets/2690773/8baaa049-1bad-42d7-8ea6-2fe29f9f3af5)

New versions are supposed to download eslint of version `2.2.20-Insider` and one way to ensure that the new version should work is to check the `~/Library/Application Support/Zed/languages/eslint/vscode-eslint-release` directory after launching the fixed version, opening the file in the repo with eslint set-up and installed and waiting for the new language server downloaded.

**Comment by anton-patrushev** [comment] 2024-03-11 18:15
I still have that issue and don't see any eslint warning or errors in editor

I remember it was working for me a week ago or something

**Comment by hnbnh** [comment] 2024-03-12 00:34
Same here, I'm using the latest version `0.125.3`, only tsserver error shows up.

@SomeoneToIgnore Could you please have a look?

**Comment by SomeoneToIgnore** [comment] 2024-03-12 10:01
Thanks to Thorsten, it is tracked and being fixed in https://github.com/zed-industries/zed/issues/9213

**Comment by anton-patrushev** [comment] 2024-03-12 11:19
thanks @SomeoneToIgnore , I put few comments into #9213 about release timeline
would be great if you could somehow impact that timeline so the fix would land on a stable channel asap

**Comment by mrnugget** [comment] 2024-03-12 12:19
Fix is now also in Stable: Now also in stable: https://github.com/zed-industries/zed/releases/tag/v0.125.4

**Comment by fazulk** [comment] 2024-03-15 06:42
Running `0.126.2` and getting the same issue described above.

**Comment by mrnugget** [comment] 2024-03-15 08:57
@fazulk can you expand a bit and explain what exactly you're seeing or not seeing and how to reproduce?

**Comment by fazulk** [comment] 2024-03-15 16:17
@mrnugget this could be related to using a flat config. Trying to rule that out first. Commented here, with some details of the configuration: https://github.com/zed-industries/zed/pull/8109

**Comment by prbxr** [comment] 2024-09-29 11:03
not working for me
