### ISSUE TITLE
@ symbol can't be inserted in certain keyboard layouts

### ISSUE THREAD

**Issue by dontwanttothink** [zed-industries/zed#19997] opened 2024-10-30 23:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

By default, `opt-q` is set as the key bind for `editor::Rewrap`. Unfortunately, that's also the keyboard combination used to type an @ symbol in various keyboard layouts, including Spanish (Latin America).

Performing the key combination does not insert the @ character. Unsetting the key bind in your own user key binds file does not restore functionality.

### Environment

Zed: v0.160.0 (Zed Preview)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by overjt** [comment] 2024-10-31 15:04
you can disable the opt-q keyboard shortcut by adding the following configuration to your keymap.json file:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "opt-q": null
    }
  }
]
```

This will disable the opt-q shortcut that's interfering with typing the @ symbol on your Spanish (Latin America) keyboard layout. You can access the keymap.json file by pressing ⌘ + K, ⌘ + S or by navigating to Zed > Settings > Open Key Bindings.

**Comment by JosephTLyons** [comment] 2024-11-01 21:06
Hey @dontwanttothink,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/18104

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, feel free to leave a comment here explaining the difference and we will reopen this issue.

**Closed by JosephTLyons** 2024-11-01 21:06 UTC
Labels: defect, editor, internationalization, keymap / key binding
