### ISSUE TITLE
failed to run custom build command for `live_kit_server v0.1.0

### ISSUE THREAD

**Issue by aohanhongzhi** [zed-industries/zed#11539] opened 2024-05-08 08:42 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

windows10
```rust
PS C:\Users\Eric\Project\Rust\zed> cargo build --release
warning: `C:\Users\Eric\.cargo\config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `C:\Users\Eric\.cargo\config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling gpui v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\gpui)
   Compiling rope v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\rope)
   Compiling rpc v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\rpc)
   Compiling node_runtime v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\node_runtime)
   Compiling isahc v1.7.2
   Compiling live_kit_server v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\live_kit_server)
   Compiling media v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\media)
   Compiling prost-types v0.9.0
   Compiling live_kit_client v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\live_kit_client)
   Compiling thread_local v1.1.7
   Compiling hound v3.5.0
   Compiling nanoid v0.4.0
error: failed to run custom build command for `live_kit_server v0.1.0 (C:\Users\Eric\Project\Rust\zed\crates\live_kit_server)`

Caused by:
  process didn't exit successfully: `C:\Users\Eric\Project\Rust\zed\target\release\build\live_kit_server-cb58d8416c80c087\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at crates\live_kit_server\build.rs:5:10:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: protocol/livekit_room.proto: No such file or directory\r\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

### Environment

windows10

**Comment by SomeoneToIgnore** [comment] 2024-05-08 09:50
Looks exactly like https://github.com/zed-industries/zed/issues/9240 

Have you read https://github.com/zed-industries/zed/blob/63a5f46df4a694cf5ccfea43628a2ac8a4f053da/docs/src/development/windows.md and run the same command it says in https://github.com/zed-industries/zed/blob/63a5f46df4a694cf5ccfea43628a2ac8a4f053da/docs/src/development/windows.md#repository ?

`git submodule update --init --recursive`

**Comment by SomeoneToIgnore** [comment] 2024-05-09 07:56
Closing this as most probably a submodule issue.
Feel free to post more details if it's not.

**Closed by SomeoneToIgnore** 2024-05-09 07:56 UTC
Labels: defect, needs info / awaiting response, windows, admin read

**Comment by victor141516** [comment] 2024-07-06 10:44
I had this same error. The cause was that my user directory has a tilde. I moved the `CARGO_HOME` to `C:\.cargo` and worked fine.
It's amazing we're in 2024 and Windows still can't handle non-ascii

**Comment by morags** [comment] 2025-01-18 00:28
Can confirm the same problem as @victor141516's, but instead of moving I just created a symlink and pointed `CARGO_HOME` to it.
