### ISSUE TITLE
On open new window or last opened folder the window appears top right corner rest all blank

### ISSUE THREAD

**Issue by PrashantSakre** [zed-industries/zed#13663] opened 2024-06-29 06:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Strange behaviour as bellow image on open last opened folder or new window. 

The issue solves after I resize the window it fixes it self to show properly.

### Environment

macOS Monterey - Version 12.7.5

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-06-29 at 11 49 01](https://github.com/zed-industries/zed/assets/42613882/fbc1b4da-ae1c-4206-b6b9-fd74995893ab)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by PrashantSakre** [comment] 2024-07-01 09:13
Update: I think the issue comes when monitor screen resolution is ‎1366 x 768 pixels, when I connected to 1440p resolution monitor worked fine.

**Comment by notpeter** [comment] 2024-07-01 17:29
Duplicate of: 
- https://github.com/zed-industries/zed/issues/13672

**Closed by notpeter** 2024-07-01 17:29 UTC
Labels: defect, triage, admin read
