### ISSUE TITLE
cannot open filename contains special char

### ISSUE THREAD

**Issue by futurist** [zed-industries/zed#19000] opened 2024-10-10 03:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

cannot open below filename:
```
idea(1).log
```

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 14.5.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

run `zed idea\(1\).log` will show below:

![image](https://github.com/user-attachments/assets/b8a82742-4282-413f-84fd-96a35a377802)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-10 06:22
Duplicate of https://github.com/zed-industries/zed/issues/18268

**Closed by SomeoneToIgnore** 2024-10-10 06:22 UTC
Labels: defect, triage, admin read
