### ISSUE TITLE
Delete key does not work in the editor

### ISSUE THREAD

**Issue by ErrolFernandes** [zed-industries/zed#11713] opened 2024-05-11 21:37 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the editor when I press the delete key it does not delete anything but works in terminal.
Also works with option key which deleted complete words

### Environment

MacOS latest

**Comment by Moshyfawn** [comment] 2024-05-12 00:19
Do you per chance have `"vim_mode": true` in your `settings.json` file?

**Comment by ErrolFernandes** [comment] 2024-05-12 01:22
Yes

**Comment by Moshyfawn** [comment] 2024-05-12 01:27
So you are in Vim `NORMAL` mode, where you can jump around in the code, but you can't edit it - hence the delete button doesn't work. When you press `i`, you are in `INSERT` mode, where you can edit the text.

If you accidentally switched on the Vim mode, you can switch it off by setting `"vim_mode": false` or by deleting the line completely.

**Comment by ErrolFernandes** [comment] 2024-05-12 03:02
Oh thankyou very much.

**Comment by Moshyfawn** [comment] 2024-05-12 03:07
Np! I'm going to close this issue because it's working as intended, but feel free to ask if you still have any questions.

**Closed** 2024-05-12 03:07 UTC
Labels: defect, needs info / awaiting response, editor, admin read
