### ISSUE TITLE
Open Binary Files

### ISSUE THREAD

**Issue by shade** [zed-industries/zed#11704] opened 2024-05-11 16:28 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be really nice to be able to open large binary files, VSCode supports this out of the box. At the moment Zed complains about files lacking UTF-8
<img width="259" alt="Screenshot 2024-05-11 at 9 26 25 AM" src="https://github.com/zed-industries/zed/assets/7436560/9a087ed7-5c1c-4cf0-b35c-ea6eb6d3434d">

### If applicable, add mockups / screenshots to help present your vision of the feature

This is what I would expect to see:

<img width="640" alt="Screenshot 2024-05-11 at 9 27 35 AM" src="https://github.com/zed-industries/zed/assets/7436560/aab2c54e-2adc-4d8f-aaba-4a3c21c36dc8">

**Comment by Moshyfawn** [comment] 2024-05-11 17:07
This issue appears to be a duplicate of:
- #5348

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

Related:
- #11331

**Closed by Moshyfawn** 2024-05-11 17:07 UTC
Labels: enhancement, triage, admin read

**Comment by shade** [comment] 2024-05-11 23:20
Great, that I'm not the only one, thanks!
