### ISSUE TITLE
Profile favicons on inline git blame don't show up

### ISSUE THREAD

**Issue by dimeeentor** [zed-industries/zed#11500] opened 2024-05-07 15:49 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

1. Toggle on "Inline Git blame"
2. Hover over inline hint until the popup appears

<img width="470" alt="Screenshot 2024-05-07 at 17 37 27" src="https://github.com/zed-industries/zed/assets/32683179/7b6b7293-5e6c-497b-94be-7f8b9beb114e">

### Environment

Zed: v0.134.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

When I was using stable version and when this feature was introduced it worked fine, then I've switched to the preview one and it doesn't work no more.

**Comment by Moshyfawn** [comment] 2024-05-08 02:21
I can't seem to reproduce the problem on the same version as you. Are there any related logs generated that you can find by selecting `zed: open log` in the command palette after trying to view the popovver with the unloaded git avatar?

**Comment by dimeeentor** [comment] 2024-05-08 07:13
Seems like nothing related to unloaded git avatars, however when I toggle on and off inline git blame and git blame, then `null` can appear in the logs.

```
2024-05-08T09:04:01+02:00 [INFO] Initializing default prettier with plugins {}
2024-05-08T09:04:01+02:00 [INFO] starting language servers for CSS: vscode-css-language-server, tailwindcss-language-server
2024-05-08T09:04:01+02:00 [INFO] Language server with id 1 sent unhandled notification workspace/diagnostic/refresh:
null
2024-05-08T09:05:31+02:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-05-08T09:05:32+02:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-05-08T09:05:33+02:00 [ERROR] unexpected item event after pane was dropped
2024-05-08T09:05:33+02:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-05-08T09:05:33+02:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-05-08T09:05:41+02:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-05-08T09:05:41+02:00 [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
2024-05-08T09:05:53+02:00 [INFO] Initializing default prettier with plugins {}
2024-05-08T09:05:53+02:00 [INFO] starting language servers for CSS: vscode-css-language-server, tailwindcss-language-server
2024-05-08T09:05:53+02:00 [INFO] Initializing default prettier with plugins {}
2024-05-08T09:05:53+02:00 [INFO] starting language servers for CSS: vscode-css-language-server, tailwindcss-language-server
2024-05-08T09:05:53+02:00 [INFO] Language server with id 1 sent unhandled notification workspace/diagnostic/refresh:
null
```

**Comment by maxdeviant** [comment] 2024-05-08 12:48
@dimeeentor Are you seeing this in a public or private repo?

**Comment by dimeeentor** [comment] 2024-05-08 14:30
A private one. I guess important thing, is that it worked when I was using Zed stable.

**Comment by mrnugget** [comment] 2024-05-14 09:05
We can't fetch commit information from private repositories without authentication. GitHub's API doesn't allow us to fetch the commit author without having access to the repository.

We need to talk to the GitHub API because just by pure git information, we can't get the avatar of the author associated with the commit. (We'd need to use something like gravatar for that, not sure if they're still around)

But I did put an escape hatch in: if you launch Zed from the CLI and `GITHUB_TOKEN` is set, then that's used to talk to GitHub. So it's possible that this is what was happening when using Zed stable.

I'm going to close this, because right now it's not supported to get the avatar from a private repository. Happy to reopen if my assessment here is wrong.

**Closed by mrnugget** 2024-05-14 09:05 UTC
Labels: defect, needs info / awaiting response, editor, git, git blame
