### ISSUE TITLE
Issue with showing folders with dots

### ISSUE THREAD

**Issue by mariuso** [zed-industries/zed#13242] opened 2024-06-18 22:00 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Have a folder structure with dots, like this (versioned numbered in this case):

<img width="323" alt="image" src="https://github.com/zed-industries/zed/assets/2239962/9a4e08e8-8418-47cf-a9f5-a748c1eaa724">

Open all folders in ZED:
<img width="287" alt="image" src="https://github.com/zed-industries/zed/assets/2239962/116f3605-ae8e-458b-821e-eb1bb3d3fe74">

When opening the folders it shows all folders/files combined in the last folder

Renaming the folders to use i.e. hyphen (-), rather than dots (.) solves the issue

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-06-19 10:34
Thanks, this is a duplicate of https://github.com/zed-industries/zed/issues/12470

**Closed by SomeoneToIgnore** 2024-06-19 10:34 UTC
Labels: defect, triage, admin read
