### ISSUE TITLE
Allow a way to apply color to a regex pattern

### ISSUE THREAD

**Issue by johnfercher** [zed-industries/zed#18524] opened 2024-09-30 04:03 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I want to change de color of some items, which I could not change based on examples.

![Screenshot from 2024-09-30 00-51-37](https://github.com/user-attachments/assets/6b9290c8-0bdd-4ac1-a623-5dee680c1ee6)

1. `package main` : I want to change the **main** color, in this scenario that is a package. (Kinda a namespace in other languages than Go)
2. `http2 "import"`: I want to change the **http2** color, in this scenario that is an alias.
3. `context.TODO()`, `os.Args` or `anything.Something`:  when there is a scenario where I have `anything.Something`, I would like to be able to change the `anything` color. This kinda based on a bunch of themes from other APIs of Golang.
4. `if err != nil`: I would like to be able to change the color of some keyworkds. Kinda, `nil = purple`, `string == green` and etc.

**Comment by jansol** [comment] 2024-09-30 11:56
You need to specify a tree-sitter query in `highlights.scm` for the language in question. AFAIK you can specify any queries you want there, and the syntax section of your theme can specify styling for any custom queries you want by adding a style item whose name matches the one given in `highlights.scm`.

**Comment by demiurg** [comment] 2024-10-03 12:02
What is `highlights.scm`, where does it live? Is it a file that can be modified by a user? I found a reference in https://zed.dev/docs/extensions/languages, however, it is implied there, that this is something a developer would modify, having to build some Rust code. This is much different than a user feature request.

Am I missing anything? I would love to be able to modify a theme to make it a bit closer to ST3, but doesn't seem possible for me, if I do't want time to learn Rust.

**Comment by jansol** [comment] 2024-10-03 12:49
`highlights.scm` is a data file that's part of Zed's language support and does not by itself require writing or building Rust code (essentially it defines how Zed should use the parsed syntax tree from tree-sitter). The one for Go is [built into Zed though](https://github.com/zed-industries/zed/blob/main/crates/languages/src/go/highlights.scm), so changing that one specifically does require rebuilding Zed itself.

Essentially what `highlights.scm` does is define the semantic patterns that can be styled in a theme. This isn't really meant to be something end users regularly do, that should be done "upstream" in Zed. Fortunately it shouldn't be a controversial change as long as it makes sense semantically.

Like in your first example the pattern would require adding a highlight for packages/modules/namespaces. This shouldn't be a controversial change in any way since that's a thing that other languages already have highlights for.

Specifying a style for it in the theme OTOH is up to theme designers (and end users via theme overrides and manually added themes).

Also, if you only care specifically about Go here, I would update the issue title to request improvements to Go highlighting support rather than regular expression patterns. That would be a much easier and less controversial change than adding a whole separate highlighting system based on regular expressions, so it would be more likely to get approval from the dev team and faster to actually implement.

**Comment by demiurg** [comment] 2024-10-03 13:45
Thanks for the clarification. I am not the original issue author, I am personally interested in extending Python theme colors to import statements, constructors, docstrings, decorators, etc, which are currently not styled in any themes. I was searching the issues and found this, so I commented :)

I have a super easy time adding styles to a theme, but I'm having a really hard time finding the names for things. I don't have a clear idea why that is, is it that there is no name, and I have to figure out how to create the thing by regex, or is it that I have to understand how tree-sitter works and language extensions work? It sounds like a little bit of both, but some things are definitely language specific. Some are not, though. Perhaps the Python parsing is lacking, for example I have a style for `constructor` which I saw is referenced in some themes, but it has no effect on`__init__`. I'm happy to make a new issue for Python specifically, or I'm happy to figure out how to use regex :)

**Comment by JosephTLyons** [comment] 2024-10-03 15:25
Hey @johnfercher,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4610

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-10-03 15:25 UTC
Labels: enhancement, editor, setting
