### ISSUE TITLE
Fallback font family for CJK (non-ascii)

### ISSUE THREAD

**Issue by mkismy** [zed-industries/zed#8971] opened 2024-03-06 22:53 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

The `buffer_font_family` setting currently accept only 1 font but this is not enough for CJK so we need Zed to accept multiple fonts and fallback to the appropriate one.

Hardly any font "better for programming" include CJK characters, like the ones [listed in this article](https://kinsta.com/blog/best-programming-fonts/) which I randomly picked from google, so Zed is using an unknown system font.

### If applicable, add mockups / screenshots to help present your vision of the feature

Font settings in VSCode accepting multiple fonts and fallback to the appropriate font.
ASCII character is shown in `iA Writer Mono S` and Japanese character in `Noto Sans CJK JP`

![Screenshot 2024-03-07 at 7 37 41](https://github.com/zed-industries/zed/assets/8445575/e6428fbe-3276-4d66-a530-6ddd9cd6cb46)

**Comment by 0x2CA** [comment] 2024-03-07 01:42
duplicate #5180

**Comment by Moshyfawn** [comment] 2024-03-07 04:08
I'm going to close this one in favour of the other. Be sure to +👍 the other topic and add any missing information.

Duplicate of
- #5180

**Comment by Moshyfawn** [comment] 2024-03-07 04:09
I'm going to close this one in favour of the other. Be sure to +👍 the other topic and add any missing information.

Duplicate of
- #5180

**Closed by Moshyfawn** 2024-03-07 04:09 UTC
Labels: enhancement, triage, admin read
