### ISSUE TITLE
Git ignored file (.env) not appearing on search project files 

### ISSUE THREAD

**Issue by Dinuda** [zed-industries/zed#7067] opened 2024-01-30 10:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When searching for ignored files by git such as `.env` file. There must be expections for important files like this(like in vscode). I do understand the reason for not including ignored files, but atleast if there is a setting to change this

### Environment

node v21.10

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment] 2024-01-30 11:40
Duplicate of https://github.com/zed-industries/zed/issues/4745

**Closed by SomeoneToIgnore** 2024-01-30 11:40 UTC
Labels: defect, triage, admin read
