### ISSUE TITLE
Setting tab_size above 16 causes editor to crash

### ISSUE THREAD

**Issue by lillianrubyrose** [zed-industries/zed#14809] opened 2024-07-19 13:19 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Set "tab_size" to anything above 16.

### Environment

Zed: v0.145.0 (Zed Preview)
OS: Linux Wayland arch unknown
Memory: 30.5 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-19T09:13:33.120790545-04:00 [ERROR] {
  "thread": "<unnamed>",
  "payload": "byte index 69 is out of bounds of `                `",
  "location_data": {
    "file": "crates/editor/src/display_map/tab_map.rs",
    "line": 543
  },
  "backtrace": [],
  "app_version": "0.145.0",
  "release_channel": "Zed Preview",
  "os_name": "Linux Wayland",
  "os_version": "arch unknown",
  "architecture": "x86_64",
  "panicked_on": 1721394813120,
  "installation_id": "bd388363-4955-4421-9138-5b2ee8a76d6e",
  "session_id": "42f8b191-08fa-4e0b-b454-9614009643f4"
}
</pre></details>

**Comment by jadijadi** [comment] 2024-07-24 14:52
Tried on Mac OSX & Debian x64 Wayland and were not able to reproduce. 

Configuring `tab_size` to `25` in settings does not crashes the Zed & changes the tab size to 25 correctly. 

Zed Version: 0.146.0 (main)

**Comment by jadijadi** [comment] 2024-07-25 09:01
Thanks @lilyrrose for the detailed report, got it and I think I know where the root cause is. working on it.

**Comment by jadijadi** [comment] 2024-07-25 15:10
The problem is in `src/display_map/tab_map.rs` where we have on line 542:

```
                        return Some(Chunk {
                            text: &SPACES[..len as usize],
                            is_tab: true,
                            ..self.chunk.clone()
                        });
```

This SPACE is defined on line 458:

```
// Handles a tab width <= 16
const SPACES: &str = "                ";
```


1. setting text to something like `text: &" ".repeat(len as usize)` looks great but I did not figure out how to do it without referencing a temporary value. Any suggestions?
2. Another method is increasing 16 to something like 32 and mentioning this limitation in docs and checking `tab_size` for that. 

The solution 2 is not ideal but will prevent the current crash. 

Any suggestions?

**Comment by notpeter** [comment] 2024-11-26 18:26
I was trying to see if this was an issue in the current release of Zed, but didn't have any luck, including adding `hard_tabs` to `rustfmt.toml`.  Anything tab_size >= 16 (24, 32, etc) appears to only display tabs as 16characters wide which while technically a bug, is not an unreasonable limit.

I'm going to close as I think this may have been unintentionally fixed in the last six months.  If anyone has steps to reproduce with a current Zed, I'm happy to reopen.

Thanks for reporting all!

**Closed by notpeter** 2024-11-26 18:26 UTC
Labels: bug, panic / crash, editor, linux, setting, linux-wayland
