### ISSUE TITLE
Linux. Crash when typing "--da" after having another CSS variable beginning with the same name

### ISSUE THREAD

**Issue by SyntheticBird45** [zed-industries/zed#12022] opened 2024-05-18 21:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've a CSS file with a variable called `--dark-bg-0`. When I try to type `--dark-bg-1`, Zed crashes at `--da`. 
possibly related to https://github.com/zed-industries/zed/issues/11703

https://github.com/zed-industries/zed/assets/118022351/c1c34b59-d3ba-419e-bfc6-d93473eb1eed

### Environment

Zed: v1.0.0 (Zed)
OS: Linux 1.0.0
Memory: 15.5 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

It seems like at each crash, the logs aren't synced to disk. There are no lines of the Zed instance I started.

**Comment by apricotbucket28** [comment] 2024-05-18 22:27
Duplicate of https://github.com/zed-industries/zed/issues/11703
Btw, you seem to be running an old commit (no window decorations)

**Comment by SyntheticBird45** [comment] 2024-05-18 22:38
> Btw, you seem to be running an old commit (no window decorations)

I literally just installed v0.135.2 from AUR 3 hours ago. I must admit its weird since I saw the Wayland drag and resize PR got merged but haven't seen it in the changelog. Is it pre-release?

**Comment by apricotbucket28** [comment] 2024-05-18 22:43
> > Btw, you seem to be running an old commit (no window decorations)
> 
> I literally just installed v0.135.2 from AUR 3 hours ago. I must admit its weird since I saw the Wayland drag and resize PR got merged but haven't seen it in the changelog. Is it pre-release?

Oh, that's the latest "stable" release. The newest changes are on the master branch. I'd suggest [compiling it](https://github.com/zed-industries/zed/blob/main/docs/src/development/linux.md) yourself instead of using the AUR, it's probably more stable to use the master branch on Linux anyway :laughing:

**Comment by SyntheticBird45** [comment] 2024-05-18 22:44
> it's probably more stable to use the master branch on Linux anyway

got it. will do 👍

**Comment by SyntheticBird45** [comment] 2024-05-30 17:10
any news ? bug still present in newer version

**Comment by apricotbucket28** [comment] 2024-06-03 18:31
Fixed by https://github.com/zed-industries/zed/pull/12587

**Closed** 2024-06-03 18:31 UTC
Labels: defect, panic / crash, linux, css, language
