### ISSUE TITLE
Ruby auto indentation is inconsistent

### ISSUE THREAD

**Issue by willcosgrove** [zed-industries/zed#4479] opened 2023-09-13 16:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run into indentation issues when writing Ruby in Zed on a consistent basis. Most commonly, I encounter it when I'm in an `if..end` block. But I also notice it when I'm creating a new ruby file and there isn't a full module/class structure defined yet.

From an empty ruby file, define a method and insert a new line. I would expect the cursor to be indented one level, but it is at the top level.

https://github.com/zed-industries/community/assets/77887/5d7fa8cd-7d1b-49c4-a63e-18e3a5323c31

From an empty ruby file, begin an `if` block and insert a new line. I would again expect the cursor to be indented one level, but it is not. And neither are subsequent lines.

https://github.com/zed-industries/community/assets/77887/1da5c63f-e998-4d1a-a6af-8ba5830c610f

This last example has a more typical file structure, the code is written inside a complete class definition. Define a method, insert new line, it is correctly indented an additional level. Write an if condition and insert a new line and the indentation does not change. I would expect it to be indented an additional level. You can also see that the editors understanding of the file hierarchy breaks as soon as the `if` is written.

https://github.com/zed-industries/community/assets/77887/e157f707-6c73-4e1d-90a4-fc92a8b32ac8

Thanks, let me know if I can provide any more info!

PS: This seems related to zed-industries/zed#5116 but that issue seemed stale. I could not reproduce the bug in that issue's example so it's possible it was fixed but never closed.

### Environment

Zed: v0.103.1 (preview)
OS: macOS 13.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by richkilmer** [comment] 2024-04-01 02:58
I am going to comment on in this that this issue is THE worst part of my daily use of Zed which I have not been doing for the last 4-5 months. When you type in: **if condition** then press enter and type in **else** it de-indents it. I constantly have to fight this autoformatting issue every time. Its been such a common thing my fingers automatically fix the incorrect formatting but it would be great if this could be addressed.  if / else / end should all be at the same indent level.  The line after if should be indented and its not.

**Comment by joeldrapper** [comment] 2024-06-06 10:53
@richkilmer the issue you mentioned seems to be fixed now, but the other inconsistencies are still present.


https://github.com/zed-industries/zed/assets/246692/07d43e75-a19f-43c5-8f1a-3472d69a3470

**Comment by notpeter** [comment] 2024-11-04 00:26
Ruby has moved to the [zed-extensions/ruby](https://github.com/zed-extensions/ruby) repo.  If you are still experiencing this, please open a new issue there with steps to reproduce.

**Closed by notpeter** 2024-11-04 00:26 UTC
Labels: defect, ruby, language
