### ISSUE TITLE
ctrl + scroll wheel up and down should enlargen or shrink text

### ISSUE THREAD

**Issue by RustoMCSpit** [zed-industries/zed#20835] opened 2024-11-18 20:30 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

in the same way in your browser, you should be able to scroll up and down with ctrl to resize everything

### Environment

Zed: v0.161.2 (Zed)
OS: Linux X11 linuxmint 22
Architecture: x86_64

**Comment by notpeter** [comment] 2024-11-18 20:44
Duplicate of:
- https://github.com/zed-industries/zed/issues/10647

**Closed by notpeter** 2024-11-18 20:44 UTC
Labels: enhancement, triage, admin read
