### ISSUE TITLE
Autocomplete prioritises the less exact match.

### ISSUE THREAD

**Issue by skejeton** [zed-industries/zed#19071] opened 2024-10-11 13:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The problem is provided in the screenshot. It prefers to use `sqFeetToSqMeters` even though the string starts with `sqMet`, so the preferred completion should be `sqMetersToSqFeet`. This might be related to #17277

### Environment

Zed: v0.158.0 (Zed Dev 0a7468c89f6dc72eeb27c0ea1113c95ee100ae2c)
OS: Windows 10.0.19045
Memory: 15.9 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 || Intel Corporation || Intel driver

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/8fd1dbd0-d683-4fa3-802e-0682fe21665e)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-11 18:53
Duplicate of:
- #12698

Please vote 👍 that issue to show your interest and subscribe to get progress updates.
Thanks for reporting.

**Closed by notpeter** 2024-10-11 18:53 UTC
Labels: defect, triage, admin read

**Comment by skejeton** [comment] 2024-10-11 20:38
Thank you. I looked up issues with tags "language server" and couldn't find similar one, so I made a new one.

**Comment by notpeter** [comment] 2024-10-11 20:52
> Thank you. I looked up issues with tags "language server" and couldn't find similar one, so I made a new one.

Add that tag. Thanks for searching first!
