### ISSUE TITLE
Add Language Icon to Extension API

### ISSUE THREAD

**Issue by versecafe** [zed-industries/zed#15784] opened 2024-08-05 03:17 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Allow custom file icons for language extensions, for example the gleam extension should be able to set the icon for `*.gleam` same with zig and `*.zig`, etc as right now it needs a full IDE update to add new icons

> I just want gleam projects to have icons lucy is wonderful

## Allow extensions to turn this:

![image](https://github.com/user-attachments/assets/dde3ad42-46c7-4069-b054-12bb641d64cd)

## Into this:

![image](https://github.com/user-attachments/assets/e64b3478-786b-46ba-9414-3975833fe303)

**Comment by SomeoneToIgnore** [comment] 2024-10-31 17:01
Duplicate of https://github.com/zed-industries/zed/issues/8843

**Closed by SomeoneToIgnore** 2024-10-31 17:01 UTC
Labels: enhancement, design, file icons, extension infrastructure
