### ISSUE TITLE
Cannot format unsaved file

### ISSUE THREAD

**Issue by NicoAdrian** [zed-industries/zed#6989] opened 2024-01-29 14:00 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Open a new window and write a poorly formatted JSON for example.
2) Hit cmd-shit-I to format
3) JSON is not formatted at all

However, if I save the file, the formatting command works

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 13.6.3
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-01-29 22:58
Hey @NicoAdrian,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4529

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-01-29 22:58 UTC
Labels: enhancement, editor, keymap / key binding
