### ISSUE TITLE
Beancount extension fails to load

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#10603] opened 2024-04-16 09:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
2024-04-16T12:31:35+03:00 [INFO] installing extension beancount latest version
2024-04-16T12:31:36+03:00 [INFO] rebuilt extension index in 14.101515ms
2024-04-16T12:31:36+03:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-04-16T12:31:36+03:00 [ERROR] failed to load language Beancount:
Failed to instantiate wasm module: invalid import '_Znwm'
```

### Environment

Zed: v0.131.5 (Zed Preview)
OS: macOS 12.7.4
Memory: 16 GiB
Architecture: x86_64

(First observed on NixOS but looks like it's not a Linux/NixOS problem since it also occurs on macOS)

**Comment by JosephTLyons** [comment] 2024-04-16 15:58
I'm able to reproduce this.

**Comment by JosephTLyons** [comment] 2024-04-16 16:43
v0.0.2 has been published to the extension store and the issue is resolved on my end. I'll close this out - let me know if its busted or not for you.

**Closed** 2024-04-16 16:44 UTC
Labels: defect, extension infrastructure
