### ISSUE TITLE
Add support for LiveKit media streams to Linux

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/zed#14031] opened 2024-07-09 21:32 UTC
So you can unmute and share your screen when collaborating.

**Comment by ConradIrwin** [comment] 2024-07-10 03:54
Duplicate of https://github.com/zed-industries/zed/issues/13714

**Closed by ConradIrwin** 2024-07-10 03:54 UTC
Labels: enhancement, linux, admin read

**Comment by mikayla-maki** [comment] 2024-07-10 03:55
😅 it’s top of mind!
