### ISSUE TITLE
Zoom issue Screen 24'

### ISSUE THREAD

**Issue by Monkey-yk23** [zed-industries/zed#12854] opened 2024-06-10 16:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On my 24' screen if i zoom below a certain rate words start literally disappearing and glitching making impossible to read, need to zoom in again

### Environment

MacBook Pro (Retina, 15-inch, Mid 2014), Big SUR 11.7.10

**Comment by notpeter** [comment] 2024-06-11 12:53
Eeek, that sounds bad.  Can you provide a screen recording (cmd+shift+5 or "New Screen Recording" using QuickTime Player) which demonstrates the issue?

**Comment by notpeter** [comment] 2024-11-05 20:11
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/6853
- Specifically: https://github.com/zed-industries/zed/issues/6853#issuecomment-2181539635

Luckily, your machine has an Intel Iris Pro 5200 and by default Zed will use that instead of the Nvidia GPU which is not fully Metal2 compatible.

Thanks for reporting!

**Closed by notpeter** 2024-11-05 20:11 UTC
Labels: bug, triage, needs info / awaiting response, workspace, editor, admin read
