### ISSUE TITLE
Code Action text overlaps when too long

### ISSUE THREAD

**Issue by ThomasAlban** [zed-industries/zed#8772] opened 2024-03-03 15:45 UTC
![image](https://github.com/zed-industries/zed/assets/98399119/2e20c339-49b7-49c3-b87c-4cc840045f10)

This is in the latest version of Zed

**Comment by Moshyfawn** [comment] 2024-03-03 17:05
Duplicate of #8772

**Comment by Moshyfawn** [comment] 2024-03-03 17:05
Be sure to +👍 the other issue and add any additional information that might be missing from it.

**Closed by Moshyfawn** 2024-03-03 17:05 UTC
