### ISSUE TITLE
Need command to fold all entries in editor

### ISSUE THREAD

**Issue by Cheirnomus** [zed-industries/zed#12508] opened 2024-05-30 23:31 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'm really liking the Zed editor and looking for the essentials that I always use in VSCode. I use VSCode to model big text files that can have many deep fold levels. In VSCode I just go 'Command + K then 0' and all fold levels are folded.

I can not find this super handy feature in Zed. Please add this command, thanks so much!

**Comment by Moshyfawn** [comment] 2024-05-30 23:37
For what it's worth, you could select the whole file `cmd-a` and press `alt-cmd-[` to fold _(all)_ selected ranges.

But there's already a feature request for fold levels / fold all action, so I'll close this issue in favour of the other one. Be sure to +👍 the other thread.

Duplicate of:
- #5142

**Closed by Moshyfawn** 2024-05-30 23:37 UTC
Labels: enhancement, triage, admin read
