### ISSUE TITLE
Images not updating in editor when overwritten

### ISSUE THREAD

**Issue by UshMc** [zed-industries/zed#19770] opened 2024-10-25 23:27 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I create an "image.png" from a python script, I am able to view the image in the editor. However, if I create another image with the same name (eg by running the python script with different inputs) - the editor still displays the old image data. This is happening for both JPGs and pngs. 

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 14.4.0
Memory: 96 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-25 23:29
Duplicate of https://github.com/zed-industries/zed/issues/11529

**Closed by SomeoneToIgnore** 2024-10-25 23:29 UTC
Labels: defect, triage, admin read
