### ISSUE TITLE
Disable auto close for single quotes while commenting

### ISSUE THREAD

**Issue by andrewyur** [zed-industries/zed#20035] opened 2024-10-31 15:13 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I like the auto-close feature, but find it annoying that whenever I am writing a word inside a comment that requires an apostrophe, I have to delete the extra apostrophe it adds. It would probably be easier to disable auto close entirely within comments, but I feel like apostrophes/single quotes are the only ones that make this a problem.

**Comment by SomeoneToIgnore** [comment] 2024-10-31 15:24
What is the language you're dealing with?

**Comment by andrewyur** [comment] 2024-10-31 15:27
Python and Nix are the two languages I have tested it with (both use # for comments)

**Comment by notpeter** [comment] 2024-10-31 16:46
Yeah, it would be neat to support a more granular, comment-aware `use_autoclose`.

- Closing as duplicate of https://github.com/zed-industries/zed/issues/9195
- See also: https://github.com/zed-industries/zed/issues/14372

**Closed by notpeter** 2024-10-31 16:46 UTC
Labels: enhancement, triage, admin read
