### ISSUE TITLE
copilot chat doesn't use chatGPT 4 

### ISSUE THREAD

**Issue by karemkassem** [zed-industries/zed#16053] opened 2024-08-10 11:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the two modes for the new copilot chat ( GPT-4 and GPT-3.5) don't seem to make any difference, I asked both of them which model of gpt they are using and they both replied with GPT-3, even when picking the GPT-4.
I tried the same thing with the same account in vscode and it returned that it uses GPT-4o. ( as seen in the pictures below )
is this a bug? or something that I did wrong? 
anyway I have been using zed ever since its release on linux and it has been amazing. great work.

### Environment

Zed: v0.147.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.1.5-arch1.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot_20240810_141735](https://github.com/user-attachments/assets/f130daed-c520-4551-944c-4a7deba47ab1)
![Screenshot_20240810_141809](https://github.com/user-attachments/assets/bf7e1030-1e63-4020-9d5b-8a6a38c4dce3)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-12 16:01
I can reproduce this with my GitHub account. I also get the following response:
```
I am based on OpenAI's GPT-3 model.
```

**Comment by linuxmobile** [comment] 2024-08-15 19:44
![image](https://github.com/user-attachments/assets/5cacf91c-82a6-4d12-966d-9645890f6560)

same here.

**Comment by aperiogon3141** [comment] 2024-08-17 16:19
yes i am experiencing the same issue

**Comment by Hawkbawk** [comment] 2024-08-19 05:19
I'm not sure just how much I'd trust the model here, as it very well could be hallucinating. If you look through the code, you can see that the GitHub API is indeed being called with different models, and there's not anything else that Zed can do beyond that. A better test would be to see how the different models perform on the same task, as GPT-4 should be significantly better.
Regardless, I've just created a merge request to enable GPT-4o functionality (#16446 ) which I can confirm from my testing is definitely being used. The 128K context window and much faster response time is absolutely wonderful for asking questions in an unfamiliar codebase and confirms the API is working as intended.

**Comment by AidfulAI** [comment] 2024-10-07 23:58
Never trust the output of the model if you ask it about itself. If the system prompt is not updated correctly, you will get wrong information.

To test if you are using GPT-3 or GPT-4 use the following prompt, which is with ~9 out of 10 only correctly solved by GPT-4:
Give me 10 sentences that end with the word "apple"

**Comment by notpeter** [comment] 2024-10-08 01:37
I'm going to go ahead and close this. In the intervening two months I've become much more accustomed to models hallucinating other models as their own name, even when it's explicitly defined in the system prompt.

**Closed by notpeter** 2024-10-08 01:37 UTC
Labels: defect, copilot, ai, assistant
