### ISSUE TITLE
Customisable per window colors

### ISSUE THREAD

**Issue by mocenigo** [zed-industries/zed#19510] opened 2024-10-21 12:34 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I have seen this question on reddit
https://www.reddit.com/r/ZedEditor/comments/1g894mv/local_theme_overrides_support/
and it looks very interesting to me. 
In fact, a local override for the foreground/background colors of title bar and status line would be useful — not necessarily customising the whole theme — because it would allow for a quick identification of project windows.

**Comment by notpeter** [comment] 2024-10-21 16:10
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/13300

**Closed by notpeter** 2024-10-21 16:10 UTC
Labels: enhancement, triage, admin read

**Comment by mocenigo** [comment] 2024-10-21 23:15
> I think this is a duplicate of:
> 
> * [Per-project themes (multiple active themes) #13300](https://github.com/zed-industries/zed/issues/13300)

Yes, provided one can either define a theme override for a project OR just override some parameters. Then the other one covers everything. Weird that I did not notice that, and I did my search before!

**Comment by 42piratas** [comment] 2026-06-06 18:37
https://github.com/zed-industries/zed/pull/58755
