### ISSUE TITLE
Symlink as workspace root breaks file watching

### ISSUE THREAD

**Issue by issacdowling** [zed-industries/zed#17161] opened 2024-08-30 15:31 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, if I make a new file or directory outside of the editor (like by downloading one with `curl`, or if my program makes a config file, etc), it does not appear in the editor's file view until I restart the program. Not sure whether this is a bug or would be a new feature.

If it's a bug, I'm having the issue on Linux, on past versions, and the current one in the Arch repos (0.150.4)

### Environment

Edit: I tried this on two machines, with two different versions of Zed, but I'm now up-to-date on both. The old version (0.149.5) was not the issue, I just hadn't updated on the machine I originally posted this from.

Zed: v0.150.4 (Zed)
OS: Linux Wayland arch 20240721.0.248532
Memory: 31 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6800 (RADV NAVI21) || radv || Mesa 24.2.1-arch1.1

### Zed Log

<details><summary>Zed.log</summary><pre>
with error: failed to connect to the server
2024-09-02T12:32:22.070436438+01:00 [ERROR] ignoring event "/home/user/Downloads/test/test" outside of root path "/home/user/test"
2024-09-02T12:32:25.165355705+01:00 [INFO] Using surface present mode MAILBOX
</pre></details>

**Comment by notpeter** [comment] 2024-09-02 00:52
This is a defect, not an enhancement request so you got the wrong issue template. Zed has this feature, but it's not working for you for some reason (inotify, etc).

Could you edit your description to paste the zed specs: (ctrl-shift-p, zed: copy system specs to clipboard) and include a copy of your Zed log when this happens (ctrl-shift-p zed: open log).

Additionally there was an related bug fix for watching files which recently went out to Zed Preview (v0.151.x) can you download that and see if you can reproduce and report back.

Thanks

**Comment by issacdowling** [comment] 2024-09-02 11:38
It's a symlink issue. I'm always opening my repo directory through a symlink to it, and - trying this with another directory to be sure - the log shows weirdness between the actual directory and the symlink (I've added the log to my original post). Opening the project by manually navigating to the _actual_ directory fixes the issue, but opening through a symlink breaks it.

For when you're looking at the logs, here's what I did:

```
mkdir ~/test
ln -s ~/test ~/Downloads/test

#opens Zed, chooses ~/Downloads/test

touch test
```

Now I have a file in ~/test called test, and zed complains: "outside of root path"

Knowing I can avoid this by not opening through symlinks means this isn't a particularly urgent issue, thanks for letting me know about logging so I could make my issue correct.

**Comment by issacdowling** [comment] 2024-09-02 11:46
Also confirmed, [v0.151.1-pre](https://github.com/zed-industries/zed/releases/tag/v0.151.1-pre) still does it

**Comment by tancop** [comment] 2024-10-03 08:03
Can confirm this on [v0.155.2](https://github.com/zed-industries/zed/releases/tag/v0.155.2). My `~/Code` directory is symlinked to a secondary partition and watching is completely broken in there but works everywhere else. Specs:
```
Zed: v0.155.2 (Zed)
OS: Linux X11 arch unknown
Memory: 15 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 560.35.03
```

**Comment by notpeter** [comment] 2024-10-04 17:52
There was a recent PR which improved watching symlinks in the worktree.
- https://github.com/zed-industries/zed/pull/17609

I haven't tested it, but it is available in Zed Preview `v0.156.x`.
Could you download that and see if it helps?

**Comment by tancop** [comment] 2024-10-07 13:23
Still broken for me in preview `v0.156.0`. Looks like the PR fixes cases where something *inside* the project folder is a symlink but not the project itself.

**Comment by tancop** [comment] 2024-10-12 09:20
I figured out what the problem might be. `fs::watch` indirectly uses `readlink` from libc on Unix. `readlink` only resolves to a value if the path *itself* is a symlink, not one of its parents. `smol::fs::read_link` returns a `Err(smol::io::Error)` if the path is not a symlink but errors get discarded by the `.await.ok()` at `fs.rs:591`.

This means if the workspace root is `~/dir1/dir2/` where `dir1` is a symlink, `target_path` gets set to `None` on line 591. The closure inside `filter_map` on line 608 then returns `None` for every path because `notify::Event`s always contain the canonical path returned from `inotify` so they never start with the non-canonical `root_path`. The `.collect::<Vec<_>>()` produces an empty `Vec`  and `pending_paths` never gets extended.

All notifications from the watcher get rejected because the returned canonical path doesn't match the workspace root inside Zed. This prints out messages like this to the log: `[ERROR] ignoring event "/home/user/dir1/file" outside of root path "/home/user/link1"` where `link1` is a symlink to `dir1`.

This could be fixed by replacing line 591 with:
```rust
let target_path = self.canonicalize(&path).await.log_err();
```
and all uses of `root_path` with the canonical `target_path` .

**Note:** this is all specific to the Linux implementation of `fs::watch`. The macOS and Windows versions don't handle symlinks this way and probably don't have this issue.

**Comment by ConradIrwin** [comment] 2024-11-06 22:53
@tancop I am struggling to reproduce this with:
```
mkdir -p code/example
echo test > code/example/a.txt
ln -s code code2
zed code2/example
# open a.txt in zed
echo test > code/example/b.txt
``` 

In this case (on 0.161.0) I see `b.txt` show up in Zed immediately. That said, your description makes sense to me, so I wonder what I'm missing?

**Closed** 2024-11-22 16:20 UTC
Labels: bug, workspace, linux
