### ISSUE TITLE
Copilot suggestion not disappearing when turning off copilot

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#7355] opened 2024-02-04 11:16 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Start writing some code and trigger copilot to make a suggestion, but don't apply it
2. Turn off copilot
=> The suggestion never disappears, even after reenabling copilot.

https://github.com/zed-industries/zed/assets/19362696/c4c1590a-74f9-4820-9a51-e7fc94cd995c

### Environment

Zed: v0.121.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-06 20:13
Hey @N8th8n8el,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/6793

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-06 20:13 UTC
Labels: defect, setting, copilot
