### ISSUE TITLE
bug(Windows/LSP/Svelte): not launching

### ISSUE THREAD

**Issue by vipexv** [zed-industries/zed#20072] opened 2024-11-01 12:31 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Svelte LSP doesn't launch at all.

The error message states that "oneshot cancelled"

### Environment

Zed: v0.159.7 (Zed Dev)
OS: Windows 10.0.22631
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 560.81

**Comment by SomeoneToIgnore** [comment] 2024-11-01 12:40
Duplicate of https://github.com/zed-industries/zed/issues/12013

**Comment by SomeoneToIgnore** [comment] 2024-11-01 12:41
Which you even commented...

https://github.com/zed-industries/zed/issues/12013#issuecomment-2408685613

**Closed by SomeoneToIgnore** 2024-11-01 12:40 UTC
Labels: defect, triage, admin read

**Comment by vipexv** [comment] 2024-11-01 13:16
I forgot to mention, before the Tailwind/TS LSPs weren't working, now they are... I'm only having this issue on the Svelte LSP...
