### ISSUE TITLE
Missing `ctrl-shift-<up|down>` VSCode keymap

### ISSUE THREAD

**Issue by Conaclos** [zed-industries/zed#16510] opened 2024-08-20 10:07 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Zed doesn't provide by default the key bindings `ctrl-shift-up` and `ctrl-shift-down` that add cursor above and below respectively. They are aliases for `alt-shift-up` and `alt-shift-down`.

In the meantime, a workaround is to declare the key bindings in the keymap configuration:

```json5
[
  {
    "context": "Editor",
    "bindings": {
      // Missing VSCode Key Bindings
      "ctrl-shift-up": "editor::AddSelectionAbove",
      "ctrl-shift-down": "editor::AddSelectionBelow"
    }
  }
]
```

**Comment by notpeter** [comment] 2024-08-20 16:24
Duplicate of:
- https://github.com/zed-industries/zed/issues/16441

See: [this comment](https://github.com/zed-industries/zed/issues/16441#issuecomment-2296706269) for a workaround

**Closed by notpeter** 2024-08-20 16:24 UTC
Labels: enhancement, triage, admin read
