### ISSUE TITLE
override behavior of mouse clicks

### ISSUE THREAD

**Issue by maan2003** [zed-industries/zed#18483] opened 2024-09-28 17:25 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I want to goto definition on double click and goto to references on right click

Current behavior of select word is not useful in vim mode (viw is much faster).

**Comment by JosephTLyons** [comment] 2024-10-12 17:14
Hey @maan2003,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/10647

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-10-12 17:14 UTC
Labels: enhancement, mouse interaction, setting
