### ISSUE TITLE
Bug when opening a folder in the left doc

### ISSUE THREAD

**Issue by stalexsm** [zed-industries/zed#4281] opened 2024-01-09 07:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/community/assets/10753523/f5eeb0e8-62bd-4e15-996e-e19611340b77

### Environment

Zed: v0.119.4 (Zed Preview)
OS: macOS 14.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by permanar** [comment] 2024-01-26 16:18
May I also put this as I also think this is "kinda" a bug that related to `folder`?

So the problem is when you have like a deep folder, it doesn't let you horizontally scroll or something that let you see the complete filename or maybe possible another folder inside the folder and so on.

Attachment:

![image](https://github.com/zed-industries/zed/assets/25473432/ef998afe-2e83-4147-9e39-c80d57836271)

**Comment by mrnugget** [comment] 2024-02-12 16:15
@permanar we already have a different issue for that: https://github.com/zed-industries/zed/issues/7001

---

As for the original bug: a lot has changed with how we render things (metal renderer and how we handle z-indexes), and since I can't reproduce the issue, and we haven't had activity nor other reports of this issue in the last 3 weeks, I'm going to close it for now. We can always reopen when it pops up again.

**Closed by mrnugget** 2024-02-12 16:15 UTC
Labels: defect, regression, project panel
