### ISSUE TITLE
Add option to move tab bar to the title bar (different from hiding it)

### ISSUE THREAD

**Issue by julyfun** [zed-industries/zed#13105] opened 2024-06-16 08:05 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

An option to show tabs in title bar, next to traffic light buttons, because there is vertical space wasted in title bar.
Thank you for reviewing!

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="840" alt="image" src="https://github.com/zed-industries/zed/assets/43675484/c1bdc402-2fcd-442a-8332-90d912ed5c79">

⬇️ making it something like thils:

<img width="818" alt="image" src="https://github.com/zed-industries/zed/assets/43675484/69689ada-56d5-4a3c-b0d9-d298e4185c64">

Like in safari:

<img width="666" alt="image" src="https://github.com/zed-industries/zed/assets/43675484/7417a3c7-15dc-4ba8-8cc5-dba2ccc984b8">

**Comment by Solarunit** [comment] 2024-06-16 14:10
Looks nice! +1

**Comment by Moshyfawn** [comment] 2024-06-16 16:41
Didn't you create #11146 before?

**Comment by Moshyfawn** [comment] 2024-06-16 16:45
There's also another issue that already requests this, so I'm going to close this one as a dupe anyway. Be sure to +👍 the other thread.

Duplicate of:
- #5066

**Closed by Moshyfawn** 2024-06-16 16:45 UTC
Labels: enhancement, design, workspace, tabs, admin read
