### ISSUE TITLE
How to use glyphs from fonts, the built-in terminal can't render the glyphs?

### ISSUE THREAD

**Issue by ahmetkca** [zed-industries/zed#19876] opened 2024-10-29 08:01 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

built-in terminal can't render glyphs

### Environment

Mac Book Pro M3 Max, Sequoia 15.0.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/1d79dd5e-bdc4-49ef-8b8c-1cfe04bc1581)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-29 08:32
Duplicate of https://github.com/zed-industries/zed/issues/19833

**Closed by SomeoneToIgnore** 2024-10-29 08:32 UTC
Labels: defect, triage, admin read

**Comment by SomeoneToIgnore** [comment] 2024-10-29 18:08
https://github.com/zed-industries/zed/issues/19833#issuecomment-2444992296

has the solution, apparently `Zed Plex Mono` has no such symbols.
