### ISSUE TITLE
Line numbers and selections jiggly in big file

### ISSUE THREAD

**Issue by Gioppix** [zed-industries/zed#21120] opened 2024-11-23 19:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Line numbers and selections are glitchy while scrolling in a long file

Steps to reproduce:

Generate a large file (example using Deno repl)
```
async function generateRandomStrings() {
  const filePath = "/tmp/lol.txt";
  const file = await Deno.open(filePath, { write: true, create: true });
  const encoder = new TextEncoder();

  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

  for (let i = 0; i < 5000000; i++) {
    let str = '';
    for (let j = 0; j < 30; j++) {
      str += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    str += '\n';
    await file.write(encoder.encode(str));
  }

  file.close();
}

await generateRandomStrings();
```

Open the file
```
zed /tmp/lol.txt
```

Select text, scroll up and down

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="394" alt="Screenshot 2024-11-23 at 20 51 56" src="https://github.com/user-attachments/assets/0ebaab42-6c09-49f0-ac78-4e422d32e252">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-23 19:54
Duplicate of https://github.com/zed-industries/zed/issues/5355

**Closed by SomeoneToIgnore** 2024-11-23 19:54 UTC
Labels: bug, triage, admin read
