### ISSUE TITLE
CJK characters cannot be inputted in the Zed terminal

### ISSUE THREAD

**Issue by ika-musuko** [zed-industries/zed#14548] opened 2024-07-16 08:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The main editor supports CJK just fine, but if you go to type CJK characters in the terminal, they do not appear.

My personal use case for this that sometimes I have to write commit messages in Japanese.

Display of CJK characters is fine.

### Environment

Zed: v0.145.0 (Zed Dev 7bcebb03d928c201da990f7590f801f1231a259b)
OS: macOS 14.4.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature
Here is a demo of the current behavior in zed, versus the intended behavior in another terminal application, [alacritty](https://github.com/alacritty/alacritty)

https://github.com/user-attachments/assets/01b29dc9-b13f-4ded-a61e-a55fd64b879e

**Comment by yasainet** [comment] 2024-08-19 19:59
I'm having the same problem 🥹

**Comment by kkebo** [comment] 2024-10-03 04:27
Same as #9900

**Comment by notpeter** [comment] 2024-10-17 13:58
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/9900

Thanks for reporting.

**Closed by notpeter** 2024-10-17 13:58 UTC
Labels: defect, terminal, macOS, internationalization
