### ISSUE TITLE
Huge window decorations in X11 and wasted space around the window

### ISSUE THREAD

**Issue by AlexDaniel** [zed-industries/zed#13912] opened 2024-07-07 12:51 UTC
Zed window now has an extra blank space border around it.

Here's a screenshot of the entire screen on my desktop (alacritty windows are open to show other apps):
![2024-07-07-154715_1366x768_scrot](https://github.com/zed-industries/zed/assets/5507503/87aa74b1-d1db-45ec-8833-9e58f39962c2)

And here I highlight the wasted space in red:
![2024-07-07-154715_1366x768_scrot](https://github.com/zed-industries/zed/assets/5507503/5d498466-1de5-41c1-99ef-eb78ac350fb9)

The space highlighted in red is taken by Zed.

Ideally, the wasted space needs to be removed completely. Window decorations are fine, though with tiling window managers they're a bit counter-productive.

### Environment

Linux, X11, i3wm
Zed built from 79f364632535ef85c190fcf1be9834bbffc19c95.

**Comment by spikymonotreme** [comment] 2024-07-07 13:34
duplicate of this https://github.com/zed-industries/zed/issues/13845

**Comment by AlexDaniel** [comment] 2024-07-07 14:01
That's true, yeah. Thank you!

**Closed** 2024-07-07 14:02 UTC
Labels: defect, triage, admin read
