### ISSUE TITLE
Toggle function definition within current editor

### ISSUE THREAD

**Issue by aevatry** [zed-industries/zed#8202] opened 2024-02-22 15:22 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like to be able to toogle on and off the function definition as a little pop-up while I'm completing the fields of a function. 
I am not talking about opening the function definition in a split plane (that also works but I find I lose time going to the function name using text shortcuts and coming back). 

### If applicable, add mockups / screenshots to help present your vision of the feature

Ideally, behaviour would be similar to a code editor like VScode and a key binding would toogle that popup on and off (where popup indicates which field needs to be typed and the possible fields, see below.)

![image](https://github.com/zed-industries/zed/assets/87442477/e03c6c27-3938-45c3-bc10-ea05f23378a9)

Zed has something that closely resembles it but only when cursor is on the function name and not within field definition (see below):

![image](https://github.com/zed-industries/zed/assets/87442477/4c216e05-d809-485e-ac83-bd4be20fc955)

But it does not popup when writing within the parentheses

**Comment by JosephTLyons** [comment] 2024-02-23 20:19
Hey @aevatry,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5155

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-23 20:19 UTC
Labels: enhancement, popovers
