### ISSUE TITLE
After fixing the error `Diagnostic-msg` not close

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8397] opened 2024-02-25 17:14 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```json
{
    "context": "Editor && VimControl && !VimWaiting && !menu",
    "bindings": {
      "cmd-1": "editor::GoToDiagnostic",
      "cmd-2": "editor::GoToPrevDiagnostic"
    }
  }
```
When I use `cmd-1` to jump to an error and fix it, I find that the error message still exists, which is unusual.
![fix9](https://github.com/zed-industries/zed/assets/45585937/dea41d1d-fc15-4c24-a6a0-888cc5a32b33)
![fix10](https://github.com/zed-industries/zed/assets/45585937/0a9fbf89-31e7-4c77-9353-49c059b91a90)

### Environment

Zed: v0.124.4 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by nilskch** [comment] 2024-02-26 10:58
I agree, this is quite annoying.

**Comment by JosephTLyons** [comment] 2024-02-27 20:26
I think this might be a dupe of:

- https://github.com/zed-industries/zed/issues/4819

Closing for now, but let me know if its not quite the same.

**Closed by JosephTLyons** 2024-02-27 20:26 UTC
Labels: defect, diagnostics
