### ISSUE TITLE
Tab: split and move right

### ISSUE THREAD

**Issue by remainstheday** [zed-industries/zed#15769] opened 2024-08-04 14:06 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I know this partially exists today, please read! If a developer is trying to split the current tab into two panes then both panes show the same open file by default. This adds an extra step every time I want to compare two files side by side because I end up having to reselect the left pane and close the open tab. It would be great if there was a keybinding for "split tab and move right" similar to Jetbrains IDE's. 

![CleanShot 2024-08-04 at 10 00 19](https://github.com/user-attachments/assets/491295eb-273b-446b-a815-abc8aaab2b2c)

**Comment by failable** [comment] 2024-08-04 15:10
Related: https://github.com/zed-industries/zed/issues/15722

**Comment by notpeter** [comment] 2024-08-09 20:29
Closing as duplicate of: 
- https://github.com/zed-industries/zed/issues/15722

Related:
- https://github.com/zed-industries/zed/issues/11342

**Closed by notpeter** 2024-08-09 20:29 UTC
Labels: enhancement, triage, admin read

**Comment by Benjamin-van-Heerden** [comment] 2025-03-25 11:19
Any updates on this?
Kind of annoying. Should be the default behavior. If I am splitting, why would I want a duplicate to remain open?
