### ISSUE TITLE
[Snippet] Placeholder optional content

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#13446] opened 2024-06-24 04:00 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

```
{
  "Test3": {
    "prefix": "test3",
    "body": [
      "/**",
      " * @description description...",
      " * @param { ${1|Boolean,Number,String,Object,Array,*|} } name description...",
      " * @return { ${2|Boolean,Number,String,Object,Array,*|} } description...",
      " */",
      "$0"
    ],
    "description": "Test3"
  }
}
```
![image](https://github.com/zed-industries/zed/assets/19868292/ed1bd254-5f2d-4fc9-b251-1e6a348d5c56)

**Comment by osiewicz** [comment] 2024-06-24 08:10
Duplicate of: https://github.com/zed-industries/zed/issues/12739

**Closed by osiewicz** 2024-06-24 08:10 UTC
Labels: enhancement, triage, admin read
