### ISSUE TITLE
Keybindings don't work unless I'm on English layout

### ISSUE THREAD

**Issue by unkindypie** [zed-industries/zed#12329] opened 2024-05-26 21:49 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Keybindings from keymap.json don't work unless I'm on English layout.
If I'm on Ukrainian layout none keymaps are working.
I use linux with hyprland desktop environment which is based on wayland.

### Environment

                   -`                    maxb@archlinux
                  .o+`                   --------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: 82K8 Legion S7 15ACH6
               `+oooooo:                 Kernel: 6.9.1-arch1-2
               -+oooooo+:                Uptime: 5 hours, 1 min
             `/:-:++oooo+:               Packages: 1328 (pacman)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 2560x1440
          `/+++ooooooooooooo/`           DE: Hyprland
         ./ooosssso++osssssso+`          WM: sway
        .oossssso-````/ossssss+`         Theme: oomox-arc-dark [GTK2/3]
       -osssssso.      :ssssssso.        Icons: HighContrast [GTK2/3]
      :osssssss/        osssso+++.       Terminal: tmux
     /ossssssss/        +ssssooo/-       CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 4.46
   `/ossssso+/:-        -:/+osssso+-     GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Se
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
 `++:.                           `-/+/   Memory: 6918MiB / 39470MiB
 .`                                 `/
Zed 0.136.2

**Comment by XDeme1** [comment] 2024-05-26 22:17
Are you using IBus with vim mode enabled?
https://github.com/zed-industries/zed/pull/12299 probably fixes this issue

**Comment by XDeme1** [comment] 2024-05-26 22:20
Are you using IBus with vim mode enabled?
https://github.com/zed-industries/zed/pull/12299 might fix this issue

**Comment by Moshyfawn** [comment] 2024-05-26 23:58
This has been reported in another issue, albeit reported for MacOS, so I'll close this one in its favour. Be sure to +👍 the other thread and add any missing information. Let me know if this is a mistake and we can reopen it.

Duplicate of:
- #10972

**Closed by Moshyfawn** 2024-05-26 23:58 UTC
Labels: defect, triage, admin read

**Comment by unkindypie** [comment] 2024-05-27 15:40
@XDeme1 no I am on release 0.136.2 version. Will wait for next release where this PR is merged, thank you
