### ISSUE TITLE
Bottom dock unstable when 100% high

### ISSUE THREAD

**Issue by joeldrapper** [zed-industries/zed#8708] opened 2024-03-02 10:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the bottom dock is expanded to 100% high, it starts jumping around and disturbing the tab bar.

### Environment

Zed: v0.125.1 (Zed Preview)
OS: macOS 14.3.0
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/246692/213867d5-9fb3-4d63-b3e3-490959952952

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-03-02 16:57
It seems as if the width of the editor is being reduced for some reason, as if a panel is being expanded underneath the terminal panel.

https://github.com/zed-industries/zed/assets/16290753/685f9a23-17ed-494b-8a2b-492358bb1afd

**Comment by Moshyfawn** [comment] 2024-03-02 16:59
It actually looks like #8363 🤔

**Comment by Moshyfawn** [comment] 2024-03-05 16:34
I'm going to close this issue in favour of the other one. Be sure to +👍.

**Comment by Moshyfawn** [comment] 2024-03-05 16:34
Duplicate of #8363

**Comment by Moshyfawn** [comment] 2024-03-05 16:35
Duplicate of #8363

**Closed by Moshyfawn** 2024-03-05 16:35 UTC
Labels: defect, terminal, editor, admin read, panel
