### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by mehditareghi** [zed-industries/zed#16020] opened 2024-08-09 09:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I work on multilingual projects which contain RTL languages too. The problem is that Zed right now doesn't support them properly.

I can't select text written in an RTL language like Persian properly, there is no indicator for the selected text when it comes to languages like this... and working with these kind of languages in Zed right now is really a PAIN.

Can you fix this issue and support those things properly? I think Webstorm did a really good job on this particular subject (and VS Code did not, by the way!).
![Screenshot 2024-08-09 at 13 02 20](https://github.com/user-attachments/assets/e541795f-a08a-4a83-919b-92a9a9ac9c8d)

### Environment

Zed: v0.148.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by asibahi** [comment] 2024-08-23 14:56
Hello. 

I am interested in finding a decent RTL text editor . I hoped Zed would be it but found this issue. Ah well.

I am here to post an image I found of Emacs showing the expected behavior: from https://typo.social/@elih/112724233360735189

![](https://typo.social/system/media_attachments/files/112/724/232/518/666/474/original/998468730916c6fb.jpg)

(This is apparently Emacs)

If you guys can make that happen I am switching to Zed for life.

**Comment by notpeter** [comment] 2024-10-17 14:07
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/7465

**Closed by notpeter** 2024-10-17 14:07 UTC
Labels: defect, internationalization
