### ISSUE TITLE
Custom cursor size

### ISSUE THREAD

**Issue by rach3bartmoss** [zed-industries/zed#18309] opened 2024-09-24 22:24 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In fact i am just a learner, but i am trying for the past few days to find a way to custom the mouse cursor size, this is because since the update 0.152.4 the cursor size became bigger than the system default on my computer and for many other so far i could read on the forums, this affects when we want to click at some icon and its turn to be not very precise the clicking. i suggest a fix to the cursor size be the user system default size, or to add a custom feature in settings.json

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot from 2024-09-24 23-21-27](https://github.com/user-attachments/assets/fb1afdf8-8aa4-41d4-8a4a-9de4ca0c888c)
![Screenshot from 2024-09-24 23-21-09](https://github.com/user-attachments/assets/e4b2bc05-0373-4dc5-8f64-18238d922c30)

for some reason the print screen shows at the same size, but its not, and maybe this is cause the lack of precision at clicking, i suppose the big cursor size is on top of the real cursor

**Comment by arqalite** [comment] 2024-09-25 11:01
In my case, it's even worse, after updating to 0.153.7 on Ubuntu 22.04 x64.

I had to take pictures with my phone because screenshots would revert the cursor size to the system one.

Cursor size normally: https://drive.proton.me/urls/DMD36K0EXW#SC4ZogHzMWZG
Cursor size in Zed: https://drive.proton.me/urls/ZZED3EC82M#AP4TN3T3b52c

**Comment by notpeter** [comment] 2024-09-25 21:59
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/17771

**Closed by notpeter** 2024-09-25 21:59 UTC
Labels: enhancement, triage, admin read
