### ISSUE TITLE
Zed failed to launch

### ISSUE THREAD

**Issue by Thecode764** [zed-industries/zed#15267] opened 2024-07-26 09:22 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hi i just installed the linux version when i running the zed editor my error is

VulkanError(ERROR_INITIALIZATION_FAILED). See https://zed.dev/docs/linux for troubleshooting steps. 

i updated my system but it's not working

### Environment

i use arch linux.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>
[username@hostname ~]$ find  ~/Library/Logs/Zed/Zed.log
find: ‘/home/username/Library/Logs/Zed/Zed.log’: No such file or directory

**Comment by SomeoneToIgnore** [comment] 2024-07-26 09:40
https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+ERROR_INITIALIZATION_FAILED

Duplicate of https://github.com/zed-industries/zed/issues/8168

In general from those discussions, seems that people do not update systems but rather the video drivers, and install specific packages to solve this.

**Closed by SomeoneToIgnore** 2024-07-26 09:40 UTC
Labels: defect, triage, admin read
