### ISSUE TITLE
Significant battery usage on MacOS

### ISSUE THREAD

**Issue by inuoshios** [zed-industries/zed#4417] opened 2023-10-17 13:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Anytime I startup Zed, I get the MacOS using significant energy warning, and I've also noticed it drains my battery faster.
This warning is showed immediately I open the editor <10s.

### Environment

Zed: v0.107.7
OS: 13.6
Memory: 16 GB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="524" alt="image" src="https://github.com/zed-industries/community/assets/59049785/c1ec9da5-c185-4a33-8cd6-8b871af27483">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jonee** [comment] 2024-05-16 15:24
I can confirm this issue. I recently installed zed (0.134.4) on MacOs looking for an atom replacement which seems to have no more updates. Since the first time I launched zed, it has stayed in that significant energy location.

**Comment by evrensen467** [comment] 2024-05-31 19:15
coming from the above issue ^ (https://github.com/zed-industries/zed/issues/12449) I'm also experiencing high battery usage on my MacBook Air M3.

**Comment by evrensen467** [comment] 2024-06-01 18:29
just created a new cargo project for a simple game I wanted to make, barely any code (so I'd assume that'd rule out rust-analyzer) and zed has high energy consumption, I'm not compiling either so that'd be ruling out rustc too? I'd really appreciate if someone could look into this and push out a fix as soon as possible, I'll have to use vscode in the meantime for the sake of this laptops battery health.

https://github.com/zed-industries/zed/assets/146845123/fcf3e629-2744-4950-aed1-4d1fa21c249e

**Comment by evrensen467** [comment] 2024-06-01 18:44
I tried with a minimal python project and the same thing happened, but this time my chip got extremely hot and I immediately shut down my laptop, I'm not comfortable trying to replicate this problem on my laptop again, sorry. I hope this gets solved asap

**Comment by xgfone** [comment] 2024-06-03 13:48
As soon as I write code in Zed, the MacBook fan buzzes, and as soon as I stop editing, after a while, it doesn't ring much.

```
MacBookPro: 2014
MacXOS: Big Sur 11.7.10
Zed: 0.137.6
```

**Comment by ConradIrwin** [comment] 2024-06-03 16:28
@xgfone or @evrensen467 do either of you have time to screen share with me to see if we can try and debug what's going on here?

https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ338_067BG6UMh8ClawRpwJ12b65O1K9OCRCMMDeOGZgZihmUNQJqVmnYkNpVgQadFPyYFnOPrB

**Comment by Zinidia** [comment] 2024-06-05 02:13
I have this same issue, it's especially noticable when running Zed idle for a few minutes, I installed Zed via brew if that helps. Here's my environment:
```
Macbook Pro 2019
Zed: v0.137.6
OS: 14.5
Memory: 16 GB
Architecture: x86_64
```

**Comment by Zinidia** [comment] 2024-08-05 17:57
I had this issue too on my 2019 Intel Macbook Pro but after one of the recent updates, it seems to be fixed for me now.

**Comment by jonee** [comment] 2024-08-06 03:11
> I had this issue too on my 2019 Intel Macbook Pro but after one of the recent updates, it seems to be fixed for me now.

Since I have the same laptop for work, I installed the latest MacOs update. Then I uninstalled zed. Then installed zed from brew. Seems to look good. Will start to evaluate and use zed from now on. 

Thanks! 

@Zinidia @ConradIrwin

**Comment by notpeter** [comment] 2024-11-04 00:36
I'm going to go ahead an close this as there have been multiple major performance improvements since this was opened a year ago.

The most recent comments were likely a duplicate of this:
- https://github.com/zed-industries/zed/issues/17305

If you are still experiencing significant battery usage, please open a new issue with full details of your system and steps to reproduce. Thanks for reporting!

**Closed by notpeter** 2024-11-04 00:36 UTC
Labels: defect, performance
