### ISSUE TITLE
Jump on Mouse Click near edges of Screen

### ISSUE THREAD

**Issue by sanbox-irl** [zed-industries/zed#17546] opened 2024-09-07 20:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is maybe a bug or a feature request -- i'm not sure. I also had trouble identifying another issue, but I suspect there is one.

Right now, if I click on the top or the bottom of the screen, at say, the last line available to view, the screen will "jump" a bit farther south, so that this line is not the last line on screen. It appears to want a bit of buffer between the line i'm editing and the actual bottom of the screen.

In practice though, I do not believe this is the right UX to do when a mouse position is requested manually by the user -- it's surprising at the screen moves when I click anywhere with my house.

### Environment

Zed: v0.151.2 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-09-14 02:17
I believe you're referring to the behavior that's already been mentioned in another issue. I'll close this issue in favor of that one, but please let me know if I'm mistaken. Otherwise, be sure to +👍 the other thread.

Duplicate of:
- #5219

**Closed by Moshyfawn** 2024-09-14 02:17 UTC
Labels: defect, triage, admin read
