### ISSUE TITLE
Open files with enconding ISO 8859-1

### ISSUE THREAD

**Issue by Seidon1984** [zed-industries/zed#10759] opened 2024-04-19 05:12 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have a project which all files are enconded by ISO 8859-1, but I can not open it.

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-04-19T07:04:25+02:00 [ERROR] stream did not contain valid UTF-8

**Comment by SomeoneToIgnore** [comment] 2024-04-19 06:17
Will close it as duplicate of https://github.com/zed-industries/zed/issues/9833

**Closed by SomeoneToIgnore** 2024-04-19 06:17 UTC
Labels: defect, triage, admin read
