### ISSUE TITLE
continuous update

### ISSUE THREAD

**Issue by dabzse** [zed-industries/zed#17241] opened 2024-09-01 17:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have Zed in my `~/APPS/zed/`
    Zed 0.148.1

when I open it, it shows on the bottom: \
"Downloading Zed update..."\
"Installing Zed update..."\
"Click to restart and update Zed"

okay....
Zed 0.150.4

when I quit the app and re-open it, it shows on the bottom: \
"Downloading Zed update..."\
"Installing Zed update..."\
"Click to restart and update Zed"

I checked the version again: Zed 0.148.1
WOW \*.\*

after the update: Zed 0.150.4

exit, re-open: Zed 0.148.1, and the updating process again...
didn't open my last file. no problem....
but why does not work properly? it is a portable version....

the log shows:
`[INFO] Restarting process, using app path: "/home/<username>/.local/zed.app/libexec/zed-editor"`
but it is a portable version.... will it be fixed?

### Environment

my system is: Fedora 40 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-01 18:59
I think this is likely a duplicate of:
- https://github.com/zed-industries/zed/issues/14291

There is a fix in the most recent Zed Preview which will become the next Zed Stable on Wednesday.  You will need to manually re-run the installer, you can do that with Zed Preview today or with Zed Stable Wednesday afternoon.

In the meantime, as a workaround, you can add `"auto_update": false` to your settings.json to keep it from trying (and failing) to auto-update. [auto_update docs](https://zed.dev/docs/configuring-zed#auto-update).

Auto-update bugs are the worst. Our apologies.

**Closed by notpeter** 2024-09-01 18:59 UTC
Labels: defect, triage, admin read
