### ISSUE TITLE
Unable to open zed in ubuntu 20.04

### ISSUE THREAD

**Issue by anandanand84** [zed-industries/zed#17559] opened 2024-09-08 12:01 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Unable to open zed.

error opening [PathWithPosition { path: "/home/.../dev/../-ui", row: None, column: None }]: NoSupportedDeviceFound

### Environment

It is an ubuntu machine with no gpu.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
Caused by:
    [28] Timeout was reached
2024-09-07T17:54:38.487582026-05:00 [INFO] ========== starting zed ==========
2024-09-07T17:54:38.532023589-05:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-09-07T17:54:38.532089158-05:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-09-07T17:54:38.541297565-05:00 [INFO] Try connect ibus
2024-09-07T17:54:38.542603989-05:00 [INFO] perform;
2024-09-07T17:54:38.542650258-05:00 [INFO] authenticate;
2024-09-07T17:54:38.542723461-05:00 [INFO] read_command;
2024-09-07T17:54:38.543007553-05:00 [INFO] Opening main db
2024-09-07T17:54:38.544630699-05:00 [INFO] new;
2024-09-07T17:54:38.544964911-05:00 [INFO] socket reader;
2024-09-07T17:54:54.674408639-05:00 [INFO] Using Visual { id: 182, colormap: 0, depth: 32 }
2024-09-07T17:54:54.674615161-05:00 [INFO] Creating colormap 77594636
2024-09-07T17:54:54.67644845-05:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-09-07T17:54:54.69402195-05:00 [INFO] Adapter: "Intel(R) UHD Graphics (CML GT2)"
2024-09-07T17:54:54.694946753-05:00 [WARN] Rejected for device extension "VK_KHR_dynamic_rendering" not supported. Please update the driver!
2024-09-07T17:54:54.69506139-05:00 [INFO] Adapter: "llvmpipe (LLVM 12.0.0, 256 bits)"
2024-09-07T17:54:54.695304064-05:00 [WARN] Rejected for device extension "VK_EXT_inline_uniform_block" not supported. Please update the driver!
2024-09-07T18:02:06.952128474-05:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-07T18:02:06.952397725-05:00 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2024-09-07T18:10:06.967903322-05:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-07T18:10:06.968181879-05:00 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2024-09-07T18:13:06.954644758-05:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-07T18:13:06.954953858-05:00 [ERROR] auto-update failed: error:request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2024-09-07T18:18:06.970874052-05:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-07T18:18:06.971140572-05:00 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2024-09-08T06:46:34.475656686-05:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-08T06:46:34.475966296-05:00 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2024-09-08T06:53:49.915100201-05:00 [INFO] Using Visual { id: 182, colormap: 0, depth: 32 }
2024-09-08T06:53:49.915352745-05:00 [INFO] Creating colormap 77594639
2024-09-08T06:53:49.91763591-05:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-09-08T06:53:49.933160908-05:00 [INFO] Adapter: "Intel(R) UHD Graphics (CML GT2)"
2024-09-08T06:53:49.934462888-05:00 [WARN] Rejected for device extension "VK_KHR_dynamic_rendering" not supported. Please update the driver!
2024-09-08T06:53:49.934621988-05:00 [INFO] Adapter: "llvmpipe (LLVM 12.0.0, 256 bits)"
2024-09-08T06:53:49.934996059-05:00 [WARN] Rejected for device extension "VK_EXT_inline_uniform_block" not supported. Please update the driver!
2024-09-08T06:54:34.46815615-05:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-09-08T06:54:34.468340759-05:00 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
```

**Comment by SomeoneToIgnore** [comment] 2024-09-08 14:07
> It is an ubuntu machine with no gpu.

This is the culprit, most probably Zed with UI won't start on that machine.

There's also a ton of similar issues if you have tried searching your errors, e.g. https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+VK_KHR_dynamic_rendering+

so I'll close this as a duplicate of https://github.com/zed-industries/zed/issues/17553 and https://github.com/zed-industries/zed/issues/14237

**Closed by SomeoneToIgnore** 2024-09-08 14:07 UTC
Labels: defect, triage, panic / crash, admin read
