### ISSUE TITLE
Code appears line by line when scrolling, second half of view is empty, but code is actually there

### ISSUE THREAD

**Issue by ForceBru** [zed-industries/zed#7411] opened 2024-02-05 22:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce: open a relatively long file and scroll around.

The bottom half of the "code view" is empty. When scrolling, code gradually appears, filling more of the bottom half. Then randomly stops appearing, so the bulk of the visible code scrolls to the top while the bottom fills with empty space. Then more of the code starts appearing again. See screen recording.

When the bottom half is empty, the code is still there: I can select it, select & highlight variable names, red squiggles are there too. So it could be a graphics issue. Unfortunately I have an old NVIDIA GeForce GT 640M, so that's not good. __However__, absolutely no other text editor and no other app behaves like this for me, only Zed. VSCode, SublimeText, Jupyter, the terminal, Safari, everything works fine and has always been working fine except Zed. In fact, I've never ever encountered this kind of glitch in any other app before. Thus, perhaps the GPU isn't _so_ old that it can't render text properly...

https://github.com/zed-industries/zed/assets/8695383/da00cfd5-1373-4b2e-a2ed-05b63dd9c00d

### Environment

Zed: v0.121.3 (Zed Preview) same for many previous stable (not preview) versions
iMac 21.5-inch, Late 2012
OS: macOS 13.6.3
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
[INFO] ========== starting zed ==========
[INFO] Opening main db
[ERROR] crates/zed/src/zed.rs:519: EOF while parsing a value at line 1 column 0
[INFO] Opening main db
[ERROR] crates/zed/src/main.rs:887: reading themes from "/Users/forcebru/.config/zed/themes"

Caused by:
    No such file or directory (os error 2)
[INFO] build git repository ".git"
[INFO] set environment variables from shell:/usr/local/bin/fish, path:/Users/forcebru/.pyenv/shims:/usr/local/sbin:/Users/forcebru/.cargo/bin:/Users/forcebru/.pyenv/bin:/Users/forcebru/.juliaup/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/quarto/bin
[INFO] Opening main db
[INFO] starting language server "pyright", path: "/Users/forcebru/Desktop/VolatilityForecasting", id: 1
[INFO] Node runtime install_if_needed
[WARN] request completed with error: request or operation took longer than the configured timeout time
[ERROR] auto-update failed: error:request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
[INFO] Node runtime install_if_needed
[INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Pyright language server 1.1.345 starting"
}
[INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/forcebru/Library/Application%20Support/Zed/languages/pyright/node_modules/pyright/dist"
}
[INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Starting service instance \"\""
}
[INFO] 1 unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "b9868252-260c-47d0-b71f-c564c6b1827a",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
[ERROR] crates/lsp/src/lsp.rs:624: oneshot canceled
[ERROR] crates/ai/src/providers/open_ai/embedding.rs:170: NotPresent
[ERROR] crates/semantic_index/src/semantic_index.rs:87: user is not authenticated
[ERROR] crates/gpui/src/window.rs:387: window not found
[ERROR] crates/ai/src/providers/open_ai/embedding.rs:170: NotPresent
[ERROR] crates/semantic_index/src/semantic_index.rs:87: user is not authenticated
```

**Comment by osiewicz** [comment] 2024-02-05 23:01
Hey, thanks for the report.
This seems to be related to https://github.com/zed-industries/zed/issues/6853

**Comment by ForceBru** [comment] 2024-02-05 23:12
Couldn't find that issue myself, sorry for the duplicate. BTW, it could be useful to automatically attach a line like "iMac 21.5-inch, Late 2012" to the environment if possible, perhaps along with the GPU specs. Currently I put it there myself.

**Comment by Akshat-Jain** [comment] 2024-02-13 18:41
I'm also facing this same issue. I'm on MacBook Pro (Mid 2012).
Processor: 2.7 GHz Quad-Core Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Graphics: NVIDIA GeForce GT 650M 1 GB + Intel HD Graphics 4000 1536 MB

Really appreciate any help on this, would love to use Zed on my machine! 🙏

**Comment by davro** [comment] 2024-02-15 18:41
I also have been getting this odd issue when scrolling through text, the bottom half disappears, I have highlighted the missing text at the bottom to show it actually exists.
![JH-BCNKZ](https://github.com/zed-industries/zed/assets/252873/79351d8c-0afc-4d8e-bf28-8a05ede80dc2)

Here is the same image with a different file to show its not isolated to one file, i am just browsing the bootstraps most recent codebase.
![guheZs5r](https://github.com/zed-industries/zed/assets/252873/81948165-8133-4cc2-a8d4-a594f5546237)

This is the system i am using its a 2014 macbook pro.
![CDc4D2WD](https://github.com/zed-industries/zed/assets/252873/01d9b013-2067-49b1-ac56-6971e1588215)

**Comment by CurbaiCode** [comment] 2024-02-16 19:05
This looks just like the bug in #5062.

**Comment by lhps** [comment] 2024-02-21 20:38
I'm having the same problem. I'm on BigSur, MacBook Pro mid 2014 and Geforce GT750M

**Comment by bennjjii** [comment] 2024-02-28 08:31
Same issue, on an old mac 2013

**Comment by RyzorBent** [comment] 2024-03-19 04:00
Having same issue, running Zed 0.126.3

![Screenshot 2024-03-19 at 05 58 39](https://github.com/zed-industries/zed/assets/15725743/b3456949-d5fd-4d4d-8a76-e4f4f2be3c3c)

![Screenshot 2024-03-19 at 05 51 52](https://github.com/zed-industries/zed/assets/15725743/0fa502ea-9758-4400-afe4-ac768faf4a9d)

**Comment by MrCee** [comment] 2024-03-24 14:47
I' keep coming back hoping there is a fix. It's completely the NVIDIA GPU on my mid 2014 MacBook Pro (Metal2 / Kepler).
I don't see the issue when switching to integrated GPU.

**Comment by RyzorBent** [comment] 2024-03-24 17:12
Today, i had to **stop** using Zed all together, as letters started disappearing immediately after the latest Zed 0.127.3 update. 😥
<img width="862" alt="Screenshot 2024-03-24 at 19 12 28" src="https://github.com/zed-industries/zed/assets/15725743/7b24bb74-0abc-47ca-8f13-4c5de07dff19">

**Comment by moegidine** [comment] 2024-04-27 22:02
The same on macOS 10.15.7
With zed version 0.132.3

**Comment by MaxDac** [comment] 2024-06-12 17:40
I'm experiencing somewhat the same bug on the following configuration:

Zed version: 0.138.6
Macbook 2014
macOS 14.5
2.5 GHz quad core Intel Core i7
NVIDIA GeForce GT 750M 2GB
16 GB 1600 MHz DDR3

But in my case the characters are rendered in a completely casual fashion:

![image](https://github.com/zed-industries/zed/assets/25101798/ec95f1fd-4adc-4305-b2a4-732c575ede48)

Curiously, other buffers though does not present the issue:

![image](https://github.com/zed-industries/zed/assets/25101798/85569e79-b6eb-473c-b003-7222e6b00ea9)

**Comment by notpeter** [comment] 2024-11-04 01:27
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/6853

The root cause is GPUs which do not properly support Metal2 which we require for our rendering pipeline.  Sorry!

**Closed by notpeter** 2024-11-04 01:27 UTC
Labels: defect, editor, macOS
