### ISSUE TITLE
Vim motion "dt," (delete till comma) seems to badly misbehave?

### ISSUE THREAD

**Issue by fasterthanlime** [zed-industries/zed#13789] opened 2024-07-03 19:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In the following Rust code:

```rust
use tokio::{fs::File, io::AsyncReadExt, runtime::Handle, sync::mpsc, time::Instant};
//                                    ☝️ cursor is here
```

...I would expect `dt,` to result in the following diff:

```diff
diff --git a/mods/media/src/lib.rs b/mods/media/src/lib.rs
index 3de9888..9e705c0 100644
--- a/mods/media/src/lib.rs
+++ b/mods/media/src/lib.rs
@@ -19,7 +19,7 @@ use std::{
     sync::Arc,
     time::Duration,
 };
-use tokio::{fs::File, io::AsyncReadExt, runtime::Handle, sync::mpsc, time::Instant};
+use tokio::{fs::File, io::AsyncReadExt, sync::mpsc, time::Instant};
 use tracing::{debug, error, info, warn};
 use xmltree::{Element, EmitterConfig, XMLNode};
```

Instead, it results in the following diff:

```rust
diff --git a/mods/media/src/lib.rs b/mods/media/src/lib.rs
index 3de9888..6a24dba 100644
--- a/mods/media/src/lib.rs
+++ b/mods/media/src/lib.rs
@@ -19,7 +19,7 @@ use std::{
     sync::Arc,
     time::Duration,
 };
-use tokio::{fs::File, io::AsyncReadExt, runtime::Handle, sync::mpsc, time::Instant};
+use tokio::{fs::File, io::AsyncR runtime::Handle, sync::mpsc, time::Instant};
 use tracing::{debug, error, info, warn};
 use xmltree::{Element, EmitterConfig, XMLNode};
```

(yes, it ended up deleting code _before_ the cursor position).

In video form:

https://github.com/zed-industries/zed/assets/7998310/be04b948-ac76-4555-87db-ffd6c7dc35bf

### Environment

Zed: v0.142.4 (Zed Preview)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

**Comment by mrnugget** [comment] 2024-07-04 12:24
I cannot reproduce this:

https://github.com/zed-industries/zed/assets/1185253/49442d7e-226a-4f42-a3b2-ad9d7d6f6e6f

Two questions:
1. Can you reproduce it with an empty `keymap.json`?
2. What keyboard layout do you have?

**Comment by fasterthanlime** [comment] 2024-07-08 09:05
I can confirm that behavior seems to be caused by one of these in my keymap:

```jsonc
[
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "t w": "pane::CloseAllItems",
      "t k": "pane::ActivatePrevItem",
      "t j": "pane::ActivateNextItem",
    }
  }
]
```

With those commented out, `dt` behaves properly for me.

**Comment by mrnugget** [comment] 2024-07-08 09:39
Ah, that helps a lot! Thank you!

**Comment by mrnugget** [comment] 2024-07-12 08:14
This should be fixed by https://github.com/zed-industries/zed/pull/14233.

**Closed by mrnugget** 2024-07-12 08:14 UTC
Labels: defect, vim, keymap / key binding

**Comment by fasterthanlime** [comment] 2024-07-12 09:38
Just built zed from source to confirm — this does appear fixed!
