### ISSUE TITLE
Workspace Folder collapses unexpectedly

### ISSUE THREAD

**Issue by nigelmj** [zed-industries/zed#14491] opened 2024-07-15 12:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The folder in the workspace panel keeps collapsing at random. Sometimes when I am editing a file or when I switch between apps and come back to zed. There have been a few instances where it would collapse right after I open it.

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Moshyfawn** [comment] 2024-07-15 12:54
Is it possible that you have this setting enabled?

```json
"project_panel": {
  "auto_fold_dirs": true
}
```

**Comment by Moshyfawn** [comment] 2024-07-15 12:57
Oh, it seems to have been covered already, so I'm going to close this in favour of the one already created. Be sure to +👍 and follow the other thread instead.

Duplicate of:
- #13762

**Closed by Moshyfawn** 2024-07-15 12:57 UTC
Labels: defect, needs info / awaiting response, workspace, project panel, admin read
