### ISSUE TITLE
Wired behaviour in opening folders in the dock

### ISSUE THREAD

**Issue by kitro** [zed-industries/zed#12749] opened 2024-06-06 18:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I get I wired behaviour When I want to open a folder in the left dock it toggle inside the last folder name. 
Example I have this folders structure:
```
docker/
  8.0/
  8.1/
  8.2/
```
each folder `8.0`, `8.1` and `8.2` contains their own files . but when I open the folder `8.0` or `8.1` it will be open inside `8.2`. 

### Environment

macOs Montery 
Zed 0.138.4
45dbb8964e3a9d72dbc5bba8fb97f1fd63faee9a

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/5256921/80744fe8-f338-402a-8dd3-5ecc00dd7a9d

**Comment by SomeoneToIgnore** [comment] 2024-06-07 05:00
Looks like a duplicate of https://github.com/zed-industries/zed/issues/12470

**Closed by SomeoneToIgnore** 2024-06-07 05:00 UTC
Labels: defect, triage, admin read
