### ISSUE TITLE
Show more info in Typescript intellisense

### ISSUE THREAD

**Issue by jezikk** [zed-industries/zed#4457] opened 2023-09-21 12:04 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Actually It is very hard to work with Typescript intellisense in large projects where are multiple items with the same name.

1. More items with the same name from different resources:

VSCode
<img width="559" alt="vscode_trash" src="https://github.com/zed-industries/community/assets/7671531/2a69f8b9-02bf-46db-bb1f-9ed447d203e9">

Zed
<img width="321" alt="zed_trash" src="https://github.com/zed-industries/community/assets/7671531/1bd260ce-cf71-4cd1-a390-64a6285affbc">

2. It would be nice to show path:

VSCode
<img width="567" alt="vscode_popover" src="https://github.com/zed-industries/community/assets/7671531/fe4172f9-55f9-409d-a454-12d889c4fa8c">

Zed
<img width="544" alt="zed_popover" src="https://github.com/zed-industries/community/assets/7671531/e9331ee6-6db3-4149-9b47-2518114df6ca">

3. Intellisense is closed unexpectedly during writing
https://github.com/zed-industries/community/assets/7671531/7223bd31-47f3-4229-a053-a2f14b937960

**Comment by davidlgj** [comment] 2024-01-26 13:07
I'm having the same issue, exasperated by us using a monorepo in which you can import things more than one way (but only one is correct...)
<img width="409" alt="image" src="https://github.com/zed-industries/zed/assets/151694/8453491c-8879-462e-ae24-a73662da0aad">

The difference between `Button` and `Button` here is how they are imported 😅

**Comment by TudorEsan** [comment] 2024-02-24 07:24
Having the same issue 🙂

**Comment by arggh** [comment] 2024-04-29 08:33
This issue is literally the only thing preventing me from switching over to Zed. 

> I'm having the same issue, exasperated by us using a monorepo in which you can import things more than one way (but only one is correct...) 
> 
> The difference between `Button` and `Button` here is how they are imported 😅

Would be even better, if this became configurable, so that for certain imports, it would only ever display the correct import options (like using the package name instead of a relative path in a monorepo).

**Comment by osiewicz** [comment] 2024-05-24 00:02
Isn't this issue a duplicate of https://github.com/zed-industries/zed/issues/10075 ?

**Comment by trivikr** [comment] 2024-08-24 03:07
While trying to repro this, I noticed that Zed 0.149.5 on MacOS doesn't show any Intellisense

<details>
<summary>Zed</summary>

https://github.com/user-attachments/assets/ebc796c3-7a26-4a54-8a4d-11e44f531ce1

</details> 

<details>
<summary>VSCode</summary>

https://github.com/user-attachments/assets/786259ec-3826-4a1a-a524-b13d045f2cc7

</details>

**Comment by trivikr** [comment] 2024-08-24 03:13
I think this can be closed. The Intellisense shows the paths in Zed 0.149.5


https://github.com/user-attachments/assets/7311a101-cf65-46ff-83db-3f45125e37f2

**Closed** 2024-08-24 04:30 UTC
Labels: enhancement, typescript, javascript, language, popovers, autocompletions
