### ISSUE TITLE
Vertical scroll bar covers portion of text editor/caret for long lines

### ISSUE THREAD

**Issue by landaire** [zed-industries/zed#10809] opened 2024-04-20 17:42 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The vertical scroll bar in Zed covers just over 2 character's worth of horizontal space in the editor, making it difficult to see what's currently being edited.

This is 100% speculation but I think that the text component is laid out, then the minimap/scroll bar are laid out **on top** of the text component instead of **adjacent to** the text component. The following video captures the problem quite well:

https://github.com/zed-industries/zed/assets/1313522/d64f23e5-2ad3-4dfc-b70d-c7409f92d489

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.2.1
Memory: 24 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-04-20 19:48
This has already been reported, so I'm going to close this issue in favour of the one that already exists. Be sure to +👍 and follow the other thread.

Duplicate of:
- #7098

**Closed by Moshyfawn** 2024-04-20 19:48 UTC
Labels: defect, triage, admin read
