### ISSUE TITLE
Separate Themes from Extensions

### ISSUE THREAD

**Issue by sysdevoperations** [zed-industries/zed#9063] opened 2024-03-08 13:14 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hello Zed Team,

I was wondering if it would be possible to separate out themes from extensions.
As you can see they are both combined even though the functionality of themes are completely different from normal expectations for extensions.

If a filter can be added to help distinguish between the two that would be great for seeing very quickly what is available for themes vs extension.  As the only way to tell the difference is by the title and description.

<img width="1597" alt="Screenshot 2024-03-08 at 8 09 45 AM" src="https://github.com/zed-industries/zed/assets/24926817/f98cfbfb-7762-4010-b4ed-ec093beeed0d">

**Comment by jansol** [comment] 2024-03-08 13:26
Duplicate of #8848

**Comment by Moshyfawn** [comment] 2024-03-08 13:29
Be sure to +👍 the other issue to show your interest.

Duplicate of
- #8848

**Closed by Moshyfawn** 2024-03-08 13:29 UTC
Labels: enhancement, triage, admin read
