### ISSUE TITLE
Running "editor: fold all" in search results crashes Zed

### ISSUE THREAD

**Issue by adamchainz** [zed-industries/zed#19855] opened 2024-10-28 20:19 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Run "editor: fold all" in a populated search results page and Zed crashes.

(I was wondering if I can fold up the results to see just the matched filenames.)

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-28T20:15:36.628431Z [INFO] ========== starting zed ==========
2024-10-28T20:15:36.630825Z [INFO] Opening main db
2024-10-28T20:15:36.633575Z [INFO] Opening main db
2024-10-28T20:15:36.655572Z [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-10-28T20:15:36.926174Z [INFO] no tokio runtime found, creating one for Reqwest...
2024-10-28T20:15:36.955085Z [INFO] initializing context server client
2024-10-28T20:15:36.955492Z [INFO] Registering built-in prompt template: content_prompt
2024-10-28T20:15:36.95622Z [INFO] Registering built-in prompt template: edit_workflow
2024-10-28T20:15:36.956407Z [INFO] Registering built-in prompt template: project_slash_command
2024-10-28T20:15:36.956475Z [INFO] Registering built-in prompt template: step_resolution
2024-10-28T20:15:36.956806Z [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-10-28T20:15:36.957002Z [INFO] No prompt template overrides directory found at /Users/chainz/.config/zed/prompt_overrides. Using built-in prompts.
2024-10-28T20:15:36.958569Z [INFO] extensions updated. loading 9, reloading 0, unloading 0
2024-10-28T20:15:37.011785Z [INFO] Opening main db
2024-10-28T20:15:37.021594Z [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-28T20:15:37.167885Z [INFO] set status on client 0: Authenticating
2024-10-28T20:15:37.172662Z [INFO] Opening main db
2024-10-28T20:15:37.178835Z [INFO] Opening main db
2024-10-28T20:15:37.184074Z [INFO] set status on client 207815: Connecting
2024-10-28T20:15:37.211856Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.218724Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.224456Z [INFO] attempting to start language server "pyright", path: "/Users/chainz/Documents/Projects/django", id: 1
2024-10-28T20:15:37.240591Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.257932Z [INFO] Node runtime install_if_needed
2024-10-28T20:15:37.31868Z [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-28T20:15:37.32348Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.341336Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-10-28T20:15:37.363557Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.376414Z [ERROR] No path or contents found for buffer
2024-10-28T20:15:37.376492Z [ERROR] No path or contents found for buffer
2024-10-28T20:15:37.376551Z [ERROR] No path or contents found for buffer
2024-10-28T20:15:37.402129Z [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-28T20:15:37.407092Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.407484Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.419204Z [INFO] set environment variables from shell:/bin/zsh, path:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin:/Users/chainz/.local/share/mise/installs/usage/latest/bin:/Users/chainz/.local/share/mise/installs/bun/1.1/bin:/Users/chainz/.local/share/mise/installs/ruby/3.3/bin:/Users/chainz/.local/share/mise/installs/node/20/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin
2024-10-28T20:15:37.449937Z [INFO] attempting to start language server "pyright", path: "/Users/chainz/Documents/Projects/_mine/_open/django-watchfiles", id: 2
2024-10-28T20:15:37.483675Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.484152Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.486969Z [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-28T20:15:37.511627Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.512008Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.552218Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.552715Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.689406Z [INFO] attempting to start language server "pyright", path: "/Users/chainz/Documents/ElkRange/maroon-bells", id: 3
2024-10-28T20:15:37.746319Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.756194Z [INFO] starting language server process. binary path: "/Users/chainz/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/", args: ["/Users/chainz/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-10-28T20:15:37.780738Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.781106Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.781358Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.821197Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.821283Z [INFO] attempting to start language server "snippet-completion-server", path: "/Users/chainz/Documents/Projects/django", id: 4
2024-10-28T20:15:37.821648Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.821709Z [INFO] attempting to start language server "snippet-completion-server", path: "/Users/chainz/Documents/Projects/mystack", id: 5
2024-10-28T20:15:37.821857Z [INFO] attempting to start language server "snippet-completion-server", path: "/Users/chainz/Documents/Projects/_mine/_open/django-watchfiles", id: 6
2024-10-28T20:15:37.821933Z [INFO] attempting to start language server "esbonio", path: "/Users/chainz/Documents/Projects/_mine/_open/django-watchfiles", id: 7
2024-10-28T20:15:37.822148Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:37.82221Z [INFO] attempting to start language server "snippet-completion-server", path: "/Users/chainz/Documents/ElkRange/maroon-bells", id: 8
2024-10-28T20:15:37.857484Z [INFO] add connection to peer
2024-10-28T20:15:37.857553Z [INFO] add_connection;
2024-10-28T20:15:37.857599Z [INFO] waiting for server hello
2024-10-28T20:15:37.866477Z [INFO] got server hello
2024-10-28T20:15:37.866558Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 604, id: 107850 })
2024-10-28T20:15:37.866626Z [INFO] set status on client 207815: Connected { peer_id: PeerId { owner_id: 604, id: 107850 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-10-28T20:15:37.895194Z [INFO] using project environment variables shell launched in "/Users/chainz/Documents/Projects/django". PATH="/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin:/Users/chainz/.local/share/mise/installs/usage/latest/bin:/Users/chainz/.local/share/mise/installs/bun/1.1/bin:/Users/chainz/.local/share/mise/installs/ruby/3.3/bin:/Users/chainz/.local/share/mise/installs/node/20/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin"
2024-10-28T20:15:38.019599Z [INFO] fetching latest version of language server "pyright"
2024-10-28T20:15:38.031767Z [INFO] using project environment variables shell launched in "/Users/chainz/Documents/Projects/_mine/_open/django-watchfiles". PATH="/Users/chainz/.local/share/mise/installs/usage/latest/bin:/Users/chainz/.local/share/mise/installs/bun/1.1/bin:/Users/chainz/.local/share/mise/installs/ruby/3.3/bin:/Users/chainz/.local/share/mise/installs/node/20/bin:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin"
2024-10-28T20:15:38.032245Z [ERROR] Failed to start language server "esbonio": esbonio not installed
2024-10-28T20:15:38.032306Z [ERROR] server stderr: ""
2024-10-28T20:15:38.086141Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-10-28T20:15:38.082Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-10-28T20:15:38.082Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-10-28T20:15:38.090161Z [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "f4eda9eb-644c-4c68-a608-16b76945e0ae",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-10-28T20:15:38.092605Z [INFO] starting language server process. binary path: "/Users/chainz/Library/Application Support/Zed/extensions/work/snippets/simple-completion-language-server-v0.1.1/simple-completion-language-server", working directory: "/Users/chainz/Documents/Projects/django", args: []
2024-10-28T20:15:38.094964Z [INFO] using project environment variables shell launched in "/Users/chainz/Documents/Projects/mystack". PATH="/Users/chainz/.local/share/mise/installs/usage/latest/bin:/Users/chainz/.local/share/mise/installs/bun/1.1/bin:/Users/chainz/.local/share/mise/installs/ruby/3.3/bin:/Users/chainz/.local/share/mise/installs/node/20/bin:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin"
2024-10-28T20:15:38.09529Z [INFO] starting language server process. binary path: "/Users/chainz/Library/Application Support/Zed/extensions/work/snippets/simple-completion-language-server-v0.1.1/simple-completion-language-server", working directory: "/Users/chainz/Documents/Projects/mystack", args: []
2024-10-28T20:15:38.095849Z [INFO] starting language server process. binary path: "/Users/chainz/Library/Application Support/Zed/extensions/work/snippets/simple-completion-language-server-v0.1.1/simple-completion-language-server", working directory: "/Users/chainz/Documents/Projects/_mine/_open/django-watchfiles", args: []
2024-10-28T20:15:38.100361Z [INFO] using project environment variables shell launched in "/Users/chainz/Documents/ElkRange/maroon-bells". PATH="/Users/chainz/.local/share/mise/installs/node/18/bin:/Users/chainz/.local/share/mise/installs/usage/latest/bin:/Users/chainz/.local/share/mise/installs/bun/1.1/bin:/Users/chainz/.local/share/mise/installs/ruby/3.3/bin:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Users/chainz/bin/google-cloud-sdk/bin:/Applications/Inkscape.app/Contents/MacOS:/Users/chainz/.cargo/bin:/opt/homebrew/opt/postgresql@16/bin:/Users/chainz/.local/share/uv/python/cpython-3.12.6-macos-aarch64-none/bin:/Users/chainz/bin:/Users/chainz/script:/Users/chainz/.local/bin"
2024-10-28T20:15:38.100797Z [INFO] starting language server process. binary path: "/Users/chainz/Library/Application Support/Zed/extensions/work/snippets/simple-completion-language-server-v0.1.1/simple-completion-language-server", working directory: "/Users/chainz/Documents/ElkRange/maroon-bells", args: []
2024-10-28T20:15:38.399662Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-10-28T20:15:38.396Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-10-28T20:15:38.396Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-10-28T20:15:38.56755Z [INFO] downloading language server "pyright"
2024-10-28T20:15:39.87014Z [INFO] downloaded update. path:"/var/folders/20/lzgtdyzs7wj5fc_90w1h3bhc0000gn/T/zed-auto-update7UZLrg/Zed.dmg"
2024-10-28T20:15:40.470659Z [INFO] using project environment for language server LanguageServerName("pyright")
2024-10-28T20:15:40.470874Z [INFO] starting language server process. binary path: "/Users/chainz/.local/share/mise/installs/node/20/bin/node", working directory: "/Users/chainz/Documents/Projects/django", args: ["/Users/chainz/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-10-28T20:15:40.577442Z [INFO] using project environment for language server LanguageServerName("pyright")
2024-10-28T20:15:40.577607Z [INFO] starting language server process. binary path: "/Users/chainz/.local/share/mise/installs/node/20/bin/node", working directory: "/Users/chainz/Documents/Projects/_mine/_open/django-watchfiles", args: ["/Users/chainz/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-10-28T20:15:40.778254Z [INFO] language server 2: unregistered workspace/DidChangeWatchedFiles capability with id 621120a6-6eca-4758-83c0-5ac6d538e86c
2024-10-28T20:15:40.93492Z [INFO] using project environment for language server LanguageServerName("pyright")
2024-10-28T20:15:40.935061Z [INFO] starting language server process. binary path: "/Users/chainz/.local/share/mise/installs/node/20/bin/node", working directory: "/Users/chainz/Documents/ElkRange/maroon-bells", args: ["/Users/chainz/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-10-28T20:15:41.206742Z [INFO] language server 3: unregistered workspace/DidChangeWatchedFiles capability with id 2662c53e-9135-4821-9d9e-2663f596f9f2
2024-10-28T20:15:41.491385Z [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 156da02b-e5eb-40c1-8022-e72b12a6d22c
2024-10-28T20:15:42.700429Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.752954Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.753426Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.753826Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.756341Z [INFO] attempting to start language server "vtsls", path: "/Users/chainz/Documents/ElkRange/maroon-bells", id: 9
2024-10-28T20:15:42.756421Z [INFO] attempting to start language server "tailwindcss-language-server", path: "/Users/chainz/Documents/ElkRange/maroon-bells", id: 10
2024-10-28T20:15:42.756465Z [INFO] attempting to start language server "eslint", path: "/Users/chainz/Documents/ElkRange/maroon-bells", id: 11
2024-10-28T20:15:42.756517Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.771669Z [INFO] fetching latest version of language server "vtsls"
2024-10-28T20:15:42.773291Z [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-10-28T20:15:42.773524Z [INFO] fetching latest version of language server "eslint"
2024-10-28T20:15:42.773576Z [INFO] downloading language server "eslint"
2024-10-28T20:15:42.826265Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.826776Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.827156Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.890733Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.891219Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.891615Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.908413Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.913066Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.913627Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.914178Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.921768Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.923108Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.924307Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.925487Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.927121Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.949905Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.950403Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.950757Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.953356Z [INFO] attempting to start language server "vscode-css-language-server", path: "/Users/chainz/Documents/ElkRange/maroon-bells", id: 12
2024-10-28T20:15:42.953431Z [INFO] Initializing default prettier with plugins {}
2024-10-28T20:15:42.970501Z [INFO] fetching latest version of language server "vscode-css-language-server"
2024-10-28T20:15:43.138534Z [INFO] language server 2: unregistered workspace/DidChangeWatchedFiles capability with id 9737d5dd-6bd2-4ded-801b-7a40b005dae5
2024-10-28T20:15:43.472221Z [INFO] language server 2: unregistered workspace/DidChangeWatchedFiles capability with id 6a342c83-6aff-4d82-bde6-74fae33b738e
2024-10-28T20:15:43.557148Z [INFO] using project environment for language server LanguageServerName("eslint")
2024-10-28T20:15:43.558942Z [INFO] starting language server process. binary path: "/Users/chainz/.local/share/mise/installs/node/20/bin/node", working directory: "/Users/chainz/Documents/ElkRange/maroon-bells", args: ["--max-old-space-size=8192", "/Users/chainz/Library/Application Support/Zed/languages/eslint/vscode-eslint-2.4.4/vscode-eslint/server/out/eslintServer.js", "--stdio"]
2024-10-28T20:15:43.659104Z [INFO] language server 2: unregistered workspace/DidChangeWatchedFiles capability with id e0780f98-ba1c-4f76-906f-706b86bb3d61
2024-10-28T20:15:43.73637Z [ERROR] {
  "thread": "main",
  "payload": "called `Option::unwrap()` on a `None` value",
  "location_data": {
    "file": "crates/editor/src/display_map.rs",
    "line": 915
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "zed::reliability::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "core::panicking::panic",
    "core::option::unwrap_failed",
    "<editor::display_map::DisplaySnapshot>::starts_indent",
    "<editor::display_map::DisplaySnapshot>::foldable_range",
    "<editor::Editor>::fold_all",
    "editor::element::register_action::<editor::actions::FoldAll, <editor::Editor>::fold_all>::{closure#0}",
    "<gpui::window::WindowContext>::dispatch_action_on_node",
    "<gpui::window::WindowContext>::dispatch_event",
    "<gpui::window::Window>::new::{closure#10}",
    "gpui::platform::mac::window::handle_key_event",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "<gpui::app::App>::run::<zed::main::{closure#5}>",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.158.1",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "14.6.1",
  "architecture": "aarch64",
  "panicked_on": 1730146543736,
  "system_id": "8e240d19-b978-4038-9552-a5f569af9cf7",
  "installation_id": "913d6ef5-7fec-4f38-bda8-57ff14ac68ab",
  "session_id": "1c647482-9aa9-4567-95dc-8dc1f318abdd"
}
</pre></details>

**Comment by CharlesChen0823** [comment] 2024-10-29 00:48
same #19054

**Comment by mrnugget** [comment] 2024-10-29 10:16
Duplicate of https://github.com/zed-industries/zed/issues/19054 (thanks @CharlesChen0823)

**Closed by mrnugget** 2024-10-29 10:16 UTC
Labels: defect, triage, panic / crash, admin read
