### ISSUE TITLE
Not able to write @ ("at" sign)

### ISSUE THREAD

**Issue by tjconcept** [zed-industries/zed#21587] opened 2024-12-05 12:44 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm unable to type an @-sign. Nothing happens on hitting <kbd>option</kbd> + <kbd>'</kbd>, which is the shortcut on a Danish keyboard layout. Here's an image of the key:

![dakbd](https://github.com/user-attachments/assets/67ca1e91-5d1d-4ec6-86e5-91ae32335e92)

I'm equally frustrated that I have no idea how to debug this, and was not able to google my way to how either.

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 18 GiB
Architecture: aarch64

**Comment by tjconcept** [comment] 2024-12-05 12:51
Opening the key context view, hitting the key combination, it looks like this:

<img width="468" alt="Screenshot 2024-12-05 at 13 51 03" src="https://github.com/user-attachments/assets/42e6ddd8-c2e0-4606-b914-89e1770990aa">

**Comment by crob-tv2** [comment] 2024-12-05 15:08
I have the same issue, which is also discussed in https://github.com/zed-industries/zed/issues/21049

**Comment by notpeter** [comment] 2024-12-05 15:32
Duplicate of:
- https://github.com/zed-industries/zed/issues/21049

**Closed by notpeter** 2024-12-05 15:32 UTC
Labels: bug, triage, admin read
