### ISSUE TITLE
Unable to close the project

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9874] opened 2024-03-27 16:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have opened a project (folder) named `Daily notes`.
<img width="459" alt="Снимок экрана 2024-03-27 в 19 07 37" src="https://github.com/zed-industries/zed/assets/230824/acfcf4ff-4214-4ef6-be09-d3d3369ec955">

Now I want to close this project without opening another one. I have already closed all the buffers with `Cmd-W`. After this I tried `Shift-Cmd-W`. This closes the Zed window (Zed is still running). Here is what I see after clicking on Zed icon in a Dock:

<img width="459" alt="Снимок экрана 2024-03-27 в 19 07 57" src="https://github.com/zed-industries/zed/assets/230824/cdb2f2d2-52db-4404-961d-0f0b763ade58">

So far so good. But now if I close Zed and relaunch it - the `Daily notes` project is back:

<img width="459" alt="Снимок экрана 2024-03-27 в 19 07 37" src="https://github.com/zed-industries/zed/assets/230824/acfcf4ff-4214-4ef6-be09-d3d3369ec955">

So, how can I actually close the project?

### Environment

Zed: v0.128.3 (Zed Preview)
OS: macOS 12.7.4
Memory: 32 GiB
Architecture: x86_64

**Comment by jansol** [comment] 2024-03-27 17:32
Zed simply reopens the last project you had open when it launches (which arguably is often what you want). So if you open a different project (and close this one) and close zed, it will open the other project one next time.

I guess there could be a setting to open the welcome page or an empty project by default instead.

**Comment by VKondakoff** [comment] 2024-03-27 17:36
I'm often editing files, which are not part of any project. This is why I was asking how to close the previous project without opening another one.

**Comment by VKondakoff** [comment] 2024-03-27 19:12
It is interesting, that the project reopens even if I open another empty Zed window (`Shift-Cmd-N`) and close the previous one before closing the empty window. After relaunch - the project is back. ;)
Pretty sure this is not intended.

**Comment by Jaiminkapopara** [comment] 2024-03-28 05:37
> It is interesting, that the project reopens even if I open another empty Zed window (`Shift-Cmd-N`) and close the previous one before closing the empty window. After relaunch - the project is back. ;) Pretty sure this is not intended.

**Comment by notpeter** [comment] 2024-06-27 17:21
I'm going to close this as a duplicate of:
- #7759

Please 👍 that issue to vote and subscribe there to track the progress.
If this is in error, please leave a comment and/or reopen with clarification.

**Closed** 2024-06-27 17:21 UTC
Labels: defect, workspace, serialization
