### ISSUE TITLE
Allow filtering file tree by git "has-changes" status

### ISSUE THREAD

**Issue by pedrorolo** [zed-industries/zed#10704] opened 2024-04-17 22:50 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

There should be a checkbox in the edge of the file tree allowing to only show files that are uncommitted to git.

My motivation for this is that when using another editor I often prefer to navigate within my work  by using its git-ui file tree, which only contains the files that I am actually editing. Zed still lacks a proper git UI, thus we users are expected to use an external tool for it; however, an external tool can't provide the git-status based file navigation benefits that a interface within the editor can, thus this feature could be a quick win without having to implement a full-fledged git-ui within the editor with all the bells and wistles.

**Comment by pedrorolo** [comment] 2024-04-17 23:17
When thinking further about this I even had a more sophisticated idea around it: auto-close non-git-modified files after x minutes open and seen, thus allowing the the tabs to function as the list of non-git-modified files.

Question: Is this easy to implement as an extension?

**Comment by SomeoneToIgnore** [comment] 2024-04-18 07:13
IIRC, current extensions do not have any control over Zed UI elements, including closing any tabs in the panes, so impossible right now.

As for the "show only changed files" feature, it sounds like a nice idea to be done in Zed directly, as possible already and most probably needed for the project diff panel in the future.

**Comment by Moshyfawn** [comment] 2024-04-18 15:54
This sounds like #4367 to me. Let me know if it would be fair to merge this request with the original #4367.

**Comment by Moshyfawn** [comment] 2024-04-18 17:21
I'm going to close this issue in favour of the source panel one to keep the conversation in one place. Be sure to +👍 the other request and add any additional information you think is missing.

Let me know if you think this deserves it's own thread if you want to explore other options before the source panel is developed.

Duplicate of
- #4367

**Closed by Moshyfawn** 2024-04-18 17:21 UTC
Labels: enhancement, needs info / awaiting response, workspace, git, admin read, panel
