### ISSUE TITLE
Do live update on global text search without having to manually pressing `return`

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/zed#4489] opened 2023-09-11 19:08 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

If I do `cmd+shift+f` and enter some text into search:

<img width="507" alt="image" src="https://github.com/zed-industries/community/assets/6391776/15d5aece-cc92-4736-9632-dd6df94afa53">

I want the results to instantly show. I don't want to then press `return` every time I want to activate a search.

This is the behavior that happens in VSCode and it's amazing. 

Please add it.

**Comment by Moshyfawn** [comment] 2024-03-14 14:22
There is a new duplicate feature request that has already received more upvotes, so I'm going to close this one. Be sure to +👍 the other issue and add any missing information.

Duplicate of
- #4489

**Closed by Moshyfawn** 2024-03-14 14:22 UTC
Labels: enhancement, seach / project search
