### ISSUE TITLE
doesn't run zed on my machine

### ISSUE THREAD

**Issue by AbhimanyuAryan** [zed-industries/zed#18820] opened 2024-10-07 16:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I installed the visual studio deps and cmake. When I build zed. I am stuck here

```
   Compiling assistant v0.1.0 (D:\zed\crates\assistant)
   Compiling collab_ui v0.1.0 (D:\zed\crates\collab_ui)
   Compiling quick_action_bar v0.1.0 (D:\zed\crates\quick_action_bar)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3m 47s
     Running `target\debug\zed.exe`
[2024-10-07T17:15:39+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:39+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:40+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:40+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:40+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:40+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:40+01:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-07T17:15:41+01:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-07T17:15:41+01:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-07T17:15:41+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:42+01:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-10-07T17:15:42+01:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-10-07T17:15:42+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T17:15:42+01:00 ERROR assistant] no worktrees when constructing LocalLspAdapterDelegate
```

After this nothing happens

### Environment

Device name	
Full device name	
Processor	AMD Ryzen 7 8840U w/ Radeon 780M Graphics         3.30 GHz
Installed RAM	32.0 GB (31.3 GB usable)
Device ID	
Product IDSystem type	64-bit operating system, x64-based processor

Windows 11 23H2 OS Build 22631.4169

**Comment by notpeter** [comment] 2024-10-07 19:10
Duplicate of:
- https://github.com/zed-industries/zed/issues/18610

**Closed by notpeter** 2024-10-07 19:10 UTC
Labels: defect, triage, admin read
