### ISSUE TITLE
[ESLint] eslintClass.getRulesMetaForResults is not a function

### ISSUE THREAD

**Issue by ivansvlv** [zed-industries/zed#8263] opened 2024-02-23 10:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening a .js file (with `node_modules` installed in project) throws this error:

![CleanShot 2024-02-23 at 11 54 35@2x](https://github.com/zed-industries/zed/assets/16175855/bbb98690-0492-41c7-9c04-0311e6b94d17)

If you perform a global search on a big monorepo, it renders Zed irresponsive due to amount of errors popping up. "Open Output" doesn't open anything.

**Note**: This error didn't occur before.

### Environment

Zed: v0.123.3 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

I've redacted irrelevant parts with `???`:

```
2024-02-23T12:15:49+02:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-23T12:15:49+02:00 [INFO] 3 unhandled notification eslint/status:
{
  "uri": "file:///Users/???/???/Code/???/???/???/src/list/dispatch.js",
  "state": 3
}
2024-02-23T12:15:58+02:00 [INFO] 3 unhandled notification eslint/showOutputChannel:
[
  null
]
```

**Comment by SomeoneToIgnore** [comment] 2024-02-23 11:00
Can you please provide a project to reproduce this on?
Simple projects like https://github.com/koddsson/eslint-configs-demo do not seem to trigger that, unfortunately.

**Comment by SomeoneToIgnore** [comment] 2024-02-23 11:03
And also seems to be a duplicate of https://github.com/zed-industries/zed/issues/8229, let's consolidate there.

**Closed by SomeoneToIgnore** 2024-02-23 11:03 UTC
Labels: defect, triage, admin read
