### ISSUE TITLE
Explorer edge case: when resizing at low mouse acceleration it doesn't follow cursor, causes misclick

### ISSUE THREAD

**Issue by clo4** [zed-industries/zed#4951] opened 2023-03-13 22:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I ran into this while just resizing the pane. Just wanted it to be a tiny bit smaller, so I moved the cursor very slowly, and it caused a misclick on a file which was quite surprising. Here's a repro:

https://user-images.githubusercontent.com/52195359/224848039-f53695c7-23ff-43f8-844f-e404153d130b.mov

macOS makes it very difficult to disable acceleration so I can imagine this being something people run into every now and then. Low priority but QOL fix

### Environment

Zed: v0.76.1 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-27 21:23
I'm not able to reproduce this in current Zed, so I will close this issue out. If you run into it again, please open a new issue!

**Closed by JosephTLyons** 2024-07-27 21:23 UTC
Labels: defect, project panel
