### ISSUE TITLE
Theme from extension isn't recognized as valid value in settings

### ISSUE THREAD

**Issue by onx2** [zed-industries/zed#15108] opened 2024-07-24 18:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Problem**
Using a theme that was installed as an extension shows a warning in the settings file -> theme key. Check out the images below to see what it says.

**Expected behavior**
When a theme is installed via extension, it should be considered a valid option in the settings file.

### Environment

Zed: v0.145.1 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1346" alt="image" src="https://github.com/user-attachments/assets/4c692f4c-deac-47bd-b738-7ebe345a436c">
<img width="678" alt="image" src="https://github.com/user-attachments/assets/dd575463-0be5-4ef8-910c-d0e7c333df4a">
<img width="891" alt="image" src="https://github.com/user-attachments/assets/70a92fb1-f2dd-4ebf-a8a9-2754e6324e34">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-24 19:02
Duplicate of:
- https://github.com/zed-industries/zed/issues/14916

It'll only happen for the open Zed session. Next time you launch zed (or trigger the `zed: reload zed` action from the `cmd-shift-p` command palette) it'll go away.

Thanks for reporting @onx2, this duplicate reporting is what drove me to re-open that issue.

**Closed by notpeter** 2024-07-24 19:02 UTC
Labels: duplicate

**Comment by onx2** [comment] 2024-07-24 19:05
Thanks for the explanation!
