### ISSUE TITLE
Update copilot chat to support selection of models as copilot now supports Gemini, GPT, and Anthropic Clause models

### ISSUE THREAD

**Issue by PyDataBlog** [zed-industries/zed#20133] opened 2024-11-03 10:47 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently in VS Code, Code copilot chat supports all the big commercial models. Can the copilot chat be updated to do same?

![image](https://github.com/user-attachments/assets/13c56ac4-04b7-4020-bf11-74997f96738b)

**Comment by SomeoneToIgnore** [comment] 2024-11-03 10:56
Duplicate of https://github.com/zed-industries/zed/issues/19963
Will be handled by https://github.com/zed-industries/zed/pull/19968

**Closed by SomeoneToIgnore** 2024-11-03 10:56 UTC
Labels: enhancement, triage, admin read
