### ISSUE TITLE
When editing and saving files that do not have write permissions, there may be a hint or some auxiliary operations

### ISSUE THREAD

**Issue by weartist** [zed-industries/zed#10423] opened 2024-04-11 14:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

At present, when editing a file without write permissions, there is no prompt when the save occurs, and when you run the source code, you can indeed see the error message that you cannot save, but for the release version, the user may not be aware of it
I'm not sure if this feature is necessary, but for read-only files, we might be able to make them unable to edit and give a hint, or leave them as they are and let the user choose whether to try to change the permissions of the current file when saving, etc

### Environment

Zed: v0.130.5 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/17105034/24b8b0f4-8c6c-40dd-986c-178a94573c71

**Comment by hippietrail** [comment] 2024-04-22 10:10
I was about to file this issue. Similarly, trying to open a file you don't have permission to open just fails silently with no visible user-feedback, at least on Mac.

**Comment by Moshyfawn** [comment] 2024-08-18 03:03
We could probably merge this issue with #13259, since the goal of both is to prompt the user of the insufficient permissions.

**Comment by Moshyfawn** [comment] 2024-08-18 03:04
I'm going to close this in favour of the other issue, but feel free to object so we can reopen it.

Duplicate of:
- #13259

**Closed by Moshyfawn** 2024-08-18 03:04 UTC
Labels: enhancement, editor

**Comment by Moshyfawn** [comment] 2024-08-18 03:08
> Similarly, trying to open a file you don't have permission to open just fails silently with no visible user-feedback, at least on Mac.

There's a newly created #16383 specifically around opening files that you might want to +👍.
