### ISSUE TITLE
Pink window on startup

### ISSUE THREAD

**Issue by bhanuvrat** [zed-industries/zed#6962] opened 2024-01-29 04:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

shows a pink window with no components inside on start up

﻿
<img width="1039" alt="image" src="https://github.com/zed-industries/zed/assets/499894/c3d043d4-da26-40df-b431-6c5ad0ddc0be">

### Environment

cannot open command pallete to copy system specs.

apple m1 max
32 gb
mac os ventura 13.3

### If applicable, add mockups / screenshots to help explain present your vision of the feature

tried with last two versions 119.19 and 119.20

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-01-29T04:32:26 [INFO] ========== starting zed ==========
2024-01-29T04:32:26 [INFO] Opening main db
2024-01-29T04:32:27 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-01-29T04:32:27 [ERROR] crates/zed/src/zed.rs:538: EOF while parsing a value at line 1 column 0
2024-01-29T04:32:27 [INFO] Opening main db
2024-01-29T04:32:27 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/anuvrat/.mix/escripts:/opt/homebrew/opt/openjdk/bin:/usr/local/texlive/2021basic/bin/universal-darwin/:/usr/local/bin/flutter/bin:/Users/anuvrat/.cargo/bin:/Users/anuvrat/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin::/Users/anuvrat/.emacs.d/.local/straight/build-28.2/emacsql-sqlite/sqlite:/Users/anuvrat/.nix-profile/bin/:/Users/anuvrat/.mix/escripts:/opt/homebrew/opt/openjdk/bin:/usr/local/texlive/2021basic/bin/universal-darwin/:/usr/local/bin/flutter/bin:/Users/anuvrat/.cargo/bin:/Users/anuvrat/bin:/usr/local/bin:/Users/anuvrat/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
2024-01-29T04:32:27 [INFO] Node runtime install_if_needed
2024-01-29T04:32:28 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-01-29T04:32:28.095Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-01-29T04:32:28.095Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-01-29T04:32:28 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "49ac0d9f-ffbc-43cc-93c6-7667355ea12b",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-01-29T04:32:28 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-01-29T04:32:28.102Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-01-29T04:32:28.102Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-01-29T04:32:51 [INFO] downloaded update. path:"/var/folders/zx/svd595x50w1fwvg2tt5ygf040000gn/T/zed-auto-update.HWkx7FViXfQf/Zed.dmg"

**Comment by JosephTLyons** [comment] 2024-01-29 06:59
We've seen this happen a few times before, its very strange. Are you able to reproduce this faithfully?

- https://github.com/zed-industries/zed/issues/6390

**Comment by karakanb** [comment] 2024-01-29 15:28
Same happens to me as well, here are my device specs:
- 16" m2 pro, 32gb memory
- macOS Version 14.2.1 (23C71)

I downloaded Zed yesterday, tried it out, then closed it. Today I double clicked a markdown file and it brought up Zed automatically, and it had the pink screen. since then it has the same screen. There's no other window/popup visible on the pink screen.

**Comment by bhanuvrat** [comment] 2024-01-30 03:52
followed that thread.
reboot fixed it.
I hadn't rebooted in over 100 days.

thank you @JosephTLyons

**Closed** 2024-01-30 03:52 UTC
Labels: defect, macOS, gpui

**Comment by davebarrau** [comment] 2024-02-28 10:11
Just adding a tidbit here in case it's useful to others. I encountered this, and later found it was additionally affecting scrollback from functioning correctly in iTerm 2 as well, so definitely not a Zed problem per se. As with others, a reboot fixes it.
