### ISSUE TITLE
Basic Markdown Outliner Features

### ISSUE THREAD

**Issue by Feel-ix-343** [zed-industries/zed#14123] opened 2024-07-11 00:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Convenience features for editing markdown:
- Insert properly indented bullet points when creating a line after a list item
    - Do this when pressing return
    - Do this when pressing o in Vim mode
- insert properly indented task items following above behavior 
- Indent and de-indent list items along with sublist items
- Swap up and down list items along with their sublist items (this should be easy with tree-sitter, as it is in my neovim config)

Inspired by Logseq and other outliners

I am also wondering if there is a reason this was not implemented before.

**Comment by notpeter** [comment] 2024-07-11 05:52
Duplicate of 
- https://github.com/zed-industries/zed/issues/5089

Please vote 👍 on that issue and click subscribe to follow its progress.

**Closed by notpeter** 2024-07-11 05:52 UTC
Labels: enhancement, triage, admin read

**Comment by Feel-ix-343** [comment] 2024-07-11 14:45
thank you
