### ISSUE TITLE
Can not scroll hovered document with mouse if the hover is created by command/shortcut

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4728] opened 2023-05-26 12:37 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The hovered document can be scrolled if it is created by moving the mouse to the symbol.

But it can not be scrolled if it is created by calling `editor: hover` (or some shortcut). If the mouse is not under the symbol at the moment the command is called, moving the mouse caused the hover disappeared.

### Environment

Zed: v0.87.6 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 06:16
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 06:16 UTC
Labels: defect, editor, popovers
