### ISSUE TITLE
Code actions menu item sometimes wrapped and layout of the menu broken

### ISSUE THREAD

**Issue by noritada** [zed-industries/zed#8341] opened 2024-02-24 17:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Code actions menu item sometimes gets wrapped and layout of the menu gets broken.
(I don't know why, but the menu does not appear to be wide enough.)

#### Steps to reproduce the bug

1. Write Rust code `} else if vim.state().mode == Mode::VisualLine {` in a proper context.
2. Run `editor: toggle code actions` command
3. In the menu, find `Replace if with match`, whose word "match" is displayed below, overlapped by another menu item.

#### Additional information

- I use code actions occasionally, but this is the first time I have seen this phenomenon.
- `Replace if with match` is always the item that is shown wrapped in this code line. I have never seen any other item wrapped.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 13.6.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![ss 2024-02-25 1 38 36](https://github.com/zed-industries/zed/assets/20850/205699fa-17ec-4426-af80-f9f1ba6b2352)
![ss 2024-02-25 1 38 50](https://github.com/zed-industries/zed/assets/20850/3443cf49-ecb3-4be9-b0a9-e8a00e7e304f)
![ss 2024-02-25 1 39 16](https://github.com/zed-industries/zed/assets/20850/8ec3a165-f3d8-4732-8652-53bd072c5d01)
![ss 2024-02-25 1 39 31](https://github.com/zed-industries/zed/assets/20850/ef24b6aa-2954-4375-83f6-55d67b541e8b)
![ss 2024-02-25 1 39 45](https://github.com/zed-industries/zed/assets/20850/764ac389-433c-4af8-b1da-44901821501f)
![ss 2024-02-25 1 39 59](https://github.com/zed-industries/zed/assets/20850/ce7080c2-57b6-46b7-8cc6-1410ee5091aa)
![ss 2024-02-25 1 40 13](https://github.com/zed-industries/zed/assets/20850/644e4418-2118-4821-93d3-3060cd706f12)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

I have checked the log, but there was not a single record for the time period in question.

**Comment by noritada** [comment] 2024-02-25 07:24
Just a quick look at the code, but it seems to me that the problem is caused by the width of the menu being taken from the width of the menu item, which has the maximum number of characters. In this case, both of `Replace if with match` and `Extract into variable` have 21 characters length.

https://github.com/zed-industries/zed/blob/dbe1f48f95558aa5764c5ed0c87022291fb5800b/crates/editor/src/editor.rs#L842-L860

**Comment by Moshyfawn** [comment] 2024-03-03 17:03
I'm going to close this issue in favour of a newer one that simply has more upvotes. Be sure to +👍 the other topic and add any information you feel is missing.

**Comment by Moshyfawn** [comment] 2024-03-03 17:03
Duplicate of #8772

**Comment by Moshyfawn** [comment] 2024-03-03 17:04
Come to think of it, this is a well-written issue, so I'll close the other one instead. Sorry for the extra notifications.

**Comment by as-cii** [comment] 2024-03-11 15:41
This was fixed in https://github.com/zed-industries/zed/pull/9178, thanks for the bug report!

**Closed by as-cii** 2024-03-11 15:41 UTC
Labels: defect, popovers
