### ISSUE TITLE
Bidirectional cmd+click

### ISSUE THREAD

**Issue by Micnubinub** [zed-industries/zed#9259] opened 2024-03-13 03:52 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When you `cmd+click` it goes to a definition, at the moment which is good, but can we also `cmd+click` open a dialog showing the `callers` of the definition. See below (also including references to other files)

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="977" alt="image" src="https://github.com/zed-industries/zed/assets/4921356/9cea449a-9b57-4607-8cd5-acaee43518f1">

**Comment by JosephTLyons** [comment] 2024-03-13 04:58
Hey @Micnubinub

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5351

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

---

Also, this is being worked on right now! :)

https://github.com/zed-industries/zed/pull/9243

**Closed by JosephTLyons** 2024-03-13 04:58 UTC
Labels: enhancement, editor
