### ISSUE TITLE
Sidebar alternates between shown/hidden with every launch

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#4968] opened 2023-03-11 13:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I quit and re-launch Zed, the sidebar would become hidden, and with the next launch shown, and then hidden, and so on…

### Environment

Zed: v0.75.2 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

A demo:

https://user-images.githubusercontent.com/5619348/224486077-03ce24a6-915e-4cf1-bff5-842fec5c932f.mp4

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-27 20:57
I cannot reproduce this behavior in current Zed, so I'm going to close this issue out. If you hit it again, please open a new issue!

**Closed by JosephTLyons** 2024-07-27 20:57 UTC
Labels: defect, workspace
