### ISSUE TITLE
Vertical scrollbar in extension's page

### ISSUE THREAD

**Issue by palmeida1959** [zed-industries/zed#16326] opened 2024-08-15 23:47 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

The Zed extensions page has no vertical scrollbar and it is inconvenient to only be able to search using the search field.

**Comment by Moshyfawn** [comment] 2024-08-17 16:25
This case and a few others have already been mentioned in another issue, so I'm going to close this one in favour of the existing one to keep the conversation in one place. Be sure to +👍 the other thread.

Duplicate of:
- #15324

**Closed by Moshyfawn** 2024-08-17 16:25 UTC
Labels: enhancement, triage, admin read
