### ISSUE TITLE
Text rendering problem at the end of a large file ...  [+1 (👍)]

### ISSUE THREAD

**Issue by patrik64** [zed-industries/zed#20212] opened 2024-11-05 01:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

at least two similar issues already exist, but here is an easy, fast and consistent way to reproduce it: 

install cargo pants (https://crates.io/crates/cargo-pants):

```cargo install cargo-pants```

create the file in the zed root folder:

```cargo pants > result.txt```

the file size is about 2.5Gb 

open the file and go to the end of the file.

### Environment

Zed: v0.161.0 (Zed Dev 20eeb78251a866f8ccd86b0ced795e5f8a24cc02)
OS: macOS 14.6.1
Memory: 24 GiB
Architecture: aarch64

also on
linux - fedora 40 - (thinkpad x280)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![grafik](https://github.com/user-attachments/assets/2f6ded03-60b0-48f9-b0d8-81ad4fa62e57)
![grafik](https://github.com/user-attachments/assets/2c4831d3-3d65-4c0b-a7e1-2f3346d283a4)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-11-05 01:42
Duplicate of https://github.com/zed-industries/zed/issues/5355

**Closed by SomeoneToIgnore** 2024-11-05 01:42 UTC
Labels: triage, admin read
