### ISSUE TITLE
Allow adding images to the project by dragging and dropping the file

### ISSUE THREAD

**Issue by emersonjds** [zed-industries/zed#8074] opened 2024-02-20 16:52 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In many code editors, it is very common to drag and drop an image into the tool and it already understands that an image or any file, svg or gif, has been added.

Unfortunately in ZED this is not yet allowed, I believe it is a very valuable feature for the tool.

#goZED

Thanks for everyone's work

### If applicable, add mockups / screenshots to help present your vision of the feature

how it works today

https://github.com/zed-industries/zed/assets/12503997/22e69b1b-b404-4e2b-a080-d4a666cf7703

How it should work

https://github.com/zed-industries/zed/assets/12503997/48beb51b-30dd-412f-9735-1dd74ec39791

**Comment by jansol** [comment] 2024-02-20 17:48
Should this copy the image to the project directory too? Or only add it to the list of files in the side bar?

**Comment by emersonjds** [comment] 2024-02-20 18:21
@jansol You must copy the image to the directory and make the image available for use in the project from the path

**Comment by vultix** [comment] 2024-02-20 18:30
I'm surprised this doesn't work for all files and folders.  I'd expect anything you drag will be copied or moved to the target location. 

There should be a way to configure whether you copy, move, or ask

**Comment by jansol** [comment] 2024-02-20 19:03
Yeah, I agree that you should be able to move and rename any files regardless of whether Zed can open them or not.

**Comment by JosephTLyons** [comment] 2024-02-20 20:42
Thanks for the good suggestion, @emersonjds!

**Comment by zarifpour** [comment] 2024-02-25 17:41
Possible duplicate of: https://github.com/zed-industries/zed/issues/7386

**Comment by JosephTLyons** [comment] 2024-02-26 21:10
> Possible duplicate of: #7386

I think you may be right, it does seem like this is a more specific request of 

- #7386 

Let's close this out in favor of that one.

**Closed by JosephTLyons** 2024-02-26 21:10 UTC
Labels: enhancement, project panel
