### ISSUE TITLE
Terminal problem hushlogin

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12216] opened 2024-05-23 18:48 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode:
![image](https://github.com/zed-industries/zed/assets/20476002/11eb4c85-85fb-4444-bfeb-20e79a6d4c49)
Zed:
![image](https://github.com/zed-industries/zed/assets/20476002/873f8336-199d-44fa-89b4-5878b11a5f88)

**Comment by znycheporuk** [comment] 2024-05-23 19:54
Duplicate of https://github.com/zed-industries/zed/issues/4827

**Closed** 2024-05-23 22:58 UTC
Labels: enhancement, triage, admin read
