### ISSUE TITLE
Terminal splitting

### ISSUE THREAD

**Issue by RageLtd** [zed-industries/zed#16174] opened 2024-08-13 18:47 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Tabbed terminals are fantastic, but as a user I would like to be able to see the output of more than one terminal at once

## User Story

As a web developer I often have to run multiple microservices (or macroservices) at once to fulfill my work requirements. Being able to monitor the output from those services simultaneously is important

### Current behaviour:

1. Start one service in one tab
2. Start another service in another tab
3. have the services interact
4. User has to switch back and forth between the two tabbed terminal panes to see output and track the interaction

### Desired behaviour:

1. Start one service in one tab
2. Split terminal tab into two terminals
3. Start second service in newly split terminal
4. Have services interact
5. Observe interaction in real time without switching tabs

### If applicable, add mockups / screenshots to help present your vision of the feature

![split_term](https://github.com/user-attachments/assets/d42d71b7-6d46-45f8-ba05-63bdd4173c02)

**Comment by SomeoneToIgnore** [comment] 2024-08-13 21:34
Duplicate of https://github.com/zed-industries/zed/issues/4351

**Closed by SomeoneToIgnore** 2024-08-13 21:34 UTC
Labels: enhancement, triage, admin read
