### ISSUE TITLE
Drag or use keyboard command to open new app instances/app windows

### ISSUE THREAD

**Issue by sonaro** [zed-industries/zed#15836] opened 2024-08-06 04:53 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

For multi-display workstations, or workstations with very large displays, it would be very nice to be able to open multiple separate app instances/app windows so that it's easier to separate entire projects and other use cases.

In terms of action, dragging a pane outside of an existing app instance could create a new app instance with the corresponding project file as the first pane.

### If applicable, add mockups / screenshots to help present your vision of the feature

Not needed, just separate app instances.

**Comment by notpeter** [comment] 2024-08-06 14:56
Duplicate of:
- https://github.com/zed-industries/zed/issues/6722

**Closed by notpeter** 2024-08-06 14:56 UTC
Labels: enhancement, triage, admin read
