### ISSUE TITLE
[Feature] Add EOL setting, like "files.eol" in vscode

### ISSUE THREAD

**Issue by xgfone** [zed-industries/zed#12763] opened 2024-06-07 06:13 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In setting, add an option, such as `"eol"`, to apply the file automatically when newing a file.

Also, it is better to support to modify EOL of the current opened file.

**Comment by xgfone** [comment] 2024-06-07 06:17
Maybe duplicate of #5294??

**Comment by Moshyfawn** [comment] 2024-06-07 16:35
I'm closing this thread in favour of the one linked above, as they seem to be the same. Be sure to +👍 the other thread.

Duplicate of:
- 5294

**Closed by Moshyfawn** 2024-06-07 16:35 UTC
Labels: enhancement, triage, admin read
