### ISSUE TITLE
[Task]: Run test in rust with incorrect command

### ISSUE THREAD

**Issue by MrHeer** [zed-industries/zed#11914] opened 2024-05-16 14:00 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I click this icon to run a test.

<img width="444" alt="image" src="https://github.com/zed-industries/zed/assets/18595761/9835fcdb-7bca-4df0-b88b-fdfe2fccde4b">

Zed will execute this command in terminal.

<img width="593" alt="image" src="https://github.com/zed-industries/zed/assets/18595761/f1409ac1-af29-473c-a508-7c4a7e847774">

This command will run a lot of other tests.
> 
<details><summary>Details</summary>
<p>

     Running unittests src/bin/01.rs (target/debug/deps/01-fa6bf0f44e41994e)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.01s

     Running unittests src/bin/02.rs (target/debug/deps/02-a1ffed74751f6a75)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/03.rs (target/debug/deps/03-39ab69126ada9391)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/04.rs (target/debug/deps/04-eeedc5b007763b92)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/05.rs (target/debug/deps/05-a78e9b1955f8bf52)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/06.rs (target/debug/deps/06-a3eeb012d8ad8a47)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/07.rs (target/debug/deps/07-aae379819059c02d)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/08.rs (target/debug/deps/08-2f34a9c7bdf6dd96)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/09.rs (target/debug/deps/09-3eda29c2cbf797e7)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/10.rs (target/debug/deps/10-823223e9632c86ed)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/11.rs (target/debug/deps/11-60ae617d1360c44a)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/12.rs (target/debug/deps/12-85358d2a7282b092)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/13.rs (target/debug/deps/13-6bc0b76ab1e66df6)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/14.rs (target/debug/deps/14-fce44cb47f2eefd1)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/15.rs (target/debug/deps/15-711968d42f9ca180)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/16.rs (target/debug/deps/16-8340e17a0efedfbb)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/17.rs (target/debug/deps/17-a3fb6d0dc790002f)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.01s

     Running unittests src/bin/18.rs (target/debug/deps/18-0ab82c14a7fd55b5)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/19.rs (target/debug/deps/19-27f0e7e9b0c080fb)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s

     Running unittests src/bin/20.rs (target/debug/deps/20-1cc651aff78c4d59)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.02s

     Running unittests src/bin/21.rs (target/debug/deps/21-c054223283c42c63)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.02s

     Running unittests src/bin/22.rs (target/debug/deps/22-3f292167bf5c227d)

running 1 test
test tests::test_part_one ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s

</p>
</details> 

I'm doing something similar inside Visual Studio Code, and its command looks like this.

```
cargo test --package advent_of_code --bin 22 -- tests::test_part_one --exact --show-output
```

By the way, when I press this icon, the other icons are also pressed effect.

<img width="123" alt="image" src="https://github.com/zed-industries/zed/assets/18595761/e54f2469-e413-49fa-93ec-8b83bef457c7">

### Environment

Zed: v0.135.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-05-16 15:11
Thank you.

> By the way, when I press this icon, the other icons are also pressed effect.

Fixed in https://github.com/zed-industries/zed/pull/11846 and should come with Zed 0.137

The rest seems to be a duplicate of 

https://github.com/zed-industries/zed/issues/10968

so I will close this issue as a duplicate.

**Closed by SomeoneToIgnore** 2024-05-16 15:11 UTC
Labels: defect, triage, admin read
