### ISSUE TITLE
Global search: search on each query change, not on Enter

### ISSUE THREAD

**Issue by ComplexPlane** [zed-industries/zed#22303] opened 2024-12-20 20:43 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be very convenient if Zed's global search updated on each keystroke instead of requiring the user to press Enter each time to search. VSCode is performant enough to do this, I would assume that Zed is as well.

Ergonomically it does not make much of a difference for one-off searches, but when wanting to change the search query frequently (especially in response to live results, or during a refactor) it's very nice to have it just update automatically.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.2.0
Memory: 16 GiB
Architecture: aarch64

macOS Sequoia 15.2
16GB RAM

**Comment by JosephTLyons** [comment] 2024-12-20 22:03
Hey @ComplexPlane,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/9318

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, feel free to leave a comment here explaining the difference and we will reopen this issue.

**Closed by JosephTLyons** 2024-12-20 22:03 UTC
Labels: enhancement, search / project search
