### ISSUE TITLE
The TOML files in Rust do not show the versions of the dependencies.

### ISSUE THREAD

**Issue by rafael-arreola** [zed-industries/zed#15261] opened 2024-07-26 07:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Add any Rust dependency in the Cargo.toml file
example:

axum = "

enable autocomplete and the content shown in the image appears

![image](https://github.com/user-attachments/assets/355cee36-2891-4cb0-8061-aae823b76a88)

This happens in the latest versions of both stable and preview.

### Environment

Linux 6.9.9-arch1-1
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Address sizes: 48 bits physical, 48 bits virtual
Byte Order: Little Endian
CPU(s): 32
On-line CPU(s) list: 0-31
Vendor ID: AuthenticAMD
Model name: AMD Ryzen 9 5950X 16-Core Processor
CPU family: 25
Model: 33
Thread(s) per core: 2
Core(s) per socket: 16
Socket(s): 1
Stepping: 2
Frequency boost: enabled
CPU(s) scaling MHz: 60%
CPU max MHz: 5083.3979
CPU min MHz: 2200.0000
BogoMIPS: 6802.28

Gnome ( Wayland )

**Comment by SomeoneToIgnore** [comment] 2024-07-26 08:53
Duplicate of https://github.com/zed-industries/zed/issues/10630

**Closed by SomeoneToIgnore** 2024-07-26 08:53 UTC
Labels: defect, triage, admin read
