### ISSUE TITLE
Cannot able to sign in with different aaccount

### ISSUE THREAD

**Issue by devmadhavv** [zed-industries/zed#9693] opened 2024-03-22 12:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Click on Sign-out from top right corner
2. Click on Sign-in 

On clicking sign-in it logs in with the previous account from which I logged out

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-03-22T17:31:39+05:30 [INFO] set status on client 97587: SignedOut
2024-03-22T17:31:43+05:30 [INFO] set status on client 97587: Authenticating
2024-03-22T17:31:43+05:30 [INFO] set status on client 97587: Connecting
2024-03-22T17:31:43+05:30 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-03-22T17:31:44+05:30 [INFO] add connection to peer
2024-03-22T17:31:44+05:30 [INFO] waiting for server hello
2024-03-22T17:31:44+05:30 [INFO] got server hello
2024-03-22T17:31:44+05:30 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 3 }, peer id: PeerId { owner_id: 377, id: 139738 })
2024-03-22T17:31:44+05:30 [INFO] set status on client 97587: Connected { peer_id: PeerId { owner_id: 377, id: 139738 }, connection_id: ConnectionId { owner_id: 0, id: 3 } }

**Comment by Moshyfawn** [comment] 2024-03-22 12:54
This has been a known limitation for some time. Let's close this issue in favour of the other one to keep the conversation in one place. Be sure to +👍 the other issue.

Duplicate of
- #4724

**Closed by Moshyfawn** 2024-03-22 12:54 UTC
Labels: defect, triage, admin read
