### ISSUE TITLE
 Copy-paste doesn't work with non-English keyboard layouts

### ISSUE THREAD

**Issue by 0xdeafbeef** [zed-industries/zed#14319] opened 2024-07-12 10:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Add an alternative keyboard layout(e.g. Russian) and try to use ctrl-c or ctrl-v with it. Nothing will happen

### Environment

```
Zed: v0.143.6 (Zed)
OS: Linux Wayland fedora 40
Memory: 125 GiB
Architecture: x86_64
```

same with Xorg

**Comment by notpeter** [comment] 2024-07-12 18:56
Likely a duplicate of:

- https://github.com/zed-industries/zed/issues/14053

**Comment by 0xdeafbeef** [comment] 2024-07-12 19:57
> Likely a duplicate of:
> 
> - https://github.com/zed-industries/zed/issues/14053

Yep, sorry, didn't found it

**Closed** 2024-07-12 21:18 UTC
Labels: defect, workspace, linux, internationalization, keymap / key binding, linux-wayland
