### ISSUE TITLE
Integrated Terminal starts glitching when it is expanded beyond a certain point

### ISSUE THREAD

**Issue by Taru-garg** [zed-industries/zed#9423] opened 2024-03-15 22:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When the Integrated terminal is stretched/expanded, to the top of the screen it has a very weird behavior and makes it very hard to scale it back down

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/39818803/0a688954-fd8d-4ebe-8b4f-368b7c21e4ab

**Comment by Moshyfawn** [comment] 2024-03-19 19:07
Should be fixed in the latest Zed Preview. Feel free to reopen if it's not.

Duplicate of
- #8363

**Closed by Moshyfawn** 2024-03-19 19:07 UTC
Labels: defect, triage, admin read

**Comment by Taru-garg** [comment] 2024-03-20 14:10
Thanks will check on the latest preview version
