### ISSUE TITLE
Go to definition jumps to one line above the correct line

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/zed#5000] opened 2023-02-20 07:37 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See screenshot.
It jumps to one line above the correct one and even highlights the correct number of characters.
This is a typescript project and the function is defined in an `interface` in another file.

It consistently jump one line above the correct one for all member of the interface even after a restart of Zed. Sadly I can't share the exact code with you.

![Screenshot 2023-02-20 at 08 28 44](https://user-images.githubusercontent.com/19362696/220041771-eaa11dec-35a1-4e4b-ae51-e8b27b810c09.png)
![Screenshot 2023-02-20 at 08 28 53](https://user-images.githubusercontent.com/19362696/220041783-b48c8667-fb5c-4389-a1ea-7dd8fa981df4.png)

### Environment

Zed: v0.73.3 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-27 20:23
Since we don't have a reproduction case here, I'm going to close this issue out. If you hit it again with code you can share, please open a new issue!

**Closed by JosephTLyons** 2024-07-27 20:23 UTC
Labels: defect, editor
