### ISSUE TITLE
Dragging Terminal Window Slider To Top Of Screen Causes Bottom Part Of Terminal To Be Obscured

### ISSUE THREAD

**Issue by KyleDickersonComposer** [zed-industries/zed#16616] opened 2024-08-21 19:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

@

https://github.com/user-attachments/assets/2459be0d-5e3e-4f4c-8c2a-8ffac33781f0

### Environment

Zed: v0.149.3 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment] 2024-08-23 19:42
Hey @KyleDickersonComposer,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/12966

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-08-23 19:42 UTC
Labels: defect, terminal
