### ISSUE TITLE
Alt/option key related shortcuts not working in mac m1

### ISSUE THREAD

**Issue by auspy** [zed-industries/zed#10236] opened 2024-04-06 14:44 UTC
### Check for existing issues

- [X] Completed

### My device
Mac m1 8gb 256gb

### Description 
i tried adding custom keybindings base on alt/option key but they are not working.

Example of keybindings i tried:
```json
  {
    "context": "Editor && vim_mode == normal", 
    "bindings": {
      "alt-h": "editor::MoveToPreviousWordStart",
      "alt-l": "editor::MoveToNextWordEnd"
    }
  }
```

- the keybindings imported from vscode which contains option/alt key works fine.

### Environment

Mac m1 8gb 256gb

**Comment by jborkowski** [comment] 2024-04-21 17:41
Hey @auspy,

I've just tried reproducing your problem on my Mac, and I cannot. For me, everything works as expected. Here is my configuration:
```json
[
  {
    "context": "Editor && vim_mode == normal",
    "bindings": {
      "alt-h": "editor::MoveToPreviousWordStart",
      "alt-l": "editor::MoveToNextWordEnd"
    }
  }
]
```

I tried on macOS Sonoma 14.4.1 with Zed 0.131.6

**Comment by auspy** [comment] 2024-04-22 09:01
> Hey @auspy,
> 
> I've just tried reproducing your problem on my Mac, and I cannot. For me, everything works as expected. Here is my configuration:
> 
> ```json
> [
>   {
>     "context": "Editor && vim_mode == normal",
>     "bindings": {
>       "alt-h": "editor::MoveToPreviousWordStart",
>       "alt-l": "editor::MoveToNextWordEnd"
>     }
>   }
> ]
> ```
> 
> I tried on macOS Sonoma 14.4.1 and Zed 0.131.6. Could you give me any reproduction steps?

i am using macOS Sonoma 14.1.1 and zed 0.131.6. I tested the snippet you sent and it's not working

**Comment by jborkowski** [comment] 2024-04-22 09:19
Interesting, maybe macOS captures these shortcuts? 
I will try to reproduce this on a different MBP.

**Comment by notpeter** [comment] 2024-08-27 14:09
I am not able to reproduce this either, adding these keybinds worked as expected.

Your original snippet was not valid JSON (extra comma).  In the Zed version when this issue was filed, invalid json would (silently) prevent a keymap from being applied.  We've subsequently improved validation support to settings/keymaps which will automatically fix small issue (excess commas) and throw an error with an invalid configuration.

If you are still experiencing this issue, please feel free to comment and I'm happy to reopen.

**Comment by LogicKahanHai** [comment] 2024-09-20 09:02
Was any solution found for this? I am also not able to get these 'alt' specific key binds to work.

Here is my keymaps file

```json
  {
    "context": "Editor && vim_mode==normal",
    "bindings": {
      "alt-h": ["workspace::ActivatePaneInDirection", "Left"], // All of these don't work 
      "alt-j": ["workspace::ActivatePaneInDirection", "Down"],
      "alt-k": ["workspace::ActivatePaneInDirection", "Up"],
      "alt-l": ["workspace::ActivatePaneInDirection", "Right"]
    }
  },
  {
    "context": "Editor && vim_mode==normal && vim_operator == none && !VimWaiting",
    "bindings": {
      //... some other non-clashing keybinds
      
      "space m h": ["workspace::ActivatePaneInDirection", "Left"] // This works
    }

```

**Comment by notpeter** [comment] 2024-09-21 01:45
This may be a Sequoia specific issue. @auspy are you also running Sequoia?

**Comment by LogicKahanHai** [comment] 2024-09-26 06:38
> This may be a Sequoia specific issue.

@notpeter I think it is not that, cuz I was using zed for a few days before upgrading to Sequoia. 
I reckon it's related to `alt` key being auto-mapped to `option` key in the mac native keyboard and there are these annoying keystrokes with `option` key that get triggered when these combinations are pressed. I have also noticed a `?` appearing at the cursor location when I put the key combo. 

I am sorry, but I am fairly new to all of this (mac, vim, and zed) and when I researched a bit about this `?` appearing I found all these details. Is it possible that you have disabled those special characters and so you're zed is able to capture the `option` keystroke? If yes, can you please share some resource to do that? I tried stackoverflow's answer but it was very complicated for me to follow. Thanks for your help! :)

**Comment by eminalparslan** [comment] 2024-11-13 22:26
I had this issue with `alt-h` and `alt-k`, but not `alt-j` and `alt-l` which worked fine. This was caused by using a different keyboard layout (Turkish Q - Legacy) instead of U.S. English.

**Comment by notpeter** [comment] 2024-11-13 22:33
These should all be fixed in Zed Preview.
See the bottom of the release notes:
https://github.com/zed-industries/zed/releases/tag/v0.162.0-pre

**Closed by notpeter** 2024-11-13 22:33 UTC
Labels: bug, macOS, keymap / key binding
