### ISSUE TITLE
Error when running compiled version from source on windows

### ISSUE THREAD

**Issue by StumbDev** [zed-industries/zed#18782] opened 2024-10-06 14:04 UTC
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

I compiled zed on my Windows 11 machine with this command:
```powershell
cargo build
```

but after compiled it give me this error:
```powershell
 debug  .\zed.exe
[2024-10-06T10:58:22-03:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-06T10:58:23-03:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-06T10:58:24-03:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-06T10:58:24-03:00 ERROR blade_graphics::hal::init] Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } })
Zed failed to open a window: VulkanLoadingError(LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } })). See https://zed.dev/docs/linux for troubleshooting steps.
```

### Environment

OS: Windows 11 22H2 build 22621.3007
Processor: Intel Core i5-5200U
4GB of RAM

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/f20657ec-6029-4e8c-aa39-5f366251f273)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment] 2024-10-07 15:54
Hey @StumbDev, I don't have a Windows machine and haven't really looked at the error, but I do think that `cargo build` alone isn't enough. We have docs that mention a few other things that need to be ran first here:

- https://zed.dev/docs/development/windows

Can you run through these and see if you are still having issues?

**Comment by TaelinSu** [comment] 2024-10-08 09:50
I can compile the latest Zed repository with `cargo build --release` in Windows 11, but I can't open the `zed.exe`. I try double clicking the file or running `zed` command in powershell, no window appears. But the program does run in the background:

![image](https://github.com/user-attachments/assets/9ca6845f-f2fc-4afb-aa89-ecf9d9a031a3)

https://github.com/user-attachments/assets/3f4699ca-ebaf-4e40-a737-9ca85e38b730

**Comment by JohnnyWulgaru** [comment] 2024-10-08 11:44
This sounds like it is a duplicate of #18610

**Comment by cyrixsimon** [comment] 2024-10-15 12:43
Hi,

I get the same error on my Windows machine. The compile works but executing the binary raises the following error. 

`ERROR blade_graphics::hal::init] Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } })
Zed failed to open a window: VulkanLoadingError(LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } }))
 
Stack backtrace:
   0: std::backtrace_rs::backtrace::dbghelp64::trace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91`

**Comment by StumbDev** [comment] 2024-10-15 15:41
> Hi,
> 
> I get the same error on my Windows machine. The compile works but executing the binary raises the following error. 
> 
> `ERROR blade_graphics::hal::init] Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } })
> Zed failed to open a window: VulkanLoadingError(LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } }))
>  
> Stack backtrace:
>    0: std::backtrace_rs::backtrace::dbghelp64::trace
>              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91`

I got a way to run it in win64 via wsl

**Comment by cyrixsimon** [comment] 2024-10-15 16:42
> > Hi,
> > I get the same error on my Windows machine. The compile works but executing the binary raises the following error.
> > `ERROR blade_graphics::hal::init] Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } })
> > Zed failed to open a window: VulkanLoadingError(LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } }))
> > Stack backtrace:
> > 0: std::backtrace_rs::backtrace::dbghelp64::trace
> > at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src....\backtrace\src\backtrace\dbghelp64.rs:91`
> 
> I got a way to run it in win64 via wsl. I only tested it on Debian (wsl) and it worked but like it's a virtualisation it would be a bit laggy in some machines (my case)

How did you get it to work under WSL? Can you describe your solution here?

**Comment by StumbDev** [comment] 2024-10-20 22:05
> > > Hi,
> > > I get the same error on my Windows machine. The compile works but executing the binary raises the following error.
> > > `ERROR blade_graphics::hal::init] Missing Vulkan entry points: LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } })
> > > Zed failed to open a window: VulkanLoadingError(LibraryLoadFailure(LoadLibraryExW { source: Os { code: 126, kind: Uncategorized, message: "Das angegebene Modul wurde nicht gefunden." } }))
> > > Stack backtrace:
> > > 0: std::backtrace_rs::backtrace::dbghelp64::trace
> > > at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src....\backtrace\src\backtrace\dbghelp64.rs:91`
> > 
> > I got a way to run it in win64 via wsl. I only tested it on Debian (wsl) and it worked but like it's a virtualisation it would be a bit laggy in some machines (my case)
> 
> How did you get it to work under WSL? Can you describe your solution here? 
> 
> 

I literally just installed Debian with the wsl --install -d Debian and runned the command from the zed website, just that

**Closed** 2024-11-07 21:49 UTC
Labels: bug, windows, open source

**Comment by TheAjaykrishnanR** [comment] 2024-12-24 10:58
why is this issue closed ? How is being able to run this in wsl the appropriate solution ?
