### ISSUE TITLE
editor: sort import on save

### ISSUE THREAD

**Issue by avetisk** [zed-industries/zed#7624] opened 2024-02-09 16:39 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently sorting import is done manually through action menu.

It would be great to be able to have an option to sort them on save.

**Comment by JosephTLyons** [comment] 2024-02-09 19:57
Hey @avetisk,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5232

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-09 19:57 UTC
Labels: enhancement, triage, admin read

**Comment by avetisk** [comment] 2024-02-09 20:02
@JosephTLyons done!

Sorry, I only checked for the specific feature in the existing issues. Next time I'll take more time and check thoroughly  👍
