### ISSUE TITLE
File deletion is unintuitive

### ISSUE THREAD

**Issue by stoksc** [zed-industries/zed#21605] opened 2024-12-05 19:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

"UX Bug"...

If I left click and file, then right click another and press "delete", I get a modal asking if I want to delete two files. I clicked through it quickly and lost some uncommitted work. Of course this is my fault! But not entirely, I'd argue.

If I left click a file, then right click another and press "delete" _on VS Code_, I get a modal asking if I want to delete the one, right-clicked, file. By habit, this is what led to me hurrying through your modal.

If I left click a file on finder, then right click another and press "delete", just the right-clicked file goes to the trash can.

The behavior of zed is counter to almost every other tool I could find. I think this should be changed! Just my 2c. Otherwise zed is amazing, thanks for it.

### Environment

Latest MacOS

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by stoksc** [comment] 2024-12-05 19:17
If anyone in charge here agrees I'll send a pull, just let me know.

**Comment by notpeter** [comment] 2024-12-05 21:20
I can reproduce with the latest nightly.
The project panel selection code is a bit hairy but this is a bug and it should be fixed, yes.

**Comment by stoksc** [comment] 2024-12-06 04:20
Without a lot of due diligence I've opened https://github.com/zed-industries/zed/pull/21622. I tested it locally but could try to run / add tests for fun later, only had a few minutes to mess with it today. What's not sitting right with me is the code very intentionally has this behavior, it doesn't appear to be just a bug.

**Comment by stoksc** [comment] 2024-12-06 12:53
After sleep, I guess there is some subtlety here. If it is a shift click selection it should delete all, else it shouldn't. So that logic is still necessary.

**Comment by mindon** [comment] 2024-12-08 00:28
lost two files in a week... 😓 cannot find it back...

**Comment by arifd** [comment] 2024-12-08 14:08
Me too. And I'm not sure why this happened. I try to delete one, and it deleted another in the same directory. Please as a priority never hard delete... just move to trash!! 

I know undo is a hard feature, but the willingness for zed to just nuke files is crazy

**Comment by 0xtimsb** [comment] 2024-12-08 18:04
Thank you, @stoksc, for bringing up this issue!

I tried different file managers and VSCode and went with the approach that felt most intuitive. Please take a look at the PR above. If it feels right, we can move forward with it else we can discuss it here.

**Closed** 2024-12-09 02:13 UTC
Labels: bug, project panel, reproducible

**Comment by stoksc** [comment] 2024-12-09 06:13
Looks right to me! Nice fix, I felt there was something simple but couldn't find it.

**Comment by arifd** [comment] 2024-12-13 15:48
When can I expect to see this fix land in my binary (assuming my binary auto-updates)

I just nuked 3 files yet again(!!!) because of this (and because "delete" is permanent!)

This is really a show stopper. No feature of Zed makes up for lost time due to accidental hard deleting of work! 😢

**Comment by 0xtimsb** [comment] 2024-12-13 17:43
Sorry about that. It might take a few more days to land on Stable. For now, it's available in the latest Preview release (0.166.0), which you can grab at [https://zed.dev/releases/preview](https://zed.dev/releases/preview).

**Comment by notpeter** [comment] 2024-12-13 19:17
> When can I expect to see this fix land in my binary (assuming my binary auto-updates)

This was released as part of Zed v0.166.0 which is available now as part of Zed Preview and will become Zed Stable on Wednesday 2024-12-18.

**Comment by arifd** [comment] 2024-12-13 20:17
Great, thanks for the update!
