### ISSUE TITLE
Filter for extensions not working

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#11667] opened 2024-05-10 17:03 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It seems the filter search isn't working properly.
The search seems to only work for the title, but not for description or anything else.
In the example below it shouldn't find anything, but instead it seems to find an element.

<img width="1440" alt="Screenshot 2024-05-10 alle 19 00 40" src="https://github.com/zed-industries/zed/assets/20476002/456bebfb-bd45-41be-b7ac-0b7e27a63c92">

Filters that would be interesting to implement in the search:
```
author:NameUser
author:not:NameUser
Theme
not:Theme
```

**Comment by Moshyfawn** [comment] 2024-05-10 17:14
This has already been mentioned in another issue, so I'll close this one. Be sure to +👍 the other thread and add any missing information.

Duplicate of:
- #10340

**Closed by Moshyfawn** 2024-05-10 17:14 UTC
Labels: enhancement, triage, admin read
