### ISSUE TITLE
When expanding excerpts in multi-buffer overlapping excerpts within the same file should merge into one

### ISSUE THREAD

**Issue by exalted** [zed-industries/zed#21864] opened 2024-12-11 16:40 UTC
### Check for existing issues

- [X] Completed

Found:

* https://github.com/zed-industries/zed/issues/13513

### Describe the bug / provide steps to reproduce it

When expanding excerpts in a multi-buffer, overlapping excerpts (line number-wise) within the same file should merge into one. Otherwise, it gets confusing to parse, visually speaking, the multi-buffer with repeating lines.

### Environment

Zed: v0.165.4 (Zed Preview)
OS: macOS 15.1.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2024-12-11 at 17 32 07@2x](https://github.com/user-attachments/assets/b607f187-1e62-4d87-af9f-bf694461f5fa)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by exalted** [comment] 2024-12-11 16:59
@filipwiech thanks! I searched all the issues, but that issue didn't use the term `excerpt`, so I couldn't find it. ✌️

**Comment by filipwiech** [comment] 2024-12-11 17:05
No problem at all, just wanted to link the issues together. :slightly_smiling_face: Also, this might be even more relevant now, looking at the upcoming git diff view based on the multi-buffer (#21543). :+1:

**Comment by exalted** [comment] 2024-12-11 17:06
Cool stuff!

**Comment by jansol** [comment] 2024-12-11 18:10
Closing as a duplicate of #13513

**Closed by jansol** 2024-12-11 18:10 UTC
Labels: bug, triage, admin read
