### ISSUE TITLE
commenting tsx/jsx with ctrl-/ not working properly

### ISSUE THREAD

**Issue by khalil-cheddadi** [zed-industries/zed#16390] opened 2024-08-16 23:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in a jsx/tsx file, when commenting the render part , it only adds `//` to the start of the line which is normal behavior for a js file but this results errors in the case of tsx render method return, which should be `{/*[LINE]*/}`  instead

### Environment

Zed: v0.148.1 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 7.5 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics (ICL GT1) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot from 2024-08-17 00-15-46](https://github.com/user-attachments/assets/2b9ff137-75c8-45f6-87aa-4165a6b2640c)

**Comment by DaniumX** [comment] 2024-08-17 07:44
This is very annoying and I hope they prioritize fixing it. Typing out comments manually in jsx/tsx is so cumbersome.

**Comment by SomeoneToIgnore** [comment] 2024-08-17 10:15
Looks like a duplicate of https://github.com/zed-industries/zed/issues/16337 so I'll close this one.

Anybody is welcome to prioritize and work on https://github.com/tree-sitter/tree-sitter-typescript/issues/306 to fix this.

**Closed by SomeoneToIgnore** 2024-08-17 10:15 UTC
Labels: defect, triage, admin read
