### ISSUE TITLE
Add hover support for Tailwind (and if possible more generally CSS) classes

### ISSUE THREAD

**Issue by gawlk** [zed-industries/zed#9056] opened 2024-03-08 08:09 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I little window that appears with the CSS of a CSS class just like any other hover preview.

It works great in VS Code and it's very useful.

The feature was mentioned in: https://github.com/zed-industries/zed/issues/5830

But I didn't see anyone confirming that it's working and I tried any many different files and it doesn't for me

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot 2024-03-08 at 09 07 46](https://github.com/zed-industries/zed/assets/32246972/991af785-f17c-46c9-8484-e46eeb77029e)

**Comment by JosephTLyons** [comment] 2024-03-08 16:04
Hey @gawlk,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7947

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-03-08 16:04 UTC
Labels: enhancement, language, language server, tailwind css

**Comment by gawlk** [comment] 2024-03-08 16:53
Hey @JosephTLyons !

Sorry about that a tried several queries and somehow still missed it, very weird !

I'll definitely upvote it it's a very important feature for anyone using tailwind which at this point is quite some people. Really the only thing at this point (with the ts errors not showing) that prevents me from using Zed also for front end.

**Comment by gawlk** [comment] 2024-03-08 17:06
@JosephTLyons could you just confirm that the feature isn't implemented and there isn't a bug on my side ?

I'm like 90% sure that there was a pop up on hover with the CSS showing some months ago but now I'm not so certain

**Comment by SomeoneToIgnore** [comment] 2024-04-04 09:19
This is now available in [v0.130.0-pre](https://zed.dev/releases/preview/0.130.0).

![Screenshot 2024-04-04 at 12 17 49](https://github.com/zed-industries/zed/assets/2690773/e0db2078-6330-4f6f-8f32-59e7fc375b8b)

**Comment by klyuk88** [comment] 2024-04-04 09:45
How to enable support for .vue files? In vue files dont work ((
