### ISSUE TITLE
Customizable Font/Font Size for Inlay Hints

### ISSUE THREAD

**Issue by xvbcfj** [zed-industries/zed#17017] opened 2024-08-28 17:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode supports a few configurations for Inlay Hints including:
(https://code.visualstudio.com/docs/getstarted/settings)
```
  // Controls font family of inlay hints in the editor. When set to empty, the `editor.fontFamily` is used.
  "editor.inlayHints.fontFamily": "",

  // Controls font size of inlay hints in the editor. As default the `editor.fontSize` is used when the configured value is less than `5` or greater than the editor font size.
  "editor.inlayHints.fontSize": 0,
```

Please support such customizations.

**Comment by notpeter** [comment] 2024-11-26 16:59
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/15716

Because that issue is older and has more upvotes.
Please 👍 vote that issue and subscribe to track progress.
Thanks for reporting.

**Closed by notpeter** 2024-11-26 16:59 UTC
Labels: enhancement, editor, setting, font, inlay hints
