### ISSUE TITLE
Add Block Cursor in Editor

### ISSUE THREAD

**Issue by sanbox-irl** [zed-industries/zed#8801] opened 2024-03-04 04:11 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'd love to have block cursor support in Zed. Here's what it looks like in VSC:

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot 2024-03-03 at 11 10 41 PM](https://github.com/zed-industries/zed/assets/31973761/369a7107-99f7-439b-8b3b-d068862cc855)

**Comment by Moshyfawn** [comment] 2024-03-04 04:13
There's already a more general feature request for cursor shape configuration. Be sure to +👍 it if you're interested.

**Comment by Moshyfawn** [comment] 2024-03-04 04:13
Duplicate of #7203

**Closed by Moshyfawn** 2024-03-04 04:13 UTC
Labels: enhancement, triage, admin read

**Comment by sanbox-irl** [comment] 2024-03-04 04:16
ah jeez, thanks -- I just looked up "block cursor" and should have looked through all "cursor"

**Comment by Moshyfawn** [comment] 2024-03-04 04:17
No problem at all!
