### ISSUE TITLE
Dialogs should disappear after a few seconds

### ISSUE THREAD

**Issue by verhovsky** [zed-industries/zed#17924] opened 2024-09-17 06:06 UTC
It's annoying to have to click away from a dialog every few days. I don't even need to know that Zed was updated, but if you must tell me then please hide the dialog after a few seconds instead of making thousands of people click it.

<img width="496" alt="Screenshot 2024-09-17 at 00 06 07" src="https://github.com/user-attachments/assets/55b6fd18-de20-499c-a985-73212ec00f42">

This should apply to all dialogs, though you might want to have a setting per dialog for how many seconds it should take before it disappears automatically.

**Comment by felixmerz00** [comment] 2024-09-25 07:49
This issue is a duplicate of [#15740](https://github.com/zed-industries/zed/issues/15740), isn't it?

**Closed** 2024-09-25 08:53 UTC
Labels: enhancement, discoverability, installer / updater, popovers
