### ISSUE TITLE
clangd's (fix available) does not provide code actions

### ISSUE THREAD

**Issue by WeetHet** [zed-industries/zed#9776] opened 2024-03-25 15:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a C++ file, write
```c++
#include <iostream>
int main() {}
```

Clangd shows `Included header iostream is not used directly (fix available)` and actually provides the fixes for example in neovim with lspconfig, but not in zed. 

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1297" alt="Screenshot 2024-03-25 at 17 45 57" src="https://github.com/zed-industries/zed/assets/43210583/522ea10e-6a49-462a-a5b7-b22ef8e82340">
<img width="932" alt="Screenshot 2024-03-25 at 17 46 41" src="https://github.com/zed-industries/zed/assets/43210583/ac3872ec-a4d0-4be3-80c4-bee5d20b9c6f">

**Comment by JosephTLyons** [comment] 2024-03-26 18:12
Hey @WeetHet,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4757

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-03-26 18:12 UTC
Labels: defect, c++, language, c, language server
