### ISSUE TITLE
don't scroll my editor with mouse click

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#8517] opened 2024-02-28 06:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```rs
fn main() {
    let str = "123";
    let c = match str {
        "words1" => 1,
        "words2" => 1,
        "words3" => 1,
        "words4" => 1,
        "words5" => 1,
        "words6" => 1,
        "words7" => 1,
        "words8" => 1,
        "words9" => 1,
        _ => 1,
    };
    dbg!(c);
}
```

In VSCode, if I want to change "words1" to another word, I can double click the word, and change it.

<img width="403" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/d9d2a221-8fcf-4e37-b5b0-67bf715bc06e">

In Zed,

If I double click a word, because of the `auto scroll`, it will select another word, this is annoying. especially when I want to change words at the top area and bottom area.

![2024-02-28](https://github.com/zed-industries/zed/assets/11925432/fac14500-aa2d-45e0-8349-e841bcd198d2)

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-02-28 06:47
Duplicate of #5219

**Closed by Moshyfawn** 2024-02-28 06:47 UTC
Labels: defect, editor, admin read

**Comment by Moshyfawn** [comment] 2024-02-28 06:53
Be sure to leave +👍 reaction and perhaps a comment if you have any additional information on the matter in the original thread.
