### ISSUE TITLE
Displayed lines shift and overlap when viewing large files (line 16777217)

### ISSUE THREAD

**Issue by Dartt0n** [zed-industries/zed#17113] opened 2024-08-29 20:59 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Viewing & editing large files (1GB+) in Zed works almost perfectly for me, but sometimes I encounter weird display behaviour.  After several million lines, the displayed lines of code start to overlap:
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/deeb3c9b-d07b-48e3-9e4d-58999be1a7f3">
<img width="893" alt="image" src="https://github.com/user-attachments/assets/539a52e7-1412-4abd-a13c-8a3e41b6b41d">
However, this is a display error. Clicking on line with the cursor or navigating with the keyboard works fine. All the changes and edits are made correctly and the content changes accordingly.
<img width="894" alt="image" src="https://github.com/user-attachments/assets/f8e8f7e3-e8a1-4d10-8ded-7059bca61a3f">
This behaviour seems to be reproducible with any file and starts at lines around 16777217 (exactly at line 16777217):
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/a66261b4-bd4f-4dec-8cf1-4f27e02154e5">
<img width="940" alt="image" src="https://github.com/user-attachments/assets/2bb33182-ffcb-4871-8585-25e8f1396890">

### Environment

Zed: v0.150.4 (Zed)
OS: macOS 14.6.1
Memory: 8 GiB
Architecture: aarch64

**Comment by Dartt0n** [comment] 2024-08-29 21:08
Line 16777217 is `1000000000000000000000001` in binary, so  16777216 (the last "working" line) is `1000000000000000000000000`, so may be this is somehow related (uint24 overflow?)

**Comment by osiewicz** [comment] 2024-08-29 22:22
Nope, but close; it's f32 overflow and 16777216 is the last value that can be represented precisely: https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e

Closing this issue as it's a duplicate of https://github.com/zed-industries/zed/issues/5355

**Closed by osiewicz** 2024-08-29 22:22 UTC
Labels: defect, triage, admin read

**Comment by 0x2CA** [comment] 2024-08-30 07:30
> Nope, but close; it's f32 precision issue and 16777216 is the last value that can be represented precisely: https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e
> 
> Closing this issue as it's a duplicate of
> 
> * [Text rendering has glitches for pathologically large files #5355](https://github.com/zed-industries/zed/issues/5355);
> 
> thanks for taking the time to file out this issue though!

Is it possible to switch to `BigDecimal` to avoid these situations for such large numbers?
