### ISSUE TITLE
C++ enum variants and comments barely distinguishable in Ayu Mirage 

### ISSUE THREAD

**Issue by shahamran** [zed-industries/zed#20007] opened 2024-10-31 08:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing C++ files with Ayu Mirage theme, enum members and comments have almost the same color, which is very confusing in heavily documented enums.

Minimal example:
<img width="396" alt="image" src="https://github.com/user-attachments/assets/58d8a85f-ae91-4df8-a9b1-fb856ec4dcd7">

### Environment

Zed: v0.159.5 (Zed)
OS: macOS 14.7.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-31 17:52
If you would like to modify a particular theme you can easily copy theme json into `~/.config/zed/themes/` (e.g. [ayu.json](https://github.com/zed-industries/zed/blob/main/assets/themes/ayu/ayu.json)), change the names and customize colors as you see fit.

Alternatively you can use [theme overrides](https://zed.dev/docs/themes#theme-overrides) in your setting if you just want to override the comment coloration.
Something like this:
```json
  "experimental.theme_overrides": {
    "syntax": {
      "comment": {
        "color": "#D4C822"
      }
    }
  }
```

Closing as duplicate of: 
- #15521 

Please 👍 and subscribe to that issue. Feel free to also comment there with your example above.

**Closed by notpeter** 2024-10-31 17:52 UTC
Labels: defect, triage, admin read

**Comment by shahamran** [comment] 2024-10-31 22:43
Thanks @notpeter, this is helpful.
