### ISSUE TITLE
Markdown Code Highlight Bug

### ISSUE THREAD

**Issue by adityajideveloper** [zed-industries/zed#9464] opened 2024-03-17 18:19 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The problem is with the syntax highlight and is not working properly. Things which needs to be highlighted as they are code block are not highlighted when viewing or editing this markdown.

The Preview of Markdown works as expected, the issue is with the editor.

### Environment

Zed: 0.126.2
OS: Sonoma 14.1.2
Memory: 8GB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1470" alt="Screenshot 2024-03-17 at 11 26 24 PM" src="https://github.com/zed-industries/zed/assets/117935160/671d6b38-6cc0-40db-842d-6e737a8b8eb2">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[zed.log](https://github.com/zed-industries/zed/files/14628440/zed.log)

**Comment by slymax** [comment] 2024-03-18 10:45
I think there are a few issues with markdown highlighting

another one I noticed:

<img width="245" alt="Bildschirmfoto 2024-03-18 um 11 42 46" src="https://github.com/zed-industries/zed/assets/3922572/5f97a00d-b2d4-4e2f-90d7-faf32c78e3fb">

**Comment by slymax** [comment] 2024-03-18 10:57
related open issues: #8108, #4565, #5217

**Comment by Moshyfawn** [comment] 2024-03-19 18:26
I think this issue can be closed in favour of #8108, as it was created early last month. Be sure to +👍 and add any missing information.

Duplicate of
- #8108

**Closed by Moshyfawn** 2024-03-19 18:26 UTC
Labels: defect, triage, admin read
