### ISSUE TITLE
CRLF lines show as modified lines

### ISSUE THREAD

**Issue by naim94a** [zed-industries/zed#4293] opened 2024-01-04 22:45 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After cloning a git repository, I realized that files with CRLF line endings always show as modified lines (yellow marker on the left), regardless if they were modified or not (`git diff` output is empty).

### Environment

Zed: v0.118.1 (Zed)
OS: macOS 14.2.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by gianpaj** [comment] 2024-05-15 08:48
duplicate of https://github.com/zed-industries/zed/issues/5294

**Comment by SomeoneToIgnore** [comment] 2024-05-15 09:36
https://github.com/zed-industries/zed/pull/11519 could've helped with the diff issue.
Could you check Zed 0.136 when it's released today?

>  All lines are converted to LFs if I actually modify the file. 

will stay for now alas and could be solved as part of https://github.com/zed-industries/zed/issues/5294

**Comment by notpeter** [comment] 2024-10-13 18:03
I think this may have been solved by:
- #11519

@naim94a If you still experience this with a current build please comment and I'm happy to reopen.

**Closed by notpeter** 2024-10-13 18:03 UTC
Labels: defect, git

**Comment by willleeney** [comment] 2025-07-18 10:03
I'm getting this as a problem when I'm using the ai agent
