### ISSUE TITLE
Add some kind of an SQL viewer

### ISSUE THREAD

**Issue by SsNiPeR1** [zed-industries/zed#7695] opened 2024-02-12 16:52 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

An SQL (specifically, SQLite) viewer would be useful to observe your databases easily

### If applicable, add mockups / screenshots to help present your vision of the feature

Something like that: https://marketplace.visualstudio.com/items?itemName=qwtel.sqlite-viewer

**Comment by jansol** [comment] 2024-02-13 02:05
Duplicate of #4838

**Comment by SsNiPeR1** [comment] 2024-02-13 04:56
> Duplicate of #4838

whoops, overlooked

**Closed** 2024-02-13 07:54 UTC
Labels: enhancement, workspace, language
