### ISSUE TITLE
 Automatically senses that you can select and copy content with the mouse

### ISSUE THREAD

**Issue by ZeroHawkeye** [zed-industries/zed#12030] opened 2024-05-19 07:19 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

![image](https://github.com/zed-industries/zed/assets/161401688/b12fa0d2-0070-49ad-aa5a-692c9a8e063d)

I hope to add the function of selecting the content of the pop-up box with the mouse. This is very useful.

**Comment by MatinAniss** [comment] 2024-05-19 08:05
May be a duplicate of https://github.com/zed-industries/zed/issues/5236

**Closed** 2024-05-19 08:08 UTC
Labels: enhancement, mouse interaction, popovers
