### ISSUE TITLE
Arabic Characters Not Displaying Correctly in Code Editor 

### ISSUE THREAD

**Issue by CRY-D** [zed-industries/zed#14477] opened 2024-07-15 08:55 UTC
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

There is an issue with the code editor where Arabic characters do not display correctly under certain conditions. Specifically, when I start typing Arabic text on a new or empty line, nothing appears. However, if I start typing in English and then switch to Arabic, the Arabic characters display without any problem. Additionally, if the font used in the editor does not support Arabic characters, they appear as squares. This behavior is different from other editors like VS Code, where Arabic characters display correctly even if the font does not support them (e.g., using JetBrains Mono).

#### Steps to Reproduce
1. Open the code editor.
2. Start typing Arabic text on a new or empty line, for example: "مرحبا بالعالم".
3. Observe that nothing appears.
4. Now, start typing some English text first, for example: "Hello".
5. Switch to Arabic and type: "مرحبا بالعالم".
6. Observe that the Arabic characters display correctly this time if the font supports Arabic.
7. Change the font to one that does not support Arabic characters (e.g., JetBrains Mono).
8. Type Arabic text again and observe that characters appear as squares.
 
- what I think is that Arabic characters should display correctly regardless of the font's support for Arabic, similar to behavior in VS Code.
- 
![Screenshot_20240715_094726](https://github.com/user-attachments/assets/8317c8da-0820-4330-921a-f47013836444)
![Screenshot_20240715_094734](https://github.com/user-attachments/assets/33b7bd40-72da-4545-ae71-c09505ed2be8)
![Screenshot_20240715_094755](https://github.com/user-attachments/assets/483d8a7b-f5dd-4821-8ad2-61d12faf8ef8)

 

### Environment

OS: Manjaro Linux x86_64 
Kernel: 6.5.13-7
DE: Plasma 6.0.5 
Zed Editor: 0.139.3-1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by LaPingvino** [comment] 2024-07-15 11:29
On Linux font fallback is usually done through fontconfig. It looks like Zed doesn't do any font fallback on Linux at the moment.

**Comment by notpeter** [comment] 2024-07-15 21:18
I can confirm this works as expect on MacOS, so this only affects linux at the moment.

**Comment by ahmed-abdelrazek** [comment] 2024-07-18 23:41
on windows it render arabic backward and from ltr
![image](https://github.com/user-attachments/assets/f64f2956-6cef-4099-acab-af0a130f78c9)

it should be
طلب سيئ
but what is rendered ئ.يس ب.لط without the dots

**Comment by apricotbucket28** [comment] 2024-07-27 16:03
Font fallback on Linux has been fixed in a recent version (you're using a Zed version released prior to the official Linux launch). And RTL text not working properly is a known issue: https://github.com/zed-industries/zed/issues/7465

**Comment by notpeter** [comment] 2024-10-17 14:02
I believe [`buffer_font_fallbacks`](https://zed.dev/docs/configuring-zed#buffer-font-fallbacks) is still only supported on MacOS and Windows (not Linux). So I believe this is still a valid issue; and here's the issue for RTL:
- https://github.com/zed-industries/zed/issues/7465

**Comment by apricotbucket28** [comment] 2024-10-17 21:20
If copy the text in the example while using the default font, it renders correctly:
![image](https://github.com/user-attachments/assets/cd0b70be-c3f7-49da-8982-66ae4498609d)

> I believe [buffer_font_fallbacks](https://zed.dev/docs/configuring-zed#buffer-font-fallbacks) is still only supported on MacOS and Windows (not Linux)

That probably should be tracked as part of https://github.com/zed-industries/zed/issues/13951

**Closed** 2024-10-17 21:38 UTC
Labels: defect, linux, internationalization, font
