### ISSUE TITLE
Edit title of the terminal

### ISSUE THREAD

**Issue by priyankarpal** [zed-industries/zed#14480] opened 2024-07-15 09:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Say you're working on a project. You need to open a few terminal sessions, but the title changes according to the folder names when you navigate to the folder. It would be great if we could customize it according to our preferences. 

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/ca609822-314f-4610-b5c0-ed5c543d00e3)

**Comment by notpeter** [comment] 2024-07-15 13:54
Duplicate of:
- https://github.com/zed-industries/zed/issues/11023

Please 👍 to vote that issue and subscribe over there to track its progress.
Thanks for reporting

**Closed by notpeter** 2024-07-15 13:54 UTC
Labels: duplicate
