### ISSUE TITLE
[Linux] Incorrect rendering of the hide/show rows buttons

### ISSUE THREAD

**Issue by judemvm** [zed-industries/zed#15232] opened 2024-07-25 22:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Incorrect rendering of the hide/show rows buttons.
You can see that the button has something like a line at the top.

### Environment

Zed: v0.145.1 (Zed)
OS: Ubuntu 22.04 jammy
Memory: 32 GiB
Architecture: x86_64
DE: GNOME 41.7
GPU: NVIDIA GeForce RTX 2060
GPU Driver Version: 550.90.07

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[bug.webm](https://github.com/user-attachments/assets/1269f1e5-1d92-4117-85f6-f8db93741e2f)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-26T05:58:56.277344985+08:00 [INFO] ========== starting zed ==========
2024-07-26T05:58:56.310840164+08:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-07-26T05:58:56.310884199+08:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-07-26T05:58:56.316430287+08:00 [INFO] Try connect ibus
2024-07-26T05:58:56.316953387+08:00 [INFO] perform;
2024-07-26T05:58:56.317007061+08:00 [INFO] read_command;
2024-07-26T05:58:56.317057242+08:00 [INFO] read_command;
2024-07-26T05:58:56.317228555+08:00 [INFO] Opening main db
2024-07-26T05:58:56.317279036+08:00 [INFO] socket reader;
2024-07-26T05:58:56.317799335+08:00 [INFO] new;
2024-07-26T05:58:56.318542638+08:00 [INFO] keep_updated;
2024-07-26T05:58:56.318987082+08:00 [INFO] Using git binary path: None
2024-07-26T05:58:56.356831099+08:00 [ERROR] theme not found: New Darcula
2024-07-26T05:58:56.357507308+08:00 [INFO] extensions updated. loading 8, reloading 0, unloading 0
2024-07-26T05:58:56.387700397+08:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-26T05:58:56.387797106+08:00 [INFO] Opening main db
2024-07-26T05:58:56.388977997+08:00 [INFO] XConnected server on 33554440, transport version: 0.0, TRANSPORT_MAX: 20
2024-07-26T05:58:56.389213219+08:00 [INFO] perform;
2024-07-26T05:58:56.389275816+08:00 [INFO] read_command;
2024-07-26T05:58:56.389392926+08:00 [INFO] read_command;
2024-07-26T05:58:56.389524977+08:00 [INFO] socket reader;
2024-07-26T05:58:56.390278852+08:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2024-07-26T05:58:56.390325335+08:00 [INFO] Creating colormap 46137347
2024-07-26T05:58:56.427667969+08:00 [INFO] Enabling color space support
2024-07-26T05:58:56.454367849+08:00 [WARN] Rejecting Intel for not presenting when Nvidia is present (on Linux)
2024-07-26T05:58:56.458805176+08:00 [INFO] Adapter "NVIDIA GeForce RTX 2060"
2024-07-26T05:58:56.458883824+08:00 [INFO] Ray tracing is supported
2024-07-26T05:58:56.581291659+08:00 [INFO] Using surface present mode FIFO_RELAXED
2024-07-26T05:58:56.583129325+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-26T05:58:56.645350347+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-26T05:58:56.645430427+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-26T05:58:56.645484154+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-26T05:58:56.678734672+08:00 [INFO] Refreshing at 6943 micros
2024-07-26T05:58:56.687580254+08:00 [WARN] Acquire failed because the surface is out of date
2024-07-26T05:58:56.689995854+08:00 [INFO] Using surface present mode FIFO_RELAXED
2024-07-26T05:58:56.690155921+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-26T05:58:56.698629604+08:00 [WARN] Unknown request DestroyIcReply { input_method_id: 2, input_context_id: 81 }
2024-07-26T05:58:56.699610159+08:00 [INFO] Opening main db
2024-07-26T05:58:56.702351294+08:00 [WARN] Unknown request DestroyIcReply { input_method_id: 2, input_context_id: 83 }
2024-07-26T05:58:56.710914404+08:00 [WARN] GPU frame is out of date
2024-07-26T05:58:56.712078607+08:00 [WARN] Acquire failed because the surface is out of date
2024-07-26T05:58:56.712677204+08:00 [INFO] Using surface present mode FIFO_RELAXED
2024-07-26T05:58:56.712856563+08:00 [WARN] Unable to forbid exclusive full screen
2024-07-26T05:58:56.716213368+08:00 [ERROR] No path stored for this editor
2024-07-26T05:58:56.737784711+08:00 [INFO] Initializing default prettier with plugins {}
2024-07-26T05:58:56.737839739+08:00 [INFO] starting language servers for Markdown: 
2024-07-26T05:58:56.737926414+08:00 [INFO] Initializing default prettier with plugins {}
2024-07-26T05:58:56.737985914+08:00 [INFO] starting language servers for Markdown: 
2024-07-26T05:58:56.946975438+08:00 [INFO] set environment variables from shell:/usr/bin/zsh
2024-07-26T05:58:57.27153911+08:00 [INFO] Initializing default prettier with plugins {}
2024-07-26T05:58:57.271589865+08:00 [INFO] starting language servers for Markdown: 
2024-07-26T05:59:00.577738015+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-26T05:59:00.584507027+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-26T05:59:00.587782373+08:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-26T05:59:00.594768379+08:00 [INFO] Creating a descriptor pool for at most 256 sets
</pre></details>

**Comment by apricotbucket28** [comment] 2024-07-26 00:01
Duplicate of https://github.com/zed-industries/zed/issues/12352

**Closed** 2024-07-26 00:35 UTC
Labels: defect, triage, admin read
