### ISSUE TITLE
Line rendering bug after last update

### ISSUE THREAD

**Issue by Kurt1968** [zed-industries/zed#8056] opened 2024-02-20 11:45 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hi there, thank you for your work on Zed, after the last update I'm experiencing a strange bug on line rendering.
The rendered lines do not fill the whole screen but tend to render while scrolling, zooming seems to resolve for a second but then it comes back.

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/47362261/f750dc1e-95f8-4c56-b183-3d555d95f5ea

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jansol** [comment] 2024-02-20 16:45
What GPU do you have there? There's been #5062 reported before which sounds vaguely similar, and seems to be specific to macs with NVIDIA GPUs.

**Comment by Kurt1968** [comment] 2024-02-20 17:37
> What GPU do you have there? There's been #5062 reported before which sounds vaguely similar, and seems to be specific to macs with NVIDIA GPUs.

I do have an Nvidia 750M indeed,I had not seen the issue you cited before, actually I experienced another problem a few minutes ago, the visual bug caused a shift of line order in a file I was working on. The only strange thing is that it started happening just after the last update and not from the beginning as in #5062

**Comment by JosephTLyons** [comment] 2024-02-20 19:20
Hey @Kurt1968,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7411

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-20 19:20 UTC
Labels: defect, triage, admin read

**Comment by lhps** [comment] 2024-02-21 21:01
[Zed.log](https://github.com/zed-industries/zed/files/14365065/Zed.log)
