### ISSUE TITLE
doc string theme color

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#10627] opened 2024-04-16 15:02 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

display doc strings similar to jetbrains(other color, hide '///' and indicator on the side)

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="167" alt="Screenshot 2024-04-16 at 17 00 35" src="https://github.com/zed-industries/zed/assets/121750393/7c8b6fa5-1632-4952-9bff-5fce5555d277">

<img width="134" alt="Screenshot 2024-04-16 at 17 00 20" src="https://github.com/zed-industries/zed/assets/121750393/7bcfa401-18ec-4917-9bf3-48dff4a6d04e">

**Comment by Moshyfawn** [comment] 2024-04-16 17:48
I think this falls under #4296.

I'm going to close this thread in favour of the other one. Be sure to +👍 and add any additional information to it.

Duplicate of:
- #4296

**Closed by Moshyfawn** 2024-04-16 17:48 UTC
Labels: enhancement, triage, admin read
