### ISSUE TITLE
[BUG] cannot open images for preview

### ISSUE THREAD

**Issue by vitalics** [zed-industries/zed#7681] opened 2024-02-12 06:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

#206 already described the error message: `stream did not contain valid UTF-8. Please try again.`

Try to open `.png`, `.jpg`, `.ico`, `.jpeg` file
<img width="1230" alt="image" src="https://github.com/zed-industries/zed/assets/8816260/d5035bbb-4b8c-42af-acd2-da4f601ce43e">

### Environment

OS: macOS 14.3.1 23D60 arm64
Kernel: 23.3.0
CPU: Apple M2 Pro

Zed: 0.121.7
Hash: dc78995feeb71abc7fadaf242665e7a6fad2ee5a

### If applicable, add mockups / screenshots to help explain present your vision of the feature

VS Code successfully opened selected image

<img width="1318" alt="image" src="https://github.com/zed-industries/zed/assets/8816260/4fd4176f-9b59-411f-bc87-19e5d8c6cc92">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

``` txt
2024-02-12T10:17:14+04:00 [ERROR] stream did not contain valid UTF-8
```

**Comment by SomeoneToIgnore** [comment] 2024-02-12 08:21
Duplicate of https://github.com/zed-industries/zed/issues/5251 but indeed Zed should rather ignore such clicks entirely than showing an error message.

**Closed by SomeoneToIgnore** 2024-02-12 08:21 UTC
Labels: defect, triage, admin read
