### ISSUE TITLE
Zed not remembering my last project on opening

### ISSUE THREAD

**Issue by dhruvkaushik305** [zed-industries/zed#15730] opened 2024-08-03 09:58 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open zed, it should open the previous files that were open. It is instead opening a new untitled file. Even though i have added the "restore_on_startup" to "last session", it is still not working

### Environment

I am sorry, I didn't understand how to run this command palette action so my answer would vary. My system is Ubuntu 22 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/371498c8-9cfd-4fd8-8f14-ce778cfc2860)

### If applicable, attach your Zed.log file to this issue.

[log.txt](https://github.com/user-attachments/files/16479002/log.txt)

**Comment by apricotbucket28** [comment] 2024-08-03 12:59
Duplicate of https://github.com/zed-industries/zed/issues/15642

**Comment by dhruvkaushik305** [comment] 2024-08-03 14:24
Makes so much sense, thank you so much :)

**Comment by mrnugget** [comment] 2024-08-05 07:54
Closing since #15642 is also closed now.

**Closed by mrnugget** 2024-08-05 07:54 UTC
Labels: defect, triage, admin read
