### ISSUE TITLE
Open file from cli into current editor session.

### ISSUE THREAD

**Issue by eneiford** [zed-industries/zed#7998] opened 2024-02-19 04:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

A cli flag to allow opening a text file from outside the current project path in the current editor session.  Currently if outside the current project path, executing `zed <filename>`  will open a new editor window even if launched from the terminal pane.

This would be helpful when bouncing between log files and would allow quick buffer navigation between files that don't necessarily belong in the same project.

Maybe a cli flag to add current  working directory as folder to project would be sufficient.  As soon as the directory is added to the Project, files open in the existing session as expected.

**Comment by JosephTLyons** [comment] 2024-02-20 19:05
Hey @eneiford,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4861

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-20 19:05 UTC
Labels: enhancement, cli
