### ISSUE TITLE
More decipherable error diagnostics

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#18624] opened 2024-10-02 11:09 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Here are some differences in the error diagnostics display.

For example on vscode you can expand or contract for each file that contains an error.
For each file you can know how many errors the file contains.

If it were possible to have a more readable design, it's a bit confusing, scrolling quickly you can't understand where the errors of one file begin compared to another.

| Zed | Vscode |
| -- | -- |
| <img width="1439" alt="Screenshot 2024-10-02 alle 12 48 09" src="https://github.com/user-attachments/assets/fc78dca6-8f1b-4d13-9361-a5ae792de892"> | <img width="418" alt="Screenshot 2024-10-02 alle 12 48 44" src="https://github.com/user-attachments/assets/c76a7a5a-87e3-4ad6-81d9-48ad44d54b11"> | 
| <img width="1439" alt="Screenshot 2024-10-02 alle 12 51 32" src="https://github.com/user-attachments/assets/896c4bb5-a3c8-40a7-95fc-33a71ccc6716"> | <img width="1004" alt="Screenshot 2024-10-02 alle 12 52 10" src="https://github.com/user-attachments/assets/d189674f-3b79-4c9c-95f8-e47dd600522e"> |
| <img width="1439" alt="Screenshot 2024-10-02 alle 12 56 18" src="https://github.com/user-attachments/assets/0b28ad50-c3b3-4b5a-b636-faa58a93d62b"> | <img width="812" alt="Screenshot 2024-10-02 alle 12 56 43" src="https://github.com/user-attachments/assets/e63fdb8c-c126-4d5e-9746-004ed6c315dc"> |

**Comment by notpeter** [comment] 2024-10-13 19:26
This sort of display is available Outline view (cmd-shift-b) in the left dock.
<img width="573" alt="Screenshot 2024-10-13 at 15 23 54" src="https://github.com/user-attachments/assets/b9c5c75e-7f52-497c-ba02-5684ef14b3ce">

Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/18672

**Closed by notpeter** 2024-10-13 19:26 UTC
Labels: enhancement, triage, admin read
