### ISSUE TITLE
Assistant New Context Not Working On Remote Server

### ISSUE THREAD

**Issue by Supremesource** [zed-industries/zed#18107] opened 2024-09-19 23:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

To reproduce:
- connect to remote server over ssh
- open assistant new context 
- nothing opens up

### Environment

Manjaro linux, connecting to ubuntu server 
Zed version `0.153.6`

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-20 13:15
Duplicate of:
- https://github.com/zed-industries/zed/issues/17898

**Closed by notpeter** 2024-09-20 13:15 UTC
Labels: duplicate
