### ISSUE TITLE
Deleting selected file also deletes opened file

### ISSUE THREAD

**Issue by ExposedCat** [zed-industries/zed#22038] opened 2024-12-15 10:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open any file, click RMB on any other file, click Delete - prompt window will ask about deleting 2 files instead of 1 - it includes opened file as if it was selected.

I've just deleted file I've been working on for an hour and didn't commit yet, I didn't notice popup confirmation mentioned open file too

I found #21707 but I still have this issue in latest Stable

### Environment

Linux, Fedora 41
Zed 0.165.4

**Comment by 5brian** [comment] 2024-12-15 19:11
#21707 is included in 0.166 preview, not out in stable yet

**Comment by notpeter** [comment] 2024-12-16 03:36
Duplicate of:
- https://github.com/zed-industries/zed/issues/21605

**Closed by notpeter** 2024-12-16 03:36 UTC
Labels: bug, triage, admin read
