### ISSUE TITLE
improper rendering of ascii characters for some files using default zed font

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#16528] opened 2024-08-20 15:51 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

if i try to display a file that uses a lot of whitespace and ascii characters for formatting, such as [this one](https://github.com/qmk/qmk_firmware/blob/557e4e7ffca754b323d383b967af788d0d88790b/keyboards/keebio/iris/keymaps/via/keymap.c#L15), it is illegible. 

Switching from the zed font to something like "buffer_font_family": "FiraCode Nerd Font Mono",` fixes the issue

# zed
![image](https://github.com/user-attachments/assets/5e10c371-0327-4145-99e4-cb706ee158d8)

# vscode
![image](https://github.com/user-attachments/assets/8b6015af-9198-4c31-9742-1a9db224fdb3)

# github
![image](https://github.com/user-attachments/assets/96d9d0e1-89df-4246-bc34-20b481d8d1f8)

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-20 16:15
Yeah there's something wonky with the default font (Zed Plex Mono) box drawing characters. 

Duplicate of:
- https://github.com/zed-industries/zed/issues/15542

**Closed by notpeter** 2024-08-20 16:15 UTC
Labels: duplicate
