### ISSUE TITLE
Terminal binding doesn't work properly with ctrl + ` shortcut on abnt2 on wayland 

### ISSUE THREAD

**Issue by gabriel-araujjo** [zed-industries/zed#15076] opened 2024-07-24 09:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using Linux, wayland and an abnt2 layout keyboard, the <code>ctrl + `</code> shortcut doesn't work properly.

The first time I pressed the combo, a grave accent (<code>`</code>) appears on the editor, and only when I press them twice, the bottom panel opens and receives focus, but the grave accent is typed on the cursor position.

Additional info: The grave accent, present on the combo, is accessed only when the shift key is active. See the keyboard layout bellow:

![2016-06-21-900px-kb-portuguese-brazilsvg-](https://github.com/user-attachments/assets/ef722bb2-0d7e-4e10-b82f-4a197320a874)

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland arch unknown
Memory: 23.2 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Screencast from 2024-07-24 06-09-55.webm](https://github.com/user-attachments/assets/5dea7c2f-e94a-4ff6-b0ed-283b1a9c5143)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-24T06:31:00.967376459-03:00 [INFO] ========== starting zed ==========
2024-07-24T06:31:01.149779537-03:00 [INFO] perform;
2024-07-24T06:31:01.149881254-03:00 [INFO] read_command;
2024-07-24T06:31:01.149958519-03:00 [INFO] read_command;
2024-07-24T06:31:01.15018403-03:00 [INFO] socket reader;
2024-07-24T06:31:01.150510549-03:00 [INFO] new;
2024-07-24T06:31:01.150883126-03:00 [INFO] Opening main db
2024-07-24T06:31:01.151745698-03:00 [INFO] keep_updated;
2024-07-24T06:31:01.153911443-03:00 [INFO] Using git binary path: None
2024-07-24T06:31:01.195472298-03:00 [INFO] set environment variables from shell:/usr/bin/fish, path:/home/gabriel/.go/bin:/home/gabriel/.cargo/bin:/usr/lib/ccache/bin:/home/gabriel/.npm-packages/bin:/home/gabriel/.local/bin:/home/gabriel/.sdkman/candidates/springboot/current/bin:/home/gabriel/.deno/bin:/home/gabriel/.config/netlify/helper/bin:/home/gabriel/.opam/default/bin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2024-07-24T06:31:01.251615718-03:00 [ERROR] theme not found: Adwaita Pastel Light
2024-07-24T06:31:01.254475168-03:00 [INFO] extensions updated. loading 4, reloading 0, unloading 0
2024-07-24T06:31:01.254721937-03:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-24T06:31:01.257908002-03:00 [INFO] Opening main db
2024-07-24T06:31:01.258560815-03:00 [INFO] perform;
2024-07-24T06:31:01.258637046-03:00 [INFO] read_command;
2024-07-24T06:31:01.258790907-03:00 [INFO] read_command;
2024-07-24T06:31:01.260119664-03:00 [INFO] socket reader;
2024-07-24T06:31:01.274247646-03:00 [INFO] new;
2024-07-24T06:31:01.278114542-03:00 [INFO] keep_updated;
2024-07-24T06:31:01.283535983-03:00 [INFO] Enabling Vulkan Portability
2024-07-24T06:31:01.283579808-03:00 [INFO] Enabling color space support
2024-07-24T06:31:01.290095656-03:00 [INFO] Adapter "Intel(R) HD Graphics 620 (KBL GT2)"
2024-07-24T06:31:01.29015858-03:00 [INFO] No ray tracing extensions are supported
2024-07-24T06:31:01.294717731-03:00 [INFO] Using surface present mode MAILBOX
2024-07-24T06:31:01.295320987-03:00 [WARN] Unable to forbid exclusive full screen
2024-07-24T06:31:01.295978264-03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-24T06:31:01.29614235-03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-24T06:31:01.296297903-03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-24T06:31:01.309536817-03:00 [INFO] set status on client 0: Authenticating
2024-07-24T06:31:01.30988072-03:00 [INFO] perform;
2024-07-24T06:31:01.309955909-03:00 [INFO] read_command;
2024-07-24T06:31:01.310588828-03:00 [INFO] read_command;
2024-07-24T06:31:01.310967189-03:00 [INFO] Opening main db
2024-07-24T06:31:01.311044533-03:00 [INFO] socket reader;
2024-07-24T06:31:01.323777816-03:00 [INFO] new;
2024-07-24T06:31:01.325881523-03:00 [INFO] keep_updated;
2024-07-24T06:31:01.339479996-03:00 [INFO] Using surface present mode MAILBOX
2024-07-24T06:31:01.340091278-03:00 [WARN] Unable to forbid exclusive full screen
2024-07-24T06:31:01.341997194-03:00 [INFO] set status on client 191170: Connecting
2024-07-24T06:31:01.343829607-03:00 [INFO] Opening main db
2024-07-24T06:31:01.456111195-03:00 [ERROR] No worktree for path: "/home/gabriel/.config/zed/keymap.json"
2024-07-24T06:31:01.884711456-03:00 [INFO] Node runtime install_if_needed
2024-07-24T06:31:01.942871013-03:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-24T06:31:02.497670328-03:00 [INFO] starting language server. binary path: "/home/gabriel/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/gabriel/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-24T06:31:02.524107903-03:00 [INFO] add connection to peer
2024-07-24T06:31:02.524179093-03:00 [INFO] add_connection;
2024-07-24T06:31:02.524246708-03:00 [INFO] waiting for server hello
2024-07-24T06:31:02.524546885-03:00 [INFO] got server hello
2024-07-24T06:31:02.524597773-03:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 454, id: 766016 })
2024-07-24T06:31:02.524691229-03:00 [INFO] set status on client 191170: Connected { peer_id: PeerId { owner_id: 454, id: 766016 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-24T06:31:03.236597003-03:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-24T09:31:03.226Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-24T09:31:03.226Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-24T06:31:03.237867672-03:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "6e5056ff-0ba6-4fed-97df-7bf46fdabad6",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-24T06:31:03.932312225-03:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 1,
  "message": "[INFO] [auth] [2024-07-24T09:31:03.930Z] Invalid copilot token: missing token: 403 ",
  "metadataStr": "[INFO] [auth] [2024-07-24T09:31:03.930Z]",
  "extra": [
    "Invalid copilot token: missing token: 403 "
  ]
}
2024-07-24T06:31:03.932609535-03:00 [INFO] Language server with id 0 sent unhandled notification window/showMessageRequest:
{
  "type": 2,
  "message": "No access to GitHub Copilot found. You are currently logged in as gabriel-araujjo.",
  "actions": [
    {
      "title": "Sign up for GitHub Copilot"
    },
    {
      "title": "Dismiss"
    }
  ]
}
2024-07-24T06:31:03.949537096-03:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-24T09:31:03.941Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-24T09:31:03.941Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-07-24T06:31:05.404404055-03:00 [INFO] Initializing default prettier with plugins {}
2024-07-24T06:31:05.404472745-03:00 [INFO] starting language servers for Shell Script: 
2024-07-24T06:31:05.404611068-03:00 [INFO] Initializing default prettier with plugins {}
2024-07-24T06:31:05.404662458-03:00 [INFO] starting language servers for Shell Script: 
</pre></details>

**Comment by gabriel-araujjo** [comment] 2024-07-28 13:01
cc @non-descriptive

**Comment by notpeter** [comment] 2024-07-28 13:52
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/14053

Which is related to this:
- https://github.com/zed-industries/zed/issues/12811

The grave accent <kbd>`</kbd> / tilde `~` key in particular seems to be a particularly problematic character.

**Closed by notpeter** 2024-07-28 13:52 UTC
Labels: defect, triage, admin read
