### ISSUE TITLE
Local Theme override

### ISSUE THREAD

**Issue by bhanusanghi** [zed-industries/zed#19503] opened 2024-10-21 06:51 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently zed allows overriding themes globally using the `experimental.themeOverrides` in the global settings.json file.
However, allowing theme overrides per project using the local settings file allows for far deeper levels of customisation that are apt and necessary for modern editors.
This unlocks high levels of dev productivity by reducing the cognitive load on devs working with multiple projects which is often the case.

### If applicable, add mockups / screenshots to help present your vision of the feature

NA

**Comment by notpeter** [comment] 2024-10-21 17:53
Duplicate of:
- https://github.com/zed-industries/zed/issues/13300

**Closed by notpeter** 2024-10-21 17:53 UTC
Labels: enhancement, triage, admin read

**Comment by CaptainCodeAU** [comment] 2026-06-03 05:55
This is still very much needed. the global experimental override exists, the only missing piece is letting it live in the project .zed/settings.json.

Adding the angle I haven't seen mentioned much: for some of us this is accessibility, not customization. I'm dyslexic with ADHD, and color is genuinely how I keep track of which window is which. text labels don't register for me. when I've got several projects open they're all visually identical and I waste a stupid amount of focus all day just orienting myself. a per project title bar color would remove that entirely.

VSCode and Cursor already do this with workbench.colorCustomizations per workspace. it's one of the few things still pulling me back there.
