### ISSUE TITLE
IntelliJ Keybinding not working

### ISSUE THREAD

**Issue by StefanGrubmueller** [zed-industries/zed#7737] opened 2024-02-13 17:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Intellij provides the shortcut "shift shift" which is used to find files inside the project (VS Code = cmd-p). I would expect this keybinding to work after manually adding it into the keymap.json.
<img width="492" alt="image" src="https://github.com/zed-industries/zed/assets/68783852/ce15a512-daa3-445e-9199-50a19fb6f857">

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-13 18:19
Hey @StefanGrubmueller,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/6460

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-13 18:19 UTC
Labels: defect, keymap / key binding
