### ISSUE TITLE
Open Git-ignored file

### ISSUE THREAD

**Issue by thomaseizinger** [zed-industries/zed#17814] opened 2024-09-13 21:19 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Sometimes, I want to open a file that is ignored from version control. Currently, those appear to be excluded from the "Search project files" pop-up.

For example, I have a test that produces many output log files, numbered by the test-run, i.e. `1.log` all the way potentially `4xxx.log`. Running the test tells me which one failed and I'd like to open that one in in a buffer.

Currently, the only way how I can do this is open the directory in the project pane and scroll until I can find the file manually. Given that I know the exact file name, it would be nice to be able to just jump to it.

**Comment by Moshyfawn** [comment] 2024-09-14 00:39
This has already been requested and is being investigated by one of the community members. Be sure to +👍 the other thread.

Duplicate of:
- #4745

**Closed by Moshyfawn** 2024-09-14 00:39 UTC
Labels: enhancement, triage, admin read
