### ISSUE TITLE
Error while doing an update

### ISSUE THREAD

**Issue by marpit19** [zed-industries/zed#7941] opened 2024-02-17 05:51 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried updating Zed but it's giving this error. Could you guys help me with this on how to fix this? I think I might be missing something out. A walkthrough would be greatly appreciated thanks!

I tried to do an auto update.

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.2.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/54642576/a0053b15-c61d-4199-8ecd-f05e41d1409a)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment] 2024-02-17 09:56
This is a duplicate of https://github.com/zed-industries/zed/issues/7909 so I'll close it, it also has less relevant information.
The error itself is biting me too, but I have good walkthrough for it yet: it seems that we need to understand which timeout is that and set a bigger one — the current one is overly generic and used for many operations where small value makes sense, but for this particular case it's not suitable.

**Closed by SomeoneToIgnore** 2024-02-17 09:56 UTC
Labels: defect, triage, admin read

**Comment by marpit19** [comment] 2024-02-17 10:01
Oops didn't check if the issue was already there. I might have missed out. Sorry

**Comment by SomeoneToIgnore** [comment] 2024-02-17 10:35
No worries at all, that one is hard to find due to odd naming.
