### ISSUE TITLE
[Linux] zed doesn't open Sign-in Link in my browser 

### ISSUE THREAD

**Issue by No0ne003** [zed-industries/zed#14392] opened 2024-07-13 10:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when I click sign-in on github from zed it doesn't open any link in my browser and I think I have solution.

using xdg-open {url} that command will open on the default browser.

### Environment

Zed: v0.143.6-1 
OS: Arch Linux
Memory: 8 GB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by coder3112** [comment] 2024-07-13 15:24
Duplicate of https://github.com/zed-industries/zed/issues/14028?

**Comment by JVPH** [comment] 2024-07-13 23:37
Are you using Sway? I had the same issue. The problem was that [xdg-desktop-portal-wlr](https://wiki.archlinux.org/title/XDG_Desktop_Portal) needed the XDG_CURRENT_DESKTOP and WAYLAND_DISPLAY environment variables to be set.

So the fix was to:

- run
```
$ systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
$ dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=compositor_name
```
- create the file /usr/share/sway/config.d/50-systemd-user.conf with these [contents](https://aur.archlinux.org/cgit/aur.git/tree/50-systemd-user.conf?h=sway9)

**Comment by No0ne003** [comment] 2024-07-14 10:23
i use wayland hyprland

**Comment by JVPH** [comment] 2024-07-14 13:42
You could try 

```

$ systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
$ dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
```

**Comment by No0ne003** [comment] 2024-07-14 14:04
it steam doesn't work

**Comment by coder3112** [comment] 2024-07-14 17:05
Any fixes for xorg? (xmonad + arch)

**Comment by No0ne003** [comment] 2024-08-28 16:02
the problem is fixed but now it doesn't keep me sing in

**Closed** 2024-08-28 16:03 UTC
Labels: defect, collaboration, linux
