### ISSUE TITLE
Image viewing in editor

### ISSUE THREAD

**Issue by chandudagoat** [zed-industries/zed#6915] opened 2024-01-28 06:26 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

basically something like in vscode where we can view pictures in the code workspace itself. It would be nice if zed had it too.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/152237163/f90f1bb8-5bdf-433a-9fa7-8aa467722ce7)

**Comment by Moshyfawn** [comment] 2024-03-10 15:42
This seems to be a duplicate of another feature request made earlier. I'm going to close this one in favour of the other, to keep upvoting and discussion in one thread. Be sure to +👍 and add any missing information.

Duplicate of
- #5251

**Closed by Moshyfawn** 2024-03-10 15:42 UTC
Labels: enhancement, editor
