### ISSUE TITLE
REPL completely non-functional

### ISSUE THREAD

**Issue by adienes** [zed-industries/zed#19034] opened 2024-10-10 17:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the REPL is a complete non-feature on my install and as far as I can tell none of the `repl: run` or `repl: refresh kernelspecs` do anything.

I've tried restarting several times, switching environments, my settings now contains
```
  "jupyter": {
    "kernel_selections": {
      "python": "/home/adienes/.local/share/jupyter/kernels/test_env"
    },
    "enabled": true
  }
```

but it's still just no-op across the board.

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

although I'm running the remote dev to another machine.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by rgbkrk** [comment] 2024-11-06 01:21
> although I'm running the remote dev to another machine.

That's the key here. The REPL feature doesn't support remoting at this time. Thanks for reporting.

**Comment by SomeoneToIgnore** [comment] 2024-11-06 06:52
So, duplicate of https://github.com/zed-industries/zed/issues/15196

**Closed by SomeoneToIgnore** 2024-11-06 06:52 UTC
Labels: bug, python, repl
