### ISSUE TITLE
`PKGBUILD` files not recognised as bash

### ISSUE THREAD

**Issue by neunato** [zed-industries/zed#19984] opened 2024-10-30 20:12 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Supposedly added in https://github.com/zed-industries/zed/pull/10946 but does not work. Language is Unknown.

### Environment

Zed: v0.159.5 (Zed)
OS: Linux X11 arch unknown
Memory: 62.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 with Max-Q Design || NVIDIA || 560.35.03

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/afc795d0-4f73-4e09-8964-c20fd8b28ac6

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-30T21:33:17.69432744+01:00 [INFO] ========== starting zed ==========
2024-10-30T21:33:17.701495677+01:00 [WARN] failed to load font 'SymbolsNFM'
2024-10-30T21:33:17.70293999+01:00 [WARN] failed to load font 'SymbolsNFM'
2024-10-30T21:33:17.708157106+01:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-10-30T21:33:17.708216099+01:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: false
2024-10-30T21:33:17.711483943+01:00 [INFO] perform;
2024-10-30T21:33:17.711519142+01:00 [INFO] authenticate;
2024-10-30T21:33:17.711554624+01:00 [INFO] Opening main db
2024-10-30T21:33:17.7116347+01:00 [INFO] read_command;
2024-10-30T21:33:17.711966522+01:00 [INFO] new;
2024-10-30T21:33:17.711998457+01:00 [INFO] socket reader;
2024-10-30T21:33:17.712305676+01:00 [INFO] Opening main db
2024-10-30T21:33:17.712854957+01:00 [INFO] keep_updated;
2024-10-30T21:33:17.714547459+01:00 [INFO] Using git binary path: None
2024-10-30T21:33:17.718698395+01:00 [INFO] no tokio runtime found, creating one for Reqwest...
2024-10-30T21:33:17.731480732+01:00 [INFO] set environment variables from shell:/usr/bin/bash, path:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/scripts
2024-10-30T21:33:17.754359864+01:00 [ERROR] No such file or directory (os error 2) about ["/home/user/.config/github-copilot"]
2024-10-30T21:33:17.754486912+01:00 [INFO] initializing context server client
2024-10-30T21:33:17.754562463+01:00 [INFO] Registering built-in prompt template: content_prompt
2024-10-30T21:33:17.754991955+01:00 [INFO] Registering built-in prompt template: edit_workflow
2024-10-30T21:33:17.755167551+01:00 [INFO] Registering built-in prompt template: project_slash_command
2024-10-30T21:33:17.755216283+01:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-10-30T21:33:17.75545228+01:00 [INFO] No prompt template overrides directory found at /home/user/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-10-30T21:33:17.779446518+01:00 [INFO] extensions updated. loading 9, reloading 0, unloading 0
2024-10-30T21:33:17.782627283+01:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-10-30T21:33:17.784876334+01:00 [INFO] Opening main db
2024-10-30T21:33:17.785863582+01:00 [INFO] perform;
2024-10-30T21:33:17.785932302+01:00 [INFO] authenticate;
2024-10-30T21:33:17.786004077+01:00 [INFO] read_command;
2024-10-30T21:33:17.786609169+01:00 [INFO] socket reader;
2024-10-30T21:33:17.793845407+01:00 [ERROR] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
2024-10-30T21:33:17.795789845+01:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2024-10-30T21:33:17.795814037+01:00 [INFO] Creating colormap 27262979
2024-10-30T21:33:17.797031251+01:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-10-30T21:33:17.813653958+01:00 [INFO] Enabling Vulkan Portability
2024-10-30T21:33:17.813677594+01:00 [INFO] Enabling color space support
2024-10-30T21:33:17.888830905+01:00 [INFO] Adapter: "NVIDIA GeForce RTX 2060 with Max-Q Design"
2024-10-30T21:33:17.891885733+01:00 [INFO] Ray tracing is supported
2024-10-30T21:33:18.190965382+01:00 [INFO] Using surface present mode FIFO_RELAXED
2024-10-30T21:33:18.191599915+01:00 [WARN] Unable to forbid exclusive full screen
2024-10-30T21:33:18.261603407+01:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-30T21:33:18.261633315+01:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-30T21:33:18.26165109+01:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-10-30T21:33:18.508333992+01:00 [INFO] Refreshing at 6944 micros
2024-10-30T21:33:18.508387254+01:00 [INFO] x11: no compositor present, falling back to server-side window decorations
2024-10-30T21:33:18.509113094+01:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 2060 with Max-Q Design", driver_name: "NVIDIA", driver_info: "560.35.03" }
2024-10-30T21:33:18.521102214+01:00 [WARN] Acquire failed because the surface is out of date
2024-10-30T21:33:18.526239117+01:00 [INFO] Using surface present mode FIFO_RELAXED
2024-10-30T21:33:18.526347671+01:00 [WARN] Unable to forbid exclusive full screen
2024-10-30T21:33:18.536599128+01:00 [INFO] Opening main db
2024-10-30T21:33:18.546084856+01:00 [INFO] Opening main db
2024-10-30T21:33:18.683058042+01:00 [WARN] unhandled message: Metadata(SupermavenMetadataMessage { dust_strings: None })
2024-10-30T21:33:18.6929074+01:00 [INFO] using project environment variables from CLI. PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/user/scripts"
2024-10-30T21:33:19.190436034+01:00 [WARN] GPU frame is out of date
2024-10-30T21:33:19.190657431+01:00 [INFO] Using surface present mode FIFO_RELAXED
2024-10-30T21:33:19.190729378+01:00 [WARN] Unable to forbid exclusive full screen

</pre></details>

**Comment by notpeter** [comment] 2024-10-30 20:22
Interesting. I can't reproduce on MacOS. It recognizes it as a Shell Script.

<img width="510" alt="Screenshot 2024-10-30 at 16 21 28" src="https://github.com/user-attachments/assets/0cbb651c-193c-46fd-acd7-595f56283063">

**Comment by neunato** [comment] 2024-10-30 20:43
I've updated the issue with the log file but can't see anything useful. I tried with the default settings - no luck. Is there anything else I can provide to help?

**Comment by notpeter** [comment] 2024-11-26 18:44
Do you have anything your settings which might be overriding this? Perhaps `file_types`?

**Comment by neunato** [comment] 2024-11-27 09:45
Nope, it happens with default settings as well.

**Comment by notpeter** [comment] 2024-12-04 14:49
Hi @neunato, while I totally believe you that this is happening (and a PITA), since we can't come up with steps to reproduce, I'm going to go ahead and close this as unactionable.

If you (or anyone else) manages to figure out steps to reproduce I would be happy to reopen and dig deeper.  Thanks for reporting.

**Closed by notpeter** 2024-12-04 14:49 UTC
Labels: bug, linux, language, bash, linux-x11
