### ISSUE TITLE
Run button

### ISSUE THREAD

**Issue by Nick-loves-coding** [zed-industries/zed#14133] opened 2024-07-11 02:51 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would love there to be a run button for my python projects. It is a small pain point, but it would be a great feature that would simplify stuff greatly.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1415" alt="Screenshot 2024-07-10 at 8 48 23 PM" src="https://github.com/zed-industries/zed/assets/130260916/c19eda21-d73a-4283-8b30-141a7ae8857f">

**Comment by notpeter** [comment] 2024-07-11 03:16
Duplicate of:
- https://github.com/zed-industries/zed/issues/11310

**Closed by notpeter** 2024-07-11 03:16 UTC
Labels: enhancement, triage, admin read
