### ISSUE TITLE
Horizontal stripes on title bar when showing about dialog

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/zed#9775] opened 2024-03-25 14:45 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Click on `Zed Preview` -> `About` to show the about dialog.

Happens in both stable & preview releases.

### Environment

Zed: v0.128.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/199648/b9087c70-11b1-4b45-8055-8b8be8a76ae5

**Comment by osiewicz** [comment] 2024-03-26 12:57
This happens for any prompt (e.g. for save prompts as well). I've found that it does not happen in fullscreen; with a bit of digging, it turned out that it is somehow related to us moving the traffic lights;
With this `unsafe` block gone, we no longer have these stripes show up with prompts: https://github.com/zed-industries/zed/blob/fb6cff89d77f733c39d6975a6c7b821b45ad71b3/crates/gpui/src/platform/mac/window.rs#L369

**Comment by CurbaiCode** [comment] 2024-03-26 13:18
I think this is a duplicate of #9588.

**Closed** 2024-03-26 16:57 UTC
Labels: defect, triage, admin read
