### ISSUE TITLE
Input delay on non-chorded keymaps

### ISSUE THREAD

**Issue by kbknapp** [zed-industries/zed#16643] opened 2024-08-21 23:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Add a keymap that does not use a chord to any context *except* `vim_mode == normal` such as:

```json
  {
    "context": "Pane",
    "bindings": {
      "space b K": "pane::CloseInactiveItems"
    }
  }
```

Now in an editor, enter insert mode and type anything that includes a `space` and you will see a noticeable (several hundred ms?) delay.

This makes sense as it's listening for the follow on key presses, however it was super un-intuitive and took me a while to figure out what was going on.

The fix was to move all "leader" keymaps into `vim_mode == normal`.

It feels like there should be a warning or something for this as it seems entirely reasonable that someone would try to copy over their (Neo)vim key bindings including "leader" mappings (for me leader was `space` but this would presumably apply to any standard leader key).

### Environment

Zed: v0.149.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

N/A

**Comment by ConradIrwin** [comment] 2024-08-22 03:57
Duplicate of #12539

**Closed by ConradIrwin** 2024-08-22 03:57 UTC
Labels: defect, triage, admin read
