### ISSUE TITLE
auto insert `*` when creating a newline in JS/TS doc comments

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#15627] opened 2024-08-01 15:41 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I find it really annoying that when writing docs for JS/TS, the `*` is not automatically added. While it's not technically necessary, it is the standard way of writing js docs. It'd be nice to have this as some kind of optional setting

For reference, if you are writing docstrings in rust via `///`, the newline will automatically start with `///`

or if you write comments in any language, the newline will generally start with the comment block.

```ts
/** <NEWLINE>
  <-----should start with '*'
 */
class Foo {}
```

## Typescript doc comments
https://github.com/user-attachments/assets/55f630ff-6455-4001-ab5e-79f73ee98354

## Rust doc comments

https://github.com/user-attachments/assets/36bd2ea5-6270-40d0-8a57-ded39cca93a3

**Comment by notpeter** [comment] 2024-08-01 17:06
Duplicate of:
- https://github.com/zed-industries/zed/issues/15627

Please 👍 that issue to vote. Subscribe to that issue for updates.
Thanks for reporting!

**Closed by notpeter** 2024-08-01 17:06 UTC
Labels: enhancement, triage, admin read

**Comment by universalmind303** [comment] 2024-08-01 23:59
@notpeter i think you meant this issue https://github.com/zed-industries/zed/issues/15507
