### ISSUE TITLE
Rendering (content + line numbers) is gradually more altered with higher line count in file!

### ISSUE THREAD

**Issue by thbar** [zed-industries/zed#6850] opened 2024-01-27 10:04 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have been battle testing Zed with a large file (8,5M lines, CSV data).

It looks like there is some form of decrepancy bug where the highest the line number displayed, the more miscalculation in rendering there is.

Example file:
- Go to https://transport.data.gouv.fr/datasets/reseau-urbain-et-interurbain-dile-de-france-mobilites
- in the "Static data" part, check "Horaires au format GTFS" and hit download
- unzip the file, then open `stop_times.txt` with Zed

It will take a bit of time (a spinner of some sort would be useful there to provide feedback to the user), then you'll see:

No problematic artefacts at the top of the file:

![CleanShot 2024-01-27 at 11 00 43@2x](https://github.com/zed-industries/zed/assets/10141/5b21737b-6f32-4a38-9ffb-54ab0366289f)

A bit lower, you'll see some spacing appear:

![CleanShot 2024-01-27 at 11 01 21@2x](https://github.com/zed-industries/zed/assets/10141/6d2d3a7e-5143-4164-bd11-a461640a28b6)

Then a bit more:

![CleanShot 2024-01-27 at 11 01 54@2x](https://github.com/zed-industries/zed/assets/10141/fb70a92c-911a-4eb8-bcab-dccebbe41eae)

And much more at the bottom of the file:

![CleanShot 2024-01-27 at 11 02 14@2x](https://github.com/zed-industries/zed/assets/10141/c0a0bfae-6511-42dd-acf7-fc080621f5ae)

I've implemented video games in the past and this reminds me of subtle yet gradually important calculation artefacts (e.g. rounding / interpolation of some sort to be able to display that properly !).

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-01-29 22:11
I think this is a duplicate of:

- https://github.com/zed-industries/zed/issues/5371

If I'm wrong, feel free to re-open.

**Closed by JosephTLyons** 2024-01-29 22:11 UTC
Labels: defect, editor

**Comment by thbar** [comment] 2024-01-29 23:33
@JosephTLyons I think you are right! Thanks!
