### ISSUE TITLE
How to force zed to use the system nodejs package instead of downloading it

### ISSUE THREAD

**Issue by darix** [zed-industries/zed#13863] opened 2024-07-05 14:01 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I am working on an apparmor profile for zed (before even really starting to use it) and found this:

```
type=AVC msg=audit(1720187905.297:16563): apparmor="DENIED" operation="exec" class="file" profile="zed-editor" name="${HOME}/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node" pid=950583 comm="zed-editor" requested_mask="x" denied_mask="x" fsuid=1000 ouid=1000
```

why does it need its own copy of nodejs?

### If applicable, add mockups / screenshots to help present your vision of the feature

-

**Comment by someone13574** [comment] 2024-07-05 23:32
Duplicate of https://github.com/zed-industries/zed/issues/12589

**Comment by mikayla-maki** [comment] 2024-07-09 22:44
duplicate

**Closed by mikayla-maki** 2024-07-09 22:44 UTC
Labels: enhancement, triage, admin read
