### ISSUE TITLE
error:auto-update not supported for OS "windows"

### ISSUE THREAD

**Issue by freezemusic** [zed-industries/zed#11891] opened 2024-05-16 04:18 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It is simple, I simply followed the instrcution [here (windows.md)](https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md)

Already updated to the latest GPU driver.

### Environment

Windows 11 Professional
21H2
Install at	‎5/‎10/‎2021
OS Build	22000.2538
CPU	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
RAM	128 GB
Graphic Card  GeForce GT 1030

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.02s
     Running `target\debug\Zed.exe`
[2024-05-16T12:10:42+08:00 ERROR auto_update] auto-update failed: error:auto-update not supported for OS "windows"
error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xc000041d)

**Comment by ognevny** [comment] 2024-05-16 13:54
for now that's "fine"

**Comment by JosephTLyons** [comment] 2024-05-16 14:59
Hey @freezemusic,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/11753

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-05-16 14:59 UTC
Labels: defect, panic / crash, installer / updater, windows
