### ISSUE TITLE
Unable to type Japanese using Google Japanese IME

### ISSUE THREAD

**Issue by mkismy** [zed-industries/zed#13292] opened 2024-06-20 04:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When typing Japanese, using Google Japanese IME in my environment, the input characters disappears.
It occasionally happened in the previous versions but restarting the app fixed it temporarily. Starting from v0.140.5 this is happening every time and no longer available to use zed.

I attached a screen recording with the comparison with how it normally works.

https://github.com/zed-industries/zed/assets/8445575/492e5ba2-30c6-4ed5-b6b1-41cdc09643c2

### Environment

Zed: v0.141.0 (Zed Preview)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>
2024-06-20T13:28:50+09:00 [INFO] Took 203.167µs to receive response to "shutdown" id 2
2024-06-20T13:28:50+09:00 [INFO] Took 184.5µs to receive response to "shutdown" id 2
2024-06-20T13:28:50+09:00 [ERROR] crates/lsp/src/lsp.rs:730: oneshot canceled
2024-06-20T13:28:50+09:00 [ERROR] crates/lsp/src/lsp.rs:730: oneshot canceled
</pre></details>

**Comment by jansol** [comment] 2024-06-20 08:43
Can you try with the 0.141.0 preview build? Seems to work fine there.

**Comment by mkismy** [comment] 2024-06-20 09:42
Unfortunately it doesn't work on 0.141.0 either. In fact the screen recording was shot on 0.141.0 as pasted to the "Environment" section.

**Comment by jansol** [comment] 2024-06-20 09:49
Ah, right. This is probably something specific to the Google IME then? I'm using the Apple one built into macOS.

**Comment by mkismy** [comment] 2024-06-21 03:33
Yeah I confirmed the built-in Apple one had no issue.

I wonder what triggered the kill since the last Google IME update was like 4 months ago and had no issues back then 🤔

**Comment by leaysgur** [comment] 2024-06-27 00:32
FYI: I don't know which changes worked, but this problem seemed to be fixed in `zed@preview` (0.142.1). 👏🏻

**Comment by gamella** [comment] 2024-06-27 07:58
I can confirm the issue is fixed in v0.142.1(preview) too.

**Comment by mkismy** [comment] 2024-06-27 08:56
Same here. Closing the issue for now.

**Closed** 2024-06-27 08:56 UTC
Labels: defect, editor, internationalization

**Comment by toshimaru** [comment] 2024-07-05 00:11
Just for my own reference, this issue has been fixed in the release [v0.142.4](https://zed.dev/releases/stable/0.142.4).

**Comment by ruine0213** [comment] 2024-07-19 23:00
I am facing the same issue on Linux.

Zed 0.144.4
OS Ubuntu22.04LTS
IME fcitx5-mozc
