### ISSUE TITLE
terminal ui bug

### ISSUE THREAD

**Issue by ChimeWu** [zed-industries/zed#16789] opened 2024-08-24 04:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when I drag the terminal window to the top, the buttom line can't be seen.
![截图 2024-08-24 12-46-51](https://github.com/user-attachments/assets/478f3c43-066c-4f5e-b429-20958136fbc9)
![截图 2024-08-24 12-47-41](https://github.com/user-attachments/assets/0a0a19c6-bfc4-40b4-9af6-042257979369)

### Environment

NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by aritlh** [comment] 2024-08-25 14:09
![image](https://github.com/user-attachments/assets/e1acbae4-dbe6-47cd-a055-5b6cbc248653)

same with me

**Comment by JosephTLyons** [comment] 2024-08-27 20:19
Very similar bug here:

- https://github.com/zed-industries/zed/issues/12966

**Comment by notpeter** [comment] 2024-08-27 20:25
This is a duplicate of:
- https://github.com/zed-industries/zed/issues/12966

The temporary work around is to make it 1 pixel shorter the full height or to use `workspace: toggle zoom` (shift+esc).

**Closed by notpeter** 2024-08-27 20:25 UTC
Labels: defect, terminal, panel
