### ISSUE TITLE
Nim Support

### ISSUE THREAD

**Issue by AritraBanik08** [zed-industries/zed#7065] opened 2024-01-30 10:47 UTC
### Check for existing issues

- [X] Completed

### Language

Nim

### Tree Sitter parser link

https://github.com/alaviss/tree-sitter-nim

### Language server link

https://github.com/nim-lang/langserver

### Misc notes

Providing support for [Nim](nim-lang.org) would be great as I do most of my backend in Nim.

**Comment by JosephTLyons** [comment] 2024-02-01 20:33
Hey @AritraBanik08,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5095

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-01 20:33 UTC
Labels: enhancement, triage, potential plugin, language, unsupported language, admin read
