### ISSUE TITLE
Svelte autocompletes insert the import multiple times :(

### ISSUE THREAD

**Issue by ArturGalstyan1** [zed-industries/zed#19214] opened 2024-10-15 10:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Check this video out:

https://github.com/user-attachments/assets/f3bb6ea6-50d2-43a0-ab34-2a3b7ab8a0ee

This is really bugging me and I don't know why this happens. I'm using the svelte plugin.

### Environment

Zed: v0.158.0 (Zed Dev 71a878aa399877268c6aa50ff2e8527f16cbf9c8)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by arggh** [comment] 2024-10-15 11:03
Happening also on Zed v0.156.2 (Mac OS 14.5).

**Comment by vitallium** [comment] 2024-10-19 17:54
At first glance, the problem is in the Svelte LSP that sends duplicate `additionalTextEdits`, an optional array of additional text edits that are applied when selecting this completion. Here is the LSP response when you expand the `onMount`:

```json
{
  "jsonrpc": "2.0",
  "id": 689,
  "result": {
    "label": "onMount",
    "labelDetails": { "description": "svelte" },
    "kind": 3,
    "detail": "Add import from \"svelte\"\n\nfunction onMount<T>(fn: () => NotFunction<T> | Promise<NotFunction<T>> | (() => any)): void",
    "documentation": {
      "value": "The `onMount` function schedules a callback to run as soon as the component has been mounted to the DOM.\nIt must be called during the component's initialisation (but doesn't need to live *inside* the component;\nit can be called from an external module).\n\nIf a function is returned _synchronously_ from `onMount`, it will be called when the component is unmounted.\n\n`onMount` does not run inside a [server-side component](https://svelte.dev/docs#run-time-server-side-component-api).\n\nhttps://svelte.dev/docs/svelte#onmount",
      "kind": "markdown"
    },
    "sortText": "16",
    "additionalTextEdits": [
      {
        "range": {
          "start": { "line": 0, "character": 18 },
          "end": { "line": 0, "character": 18 }
        },
        "newText": "\n  import { onMount } from \"svelte\";\n"
      },
      {
        "range": {
          "start": { "line": 0, "character": 18 },
          "end": { "line": 0, "character": 18 }
        },
        "newText": "\n  import { onMount } from \"svelte\";\n"
      },
      {
        "range": {
          "start": { "line": 0, "character": 18 },
          "end": { "line": 0, "character": 18 }
        },
        "newText": "\n  import { onMount } from \"svelte\";\n"
      }
    ],
    "commitCharacters": [".", ",", ";", "("],
    "data": {
      "name": "onMount",
      "source": "svelte",
      "data": {
        "exportName": "onMount",
        "exportMapKey": "7 2867 onMount svelte",
        "moduleSpecifier": "svelte",
        "ambientModuleName": "svelte"
      },
      "uri": "file:///Users/vslobodin/Development/my-svelte-app/src/routes/%2Bpage.svelte",
      "position": { "line": 1, "character": 3 }
    }
  }
}
```

**Comment by vitallium** [comment] 2024-10-19 20:41
> At first glance, the problem is in the Svelte LSP that sends duplicate `additionalTextEdits`, an optional array of additional text edits that are applied when selecting this completion. Here is the LSP response when you expand the `onMount`:
> 
> ```json
> {
>   "jsonrpc": "2.0",
>   "id": 689,
>   "result": {
>     "label": "onMount",
>     "labelDetails": { "description": "svelte" },
>     "kind": 3,
>     "detail": "Add import from \"svelte\"\n\nfunction onMount<T>(fn: () => NotFunction<T> | Promise<NotFunction<T>> | (() => any)): void",
>     "documentation": {
>       "value": "The `onMount` function schedules a callback to run as soon as the component has been mounted to the DOM.\nIt must be called during the component's initialisation (but doesn't need to live *inside* the component;\nit can be called from an external module).\n\nIf a function is returned _synchronously_ from `onMount`, it will be called when the component is unmounted.\n\n`onMount` does not run inside a [server-side component](https://svelte.dev/docs#run-time-server-side-component-api).\n\nhttps://svelte.dev/docs/svelte#onmount",
>       "kind": "markdown"
>     },
>     "sortText": "16",
>     "additionalTextEdits": [
>       {
>         "range": {
>           "start": { "line": 0, "character": 18 },
>           "end": { "line": 0, "character": 18 }
>         },
>         "newText": "\n  import { onMount } from \"svelte\";\n"
>       },
>       {
>         "range": {
>           "start": { "line": 0, "character": 18 },
>           "end": { "line": 0, "character": 18 }
>         },
>         "newText": "\n  import { onMount } from \"svelte\";\n"
>       },
>       {
>         "range": {
>           "start": { "line": 0, "character": 18 },
>           "end": { "line": 0, "character": 18 }
>         },
>         "newText": "\n  import { onMount } from \"svelte\";\n"
>       }
>     ],
>     "commitCharacters": [".", ",", ";", "("],
>     "data": {
>       "name": "onMount",
>       "source": "svelte",
>       "data": {
>         "exportName": "onMount",
>         "exportMapKey": "7 2867 onMount svelte",
>         "moduleSpecifier": "svelte",
>         "ambientModuleName": "svelte"
>       },
>       "uri": "file:///Users/vslobodin/Development/my-svelte-app/src/routes/%2Bpage.svelte",
>       "position": { "line": 1, "character": 3 }
>     }
>   }
> }
> ```

The duplication happens because of an issue in the Svelte LSP, I think. Zed as a LSP server receives completions, asks to resolve the selected, for example, receives the first response from the Svelte LSP with a single entry in the `additionalTextEdits`, then Zed asks to resolve the same completion again, here I am not sure if this is a correct behaviour, but I assume yes. Svelte LSP receives that command and just concatenates the `additionalTextEdits` field with some sort of `codeActions` here https://github.com/sveltejs/language-tools/blob/156bd7d7f445899dd7cf861495a570059d9e47ef/packages/language-server/src/plugins/typescript/features/CompletionProvider.ts#L892 I'd say the current behaviour is incorrect and the server should filter out duplicate entries or do not generate them at all.

Here is the `onMount` completion when Zed received it from the Svelte LSP for the first time:

**Comment by vitallium** [comment] 2024-10-19 21:01
I briefly checked the linked code and I think something like this:


```js
const additionalTextEdits = completionItem.additionalTextEdits ?? [];
completionItem.additionalTextEdits = [
    ...new Set([...additionalTextEdits, ...edit].map((i) => JSON.stringify(i)))
].map((i) => JSON.parse(i));
```

will remove duplicate entries by utilising Set's features and the JSON presentation of objects. Alternatively, instead of using JSON, we could compare all keys in objects.

**Comment by Blankeos** [comment] 2024-12-08 19:35
I was comparing the two logs of these similar 3 steps of getting autoimport in **Vscode** and **Zed**. Because this issue doesn't exist with VSCode at all.

**Anyway 3 steps are:**
1. Ctrl + Space to show list of suggestions. (Received from LSP) Response list - the same for both Zed and VSCode
2. Pressing the item to autoimport (Send to LSP) - It seems VSCode doesn't send `additionalTextEdits`, but Zed does. Though idk if this is just truncated by VSCode?
3. Received from LSP - VSCode gets always 1 `additionalTextEdits`. Zed very inconsistently gets 2 or 3. Very weird.

### 1. VSCode

<details>
   <summary>Open Logs</summary>

```jsonc
// 1. Ctrl + Space to show a list of suggestions (Contains the list of items to be rendered in autosuggest dropdown)
[Trace - 2:47:37 AM] Received response 'textDocument/completion - (475)' in 16ms.
Result: {
    "items": [
     {
        "label": "page",
        "kind": 21,
        "sortText": "16",
        "labelDetails": {
          "description": "$app/stores"
        },
        "data": {
          "name": "page",
          "source": "$app/stores",
          "data": {
            "exportName": "page",
            "exportMapKey": "4 12423 page $app/stores",
            "moduleSpecifier": "$app/stores",
            "ambientModuleName": "$app/stores"
          },
          "uri": "file:///myproject/src/components/layouts/vertical/vertical-nav.svelte",
          "position": {
            "line": 3,
            "character": 6
          }
        }
      },
      ... // truncated, but contains all suggestions

    ],
    "isIncomplete": false,
    "itemDefaults": {
        "commitCharacters": [
            ".",
            ",",
            ";",
            "("
        ]
    }
}
// 2. After Pressing the Suggestion "page" (Send)
[Trace - 2:47:37 AM] Sending request 'completionItem/resolve - (476)'.
Params: {
    "label": "page",
    "labelDetails": {
        "description": "$app/stores"
    },
    "insertTextFormat": 1,
    "kind": 21,
    "sortText": "16",
    "commitCharacters": [
        ".",
        ",",
        ";",
        "("
    ],
    "data": {
        "name": "page",
        "source": "$app/stores",
        "data": {
            "exportName": "page",
            "exportMapKey": "4 6720 page $app/stores",
            "moduleSpecifier": "$app/stores",
            "ambientModuleName": "$app/stores"
        },
        "uri": "file:///myproject/src/components/layouts/vertical/vertical-nav.svelte",
        "position": {
            "line": 3,
            "character": 6
        }
    }
}
```

// 3. Response Received
[Trace - 2:47:37 AM] Received response 'completionItem/resolve - (476)' in 3ms.
Result: {
    "label": "page",
    "labelDetails": {
        "description": "$app/stores"
    },
    "insertTextFormat": 1,
    "kind": 21,
    "sortText": "16",
    "commitCharacters": [
        ".",
        ",",
        ";",
        "("
    ],
    "data": {
        "name": "page",
        "source": "$app/stores",
        "data": {
            "exportName": "page",
            "exportMapKey": "4 6720 page $app/stores",
            "moduleSpecifier": "$app/stores",
            "ambientModuleName": "$app/stores"
        },
        "uri": "file:///myproject/src/components/layouts/vertical/vertical-nav.svelte",
        "position": {
            "line": 3,
            "character": 6
        }
    },
    "detail": "Add import from \"$app/stores\"\n\nconst page: Readable<Page<Record<string, string>, string | null>>",
    "documentation": {
        "value": "A readable store whose value contains page data.\n\nOn the server, this store can only be subscribed to during component initialization. In the browser, it can be subscribed to at any time.",
        "kind": "markdown"
    },
    "additionalTextEdits": [
        {
            "range": {
                "start": {
                    "line": 11,
                    "character": 0
                },
                "end": {
                    "line": 11,
                    "character": 0
                }
            },
            "newText": "  import { page } from '$app/stores';\n"
        }
    ]
}
</details>


### 2. Zed


<details>
<summary>Open Logs</summary>

```jsonc
// 1. Ctrl + Space to show a list of suggestions (Contains the list of items to be rendered in autosuggest dropdown)
// (Basically the same)
{
  "jsonrpc": "2.0",
  "id": 867,
  "result": {
    "items": [...],
    "isIncomplete": false,
    "itemDefaults": {
      "commitCharacters": [
        ".",
        ",",
        ";",
        "(",
        "(",
        "(",
        "(",
        "(",
        "(",
        "(",
        "(",
        "(",
        "(",
        "(",
        "("
      ]
    }
  }
}


// 2. After Pressing the Suggestion "page" (Send)
{
  "jsonrpc": "2.0",
  "id": 395,
  "method": "completionItem/resolve",
  "params": {
    "label": "page",
    "labelDetails": {
      "description": "$app/stores"
    },
    "kind": 21,
    "detail": "Add import from \"$app/stores\"\n\nconst page: Readable<Page<Record<string, string>, string | null>>",
    "documentation": {
      "kind": "markdown",
      "value": "A readable store whose value contains page data.\n\nOn the server, this store can only be subscribed to during component initialization. In the browser, it can be subscribed to at any time."
    },
    "sortText": "16",
    "additionalTextEdits": [
      {
        "range": {
          "start": {
            "line": 11,
            "character": 0
          },
          "end": {
            "line": 11,
            "character": 0
          }
        },
        "newText": "  import { page } from '$app/stores';\n"
      }
    ],
    "commitCharacters": [
      ".",
      ",",
      ";",
      "(",
      "(",
      "(",
      "(",
      "(",
      "("
    ],
    "data": {
      "name": "page",
      "source": "$app/stores",
      "data": {
        "exportName": "page",
        "exportMapKey": "4 12423 page $app/stores",
        "moduleSpecifier": "$app/stores",
        "ambientModuleName": "$app/stores"
      },
      "uri": "file:///myproject/src/components/layouts/vertical/vertical-nav.svelte",
      "position": {
        "line": 3,
        "character": 6
      }
    }
  }
}

// 3. Received Response
{
  "jsonrpc": "2.0",
  "id": 395,
  "result": {
    "label": "page",
    "labelDetails": {
      "description": "$app/stores"
    },
    "kind": 21,
    "detail": "Add import from \"$app/stores\"\n\nconst page: Readable<Page<Record<string, string>, string | null>>",
    "documentation": {
      "value": "A readable store whose value contains page data.\n\nOn the server, this store can only be subscribed to during component initialization. In the browser, it can be subscribed to at any time.",
      "kind": "markdown"
    },
    "sortText": "16",
    "additionalTextEdits": [
      {
        "range": {
          "start": {
            "line": 11,
            "character": 0
          },
          "end": {
            "line": 11,
            "character": 0
          }
        },
        "newText": "  import { page } from '$app/stores';\n"
      },
      {
        "range": {
          "start": {
            "line": 11,
            "character": 0
          },
          "end": {
            "line": 11,
            "character": 0
          }
        },
        "newText": "  import { page } from '$app/stores';\n"
      }
    ],
    "commitCharacters": [
      ".",
      ",",
      ";",
      "(",
      "(",
      "(",
      "(",
      "(",
      "("
    ],
    "data": {
      "name": "page",
      "source": "$app/stores",
      "data": {
        "exportName": "page",
        "exportMapKey": "4 12423 page $app/stores",
        "moduleSpecifier": "$app/stores",
        "ambientModuleName": "$app/stores"
      },
      "uri": "myproject/src/components/layouts/vertical/vertical-nav.svelte",
      "position": {
        "line": 3,
        "character": 6
      }
    }
  }
}
```

</details>



Idk if this would be useful. From @vitallium's explanation, I assume a PR needs to be merged in Svelte's LSP. I think an issue needs to be [opened on their repo](https://github.com/zed-extensions/svelte/tree/main/languages/svelte). 

But, is there any way we can override the way Zed sends **Step 2** at least via the extension? Maybe sending the same request shape as VSCode would give us the fix? 😅🤞. I do agree that the core issue is the LSP though.

**Comment by jasonlyu123** [comment] 2024-12-13 00:55
The issue we found in the svelte is that Zed sent a request to resolve the same completion item multiple times. Is there a reason to do that? Although the spec doesn't say you can't send it twice it really is just a waste of time and asking for trouble...

**Comment by lleyton** [comment] 2024-12-27 07:11
after a bisect, seems like a regression caused by https://github.com/zed-industries/zed/commit/05d18321db59539b56520d25f2ee95850ad911fd#diff-5b9d51b75b74266b5c651ef3c6988fe2e62d1680ac138d806cdaa75900bc8b5fR1616

**Closed** 2024-12-27 16:44 UTC
Labels: bug, language server failure, svelte

**Comment by SomeoneToIgnore** [comment] 2024-12-27 18:21
Sorry for breaking this, the fix from https://github.com/zed-industries/zed/pull/22448 should come next Wednesday.
