### ISSUE TITLE
add a File list in Serach Result panel.

### ISSUE THREAD

**Issue by finscn** [zed-industries/zed#9277] opened 2024-03-13 12:24 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

After search some texts in the whole project,  there will be many files in the Serach Result panel.
I hope zed could supply a file list in the panel. And I could selet one file to view the result of the file only, and open that file.

Or  made a view like  vs-code's search mode.

**Comment by Moshyfawn** [comment] 2024-03-13 13:48
I think this can fall under feature request #8279.

I'm going to close this in favour of the other one, but feel free to object. Be sure to +👍 the other issue, and add any additional information that might be missing.

Duplicate of
- #8279

**Closed by Moshyfawn** 2024-03-13 13:48 UTC
Labels: enhancement, triage, admin read
