### ISSUE TITLE
Improve rust syntax highlighting

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#9670] opened 2024-03-21 21:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

the rust syntax in zed isn't great many word have not colors, vscode instead has a better syntax

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1348" alt="Screenshot 2024-03-21 alle 22 53 30" src="https://github.com/zed-industries/zed/assets/53220110/0ada1acf-f79e-4611-a74e-f2fff06ea035">
<img width="804" alt="Screenshot 2024-03-21 alle 22 55 20" src="https://github.com/zed-industries/zed/assets/53220110/d8806706-46fe-4321-820a-d7dff0db72a2">

**Comment by Moshyfawn** [comment] 2024-03-22 02:25
This has already been raised. Let's close this issue in favour of the existing one to keep the conversation in one place. Be sure to +👍 and add any additional information or examples to the other thread.

Duplicate of
- #7679

**Closed by Moshyfawn** 2024-03-22 02:25 UTC
Labels: enhancement, triage, admin read
