### ISSUE TITLE
horizontal scrollbar misbehaving in projects panel 

### ISSUE THREAD

**Issue by sourabhrathourr** [zed-industries/zed#19751] opened 2024-10-25 16:59 UTC
### Check for existing issues

- [X] Completed

### Steps to reproduce - 

- Horizontal scrollbar in projects panel is misbehaving. When we have long string of file names which doesn't fit in the view of projects panel, we see the horizontal scrollbar to scroll through it. 
- But, sometimes this horizontal scrollbar comes up even if the project panel/left dock is expanded enough to fit the content which seems frustrating at times. 

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 15.0.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

In this image below, it can be clearly seen that project panel has enough space to fit the content inside, and practically there's no need for a horizontal scrollbar, still it appears.

<img width="651" alt="image" src="https://github.com/user-attachments/assets/6af4f175-63cd-402d-83db-bd0beddcc809">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-25 19:01
Duplicate of https://github.com/zed-industries/zed/issues/19637

**Closed by SomeoneToIgnore** 2024-10-25 19:01 UTC
Labels: defect, project panel
