### ISSUE TITLE
Vim feature: easymotion/jumpy2 equivalent

### ISSUE THREAD

**Issue by fbering** [zed-industries/zed#18625] opened 2024-10-02 11:17 UTC
### Check for existing issues

- [X] Completed

### Intro
I love everything I have read about Zed. Vim support out of the box, and vim's search replaced with something better.

But I cannot code without easymotion/jumpy2. It allows you to jump quick and easy in your code without ever touching your mouse. Motion on roids, as easymotion calls it.

### Describe the feature

The concept is you bind a key(s) (for me its double hit on my <leader>) to enter a mode, the mode will then highlight all capitalised characters, characters after dots, characters in new lines, brackets and so forth (simply but, every important point you could jump to). The way it highlights it is by overwriting it with a character combination - for example: `ab`. If I then type `ab` on my keyboard, the cursor will jump to that point in the code and leave the mode

This is much better illustrated on the repos I have linked below. (video and gif).
 
One important setting would be the option to allow enter what characters to prioritise, when creating the highlights. Maybe defaulting to qwerty's home row characters, but allowing Dvorak users like me to change it.

_This might not necessarily be Vim exclusive, but it is amazing to use with vim._

### If applicable, add mockups / screenshots to help present your vision of the feature

Video/gifs can be found in the these github repos:

jumpy2 in vscode: https://github.com/DavidLGoldberg/jumpy2
Easymotion in vim: https://github.com/easymotion/vim-easymotion

**Comment by jansol** [comment] 2024-10-02 13:08
Duplicate of #4930, #5063, #5289.
Also similar to #4934 and #14801

Seems like a popular feature, there has even been an attempt at implementing it: #12106

**Comment by JosephTLyons** [comment] 2024-10-03 15:53
Closing in favor of the issues mentioned by @jansol - feel free to add comments on one/any of the associated issues if you think more detail is lacking.

**Closed by JosephTLyons** 2024-10-03 15:53 UTC
Labels: enhancement, vim
