### ISSUE TITLE
Zed won't start

### ISSUE THREAD

**Issue by KeithBrown39423** [zed-industries/zed#18015] opened 2024-09-18 15:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

```
git clone https://github.com/zed-industries/zed
cargo build
./target/debug/zed.exe
```

### Environment

**Zed commit hash:** 4d074fc737db71ff10b4cf1e68f4b70e092124b6
**Cargo version:** cargo 1.81.0 (2dbb1af80 2024-08-20)
**OS:** Windows 11 23H2 22631.4169

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Anytime I try to run zed after compiling the debug build, I get the follow error.
```
[2024-09-18T10:44:36-05:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-09-18T10:44:36-05:00 ERROR] invalid type: boolean `true`, expected string or map
[2024-09-18T10:44:37-05:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }```

**Comment by SomeoneToIgnore** [comment] 2024-09-18 21:47
Looks like duplicate of https://github.com/zed-industries/zed/issues/17374

**Closed by SomeoneToIgnore** 2024-09-18 21:47 UTC
Labels: defect, triage, panic / crash, admin read
