### ISSUE TITLE
Buffer search select next/prev match not respecting right context

### ISSUE THREAD

**Issue by Anthony-Eid** [zed-industries/zed#14997] opened 2024-07-23 05:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Select next/prev match in the editor's and terminal's buffer search goes to the next/prev match of the most recently in focus buffer, instead of the search buffer that is associated with the terminal or editor. 

For example, if I search "request" in my terminal, click the editor, then click the `select next match` arrow in the terminal's buffer search, zed will go to a match in my editor instead of my terminal. Note that the match in the terminal isn't necessarily "request", it is a match from the last buffer search from the terminal. 

P.S I would be more than happy to work with someone to fix this issue. Also, pressing the "esc" key while the terminal is in focus doesn't close the terminal's search buffer. I could open another issue/bug report of that's unexpected behavior. 

### Environment

Zed: v0.144.4 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here's a video of the current behavior of Zed.

https://github.com/user-attachments/assets/c53b4e5b-fa0f-44f6-bdc5-490852ac79d1

**Comment by notpeter** [comment] 2024-07-28 16:26
Duplicate of:
- https://github.com/zed-industries/zed/issues/14838

**Closed by notpeter** 2024-07-28 16:26 UTC
Labels: defect, triage, admin read
