### ISSUE TITLE
Closed window with open folder/project keeps getting brought back over untitled empty window

### ISSUE THREAD

**Issue by wzxu** [zed-industries/zed#4967] opened 2023-03-11 13:07 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a folder in current window
2. Close current window
3. Open a new empty window
4. Quit & re-launch Zed

Expectation: Zed will restore the lastly opened window, aka the empty window
Actual: Zed brings back the closed window with open folder/project

Also, just for your information, I changed the "default_dock_anchor" setting to "bottom" during this, but the re-opened window with folder/project still preserves the old setting showing the dock on the right. If I open a new empty window it's the correct setting, but due to the behavior described above, quitting and re-launching gives me the old window stuck with old settings again.

### Environment

Zed: v0.75.2 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment] 2024-06-27 17:28
I'm going to close this as a duplicate of:
- #7759

Your issue was here first, but that one has a few 👍 upvotes some I'm going to close this one in favor of that. 

Please 👍 that issue to vote and subscribe there to track the progress.
If this is in error, please leave a comment and/or reopen with clarification.

**Closed by notpeter** 2024-06-27 17:28 UTC
Labels: defect, workspace
