### ISSUE TITLE
Go language server needs editor restart to load new modules

### ISSUE THREAD

**Issue by TheBeachMaster** [zed-industries/zed#7654] opened 2024-02-10 12:09 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Go LSP can not load newly downloaded modules unless you restart the editor

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### Zed
![Screenshot 2024-02-10 at 14 55 12](https://github.com/zed-industries/zed/assets/9129843/d66949b5-1ecc-4ba8-832f-54644fa81110)

![Screenshot 2024-02-10 at 14 55 02](https://github.com/zed-industries/zed/assets/9129843/a59506e8-2f78-42b3-a22b-9f4d84933e1d)

### VSCodium
![Screenshot 2024-02-10 at 14 55 46](https://github.com/zed-industries/zed/assets/9129843/3b219650-b44b-4011-8087-237c58cde8ec)

## After Editor restart
![Screenshot 2024-02-10 at 14 59 06](https://github.com/zed-industries/zed/assets/9129843/2f627a69-d8ce-40d1-af0e-3ba727716836)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-10T14:47:17+03:00 [ERROR] crates/editor/src/editor.rs:7710: failed to format via language server

Caused by:
    3:1: expected declaration, found 'package' (and 1 more errors)
2024-02-10T14:51:15+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:51:21+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:51:23+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:51:24+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:53:12+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:53:13+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:54:37+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:54:44+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:54:47+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:54:48+03:00 [WARN] Generic lsp request to gopls failed: failed to resolve import "github.com/panjf2000/ants/v2"
2024-02-10T14:56:36+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/panjf2000/ants/v2"
2024-02-10T14:58:13+03:00 [ERROR] crates/gpui/src/window.rs:404: window not found
2024-02-10T14:58:13+03:00 [ERROR] crates/lsp/src/lsp.rs:624: oneshot canceled
2024-02-10T14:58:13+03:00 [ERROR] crates/terminal_view/src/terminal_view.rs:402: error upgrading view

---
### I restarted the editor here 

2024-02-10T14:58:44+03:00 [INFO] build git repository ".git"
2024-02-10T14:58:44+03:00 [INFO] build git repository "servicepb/.git"
2024-02-10T14:58:44+03:00 [INFO] starting language server "gopls", path: "/[REDACTED]", id: 12
---

### I then reproduced the same error by downloading a different package

---

2024-02-10T14:58:44+03:00 [ERROR] crates/workspace/src/persistence/model.rs:257: failed to read path after update
2024-02-10T14:58:44+03:00 [ERROR] crates/workspace/src/persistence/model.rs:257: failed to read path after update
2024-02-10T15:04:17+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/gofiber/contrib/fiberzerolog"
2024-02-10T15:04:18+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/gofiber/contrib/fiberzerolog"
2024-02-10T15:04:19+03:00 [WARN] Generic lsp request to gopls failed: no package data for import "github.com/gofiber/contrib/fiberzerolog"

**Comment by JosephTLyons** [comment] 2024-02-13 18:41
Hey @TheBeachMaster,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5112

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-13 18:41 UTC
Labels: defect, language, go, language server
