### ISSUE TITLE
import path renaming/refactor rename for filenames

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#10723] opened 2024-04-18 10:42 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

it would be a great feature if the file rename would behave exactly like the symbol rename and also rename all the imports

**Comment by Moshyfawn** [comment] 2024-04-18 16:44
There's already a similar request, so I'm going to close this issue in favour of the other one. Be sure to +👍 and add any additional information to the other thread.

Duplicate of
- #5252

**Closed by Moshyfawn** 2024-04-18 16:44 UTC
Labels: enhancement, triage, admin read
