### ISSUE TITLE
RustCrypto crates don't work in zed

### ISSUE THREAD

**Issue by Snowiiii** [zed-industries/zed#16277] opened 2024-08-15 10:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello, Crates from RustCrypto are build a bit complex like shown in the screenshot.
The problem is that zed is really broken when using these crates

### Environment

Zed: v0.148.0 (Zed)
OS: Linux Wayland manjaro unknown
Memory: 30.5 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7700 XT (RADV NAVI32) || radv || Mesa 24.1.5-arch1.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/e4eda424-74d3-40ca-ba2a-b84695b24e7b)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-08-15 12:03
Can you describe/film what is really broken exactly and does it work in any other rust-analyzer-backed editor (e.g. NeoVim or VSCode?)

**Comment by SomeoneToIgnore** [comment] 2024-09-12 16:11
No further details provided, so I'll close this as a duplicate of https://github.com/zed-industries/zed/issues/17376

**Closed by SomeoneToIgnore** 2024-09-12 16:11 UTC
Labels: defect, needs info / awaiting response, rust, language, language server
