### ISSUE TITLE
Find directories in project file search

### ISSUE THREAD

**Issue by squ94wk** [zed-industries/zed#15067] opened 2024-07-24 07:47 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'm working on Go projects where a lot of times I'm looking for a certain package (=directory), but I don't know a specific file in it.

With Jetbrains Goland (IntelliJ based) I make heavy use of fuzzy finding a directory, which brings me to the project files tree and there I navigate to the specific file I'm looking for.
I find it easier (less cognitive load) to find the right file in the tree than to pick it out in the search results.

IntelliJ will suggest directories as part of the normal file search and will force directories if the search string ends with a `/`.

**Comment by notpeter** [comment] 2024-07-26 21:26
Duplicate of:

- https://github.com/zed-industries/zed/issues/7205

Please subscribe to that issue to get notifications and 👍 vote to increase visibility. Thanks for reporting.

P.S. I want this too! ;)

**Closed by notpeter** 2024-07-26 21:26 UTC
Labels: enhancement, triage, admin read
