### ISSUE TITLE
Go to previous excerpts and Go to next excerpts command in ProjectDisgnostics context and ProjectSearch context

### ISSUE THREAD

**Issue by wishque** [zed-industries/zed#12010] opened 2024-05-18 03:42 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

use keyboard jump between excerpts would be cool

**Comment by JosephTLyons** [comment] 2024-05-19 17:48
Hey @wishque,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5129

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-05-19 17:48 UTC
Labels: enhancement, keymap / key binding, multi-buffer, diagnostics
