### ISSUE TITLE
Markdown: level structure of the headings

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21320] opened 2024-11-29 09:12 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

As you can see from the image there seems to be no level structure of the headers.
See video to understand how vscode does it.

Zed:
<img width="385" alt="Screenshot 2024-11-29 alle 10 06 05" src="https://github.com/user-attachments/assets/a1126aa5-f31c-4f8e-9558-13f7352e0a91">
<img width="1003" alt="Screenshot 2024-11-29 alle 10 09 49" src="https://github.com/user-attachments/assets/34df5dc8-199d-4d3c-8561-35539ae87772">

Vscode:

https://github.com/user-attachments/assets/ed8aff24-16b8-4ff0-b004-dcc55dfde3a0

Code:

```
# Level 1 Header: Main Title
This is the main heading of the document.

## Level 2 Header: Section Title
This section introduces the first main topic.

### Level 3 Header: Subsection Title
Details about the first subsection.

#### Level 4 Header: Sub-subsection Title
More specific information within the subsection.

##### Level 5 Header: Minor Section Title
This is a minor section, providing more focused details.

###### Level 6 Header: Smallest Heading
This is the smallest heading, typically used for very specific or detailed points.
```

### Environment

```
Zed: v0.164.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

**Comment by notpeter** [comment] 2024-12-02 19:02
Related: 
- https://github.com/zed-industries/zed/issues/4924

**Comment by notpeter** [comment] 2024-12-16 08:53
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/4924

Makrdown outline support would enable nested header breadcrumbs.

**Closed by notpeter** 2024-12-16 08:53 UTC
Labels: enhancement, markdown, navigation, outline
