### ISSUE TITLE
Extension[windows]: Uninstall button not working.

### ISSUE THREAD

**Issue by ArtemMartus** [zed-industries/zed#18597] opened 2024-10-01 18:22 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The bug is that in extensions page I cannot uninstall the extension. 

I got myself a "BasedPyright" extension due to trying what is available in the market. But it requires me to install some other pypi modules which I dont want to install - so each time I launch Zed it shows me an error in a separate page that tells me about "basedpyright" plugin failed to launch due to missing pip package. So now I just want to get rid of it, but I cant. That uinstall button can be pressed, it changes my arrow icon / text tone - some animation is going on like it does something, but it's not. And also I cant delete it manually because there are no ~/.local/share/zed folder and no files nearby the zed.exe file. 

Please do update these extensions related docs to include windows platform as it is also can be used. And also add a few words about how to manually delete an extension, that would be very helpful to have in documentation.
https://zed.dev/docs/extensions/installing-extensions

### Environment

Zed: v0.156.0 (Zed Dev 280b8a89ea132f225b249ce743839c0cab96b05b)
OS: Windows 10.0.22631
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || 101.5972

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/9cda1df4-c078-49f0-a993-2ea659beba67)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-07 15:53
Duplicate of:
- https://github.com/zed-industries/zed/issues/18153

**Closed by notpeter** 2024-10-07 15:53 UTC
Labels: defect, triage, admin read
