### ISSUE TITLE
Typing `end` and pressing enter in Ruby completes to something not `end`

### ISSUE THREAD

**Issue by joeldrapper** [zed-industries/zed#13035] opened 2024-06-14 08:16 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open a Ruby file
2. Type `class Foo`
3. Press enter
4. Type `end`
5. Press enter

Zed will have replaced `end` with `extended`.

I think this would be solved by prioritising exact matches form the LSP suggestions. It seems to impact both `ruby-lsp` and `solargraph`. 

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.4.1
Memory: 128 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2024-06-14 at 09 08 28@2x](https://github.com/zed-industries/zed/assets/246692/6f675b96-df43-4d09-8e31-7747c5341f57)

**Comment by osiewicz** [comment] 2024-06-14 10:02
Hey, I'm gonna close this one as a duplicate of https://github.com/zed-industries/zed/issues/12698 - thanks for submitting this issue though ;)

**Closed by osiewicz** 2024-06-14 10:02 UTC
Labels: defect, triage, admin read
