### ISSUE TITLE
Color highlight

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#7407] opened 2024-02-05 21:24 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would like ZED to have ability to highlight and show indicated colors, whether by hex or by text value as well. Such gutter/margin coloring really helps especially with config files where there are multiple color definitions. Instead of rechecking each `hex` specified value, user could immediately see assigned colors specs in the side gutter.

### If applicable, add mockups / screenshots to help present your vision of the feature

Below screenshot shows side gutter indication of specified colors. Applies to both the `hex` value or actual `text` marker:

![colors](https://github.com/zed-industries/zed/assets/4711498/c32beb9d-2691-4c42-b6fa-9a435db98fa3)

**Comment by JosephTLyons** [comment] 2024-02-06 22:17
Hey @krstp,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4678

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-06 22:17 UTC
Labels: enhancement, triage, admin read

**Comment by an1ndra** [comment] 2025-02-25 17:32
Any update of this issue?
