### ISSUE TITLE
Consecutive opened files in current session

### ISSUE THREAD

**Issue by Ktoks** [zed-industries/zed#17312] opened 2024-09-03 15:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Please add consecutive opened files with Zed to be opened on the current session.
This is the behavior that VSCode and Neovim's Server have.

**Comment by notpeter** [comment] 2024-09-03 16:33
What do you mean by "consecutive opened files"? Like if you select multiple files in the Project Panel and press `space` it opens all of them?

**Comment by Ktoks** [comment] 2024-09-03 17:44
I mean - open one file in Zed - then some time later - open another file in Zed from Explorer, Commander, or WinSCP, etc... - and them all opening into the current session.

**Comment by notpeter** [comment] 2024-09-03 19:48
Ah, duplicate of:
- https://github.com/zed-industries/zed/issues/9370

**Closed by notpeter** 2024-09-03 19:48 UTC
Labels: enhancement, project panel
