### ISSUE TITLE
Cannot cycle through windows using keyboard shortcuts [osx]

### ISSUE THREAD

**Issue by schmurfy** [zed-industries/zed#17582] opened 2024-09-09 07:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

using the keyboard shortcuts to switch to next/previous windows does nothing most of the time, I  sometimes get it to work but never understood why so far.

### Environment

Zed: v0.151.1 (Zed)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-09 12:44
This is probably a duplicate of:
- https://github.com/zed-industries/zed/issues/16343

As a workaround you can add the following to your local `~/.config/zed/keymap.json`:

```json
[
  {
    "context": "ContextEditor > Editor",
    "bindings": {
      "cmd-<": null
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-<": null
    }
  }
]
```

**Closed** 2024-09-09 13:16 UTC
Labels: duplicate

**Comment by schmurfy** [comment] 2024-09-11 07:01
it works, thanks !

**Comment by joachimtingvold** [comment] 2024-11-27 00:04
To get both forward and backward cycling to work, this is the correct workaround;

```
  {
    "context": "ContextEditor > Editor",
    "bindings": {
      "cmd->": null,
      "cmd-<": null
    }
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd->": null,
      "cmd-<": null
    }
  }
```

**Comment by ConradIrwin** [comment] 2024-12-06 20:52
@joachimtingvold which version of zed are you using, and which keyboard layout? I am not expecting problems with `>` since version 0.162.x

**Comment by joachimtingvold** [comment] 2024-12-06 21:15
> @joachimtingvold which version of zed are you using, and which keyboard layout? I am not expecting problems with `>` since version 0.162.x

The day I made my previous comment was my first day using Zed, and the latest version was downloaded that very same day (27th of November). Not sure which version, though, but I had to add both shortcuts for both contexts in order for forward _and_ backward window cycling to work...

**Comment by ConradIrwin** [comment] 2024-12-06 21:33
And which keyboard layout? 

In theory Zed's keybindings should be moved out of the way automatically, but it seems like that's broken for you.

**Comment by joachimtingvold** [comment] 2024-12-06 21:38
> And which keyboard layout?

Norwegian.

**Comment by ConradIrwin** [comment] 2024-12-06 21:50
Thanks! Are you by chance using the layout macOS calls Norwegian Extended?

On a normal Norwegian keyboard, we should map the shortcuts from cmd-> and cmd-< to cmd-: and cmd-; , but it looks like our mapping for Norwegian Extended is missing that.

You can see what keyboard zed thinks you're using with cmd-shift-p "debug: open key context view":

<img width="882" alt="Screenshot 2024-12-06 at 14 49 30" src="https://github.com/user-attachments/assets/9a2ebf65-e31f-4ae6-be7c-2fb85f4a25d0">

**Comment by joachimtingvold** [comment] 2024-12-06 21:53
Might be related to me using Ukelele custom Norwegian keymap (I'm remapping a few keys not related to cmd-< or cmd->).

![image](https://github.com/user-attachments/assets/e23e098f-2fae-4212-bbe9-9a11ed05a24c)

**Comment by ConradIrwin** [comment] 2024-12-06 22:03
Yes, that would be the problem! Thank you for taking the time to explain.

Currently Zed ships with equivalents for the builtin Mac keyboard layouts, but we don't have a way to detect key equivalents automatically for custom layouts (nor yet a way to configure these in your settings, though one day I'd love to add that).

**Comment by joachimtingvold** [comment] 2024-12-06 23:07
So it would not be as trivial as `if keyboard_layout contains "norwegian"` or similar? Or is the cmd-> and cmd-< different within the different Norwegian keyboard layouts?

**Comment by ConradIrwin** [comment] 2024-12-06 23:11
Not quite (the values for Norwegian and Norwegian extended differ in subtleties like ^ vs ˆ), so it'd really need you to configure your bindings how you want them.

VSCode has a cool thing where they read the keyboard layout and shuffle the shortcuts automatically. We could consider doing something similar too.
