### ISSUE TITLE
Open file with no content

### ISSUE THREAD

**Issue by cycle2zhou** [zed-industries/zed#18322] opened 2024-09-25 06:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The txt file can be opened but does not display any content.

### Environment

Apple M1 Max
Memory - 32 GB
MacOs - 15.0 (24A335)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[aaa.txt](https://github.com/user-attachments/files/17126063/aaa.txt)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17126103/Zed.log)

</pre></details>

**Comment by CharlesChen0823** [comment] 2024-09-25 06:52
i think this file cannot opened, because this file is encoding with `utf-16 le`.

**Comment by cycle2zhou** [comment] 2024-09-25 07:06
> i think this file cannot opened, because this file is encoding with `utf-16 le`.

Can be opened when using vscode

**Comment by CharlesChen0823** [comment] 2024-09-25 07:24
yeah, i known. current zed not support other encoding method files.

**Comment by SomeoneToIgnore** [comment] 2024-09-25 08:54
Duplicate of https://github.com/zed-industries/zed/issues/16965

**Closed by SomeoneToIgnore** 2024-09-25 08:54 UTC
Labels: defect, triage, admin read
