### ISSUE TITLE
Git branch sync Bug

### ISSUE THREAD

**Issue by hann-yun** [zed-industries/zed#16582] opened 2024-08-21 08:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when i change git branch, different zed's git branch with git branch (terminal)

### Environment

OS : Mac Apple M1 Pro (14.4.1 (23E224))
Zed : Zed 0.149.3 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/37c77501-36ae-416c-a958-5a9334ebc952)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-26 16:03
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/13176

**Closed by notpeter** 2024-08-26 16:03 UTC
Labels: defect, git
