### ISSUE TITLE
Files not saving on macOS 14.3

### ISSUE THREAD

**Issue by yashchittora** [zed-industries/zed#7269] opened 2024-02-02 05:49 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The scenario is that I was not editing a existing file. I opened Zed and started writing onto untitled file that is currently unsaved. On saving it , it doesn't respond.
The save function , either using menu bar or CMD+S does not work. The app simply stucks and shows a spinning beachball icon (macOS).

### Environment

Zed: v0.119.20 (Zed)
OS: macOS 14.3.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by tecandrew** [comment] 2024-02-02 06:19
just experienced this on Zed Preview. Was trying to properly port a theme 

<img width="969" alt="image" src="https://github.com/zed-industries/zed/assets/21319730/168e0212-10bb-4a43-9f44-5c49b8b6e0e7">

**Comment by tecandrew** [comment] 2024-02-02 06:24
may not be related to Zed... might be MacOS related? Seems like I can't save on any other app either. (was trying to save the Zed log file)

<img width="796" alt="image" src="https://github.com/zed-industries/zed/assets/21319730/999b1d92-7343-44a3-86d5-213332c63e3f">

**Comment by bainian** [comment] 2024-02-02 08:34
Mac OS：Apple M2 Pro 14.2.1 (23C71)
Zed: v0.119.20 (Zed)

me too. writing in untitled zed,  when save or save other and zed begin not respond.

**Comment by Sakib25800** [comment] 2024-02-04 19:26
Mac OS: Apple M2 Air 14.1.2 (23B92)
Zed 0.120.6

Made changes to an existing file and saving does not work. 
On exit the save or don't save prompt appeared but pressing save did not save the file. Pressing don't save did work.

**Comment by mrnugget** [comment] 2024-02-05 08:08
Thanks for that addition @Sakib25800! So you opened a directory but were missing write-permissions in that directory?

Can the others in here confirm that this is the issue?

**Comment by Sakib25800** [comment] 2024-02-05 15:34
Yep, exactly.

**Comment by iamkeyur** [comment] 2024-02-17 16:01
Yes. This is an actual issue. It can't save file even with the permission. It completely hangs on Cmd+S.

**Comment by mrnugget** [comment] 2024-02-19 08:23
> It can't save file even with the permission.

You have write and execute permissions for a directory but can't save a file in it?

**Comment by iamkeyur** [comment] 2024-02-21 04:17
> > It can't save file even with the permission.
> 
> 
> 
> You have write and execute permissions for a directory but can't save a file in it?

Yes. That's true.

**Comment by arielgamino** [comment] 2024-02-29 15:37
I had the same issue, **FIXED** by adding a folder to project first (File-->Add Folder to Project).  Now I can save.

**Comment by i-a-n** [comment] 2024-02-29 17:36
same issue here: 
macOS 13.2.1
Zed 0.123.6

steps:
1. `command + n` for new file
2. type a few lines
3. `command + s` to save: hangs for a while, eventually stops hanging, does nothing at all
5. click `File > Save As`: hangs for a while, eventually stops hanging, does nothing at all

I currently have it open in this state and can reproduce, lmk if you want me to run any diagnostics while I do it

**Comment by daoulruke** [comment] 2024-03-01 02:26
Broadly, I have same 'cannot save' issue.
Always with new files, sometimes with others.

An expectation for users to apply configuration before they can save files is out of alignment with the application's otherwise high standard of quality, so high that I continue to use Zed despite this fundamental flaw.. though eventually some scenario will trigger an rage-existential event.

**Comment by mrnugget** [comment] 2024-03-01 08:48
@i-a-n in which folder? which project? or no project open?

**Comment by daoulruke** [comment] 2024-03-01 09:08
I’m certain the issue has struck when no folder or project has been open, I
*think* other scenarios too.

1. Load Zed [new empty window opens]
2. File->New [new file opens]
3. Type content…
4. Attempt File->Save [no response*]
5. Attempt File->Save As [no response*]

* Sometimes I briefly see the rainbow wheel of death, other times nothing
at all.

**Comment by daoulruke** [comment] 2024-03-01 09:38
FYI: after updating from 0.123.2 to 0.124.8 it seems the bug is gone.

**Comment by mrnugget** [comment] 2024-03-01 12:53
Can others confirm that it's fixed in the newest version? I assume the file-permission problems are still there, though.

**Comment by Sakib25800** [comment] 2024-03-01 13:03
After updating it works perfectly fine for me.

**Comment by SaidAbedi** [comment] 2024-03-01 15:58
Im on 0.124.8 and still can not save.

**Comment by i-a-n** [comment] 2024-03-01 16:54
> Can others confirm that it's fixed in the newest version? I assume the file-permission problems are still there, though.

I upgraded to `0.124.8` and the workflow that wasn't working now works. I'll report back if it fails again 👍

**Comment by mrnugget** [comment] 2024-03-04 08:33
> Im on 0.124.8 and still can not save.

What are your exact steps to reproduce?

As a general note in this issue here: exact steps to reproduce and clarity about what exactly doesn't work are essential. Otherwise we might lump two different issues together and not address root problems.

**Comment by Ceesaxp** [comment] 2024-03-18 10:15
I've just updated to 0.125.4 (eae06aaca98f0dd941c03679bf2428ad236ba217) and the issue is still there, i.e. anything that gets created outside of any project setup – cannot be saved via either Cmd-S or Cmd-Shift-S. Same steps to reproduce, as above:

1. New window via Cmd-Shift-N
2. Modify new buffer that is created automatically
3. Try saving (Cmd-S/Cmd-Shift-S)
4. Nothing happens

**Comment by mrnugget** [comment] 2024-03-18 10:28
@Ceesaxp thanks for the steps!

(FWIW, the newest release is [0.126.2](https://zed.dev/releases/stable/0.126.2). Not sure that will change anything, but worth a shot.)

Do you see any errors in `~/Library/Logs/Zed/Zed.log` when you try to save?

**Comment by Ceesaxp** [comment] 2024-03-18 10:33
> @Ceesaxp thanks for the steps!
> 
> (FWIW, the newest release is [0.126.2](https://zed.dev/releases/stable/0.126.2). Not sure that will change anything, but worth a shot.)
> 
> Do you see any errors in `~/Library/Logs/Zed/Zed.log` when you try to save?

It got me first up to 0.125.4, now after update to 0.126.2 – it works. And File/Open also works (did not in 0.125.4).

Super!

**Comment by dacort** [comment] 2024-03-22 17:33
Just ran into this issue.

macOS 14.3.1
Zed 0.126.3

No errors in `Zed.log` when I try to save. Permissions look fine on the new directory. Steps I took:

```
mkdir ~/Documents/some-folder
zed ~/Documents/some-folder
Open new untitled buffer
Try saving
Nothing happens / beach ball
```

It does look like Zed auto-downloaded an update (0.127.3) since I ran into this, and now it works fine.

In the previous version (0.126.3), I had an error in the log when I first opened Zed.

```
2024-03-22T10:28:05-07:00 [ERROR] crates/workspace/src/persistence/model.rs:267: No path stored for this editor
```

**Comment by mrnugget** [comment] 2024-03-25 08:31
Thanks for the comment, @dacort. Sounds like it's fixed in 0.127.3 but I want to confirm something: does Zed.app have access to your Documents folder?

![screenshot-2024-03-25-09 30 43@2x](https://github.com/zed-industries/zed/assets/1185253/f9c9b320-290a-41f9-8bac-fa440264de5b)

**Comment by dacort** [comment] 2024-03-25 16:45
@mrnugget Confirmed that it does.
<img width="486" alt="image" src="https://github.com/zed-industries/zed/assets/1512/96bdfb5e-38bb-4bc3-bf01-cd3916980959">

**Comment by juliocoelho** [comment] 2024-05-20 12:20
Still cannot save any file:
macOS 14.4.1
Zed 0.135.2
Zed has permission to write files on mac in "Privacy & Security / Files and Folders"
I have writing permission in the directory where the project resides 

steps:

command + n for new file
type a few lines
command + s to save: no response
command + w  to close file: it warns "xxx.txt contains unsaved edits. Do you want to save it?"

using the menu option to save also does nothing.

**Comment by mrnugget** [comment] 2024-05-21 08:04
@juliocoelho anything in the logs?

**Comment by juliocoelho** [comment] 2024-05-21 08:42
@mrnugget nothing there.

To make a simpler log version, I deleted it, and open a new zed session, did the steps, and the log result is

2024-05-21T09:37:33+01:00 [INFO] ========== starting zed ==========
2024-05-21T09:37:33+01:00 [INFO] Opening main db
2024-05-21T09:37:33+01:00 [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-05-21T09:37:33+01:00 [INFO] extensions updated. loading 6, reloading 0, unloading 0
2024-05-21T09:37:33+01:00 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/ImageMagick/bin:/Users/juliocoelho/.modular/pkg/packages.modular.com_mojo/bin:
2024-05-21T09:37:33+01:00 [INFO] Opening main db
2024-05-21T09:37:33+01:00 [INFO] Opening main db
2024-05-21T09:37:33+01:00 [INFO] set status on client 0: Authenticating
2024-05-21T09:37:33+01:00 [INFO] set status on client 150844: Connecting
2024-05-21T09:37:33+01:00 [ERROR] crates/workspace/src/persistence/model.rs:313: No path stored for this editor
2024-05-21T09:37:33+01:00 [ERROR] crates/workspace/src/persistence/model.rs:313: No worktree for path: "/Users/juliocoelho/Library/Logs/Zed/Zed.log"
2024-05-21T09:37:33+01:00 [ERROR] crates/workspace/src/persistence/model.rs:313: No path stored for this editor
2024-05-21T09:37:33+01:00 [INFO] starting language servers for CSV: 
2024-05-21T09:37:33+01:00 [INFO] starting language servers for CSV: 
2024-05-21T09:37:34+01:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-05-21T09:37:34+01:00 [INFO] starting language servers for CSV: 
2024-05-21T09:37:34+01:00 [INFO] Node runtime install_if_needed
2024-05-21T09:37:34+01:00 [INFO] starting language server. binary path: "/Users/juliocoelho/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/", args: ["/Users/juliocoelho/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-05-21T09:37:34+01:00 [INFO] add connection to peer
2024-05-21T09:37:34+01:00 [INFO] add_connection;
2024-05-21T09:37:34+01:00 [INFO] waiting for server hello
2024-05-21T09:37:34+01:00 [INFO] got server hello
2024-05-21T09:37:34+01:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 427, id: 2466857 })
2024-05-21T09:37:34+01:00 [INFO] set status on client 150844: Connected { peer_id: PeerId { owner_id: 427, id: 2466857 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-05-21T09:37:34+01:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-05-21T08:37:34.791Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-05-21T08:37:34.791Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-05-21T09:37:34+01:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "a7f5b0ea-5ec1-4746-9a64-2251b4fa2608",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-05-21T09:37:34+01:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-05-21T08:37:34.799Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-05-21T08:37:34.799Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-05-21T09:37:47+01:00 [INFO] open paths ["/Users/juliocoelho/Library/Logs/Zed/Zed.log"]

**Comment by mrnugget** [comment] 2024-05-21 08:48
Can you try a Preview release? https://zed.dev/releases/preview

I don't think there's anything between the current stable and the Preview release that might fix it, but since Preview is a separate app, I wonder whether there's a permission problem that might be fixed by using a new app entirely.

**Comment by juliocoelho** [comment] 2024-05-21 08:57
Similar situation.

However I made a mistake, saving from the menu option inded saves the content of the file, but using CMD+S does not.

In the default key mapping I can find the mapping for the cmd-s.
"context": "Workspace",
"bindings": {
   ....
   "cmd-s": "workspace::Save",
.....

I did not add any additional key mapping.

**Comment by mrnugget** [comment] 2024-05-21 09:06
Ohhh, okay, interesting! So does that also work with the current stable version?


If so, what happens when you open the command palette (`cmd-shift-p`) and use `workspace: save` from there?

![screenshot-2024-05-21-11 05 35@2x](https://github.com/zed-industries/zed/assets/1185253/c29eaaa1-0b0e-457b-8633-ef39670a73e2)

**Comment by bennetbo** [comment] 2024-05-21 09:10
Is the keybinding the only thing that's not working? Last week we had similar reports and it turns out that the ChatGpt Mac app intercepts cmd-s

https://github.com/zed-industries/zed/issues/11907#issuecomment-2116058015

**Comment by juliocoelho** [comment] 2024-05-21 10:09
@bennetbo you are totally right it was ChatGPT that was intercepting the cmd-s

@mrnugget Thank you for your support

**Comment by notpeter** [comment] 2024-06-27 13:51
Is anyone still experiencing this issue with current Zed releases?

I didn't have [ChatGPT intercepts cmd+s globally](https://community.openai.com/t/chatgpt-desktop-app-overwrites-cmd-s/756494/10) on my May bingo card, but it seems like they've fixed it, but wanted to check before I closed this.

**Closed** 2024-09-16 18:48 UTC
Labels: defect, editor
