### ISSUE TITLE
R support

### ISSUE THREAD

**Issue by aravezskinteeth** [zed-industries/zed#8027] opened 2024-02-19 18:48 UTC
### Check for existing issues

- [X] Completed

### Language

R

### Tree Sitter parser link

https://github.com/r-lib/tree-sitter-r

### Language server link

https://github.com/REditorSupport/languageserver

**Comment by JosephTLyons** [comment] 2024-02-19 21:09
Hey @aravezskinteeth ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4972

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-19 21:09 UTC
Labels: enhancement, potential extension, language, unsupported language

**Comment by aravezskinteeth** [comment] 2024-02-19 21:15
Done!
