### ISSUE TITLE
Rust tasks broken under nushell

### ISSUE THREAD

**Issue by bemyak** [zed-industries/zed#18564] opened 2024-10-01 06:36 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open any rust project with Nushell as your shell, spawn some task that uses ZED_CUSTOM_RUST_PACKAGE. Get
```
Error: nu::parser::env_var_not_var

  × Use $env.ZED_CUSTOM_RUST_PACKAGE instead of $ZED_CUSTOM_RUST_PACKAGE.
   ╭─[source:1:15]
 1 │ cargo test -p $ZED_CUSTOM_RUST_PACKAGE $ZED_SYMBOL -- --nocapture
   ·               ────────────┬───────────
   ·                           ╰── use $env.ZED_CUSTOM_RUST_PACKAGE instead of $ZED_CUSTOM_RUST_PACKAGE
   ╰────
```

This bug is similar to https://github.com/zed-industries/zed/issues/10998. The assumption for the fix was:
> `$ZED_CUSTOM_RUST_PACKAGE` should work for any shell.
>
> Unless some exotic syntax is used (e.g. `${NAME}_id`) bracketing variables do not offer any advantage.

But this doesn't hold true for Nushell, where environment variables are accessed with `$env.VAR_NAME`.

I guess a solution could be to allow user to customize "task templates" like the ones used for running Rust tests.

### Environment

Zed: v0.154.1 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 58.7 GiB
Architecture: x86_64
GPU: AMD Radeon 780M (RADV GFX1103_R1) || radv || Mesa 24.2.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/9ca691a3-9145-4e51-8eac-d43f161416cd)

### If applicable, attach your Zed.log file to this issue.

Not applicable IMO

**Comment by osiewicz** [comment] 2024-10-01 06:49
> I guess a solution could be to allow user to customize "task templates" like the ones used for running Rust tests.
That's already possible. Tasks have `tags` field on them which allows you to bind a task template to a given task tag. Rust tests have a `rust-test` tag.
If you have a user-defined task with a tag, that task will take precedence over language-provided tasks.

**Comment by SomeoneToIgnore** [comment] 2024-10-01 06:54
It is also a duplicate of https://github.com/zed-industries/zed/issues/12685

**Comment by bemyak** [comment] 2024-10-01 06:59
Thank you, adding this task solved the issue:
```json
  {
    "label": "Run Rust tests",
    "command": "cargo test -p $env.ZED_CUSTOM_RUST_PACKAGE $env.ZED_STEM",
    "tags": ["rust-test"],
    "use_new_terminal": true
  }
```

As for the duplicate, I was searching for `nushell` instead of `nu` and missed that one, sorry :sweat_smile:

**Closed** 2024-10-01 07:19 UTC
Labels: defect, triage, admin read
