### ISSUE TITLE
remote development  zed: open local tasks not save in ZED_WORKTREE_ROOT, save in ~/.config/zed/.zed/task.json

### ISSUE THREAD

**Issue by ChaochaoCui** [zed-industries/zed#15168] opened 2024-07-25 11:39 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

open remote project

zed:  zed: open local tasks , to new a task

this task.json in ~/.config/zed/.zed/task.json

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 15 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-25 16:42
I am not able to reproduce this (I attempted connecting from MacOS to Linux).

When I ran `zed: open local tasks` the file was created in `.zed/tasks.json` as expected.

**Comment by ChaochaoCui** [comment] 2024-07-26 13:33
I use ssh , connect from Ubuntu 24.04 to Ubuntu.

**Comment by ChaochaoCui** [comment] 2024-07-26 13:34
this task.json in server  ~/.config/zed/.zed/task.json, not in server ${workspaceFolder}/.zed/.

**Comment by ChaochaoCui** [comment] 2024-07-26 13:42
![image](https://github.com/user-attachments/assets/7f7d5802-857b-4d13-9ff6-de3cc80c545b)

**Comment by ChaochaoCui** [comment] 2024-07-26 13:44
@notpeter

**Comment by notpeter** [comment] 2024-07-26 13:47
No need to @ me. I get notifications.

**Comment by notpeter** [comment] 2024-10-13 14:02
There has been significant recent work to improve SSH remoting.
I just tested this in nightly and `zed: open local tasks` now correctly opens `.zed/tasks.json`.  This work will be released this week in Preview and next week in stable.

Thanks for reporting.

**Closed by notpeter** 2024-10-13 14:02 UTC
Labels: defect, tasks, remote dev
