### ISSUE TITLE
[Windows] Failed to start language server, generated path seems invalid

### ISSUE THREAD

**Issue by conorvenus** [zed-industries/zed#17571] opened 2024-09-08 18:49 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever Zed attempts to start a language server, it seems to produce the wrong path to the `server.js` module:

```
2024-09-08T19:27:04.1166287+01:00 [INFO] starting language server. binary path: "C:\\Users\\conor\\AppData\\Local\\Zed\\node\\node-v22.5.1-win-x64\\node.exe", working directory: "C:\\Users\\conor\\Desktop\\portfolio", args: ["/C:\\Users\\conor\\AppData\\Local\\Zed\\extensions\\work\\svelte/node_modules/svelte-language-server/bin/server.js", "--stdio"]
2024-09-08T19:27:04.1794046+01:00 [ERROR] cannot read LSP message headers
2024-09-08T19:27:04.1796993+01:00 [ERROR] failed to start language server "svelte-language-server": oneshot canceled
2024-09-08T19:27:04.1797999+01:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1222\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\C:\\...
```

It can first be noticed in the `args: ["/C:\\..."]` with a prepended `/` which then `node` seems to interpret as the module being located at `C:\\C:\\...`

In terms of reproducibility, I am unsure, I just built Zed on my machine, ran it and installed a few extensions and that was it.

### Environment

Zed: v0.152.0 (Zed Dev 072513f59f54290d03424d8873a6e6dd46764b7e)
OS: Windows 10.0.22631
Memory: 15.8 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || 101.5989

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-08T19:27:04.1166287+01:00 [INFO] starting language server. binary path: "C:\\Users\\conor\\AppData\\Local\\Zed\\node\\node-v22.5.1-win-x64\\node.exe", working directory: "C:\\Users\\conor\\Desktop\\portfolio", args: ["/C:\\Users\\conor\\AppData\\Local\\Zed\\extensions\\work\\svelte/node_modules/svelte-language-server/bin/server.js", "--stdio"]
2024-09-08T19:27:04.1794046+01:00 [ERROR] cannot read LSP message headers
2024-09-08T19:27:04.1796993+01:00 [ERROR] failed to start language server "svelte-language-server": oneshot canceled
2024-09-08T19:27:04.1797999+01:00 [ERROR] server stderr: Some("node:internal/modules/cjs/loader:1222\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\C:\\Users\\conor\\AppData\\Local\\Zed\\extensions\\work\\svelte\\node_modules\\svelte-language-server\\bin\\server.js'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)\r\n    at Module._load (node:internal/modules/cjs/loader:1045:27)\r\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\r\n    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)\r\n    at node:internal/main/run_main_module:30:49 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v22.5.1\r\n")
</pre></details>

**Comment by AlbertMarashi** [comment] 2024-09-09 08:42
Seems like a windows bug

**Comment by dovakin0007** [comment] 2024-09-09 15:25
its svelte language server specific issue I believe

**Comment by conorvenus** [comment] 2024-09-09 16:20
> its svelte language server specific issue I believe and the same happens with tailwindcss for me but for the other languages it does work fine

I am unsure, because it does the same for HTML too for me - so I am thinking it must just be an issue with how the paths are formed on Windows within Zed for whatever reason.

**Comment by dovakin0007** [comment] 2024-09-09 16:23
> > its svelte language server specific issue I believe and the same happens with tailwindcss for me but for the other languages it does work fine
> 
> I am unsure, because it does the same for HTML too for me - so I am thinking it must just be an issue with how the paths are formed on Windows within Zed for whatever reason.

maybe but it has something to do with node modules how they handle directory I didn't have any issues with Zig extension

**Comment by conorvenus** [comment] 2024-09-09 17:02
> > > its svelte language server specific issue I believe and the same happens with tailwindcss for me but for the other languages it does work fine
> > 
> > 
> > I am unsure, because it does the same for HTML too for me - so I am thinking it must just be an issue with how the paths are formed on Windows within Zed for whatever reason.
> 
> maybe but it has something to do with node modules how they handle directory I didn't have any issues with Zig extension

Perhaps - by the looks of it to me, it seems to be a problem within Zed itself passing args as `['/C:\\...']`, that prepended `/` shouldn't be there on Windows

**Comment by ItaloCunhaBueno** [comment] 2024-09-27 10:40
I'm having the exact same issue, also using deevus nightly build from https://github.com/deevus/zed-windows-builds

**Comment by JunkuiZhang** [comment] 2024-09-28 06:22
Extension which is downloaded from extension store could not work for now, see #15004

A temp solution:
 
```bash
diff --git a/crates/extension/src/extension_lsp_adapter.rs b/crates/extension/src/extension_lsp_adapter.rs
index 25179acec..ccc1cbf5e 100644
--- a/crates/extension/src/extension_lsp_adapter.rs
+++ b/crates/extension/src/extension_lsp_adapter.rs
@@ -88,7 +88,17 @@ impl LspAdapter for ExtensionLspAdapter {

             Ok(LanguageServerBinary {
                 path,
-                arguments: command.args.into_iter().map(|arg| arg.into()).collect(),
+                arguments: command
+                    .args
+                    .into_iter()
+                    .map(|arg| {
+                        if let Some(arg) = arg.strip_prefix('/') {
+                            arg.into()
+                        } else {
+                            arg.into()
+                        }
+                    })
+                    .collect(),
                 env: Some(command.env.into_iter().collect()),
             })
         }
```

**Comment by edugzlez** [comment] 2024-10-01 16:19
> Extension which is downloaded from extension store could not work for now, see #15004
> 
> A temp solution:
> 
> ```shell
> diff --git a/crates/extension/src/extension_lsp_adapter.rs b/crates/extension/src/extension_lsp_adapter.rs
> index 25179acec..ccc1cbf5e 100644
> --- a/crates/extension/src/extension_lsp_adapter.rs
> +++ b/crates/extension/src/extension_lsp_adapter.rs
> @@ -88,7 +88,17 @@ impl LspAdapter for ExtensionLspAdapter {
> 
>              Ok(LanguageServerBinary {
>                  path,
> -                arguments: command.args.into_iter().map(|arg| arg.into()).collect(),
> +                arguments: command
> +                    .args
> +                    .into_iter()
> +                    .map(|arg| {
> +                        if let Some(arg) = arg.strip_prefix('/') {
> +                            arg.into()
> +                        } else {
> +                            arg.into()
> +                        }
> +                    })
> +                    .collect(),
>                  env: Some(command.env.into_iter().collect()),
>              })
>          }
> ```

The problem exists elsewhere as well. The temporary solution does not work globally.

For astro it loads `typescript_tsdk_path` with `env::current_dir()`, but this does not pass by argument in the `LanguageServerBinary`, so it still gives problems.

https://github.com/zed-industries/zed/blob/051627c4493b5f5446cb3957576be89899b1d386/extensions/astro/src/astro.rs#L116

There should be a way to fix it without having to patch it. It is strange that the `env::current_dir()` and subsequent instructions are causing this problem.

**Comment by JunkuiZhang** [comment] 2024-10-01 16:33
> There should be a way to fix it without having to patch it. It is strange that the `env::current_dir()` and subsequent instructions are causing this problem.

From my understanding, the `WASM` environment is some kind of sand-box, which has a unix-path file system. So, the return path by calling `current_dir()` inside `WASM` will always start with `/`. So, there is no way to fix.

**Comment by alvgaona** [comment] 2024-10-12 00:11
The same happens for `@astrojs/language-server` in Windows.

```text
Language server error: astro-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'C:\C:\Users\alvga\AppData\Local\Zed\extensions\work\astro\node_modules\@astrojs\language-server\bin\nodeServer.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.5.0
```

For some reason it has `C:\C:\`.

**Comment by simonerlic** [comment] 2024-10-18 21:51
> The same happens for `@astrojs/language-server` in Windows.
> 
> ```
> Language server error: astro-language-server
> 
> oneshot canceled
> -- stderr--
> node:internal/modules/cjs/loader:1051
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\C:\Users\alvga\AppData\Local\Zed\extensions\work\astro\node_modules\@astrojs\language-server\bin\nodeServer.js'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
>     at Module._load (node:internal/modules/cjs/loader:901:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
>     at node:internal/main/run_main_module:23:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
> Node.js v20.5.0
> ```
> 
> For some reason it has `C:\C:\`.

Curious -- do you have multiple drives? I wonder if this is a multi-drive issue on Windows. Mine shows as `D:\C:\`, as my projects are on `D:\`

**Comment by alvgaona** [comment] 2024-10-19 01:14
> > The same happens for `@astrojs/language-server` in Windows.
> > ```
> > Language server error: astro-language-server
> > 
> > oneshot canceled
> > -- stderr--
> > node:internal/modules/cjs/loader:1051
> >   throw err;
> >   ^
> > 
> > Error: Cannot find module 'C:\C:\Users\alvga\AppData\Local\Zed\extensions\work\astro\node_modules\@astrojs\language-server\bin\nodeServer.js'
> >     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
> >     at Module._load (node:internal/modules/cjs/loader:901:27)
> >     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
> >     at node:internal/main/run_main_module:23:47 {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: []
> > }
> > 
> > Node.js v20.5.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For some reason it has `C:\C:\`.
> 
> Curious -- do you have multiple drives? I wonder if this is a multi-drive issue on Windows. Mine shows as `D:\C:\`, as my projects are on `D:\`

My projects are in `C:\` . I have an extra drive with letter `E:\`.

**Comment by simonerlic** [comment] 2024-10-20 23:20
> > > The same happens for `@astrojs/language-server` in Windows.
> > > ```
> > > Language server error: astro-language-server
> > > 
> > > oneshot canceled
> > > -- stderr--
> > > node:internal/modules/cjs/loader:1051
> > >   throw err;
> > >   ^
> > > 
> > > Error: Cannot find module 'C:\C:\Users\alvga\AppData\Local\Zed\extensions\work\astro\node_modules\@astrojs\language-server\bin\nodeServer.js'
> > >     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
> > >     at Module._load (node:internal/modules/cjs/loader:901:27)
> > >     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
> > >     at node:internal/main/run_main_module:23:47 {
> > >   code: 'MODULE_NOT_FOUND',
> > >   requireStack: []
> > > }
> > > 
> > > Node.js v20.5.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > For some reason it has `C:\C:\`.
> > 
> > 
> > Curious -- do you have multiple drives? I wonder if this is a multi-drive issue on Windows. Mine shows as `D:\C:\`, as my projects are on `D:\`
> 
> My projects are in `C:\` . I have an extra drive with letter `E:\`.

I'm starting to think that this might be caused by the assumption that the user has a single-drive system - maybe whatever call they make to get the file path returns just the path normally on a single drive system, and the path with the drive on multi drive systems?

I'll take a look this evening, as I'm not familiar with how it determines the path currently.

**Comment by kevivs** [comment] 2024-11-30 05:08
> > > > The same happens for `@astrojs/language-server` in Windows.
> > > > ```
> > > > Language server error: astro-language-server
> > > > 
> > > > oneshot canceled
> > > > -- stderr--
> > > > node:internal/modules/cjs/loader:1051
> > > >   throw err;
> > > >   ^
> > > > 
> > > > Error: Cannot find module 'C:\C:\Users\alvga\AppData\Local\Zed\extensions\work\astro\node_modules\@astrojs\language-server\bin\nodeServer.js'
> > > >     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
> > > >     at Module._load (node:internal/modules/cjs/loader:901:27)
> > > >     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
> > > >     at node:internal/main/run_main_module:23:47 {
> > > >   code: 'MODULE_NOT_FOUND',
> > > >   requireStack: []
> > > > }
> > > > 
> > > > Node.js v20.5.0
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > For some reason it has `C:\C:\`.
> > > 
> > > 
> > > Curious -- do you have multiple drives? I wonder if this is a multi-drive issue on Windows. Mine shows as `D:\C:\`, as my projects are on `D:\`
> > 
> > 
> > My projects are in `C:\` . I have an extra drive with letter `E:\`.
> 
> I'm starting to think that this might be caused by the assumption that the user has a single-drive system - maybe whatever call they make to get the file path returns just the path normally on a single drive system, and the path with the drive on multi drive systems?
> 
> I'll take a look this evening, as I'm not familiar with how it determines the path currently.

"might be caused by the assumption that the user has a single-drive system" Even in single drive system, it shows same error:
2024-11-30T10:29:09.0331946+05:30 [ERROR] Failed to start language server "svelte-language-server": oneshot canceled
2024-11-30T10:29:09.033355+05:30 [ERROR] server stderr: "node:internal/modules/cjs/loader:1242\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\C:\\Users\\sresu\\AppData\\Local\\Zed\\extensions\\work\\svelte\\node_modules\\svelte-language-server\\bin\\server.js'\r\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1239:15)\r\n    at Function._load (node:internal/modules/cjs/loader:1064:27)\r\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\r\n    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)\r\n    at node:internal/main/run_main_module:36:49 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v23.3.0\r\n"

**Comment by alvgaona** [comment] 2024-11-30 06:06
Refer to this issue which explains the reason for the failure: https://github.com/zed-industries/zed/issues/20559

**Comment by Adel-Harrat** [comment] 2024-12-08 08:32
Language server error: emmet-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'C:\C:\Users\X280\AppData\Local\Zed\extensions\work\emmet\node_modules\.bin\emmet-language-server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0

**Comment by dylansantwani** [comment] 2024-12-08 19:39
Language server error: vscode-html-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1252
  throw err;
  ^

Error: Cannot find module 'C:\C:\Users\dylan\AppData\Local\Zed\extensions\work\html\node_modules\@zed-industries\vscode-langservers-extracted\bin\vscode-html-language-server'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.11.0

**Comment by dylansantwani** [comment] 2024-12-08 20:17
https://github.com/dylansantwani/zed-fixed-windows try this fix. It is working for me on vanilla win 11.

**Comment by fbtwitter** [comment] 2024-12-10 04:45
@dylansantwani what's the fixes ? would you share the release release bundle file ?

**Comment by dovakin0007** [comment] 2024-12-10 05:08
> @dylansantwani what's the fixes ? would you share the release release bundle file ?
> 
> 
> 
> i got an error about this language server to start emmet now
> 
> 

Do check the above replies they do have a temporary fix and also reason why it can't be changed for now

**Comment by dylansantwani** [comment] 2024-12-10 21:40
> @dylansantwani what's the fixes ? would you share the release release bundle file ?
> 
> i got an error about this language server to start emmet now

Hello, yes I can simply clone https://github.com/dylansantwani/zed-fixed-windows  and run cargo run --release 
if you have any questions please email me

**Comment by notpeter** [comment] 2024-12-10 22:18
@dylansantwani: Please do not link to a copy of the zed repositories which has been stripped of all it's history such that user's cannot easily determine what changes you've made against upstream.  In the future, use the Github "Fork" button. This will preserve all the git commit history and then add your new changes in a commit on a branch. 

We generally assume such actions to be malicious in nature.  Instead you just wasted a bunch of my time so I could determine you checked out https://github.com/zed-industries/zed/commit/ac07b9197a5a2814dad605148fe032f6777ce5fe and made a one-line change.

```patch
--- zed/crates/language_extension/src/extension_lsp_adapter.rs	2024-12-10 15:07:44
+++ zed-fixed-windows/crates/language_extension/src/extension_lsp_adapter.rs	2024-12-10 15:07:20
@@ -155,7 +155,7 @@
 
             Ok(LanguageServerBinary {
                 path,
-                arguments: command.args.into_iter().map(|arg| arg.into()).collect(),
+                arguments: command.args.into_iter().map(|arg| arg.replace("/C:", "C:").into()).collect(),
                 env: Some(command.env.into_iter().collect()),
             })
         }
```

I assume this is a git/skill issue, but I want to be clear, your lack of competence wasted a bunch of my time just to confirm it was non-malicious. If I see this in the future, I will not be so generous and will permanently banned such users from the Zed community.

**Comment by dylansantwani** [comment] 2024-12-10 22:22
Hello,
I am not the best at git, and I am still learning. You are the one who chose to go through and see the one-line change I made. 
I personally did not ask you to review it. I will try to fork it next time, but it doesn't matter to me whether you spent time reviewing my code or not.
Thank you.

**Comment by alvgaona** [comment] 2024-12-11 01:10
This issue should be closed in favor of #20559. The root cause has already been identified. Discussions should happen over there.

**Comment by alvgaona** [comment] 2024-12-11 01:12
cc @SomeoneToIgnore ☝🏻

**Comment by notpeter** [comment] 2024-12-11 01:20
Closing in favor of:
- https://github.com/zed-industries/zed/issues/20559

**Closed by notpeter** 2024-12-11 01:20 UTC
Labels: bug, windows, language server

**Comment by fbtwitter** [comment] 2024-12-11 01:22
Hi @notpeter,

I was wondering if the fixes you mentioned apply only to the specific discussion here, or do they address the entire language server?

Recently, I had some issues with the language server while working with Astro, but it seemed to be resolved when I used the build from the Windows fork. However, I ran into more issues afterward, specifically with Emmet and Phpactor.

Could you please guide me on how to resolve these issues?

Thank you!
```
Language server error: emmet-language-server

oneshot canceled
-- stderr--
C:\Users\User\AppData\Local\Zed\extensions\work\emmet\node_modules\.bin\emmet-language-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (node:internal/modules/cjs/loader:1515:18)
    at Module._compile (node:internal/modules/cjs/loader:1537:20)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
    ```

**Comment by notpeter** [comment] 2024-12-11 02:49
I only included that diff because it was hidden in the history-less repository -- providing the diff makes it possible to discuss -- normally this is table stakes when people use commits for changes, but 🤷 . Anyways I haven't tested it, nor do I recommend using it.

Moving the emmet discussion to:
- https://github.com/zed-industries/zed/issues/21834
