### ISSUE TITLE
Zed failed to launch: Could not create directory "/Users/[]/.config/zed": Permission denied (os error 13)

### ISSUE THREAD

**Issue by MoPaMo** [zed-industries/zed#20162] opened 2024-11-04 11:39 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When trying to launch Zed after a new installation in MacOS 15.1, I get
Could not create directory "/Users/moritz/.config/zed": Permission denied (os error 13)
with my only option being to exit the project again

### Environment

- Couldn't start Zed in the first place -

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>
not created

**Comment by SomeoneToIgnore** [comment] 2024-11-04 11:42
Duplicate of https://github.com/zed-industries/zed/issues/15071

>  with my only option being to exit the project again

This is not the only option if one may change the directory permissions.

**Closed by SomeoneToIgnore** 2024-11-04 11:42 UTC
Labels: defect, triage, panic / crash, admin read

**Comment by MoPaMo** [comment] 2024-11-04 11:50
it literally is, there is only this one button
<img width="1136" alt="Screenshot 2024-11-04 at 12 50 20" src="https://github.com/user-attachments/assets/96dd8860-4c88-4221-b584-10b03331fb28">
I have already granted full disk access to zed

**Comment by notpeter** [comment] 2024-11-04 15:38
The issue is that you have incorrect permissions on your `~/.config` such that your user does not have permissions to create a `zed` directory there.  This is likely because the `~/.config` folder is owned by root and not your user.  The linked issue includes instructions for fixing this:

- https://github.com/zed-industries/zed/issues/13426#issuecomment-2187288480

**Comment by moonlockwood** [comment] 2024-12-21 00:54
if you don't want to change the permissions for the config folder, (i sure didn't) just make the directory and then it will run.

eg:

sudo mkdir /Users/moritz/.config/zed
