### ISSUE TITLE
Displayed image does not change after file has been modified

### ISSUE THREAD

**Issue by a-babarytskyi** [zed-industries/zed#19435] opened 2024-10-18 20:24 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open image file (PNG, PPM)
2. Replace image file contents
3. Old contents still displayed

What does help:
 - restarting Zed
 - renaming file with new contents and reopening (if you rename it back, it shows old contents again)

What does not help:
 - Closing tab and opening again
 - Deleting file from directory and copying again under the same name
 

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 14.6.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/17440404/Zed.log)

</pre></details>

**Comment by bbb651** [comment] 2024-10-19 00:55
This is a duplicate of #11529

**Closed** 2024-10-19 10:15 UTC
Labels: defect, triage, admin read
