### ISSUE TITLE
Zed Is consuming 5GB RAM

### ISSUE THREAD

**Issue by izanaty9** [zed-industries/zed#22464] opened 2024-12-28 14:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have only blank project opened in my editor and it's eating my Ram's, My laptop is 8GB Ram Macbook Air and it hang out whenever I opened Zed now.

### Zed Version and System Specs

Zed 0.166.1

MacBook Air 13-Inch, M1 Chip With 8-Core Processor And 7-Core Graphics/8GB RAM/256GB SSD/

### If applicable, add screenshots or screencasts of the incorrect state / behavior

<img width="935" alt="image" src="https://github.com/user-attachments/assets/c0e62024-3a5f-4a51-b86d-803bb9c27db5" />

<img width="247" alt="image" src="https://github.com/user-attachments/assets/c74e4090-f20a-4e23-9213-b7166e29c90e" />

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-12-28 15:37
No logs or any other details makes it hard to understand what's wrong with this, so I'll close this as a duplicate of https://github.com/zed-industries/zed/issues/18673 to consolidate the discussion.

**Closed by SomeoneToIgnore** 2024-12-28 15:37 UTC
Labels: bug, triage, admin read
