### ISSUE TITLE
Remote: port forwarding support

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/zed#21314] opened 2024-11-29 07:49 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When working on a project over remote that starts a webserver, it would be great if there was a way to forward the port it is listening to, as does VSCode for example. So for example, if I forward the `8080` port, I could access the development website by opening `http://127.0.0.1:8080` on my local machine.

Note: VSCode also allows to share websites over external github url but that's not what I'm asking for here.

### Environment

Zed: v0.164.0 (Zed Preview)
OS: macOS 13.7.1
Memory: 8 GiB
Architecture: x86_64

**Comment by notpeter** [comment] 2024-12-02 23:03
Duplicate of:
- #6920

**Closed by notpeter** 2024-12-02 23:03 UTC
Labels: enhancement, triage, admin read
