### ISSUE TITLE
Add `describe-key` command to show information of a given shortcut

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#16295] opened 2024-08-15 14:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Add `describe-key` command to show information of a given shortcut. After invoking this command, the user can press a shortcut key and obtain information about it. e.g. what command in what context these keystrokes are bound to. 

This is particularly useful when a shortcut key is not working, for example, due to being bound to the wrong context or a shortcut conflict.

Opening `keymap.json` to search sometimes just not working because the user does not know what actually the editor captures in what context.

In Emacs, [`describe-key`](https://www.google.com/search?q=emacs+describe-key&newwindow=1&sca_esv=9657867121c4e27e&sxsrf=ADLYWIIbVuIsspnr40o5CoyEJMMQWKpjWw%3A1723732270464&ei=LhG-ZtOKHIvO1e8Pg4Do-A4&ved=0ahUKEwjT2ayNm_eHAxULZ_UHHQMAGu8Q4dUDCA8&uact=5&oq=emacs+describe-key&gs_lp=Egxnd3Mtd2l6LXNlcnAaAhgDIhJlbWFjcyBkZXNjcmliZS1rZXkyBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIGEAAYFhgeMgYQABgWGB4yBhAAGBYYHjIIEAAYFhgeGA8yCxAAGIAEGKIEGIsDMgsQABiABBiiBBiLA0i7D1CXAliCDHABeAGQAQCYAfUBoAHSDKoBBTAuNC40uAEDyAEA-AEBmAIFoAKvBsICChAAGLADGNYEGEfCAgYQABgHGB7CAggQABiABBiiBMICBBAAGB6YAwCIBgGQBgiSBwUxLjIuMqAHjSA&sclient=gws-wiz-serp) is one of such example.

## Invoke the command
<img width="585" alt="image" src="https://github.com/user-attachments/assets/7566c0ab-e12c-4b9a-b6a2-7e2634c46737">

## Input a shortcut e.g. <kbd>C-c</kbd> <kbd>C-c</kbd> 
<img width="481" alt="image" src="https://github.com/user-attachments/assets/fc2eccfa-254c-4dda-9b75-422ad4d1cefc">

## Show information
<img width="636" alt="image" src="https://github.com/user-attachments/assets/df830f05-eb3b-4202-9296-42d43d392ebc">

**Comment by notpeter** [comment] 2024-08-15 15:13
Duplicate of:
- https://github.com/zed-industries/zed/issues/14677

**Closed by notpeter** 2024-08-15 15:13 UTC
Labels: enhancement, documentation, keymap / key binding, admin read
