### ISSUE TITLE
Hide cursor when Vim mode active

### ISSUE THREAD

**Issue by ericviana** [zed-industries/zed#12327] opened 2024-05-26 18:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Vscode and every other editors that I know hide the cursor when Vim mode is active and I start to move around the file. It's a small detail but would be nice to have it.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/76598237/d2bbf51e-f742-4a51-899f-2351e7225c08

**Comment by Moshyfawn** [comment] 2024-05-27 00:38
It seems there's already a feature request for this, so I'm going to close this issue. Be sure to +👍 the other thread.

Duplicate of:
- #11467

**Closed by Moshyfawn** 2024-05-27 00:38 UTC
Labels: enhancement, triage, admin read
