### ISSUE TITLE
Zed crash when you drag a tab from something that doesn't belong to Zed.

### ISSUE THREAD

**Issue by rafael-arreola** [zed-industries/zed#14382] opened 2024-07-13 04:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed crashes if you drag a tab from Firefox or Chrome out of the browser and it passes over the text editor.

### Environment

Linux  6.9.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000 x86_64 GNU/Linux
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen 9 5950X 16-Core Processor
CPU family:                           25
Model:                                33
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            1
Stepping:                             2
Frequency boost:                      enabled
CPU(s) scaling MHz:                   60%
CPU max MHz:                          5083.3979
CPU min MHz:                          2200.0000
BogoMIPS:                             6802.28

### If applicable, attach your Zed.log file to this issue.

2024-07-12T21:29:40-07:00 [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id cbfb79ce-4770-4d3f-b6dd-5c236833c4c7
2024-07-12T21:29:44-07:00 [ERROR] OtherError(IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
2024-07-12T21:29:44-07:00 [ERROR] oneshot canceled

**Comment by notpeter** [comment] 2024-07-13 05:19
1. Is this X11 or Wayland?
2. What desktop environment / window manager are you using?

**Comment by rafael-arreola** [comment] 2024-07-13 05:42
Wayland, Gnome

**Comment by rafael-arreola** [comment] 2024-07-13 05:45
I just checked that it doesn't happen in X11

**Comment by culebron** [comment] 2024-07-13 06:02
This doesn't happen to me.
Ubuntu 23.10, Mate 1.26.2

**Comment by rafael-arreola** [comment] 2024-07-13 06:30
[screen-recorder-fri-jul-12-2024-23-24-09.webm](https://github.com/user-attachments/assets/5b39c4fd-0ae9-4919-aea2-87d595dce6c8)

**Comment by SomeoneToIgnore** [comment] 2024-07-13 10:22
Duplicate of https://github.com/zed-industries/zed/issues/14189

**Closed by SomeoneToIgnore** 2024-07-13 10:22 UTC
Labels: defect, linux, linux-wayland
