### ISSUE TITLE
task spawn seemingly does nothing

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#19203] opened 2024-10-15 01:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried `task: spawn` with [the default example](https://zed.dev/docs/tasks) and it shows no output for me. I also tried creating a task like

```json
  {
    "label": "Open website",
    "command": "xdg-open https://google.com",
  }
```

and nothing even opened, even though copying and pasting the same command in the terminal which opened does successfully open the website in the browser.

I'm guessing this is 

### Environment

Zed: v0.156.2 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by andrewbanchich** [comment] 2024-10-15 21:58
[Screencast from 2024-10-15 17-55-08.webm](https://github.com/user-attachments/assets/b892407d-5afd-4aa4-acaf-111cf82adbc9)

**Comment by SomeoneToIgnore** [comment] 2024-10-16 05:39
The video helped a lot, it's `fish` that you use!
Then it's a duplicate of https://github.com/zed-industries/zed/issues/15421

**Closed by SomeoneToIgnore** 2024-10-16 05:39 UTC
Labels: defect, triage, admin read
