### ISSUE TITLE
Adding the `Collapse Folders in Explorer` function button to collapse the project tree

### ISSUE THREAD

**Issue by mkdr4** [zed-industries/zed#9517] opened 2024-03-18 20:25 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="444" alt="image" src="https://github.com/zed-industries/zed/assets/100870357/c3f51332-a972-4b11-8845-8bd14bd306b5">

I saw a similar question in #6880, but only the key combination is discussed there, not the button and combination. I would like to see both functions, if I did not see the similarity of the discussion with the above issue, and it is there, then you can delete my question

**Comment by Moshyfawn** [comment] 2024-03-19 17:35
The original post you mentioned contains a screenshot of the UI part you're referring to in this feature request. I think we can close this thread in favour of the other one. Be sure to +👍 it and feel free to add any missing information.

Duplicate of
- #6880

**Closed by Moshyfawn** 2024-03-19 17:35 UTC
Labels: enhancement, triage, admin read
