### ISSUE TITLE
Nothing shown in WSL2.

### ISSUE THREAD

**Issue by baiguoname** [zed-industries/zed#15402] opened 2024-07-29 05:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I trying to use Zed in WSL2. I run `WAYLAND_DISPLAY='' zed --foreground`, and this is the reaction:
![image](https://github.com/user-attachments/assets/3112b7b9-2291-43f2-8cdb-7fb4602bd09c)
The output in the terminal:
```
root@USER-20240219YW:~# WAYLAND_DISPLAY='' zed --foreground
[2024-07-29T13:12:39+08:00 ERROR assistant] no worktrees when constructing ProjectLspAdapterDelegate
```

### Environment

My system infomation:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-07-29 06:55
Duplicate of https://github.com/zed-industries/zed/issues/14173

Something from the https://github.com/zed-industries/zed/issues?q=is%3Aissue+wsl2+is%3Aopen list might contain a recipe, as some people report it working.

**Closed by SomeoneToIgnore** 2024-07-29 06:55 UTC
Labels: defect, triage, admin read
