### ISSUE TITLE
Add config to exclude file scan using .gitignore

### ISSUE THREAD

**Issue by AlvaroParker** [zed-industries/zed#17359] opened 2024-09-04 16:46 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Add a feature that behaves like the `file_scan_exclusions` configuration but instead reads the `.gitignore` file for files to exclude. Ideally this can be configured using a boolean flag on the config file. Something like `"file_scan_exclusion_gitignore": true` (might be too long).

**Comment by notpeter** [comment] 2024-09-04 18:27
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/12341

**Closed by notpeter** 2024-09-04 18:27 UTC
Labels: enhancement, triage, admin read

**Comment by AlvaroParker** [comment] 2024-09-04 20:36
I don't think is a duplicate. In the referenced issue their request is focus on file search and gitignore. I'm requesting a feature to hide files from the project side panel

**Comment by notpeter** [comment] 2024-11-14 16:36
Thank you for reopening this under:
- https://github.com/zed-industries/zed/issues/17543
