### ISSUE TITLE
Color escape sequences dumped in the terminal

### ISSUE THREAD

**Issue by silvenon** [zed-industries/zed#10804] opened 2024-04-20 13:45 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It's probably the same thing described in https://github.com/zed-industries/zed/issues/9742#issuecomment-2066134611, but I wanted to create a more generic issue rather than upvote that one because the bug is not specific to Copilot CLI, but I'm not sure exactly where mine is coming from, so I'm just going to give you as many details as I can.

This is basically the kind of sequences that I'm often seeing, Zed outputs it as if I typed it in:

```
11;rgb:dcdc/d8d8/d8d8
```

I'm using a ZSH prompt [Pure](https://github.com/sindresorhus/pure), but it's [lefthook](https://github.com/evilmartians/lefthook) that I think is causing these for me, becuase it has a colorized output that Zed already seems to struggle with, although it only happens with the header:

```
^[]11;rgb:dcdc/d8d8/d8d8^[\╭──────────────────────────────────────╮
│ 🥊 lefthook v1.6.1  hook: pre-commit │
╰──────────────────────────────────────╯
```

And because I'm using Vim as my Git editor, it types those garbled characters into my commit message! 😕

And running `npx lefthook run pre-commit` makes the same thing happen:

1. output that starts with escape sequences
  ```
  ^[]11;rgb:dcdc/d8d8/d8d8^[\╭──────────────────────────────────────╮
  │ 🥊 lefthook v1.6.1  hook: pre-commit │
  ╰──────────────────────────────────────╯
  │  eslint (skip) no files for inspection
  │  prettier (skip) no files for inspection
  
    ────────────────────────────────────
  summary: (skip) empty
  ```
2. my terminal _input_ gets filled with those same sequences: `11;rgb:dcdc/d8d8/d8d8`

That's I guess the gist of it, I hope you manage to find the culprit 🤞 

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-04-20 16:36
Seems to be duplicate of https://github.com/zed-industries/zed/issues/8497, hence closing.

**Closed by SomeoneToIgnore** 2024-04-20 16:36 UTC
Labels: defect, triage, admin read
