### ISSUE TITLE
Text rendering broken for files after 16 million lines

### ISSUE THREAD

**Issue by haydn-jones** [zed-industries/zed#15316] opened 2024-07-27 00:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Text rendering breaks after ~16 million lines. To reproduce you can download this list of PubChem compound synonyms , unzip it, and scroll down https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/Extras/CID-Synonym-filtered.gz.

![image](https://github.com/user-attachments/assets/46ecb16e-c580-4c72-be9f-1b0e7de9a262)

### Environment

Zed: v0.147.0 (Zed Dev 6af385c09e0a1ca88f2a1ff47a2befb6751127c9)
OS: Linux X11 opensuse-tumbleweed 20240725
Memory: 62.7 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3090 || NVIDIA || 550.100

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-28 14:40
Duplicate of:
- https://github.com/zed-industries/zed/issues/5355

This is a known issue relating to the precision of floating point data types used.

Please 👍 upvote and subscribe to that issue to track it's progress.

**Closed by notpeter** 2024-07-28 14:40 UTC
Labels: defect, triage, admin read
