### ISSUE TITLE
[linux wayland] the ctrl-w  key command is too slow

### ISSUE THREAD

**Issue by l-7-l** [zed-industries/zed#14540] opened 2024-07-16 05:51 UTC
same here on linux.
editor: 
  version: Zed Preview 0.144.2
  code: 
![image](https://github.com/user-attachments/assets/6283f71d-8714-479a-8c13-c8a6aaf55b0a)

os:
```
                   -`                    l-7-l@bb8 
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: Vivobook_ASUSLaptop M7600QE_M7600QE 1.0 
               `+oooooo:                 Kernel: 6.9.7-zen1-1-zen 
               -+oooooo+:                Uptime: 12 hours, 57 mins 
             `/:-:++oooo+:               Packages: 1203 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 3840x2400 
          `/+++ooooooooooooo/`           DE: GNOME 46.3.1 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gjs 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 4.680GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
 `++:.                           `-/+/   GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
 .`                                 `/   Memory: 9315MiB / 15389MiB 

```
[录屏 2024-07-16 13-47-01.webm](https://github.com/user-attachments/assets/dbebb797-4909-44e5-a220-981fa4510f8b)

_Originally posted by @l-7-l in https://github.com/zed-industries/zed/discussions/8274#discussioncomment-10058202_ 

settings:
```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
    "base_keymap": "VSCode",
    "nightly": {
        "current_line_highlight": "all"
    },
    "vim_mode": true,
    "ui_font_size": 18,
    "buffer_font_size": 18,
    "buffer_font_family": "Comic Mono",
    "preferred_line_length": 80,
    "enable_language_server": true,
    "ensure_final_newline_on_save": true,
    "remove_trailing_whitespace_on_save": true,
    "default_dock_anchor": "right",
    "formatter": "language_server",
    "lsp": {
        "rust-analyzer": {
            "initialization_options": {
                "check": {
                    "command": "clippy" // rust-analyzer.check.command (default: "check")
                }
            }
        }
    },
    "inlay_hints": {
        "enabled": true
    },
    "prettier": {
        "allowed": true
    },
    "proxy": "http://localhost:2080",
    // LXGW WenKai Screen
    // "ui_font_family": "Comic Mono",
    // "editor.fontFamily": "'Comic Mono', 'LXGW WenKai Screen'",
    // "terminal.integrated.fontFamily": "ComicShannsMono Nerd Font Mono",
    "tab_size": 4,
    "vim": {
        "use_system_clipboard": "always"
    },
    "autosave": "on_focus_change",
    "theme": {
        "mode": "system",
        // "light": "Rosé Pine Dawn",
        "light": "One Light",
        "dark": "One Dark"
    },
}
```

**Comment by bersace** [comment] 2024-07-16 06:25
Do you have a shortcut base on `ctrl-w` ? Does Zed have a keymap viewer ?

**Comment by l-7-l** [comment] 2024-07-16 07:39
@bersace No, I don't have a ctrl-w based shortcut,  there also nothing in keymap.json

**Comment by CharlesChen0823** [comment] 2024-07-16 11:32
might `"vim_mode": "true"` cause this problem.

**Comment by apricotbucket28** [comment] 2024-07-16 16:17
Could this be related to https://github.com/zed-industries/zed/issues/11089#issuecomment-2212491830?

**Comment by l-7-l** [comment] 2024-07-17 17:35
> Could this be related to [#11089 (comment)](https://github.com/zed-industries/zed/issues/11089#issuecomment-2212491830)?
I'm not sure, but turning off vim-mode does make the problem go away. However, in the vim default keymap, the binding for ctrl-w is null. If the key combination matches None, it should stop searching and hand it over to the next plugin.


> might `"vim_mode": "true"` cause this problem.

yes

**Comment by l-7-l** [comment] 2024-07-17 17:39
> Could this be related to [#11089 (comment)](https://github.com/zed-industries/zed/issues/11089#issuecomment-2212491830)?

looks more like this [As far as I know if you configure <c-w> and <c-w> x it slows down <c-w>, usually a 1 second delay to determine what keystrokes you end up with](https://github.com/zed-industries/zed/issues/10457#issuecomment-2230132143)

**Comment by ralphpig** [comment] 2024-07-31 20:34
I just added a binding to close the pane on double tap `ctrl-w`. Good enough for me right now

```json
{
    "context": "Editor",
    "bindings": {
      "ctrl-w ctrl-w": "pane::CloseActiveItem"
    }
}
```

**Comment by asborisov** [comment] 2024-08-02 09:15
I can confirm the reason. I never use "cmd-w {something}" so I just dropped those from `keymap.json` and no closing is fast again

**Comment by ConradIrwin** [comment] 2024-12-07 00:01
Since this issue was filed we've updating things a bit. The default for `ctrl-w` on vim should do nothing now, and if you bind it in your keybindings it will do what you say.

Please let me know if there are still problems.

**Closed by ConradIrwin** 2024-12-07 00:01 UTC
Labels: bug, performance, linux, keymap / key binding, linux-wayland
