### ISSUE TITLE
Zed can not open the file without utf-8 encoding.

### ISSUE THREAD

**Issue by SeanPcWoo** [zed-industries/zed#11837] opened 2024-05-15 02:22 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

when i edit a asm file in my MacOS, I found the *.S file can not open. It show this msg. 
I change the file to utf-8, it can open successfully.
![image](https://github.com/zed-industries/zed/assets/20737902/43e00c23-1c08-4dd1-a403-d2a9ff2a14a1)

**Comment by SomeoneToIgnore** [comment] 2024-05-15 06:17
Duplicate of https://github.com/zed-industries/zed/issues/9833

**Closed by SomeoneToIgnore** 2024-05-15 06:17 UTC
Labels: enhancement, triage, admin read
