### ISSUE TITLE
Go to definition on a definition should find all references

### ISSUE THREAD

**Issue by marwan-at-work** [zed-industries/zed#7395] opened 2024-02-05 18:12 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

First of all, thank you for building Zed :) 

Feature request: if you cmd+click on a symbol, it takes you to where it's defined. It would be very useful if you cmd+clicked on the definition itself, it would then trigger a "find all references" call. 

This saves time in keeps users in context as they do not need to open the command palette and type find all references. Plus, going to a definition o na definition has no other use cases. 

For an example of how this works, you can try this out with VSCode+Go which already has this feature implemented.

Thanks!

**Comment by mrnugget** [comment] 2024-02-06 09:41
Thanks for the report! I'm closing this as a duplicate of this: https://github.com/zed-industries/zed/issues/5351

**Closed by mrnugget** 2024-02-06 09:41 UTC
Labels: enhancement, triage, admin read
