### ISSUE TITLE
Zed Login And Some Extensions Not Working

### ISSUE THREAD

**Issue by AlexCodesApps** [zed-industries/zed#12913] opened 2024-06-11 22:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have an issue where where trying to log in will go to the authentication page and back, but nothing happens. I've tried using the preview version of zed and that didn't work either. The website apparently works fine but the app just doesn't log in. To add to the frustration, I am suddenly unable to install extensions, although I still have all of my previous extensions. It seems like something is going wrong with networking but everything else runs fine, including the already mentioned website.
EDIT: 
Apparently not all extensions break, as the popular ones I tried still work, just not some like the BF extension I was trying to get. I am not sure why and my login is still not working.
There is a somewhat similar unanswered issue here: https://github.com/zed-industries/zed/issues/10381, but my circumstances are different enough that I think its worth an issue.

### Environment

Zed: v0.138.6 (Zed)
OS: macOS 12.7.4
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-06-11T18:04:25-04:00 [INFO] set status on client 170598: ConnectionError
2024-06-11T18:04:25-04:00 [ERROR] timed out trying to establish connection
2024-06-11T18:04:35-04:00 [INFO] set status on client 170598: Reauthenticating
2024-06-11T18:04:38-04:00 [INFO] set status on client 170598: Reconnecting
2024-06-11T18:04:58-04:00 [INFO] set status on client 170598: ConnectionError
2024-06-11T18:04:58-04:00 [ERROR] timed out trying to establish connection
2024-06-11T18:05:22-04:00 [INFO] installing extension brainfuck latest version
2024-06-11T18:05:23-04:00 [INFO] rebuilt extension index in 287.657888ms
2024-06-11T18:05:32-04:00 [INFO] rebuilt extension index in 735.048354ms
2024-06-11T18:06:49-04:00 [ERROR] crates/assistant/src/assistant_panel.rs:1424: credentials not found
2024-06-11T18:06:49-04:00 [ERROR] crates/assistant/src/assistant_panel.rs:1424: credentials not found
2024-06-11T18:06:53-04:00 [ERROR] crates/assistant/src/assistant_panel.rs:917: credentials not found
2024-06-11T18:06:58-04:00 [ERROR] crates/assistant/src/assistant_panel.rs:917: credentials not found
2024-06-11T18:07:25-04:00 [INFO] set status on client 170598: Reauthenticating
2024-06-11T18:07:29-04:00 [INFO] set status on client 170598: Reconnecting
2024-06-11T18:07:49-04:00 [INFO] set status on client 170598: ConnectionError
2024-06-11T18:07:49-04:00 [ERROR] TODO timed out trying to establish connection

**Comment by JosephTLyons** [comment] 2024-06-12 03:27
Hey @AlexCodesApps, I'm guessing nothing has changed on your end with network restrictions - something that might require a proxy?

**Comment by AlexCodesApps** [comment] 2024-06-12 14:07
> Hey @AlexCodesApps, I'm guessing nothing has changed on your end with network restrictions - something that might require a proxy?

Actually, using a VPN worked. I can log into my account. I tried the BF extension again, it didn't work, but the way it broke changed to be where I was unable to click the button again. Other extensions still work, including more niche ones, so Im beginning to think the BF extension is just broken.

**Comment by FatLittleFan** [comment] 2024-07-31 10:01
I successed sign in on Mac, I change some configation of my "clash X Pro" proxy.
I turned off the enhance mode, and select another country,
now zed can sign in, and update

**Comment by flexibility2** [comment] 2024-09-01 07:35
> I successed sign in on Mac, I change some configation of my "clash X Pro" proxy. I turned off the enhance mode, and select another country, now zed can sign in, and update

Hi, may I ask where is the enhance mode?

**Comment by notpeter** [comment] 2024-11-05 19:58
Closing as "unable to reproduce" as this appears to be a local network issue.

**Closed by notpeter** 2024-11-05 19:58 UTC
Labels: bug, collaboration, triage, admin read, network
