### ISSUE TITLE
Performance issue in Linux without anything or with anything. just taking ram more than JetBrains Editors 

### ISSUE THREAD

**Issue by a4arpon** [zed-industries/zed#11062] opened 2024-04-26 18:16 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/70208852/be607b9d-f2a0-4d9b-a35d-1d532bbee22d)
![image](https://github.com/zed-industries/zed/assets/70208852/56f0deaa-f79b-49c9-8382-8d7a07562268)

Zed is taking more than 2 GB with just a simple starter file of TypeScript Nestjs in my Linux. I thought zed is less memory hungry and greatest code editor of all time. But the problem is there it is taking too much memory. 

It is taking more than VSCode and Jetbrains Editors (WebStorm). 

There is no snippet support yet also. 

But the performance issue is too much.  

### Environment

OS: Linux Mint 21.3 x86_64
Host: Modern 14 B11MOU REV:1.0
Kernel: 5.15.0-105-generic
Packages: 2330 (dpkg)
Shell: bash 5.1.16
Resolution: 1600x900
DE: Xfce 4.18
WM: Xfwm4
Terminal: xfce4-terminal
CPU: 11th Gen Intel i3-1115G4 (4) @
GPU: Intel Device 9a78
Memory: 3397MiB / 15693MiB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed Nightly : 0.134.0

**Comment by DissolveDZ** [comment] 2024-04-26 19:07
Try building it yourself with the --release flag, works totally fine for me.
Comparing to other editors it actually runs better than most of them. I'm on Arch and X11.

**Comment by a4arpon** [comment] 2024-04-27 05:57
I have a deb version nightly and Release version which is built by my self with release tag. But both are same. they just took my 2gb of ram.

**Comment by balazsbotond** [comment] 2024-05-09 10:58
This is a possible duplicate of #10351 which seems to have been reported earlier.

**Closed** 2024-05-09 11:12 UTC
Labels: defect, performance, linux
