### ISSUE TITLE
cursor not on where click spot belongs to when zed got refcoused

### ISSUE THREAD

**Issue by mindon** [zed-industries/zed#4647] opened 2023-06-30 03:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

last cursor focus is on editor, if click terminal area to get zed app refocused to input commands, the focusedposition is still on editor in spite of the position of click cursor, it will mass the source code ...

expect not keep the focused cursor as it was, but focus on where the mouse cursor spot is.

### Environment

Zed: v0.92.3 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 06:43
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 06:43 UTC
Labels: defect, terminal
