### ISSUE TITLE
Add semantic auto-completion for plain-text and other languages without LSP/Tree-sitter

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#11103] opened 2024-04-27 17:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Please, add semantic auto-completion for plain-text and other languages without LSP/Tree-sitter. (Auto-completion using all the words available in current or all open buffers). This is quite popular feature and it is quite helpful when text editing:

<img width="457" alt="Снимок экрана 2024-04-27 в 20 58 13" src="https://github.com/zed-industries/zed/assets/230824/850cdbe4-ce59-4f7f-ab62-b97e8a3d2079">

**Comment by JosephTLyons** [comment] 2024-04-30 17:57
Hey @VKondakoff,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4957

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-30 17:57 UTC
Labels: enhancement, admin read, autocompletions
