### ISSUE TITLE
Horizontal scrolling in project panel ability

### ISSUE THREAD

**Issue by tausifcreates** [zed-industries/zed#7563] opened 2024-02-08 11:52 UTC
### Check for existing issues

- [x] Completed

### Describe the feature

As you can see from the clip below, Intellij based editors have this ability for horizontal scrolling and it saves you from resizing the panel every time when file name is long or file tree has many branches, so they get hidden. This feature thus would be super useful.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/93582436/2e8a81a7-588c-4078-8a90-b1665e475a35

**Comment by JosephTLyons** [comment] 2024-02-08 22:39
Hey @tausifcreates,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7001

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-08 22:39 UTC
Labels: enhancement, triage, admin read
