### ISSUE TITLE
Can't navigate using arrow keys within Outline Panel

### ISSUE THREAD

**Issue by lamualfa** [zed-industries/zed#20114] opened 2024-11-02 17:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

# Reproduce

1. Focus to **Outline Panel** using `Ctrl+Shift+B`
2. The cursor will focused on `Filter ...` input inside **Outline Panel**
3. Press `Arrow Up` or `Arrow Down` keys, the cursor will focused back to the **Editor**

_**Sorry, can't provide any screen record. Can't find any recording app (even the default ubuntu app) that works on Ubuntu 22.04 Wayland.**_

# Expectation

When pressing `Arrow Up` or `Arrow Down`, the cursor will move to the items within **Outline Panel**.

### Environment

Zed: v0.159.6 (Zed)
OS: Linux Wayland ubuntu 22.04
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Xe Graphics (TGL GT2) || Intel open-source Mesa driver || Mesa 23.2.1-1ubuntu3.1~22.04.2

**Comment by SomeoneToIgnore** [comment] 2024-11-02 18:22
Duplicate of https://github.com/zed-industries/zed/issues/20073, fixed in https://github.com/zed-industries/zed/pull/20083 and should be available in the next versions on Wednesday.

**Closed by SomeoneToIgnore** 2024-11-02 18:22 UTC
Labels: defect, triage, admin read
