### ISSUE TITLE
Anthropic integration doesn't work

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/zed#13932] opened 2024-07-08 14:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've added the configuration, generated and saved a new key. After sending the prompt nothing happens, It's just endlessly waiting for a response.

This was mentioned [here](https://github.com/zed-industries/zed/issues/13357#issuecomment-2207089976) but no issues were created specifically for this.

### Environment

Zed: v0.143.2 (Zed Preview)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="646" alt="image" src="https://github.com/zed-industries/zed/assets/15632814/9a3e7469-7727-448f-b9e8-723212e17558">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bitnom** [comment] 2024-07-08 19:58
A temporary workaround might be to run a [litellm proxy](https://docs.litellm.ai/docs/simple_proxy) and set it as the OpenAI API endpoint as mentioned [here](https://github.com/zed-industries/zed/issues/10716)

**Comment by jorikvanveen** [comment] 2024-07-08 20:36
I had this issue until I regenerated my key a few times and it magically started working

**Comment by stjepangolemac** [comment] 2024-07-09 06:42
I've tried multiple keys but never got it to work, now reverted to gpto.

**Comment by pbernery** [comment] 2024-07-09 10:14
Cannot make it work either, with the same behavior as described [here](https://github.com/zed-industries/zed/issues/13357#issuecomment-2207089976): I have no prompt of Zed to enter the API key (this should be the behavior of Zed as mentioned in [the documentation](https://zed.dev/docs/assistant-panel#using-claude-35-sonnet)).

Using version 0.142.6.

**Comment by notpeter** [comment] 2024-11-05 17:59
I'm going to close this as the Assistant configuration panel has been complete reworked since this issue was open.  If you are still having trouble configuring your API keys please open a clean issue with steps to reproduce. Thanks for reporting.

**Closed by notpeter** 2024-11-05 17:59 UTC
Labels: bug, triage, admin read, ai, assistant
