### ISSUE TITLE
Incorrect cursor scaling on wayland

### ISSUE THREAD

**Issue by Demolemon11** [zed-industries/zed#19938] opened 2024-10-30 04:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it
[VID_20241030_125001.webm](https://github.com/user-attachments/assets/224c86c8-a140-46ab-9f5f-94fef00d925b)

### Environment

![Screenshot from 2024-10-30 12-53-49](https://github.com/user-attachments/assets/15b61e83-59d3-4acb-9170-04efbdcbc005)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

It's normal & correct on X11

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-30 05:45
Duplicate of https://github.com/zed-industries/zed/issues/15788

**Closed by SomeoneToIgnore** 2024-10-30 05:45 UTC
Labels: defect, triage, admin read
