### ISSUE TITLE
`Go to Implementation` in Go should work when `Cmd-Click` on definition of interface method

### ISSUE THREAD

**Issue by mkdr4** [zed-industries/zed#8861] opened 2024-03-04 22:14 UTC
I am faced with the problem of the broken functionality of the transition to the implementation of the interface in the go code. I've tried a lot of ways to fix this. Starting from all possible actions with gopls, ending with the test of the previous version of Zed. Nothing helped.....
I liked your product and I would like to test it by switching to it.

I see the following errors in the logs "[WARN] Generic jsp request to go plus failed: no type definition for METHOD" and "[ERROR] rates/editor/src/editor.rs:7370: no type definition for METHOD".

**Comment by klausbreyer** [comment] 2024-03-11 09:05
Same here. Sadly, I cannot use Go to Definition for go projects. (And there is a lot I love about zed!)

**Comment by mrnugget** [comment] 2024-03-11 09:32
Hey! Can someone give me some steps to reproduce? Example file, example `go.mod`?

Go-to-def works for me in Go projects and for many others, so it's not broken generally, which means we need to figure out why exactly it's broken here.

**Comment by klausbreyer** [comment] 2024-03-11 09:59
Thorsten! (Are you the Thorsten that popped in during the Nathans Changelog Interview? :) )

Now it is suddenly working again.. strange. And I cannot get it back to not working anymore.

**Comment by mrnugget** [comment] 2024-03-11 11:01
> Thorsten! (Are you the Thorsten that popped in during the Nathans Changelog Interview? :) )

Yes!

If it stops working again, please try to find examples to reproduce.

**Comment by manuraj17** [comment] 2024-03-12 12:58
Does this mean this issue can be closed? Or shall we wait for couple of days to do it?

**Comment by klausbreyer** [comment] 2024-03-12 14:50
@manuraj17 I still have it, but I cannot reproduce it in a new project.. :/

**Comment by mkdr4** [comment] 2024-03-13 11:51
As I understand it, `Go to Definition` works to move from a call to an interface, and `Go to implementation` from the interface to the implementation.

We get such a scheme
<img width="575" alt="image" src="https://github.com/zed-industries/zed/assets/100870357/7b1cd66c-f4da-4e1d-a143-a35bfd2d8437">
_Developers, please confirm if this is the case._

I believe that `Go to implementation` should work using the combination CMD+LBM(Left button mouse), similar to `Go to Definition'.  I also think that transitions should be cyclical so that you can use this keyboard shortcut CMD+LBM to have such a circle 
Call-Interface-Func-Call's-Interface...

In vscode, the circle works like this
<img width="503" alt="image" src="https://github.com/zed-industries/zed/assets/100870357/417c148c-2890-4a05-a256-211572fbd386">
, it is both convenient and not, it seems to me that the option I described below is more convenient
<img width="517" alt="image" src="https://github.com/zed-industries/zed/assets/100870357/a88d982d-6633-439e-ae19-9ba49f96ca78">
how do you look at such an implementation?

**Comment by mrnugget** [comment] 2024-03-14 10:47
I see. So this is about interfaces and jumping between the definition and the implementation. I updated the title.

I think this is very related to what @SomeoneToIgnore implemented yesterday to fix https://github.com/zed-industries/zed/issues/5351 here: https://github.com/zed-industries/zed/pull/9243

The difference is that this will fall back to `Find all references` and what you want is `Find all implementations`, right?

So this code here would need to do different things depending on whether it's on top of an interface or not. 

https://github.com/zed-industries/zed/pull/9243/files#diff-10065bb5e48ea679a7ebc25f37a2c0cb0d3b7e0e9717d744b15436e737076b2bR155-R159

**Comment by klausbreyer** [comment] 2024-03-14 12:36
https://github.com/zed-industries/zed/assets/32771/912140cb-4022-4a67-a3a6-f70695c9cc3e

Just to let you know, I just created a quick screen capture. (0.117.1) 
It is about cmd + left click on a type definition. It does not jump. 

But it's really hard to reproduce. It is not about the codebase but rather the state that the editor is in. Any debug logs I can provide?

**Comment by klausbreyer** [comment] 2024-03-14 12:42
For what it's worth, I tried to strip my project from any non-essential files, and (currently) it is reproducible. 

https://github.com/klausbreyer/zed-go-api-test

Context: It is a mono-repo with a react app, where the go project is in a subfolder. 
To reproduce, open the root of the repository in zed.

**Comment by mrnugget** [comment] 2024-03-14 16:29
@klausbreyer yeah, you need to use `go.work` files: https://github.com/zed-industries/zed/issues/8460#issuecomment-1971216276

**Comment by klausbreyer** [comment] 2024-03-15 07:15
Thanks for the hint, @mrnugget ! But I hope this is just a workaround and eventually there will be universal support?

**Comment by mrnugget** [comment] 2024-03-15 08:56
I'm not sure. It seems like `gopls` said they won't support it, so that means we'd have to find workarounds and those all seems pretty hacky: we'd have to find `go.mod` files (what if there isn't one?), we'd have to decide what to do with multiple` go.mod` files in a single project, manage multiple `gopls` processes, etc.

**Comment by klausbreyer** [comment] 2024-03-15 09:45
I see .. when gpls doesn't support it; then it probably isn't worth doing a dirty hack.

**Comment by nidhey27** [comment] 2024-03-22 04:49
https://github.com/zed-industries/zed/assets/46122307/f5a96c8a-fb9e-4557-b6bc-2aa27145ba4e

`Go to Definition` i.e `cmd + left click` is also not working for tsx / jsx / js / ts files as well. I think this is the case for most of the languages, not just go lang. 

I'm currently on Zed Version: `Zed 0.127.3 – /Applications/Zed.app`

**Comment by Czechh** [comment] 2024-03-22 12:45
I'm having the same issue, just tried https://github.com/zed-industries/zed/issues/8460#issuecomment-1971216276 but it still won't work. Even after opening just the Go subfolder in Zed. It's been broken for a month or so, previously it was working even in with the whole monorepo open and without the `go work init` + `go use..`

I'm currently running Zed 0.127.3

**Comment by mrnugget** [comment] 2024-03-22 14:13
It works for me on latest stable.



https://github.com/zed-industries/zed/assets/1185253/18e163a7-b3be-4125-9fe6-1c10482490ca


@nidhey27 your issue is not about Go and not about `Go to implementation` — correct? Can you create a separate ticket and put in steps to reproduce and language server log output? (`debug: open language server logs`)

@Czechh Can you also create a new issue, also with the log output, and put information in about how your Go is installed? Also what `which gopls` returns in your project's folder.

**Comment by Czechh** [comment] 2024-03-22 19:06
I figured it out, thanks for the response.

For future reference of people hitting this issue, my problem was that I had `go` installed via homebrew, and which go showed the homebrew path. While gopls was pointing to the user path.

I fixed immediately by brew install gopls. But, I'm recommending this, it might better to stay away from brew for this and keep native install for go and gopls.

**Comment by Cufee** [comment] 2024-04-18 01:20
@Czechh I also ran into this issue while using `gobrew` to manage Go versions. Once I installed `gopls` through `brew` as well, this was resolved. Thanks!

**Comment by notpeter** [comment] 2024-06-20 14:21
I'm going to close this because I believe the underlying cause of the original issue (gopls limitation) is understood. Additionally, an unrelated cause of similar behavior (mixed brew/gobrew installation of go/gopls) was identified (thanks @Czechh).

If this is incorrect and there's still outstanding issue we can open a new issue with a clean description that explains the issue and references the discussion here if appropriate.

Thanks all!

**Closed by notpeter** 2024-06-20 14:21 UTC
Labels: defect, needs info / awaiting response, language, go, language server
