### ISSUE TITLE
Zed not open with gui on ubuntu20.04

### ISSUE THREAD

**Issue by fengtuo58** [zed-industries/zed#15851] opened 2024-08-06 12:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

curl -f https://zed.dev/install.sh | sh
zed --foregroud

### Environment

Ubuntu 20.04

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

~$ zed --foreground [2024-08-06T20:27:24+08:00 ERROR copilot] error fetching latest release
 0s2 WS nap emplates ideos ed
 Caused by: 0: failed to connect to the server 1: [35] SSL connect error

</pre></details>

**Comment by fengtuo58** [comment] 2024-08-09 15:58
😥

**Comment by anrub** [comment] 2024-08-09 16:57
There are some duplicate issues around this, it looks like it has something todo with some vulkan graphics driver or so. On a fresh 24.04 install in virtualbox it starts. https://github.com/zed-industries/zed/issues/14204

**Comment by notpeter** [comment] 2024-08-09 20:48
I believe there are existing issues covering problems with Ubuntu 20.04 

Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/14237
- https://github.com/zed-industries/zed/issues/15468
- https://github.com/zed-industries/zed/issues/14204

**Closed** 2024-08-21 19:24 UTC
Labels: duplicate

**Comment by CoderParth** [comment] 2024-12-28 11:44
I had the same problem on Ubuntu.
For those who might still be having similar issues, 
the solution that worked for me was manually switching to NVIDIA GPU, and then running Ubuntu on Wayland.

`sudo prime-select nvidia`

Also please try 

`vkcube --gpu_number 0 `
and
`vkcube --gpu_number 1`

In case everything is configured properly, both the commands should open up a window with a rotating cube on the display. One of the command selects your integrated internal gpu, while the other one selects the external gpu.
