### ISSUE TITLE
asciidoc support

### ISSUE THREAD

**Issue by gdamore** [zed-industries/zed#10023] opened 2024-04-01 00:34 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

This is probably not easy, because nobody has yet put together a tree-sitter grammar for asciidoc, but its a fairly common doc format and it would be nice if it had support for highlighting and even preview support.

**Comment by bennetbo** [comment] 2024-04-01 08:31
Hey, I think that is planned as an extension, see https://github.com/zed-industries/extensions/issues/168

**Comment by Moshyfawn** [comment] 2024-04-01 12:47
> Hey, I think that is planned as an extension, see https://github.com/zed-industries/extensions/issues/168

The reason I left it open instead of closing it in favour of zed-industries/extensions#168 is the fact that the OP also mentioned preview support, which is currently outside the scope of our extensions infra. I'm happy to close it if syntax highlighting satisfies the request.

**Comment by Moshyfawn** [comment] 2024-04-01 15:58
Let's do it this way: I'm going to close this request in favour of the existing syntax highlighting extension request. Without additional extensions infra work, the preview part of the request can't be worked on, so I'm going to split it off and create it as an additional extensions API specific request instead.

Duplicate of
- zed-industries/extensions#168

**Closed by Moshyfawn** 2024-04-01 15:58 UTC
Labels: enhancement, potential extension, unsupported language
