### ISSUE TITLE
The commands in the pop-up box of the AI panel overlap each other.

### ISSUE THREAD

**Issue by mrzzmrzz** [zed-industries/zed#20714] opened 2024-11-15 08:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="294" alt="image" src="https://github.com/user-attachments/assets/ab4d1a29-1f95-4180-9a5c-6d28c3b3f1c1">

The commands in the pop-up box of the AI panel overlap each other.

### Environment

Zed Preview 0.162.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-11-15 18:29
Duplicate of:
- https://github.com/zed-industries/zed/issues/20678

**Closed by notpeter** 2024-11-15 18:29 UTC
Labels: bug, triage, admin read
