### ISSUE TITLE
ctrl + backspace from start of line removes line and previous word group

### ISSUE THREAD

**Issue by JGALWP** [zed-industries/zed#14325] opened 2024-07-12 12:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hitting ctrl + backspace from start of line removes the current line and previous word group.

Behavior on other IDEs is just to delete the empty line and put the cursor to the end of the line above without deleting the word group there.

Adding a test case like `assert(" abˇ\nˇ", cx);` to test_previous_word_start produces a failure.

https://github.com/zed-industries/zed/blob/ea26a01f5f2315b5770cd9dc475e843ee8ebc1b6/crates/editor/src/movement.rs#L271

Printing out left right boundaries it seems like the cursor jumps back one, in the case of deleting the start of a line, right becomes the new line character rather than left.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 62.7 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-12 18:47
duplicate of:
- https://github.com/zed-industries/zed/issues/5285

Please 👍 vote and subscribe over there to track progress.

**Closed by notpeter** 2024-07-12 18:47 UTC
Labels: defect, triage, admin read
