### ISSUE TITLE
Colored Icons / Icon Images

### ISSUE THREAD

**Issue by SturdyFool10** [zed-industries/zed#21086] opened 2024-11-22 23:21 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Adding colored icons would be a fantastic small enhancement. Currently, in the Project Panel, the entire line's appearance is determined by the GitHub status, while the tab row remains gray all the time. A great feature would be to allow users to enable icon colors based on the file type or language symbol.

Even better, users could replace the default symbol with the language’s icon, either as a vector graphic (SVG) or, if vector graphics aren’t supported, with a PNG for each file type. Language extensions could also define their own icons, either as grayscale images that map specific grayscale tones to colors, or as pre-colored icons.

Themes could set these colors independently while giving users control over the priority. Users could choose between the default colors (provided for built-in languages or included with extensions) and theme-specific colors, which would reuse the same SVG/PNG unless the theme supplied its own custom icons. This would add flexibility and customization while enhancing visual clarity and appeal.

### Environment

Zed: v0.164.0 (Zed Dev ebaa270bafbd8b4ca504436c5178c68dc81618e7)
OS: Windows 10.0.26120
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3080 || NVIDIA || 566.03

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/6e0c102e-e361-429e-82cd-95addb75fcac)

**Comment by SturdyFool10** [comment] 2024-11-22 23:24
small detail, but I noted the addition of the little dots next to the icon to show where in the tree there are warnings or errors, and would love if this other small detail could be added as well

**Comment by SomeoneToIgnore** [comment] 2024-11-22 23:27
Duplicate of https://github.com/zed-industries/zed/issues/4609 , superceeded by https://github.com/zed-industries/zed/issues/8843

**Closed by SomeoneToIgnore** 2024-11-22 23:27 UTC
Labels: enhancement, triage, admin read
