### ISSUE TITLE
Offer Extension Filter

### ISSUE THREAD

**Issue by nerdalytics** [zed-industries/zed#12576] opened 2024-06-02 08:52 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to request a feature. It would be beneficial if Zed provided a filter when browsing extensions. Currently, Zed displays both themes and extensions together, making it difficult to distinguish between them. Currently, identifying whether an item is an extension or a theme requires the author to include the word "Extension" or "Theme" in the short description shown in the extensions list – which requires discipline, and yet consumes a lot of time scrolling through the ever growing list of extensions/themes.

**Comment by maxdeviant** [comment] 2024-06-03 16:33
I think this is a dupe of #8848.

**Comment by nerdalytics** [comment] 2024-06-03 16:39
Yeah it is. I was not browsing all issues the search has surfaced.

**Closed** 2024-06-03 16:39 UTC
Labels: enhancement, triage, admin read
