### ISSUE TITLE
Manual Supermaven completions don't work when `"show_inline_completions": false`

### ISSUE THREAD

**Issue by BasilYes** [zed-industries/zed#16027] opened 2024-08-09 12:00 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I want to use supermaven manually by set editor::ShowInlineCompletion hotkey but, 
when I added `"show_inline_completions": false` to settings file I get infinite supermaven initialization
![image](https://github.com/user-attachments/assets/f2ba9190-fcf9-4262-b504-b2a2e11ca42b)
When I comment this option, supermaven work as well

### Environment

Zed: v0.146.4 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 31.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1050 Ti || NVIDIA || 555.58.02

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16560759/Zed.log)

**Comment by SomeoneToIgnore** [comment] 2024-08-11 20:37
Duplicate of https://github.com/zed-industries/zed/issues/8637 (that one mentions Copilot, but Zed now uses generic names for those actions, and those do not work for both Supermaven and Copilot)

**Closed by SomeoneToIgnore** 2024-08-11 20:37 UTC
Labels: defect, ai, inline completion, supermaven
