### ISSUE TITLE
Extensions search should index description (not just title)

### ISSUE THREAD

**Issue by notpeter** [zed-industries/zed#13312] opened 2024-06-20 12:55 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

The extensions panel only searches the title of the extensions.

It should also search the description.  Example: Searching 'vlang' should return this as a result.

<img width="510" alt="image" src="https://github.com/zed-industries/zed/assets/145113/e7ae0d87-f60b-4e58-9f5e-422ab69fd205">

Originally observed by user @mike-ward here: https://github.com/zed-industries/zed/issues/13278

**Comment by someone13574** [comment] 2024-06-20 14:47
Duplicate of https://github.com/zed-industries/zed/issues/10340

**Closed** 2024-06-20 17:53 UTC
Labels: enhancement, extension infrastructure, duplicate
