### ISSUE TITLE
Scrollbar covers text

### ISSUE THREAD

**Issue by pointlessone** [zed-industries/zed#7153] opened 2024-01-31 15:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Scrollbar covers text. This is especially problematic with git gutter enabled, which is solid colour.

<img width="116" alt="image" src="https://github.com/zed-industries/zed/assets/7405/dbea8d67-9242-45c1-b319-f846e4b77a55">

At the bottom of the screenshot is a part of a long green section of scrollbar. It completely covers the last character of text and the cursor.

### Environment

Zed: v0.119.21 (Zed)
OS: macOS 14.2.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

It's be nice to have some space beyond the end of text on the right. Say, 5-10 characters worth of space. This would also help seeing whether Copilot suggests anything.

**Comment by JosephTLyons** [comment] 2024-02-02 02:14
Hey @pointlessone,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7098

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-02 02:14 UTC
Labels: defect, scrollbar
