### ISSUE TITLE
feat: add tags metadata for extensions to make it easier to search

### ISSUE THREAD

**Issue by ryuukk** [zed-industries/zed#14440] opened 2024-07-14 10:54 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Let's take https://github.com/staysail/zed-d as an example

It's called `D`, if you type `D` in the search box you get:

![image](https://github.com/user-attachments/assets/68be3264-a8a9-42a1-9821-b79f01d982ec)

not what you want..

I suggest having a way to include tags in extensions, so one can type `dlang` or `d language`

Alternatively, make it easier to search for 1 letter languages

**Comment by notpeter** [comment] 2024-07-16 19:29
I'm going to close this as a duplicate of: 
- #9066 

We haven't made firm decisions about the design of this. Feel free to 👍 vote, subscribe or add to the discussion on that issue.  Thanks for reporting!

**Closed** 2024-09-10 20:30 UTC
Labels: enhancement, extension infrastructure, duplicate
