### ISSUE TITLE
Tests in TS always try Jest even if Bun is available 

### ISSUE THREAD

**Issue by versecafe** [zed-industries/zed#14840] opened 2024-07-19 20:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The test run arrow in TS/JS is supposed to use bun test or npx jest based off whichever is available but currently always uses Jest which prevents it from being used in a bun project without installing Jest and reconfiguring imports

### Environment

Zed: v0.146.0 (Zed Nightly b22718e64354457ff2572155d5a85da6e27fcfa7)
OS: macOS 15.0.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

No need to show this self explanatory

**Comment by polRk** [comment] 2024-07-23 07:32
+1

**Comment by notpeter** [comment] 2024-07-25 15:35
Duplicate of:
- https://github.com/zed-industries/zed/issues/12828

**Closed by notpeter** 2024-07-25 15:35 UTC
Labels: defect, triage, admin read
