### ISSUE TITLE
Saving SCSS Files Adds .s to Filename

### ISSUE THREAD

**Issue by spidercam** [zed-industries/zed#18229] opened 2024-09-23 14:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Create a new file: File > New
2. Then File > Save As…
3. For the filename, add the `.scss` extension to the file.

When following these steps, the filename extension saves as `[filename].scss.s` instead of `[filename].scss`.

Video Example:

https://github.com/user-attachments/assets/3350a713-5ee7-4939-b241-1386ab789801

### Environment

Zed: v0.153.6 (Zed)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-09-23 15:19
Duplicate of https://github.com/zed-industries/zed/issues/16969 and seems to be caused by macOS Sequoia

**Closed by SomeoneToIgnore** 2024-09-23 15:19 UTC
Labels: defect, triage, admin read
