### ISSUE TITLE
no autocomplete, no hint, Jump to definition not working for repo https://github.com/huggingface/candle

### ISSUE THREAD

**Issue by jk2K** [zed-industries/zed#17534] opened 2024-09-07 12:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. git clone https://github.com/huggingface/candle
2. open candle repo with zed

### Environment

Zed: v0.151.2 (Zed)
OS: macOS 13.5.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

[Zed.log.zip](https://github.com/user-attachments/files/16918208/Zed.log.zip)

**Comment by jk2K** [comment] 2024-09-07 12:42
my settings.json

```
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run `zed: open default settings` from the
// command palette
{
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "theme": {
    "mode": "system",
    "light": "Solarized Dark",
    "dark": "One Dark"
  },
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        // get more cargo-less diagnostics from rust-analyzer,
        // which might include false-positives (those can be turned off by their names)
        "diagnostics": {
          "experimental": {
            "enable": true
          }
        },
        // To disable the checking entirely
        // (ignores all cargo and check settings below)
        "checkOnSave": false,
        // To check the `lib` target only.
        "cargo": {
          "allTargets": false
        },
        // Use `-p` instead of `--workspace` for cargo check
        "check": {
          "workspace": false
        }
      }
    }
  }
}
```

**Comment by everdrone** [comment] 2024-09-08 12:14
I'm also experiencing issues with rust analyzer on rust codebases

**Comment by SomeoneToIgnore** [comment] 2024-09-08 14:08
That looks like a duplicate of https://github.com/zed-industries/zed/issues/17376 and so far the workaround is to downgrade to an older version.

**Closed** 2024-10-15 18:36 UTC
Labels: duplicate
