### ISSUE TITLE
Git gutter doesn't work unless the project is opened at the repo root

### ISSUE THREAD

**Issue by hiranya911** [zed-industries/zed#10743] opened 2024-04-18 21:31 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm working on a monorepo with many projects in it. Something like:
```
repo-root
    |---- server
    |---- client
```

If I open one of those sub directories in Zed (e.g. `zed repo-root/client`), Git gutter won't work. If I open the project at the root (`zed repo-root`), it works as usual.

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 13.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment] 2024-04-19 06:25
Hey @hiranya911,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5161

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-19 06:25 UTC
Labels: defect, git
