### ISSUE TITLE
[Windows] `Err` value: NotSupportedError" at crates\gpui\src\platform\windows\window.rs:111:14

### ISSUE THREAD

**Issue by aryanjha256** [zed-industries/zed#11398] opened 2024-05-04 21:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am trying to build **Zed** on windows and got these errors: 

PS C:\Users\[User]\Desktop\zed> cargo run

 Running `target\debug\Zed.exe`
[2024-05-05T03:02:40+05:30 ERROR util] crates\settings\src\settings_file.rs:76: EOF while parsing a value at line 1 column 0
[2024-05-05T03:02:42+05:30 ERROR util] crates\zed\src\zed.rs:668: EOF while parsing a value at line 1 column 0
[2024-05-05T03:02:42+05:30 ERROR auto_update] auto-update failed: error:auto-update not supported for OS "windows"
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: NotSupportedError" at crates\gpui\src\platform\windows\window.rs:111:14
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\dbghelp.rs:98
   1: backtrace::backtrace::trace_unsynchronized<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<backtrace::capture::impl$1::create::closure_env$0>
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:176
   4: backtrace::capture::Backtrace::new
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\backtrace-0.3.69\src\capture.rs:140
   5: Zed::reliability::init_panic_hook::closure$0
             at crates\zed\src\reliability.rs:83
   6: alloc::boxed::impl$49::call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\alloc\src\boxed.rs:2029
   7: std::panicking::rust_panic_with_hook
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:785
   8: std::panicking::begin_panic_handler::closure$0
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:659
   9: std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:171
  10: std::panicking::begin_panic_handler
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:647
  11: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\panicking.rs:72
  12: core::result::unwrap_failed
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\result.rs:1649
  13: core::result::Result::unwrap
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\core\src\result.rs:1073
  14: gpui::platform::windows::window::WindowsWindowInner::new
             at crates\gpui\src\platform\windows\window.rs:101
  15: gpui::platform::windows::window::wnd_proc
             at crates\gpui\src\platform\windows\window.rs:1794
  16: CallWindowProcW
  17: DispatchMessageW
  18: InitDManipHook
  19: KiUserCallbackDispatcher
  20: NtUserCreateWindowEx
  21: CreateWindowExW
  22: CreateWindowExW
  23: CreateWindowExW
  24: windows::Win32::UI::WindowsAndMessaging::CreateWindowExW<windows_core::strings::pcwstr::PCWSTR,ref$<windows_core::strings::hstring::HSTRING>,windows::Win32::Foundation::HWND,windows::Win32::UI::WindowsAndMessaging::HMENU,windows::Win32::Foundation::HMODUL
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.53.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:540
  25: gpui::platform::windows::window::WindowsWindow::new
             at crates\gpui\src\platform\windows\window.rs:1286
  26: gpui::platform::windows::platform::impl$3::open_window
             at crates\gpui\src\platform\windows\platform.rs:373
  27: gpui::window::Window::new
             at crates\gpui\src\window.rs:608
  28: gpui::app::impl$4::open_window::closure$0<workspace::Workspace,workspace::impl$13::new_local::closure$0::async_block$0::closure_env$8>
             at crates\gpui\src\app.rs:498
  29: gpui::app::AppContext::update<gpui::window::WindowHandle<workspace::Workspace>,gpui::app::impl$4::open_window::closure_env$0<workspace::Workspace,workspace::impl$13::new_local::closure$0::async_block$0::closure_env$8> >
             at crates\gpui\src\app.rs:363
  30: gpui::app::AppContext::open_window<workspace::Workspace,workspace::impl$13::new_local::closure$0::async_block$0::closure_env$8>
             at crates\gpui\src\app.rs:495
  31: gpui::app::async_context::AsyncAppContext::open_window<workspace::Workspace,workspace::impl$13::new_local::closure$0::async_block$0::closure_env$8>
             at crates\gpui\src\app\async_context.rs:157
  32: workspace::impl$13::new_local::closure$0::async_block$0
             at crates\workspace\src\workspace.rs:977
  33: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<gpui::window::WindowHandle<workspace::Workspace>,alloc::vec::Vec<enum2$<core::option::Option<enum2$<core::result::Resul
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\core\src\future\future.rs:124
  34: async_task::runnable::impl$6::spawn_local::impl$1::poll<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<gpui::window::WindowHandle<workspace::Workspace>,alloc::vec::Vec<enum2$<core::optio
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:455
  35: async_task::raw::RawTask::run<async_task::runnable::impl$6::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<gpui::window::WindowHandle<workspace::Workspace>,alloc::ve
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\raw.rs:557
  36: async_task::runnable::Runnable::run<tuple$<> >
             at C:\Users\[User]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.0\src\runnable.rs:781
  37: gpui::platform::windows::platform::WindowsPlatformInner::run_foreground_tasks
             at crates\gpui\src\platform\windows\platform.rs:85
  38: gpui::platform::windows::platform::WindowsPlatform::run_foreground_tasks
             at crates\gpui\src\platform\windows\platform.rs:194
  39: gpui::platform::windows::platform::impl$3::run
             at crates\gpui\src\platform\windows\platform.rs:248
  40: gpui::app::App::run<Zed::init_ui::closure_env$3>
             at crates\gpui\src\app.rs:142
  41: Zed::init_ui
             at crates\zed\src\main.rs:233
  42: Zed::main
             at crates\zed\src\main.rs:445
  43: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\core\src\ops\function.rs:250
  44: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\sys_common\backtrace.rs:155
  45: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\sys_common\backtrace.rs:155
  46: std::rt::lang_start::closure$0<tuple$<> >
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\rt.rs:166
  47: std::rt::lang_start_internal::closure$2
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
  48: std::panicking::try::do_call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:554
  49: std::panicking::try
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:518
  50: std::panic::catch_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panic.rs:142
  51: std::rt::lang_start_internal
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
  52: std::rt::lang_start<tuple$<> >
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\library\std\src\rt.rs:165
  53: main
  54: invoke_main
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  55: __scrt_common_main_seh
             at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  56: BaseThreadInitThunk
  57: RtlUserThreadStart

error: process didn't exit successfully: `target\debug\Zed.exe` (exit code: 0xffffffff)

### Environment

[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Pro	
Version	10.0.19045 Build 19045	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	DESKTOP-SAD8LUP	
System Manufacturer	Dell Inc.	
System Model	Latitude 5480	
System Type	x64-based PC	
System SKU	....
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)	
BIOS Version/Date	Dell Inc. 1.35.0, 29-01-2024	
SMBIOS Version	3.0	
Embedded Controller Version	255.255	
BIOS Mode	UEFI	
BaseBoard Manufacturer	Dell Inc.	
BaseBoard Product	0NDFXD	
BaseBoard Version	A00	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\Windows	
System Directory	C:\Windows\system32	
Boot Device	\Device\HarddiskVolume1	
Locale	United States	
Hardware Abstraction Layer	Version = "10.0.19041.3636"	
User Name	....
Time Zone	India Standard Time	
Installed Physical Memory (RAM)	16.0 GB	
Total Physical Memory	15.9 GB	
Available Physical Memory	8.42 GB	
Total Virtual Memory	18.3 GB	
Available Virtual Memory	8.88 GB	
Page File Space	2.38 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	Off	
Virtualization-based security	Running	
Virtualization-based security Required Security Properties		
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, Mode Based Execution Control	
Virtualization-based security Services Configured		
Virtualization-based security Services Running		
Device Encryption Support	Elevation Required to View	
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by ndunnett** [comment] 2024-05-05 08:02
I'm having the same issue just trying to run the GPUI hello world. I've added the following `build.rs` similar to what is in the Zed source:

```
fn main() {
    if cfg!(target_os = "windows") && cfg!(target_env = "msvc") {
        println!("cargo:rustc-link-arg=/stack:{}", 8 * 1024 * 1024);
    }
}
```

Here is the full stack trace from running `cargo run`:

```
thread 'main' panicked at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\platform\windows\window.rs:111:14:
called `Result::unwrap()` on an `Err` value: NotSupportedError
stack backtrace:
   0:     0x7ff690f5e3fa - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:99
   1:     0x7ff690f5e3fa - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff690f5e3fa - std::sys_common::backtrace::_print_fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ff690f5e3fa - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ff690f81abb - core::fmt::rt::Argument::fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt\rt.rs:142
   5:     0x7ff690f81abb - core::fmt::write
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt\mod.rs:1153
   6:     0x7ff690f5a0b1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\io\mod.rs:1843
   7:     0x7ff690f5e1e6 - std::sys_common::backtrace::print
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ff690f6060f - std::panicking::default_hook::closure$1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:272
   9:     0x7ff690f602a7 - std::panicking::default_hook
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:292
  10:     0x7ff690f60b4d - std::panicking::rust_panic_with_hook
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:779
  11:     0x7ff690f60a09 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:657
  12:     0x7ff690f5ed09 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common\backtrace.rs:171
  13:     0x7ff690f606c6 - std::panicking::begin_panic_handler
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
  14:     0x7ff691013177 - core::panicking::panic_fmt
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
  15:     0x7ff691013753 - core::result::unwrap_failed
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\result.rs:1654
  16:     0x7ff6903d93bd - enum2$<core::result::Result<blade_graphics::hal::Context,blade_graphics::NotSupportedError> >::unwrap
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\result.rs:1077
  17:     0x7ff6903d93bd - gpui::platform::windows::window::WindowsWindowInner::new
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\platform\windows\window.rs:101
  18:     0x7ff6903e6c98 - gpui::platform::windows::window::wnd_proc
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\platform\windows\window.rs:1794
  19:     0x7ffb802989a1 - DispatchMessageW
  20:     0x7ffb8029865c - DispatchMessageW
  21:     0x7ffb802a5d9c - CallNextHookEx
  22:     0x7ffb80f53994 - KiUserCallbackDispatcher
  23:     0x7ffb7e8f2294 - NtUserCreateWindowEx
  24:     0x7ffb8028f760 - CreateWindowExW
  25:     0x7ffb8028f47c - CreateWindowExW
  26:     0x7ffb8028f2c2 - CreateWindowExW
  27:     0x7ff6903c26a5 - windows::Win32::UI::WindowsAndMessaging::CreateWindowExW<windows_core::strings::pcwstr::PCWSTR,ref$<windows_core::strings::hstring::HSTRING>,windows::Win32::Foundation::HWND,windows::Win32::UI::WindowsAndMessaging::HMENU,windows::Win32::Foundation::HMODUL
                               at C:\Users\<redacted>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.53.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:540
  28:     0x7ff6903e2416 - gpui::platform::windows::window::WindowsWindow::new
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\platform\windows\window.rs:1286
  29:     0x7ff6903d20fa - gpui::platform::windows::platform::impl$3::open_window
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\platform\windows\platform.rs:373
  30:     0x7ff69031ae39 - gpui::window::Window::new
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\window.rs:608
  31:     0x7ff6902262bd - gpui::app::impl$4::open_window::closure$0<gpui::HelloWorld,gpui::main::closure$0::closure_env$0>
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\app.rs:498
  32:     0x7ff6902265ed - gpui::app::AppContext::update<gpui::window::WindowHandle<gpui::HelloWorld>,gpui::app::impl$4::open_window::closure_env$0<gpui::HelloWorld,gpui::main::closure$0::closure_env$0> >
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\app.rs:363
  33:     0x7ff69022610f - gpui::app::AppContext::open_window<gpui::HelloWorld,gpui::main::closure$0::closure_env$0>
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\app.rs:495
  34:     0x7ff690227d76 - gpui::main::closure$0
                               at C:\Users\<redacted>\source\gpui_project\src\main.rs:29
  35:     0x7ff690226a31 - gpui::app::impl$3::run::closure$0<gpui::main::closure_env$0>
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\app.rs:144
  36:     0x7ff690221a61 - core::ops::function::FnOnce::call_once<gpui::app::impl$3::run::closure_env$0<gpui::main::closure_env$0>,tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
  37:     0x7ff690412b40 - alloc::boxed::impl$47::call_once<tuple$<>,dyn$<core::ops::function::FnOnce<tuple$<>,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\alloc\src\boxed.rs:2020
  38:     0x7ff6903d10e6 - gpui::platform::windows::platform::impl$3::run
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\platform\windows\platform.rs:225
  39:     0x7ff690226874 - gpui::app::App::run<gpui::main::closure_env$0>
                               at C:\Users\<redacted>\.cargo\git\checkouts\zed-23861290b5d2093f\89039f6\crates\gpui\src\app.rs:142
  40:     0x7ff690222eb1 - gpui::main
                               at C:\Users\<redacted>\source\gpui_project\src\main.rs:27
  41:     0x7ff690221adb - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
  42:     0x7ff690227e0e - core::hint::black_box
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\hint.rs:337
  43:     0x7ff690227e0e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\sys_common\backtrace.rs:155
  44:     0x7ff6902260a1 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\rt.rs:166
  45:     0x7ff690f54f42 - std::rt::lang_start_internal
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\rt.rs:148
  46:     0x7ff69022607a - std::rt::lang_start<tuple$<> >
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\rt.rs:165
  47:     0x7ff690222ed9 - main
  48:     0x7ff691010d60 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  49:     0x7ff691010d60 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  50:     0x7ffb7f92257d - BaseThreadInitThunk
  51:     0x7ffb80f0aa48 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\gpui.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

The same code runs fine on macOS. I'm on Windows 11 with with the following installed:
- Windows 11 SDK (10.0.22000.832)
- MSVC v143 x64/x86 build tools (19.39.33523)
- rustup/rustc/cargo 1.78.0

**Comment by ndunnett** [comment] 2024-05-05 15:27
> It says that your GPU is not supported. Have you tried updating your graphics card driver?

That fixed it for me, thank you. I didn't realise I was on old drivers - updated from GeForce ~472 to 552.22 and now it runs no problem.

**Comment by Moshyfawn** [comment] 2024-05-05 16:02
This seems to be a duplicate question. I'll close this one in favour of the other. Be sure to +👍 and add any missing information.

Duplicate of:
- #9251

**Closed by Moshyfawn** 2024-05-05 16:02 UTC
Labels: defect, triage, panic / crash, admin read
