### ISSUE TITLE
Remove folder from project does not persist its state

### ISSUE THREAD

**Issue by fallenwood** [zed-industries/zed#6696] opened 2024-01-25 10:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open Zed, File -> Add folder to project
2. Right click the folder at side bar, click Remove from Project, make sure the folder is removed
3. Quit Zed (Zed -> Quit)
4. Reopen Zed, the removed folder appears again in the sidebar, which is NOT expected

### Environment

Zed: v0.119.19 (Zed)
OS: macOS 14.3.0
Memory: 64 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment] 2024-01-29 12:07
Zed does not save any "workspace exclusions" yet, but it saves recent workspaces' information in the database, see https://github.com/zed-industries/zed/discussions/6703?notification_referrer_id=NT_kwDOACkO1bI5MjE0NzYyNjUwOjI2OTA3NzM&notifications_query=repo%3Azed-industries%2Fzed+is%3Aunread#discussioncomment-8281516 for more details.

We need to store such exclusions in the database and query for every workspace loaded.

**Comment by Moshyfawn** [comment] 2024-05-30 18:50
The expected behaviour seems to be the current one in the latest version of Zed. I'm going to close this issue as resolved, but be sure to let us know if you're still seeing the same behaviour so we can reopen the ticket.

**Closed by Moshyfawn** 2024-05-30 18:50 UTC
Labels: defect, project panel

**Comment by arkrost** [comment] 2024-10-24 22:48
How is it possible to start with empty workspace again? I opened a folder, then remove it from project, but it persists.
