### ISSUE TITLE
Frame rate is capped to 60fps using Mac ProMotion display

### ISSUE THREAD

**Issue by Tom-Boscher** [zed-industries/zed#7413] opened 2024-02-05 23:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

ProMotion is enabled on my Mac M1 Pro, I tested on some games/app, the frame rate hit 120fps but using Zed the frame rate is capped to 60fps.

### Environment

Zed: v0.121.3 (Zed Preview)
OS: macOS 14.3.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/24520681/7eeb2d2f-4a71-4f14-9595-a4b9bcb21eaf

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment] 2024-02-06 08:12
Ohh, interesting that this still shows up. Thanks for reporting @Tom-Boscher.

What happens in `Direct` mode? Does that go up to 120fps? In your video you're in `composited` mode. You can try going in/out of fullscreen, for example, to try to trigger `Direct` mode.

**Comment by mrnugget** [comment] 2024-02-06 09:31
cc @as-cii and @nathansobo

**Comment by as-cii** [comment] 2024-02-06 09:41
Thanks for the report!

The only thing I can think is happening here is that we somehow started the display link on the wrong screen. @Tom-Boscher do you have multiple screens? If so, what happens if you move Zed between those screens and try scrolling around?

**Comment by Tom-Boscher** [comment] 2024-02-06 09:58
I had only the MacBook display when I recorded the vidéo, no external screens.
I retried just now (entering/exiting fullscreen) and I'm still in `composited` mode:

https://github.com/zed-industries/zed/assets/24520681/c6b66f18-927d-4c1c-878c-9f52083461c4

**Comment by mrnugget** [comment] 2024-02-06 13:38
Just to exclude some things: what if you open this file and scroll it all the way down, as fast as you can? https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts

(We don't use 120FPS if we don't need them, so 45FPS can be completely fine if not a lot happens)

**Comment by Tom-Boscher** [comment] 2024-02-06 14:00
I did a more radical test: I reset my MacBook to factory settings then reinstall Zed Preview and now it works:

https://github.com/zed-industries/zed/assets/24520681/37a4cd6b-f4af-4746-9a98-94237bfb37d8

**Comment by mrnugget** [comment] 2024-02-06 14:03
Hmmmmm, factory reset — not sure whether I should say "fixed" now or not. But I guess we've now lost all information to reproduce anyway, so do you think it's okay to close this issue @Tom-Boscher?

**Comment by Tom-Boscher** [comment] 2024-02-06 14:04
When I record my screen using Quicktime Player, `Composited` mode is activated. If I don't record the screen, `Direct` mode is activated when in fullscreen (`Composited` is activated when not in fullscreen)

**Comment by Tom-Boscher** [comment] 2024-02-06 14:06
> Hmmmmm, factory reset — not sure whether I should say "fixed" now or not. But I guess we've now lost all information to reproduce anyway, so do you think it's okay to close this issue @Tom-Boscher?

Indeed we lost information. We can close this issue and I will investigate on my side to see if using an external screen I encounter a capping of the framerate in Zed.

**Comment by wzxu** [comment] 2024-02-07 15:27
> Just to exclude some things: what if you open this file and scroll it all the way down, as fast as you can? https://github.com/microsoft/TypeScript/blob/main/src/compiler/types.ts
> 
> (We don't use 120FPS if we don't need them, so 45FPS can be completely fine if not a lot happens)

Hi everyone so it turns out I'm having this issue as well. No wonder I find VS Code much smoother than Zed at scrolling.
Here's me scrolling this file. It's built-in Retina display on MBP 14. What can I do to help debug this?

https://github.com/zed-industries/zed/assets/5619348/c7e584fd-6f80-4bd6-ae7d-f76737cb01f9

**Comment by wzxu** [comment] 2024-02-07 15:34
Okay so I tried going into full screen and quickly scroll there, and it did kick Zed into "Direct" mode, but the fps still cap at 60hz. (Can't screen record because that dropped it back to "Composite" again.)

**Comment by wzxu** [comment] 2024-02-08 11:25
> Okay so I tried going into full screen and quickly scroll there, and it did kick Zed into "Direct" mode, but the fps still cap at 60hz, only slightly going into 61 or 62hz. (Can't screen record because that dropped it back to "Composite" again.)


https://github.com/zed-industries/zed/assets/5619348/b9bad9fd-3662-4967-92ba-74b55d42a7d6

**Comment by jansedlon** [comment] 2024-02-09 07:45
Seems like it's fixed in 0.122.2

**Comment by mrnugget** [comment] 2024-02-09 08:25
Yes, this was fixed in https://github.com/zed-industries/zed/pull/7583.

**Closed by mrnugget** 2024-02-09 08:25 UTC
Labels: defect, macOS, gpui

**Comment by wzxu** [comment] 2024-02-09 15:20
Confirmed fixed on my end with 0.122.2 🎉
