### ISSUE TITLE
Project search does not respect .git/info/exclude automatically

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#20706] opened 2024-11-15 02:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Similar to https://github.com/zed-industries/zed/issues/12341.

- `echo "Hello" > abc`
- `echo "/abc" >> .git/info/exclude`
- Project search "Hello"
- Result shown

### Environment

Zed: v0.162.1 (Zed Preview)
OS: macOS 15.1.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-15 05:54
> Check for existing issues

https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+.git%2Finfo%2Fexclude

Duplicate of https://github.com/zed-industries/zed/issues/5029

**Closed by SomeoneToIgnore** 2024-11-15 05:54 UTC
Labels: bug, triage, admin read
