### ISSUE TITLE
Support terminal link from git diff

### ISSUE THREAD

**Issue by watsoncj** [zed-industries/zed#17442] opened 2024-09-05 18:13 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Similar to https://github.com/zed-industries/zed/pull/7303, the Zed terminal should support opening a file by clicking the name in the git diff to optimize workflow with the git cli.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/user-attachments/assets/82408436-8d93-4823-b133-667fa58ae916

**Comment by notpeter** [comment] 2024-09-05 18:36
Duplicate of:
- https://github.com/zed-industries/zed/issues/15081

**Closed by notpeter** 2024-09-05 18:36 UTC
Labels: enhancement, triage, git, admin read
