### ISSUE TITLE
regex: \s not matching \n in Find with Regular Expression enabled

### ISSUE THREAD

**Issue by suren1986** [zed-industries/zed#19184] opened 2024-10-14 09:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Text:
```
ABCD
EFGH
IJKL
```

Pattern1: `\w+\n\w+\s\w+`
Pattern2: `\w+\s\w+\s\w+`

Pattern1 and Pattern2 should both match this text, while only Pattern1 match.

<img width="656" alt="图片" src="https://github.com/user-attachments/assets/d63dd0e7-a19c-4aed-b4e0-167d78e642df">
<img width="679" alt="图片" src="https://github.com/user-attachments/assets/3b419fe0-a2b1-4221-a27b-8c3552ce195f">

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

**Comment by dovakin0007** [comment] 2024-10-14 16:26
can you verify the regex I tried in Vs code still it wasn't working?
**
![image](https://github.com/user-attachments/assets/b5ebfc9f-567a-4381-8b7d-c49b587b813d)
**

**Comment by suren1986** [comment] 2024-10-15 01:25
> can you verify the regex I tried in Vs code still it wasn't working? ** ![image](https://private-user-images.githubusercontent.com/73059450/376321382-b5ebfc9f-567a-4381-8b7d-c49b587b813d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTU1OTUsIm5iZiI6MTcyODk1NTI5NSwicGF0aCI6Ii83MzA1OTQ1MC8zNzYzMjEzODItYjVlYmZjOWYtNTY3YS00MzgxLThiN2QtYzQ5YjU4N2I4MTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAxMjEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiM2YzM2Y3OGEzYmZjMTBhZWZlNzU0NDM5ZTkwNjYwMjFhOWRlOTM0NjFlZjk0NWYxZGM4MDY2MGRmNjk0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gLZpEDA1qaoOvyoilSStNgYlZP5r6DdBAZt5468Ftuc) **

Thank you for your reply.

I can verify it in Sublime
<img width="822" alt="图片" src="https://github.com/user-attachments/assets/48be8f2b-c18e-437b-9554-c9b1f59900a3">

I think `\s` should match EOL. It match the EOL of `EFGH`, it should also match the EOL of `ABCD`.

**Comment by suren1986** [comment] 2024-10-15 01:33
Pattern2 also worked in Javascript.

code
```
let str = "ABCD\nEFGH\nIJKL";

// 定义正则表达式
let regex = /\w+\s\w+\s\w+/g;

// 使用 match 方法匹配正则
let result = str.match(regex);

// 判断是否匹配到内容
if (result) {
    console.log("result: ", result);
} else {
    console.log("not match");
}
```

result:
<img width="934" alt="图片" src="https://github.com/user-attachments/assets/b8f635f7-0550-410f-b7c1-f8d10722e2fb">

**Comment by notpeter** [comment] 2024-10-15 19:06
I can reproduce.

For reference,  Zed uses the Rust [regex crate](https://docs.rs/regex/1.5.0/regex/index.html), currently v1.5.0.  Looks like the default features include `unicode` which includes `unicode-perl` which provides the `\s`.

`\s` should be equivalent to `[\t\r\n\f ]` and `[\t\r\n\f ]` works as expected.

Which led me to the solution: `\s` (just like `\n`) only makes sense if you are doing a multiline regex which usually is defined outside the scope of your regex itself (e.g. [`re.MULTILINE`](https://docs.python.org/3/library/re.html#re.MULTILINE) in Python, `/m` in Sed, `/s` in Perl, etc).

Which we do here:
https://github.com/zed-industries/zed/blob/695176898e809fe097b5f6ea6db5712cf1cfefe0/crates/project/src/search.rs#L128-L132

Fixed in:
- https://github.com/zed-industries/zed/pull/19241

**Closed** 2024-10-15 19:47 UTC
Labels: defect, editor, search / project search

**Comment by notpeter** [comment] 2025-03-03 15:32
FYI I'm reverting https://github.com/zed-industries/zed/pull/19241 in https://github.com/zed-industries/zed/pull/25926.

Once that lands, unless we implement a proper multiline regex toggle, as a workaround you'll need to explicitly include the literal `\n` in your regex when you want to use multiline regex mode.  So instead of `\s+` you'll have to do `[\t\n ]+` or a class with the [complete set of unicode whitespace characters](https://www.unicode.org/Public/UCD/latest/ucd/PropList.txt) if `\t\n ` is insufficient for your needs.

Apologies for the inconvenience.

For more context see:
- https://github.com/zed-industries/zed/issues/25901#issuecomment-2692996651
- https://github.com/zed-industries/zed/issues/25925
