### ISSUE TITLE
Documentation closes too fast

### ISSUE THREAD

**Issue by DevNulPavel** [zed-industries/zed#8369] opened 2024-02-25 06:43 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hello

Documentation for symbol in code closes too fast, so i sometimes cannot move mouse pointer fast enough to read full text with scroll 

<img width="613" alt="Screenshot 2024-02-25 at 09 40 30" src="https://github.com/zed-industries/zed/assets/14924622/1e46faf9-b85b-4444-8a98-016f71052660">

**Comment by JosephTLyons** [comment] 2024-02-27 18:54
Hey @DevNulPavel,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7304

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-27 18:54 UTC
Labels: enhancement, popovers
