### ISSUE TITLE
Show what eslint error is triggered

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [zed-industries/zed#21636] opened 2024-12-06 11:14 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Instead of just showing that the error is from eslint like that:
![image](https://github.com/user-attachments/assets/b778b059-d479-43ca-9bf8-a925304670ed)
it should show what eslint rule was violated like that:
![image](https://github.com/user-attachments/assets/eecfb379-81b5-401a-901b-a0c5a257b735)

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: x86_64

**Comment by JosephTLyons** [comment] 2024-12-12 20:26
Hey @FleetAdmiralJakob,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4388

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, feel free to leave a comment here explaining the difference and we will reopen this issue.

**Closed by JosephTLyons** 2024-12-12 20:26 UTC
Labels: enhancement, typescript, javascript, eslint, tooling, logging, duplicate
