### ISSUE TITLE
Allow git commands for Staged and Unstaged files directly on the platform.

### ISSUE THREAD

**Issue by emersonjds** [zed-industries/zed#7920] opened 2024-02-16 18:14 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

As I work I have adopted micro commits to have greater control over the history of changes. Currently VSCode allows me to make this micro commit on any change directly in the editor.

It would be incredible if ZED had this same possibility since it is already integrated with git and any change we make we already see changes and color markings, but without the possibility of committing a single file but having to commit several things at once .

I really believe in the project and I'm always looking for tools that work to improve the developer experience.

#goZED

Thanks for everyone's work.

### If applicable, add mockups / screenshots to help present your vision of the feature

How it works today

![Screenshot 2024-02-16 at 15 04 50](https://github.com/zed-industries/zed/assets/12503997/7e575ad3-413a-492a-9fcf-acdb869da301)

How it should work

https://github.com/zed-industries/zed/assets/12503997/936ceace-8faf-4d72-99c9-ef2c29c5d482

**Comment by CurbaiCode** [comment] 2024-02-16 18:54
I'm pretty sure this is a duplicate of #4367, which I would really love to see in Zed as well!

**Comment by SomeoneToIgnore** [comment] 2024-02-16 20:15
Indeed seems like a dupe, thank you for spotting.

**Closed by SomeoneToIgnore** 2024-02-16 20:15 UTC
Labels: enhancement, triage, admin read
