### ISSUE TITLE
Controls whether folders should open in a new window or replace the last active window

### ISSUE THREAD

**Issue by danilkinkin** [zed-industries/zed#8249] opened 2024-02-23 06:34 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Add an option like in VSCode "Controls whether folders should open in a new window or replace the last active window"

### If applicable, add mockups / screenshots to help present your vision of the feature

How it's work in VSCode

https://github.com/zed-industries/zed/assets/10831688/9d113b01-bcb2-47f3-ac78-34401bcbd69e

How it's work in Zed

https://github.com/zed-industries/zed/assets/10831688/e5ca24b7-f12e-4559-8622-a5da6ae53916

**Comment by d1y** [comment] 2024-02-23 07:02
Someone finally raised this issue. It would be very uncomfortable to switch to zed from vscode.

**Comment by SomeoneToIgnore** [comment] 2024-02-23 07:19
This is actually a duplicate of https://github.com/zed-industries/zed/issues/7419

**Closed by SomeoneToIgnore** 2024-02-23 07:19 UTC
Labels: enhancement, triage, admin read

**Comment by SomeoneToIgnore** [comment] 2024-02-23 11:37
Posting a fix here for visibility: https://github.com/zed-industries/zed/pull/8267
