### ISSUE TITLE
Once signed in, not possible to change user

### ISSUE THREAD

**Issue by danielm-cfa** [zed-industries/zed#8196] opened 2024-02-22 13:44 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I signed in with a github user. I wanted to change to a different github user but it is not possible.
I tried signing out, restarting the app, even removing the app from github user settings.

### Environment

macos

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2024-02-22T08:40:21-05:00 [INFO] ========== starting zed ==========
2024-02-22T08:40:21-05:00 [INFO] Opening main db
2024-02-22T08:40:21-05:00 [ERROR] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
2024-02-22T08:40:21-05:00 [INFO] Opening main db
2024-02-22T08:40:21-05:00 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/opt/cython/bin:/Users/style/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/opt/node@20/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/style/Library/Application Support/JetBrains/Toolbox/scripts
2024-02-22T08:40:21-05:00 [INFO] build git repository ".git"
2024-02-22T08:40:21-05:00 [INFO] set status on client 0: Authenticating
2024-02-22T08:40:21-05:00 [INFO] Opening main db
2024-02-22T08:40:21-05:00 [INFO] set status on client 119234: Connecting
2024-02-22T08:40:21-05:00 [INFO] Opening main db
2024-02-22T08:40:21-05:00 [INFO] Node runtime install_if_needed
2024-02-22T08:40:21-05:00 [ERROR] crates/workspace/src/persistence/model.rs:257: No such file or directory (os error 2)
2024-02-22T08:40:21-05:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-02-22T08:40:21-05:00 [INFO] starting language server "pyright", path: "/Users/style/projects/d20-functions", id: 1
2024-02-22T08:40:22-05:00 [INFO] add connection to peer
2024-02-22T08:40:22-05:00 [INFO] waiting for server hello
2024-02-22T08:40:22-05:00 [INFO] got server hello
2024-02-22T08:40:22-05:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 337, id: 908985 })
2024-02-22T08:40:22-05:00 [INFO] set status on client 119234: Connected { peer_id: PeerId { owner_id: 337, id: 908985 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-02-22T08:40:22-05:00 [INFO] Node runtime install_if_needed
2024-02-22T08:40:22-05:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-22T13:40:22.803Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-02-22T13:40:22.803Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-02-22T08:40:22-05:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "c22e14ed-5912-426a-bbfc-fde16578a615",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-02-22T08:40:23-05:00 [INFO] Node runtime install_if_needed
2024-02-22T08:40:23-05:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-22T13:40:23.192Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-02-22T13:40:23.192Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-02-22T08:40:23-05:00 [INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Pyright language server 1.1.351 starting"
}
2024-02-22T08:40:23-05:00 [INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/style/Library/Application%20Support/Zed/languages/pyright/node_modules/pyright/dist"
}
2024-02-22T08:40:23-05:00 [INFO] 1 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Starting service instance \"\""
}
2024-02-22T08:40:24-05:00 [INFO] 1 unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "8fb6a2cb-7b7f-469d-9c67-1e0b61b035c3",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-02-22T08:40:25-05:00 [INFO] set status on client 119234: SignedOut
2024-02-22T08:41:25-05:00 [INFO] set status on client 119234: Authenticating
2024-02-22T08:41:25-05:00 [INFO] set status on client 119234: Connecting
2024-02-22T08:41:25-05:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-02-22T08:41:26-05:00 [INFO] add connection to peer
2024-02-22T08:41:26-05:00 [INFO] waiting for server hello
2024-02-22T08:41:26-05:00 [INFO] got server hello
2024-02-22T08:41:26-05:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 1 }, peer id: PeerId { owner_id: 337, id: 909393 })
2024-02-22T08:41:26-05:00 [INFO] set status on client 119234: Connected { peer_id: PeerId { owner_id: 337, id: 909393 }, connection_id: ConnectionId { owner_id: 0, id: 1 } }
2024-02-22T08:41:30-05:00 [INFO] open paths ["/Users/style/.config/zed/settings.json"]
2024-02-22T08:41:30-05:00 [INFO] Initializing default prettier with plugins {}
2024-02-22T08:41:30-05:00 [INFO] starting language server "json-language-server", path: "/Users/style/.config/zed/settings.json", id: 2
2024-02-22T08:41:30-05:00 [INFO] Node runtime install_if_needed
2024-02-22T08:41:30-05:00 [INFO] 1 unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "1bf4b8cd-4713-4679-8846-117e4d01694c",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-02-22T08:41:31-05:00 [INFO] Node runtime install_if_needed
```

**Comment by SomeoneToIgnore** [comment] 2024-02-22 15:12
Yes, this is a very unfortunate UX we have here, but the only way to log off for good is to remove Zed from your keychains.
https://github.com/zed-industries/zed/issues/4716#issuecomment-1908631372

Will close it as a duplicate of the issue linked.

**Closed by SomeoneToIgnore** 2024-02-22 15:12 UTC
Labels: defect, triage, admin read

**Comment by JosephTLyons** [comment] 2024-02-23 18:33
Here as well, just for future reference:

https://zed.dev/faq#how-do-i-log-out-of-github-in-zed
