### ISSUE TITLE
Assistant configuration panel should allow scrolling down in Linux

### ISSUE THREAD

**Issue by pdenapo** [zed-industries/zed#16289] opened 2024-08-15 13:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Wen you want to configure the assistant through the configuration panel, the options shown get truncated . See my screenshot below, you cannot configure Ollama.  I would suggest to add a lateral scroll-down bar (like in the settings windows in my screenshot)

### Environment

Zed: v0.148.0 (Zed)
OS: Linux X11 endeavouros unknown
Memory: 7.7 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 4400 (HSW GT2) || Intel open-source Mesa driver || Mesa 24.1.6-arch1.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![zed_bug_report](https://github.com/user-attachments/assets/f34c367f-c27d-467b-b785-0d039005b99e)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Moshyfawn** [comment] 2024-08-15 13:57
This has already been addressed in [`0.148.1`](https://zed.dev/releases/stable/0.148.1). Let us know if the update has fixed it for you.

Duplicate of:
- #16280

**Closed by Moshyfawn** 2024-08-15 13:57 UTC
Labels: defect, triage, admin read

**Comment by CharlesChen0823** [comment] 2024-08-15 13:59
I think this not fixed, I test mouse scroll not working in X11. But I have remember it works before?

**Comment by pdenapo** [comment] 2024-08-15 14:30
It worked for me in 0.148.1 !
