### ISSUE TITLE
Doesn't open when its already open in another profile on macOS

### ISSUE THREAD

**Issue by AnilSeervi** [zed-industries/zed#11248] opened 2024-05-01 09:05 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The App does not open when tried to open in another profile on macOS(its already running/open in the other profile)

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

N/A

**Comment by JosephTLyons** [comment] 2024-05-03 18:31
Hey @AnilSeervi,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4607

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-05-03 18:31 UTC
Labels: defect, triage, admin read

**Comment by AnilSeervi** [comment] 2024-05-04 08:24
> Hey @AnilSeervi,
> 
> This issue appears to be a duplicate of:
> 
> - https://github.com/zed-industries/zed/issues/4607
> 
> Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

Thank you @JosephTLyons. I wasn't able to find the related issue.

**Comment by JosephTLyons** [comment] 2024-05-07 18:26
No worries - they sometimes are hard for me to find as well, and I'm in here all the time.
