### ISSUE TITLE
[Windows][Nightly] Cmd window opens and closes (flickering) 10 times upon Zed startup

### ISSUE THREAD

**Issue by SoleSoul** [zed-industries/zed#19186] opened 2024-10-14 10:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Start Zed and wait a few seconds. You can see a Cmd window open and close for a moment 10 times.

### Environment

Zed: v0.158.0 (Zed Dev ec5d6e96bb304886f49680b54e58c9b0e7221cd6)
OS: Windows 10.0.22631
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || 101.5595

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SoleSoul** [comment] 2024-10-14 10:17
https://github.com/user-attachments/assets/0d009923-d053-43c8-97f7-b29e379443fa

**Comment by SomeoneToIgnore** [comment] 2024-10-14 10:25
Duplicate of https://github.com/zed-industries/zed/issues/18371

**Closed by SomeoneToIgnore** 2024-10-14 10:25 UTC
Labels: defect, triage, admin read
