### ISSUE TITLE
add run, debug and crash, troubleshooting support

### ISSUE THREAD

**Issue by toythebananaman** [zed-industries/zed#13896] opened 2024-07-06 14:27 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

a run arrow like vs code, for cpp c and python, in my case, so linking, variable changing ram usage. and others, for large programms allow runtime stops to handle errors

### If applicable, add mockups / screenshots to help present your vision of the feature

O-
O---O
O------O
O---O
O-

**Comment by someone13574** [comment] 2024-07-06 14:30
Duplicate of https://github.com/zed-industries/zed/issues/5065
Open PR: https://github.com/zed-industries/zed/pull/13433

**Closed** 2024-07-06 16:54 UTC
Labels: enhancement, triage, admin read
