### ISSUE TITLE
environment variables for rust analyzer (via extraEnv) not working

### ISSUE THREAD

**Issue by huntc** [zed-industries/zed#14994] opened 2024-07-23 02:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I don't appear to be able to set environment variables for Rust Analyzer. Perhaps my paths are incorrect? Here are my project's settings:

```json
{
  "lsp": {
    "rust-analyzer": {
      "initialization_options": {
        "server": {
          "extraEnv": {
            "RUSTUP_TOOLCHAIN": "stable"
          }
        }
      }
    }
  }
}
```

### Environment

```
Zed: v0.144.4 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by matthew-levan** [comment] 2024-07-23 14:26
I am experiencing this bug as well, as of the latest update on `macos-aarch64` version `0.144.4`.

**Comment by notpeter** [comment] 2024-07-26 18:06
Duplicate of:
- https://github.com/zed-industries/zed/issues/14334

**Closed by notpeter** 2024-07-26 18:06 UTC
Labels: defect, triage, admin read
