### ISSUE TITLE
User configurable mouse bindings

### ISSUE THREAD

**Issue by fornellas-udemy** [zed-industries/zed#18622] opened 2024-10-02 10:55 UTC
### Describe the feature

alt-click can be used to create multiple cursors. Under Linux, it is _fairly common_ for alt+click to be "drag a window" in various desktops environments. In this scenario, it is impossible to create multiple cursors. On Sublime, it uses ctrl+click for multi-cursor and that works just fine.

I could not find a way to reconfigure from alt-click to ctrl-click to resolve this incompatibility.

Editing in a multibuffer: Can we have multi-cursor with alt+click to be reconfigurable to what works best for each user, just like we can do with all keybindings?

Thanks.

**Comment by notpeter** [comment] 2024-10-04 19:47
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/10647

But I took your suggestions from here and edited that issue to explicitly flesh it out a bit.

I also included your notes from:
- https://github.com/zed-industries/zed/issues/18627

**Closed by notpeter** 2024-10-04 19:47 UTC
Labels: enhancement, mouse interaction, editor, keymap / key binding, multi-buffer
