### ISSUE TITLE
Support autocomplete from ollama models for inline completions

### ISSUE THREAD

**Issue by TechnicalParadox** [zed-industries/zed#16030] opened 2024-08-09 13:14 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode I use the Continue.dev extension to change the autocomplete model from GitHub Copilot to ollama deepseek-coder:7b. This works great. I would like to see a similar feature added to Zed.

Currently, we can use inline generation with other models but not autocomplete.

### If applicable, add mockups / screenshots to help present your vision of the feature

Heres an example of the config.json in Continue.dev to change autocomplete model:
```
  "tabAutocompleteModel": {
    "title": "Tab Autocomplete Model",
    "provider": "ollama",
    "apiBase": "http://localhost:11434",
    "model": "deepseek-coder:6.7b",
    "contextLength": 8192
  },
  "tabAutocompleteOptions": {
    "prefixPercentage": 0.5,
    "maxPromptTokens": 4096
  },
```

**Comment by notpeter** [comment] 2024-08-09 18:15
Duplicate of 
- https://github.com/zed-industries/zed/issues/15968

**Closed by notpeter** 2024-08-09 18:15 UTC
Labels: enhancement, ai, inline completion
