### ISSUE TITLE
REPL not working for venv setup

### ISSUE THREAD

**Issue by andaag** [zed-industries/zed#16757] opened 2024-08-23 15:28 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

REPL doesn't seem to find the kernel at all. My assumption is that it's looking for only system kernels, while I want to use the one in .venv. I can't find any way of selecting python .venv for this?

Opening a terminal in this and running things there naturally works as direnv works.

### Environment

Linux fedora, python 3.12.
direnv activating and installing .venv
```
pyenv local $(cat .python-version)
export POETRY_VIRTUALENVS_IN_PROJECT=1
poetry env use "$(pyenv root)/versions/$(cat .python-version)/bin/python"
poetry install --sync --no-root
export VIRTUAL_ENV=$(poetry env info --path)
PATH_add "$VIRTUAL_ENV/bin"
export POETRY_ACTIVE=1
```

```
[tool.poetry]
name = "nansen-clickhouse"
version = "0.1.0"
description = ""
authors = ["Anders Aagaard <anders.aagaard@nansen.ai>"]

[tool.poetry.dependencies]
python = "^3.11"
jupysql = "^0.10.1"
clickhouse-sqlalchemy = "^0.2.4"
ipykernel = "^6.25.2"
toml = "^0.10.2"
pandas = "^2.1.0"
matplotlib = "^3.8.0"
clickhouse-connect = "^0.6.22"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.jupysql.SqlMagic]
autopandas = true
displaylimit = 0
named_parameters = true

```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[zed.log](https://github.com/user-attachments/files/16730776/zed.log)

</pre></details>

**Comment by universalmind303** [comment] 2024-08-23 18:55
possible duplicate of https://github.com/zed-industries/zed/issues/15563

**Closed** 2024-11-11 18:19 UTC
Labels: bug, linux, repl
