### ISSUE TITLE
Inlay hints are hopelessly broken

### ISSUE THREAD

**Issue by lylythechosenone** [zed-industries/zed#14869] opened 2024-07-20 17:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using many non-standard inlay hints from rust-analyzer, characters are shuffled around such that their original meaning is indiscernible. See screenshots.

### Environment

```
Zed: v0.144.3 (Zed)
OS: macOS 15.0.0
Memory: 8 GiB
Architecture: aarch64
```

```
rustc 1.81.0-nightly (6b0f4b5ec 2024-06-24)
binary: rustc
commit-hash: 6b0f4b5ec3aa707ecaa78230722117324a4ce23c
commit-date: 2024-06-24
host: aarch64-apple-darwin
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

VSCode (correct):
![image](https://github.com/user-attachments/assets/d359c22c-14ef-4196-bf3e-45b1d9b58931)
Zed (incorrect):
![image](https://github.com/user-attachments/assets/551c0106-2a1e-47f6-9f19-2cf063e4d2f5)

**Comment by SomeoneToIgnore** [comment] 2024-07-20 18:20
Duplicate of https://github.com/zed-industries/zed/issues/13381 and https://github.com/zed-industries/zed/issues/7928

**Closed by SomeoneToIgnore** 2024-07-20 18:20 UTC
Labels: defect, triage, admin read
