### ISSUE TITLE
horizontal Unicode box drawing characters rendered at double width

### ISSUE THREAD

**Issue by perkee** [zed-industries/zed#15913] opened 2024-08-07 15:59 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

paste the following into a text file
```
┌──────┐
│ boxy │
└──────┘
```
Open the file in zed and you get 

![image](https://github.com/user-attachments/assets/4845fb4c-60a1-4023-96c4-5a9eb69d83cf)

Compare with `cat boxy.txt` in wezterm

![image](https://github.com/user-attachments/assets/31603a2d-5502-4e40-97a2-aba9a6aa98cb)

or opening it in VSCode 

![image](https://github.com/user-attachments/assets/5ccdcaaf-e139-4332-9922-d8ad146884f1)

### Environment

Zed: v0.146.5 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-09 19:15
I think this is a duplicate of:

- #15542 

It only fails for me with the default `Zed Plex Mono` font not with anything else.  As a workaround you can download [IBM Plex Mono](https://fonts.google.com/specimen/IBM+Plex+Mono) (the font Zed Plex Mono is based on) and set `"buffer_font_family": "IBM Plex Mono",` in your settings.

Thanks for reporting and the simple reproduction test case.

**Closed by notpeter** 2024-08-09 19:16 UTC
Labels: defect, triage, admin read
