### ISSUE TITLE
`CMD+W` to close the workspace window (but not the entired app) __after__ all individual file tabs are closed (currently forced to use `CMD+SHIT+W`)

### ISSUE THREAD

**Issue by danielweck** [zed-industries/zed#7200] opened 2024-02-01 09:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I am gradually transitioning from Visual Studio Code for some of my development projects (I love Zed's launch speed and general superior performance, so much so that I can live with a few inconsistencies / learning curve due to different design choices, missing features and bugs 👍 ).

I was/am used to `CMD+W` closing the VSCode workspace window __after__ all individual file tabs are closed. It is strange to me that an additional shortcut with the `SHIFT` key modifier is necessary to achieve this in Zed, though I totally appreciate how useful `CMD+SHIT+W` is when one or more file tabs are still open (saves me hitting `CMD+W` multiple times until the workspace window finally closes :)

Related issue: https://github.com/zed-industries/zed/issues/4322

**Comment by JosephTLyons** [comment] 2024-02-02 03:32
Hey @danielweck,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4835

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-02 03:32 UTC
Labels: enhancement, workspace

**Comment by danielweck** [comment] 2024-02-02 05:45
Duplicate issue Indeed, sorry for not finding the original one, and thank you for the triage!

**Comment by danielweck** [comment] 2024-02-02 05:52
actually there's an even older identical issue / feature request:

https://github.com/zed-industries/zed/issues/5322

:)
