### ISSUE TITLE
flickering tabs

### ISSUE THREAD

**Issue by gabrielalexandrelopes** [zed-industries/zed#8596] opened 2024-02-29 10:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The tabs keep flickering when the text window is selected. See examples:

https://github.com/zed-industries/zed/assets/133671070/aa593490-11ba-46f5-a915-6717a958af88

https://github.com/zed-industries/zed/assets/133671070/e4df21a8-74b1-468a-b5d5-7b5be8110de3

https://github.com/zed-industries/zed/assets/133671070/facacb53-0db2-4f87-944b-1eff90337411

### Environment

Zed: v0.125.0 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

sorry, cannot add log because it contains paths that I cannot share

**Comment by Moshyfawn** [comment] 2024-02-29 13:53
Duplicate of #8050

**Comment by Moshyfawn** [comment] 2024-02-29 13:54
Be sure to +👍 the other issue to bump it and possibly add any additional details you have.

**Closed by Moshyfawn** 2024-02-29 13:54 UTC
Labels: defect, triage, admin read
