### ISSUE TITLE
html-language-server not installing (Windows)

### ISSUE THREAD

**Issue by ZeroHawkeye** [zed-industries/zed#18519] opened 2024-09-30 00:59 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The project is on the E drive and cannot be started when using the emmet lsp plug-in

### Environment

windows 10
32G RAM

### If applicable, attach your Zed.log file to this issue.

```bash
-- stderr--
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'E:\C:\Users\zero\AppData\Local\Zed\extensions\work\html\node_modules\@zed-industries\vscode-langservers-extracted\bin\vscode-html-language-server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.17.0
```

**Comment by 001123** [comment] 2024-10-08 12:53
Same issue, I cannot figure out how to enable emmet.


Zed: v0.156.0 (Zed Dev 85eceb7194440eb308e331b425901cf88a306f0b)
OS: Windows 10.0.22631
Memory: 63.7 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4060 Laptop GPU || NVIDIA || 565.90

**Comment by mally8** [comment] 2024-10-18 03:36
Same here.
I think the issue is its trying to go to `"C:\C:\"` which seems to fail since that does not exist ?
Same with pictures above that its trying to go to `D:\C:\` and `E:\C:\`.

I have checked the file and it does exist so that is my only guess so far.

![image](https://github.com/user-attachments/assets/eaff699a-4dca-4ac2-b387-d9e17ff26470)

**Comment by hironichu** [comment] 2024-10-23 17:36
Yeah it works after editing the code for the extension, not sure if this is the way to go, im not familiar with how Zed extension system works (especially for html)

But this fixes the issue and now works on Windows 11 

```rust
    fn language_server_command(
        &mut self,
        language_server_id: &LanguageServerId,
        _worktree: &zed::Worktree,
    ) -> Result<zed::Command> {
        let server_path = self.server_script_path(language_server_id)?;
		let current_dir = env::current_dir().unwrap();

		let full_path  = current_dir.join(&server_path).to_string_lossy().to_string();

		#[cfg(not(target_os = "windows"))]
		let path: String = full_path.split_off(3);

		#[cfg(target_os = "windows")]
		let path: String = full_path;

        Ok(zed::Command {
            command: zed::node_binary_path()?,
            args: vec![
                path,
                "--stdio".to_string(),
            ],
            env: Default::default(),
        })
    }
```

Note, i have not tried on Mac or Linux, i just blindly added some checks, if you have a better way to dismiss the Drive letter on either the Node side or Rust side


In any case, I'll fork the repo with the fix for windows if anyone is interested...

**Comment by shessafridi** [comment] 2024-11-05 07:31
The same issue is happening with the emmet plugin too on Windows

it's trying to go to `F:\C:`

Specs:
Zed: v0.161.0 (Zed Dev 3b76ba6d5ab6745cd12d2cb632ae4a55680dc89a)
OS: Windows 10.0.26100
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 || NVIDIA || 566.03

Error Message:
```
Language server error: emmet-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'F:\C:\Users\Shess\AppData\Local\Zed\extensions\work\emmet\node_modules\.bin\emmet-language-server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0
```

**Comment by dylansantwani** [comment] 2024-12-08 20:15
Hello, if anyone still has this issue I have fixed it. Clone my repository below.
https://github.com/dylansantwani/zed-fixed-windows

**Comment by 001123** [comment] 2024-12-11 04:51
> Hello, if anyone still has this issue I have fixed it. Clone my repository below. https://github.com/dylansantwani/zed-fixed-windows

How do you fix it? Can you make a PR

**Comment by notpeter** [comment] 2024-12-11 15:04
> How do you fix it? Can you make a PR

Their diff is here:
- https://github.com/zed-industries/zed/issues/17571#issuecomment-2533059257

But it is an unsuitable solution.

**Comment by notpeter** [comment] 2024-12-11 15:08
Closing in favor of:
- https://github.com/zed-industries/zed/issues/20559

**Closed by notpeter** 2024-12-11 15:09 UTC
Labels: bug, windows, html

**Comment by Rahullkumr** [comment] 2024-12-25 20:39
Language server error: vscode-html-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1252
  throw err;
  ^

Error: Cannot find module 'C:\C:\Users\rahul\AppData\Local\Zed\extensions\work\html\node_modules\@zed-industries\vscode-langservers-extracted\bin\vscode-html-language-server'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.12.0
