### ISSUE TITLE
Support Re-indent selected code?

### ISSUE THREAD

**Issue by diuming** [zed-industries/zed#16010] opened 2024-08-09 02:23 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

support Re-indent selected code feature like Xcode `Ctrl + I`?

**Comment by notpeter** [comment] 2024-08-09 18:10
Duplicate of:
- https://github.com/zed-industries/zed/issues/5026

Please 👍 to vote on that issue and subscribe to track it's progress.
Thanks for reporting!

**Closed by notpeter** 2024-08-09 18:10 UTC
Labels: enhancement, triage, admin read
