### ISSUE TITLE
autocomplete only appears when pressing ctrl + space in astro js project

### ISSUE THREAD

**Issue by dai-re** [zed-industries/zed#14960] opened 2024-07-22 12:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

autocomplete only appears when pressed ctrl + space in astro js project,

in next js autocomplete runs smoothly

### Environment

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.9-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8350U CPU @ 1.70GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: LENOVO
Product Name: 20L5S0M60J
System Version: ThinkPad T480

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Uploading untitled.mp4…

**Comment by dai-re** [comment] 2024-07-23 00:28
https://github.com/user-attachments/assets/58c149e2-0908-4019-a61c-86625a4833c4

**Comment by PolyCatDev** [comment] 2024-08-01 09:29
I have the same issue here. Any updates in this?

**Comment by SomeoneToIgnore** [comment] 2024-08-01 09:36
So far, I have asked a project to repro it on (both here and in https://github.com/zed-industries/zed/issues/8766), any updates on this?

**Comment by SomeoneToIgnore** [comment] 2024-08-01 09:40
I think I will close this a as a duplicate of https://github.com/zed-industries/zed/issues/8766 so we can concentrate the discussion (and my repeated pledges for a project) in one place.

**Closed by SomeoneToIgnore** 2024-08-01 09:40 UTC
Labels: defect, autocompletions, astro
