### ISSUE TITLE
Text off screen

### ISSUE THREAD

**Issue by uforek** [zed-industries/zed#10151] opened 2024-04-04 04:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Perhaps I am using the editor incorrectly, but...

If the text I am entering on the current line exceeds the window width, the text becomes obscured by the scrollbar. The scrollbar is just wide enough to obscure a single character. I should also mention that I use zed split screen, so my width is pretty narrow, and my font is relatively large (14px).

Is there a setting I could configure that makes the text scoot over sooner, so it never reaches the scrollbar?

### Environment

Zed: v0.130.0 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

**Comment by bennetbo** [comment] 2024-04-04 08:41
Sounds like this is a duplicate of #7098, as of right now I don't think there is anything you can configure to prevent this.

**Closed** 2024-04-04 08:42 UTC
Labels: defect, triage, admin read
