### ISSUE TITLE
Inline syntax highlighting

### ISSUE THREAD

**Issue by hos** [zed-industries/zed#12271] opened 2024-05-25 07:12 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In `vscode`, we have extensions to support different languages syntax highlighting inlined into another language. Primarily, I use it for `SQL`, but if it will be available, I think it will be very useful to switch language inside the context of the buffer. For example when we write an `html` inside of `go` application.

For existing issues I searched using `inline` and `syntax highlight` keywords.

### If applicable, add mockups / screenshots to help present your vision of the feature

```ts
await pgClient.query(
    sql`
    -- highlight this as SQL
    update users
        set ai_replaceable = false
    where users.user_id = $1
    `,
    [userId, amounts]
    )
    ```

**Comment by Moshyfawn** [comment] 2024-05-26 20:39
This seems to be a duplicate of another issue, so I'm going to close this one. Be sure to +👍 the other thread as well ashttps://github.com/zed-industries/zed/issues/7710#issuecomment-1942732210 for information on the current state of inline / injected syntax highlighting.

Duplicate of:
- #7710

**Closed by Moshyfawn** 2024-05-26 20:39 UTC
Labels: enhancement, triage, admin read
