### ISSUE TITLE
Diagnostics in Project Panel

### ISSUE THREAD

**Issue by aalhitennf** [zed-industries/zed#14990] opened 2024-07-22 23:10 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Coming from vscode i'm used to see red (error) and yellow (warning) entries in explorer if file contains any. I know Project Diagnostics (ctrl + shift + m) exists in Zed but it feels very unintuitive, at least for me. Seeing some feedback in file tree feels much more natural since you don't then have to switch to back and forth to diagnostics tab all the time.

### If applicable, add mockups / screenshots to help present your vision of the feature

![colors](https://github.com/user-attachments/assets/5fbba956-fc72-412a-a488-0d55785ce49c)

**Comment by JosephTLyons** [comment] 2024-07-27 20:30
Hey @aalhitennf,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5016

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-27 20:30 UTC
Labels: enhancement, project panel, diagnostics
