### ISSUE TITLE
Autocomplete Suggestions in Zed Prioritize Incorrect Items Compared to VSCode and Neovim

### ISSUE THREAD

**Issue by siddarta-weis** [zed-industries/zed#19453] opened 2024-10-19 10:05 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When typing in Zed, the autocomplete suggestions do not prioritize the most relevant items. For instance, when I type `Tb`, I expect suggestions like `TblComissoesOperadora` (which starts with Tb) to appear at the top of the list. However, other unrelated suggestions, such as `TabError` or `Traceback`, are prioritized. This issue affects development productivity since I need to scroll through or manually search for the correct autocomplete suggestion.

I've attached comparison screenshots from VSCode, Neovim, and Zed where Tb is typed in all three editors, showing how the correct suggestion is prioritized in the others but not in Zed.

### Environment

Zed: v0.157.5 (Zed)
OS: Linux Wayland fedora 40
Memory: 15.3 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (ADL GT2) || Intel open-source Mesa driver || Mesa 24.1.7

### If applicable, add mockups / screenshots to help explain present your vision of the feature

VSCode:
![vscode](https://github.com/user-attachments/assets/03437e51-822e-4fa8-ba6b-143545aa9afc)

NVIM:
![nvim](https://github.com/user-attachments/assets/74dc5866-0208-4610-a1b9-f795da9112eb)

Zed:
![zed](https://github.com/user-attachments/assets/18af9042-ecd0-44c3-8390-f7c61213eb83)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-22 18:30
Duplicate of:
- https://github.com/zed-industries/zed/issues/4327
- https://github.com/zed-industries/zed/issues/12698

**Closed by notpeter** 2024-10-22 18:30 UTC
Labels: defect, triage, admin read
