### ISSUE TITLE
Font features / stylistic sets not working on M1 but works on Intel

### ISSUE THREAD

**Issue by assayire** [zed-industries/zed#4839] opened 2023-04-04 20:13 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Use a font like Maple Mono NF or Cascadia Code that supports stylistic sets and enable them in the Zed settings, you will see that the font does not render the ligatures / SS on M1 but works on Intel

### Environment

Zed 0.79.1
Mac M1 on latest OS version

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by thorerik** [comment] 2024-02-02 10:16
It's a little more strange than that, it works if you eg. with Cascadia Code set
`"buffer_font_features": "ss19"` works, but the theme settings are entirely ignored.
Setting:
```json
"buffer_font_features": {
    "ss19": true
}
```
it doesn't work but theme settings are honored.

**Comment by thorerik** [comment] 2024-04-09 06:46
Quick test today it seems to be working with Zed Preview 0.130.2

**Comment by arjpar** [comment] 2024-05-05 07:26
I believe I still have this issue on latest Zed stable.

**Comment by thorerik** [comment] 2024-05-06 10:32
@arjpar If you can share your configuration, I can take a look, as the original issue isn't reproducible for me anymore in either Preview or Stable.

**Comment by arjpar** [comment] 2024-05-06 11:59
@thorerik It seems to be an issue I'm facing only with [Commit Mono](https://commitmono.com/). The character variants don't work. I think the stylistic sets do work. This is my config:
```json
{
  // [...] other settings above
  "buffer_font_family": "CommitMono",
  "buffer_font_features": {
    "ss01": true,
    "ss02": true,
    "ss03": true,
    "ss04": true,
    "ss05": true,
    "cv06": true,
    "cv07": true,
    "cv08": true
    //"ss06": true,
    //"ss07": true,
    //"ss08": true,
    //"calt": true,
    // "liga": true
  },
// [...] other settings below
```

Let me know if you have any questions.

**Comment by thorerik** [comment] 2024-05-07 08:31
@arjpar It works fine for me:
<img width="1078" alt="image" src="https://github.com/zed-industries/zed/assets/219796/f1ff7217-aba9-405f-aae2-fef8b03f0eef">

**Comment by arjpar** [comment] 2024-05-07 09:09
@thorerik Yes, the stylistic sets work fine (ligatures), but the character variants aren't working.
This is what it's (character variants) supposed to look like: (dotted 0, alt 6 & 9, and alt italic)
<img width="337" alt="image" src="https://github.com/zed-industries/zed/assets/41452613/f9992238-cddb-4225-8f24-0841afe9e3f4">

**Comment by thorerik** [comment] 2024-05-07 10:09
@arjpar the issue here is about stylistic sets, perhaps open a new issue regarding CVs, since nobody from the team seem to monitor this issue.

**Comment by Moshyfawn** [comment] 2024-05-08 03:23
I'm going to close this issue as it doesn't seem to be present in the latest Stable [`0.133.7`](https://zed.dev/releases/stable/0.133.7) version of Zed. Let me know if it's a mistake and we can reopen it.

**Closed by Moshyfawn** 2024-05-08 03:23 UTC
Labels: defect, font
