### ISSUE TITLE
Text and icons are all disappeared

### ISSUE THREAD

**Issue by neebneeba** [zed-industries/zed#15477] opened 2024-07-30 11:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After few minutes of break I returned to my laptop and unlock it to write some code. But then text and icons are all disappeared.

### Environment

![Screenshot_20240730_201814](https://github.com/user-attachments/assets/ab3cac2f-cf80-4de7-b5df-5f7fa9b6d9a1)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot_20240730_201031](https://github.com/user-attachments/assets/5f25f54b-1d30-4027-b45d-45ff31da212c)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-30T16:55:50.513564835+09:00 [INFO] ========== starting zed ==========
2024-07-30T16:55:51.046889972+09:00 [INFO] perform;
2024-07-30T16:55:51.047530581+09:00 [INFO] read_command;
2024-07-30T16:55:51.049240468+09:00 [INFO] read_command;
2024-07-30T16:55:51.051547629+09:00 [INFO] socket reader;
2024-07-30T16:55:51.052684237+09:00 [INFO] new;
2024-07-30T16:55:51.053852316+09:00 [INFO] keep_updated;
2024-07-30T16:55:51.061712471+09:00 [INFO] Opening main db
2024-07-30T16:55:51.073480164+09:00 [INFO] Using git binary path: None
2024-07-30T16:55:51.185481901+09:00 [INFO] extensions updated. loading 3, reloading 0, unloading 0
2024-07-30T16:55:51.217672871+09:00 [INFO] set environment variables from shell:/usr/bin/bash, path:/home/dark/.local/share/gem/ruby/3.0.0/bin:/home/dark/android-studio/bin:/home/dark/flutter/bin:/home/dark/.nvm/versions/node/v20.14.0/bin:/home/dark/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2024-07-30T16:55:51.242935279+09:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-30T16:55:51.24301263+09:00 [INFO] Opening main db
2024-07-30T16:55:51.248080298+09:00 [INFO] perform;
2024-07-30T16:55:51.248193682+09:00 [INFO] read_command;
2024-07-30T16:55:51.248247627+09:00 [INFO] read_command;
2024-07-30T16:55:51.248401463+09:00 [INFO] socket reader;
2024-07-30T16:55:51.256107376+09:00 [INFO] new;
2024-07-30T16:55:51.25669301+09:00 [INFO] keep_updated;
2024-07-30T16:55:51.257756329+09:00 [INFO] set status on client 0: Authenticating
2024-07-30T16:55:51.257926505+09:00 [INFO] perform;
2024-07-30T16:55:51.257949329+09:00 [INFO] read_command;
2024-07-30T16:55:51.257966249+09:00 [INFO] read_command;
2024-07-30T16:55:51.258010534+09:00 [INFO] socket reader;
2024-07-30T16:55:51.25851116+09:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-07-30T16:55:51.263580101+09:00 [INFO] new;
2024-07-30T16:55:51.264153135+09:00 [INFO] keep_updated;
2024-07-30T16:55:51.304345002+09:00 [INFO] Enabling Vulkan Portability
2024-07-30T16:55:51.304369227+09:00 [INFO] Enabling color space support
2024-07-30T16:55:51.362569064+09:00 [INFO] Adapter "NVIDIA GeForce GTX 1650 Ti with Max-Q Design"
2024-07-30T16:55:51.362604606+09:00 [INFO] No ray tracing extensions are supported
2024-07-30T16:55:51.54135644+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.541386825+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.590640696+09:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-30T16:55:51.590668164+09:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-30T16:55:51.590679265+09:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-30T16:55:51.627029891+09:00 [INFO] set status on client 192055: Connecting
2024-07-30T16:55:51.630930453+09:00 [INFO] Opening main db
2024-07-30T16:55:51.671309756+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.671429476+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.695182637+09:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-30T16:55:51.708523874+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.708557941+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.720989292+09:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-07-30T16:55:51.727311907+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.727334879+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.773843883+09:00 [INFO] Opening main db
2024-07-30T16:55:51.867354831+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.867523008+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.908985273+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.90915427+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.952779876+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.95291215+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:51.986013701+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:51.986169949+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.001830483+09:00 [INFO] Node runtime install_if_needed
2024-07-30T16:55:52.003142774+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.00316654+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.027783296+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.027816221+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.047123148+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.047148873+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.062001776+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.062028778+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.076696283+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.07672069+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.091496453+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.091528174+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.106576408+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.106602347+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.128950533+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.12899235+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.164001742+09:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-30T16:55:52.165678356+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T16:55:52.165782183+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T16:55:52.303102092+09:00 [INFO] Initializing default prettier with plugins {}
2024-07-30T16:55:52.303170509+09:00 [INFO] starting language servers for Rust: rust-analyzer
2024-07-30T16:55:52.3031833+09:00 [INFO] starting language server "rust-analyzer", path: "/home/dark/Tutorials/rustlings", id: 1
2024-07-30T16:55:52.303605479+09:00 [INFO] Initializing default prettier with plugins {}
2024-07-30T16:55:52.303621622+09:00 [INFO] starting language servers for Rust: rust-analyzer
2024-07-30T16:55:52.314559175+09:00 [INFO] fetching latest version of language server "rust-analyzer"
2024-07-30T16:55:52.876351392+09:00 [INFO] starting language server. binary path: "/home/dark/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/dark/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-30T16:55:52.910258595+09:00 [INFO] add connection to peer
2024-07-30T16:55:52.910285452+09:00 [INFO] add_connection;
2024-07-30T16:55:52.910321341+09:00 [INFO] waiting for server hello
2024-07-30T16:55:52.95323592+09:00 [INFO] got server hello
2024-07-30T16:55:52.953676727+09:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 460, id: 416362 })
2024-07-30T16:55:52.953700889+09:00 [INFO] set status on client 192055: Connected { peer_id: PeerId { owner_id: 460, id: 416362 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-07-30T16:55:53.016341063+09:00 [INFO] downloading language server "rust-analyzer"
2024-07-30T16:55:53.016743388+09:00 [INFO] starting language server. binary path: "/home/dark/.local/share/zed/languages/rust-analyzer/rust-analyzer-2024-07-29", working directory: "/home/dark/Tutorials/rustlings", args: []
2024-07-30T16:55:53.48192568+09:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-30T07:55:53.468Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-30T07:55:53.468Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-30T16:55:53.482186885+09:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "7e5ca8e7-985a-498a-a356-3bd58b2c60f3",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-30T16:55:53.543660569+09:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-30T07:55:53.502Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-30T07:55:53.502Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-07-30T16:56:28.545027746+09:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-30T16:56:28.55408409+09:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-30T16:56:28.557256016+09:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-30T16:56:28.562788935+09:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-07-30T16:56:32.539263526+09:00 [INFO] perform;
2024-07-30T16:56:32.539328581+09:00 [INFO] read_command;
2024-07-30T16:56:32.539364621+09:00 [INFO] read_command;
2024-07-30T16:56:32.539458335+09:00 [INFO] socket reader;
2024-07-30T16:56:32.553130066+09:00 [INFO] new;
2024-07-30T16:56:32.555620066+09:00 [INFO] keep_updated;
2024-07-30T17:08:39.503516935+09:00 [INFO] Initializing default prettier with plugins {}
2024-07-30T17:08:39.503751+09:00 [INFO] starting language servers for Markdown: 
2024-07-30T17:08:44.951524687+09:00 [INFO] new;
2024-07-30T17:08:44.954325242+09:00 [INFO] keep_updated;
2024-07-30T17:08:44.954480812+09:00 [INFO] new;
2024-07-30T17:09:51.196320827+09:00 [INFO] new;
2024-07-30T17:09:51.19749499+09:00 [INFO] keep_updated;
2024-07-30T17:09:51.197622823+09:00 [INFO] new;
2024-07-30T17:09:53.935756354+09:00 [INFO] new;
2024-07-30T17:09:53.937438326+09:00 [INFO] keep_updated;
2024-07-30T17:09:53.937615609+09:00 [INFO] new;
2024-07-30T17:48:09.378778309+09:00 [INFO] Initializing default prettier with plugins {}
2024-07-30T17:48:09.379062931+09:00 [INFO] starting language servers for Rust: rust-analyzer
2024-07-30T19:59:02.664877602+09:00 [ERROR] connection error: delay between messages too long
2024-07-30T19:59:02.665027024+09:00 [INFO] set status on client 192055: ConnectionLost
2024-07-30T19:59:02.665671967+09:00 [INFO] set status on client 192055: Reauthenticating
2024-07-30T19:59:02.665834771+09:00 [INFO] set status on client 192055: Reconnecting
2024-07-30T19:59:02.974149517+09:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-07-30T19:59:03.552360695+09:00 [INFO] perform;
2024-07-30T19:59:03.552541778+09:00 [INFO] read_command;
2024-07-30T19:59:03.552678815+09:00 [INFO] read_command;
2024-07-30T19:59:03.552934786+09:00 [INFO] socket reader;
2024-07-30T19:59:03.591669347+09:00 [INFO] add connection to peer
2024-07-30T19:59:03.591893352+09:00 [INFO] add_connection;
2024-07-30T19:59:03.592094456+09:00 [INFO] waiting for server hello
2024-07-30T19:59:03.592687963+09:00 [INFO] got server hello
2024-07-30T19:59:03.592820569+09:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 1 }, peer id: PeerId { owner_id: 460, id: 505870 })
2024-07-30T19:59:03.594377622+09:00 [INFO] set status on client 192055: Connected { peer_id: PeerId { owner_id: 460, id: 505870 }, connection_id: ConnectionId { owner_id: 0, id: 1 } }
2024-07-30T20:10:20.568018823+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T20:10:20.578989127+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T20:10:21.892647444+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T20:10:21.892726377+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T20:17:11.646157794+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T20:17:11.646305776+09:00 [WARN] Unable to forbid exclusive full screen
2024-07-30T20:17:13.454054209+09:00 [INFO] Using surface present mode MAILBOX
2024-07-30T20:17:13.454199266+09:00 [WARN] Unable to forbid exclusive full screen

</pre></details>

**Comment by notpeter** [comment] 2024-07-30 15:00
Duplicate of:
- https://github.com/zed-industries/zed/issues/12827

**Closed by notpeter** 2024-07-30 15:00 UTC
Labels: defect, triage, admin read
