### ISSUE TITLE
Visual display support is not available in terminal

### ISSUE THREAD

**Issue by Jinx-FX** [zed-industries/zed#17481] opened 2024-09-06 04:53 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

I use a visualization tool like lazygit in the terminal, and I get this happening
![image](https://github.com/user-attachments/assets/2a7997aa-7136-4952-8ceb-b0902138edb2)

And QR code so on，it can't be used
![image](https://github.com/user-attachments/assets/293e3e23-e027-499b-92f4-0ec072c77398)

### Environment

![image](https://github.com/user-attachments/assets/5a7215f9-0cba-4aa3-b091-4808450a8c60)
0c74f4e0ca0bf1641b31a1dfc58784654337dd28

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-06 17:04
This is a duplicate of:
- #15542 

Basically there's two things going one. One `Zed Plex Mono` has some issues not present in upstream `IBM Plex Mono`.  As a workaround you can install `IBM Plex Mono` or [`BlexMono Nerd Font Mono`](https://www.nerdfonts.com/font-downloads) (IBM Plex Mono + Nerd Font Glyphs) and they will look much better.

Two, you probably want to configure [terminal `line_height`](https://zed.dev/docs/configuring-zed#terminal-line-height) in your settings:
```json
{
  "terminal": {
    "font_family": "BlexMono Nerd Font Mono",
    "line_height": "standard"
  }
}
```

**Closed by notpeter** 2024-09-06 17:04 UTC
Labels: defect, triage, admin read
