### ISSUE TITLE
Can't open a context menu on selected text

### ISSUE THREAD

**Issue by alexis-martel** [zed-industries/zed#4583] opened 2023-07-28 02:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to open a context menu while having text selected doesn't provide a menu of text-related actions (such as the one from TextEdit shown below): it only deselects the text and opens the same menu that shows up upon right- or control-clicking on any location within the buffer.

**To reproduce:**
1. Select some text in a buffer;
2. Open up the context menu (by either right-clicking or control-clicking on the selected text).

### Environment

Zed: v0.97.4 (preview)
OS: macOS 13.5.0
Memory: 8 GiB
Architecture: x86_64
**AND**
Zed: v0.96.3 (stable)
OS: macOS 13.5.0
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="262" alt="image" src="https://github.com/zed-industries/community/assets/83471846/bfc80363-3b08-4325-80de-6268fdea784a">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 07:03
I'm not able to reproduce this in current Zed - I'm able to select text and open the context menu, without losing the selection., I'm going to close this issue out. If you run into this again, feel free to open a new issue!

<img width="615" alt="SCR-20240728-dmvw" src="https://github.com/user-attachments/assets/f616f244-ec49-4e3d-afbe-7818f2581b9d">

**Closed by JosephTLyons** 2024-07-28 07:03 UTC
Labels: enhancement, editor, popovers
