### ISSUE TITLE
Repeating indent doesn't select the same portion of text in Vim mode

### ISSUE THREAD

**Issue by janko** [zed-industries/zed#12351] opened 2024-05-27 12:31 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In Vim, when I select a portion of text in visual line mode and press `<`/`>`, I then often use "." to repeat the indent/outdent on the same text multiple times. E.g. in Ruby if I want to outdent by 4 spaces, I would press `<` (2 spaces) and then `.` once (2 more spaces).

In Zed, this doesn't appear to work correctly. When I hit `.` after `<`/`>`, it indents/outdents a different part of text than what I initially selected.

I would be fine with indenting with `Tab` and outdenting `Shift-Tab`, but those don't appear to work in Vim's virtual line mode. It would be nice if it did 🙂 

### Environment

Zed: v0.136.2 (Zed)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Here I pressed `<` and then `...`.

https://github.com/zed-industries/zed/assets/795488/d651699f-2a6f-4fad-91d1-afbc6dda4494

**Comment by MaxThom** [comment] 2024-05-30 03:31
+1

**Comment by chrisvander** [comment] 2024-06-05 20:07
Good workaround for now would be to use `cmd {` and `cmd }` for indenting/un-indenting, which I just discovered while trying to figure out why `4<` didn't work.

**Comment by Thomascountz** [comment] 2024-06-06 10:01
> Good workaround for now would be to use `cmd {` and `cmd }` for indenting/un-indenting, which I just discovered while trying to figure out why `4<` didn't work.

`⌘ + }` and `⌘ + {` will outdent and indent visual-selected lines, similar to `>` and `<`. However, they're not repeated  when using the repeat command (`.`). I think it's because they are `editor` commands as opposed to `vim` commands.

I think the problem is that in visual mode, the vim command for `>` and `<` is only outdent/indent. But once in normal mode, when the repeat command is used (`.`), the command is first `vim::PushOperator`, and _then_ outdent/indent. I'm thinking that the `vim::PushOperator` causes the cursor to first move, and then the outdent/indent happens.

```json
// Vim default keymap
[
  //...
  {
    "context": "Editor && vim_mode == visual && !VimWaiting && !VimObject",
    "bindings": {
        ">": "vim::Indent",
        "<": "vim::Outdent",
    }
  },
  {
    "context": "Editor && vim_mode == normal && vim_operator == none && !VimWaiting",
    "bindings": {
      ".": "vim::Repeat",
      ">": ["vim::PushOperator", "Indent"],
      "<": ["vim::PushOperator", "Outdent"],
}
```

**Comment by Moshyfawn** [comment] 2024-06-08 16:27
Please let us know if the attached PR has resolved the issue for you.

**Comment by janko** [comment] 2024-06-08 17:28
@Moshyfawn Would that require building Zed from source? I tried the latest preview now (0.139.3), but the behavior of repeating indent/outdent still appears to be the same.

**Comment by mrnugget** [comment] 2024-06-10 06:56
Yeah, the commit https://github.com/zed-industries/zed/commit/2f057785f7da4faf05af85dc667f8bba83ce027a is not in a release yet. Will go into next Preview release on Wednesday. Stable the week after.

**Comment by JosephTLyons** [comment] 2024-06-12 21:50
The feature is now in today's preview ([0.140-pre](https://zed.dev/releases/preview/0.140.0)). I'm going to optimistically close this out, but feel free to ping us to reopen if something isn't correct.

**Closed by JosephTLyons** 2024-06-12 21:50 UTC
Labels: defect, needs info / awaiting response, vim, editor
