### ISSUE TITLE
ERROR blade_graphics::hal::init] Instance extension "VK_KHR_get_physical_device_properties2" is not supported

### ISSUE THREAD

**Issue by stephen-hill** [zed-industries/zed#14211] opened 2024-07-11 14:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running zed --forground gives the error

`ERROR blade_graphics::hal::init] Instance extension "VK_KHR_get_physical_device_properties2" is not supported`

Installed on a relatively clean install of Debian 12.

### Environment

```
stephen@riften:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
024-07-11T15:39:28+01:00 [INFO] ========== starting zed ==========
2024-07-11T15:39:28+01:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-07-11T15:39:28+01:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-07-11T15:39:28+01:00 [INFO] perform;
2024-07-11T15:39:28+01:00 [INFO] read_command;
2024-07-11T15:39:28+01:00 [INFO] read_command;
2024-07-11T15:39:28+01:00 [INFO] socket reader;
2024-07-11T15:39:28+01:00 [INFO] Opening main db
2024-07-11T15:39:28+01:00 [INFO] new;
2024-07-11T15:39:28+01:00 [INFO] Using git binary path: None
2024-07-11T15:39:28+01:00 [INFO] set environment variables from shell:/bin/bash, path:/home/stephen/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
2024-07-11T15:39:28+01:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-11T15:39:28+01:00 [INFO] Opening main db
2024-07-11T15:39:28+01:00 [INFO] Using Visual { id: 94, colormap: 0, depth: 32 }
2024-07-11T15:39:28+01:00 [INFO] Creating colormap 52428803
2024-07-11T15:39:28+01:00 [INFO] perform;
2024-07-11T15:39:28+01:00 [INFO] read_command;
2024-07-11T15:39:28+01:00 [INFO] read_command;
2024-07-11T15:39:28+01:00 [INFO] socket reader;
2024-07-11T15:39:28+01:00 [ERROR] Instance extension "VK_KHR_get_physical_device_properties2" is not supported
2024-07-11T15:39:28+01:00 [INFO] rebuilt extension index in 918.477µs
2024-07-11T15:39:29+01:00 [INFO] Node runtime install_if_needed
2024-07-11T15:39:36+01:00 [INFO] starting language server. binary path: "/home/stephen/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/stephen/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-11T15:39:36+01:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-11T14:39:36.775Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-11T14:39:36.775Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-11T15:39:36+01:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "0e80121d-2cd5-4727-8bf7-02f2fe77b6a0",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-11T15:39:36+01:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-11T14:39:36.805Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-11T14:39:36.805Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
```

**Comment by dong8yong8** [comment] 2024-07-11 15:14
me too

**Comment by matusbielik** [comment] 2024-07-12 02:04
same problem, Debian 12.

**Comment by stalkerg** [comment] 2024-07-12 10:52
I don't know which GPU are you using but VK_KHR_get_physical_device_properties2 is Vulkan 1.1, can you show `vulkaninfo`? 
Probably it will work with Debian Seed

**Comment by stephen-hill** [comment] 2024-07-12 10:56
@stalkerg This is on a qemu virtual machine.

![image](https://github.com/user-attachments/assets/1ea14c7e-b8ae-4a50-9e0b-55a45e3591c2)

**Comment by stalkerg** [comment] 2024-07-18 00:25
As I remember Vulkan driver for qemu still under development.

**Comment by stephen-hill** [comment] 2024-07-18 07:40
@stalkerg Thanks for the info.

**Comment by ConradIrwin** [comment] 2024-07-23 20:14
Closing this for now, as it sounds like the problem is lack of Vulkan support.

**Closed by ConradIrwin** 2024-07-23 20:14 UTC
Labels: defect, panic / crash, linux

**Comment by 0xtimsb** [comment] 2024-10-15 18:23
This worked for me: [vulkan-intel](https://archlinux.org/packages/extra/x86_64/vulkan-intel/)
