### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by SyabAhmad** [zed-industries/zed#8669] opened 2024-03-01 14:30 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Please add support for windows users.

**Comment by Moshyfawn** [comment] 2024-03-01 14:36
Duplicate of #5394

**Comment by Moshyfawn** [comment] 2024-03-01 14:37
Please make sure to +👍 the other issue to show your interest.

**Closed by Moshyfawn** 2024-03-01 14:36 UTC
Labels: enhancement, triage, admin read
