### ISSUE TITLE
Settings to control max tabs open

### ISSUE THREAD

**Issue by etkachev** [zed-industries/zed#4784] opened 2023-04-21 18:16 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have a setting in zed that allows to configure the max amount tabs that can be open.

Like in IntelliJ products, I typically set my max to 1 so my IDE can only have one tab open at a time that I'm working on. I then use the shortcut for opening recent files to navigate where else I need to if I'm working through multiple files.

Let me know what you guys think. I still have to check if there is already an open issue to allow a shortcut to open recent files.

**Comment by BuonOmo** [comment] 2024-03-09 14:50
I wanted it really badly, so here's the diff if you want to build your own zed with this integrated: https://github.com/BuonOmo/zed/compare/main...BuonOmo:zed:zentab

I think the footprint is sufficiently light that it could be considered. But I'm doubting that this setting has enough traction...

**Comment by remorses** [comment] 2024-08-03 14:11
This should help with the lsp performance right? In VSCode for example the typescript language server checks the types for all open tabs and setting a low tab limit helps keeping the language server memory usage down

**Comment by remorses** [comment] 2024-08-05 13:43
@BuonOmo why not open a PR? This setting is very important in my opinion

**Comment by BuonOmo** [comment] 2024-08-07 18:33
@remorses I could, I'm just not sure there is enough traction for it to be accepted. TBH it is not the only place in this codebase I'd like to contribute whilst not knowing if it is desired by the core team...

**Comment by remorses** [comment] 2024-08-07 19:24
I opened a PR with your diff after resolving the conflicts: https://github.com/zed-industries/zed/pull/15926

Let's see if the team agrees on the change

**Comment by remainstheday** [comment] 2024-10-08 16:28
@remorses and @BuonOmo are there any updates on this? I'd love to help push it across the finish line so we can use this setting asap.

**Comment by BuonOmo** [comment] 2024-10-09 11:56
@remainstheday I think the main issue is not the code. I could open a new PR by tomorrow. The issue is the visibility of this, it is unfortunately not a top ranking issue... Maybe if my new PR is clean enough they'll like it even though. Let's say I make it and you review it before them to be sure we're doing good work ? We could even pair up at some point, available today afternoon and tomorrow working hours GMT+1

**Comment by denis-manokhin** [comment] 2024-11-07 10:59
Any news about this feature?
This is the last thing I need to start using `zed` daily.

**Closed** 2024-12-14 04:32 UTC
Labels: enhancement, tabs, setting
