### ISSUE TITLE
Command Pallet doesn't include all available commands in Zed?

### ISSUE THREAD

**Issue by martinbliss** [zed-industries/zed#4329] opened 2023-11-25 20:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As a Zed user, I would like to be able to issue any available Zed command from the Command Pallet, even if the command is already made available in a different interface such as the menu bar. It is currently not possible (to my knowledge) to search for symbols from the Command Pallet unless you use the Go->Go To Symbol... menu option or the CMD+T shortcut. I was expecting this option to be available (on a Mac) by invoking CMD+P followed by `#(symbol name)`

### Environment

Zed: v0.113.0 (stable)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/community/assets/11949431/4dfe5d97-2328-4354-96d5-03e8ec9ce6b7)
Above is an example of the Go to Symbol in Project feature which works as expected from the menu or using the CMD+T shortcut (VSCode key map).

![image](https://github.com/zed-industries/community/assets/11949431/df4ec7c4-b465-4317-a9ab-8692cd4498df)
Above is an example of using the same `#` prefix as found in VSCode for doing a symbol search from the command pallet.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment] 2024-11-05 23:04
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/14249
- #15896

**Closed by notpeter** 2024-11-05 23:04 UTC
Labels: enhancement, file finder
