### ISSUE TITLE
Tooltip is obscured by menu.

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/zed#4976] opened 2023-03-09 01:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

<img width="1680" alt="Snipaste_2023-03-09_09-32-03" src="https://user-images.githubusercontent.com/40336192/223892461-937869b4-fb0d-40ae-b4b9-511f15afaa9a.png">

### Environment

Zed: v0.75.2 (stable)
OS: macOS 13.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment] 2024-03-12 18:14
I can't seem to reproduce this in Zed Nightly:

<img width="218" alt="Screenshot 2024-03-12 at 2 12 30 PM" src="https://github.com/zed-industries/zed/assets/1486634/3de2b8d6-d7bf-4648-8e21-8a1ac29d1645">

Given that this was reported on an old version of Zed and since we've completed reworked our approach to laying out these kinds of elements in #9012, so I'm going to close this out.

**Closed by maxdeviant** 2024-03-12 18:14 UTC
Labels: defect, tooltips

**Comment by Moshyfawn** [comment] 2024-03-12 18:16
I think it works as intended now.
