### ISSUE TITLE
Scroll completely broken (Linux Mint)

### ISSUE THREAD

**Issue by ChristoferMendes** [zed-industries/zed#14089] opened 2024-07-10 19:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In a fresh install of Zed (Stable), when opening the editor, the scroll is not working at all.

Even clicking in the scrollbar does not work.

### Environment

Linux Mint

AMD Ryzen 7 4800H with Radeon Graphics
Geforce GTX 1650 Ti mobile

**Comment by ChristoferMendes** [comment] 2024-07-11 11:57
I'm not sure if it's related, but after reading issue #14085, I noticed that @aminya mentioned removing a file while working on the Linux builds (which is also what I'm doing). Following this, I ran rm -rf ~/.config/zed/keymaps.json, and the scrolling issue stopped occurring.

However, the error of CTRLs does not worked for me :(

**Comment by ChristoferMendes** [comment] 2024-07-12 11:56
> ### Check for existing issues
> 
>     * [x]  Completed
> 
> 
> ### Describe the bug / provide steps to reproduce it
> 
> In a fresh install of Zed (Stable), when opening the editor, the scroll is not working at all.
> 
> Even clicking in the scrollbar does not work.
> ### Environment
> 
> Linux Mint
> 
> AMD Ryzen 7 4800H with Radeon Graphics Geforce GTX 1650 Ti mobile

I'm having this issue while using AnyDesk only

**Comment by krial057** [comment] 2024-08-02 06:43
I had the same issue using Linux Mint and a remote desktop tool.
It still worked before the pull request #11110 got merged. I believe the issue is that remote desktop tools are still using the button press event detail 4,5 to perform the scrolling and to not provide scrolling over an inputmotion event. 
I think a fallback to the previous scrolling method would be a possible fix.

**Comment by donjan** [comment] 2024-08-02 16:05
OP doesn't specify remote control tools, but the last two commenters do. So I'll attach here, but please advise if the devs prefer a new issue.

Zed 0.146.4 on Ubuntu 22.04.4, scrolling works natively, which is nice.
Scrolling as an input-leap client (same protocol as Synergy and Barrier) does not work. Toggling "relative mouse moves" in input-leap has no effect, other options don't seem relevant.
To me, this is a hard requirement for trying out Zed any further.

**Comment by ninbura** [comment] 2024-08-06 17:15
I'm unable to scroll any pane in the app that has a scroll bar on Ubuntu 24.04. I use Synergy, so I assumed that was the problem at first. But even when I directly connect my mouse to the computer I still can't scroll.

I've had this bug/issue since initial release on Ubuntu 24.04, but thought I'd give it aw few weeks before opening / looking into existing GitHub issues. Tested with the latest stable and preview builds as of today, still a problem.

**Comment by ninbura** [comment] 2024-08-06 17:20
> I'm unable to scroll any pane in the app that has a scroll bar on Ubuntu 24.04. I use Synergy, so I assumed that was the problem at first. But even when I directly connect my mouse to the computer I still can't scroll.

> I had the same issue using Linux Mint and a remote desktop tool. It still worked before the pull request #11110 got merged. I believe the issue is that remote desktop tools are still using the button press event detail (4&5) to perform the scrolling and do not provide scrolling over an _inputmotion_ event. I think a fallback to the previous scrolling method would be a possible fix.

Oh... looks like if I exit Synergy, connect a mouse directly to the system, and then restart Zed scrolling works. Thanks for the hint. This will also meaningfully prevent me from using Zed as Synergy is my primary method of controlling the system in question.

**Comment by donjan** [comment] 2024-08-09 15:00
Great news for Wayland users!
Scrolling on a Waynergy client from a input-leap host seems to work.
(Zed also updated itself to 0.146.5 in the meantime, but I doubt the git blame toggle fix in that patch is relevant)

**Comment by atljoseph** [comment] 2024-09-14 18:05
I installed latest release in Zorin (basically Ubuntu). Same. Can’t scroll in code files. Can’t scroll in dropdowns. Can scroll in assistant. Can scroll in right click context menu. Just can’t scroll. Unusable. Arrow keys work for some scrolling.

**Comment by mash-97** [comment] 2024-09-16 05:57
I'm also facing the same, just installed on my Ubuntu 22.04.4 LTS. Scrolling not working.

**Closed** 2024-10-01 07:14 UTC
Labels: defect, linux, scroll / scrollbar
