### ISSUE TITLE
Cannot Save Changes to privileged files Opened with sudo in Zed

### ISSUE THREAD

**Issue by anishgowda21** [zed-industries/zed#19843] opened 2024-10-28 17:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I cannot save changes when opening and editing privileged files. Such as ```/etc/hosts```.

Below are the steps to reproduce it.

```sudo zed /etc/hosts```

After making edits, I try to save the file, but nothing happens even if I do ```cmd+s``` or ```file->save``` even when we close the file without saving and click save in the alert the file will not be saved. It seems to be a permissions issue by looking at the logs, despite opening the file with sudo.

### Environment

Zed: v0.158.2 (Zed)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="851" alt="image" src="https://github.com/user-attachments/assets/11012005-ea35-4c88-916f-04e15b00d01c">
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/2c504877-8904-4e0d-b80a-43cf76560b0d">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[zed_edit.log](https://github.com/user-attachments/files/17546292/zed_edit.log)

</pre></details>

**Comment by notpeter** [comment] 2024-10-28 19:03
Duplicate of:
- #13259

**Closed by notpeter** 2024-10-28 19:03 UTC
Labels: defect, triage, admin read
