### ISSUE TITLE
Rename Symbol & Find All References both don't show up at all

### ISSUE THREAD

**Issue by wottpal** [zed-industries/zed#16781] opened 2024-08-23 20:53 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Neither "Rename Symbol" nor the "Find All References" actions shows up for me (tried via right-click & shortcut). Just nothing happens. Tried in TypeScript (`.tsx`) and Python (`.py`) files.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

**Comment by wottpal** [comment] 2024-08-23 20:56
Seems to be related to the biome.js extension 🤔

In my settings, if i replace:
```
  "language_servers": ["biome", "..."],
```
with:
```
  "language_servers": ["...", "biome"],
```

… It seems to work again 🤔 Wonder wether if this has any other implications. cc @luckydye

**Comment by luckydye** [comment] 2024-08-23 21:13
Prob. duplicate of https://github.com/zed-industries/zed/issues/15917 / https://github.com/zed-industries/zed/issues/16619

**Comment by notpeter** [comment] 2024-08-27 20:30
Closing as duplicate of 
- https://github.com/zed-industries/zed/issues/15917

**Closed by notpeter** 2024-08-27 20:30 UTC
Labels: defect, triage, admin read
