### ISSUE TITLE
Rust Language Server Stalling / Crashing on Mac

### ISSUE THREAD

**Issue by markusmoenig** [zed-industries/zed#17739] opened 2024-09-12 04:58 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Rust Language server becomes unresponsive on Mac. This happened in a previous build, but was fixed in one of the last builds. But with Zed 0.152.3 it happens again.
I cannot work for more than 2 minutes without the language server not reacting anymore.

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 14.6.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by DylanVerstraete** [comment] 2024-09-12 13:57
+1

**Comment by SomeoneToIgnore** [comment] 2024-09-12 16:11
Duplicate of https://github.com/zed-industries/zed/issues/17376

**Closed by SomeoneToIgnore** 2024-09-12 16:11 UTC
Labels: defect, triage, admin read
