### ISSUE TITLE
Incorrect file display after renaming the root directory

### ISSUE THREAD

**Issue by Oleksii-LnxUsr** [zed-industries/zed#10225] opened 2024-04-06 05:27 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

After renaming the project's root directory, several issues arose:

File and directory display:

After renaming the root directory, nested files and directories stopped appearing in the sidebar menu.
Some files and directories that were located in the renamed directory are no longer visible in the sidebar panel.

Creating a new directory with the old name:

It was noticed that after renaming the project, a new directory with the previous project name was created. Parts of the project are located in this directory.

Steps to reproduce the problem:

Open the project in the IDE.
Rename the project's root directory using Finder (zed does not allow renaming the root directory).

Expected behavior:

After renaming the root directory, all files and folders should be correctly displayed and reflect the changes in the root directory's name.

### Environment

Sonoma 14.4
Apple M2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/111213562/e03088f2-d720-4c95-a524-5a9349969dac

this is what it looks like

**Comment by JosephTLyons** [comment] 2024-04-08 04:40
Hey @Oleksii-LnxUsr,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7923

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-08 04:40 UTC
Labels: defect, project panel
