### ISSUE TITLE
Failed to load image: Invalid symbol 10, offset 72

### ISSUE THREAD

**Issue by cthed2** [zed-industries/zed#18086] opened 2024-09-19 16:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The R code executes fine, I can't view images generated by ggplot2. Instead, I receive the following error message.
Settings:

  "jupyter": {
    "kernel_selections": {
      "r": "ark"
    }
  }

is there any solution?

### Environment

Zed: v0.154.0 (Zed Dev c3f47b8040a83b6414b8a28399628370fb7224f4)
OS: Windows 10.0.22631
Memory: 31.7 GiB
Architecture: x86_64
GPU: Intel(R) RaptorLake-S Mobile Graphics Controller || Intel Corporation || Intel driver

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![imagen](https://github.com/user-attachments/assets/1c4b7b1b-540b-48af-82d2-109ca1218baf)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-19T11:07:07.461096-05:00 [ERROR] Error { code: HRESULT(0x80070490), message: "No se ha encontrado el elemento." }
</pre></details>

**Comment by notpeter** [comment] 2024-09-19 20:46
Rather than open a new issue, I'm going to close this a duplicate of:
- https://github.com/zed-industries/zed/issues/16330

And reopen that.

**Closed by notpeter** 2024-09-19 20:46 UTC
Labels: defect, triage, admin read
