### ISSUE TITLE
Simple non-macOS-native full-screen mode like in SublimeText

### ISSUE THREAD

**Issue by davidvdw** [zed-industries/zed#13687] opened 2024-06-30 15:42 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great to have a simple full-screen mode like the one in SublimeText.
The full screen stays in the same desktop space when this mode is activated.

The setting in SublimeText is:
`"use_simple_full_screen": true`

Another application that does this is iTerm2.
Switching between these applications happens smoothly and quickly when not using new desktop spaces.

**Comment by notpeter** [comment] 2024-07-01 13:40
I believe this is a duplicate of
- https://github.com/zed-industries/zed/issues/4382

**Comment by davidvdw** [comment] 2024-07-01 19:43
This is not a duplicate of #4382 and has nothing to do with Zen mode in VScode.

Zed and VScode's have the same default behavior in full-screen mode. This behavior is not only annoying but also time-consuming. SublimeText, on the other hand, handles this correctly in "simple full-screen mode."

The advantages of this feature:
- go in and out full screen in a quick and snappy way
- switch applications in the same desktop space while staying in full screen mode

I hope you can re-open this.

**Comment by mrnugget** [comment] 2024-07-04 12:43
I think this is a duplicate of https://github.com/zed-industries/zed/issues/7257 — right, @davidvdw?

**Closed** 2024-08-08 13:46 UTC
Labels: enhancement, workspace, macOS
