### ISSUE TITLE
Buggy rename from sidebar

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4551] opened 2023-08-06 03:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Reproduce steps:

1. Run "workspace::NewFile" by shortcut or command box. (DON'T create the new file from sidebar)
2. Run "workspace::Save" to save the file immediately with name `test.hml` in the Finder dialog.
3. Rename the file to `test.html` in the sidebar using the right click menu and confirm.

Observation:

1. The file name is renamed to `test.html` in the sidebar.
2. The opened file / buffer is not rename to `test.html`, still `test.tml`.
3. Write some test in the opened buffer `test.hml` and save, a `test.hml` is created in the sidebar.
4. Clicking `test.html` from sidebar will not open the file `test.html`.
5. Close file / buffer `test.hml`, click `test.html` and an empty file is opened.

Note that if the file `test.hml` is created from sidebar in reproduce steps 1. The issue does not happen.

### Environment

Zed: v0.98.1 (preview)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxdeviant** [comment] 2024-03-12 19:39
I can't reproduce this in the latest Zed.

Since this was reported against a version of Zed that predates the GPUI 2 rewrite, I'm going to close it out.

**Closed by maxdeviant** 2024-03-12 19:39 UTC
Labels: defect, workspace
