### ISSUE TITLE
bug(win): modules not found for multiple languages

### ISSUE THREAD

**Issue by vipexv** [zed-industries/zed#19119] opened 2024-10-12 12:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Svelte/TSX/Tailwind LSP's so far aren't working for me on Win 11, this has been an occurring issue for awhile now that i reported a bit ago and no solution was found.

### Environment

Zed: v0.153.0 (Zed Dev)
OS: Windows 10.0.22631
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 560.81

### If applicable, attach your Zed.log file to this issue.

Zed-logs Gist: https://gist.github.com/174efe724b8a6435c383da812f7b0359.git

**Comment by SomeoneToIgnore** [comment] 2024-10-12 12:52
Duplicate of https://github.com/zed-industries/zed/issues/12013

**Closed by SomeoneToIgnore** 2024-10-12 12:52 UTC
Labels: defect, triage, admin read
