### ISSUE TITLE
Failed to open file: stream did not contain valid UTF-8.

### ISSUE THREAD

**Issue by CurtisLeeBolin** [zed-industries/zed#15656] opened 2024-08-01 21:07 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Failed to open file
stream did not contain valid UTF-8. Please try again.

The file opens fine with Pulsar and other text editors.
[html.tar.gz](https://github.com/user-attachments/files/16461890/html.tar.gz)

I imagine this old file was opened by some weird text editor in the past that caused this problem, but I know you will want to find a way to work around this to get it to open in Zed.

### Environment

Zed: v0.147.1 (Zed Preview)
OS: Linux Wayland arch unknown
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) HD Graphics 530 (SKL GT2) || Intel open-source Mesa driver || Mesa 24.1.4-arch1.2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-01 21:36
Hi! 👋  This is a known limitation of Zed.
We currently only support editing valid UTF-8.

If you don't know which encoding your file is using, `file -I` can usually tell.
And then you can use iconv to convert. For example:

```
# file -I _RegForm.html                                           
_RegForm.html: text/html; charset=iso-8859-1
# iconv -f iso-8859-1 -t UTF-8 _RegForm.html > _RegForm_fixed.html
```

Duplicate of: 
- https://github.com/zed-industries/zed/issues/9833

**Closed by notpeter** 2024-08-01 21:36 UTC
Labels: defect, triage, admin read

**Comment by CurtisLeeBolin** [comment] 2024-08-02 12:08
Understood.  Thank you, @notpeter.
