### ISSUE TITLE
White spaces are misplaced in Russian text (`"show_whitespaces": "selection"`)

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#10332] opened 2024-04-09 19:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have set Zed to show white spaces on selection: `"show_whitespaces": "selection"`. Today I noticed, that whitespaces are misplaced in Russian text: 

<img width="517" alt="Снимок экрана 2024-04-09 в 22 43 49" src="https://github.com/zed-industries/zed/assets/230824/70732db2-8162-4f2e-8580-f3d6a373bb42">

Once a saw this issue in Latin text as well, but can not reproduce again.

Here is the text:

```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без заметных изменений пять веков, но и перешагнул в электронный дизайн. Его популяризации в новое время послужили публикация листов Letraset с образцами Lorem Ipsum в 60-х годах и, в более недавнее время, программы электронной вёрстки типа Aldus PageMaker, в шаблонах которых используется Lorem Ipsum.
```

### Environment

Zed: v0.130.3 (Zed Preview)
OS: macOS 12.7.4
Memory: 32 GiB
Architecture: x86_64

**Comment by jansol** [comment] 2024-04-09 20:24
If you look closely at the russian text you can see that the whitespace dots are there but their positions are all over the place: for example on the first line there's one in the hole of the `это`.

**Comment by VKondakoff** [comment] 2024-04-09 20:26
Exactly! Thanks for noticing. Just renaming the report.

**Comment by jansol** [comment] 2024-04-09 20:30
Could you also add what font you are using as your buffer font? It might be related to that...

**Comment by VKondakoff** [comment] 2024-04-09 20:33
Don't think so, as the other editors using the same font are not displacing the white spaces:

<img width="526" alt="Снимок экрана 2024-04-09 в 23 32 46" src="https://github.com/zed-industries/zed/assets/230824/7523695c-e10f-4173-ad39-90b2515c7037">

The font is MonoLisa.

**Comment by ConradIrwin** [comment] 2024-04-10 21:58
I suspect this is because the whitespace indices are set in terms of code-points, but zed internally maintains indices in terms of utf-8 bytes.

A minimal reproduction is: `ßß ` which shows the space dot under the second ß instead of at the end.

**Comment by nuno-am** [comment] 2024-04-22 00:21
Apologies in advance for potentially hijacking this thread.

This might not be a problem just for Cyrillic characters.
As you can see from the attached screenshot, there are several other characters under the latin alphabet that can cause this to happen. From the attached screenshot, accent characters and the `ç` character break the whitespace indicators:
<img width="579" alt="Screenshot 2024-04-22 at 01 15 35" src="https://github.com/zed-industries/zed/assets/99328312/25e6278d-0c01-4fa0-9f8e-8d4dac6cc419">

As soon as these characters are removed, it behaves normally:
<img width="579" alt="Screenshot 2024-04-22 at 01 17 20" src="https://github.com/zed-industries/zed/assets/99328312/62bae2ef-aefc-4a4c-a0c2-31b512b57e9c">

No custom font settings are being applied on my instance.

**Comment by SomeoneToIgnore** [comment] 2024-04-22 05:36
It is not even about the languages, as any non-single-whitespace symbol may offset, consider `alt-shift--` long hyphen:

```
hello — goodbye
hello - goodbye
```

<img width="272" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/99356869-9454-4650-aae8-b352e2064eaa">

-----------------

The culprit seems to be there:

https://github.com/zed-industries/zed/blob/e1685deb29851a2e9e65a6a45bb9370b8d3e66c4/crates/editor/src/element.rs#L3294-L3319

and most probably offsets are wrong in this code, but that needs further investigation.

**Comment by bkircher** [comment] 2024-05-25 09:51
Just checked with main branch: this is fixed with https://github.com/zed-industries/zed/pull/12211 ❤️

**Comment by ConradIrwin** [comment] 2024-05-28 02:46
Thanks for confirming!

**Closed by ConradIrwin** 2024-05-28 02:46 UTC
Labels: defect, internationalization, font
