### ISSUE TITLE
Support for loongarch64

### ISSUE THREAD

**Issue by Qinka** [zed-industries/zed#12537] opened 2024-05-31 15:33 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Is there any plan to support loognarch64-unknown-linux-gnu.

I tried to compile zed on loongarch64 machine, but `cranelift-codegen v0.106.0` reported it does not support loongarch.

**Comment by maxdeviant** [comment] 2024-05-31 15:38
> I tried to compile zed on loongarch64 machine, but `cranelift-codegen v0.106.0` reported it does not support loongarch.

It sounds like support for loongarch64 would need to be added upstream, if `cranelift-codegen` does not support it.

**Comment by someone13574** [comment] 2024-05-31 18:19
Duplicate of https://github.com/zed-industries/zed/issues/12248

**Closed** 2024-06-01 07:24 UTC
Labels: enhancement, platform support
