### ISSUE TITLE
allow only formatting changes

### ISSUE THREAD

**Issue by hferreiro** [zed-industries/zed#19282] opened 2024-10-16 14:20 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

A common guideline for projects is to use formatting tooling but apply it only to what has been changed.

**Comment by notpeter** [comment] 2024-10-16 15:52
Duplicate of:
- https://github.com/zed-industries/zed/issues/16509

**Closed by notpeter** 2024-10-16 15:52 UTC
Labels: enhancement, triage, admin read
