### ISSUE TITLE
Failing to Load vscode-html-language-server in windows machine 

### ISSUE THREAD

**Issue by akshaykrishnan003** [zed-industries/zed#21677] opened 2024-12-07 07:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Getting this below error while opening any html file

Language server error: vscode-html-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'C:\C:\Users\akshaykrishnan\AppData\Local\Zed\extensions\work\html\node_modules\@zed-industries\vscode-langservers-extracted\bin\vscode-html-language-server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.13.0

### Environment

Processor	12th Gen Intel(R) Core(TM) i7-1270P   2.20 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

![image](https://github.com/user-attachments/assets/62a31868-2199-49b2-9f4c-362b8b68face)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-07T12:26:10.282035+05:30 [INFO] Creating buffer 0x21905a93588 of size 63168, name 'chunk-11', handle 13
2024-12-07T12:26:46.1405432+05:30 [INFO] Opening main db
2024-12-07T12:26:46.1422669+05:30 [INFO] attempting to start language server "vscode-css-language-server", path: "C:\\Org\\sample.app", id: 1
2024-12-07T12:26:46.142405+05:30 [INFO] attempting to start language server "tailwindcss-language-server", path: "C:\\Org\\sample.app", id: 2
2024-12-07T12:26:46.1425661+05:30 [INFO] Initializing default prettier with plugins {}
2024-12-07T12:26:46.1428326+05:30 [INFO] Initializing default prettier with plugins {}
2024-12-07T12:26:46.1575916+05:30 [INFO] fetching latest version of language server "vscode-css-language-server"
2024-12-07T12:26:46.1687605+05:30 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-12-07T12:26:46.2061966+05:30 [INFO] Initializing default prettier with plugins {}
2024-12-07T12:26:46.2095724+05:30 [WARN] Failed to open HKLM\Software\Python\PythonCore\3.9\InstallPath, Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
2024-12-07T12:26:47.928567+05:30 [INFO] downloading language server "vscode-css-language-server"
2024-12-07T12:26:48.9714864+05:30 [INFO] downloading language server "tailwindcss-language-server"
2024-12-07T12:26:49.4198397+05:30 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "C:\\Org\\sample.app", args: ["C:\\Users\\akshaykrishnan\\AppData\\Local\\Zed\\languages\\vscode-css-language-server\\node_modules/vscode-langservers-extracted/bin/vscode-css-language-server", "--stdio"]
2024-12-07T12:26:50.7916252+05:30 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "C:\\Org\\sample.app", args: ["C:\\Users\\akshaykrishnan\\AppData\\Local\\Zed\\languages\\tailwindcss-language-server\\node_modules/@tailwindcss/language-server/bin/tailwindcss-language-server", "--stdio"]
2024-12-07T12:26:51.1560554+05:30 [WARN] unhandled capability registration: Registration { id: "1162c187-56ca-4408-a003-752d1ad6d79f", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-12-07T12:26:53.6833405+05:30 [INFO] Creating buffer 0x21905a93c58 of size 81984, name 'chunk-12', handle 14
2024-12-07T12:26:53.6837957+05:30 [INFO] Creating buffer 0x21905a98078 of size 81984, name 'chunk-13', handle 15
2024-12-07T12:26:53.6928319+05:30 [INFO] attempting to start language server "vscode-html-language-server", path: "C:\\Org\\sample.app", id: 3
2024-12-07T12:26:53.6930309+05:30 [INFO] Initializing default prettier with plugins {}
2024-12-07T12:26:53.6934423+05:30 [INFO] Initializing default prettier with plugins {}
2024-12-07T12:26:53.7031148+05:30 [WARN] Failed to open HKLM\Software\Python\PythonCore\3.9\InstallPath, Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
2024-12-07T12:26:55.9138562+05:30 [INFO] Creating buffer 0x21905a98e18 of size 82656, name 'chunk-14', handle 16
2024-12-07T12:26:56.9197376+05:30 [INFO] starting language server process. binary path: "C:\\Program Files\\nodejs\\node.exe", working directory: "C:\\Org\\sample.app", args: ["/C:\\Users\\akshaykrishnan\\AppData\\Local\\Zed\\extensions\\work\\html/node_modules/@zed-industries/vscode-langservers-extracted/bin/vscode-html-language-server", "--stdio"]
2024-12-07T12:26:56.9685398+05:30 [ERROR] cannot read LSP message headers
2024-12-07T12:26:56.9688326+05:30 [ERROR] Failed to start language server "vscode-html-language-server": oneshot canceled
2024-12-07T12:26:56.9688987+05:30 [ERROR] server stderr: "node:internal/modules/cjs/loader:1042\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module 'C:\\C:\\Users\\akshaykrishnan\\AppData\\Local\\Zed\\extensions\\work\\html\\node_modules\\@zed-industries\\vscode-langservers-extracted\\bin\\vscode-html-language-server'\r\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)\r\n    at Module._load (node:internal/modules/cjs/loader:885:27)\r\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\r\n    at node:internal/main/run_main_module:23:47 {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: []\r\n}\r\n\r\nNode.js v18.13.0\r\n"
2024-12-07T12:26:56.9691665+05:30 [ERROR] server shut down
```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-12-07 08:46
The root cause is https://github.com/zed-industries/zed/issues/20559 so I'll close this to avoid bloating the tracker more.

**Closed by SomeoneToIgnore** 2024-12-07 08:46 UTC
Labels: bug, triage, admin read

**Comment by dylansantwani** [comment] 2024-12-08 20:16
If you still have this issue, I have fixed it. Clone my repository.
https://github.com/dylansantwani/zed-fixed-windows
