### ISSUE TITLE
Lines greater than 1024 chars long crash the editor on Windows 11.

### ISSUE THREAD

**Issue by professorbee** [zed-industries/zed#11518] opened 2024-05-07 21:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Lines greater than 1024 characters break windows. Steps to reproduce: 
1. Create a file in another text editor with a line containing 1025 characters. 
2. Open in editor. 
3. Watch it crash.

Here's the file I used: [test.txt](https://gist.github.com/professorbee/7299b1ad546b96165d56db21816b83d5)

### Environment

Zed: v0.135.0 (Zed Dev d64106e01b0ebec37d00ff0fd28f6848e16a997b)
OS: Windows 10.0.22631
Memory: 31.7 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

# [Zed.log](https://gist.github.com/professorbee/de19b97166307c5b574144965d25766d)

**Comment by pidjan** [comment] 2024-05-07 21:36
i can confirm that this issue also occurs for me on the latest commit: [6a64b73](https://github.com/zed-industries/zed/commit/6a64b732b67c6a251126af45158190736ebe2318).
OS: Windows 11 22631.2861
Memory: 32GB
Arch: x86_64
[Zed.log](https://github.com/zed-industries/zed/files/15241202/Zed.log)

**Comment by someone13574** [comment] 2024-05-08 03:12
Found the problem. I used git bisect to find that https://github.com/zed-industries/zed/pull/11080 ([this](https://github.com/zed-industries/zed/pull/11080/commits/5392cf699ecfeb5d8a6cb7441791a381893d9015) commit specifically) introduces a new soft-wrap mode "none" which doesn't respect `MAX_LINE_LEN` (which is set to 1024), causing a crash (or not scrolling and however mac reacts to it) when the line length exceeds that instead of wrapping at 512. Temporarily, you can fix this by adding `"soft_wrap": "prefer_line"` to your settings.json. I'm not sure how @SomeoneToIgnore want's to deal with it long term.

**Comment by SomeoneToIgnore** [comment] 2024-05-08 06:29
`PreferLine` variant is supposed to be the new default, as the one being called `None` before — the only place current `None` is intended to be used is git diff hunks.

So, I see two problems with Windows impl:
* usage of `None` instead of `PreferLine`
* panics on long lines

**Comment by JunkuiZhang** [comment] 2024-05-08 07:26
This surprised me. I tested it, and when calling `layout_line`, the input text parameter has only 256 characters, but the `FontRun` parameter indicates there are 1025 characters, causing a panic when accessing `text[index]`. I think the issue lies in the input parameter when calling `layout_line`, but it can also be easily fixed in `DirectWrite`. Should I fix it on the `DirectWrite` side or where `layout_line` is called?

**Comment by JunkuiZhang** [comment] 2024-05-08 08:09
#11536 should fix this, I tested it on my laptop.

**Closed** 2024-05-08 23:08 UTC
Labels: defect, performance, panic / crash, editor, windows, linux, admin read
