### ISSUE TITLE
Horizontal scrollbar shows in file tree despite adaquete room

### ISSUE THREAD

**Issue by someone13574** [zed-industries/zed#19792] opened 2024-10-26 15:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Even when the project panel has lots of horizontal room, the horizontal scrollbar will still show if you mouse over it. The vertical scrollbar does not do this.

### Environment

Zed: v0.159.1 (Zed Preview)
OS: Linux Wayland void unknown
Memory: 27.1 GiB
Architecture: x86_64
GPU: AMD Radeon Graphics (RADV GFX1103_R1) || radv || Mesa 24.2.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot from 2024-10-26 11-20-57](https://github.com/user-attachments/assets/9271b2ac-00ea-43a4-9909-cc4a9bd3f829)

**Comment by SomeoneToIgnore** [comment] 2024-10-26 18:57
Duplicate of https://github.com/zed-industries/zed/issues/19637

**Closed by SomeoneToIgnore** 2024-10-26 18:57 UTC
Labels: defect, triage, admin read
