### ISSUE TITLE
UI very laggy 

### ISSUE THREAD

**Issue by Amtr4x** [zed-industries/zed#14645] opened 2024-07-17 13:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Since I've installed the editor in my pc, the performance is awful. Editor opens quickly but navigation, and code editing have a very annoying delay, I'm talking about 1 sec of delay. I can't figure what is the problem, since I have all dependencies needed to launch the program. Also tried to disable copilot but, performance still inexistent.

### Environment

system: Pop!_OS 22.04 LTS x86_64
CPU: Intel Celeron N4020 (2) @ 2.800GHz
GPU: Intel GeminiLake [UHD Graphics 600]

**Comment by SomeoneToIgnore** [comment] 2024-07-17 16:33
Duplicate of https://github.com/zed-industries/zed/issues/14222

**Closed by SomeoneToIgnore** 2024-07-17 16:33 UTC
Labels: defect, triage, admin read

**Comment by Amtr4x** [comment] 2024-07-18 16:18
Excuse me SR, the report is not duplicate. This behavior is not related in the report provided by you. I'm talking about constant bad performance and fast start. I'm my device this only tooks 1s to start, but interactions are delayed to much, as if was consuming a lot of resources but in this case is not consuming a lot of resources.

**Comment by SomeoneToIgnore** [comment] 2024-07-18 16:45
What about this?
https://github.com/zed-industries/zed/issues/14240

Generally, feels that PopOS was in every performance-related report 
* some of the issues are due to gpu not supported by Zed's rendering part, falling back to software rendering and lagging (not very related but similar issues cause https://github.com/zed-industries/zed/issues/14204 and https://github.com/zed-industries/zed/issues/14430)
* some of the issues are due to X11: https://github.com/zed-industries/zed/issues/13203, https://github.com/zed-industries/zed/issues/12690

This issue is quite generic, so not sure that it will be fixed before the ones mentioned above — and I'm quite certain the root of the issues is shared with them, so this issue will be fixed too with high probability.

**Comment by Amtr4x** [comment] 2024-07-18 20:16
In this case maybe you have reason. I'm agree that my behaviour is shared across the last 2 report. But in my case at the time of typing lag is constant. Thanks for the attention I hope fixes soon.

**Comment by ConradIrwin** [comment] 2024-07-19 01:43
@Amtr4x extreme slowness is usually caused by falling back to a software emulated GPU. Could you please check that `vkcube` is running correctly on your machine and not using `llvmpipe`. Detailed instructions are here: https://zed.dev/docs/linux#zed-is-very-slow

**Comment by Amtr4x** [comment] 2024-07-21 13:05
Excuse me for the delay, but after running vkcube the performance of the window opened was perfect, no delays, no crashes and i've not obtained an output talking nothing about llvmpipe, just a cube rotating with a "Lunar" tag.

**Comment by tuimz** [comment] 2024-07-23 09:07
I am experiencing the same issues, scrolling is very slow and jumpy, also text rendering of UI seems strange/off. See also my screenshot.
![image](https://github.com/user-attachments/assets/287f67c2-6cb6-4cbf-8859-6fcfd70c6e83)

It starts very fast though so not a duplicate of #14222 

vkcube runs smoothly

```
vkcube
Selected GPU 0: Intel(R) Xe Graphics (TGL GT2), type: 1
```

```
cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
```

```
zed --version
Zed 0.144.4 – /home/tim/.local/zed.app/libexec/zed-editor
```

**Comment by Amtr4x** [comment] 2024-07-23 21:39
If there still closing important reports as duplicated without review it and analyze it, we well have zed on linux in the year 2090.

**Comment by AlexDaniel** [comment] 2024-07-28 17:15
@Amtr4x where did you obtain zed or how did you build it? What's the version?

**Comment by Amtr4x** [comment] 2024-07-29 09:38
from the official page, the install script.

**Comment by tuimz** [comment] 2024-07-29 09:41
In the mean time I was able to solve my slowness by following directions from #14240

By changing `/etc/prime-discrete` to 'off'

**Comment by tuimz** [comment] 2024-07-29 10:14
```
$ cat /etc/prime-discrete 
off
```

**Comment by Amtr4x** [comment] 2024-07-29 10:21
Sr, this file not exists in my device... i need a copy of this file or the content to add it

**Comment by tuimz** [comment] 2024-07-29 10:22
The only content on my machine of that file is `off`

**Comment by Amtr4x** [comment] 2024-07-29 10:23
Thanks problem solved completely
