### ISSUE TITLE
`!` snippet not working in zed

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#15680] opened 2024-08-02 10:28 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

just type `!` inside an empty html file,
it should give an emmet suggestion to have a basic skeleton shell like this instead it does nothing:
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	
</body>
</html>
```
the other snippets works except this (afaict), VSCode image example below:
![vscode-emmet](https://github.com/user-attachments/assets/1caeb74d-a7dc-4147-909c-0e01f48f47c1)

### Environment

Linux Mint
Zed 0.146.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![vscode-emmet](https://github.com/user-attachments/assets/1caeb74d-a7dc-4147-909c-0e01f48f47c1)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment] 2024-08-02 16:46
Hey @sparrowsl, do you get any emmet completions at all in an html file, or is it just `!` that seems to be broken?

**Comment by sparrowsl** [comment] 2024-08-02 16:47
it's just the `!` that is broken, _(the others I mostly used seems to work fine)_

**Comment by axoking** [comment] 2024-08-02 17:12
I have the same issue

(Mac OS Sequioa, Apple M1)

**Comment by JosephTLyons** [comment] 2024-08-02 17:51
Huh, very strange - this seems to work for me on macOS.

<img width="834" alt="SCR-20240802-mice" src="https://github.com/user-attachments/assets/05881ce1-e494-422a-9cff-98890f9a385d">

Not quite sure what might be causing an issue.

Can you include the contents from your `keymap.json` and from your `settings.json`? Maybe something is interfering with it.

**Comment by sparrowsl** [comment] 2024-08-02 18:01
`keymap.json`
```json
// Zed keymap
//
// For information on binding keys, see the Zed
// documentation: https://zed.dev/docs/key-bindings
//
// To see the default key bindings run `zed: Open Default Keymap`
// from the command palette.
[
  {
    "context": "Workspace",
    "bindings": {
      // "shift shift": "file_finder::Toggle"
    }
  },
  {
    "context": "Editor",
    "bindings": {
      // "j k": ["workspace::SendKeystrokes", "escape"]
    }
  }
]

```

**Comment by sparrowsl** [comment] 2024-08-02 18:01
`settings.json`
```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "auto_install_extensions": {
    "ruff": true
  },
  "auto_update_extensions": {
    "ruff": false
  },
  "ui_font_size": 15,
  "buffer_font_size": 14,
  // "ui_font_size": 13.5,
  // "buffer_font_size": 13.5,
  "theme": "Catppuccin Macchiato",
  // "format_on_save": "on",
  "restore_on_startup": "last_workspace",
  // "auto_signature_help": true,
  "chat_panel": {
    "button": false
  },
  "collaboration_panel": {
    "button": false
  },
  "assistant": {
    "version": "2",
    "button": false,
    "enabled": false
  },
  "notification_panel": {
    "button": false
  },
  "outline_panel": {
    "button": false
  },
  "terminal": {
    "button": false
  },
  "tabs": {
    "git_status": true,
    "file_icons": true
  },
  "file_types": {
    "JSONC": ["tsconfig.json", "jsconfig.json", "*.json"]
  },
  // "redact_private_values": true,
  "scroll_beyond_last_line": "vertical_scroll_margin",
  "show_call_status_icon": false,
  "soft_wrap": "editor_width",
  "autosave": "on_focus_change",
  "scrollbar": {
    "show": "auto",
    "cursors": false,
    "git_diff": true,
    "search_results": true,
    "selected_symbol": true,
    "diagnostics": true
  },
  // "formatter": "auto",
  "show_whitespaces": "boundary",
  "tab_size": 2,
  "languages": {
    "JavaScript": {
      "language_servers": [
        "!typescript-language-server",
        "!eslint",
        "!prettier",
        "..."
      ],
      "code_actions_on_format": {
        "source.organizeImports.biome": true
      }
    },
    "C": {
      "format_on_save": "on"
    },
    "Python": {
      "tab_size": 4,
      "format_on_save": { "language_server": { "name": "ruff" } },
      "language_servers": ["pyright", "ruff"],
      "formatter": [
        {
          "code_actions": {
            // Fix all auto-fixable lint violations
            // "source.fixAll.ruff": true,
            // Organize imports
            "source.organizeImports.ruff": true
          }
        },
        { "language_server": { "name": "ruff" } }
      ]
    },
    "Go": {
      "tab_size": 4
    }
  }
}
```

**Comment by bbb651** [comment] 2024-08-03 15:57
I was very confused because I managed to reproduce this yesterday but I knew it worked before, then today I tried it and it worked again - turns out it only works for files named `index.html`!

**Comment by htor** [comment] 2024-10-12 12:01
I can't reproduce the error here. Typing `!` and hitting Enter correctly inserts the HTML snippet. It also works regardless of filename. 

Zed: v0.157.2 (Zed Preview)
OS: macOS 12.7.4
Memory: 16 GiB
Architecture: aarch64

**Comment by htor** [comment] 2024-10-12 12:03
Also, this issue is probably a duplicate of: https://github.com/zed-industries/zed/issues/12791

**Comment by JosephTLyons** [comment] 2024-10-13 17:29
Closing in favor of #12791 - feel free to upvote that issue with a 👍!

**Closed by JosephTLyons** 2024-10-13 17:29 UTC
Labels: defect, needs info / awaiting response, html, language, tooling
