### ISSUE TITLE
System Window Decorations

### ISSUE THREAD

**Issue by tripplehelix** [zed-industries/zed#14326] opened 2024-07-12 12:55 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Would be really nice if we could use the systems window decorations instead of the apps. 

The close/maximise/minimise buttons are in the wrong place and order for my setup, also doesn't fit in with my custom system theme.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/66923dc5-1a99-4532-94f1-bcfc38ec6797)

vs

![Screenshot_2024-07-12_13-53-37](https://github.com/user-attachments/assets/73acdf53-c089-4342-a5b5-57f494acb3c6)

**Comment by someone13574** [comment] 2024-07-13 02:04
Run with the `ZED_WINDOW_DECORATIONS=server` environment variable.

**Comment by tripplehelix** [comment] 2024-07-13 12:16
> Run with the `ZED_WINDOW_DECORATIONS=server` environment variable.

Amazing! Thank you! This also fixes a weird issue where moving the mouse over the title bar attaches the window to the mouse. (x11 xfce)

**Comment by someone13574** [comment] 2024-07-14 01:30
@tripplehelix Can this issue be closed then?

**Comment by tripplehelix** [comment] 2024-07-14 01:34
Should still have a setting to make this easier and more obvious.

**Comment by LSeelig** [comment] 2024-07-16 00:25
Unfortunately, GNOME Wayland does not support SSD. A "System" titlebar option should really use something like libdecor if it will look decent. The rounded corners also seem to be causing issues. They're a bit glitchy (under wayland), and I don't know of any distro with a similar radius.

**Comment by tripplehelix** [comment] 2024-07-16 01:02
Just disable the option if the user is running Gnome? One WM shouldn't bring down the vast number of other desktops.

**Comment by LSeelig** [comment] 2024-07-16 01:09
> Just disable the option if the user is running Gnome? One WM shouldn't bring down the vast number of other desktops.

It's ultimately up to the developers and the community if they want to support the DE a plurality of Linux desktop users use. It's not "bringing down" anyone but GNOME's users.

**Comment by AndydeCleyre** [comment] 2024-07-16 16:56
For KDE Plasma, the following is probably the most straightforward way.

```console
$ mkdir -p ~/.config/plasma-workspace/env
$ echo 'export ZED_WINDOW_DECORATIONS=server' >>~/.config/plasma-workspace/env/zed.sh
```

Maybe other DE users would like to post suitable approaches for those here as well.

**Comment by tripplehelix** [comment] 2024-07-16 17:03
You just add it to your `.bashrc`, `.bash_profile`, `.profile`, `/etc/environment` or `/etc/profile` no?

As I use FISH I added it to `.config/fish/config.fish`

Still would be easier if zed's settings had this as an option so this wasn't needed.

**Comment by RustoMCSpit** [comment] 2024-07-27 00:22
> ZED_WINDOW_DECORATIONS=server

you mean in the terminal? i tried ./zed --ZED_WINDOW_DECORATIONS=server
and got
`error: unexpected argument '--ZED_WINDOW_DECORATIONS' found

  tip: to pass '--ZED_WINDOW_DECORATIONS' as a value, use '-- --ZED_WINDOW_DECORATIONS'

Usage: zed [OPTIONS] [PATHS_WITH_POSITION]...

For more information, try '--help'.
``

**Comment by someone13574** [comment] 2024-07-27 00:51
Its an environment variable. `ZED_WINDOW_DECORATIONS=server ./zed`

**Comment by Moshyfawn** [comment] 2024-08-18 02:39
There's a slightly older issue on the same topic that's getting more traction, so I'm going to close it in its favour to keep the conversation in one place. Be sure to +👍 the other thread and continue the conversation there.

Duplicate of:
- #14165

**Closed by Moshyfawn** 2024-08-18 02:39 UTC
Labels: enhancement, linux, support
