### ISSUE TITLE
Deleted files in a multibuffer are recreated by autosave  

### ISSUE THREAD

**Issue by CountryTk** [zed-industries/zed#18852] opened 2024-10-08 10:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you use the search function and search for a keyword and then delete a file with that keyword, the file that was deleted is still open in the search tab which means autosave "recreates" the file.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS Sonoma 14.5
Memory: 32 GiB
Architecture: ARM

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I've attached a screen recording of how to reproduce the bug

https://github.com/user-attachments/assets/85bec6b8-2cb5-4c93-bc8e-62aced5df2e2

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-08 22:45
Duplicate of https://github.com/zed-industries/zed/issues/9101

**Closed by SomeoneToIgnore** 2024-10-08 22:45 UTC
Labels: defect, editor, multi-buffer
