### ISSUE TITLE
Icons jumping about

### ISSUE THREAD

**Issue by askegg** [zed-industries/zed#8605] opened 2024-02-29 12:45 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am unable to reliably reproduce this visual bug.

### Environment

Macbook Pro 2016 13", 3.3GHz, 16GB ram, MacOS 12.7.3

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/59593013/e0d1e9a3-93fc-4b64-873c-63ee49e49b7b

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by alygin** [comment] 2024-02-29 14:44
Resembles #8050, though they are really pulsating in @askegg’s screencast, not just shaking

**Comment by Moshyfawn** [comment] 2024-02-29 14:53
Duplicate of #8050

Make sure to +👍 on the other thread and provide any additional information.

**Closed by Moshyfawn** 2024-02-29 14:53 UTC
Labels: defect, triage, admin read
