### ISSUE TITLE
Duplicate buttons appear when moving dock side

### ISSUE THREAD

**Issue by ghostdevv** [zed-industries/zed#9713] opened 2024-03-22 18:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I right click the buttons in the bottom bar to move to the right it will duplicate it, and if you keep moving it back and forth you can make lots of them

<img width="601" alt="image" src="https://github.com/zed-industries/zed/assets/47755378/74991d90-4753-4666-8c81-12d966b9a9db">

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: x86_64

**Comment by ghostdevv** [comment] 2024-03-22 18:29
I restarted zed and it isn't happening - it might be related to it being the first ever time I opened zed?

**Comment by Moshyfawn** [comment] 2024-03-22 22:59
This has already been reported, so I'm going to this issue in favour of the other one. Be sure to +👍.

Duplicate of
- #9688

**Closed by Moshyfawn** 2024-03-22 22:59 UTC
Labels: defect, triage, admin read
