### ISSUE TITLE
Can't input Japanese with Google Japanese Input

### ISSUE THREAD

**Issue by toshimaru** [zed-industries/zed#13380] opened 2024-06-21 23:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't input Japanese with [Google Japanese Input](https://www.google.co.jp/ime/).

https://github.com/zed-industries/zed/assets/803398/37ea5e6e-2406-487b-a780-3aff16b7c0d5

### Environment

Zed: v0.140.5 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-06-22 19:29
I think this is a duplicate of 
- https://github.com/zed-industries/zed/issues/13292

Please 👍 to vote for prioritizing that issue and subscribe to track its progress.
Thanks for reporting!

**Closed by notpeter** 2024-06-22 19:29 UTC
Labels: defect, triage, admin read

**Comment by toshimaru** [comment] 2024-06-23 23:42
@notpeter 
Thanks, I've voted the issue. 👍
