### ISSUE TITLE
Vim mode: Replace mode (`R`)

### ISSUE THREAD

**Issue by tfeldmann** [zed-industries/zed#9625] opened 2024-03-21 09:36 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'd love to see vim's replace mode (`R`)

**Comment by Moshyfawn** [comment] 2024-03-21 14:15
This is [supported](https://github.com/zed-industries/zed/issues/4440#issuecomment-1998835984
) in [`v0.128.0`] (https://zed.dev/releases/preview/0.128.0). Feel free to reopen if this is not what you're looking for.

Duplicate of
- #4440

**Closed by Moshyfawn** 2024-03-21 14:15 UTC
Labels: enhancement, triage, admin read

**Comment by tfeldmann** [comment] 2024-03-21 14:49
That's great! Thanks!
