### ISSUE TITLE
Support split screen to use 2 terminal windows at the same time

### ISSUE THREAD

**Issue by link271** [zed-industries/zed#10757] opened 2024-04-19 02:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Please add support for terminal split screen so 2 windows can be use at the same time.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot 2024-04-19 at 09 58 10](https://github.com/zed-industries/zed/assets/4545024/4564be25-b2f5-42ac-a684-8a1d206b1eab)

**Comment by JosephTLyons** [comment] 2024-04-19 05:40
Hey @link271,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4351

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-19 05:40 UTC
Labels: enhancement, terminal
