### ISSUE TITLE
TailwindCSS support in ERB tags broken

### ISSUE THREAD

**Issue by drale2k** [zed-industries/zed#11128] opened 2024-04-28 13:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am filling this as a bug since it is supposed to work after this PR https://github.com/zed-industries/zed/issues/6340

As reported in the PR comments, it does not work as intended. It works when you use plain html in ERB files, but not when actually using ERB.

For example it does not work <%= f.label :keywords, class: "block text-sm font-medium leading-6 text-gray-900" %>. 
Class names here will not be suggested.

### Environment

Zed: v0.132.3 (Zed)
OS: macOS 14.2.1
Memory: 64 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-04-29 01:22
Similar to #4368

**Comment by mrnugget** [comment] 2024-06-07 04:23
Closing as duplicate of https://github.com/zed-industries/zed/issues/12728, which is newer, but it's now where all the action is.

**Closed by mrnugget** 2024-06-07 04:23 UTC
Labels: defect, ruby, language, language server, tailwind css
