### ISSUE TITLE
Zed opens an invisible window

### ISSUE THREAD

**Issue by Nikita0x** [zed-industries/zed#15631] opened 2024-08-01 17:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed opens up the editor, but with the **Invisible** window.

1) Install Zed with the
```curl -f https://zed.dev/install.sh | sh```
2) Run Zed with the
```zed```

https://github.com/user-attachments/assets/19690ea0-11b6-47ba-9160-bb0b369cae89

### Environment

OS: Linux Mint 21.2 x86_64 
Host: ASUS TUF Gaming F15 FX506LI_FX506LI 1.0 
Kernel: 5.15.0-107-generic 
Uptime: 1 hour, 57 mins 
Packages: 2694 (dpkg), 12 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Cinnamon 5.8.4 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-Aqua (Mint-Y) 
Theme: Mint-Y-Dark-Aqua [GTK2/3] 
Icons: Mint-Y-Aqua [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-10300H (8) @ 4.500GHz 
GPU: Intel CometLake-H GT2 [UHD Graphics] 
GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
Memory: 4835MiB / 15825MiB

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

sudo: /home/nikita/.local/share/zed/logs/Zed.log: command not found

</pre></details>

**Comment by notpeter** [comment] 2024-08-01 17:07
Duplicate of:
- https://github.com/zed-industries/zed/issues/14648

**Closed** 2024-08-12 15:35 UTC
Labels: duplicate
