### ISSUE TITLE
Preserve cursor location after canceling a `"editor::SelectAll"`

### ISSUE THREAD

**Issue by liebkne** [zed-industries/zed#8105] opened 2024-02-21 07:11 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Preserve cursor location after canceling a `"editor::SelectAll"`. Currently the cursor is placed to end of buffer if a `"editor::SelectAll"` command is canceled.

**Comment by SomeoneToIgnore** [comment] 2024-02-29 09:47
Will close as a duplicate of a more broad https://github.com/zed-industries/zed/issues/8588 that now has some instructions on how to proceed.

**Closed by SomeoneToIgnore** 2024-02-29 09:47 UTC
Labels: enhancement, editor
