### ISSUE TITLE
Image cache is too aggressive

### ISSUE THREAD

**Issue by v3rm0n** [zed-industries/zed#18801] opened 2024-10-07 10:00 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Looks like Zig caches images and even if the image file is overwritten it will still show the old image. The cache seems to be path based so if I move the image around I can get the new one, if I move it back it will show the old one.

In the screenshots, file **screenshot.bmp** was created initially as a red square on a black background and then it was overwritten with green square on a black background, but any time the file called **screenshot.bmp** is in its original location, the old preview is shown. Renaming or moving the file will use the correct preview.

### Environment

Zed: v0.155.2 (Zed)
OS: macOS 15.0.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1014" alt="Screenshot 2024-10-07 at 12 56 29" src="https://github.com/user-attachments/assets/aa575831-ae99-47b5-954a-073484e5582f">
<img width="1020" alt="Screenshot 2024-10-07 at 12 56 45" src="https://github.com/user-attachments/assets/7ecf09a8-1507-4692-ab19-e287edad8ef5">
<img width="1019" alt="Screenshot 2024-10-07 at 12 56 57" src="https://github.com/user-attachments/assets/ea2783ba-0bdd-49de-974a-f903192a291c">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-07 13:19
Duplicate of:
- https://github.com/zed-industries/zed/issues/11529

**Closed by notpeter** 2024-10-07 13:19 UTC
Labels: defect, triage, admin read
