### ISSUE TITLE
Preview sql file of db relationships

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12802] opened 2024-06-08 14:54 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if, as for example with markdown, the `.sql` files would be able to see a preview of the relationships of the various tables like `dbdiagram` does for example which allows you to see the relationships from the converted code.

Link: https://dbdiagram.io/d/66646fb19713410b05165782

<img width="996" alt="Screenshot 2024-06-08 alle 16 49 25" src="https://github.com/zed-industries/zed/assets/20476002/114cb3ce-6e13-4987-a821-8effe4cd9838">

Code example `db.sql` :

```sql
-- Creazione del database
CREATE DATABASE my_database;
USE my_database;

-- Creazione della tabella user
CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Creazione della tabella organization
CREATE TABLE organization (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Creazione della tabella permission
CREATE TABLE permission (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Creazione della tabella role
CREATE TABLE role (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Creazione della tabella user_session
CREATE TABLE user_session (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    session_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

-- Creazione della tabella role_permission
CREATE TABLE role_permission (
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role(id),
    FOREIGN KEY (permission_id) REFERENCES permission(id)
);

-- Creazione della tabella user_org_role
CREATE TABLE user_org_role (
    user_id INT NOT NULL,
    organization_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, organization_id, role_id),
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (role_id) REFERENCES role(id)
);
```

**Comment by Moshyfawn** [comment] 2024-06-08 16:17
There's already an extension request for this, so I'm going to close this issue in favour of the other one. Be sure to +👍 the other thread.

Duplicate of:
- zed-industries/extensions#514

**Closed by Moshyfawn** 2024-06-08 16:17 UTC
Labels: enhancement, triage, admin read

**Comment by Moshyfawn** [comment] 2024-06-10 01:15
> @Moshyfawn : These seem like two different issues to me. I don't understand why close it.

This request seems like a good candidate for the extension of the request I've closed it in favour of; moreover, the disussers mention it https://github.com/zed-industries/extensions/issues/514#issuecomment-2052186109 as a possibility, so it would make sense to combine the two.
