### ISSUE TITLE
Git File Tracking

### ISSUE THREAD

**Issue by TarekArar** [zed-industries/zed#8663] opened 2024-03-01 11:30 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hi, Thanks for the great work you did, I'm using Zed for few days and it's becoming my default editor but the only thing that I find lacking is git extension like the one in vs code, where you can see the changed files and add them from GUI.

Thank you for considering this.

**Comment by evrsen** [comment] 2024-03-01 12:25
If I understand you right you wish to have a Source Control panel in Zed? If so, you might wanna upvote the relevant issue https://github.com/zed-industries/zed/issues/4367

**Comment by Moshyfawn** [comment] 2024-03-02 02:33
Let's close this one in favour of the other, unless anyone objects. Be sure to +👍 the other topic and add any relevant information that may be missing.

**Comment by Moshyfawn** [comment] 2024-03-02 02:33
Duplicate of #4367

**Closed by Moshyfawn** 2024-03-02 02:33 UTC
Labels: enhancement, triage, admin read
