### ISSUE TITLE
Add hjson support

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#10369] opened 2024-04-10 17:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Please, add [hjson](https://hjson.github.io) support.

**Comment by JosephTLyons** [comment] 2024-04-11 16:01
Hey @VKondakoff,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/extensions/issues/153

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-11 16:01 UTC
Labels: enhancement, triage, admin read
