### ISSUE TITLE
Moving/Renaming files should auto rename

### ISSUE THREAD

**Issue by obnol** [zed-industries/zed#10109] opened 2024-04-03 09:25 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Moving or renaming `files` should also auto rename its implementations. For example, If I have a `useUser.ts` file and I rename it to `useGetUser.ts`, the files that are using this should also update its import

**Comment by Moshyfawn** [comment] 2024-04-04 03:37
I think there's already a feature request for this, so I'm going to close this thread in favour of the other one. Be sure to +👍 the other post.

Duplicate of
- #5252

**Closed by Moshyfawn** 2024-04-04 03:37 UTC
Labels: enhancement, triage, admin read
