### ISSUE TITLE
Support accepting input from command line pipes

### ISSUE THREAD

**Issue by kevinxiong** [zed-industries/zed#9473] opened 2024-03-18 02:27 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

echo "hello" | zed - 
does not work as expected

**Comment by Moshyfawn** [comment] 2024-03-19 18:13
I think this has already been brought up. I'm going to close this topic in favour of keeping all the discussion and upvotes in one place. Be sure to +👍 and add any additional information.

Duplicate of
- #5044

**Closed by Moshyfawn** 2024-03-19 18:13 UTC
Labels: enhancement, triage, admin read
