### ISSUE TITLE
Find: Hide/Show results from file

### ISSUE THREAD

**Issue by davidspry** [zed-industries/zed#21725] opened 2024-12-09 03:26 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to be able to hide/show the search results from a particular file in the Find UI.

Currently, clicking a file header (such as the 'sampler.ixx' bar in the screenshot below) navigates to the file. I suggest that clicking this bar should hide/show the search results belonging to the file, and clicking the bar's arrow icon should navigate to the file.

<img width="1008" alt="A screenshot of the Find UI" src="https://github.com/user-attachments/assets/fd4c0c71-44af-46f9-87a8-ec65936a4e30">

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.1.1
Memory: 64 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-12-09 11:20
Duplicate of https://github.com/zed-industries/zed/issues/5290

**Closed by SomeoneToIgnore** 2024-12-09 11:20 UTC
Labels: enhancement, triage, admin read
