### ISSUE TITLE
Can't sign in to Copilot

### ISSUE THREAD

**Issue by wytzepiet** [zed-industries/zed#9736] opened 2024-03-23 09:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can't sign in to copilot in Zed. When i click the little copilot button in the bottom, a window opens like normal. Nothing happens when clicking any buttons though. 
When trying to sign in with the command palette using 'Copilot: sign in', nothing happens either.

### Environment

Zed: v0.127.3 (Zed)
OS: macOS 14.4.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/71794633/8e2251bb-7057-4435-801b-e667dc7d9e47

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-03-23T10:39:10+01:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-23T10:40:08+01:00 [ERROR] Cancelled LSP request task for "signInConfirm" id 5 which took over 120s
2024-03-23T10:40:08+01:00 [ERROR] crates/copilot/src/copilot.rs:105: LSP request timeout
2024-03-23T10:40:08+01:00 [ERROR] crates/copilot/src/copilot.rs:105: LSP request timeout
2024-03-23T10:40:08+01:00 [ERROR] crates/copilot/src/copilot.rs:105: LSP request timeout
2024-03-23T10:40:08+01:00 [ERROR] crates/copilot/src/copilot.rs:105: LSP request timeout
2024-03-23T10:44:33+01:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled

**Comment by Moshyfawn** [comment] 2024-03-23 14:19
This has been fixed in [`0.128.1`](https://zed.dev/releases/preview/0.128.1).

Duplicate of
- #9596

**Closed by Moshyfawn** 2024-03-23 14:19 UTC
Labels: defect, triage, admin read

**Comment by wytzepiet** [comment] 2024-03-25 11:47
Didn’t see that that issue. Thanks for the reply!
