### ISSUE TITLE
can't we use this editor for django code?

### ISSUE THREAD

**Issue by JuniorNoah** [zed-industries/zed#4262] opened 2024-01-17 07:33 UTC
### Check for existing issues

- [ ] Completed

### Describe the feature

This editor provide python language and pyright lsp.
But, in django's grammer doesn't provied

for example, i wrote model.objects.filter(field=None), then this editor said cannot access member 'objects' for type ~~
and can't i change language's lsp to others.

i don't know i don't find where can i do, or doesn't provide, it is possible to provide?

### If applicable, add mockups / screenshots to help present your vision of the feature

provide django format allow

**Comment by pratyushmittal** [comment] 2024-01-25 03:41
Installing [`django-types`](https://pypi.org/project/django-types/) fixes this.

The issue seems to be because [Pyright isn't able to detect types for Django](https://github.com/microsoft/pyright/issues/1359).

**Comment by LucasKuhn** [comment] 2024-01-26 18:15
For formatting Django html files, installing [djhtml](https://github.com/rtts/djhtml) works fine - as long as you set it for all HTML files
```json
{
  "language_overrides": {
    "HTML": {
      "format_on_save": {
        "external": {
          "command": "djhtml",
          "arguments": ["-"]
        }
      }
    }
  }
}
```
It would be nice to have a proper html-django language for django templates files.
There is a [tree-sitter-htmldjango](https://github.com/interdependence/tree-sitter-htmldjango?tab=readme-ov-file), but I have no idea how to set it as a new langue (read the docs on [adding new languages](https://zed.dev/docs/adding-new-languages), still lost)

**Comment by pratyushmittal** [comment] 2024-02-01 10:17
@LucasKuhn I used the option of "local settings" to override the `formatter` only for my Django project. I used this in my project's `.zed/settings.json`:

```
{
  "language_overrides": {
    "HTML": {
      "formatter": {
        "external": {
          "command": ".venv/bin/djlint",
          "arguments": [
            "{buffer_path}",
            "--reformat",
            "--indent",
            "2",
            "--max-blank-lines",
            "2",
            "--profile",
            "django"
          ]
        }
      }
    }
  }
}
```

**Comment by gitKearney** [comment] 2024-02-17 01:47
Thanks for all the suggestions and hard work! Solved my problems

**Comment by ctwillie** [comment] 2024-02-17 02:22
I'm using `venv` for virtual environment management and no modules are recognized in the IDEA. Any help/direction would be much appreciated. Hoping to take this editor for a thorough spin!

**Comment by patgd** [comment] 2024-03-10 18:03
@ctwillie I found [this doc](https://github.com/zed-industries/zed/blob/main/docs/src/languages/python.md) on the topic. Basically, you must create a `pyrightconfig.json` file at the root of your project with the following JSON:
```json
{
  "venvPath": ".",
  "venv": ".venv"
}
```

**Comment by ctwillie** [comment] 2024-03-10 19:19
> @ctwillie I found [this doc](https://github.com/zed-industries/zed/blob/main/docs/src/languages/python.md) on the topic. Basically, you must create a `pyrightconfig.json` file at the root of your project with the following JSON:
> ```json
> {
>   "venvPath": ".",
>   "venv": ".venv"
> }
> ```

Thanks for posting this. I ended up finding the same solution. I should have re-posted here as you did. Thanks again. I can't wait until the git diff feature...

**Comment by hbilal9** [comment] 2024-05-23 07:06
pyrightconfig.json
{
  "venvPath": ".",
  "venv": "venv",
  "pythonPath": "venv/bin/python"
}


but still alot of error

<img width="1170" alt="Screenshot 2024-05-23 at 12 05 43 PM" src="https://github.com/zed-industries/zed/assets/25703314/8b99f890-d65b-456e-8b81-104c7be0dbb8">

<img width="1171" alt="Screenshot 2024-05-23 at 12 06 15 PM" src="https://github.com/zed-industries/zed/assets/25703314/c05d3ee8-9064-448b-b313-1651dbf5cd65">

**Comment by notpeter** [comment] 2024-11-04 00:51
Would anyone who is using Zed for Django be willing to submit a PR with some suggested configuration options to the [python.md](https://github.com/zed-industries/zed/blob/main/docs/src/languages/python.md?plain=1) docs?

**Comment by notpeter** [comment] 2024-11-26 19:34
I'm going to close this in favor of:
- https://github.com/zed-industries/zed/issues/18469

Which has an partially working example for how to get Django / pyright / mypy integration working and a reproduction case for an additional area of improvement.

**Closed by notpeter** 2024-11-26 19:34 UTC
Labels: bug, language
