### ISSUE TITLE
Linux through WSL/Vulcan

### ISSUE THREAD

**Issue by XluuluX** [zed-industries/zed#16810] opened 2024-08-24 20:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I can get the vulcan test cube window, and open other linux apps using my WSL installed ubuntu Linux, but Zed's window won't open... I just get an open prompt that shows it executed successfully without errors listing in the zed logs. Any ideas?
I love that I can open linux apps and have them alongside my window's apps... and if I could get Zed open as well, this would be a game changer for me.

### Environment

See image
![image](https://github.com/user-attachments/assets/27787d5d-fb5f-4d96-93f2-eca3eefa31ff)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/8495ea7e-5a2f-4d23-a886-dd0f60744d1b)
Vulcan test cube window.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-08-25 11:14
Assuming that the issue is about WSL2 support, it seems to be a duplicate of https://github.com/zed-industries/zed/issues/15295 , so I'll close this one.

**Closed by SomeoneToIgnore** 2024-08-25 11:14 UTC
Labels: defect, triage, admin read
