### ISSUE TITLE
move buffers from one pane to another

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#17468] opened 2024-09-05 23:28 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

a common workflow for me is moving buffers/tabs from one pane to another, 

there is the new `pane: join into next` that merges the two panes together, but what I want is to move a single tab/buffer from one to another. 

AFAIK, this can only be done through the drag and drop ui by selecting the tab and moving it to the other pane. 

If you do not have the tab bar enabled, you can not perform this drag & drop. 

VSCode has several commands for moving a single buffer/tab into a different pane. 

- View: Move Editor into Left Group 
- View: Move Editor into Right Group
- View: Move Editor into Group Above
- View: Move Editor into Group Below
- View: Move Editor into Next Group
- View: Move Editor into Previous Group

it would be nice to support all of these keybindings

**Comment by Moshyfawn** [comment] 2024-09-10 13:35
There's already a feature request for this kind of functionality, so I'll close this issue in favour of the already existing one. Be sure to +👍 the other thread and add any additional information about your use case there.

Duplicate of:
- #14761

**Closed by Moshyfawn** 2024-09-10 13:35 UTC
Labels: enhancement, triage, admin read
