### ISSUE TITLE
Inconsistent block cursor width

### ISSUE THREAD

**Issue by dartt0n** [zed-industries/zed#22486] opened 2024-12-29 18:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Due to old habits, I always use a block cursor with monospaced fonts. I have simply found this combination very useful, as it allows me to know exactly where the cursor is located.
However, recently, I noticed a bug (or unexpected desired solution) - the block cursor width in Zed Editor is inconsistent. More specifically, in the Editor tab (including the AI chat and messages chat), when the cursor is placed on a new-line character, *its width is slightly less* (by 5 pixels on my configuration) then when the cursor is placed on any other character. Such behaviour is **not** represented in the Terminal tab, where the width of the cursor remains constant. I am wondering if this is a bug or a desired solution. If it is the latter, then I would appreciate the option to disable this behaviour.

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![image](https://github.com/user-attachments/assets/844ae6df-fe26-4919-9a58-d6bc0d61919e)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by AaronFeickert** [comment] 2024-12-29 20:56
Duplicate of #22260, which is already fixed by #22275.

**Closed** 2024-12-29 21:42 UTC
Labels: bug, triage, admin read
