### ISSUE TITLE
vim: `vim_mode:false` does not work in project local settings

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#9315] opened 2024-03-14 04:32 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/zed-industries/zed/assets/19868292/2c6c1ddf-4474-4c48-9350-b499259bd761)

vim should be disabled

### Environment

Zed: v0.127.0 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

**Comment by weartist** [comment] 2024-03-23 11:23
@ConradIrwin  I see in the docs that the current configuration options that support local setting to override clobal setting are the only ones, vim_mode are not included, do we need to add vim_mode as well, if needed, I can propose a PR to fix the problem:
https://github.com/zed-industries/zed/blob/7367350f41b98d575aebdfe2206c1723d154d8c9/docs/src/configuring_zed.md?plain=1#L7C1-L22C1

**Comment by ConradIrwin** [comment] 2024-03-25 12:06
Happy for you to send a PR for this

**Comment by weartist** [comment] 2024-03-25 15:37
> Happy for you to send a PR for this

@ConradIrwin hi Conrad, at present, our vim setting changes are completed in the monitoring of global settings, as shown below:
https://github.com/zed-industries/zed/blob/7367350f41b98d575aebdfe2206c1723d154d8c9/crates/vim/src/vim.rs#L87C1-L101C15

If we need to change it to support a local-first setting, we may need to add the vim_mode to the LanguageSettings, and then we can read the latest value of the LanguageSettings when the global file will change from observe_global, but this does not include the listener for the local file change, do you have some suggestions for local setting change?

**Comment by ConradIrwin** [comment] 2024-03-26 15:02
I hadn’t realized why the distinction existed. I don’t think vim mode should be a language setting, so maybe we should not do this (it would be annoying if a colleague accidentally added a vim_mode directive to a project if I didn’t want to use vim mode), or wait until there’s a better way to do any setting per directory.

@0x2CA why did you want this to work?

**Comment by 0x2CA** [comment] 2024-03-26 15:19
> I hadn’t realized why the distinction existed. I don’t think vim mode should be a language setting, so maybe we should not do this (it would be annoying if a colleague accidentally added a vim_mode directive to a project if I didn’t want to use vim mode), or wait until there’s a better way to do any setting per directory.
> 
> @0x2CA why did you want this to work?

In concepts local settings will override global settings, whether it's `vim mode` or `buffer font size` or `extension settings` or `lsp settings`, if it's in a local setting then everyone should be set accordingly, if you don't want everyone to use the same look or keymap or other then you shouldn't have local settings in your project.

**Comment by maxdeviant** [comment] 2024-04-23 17:08
> > I hadn’t realized why the distinction existed. I don’t think vim mode should be a language setting, so maybe we should not do this (it would be annoying if a colleague accidentally added a vim_mode directive to a project if I didn’t want to use vim mode), or wait until there’s a better way to do any setting per directory.
> > @0x2CA why did you want this to work?
> 
> In concepts local settings will override global settings, whether it's `vim mode` or `buffer font size` or `extension settings` or `lsp settings`, if it's in a local setting then everyone should be set accordingly, if you don't want everyone to use the same look or keymap or other then you shouldn't have local settings in your project.

I disagree with this.

I think there are some settings that should be fundamentally left up to user choice and shouldn't be able to be set by the project settings.

**Comment by maxdeviant** [comment] 2024-04-23 17:11
I'm closing this out because this is working as intended from Zed's perspective.

For individual groups of settings we allow controlling what sources they respect based on the desired behavior.

For `vim_mode` in particular we only care about the user setting, as it should be the user who is in control of whether they are using Vim mode or not.

**Closed by maxdeviant** 2024-04-23 17:11 UTC
Labels: defect, vim, setting
