### ISSUE TITLE
Zed Flatpak doesn't SAVE or LOAD Assistant Configuration

### ISSUE THREAD

**Issue by cgraham149** [zed-industries/zed#18257] opened 2024-09-24 03:46 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using the Zed Flatpak.

I added my Anthropic and OpenAI keys in the configuration panel but they do not save. They are only good for that session but if I restart, I have to enter the keys all over again.

I also tried adding the env to settings.json and restarted Zed but they don't load and I am given the "LLM provider not configured" warning and "Open configuration" link.

I added this to the bottomof my settings.json file:

"env": {
    "OPENAI_API_KEY": "my-api-key",
    "ANTHROPIC_API_KEY": "my-api-key"
  }

### Environment

Zed: v0.151.1 (Zed)
OS: Linux Wayland manjaro unknown
Memory: 15.5 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 620 (KBL GT2) || Intel open-source Mesa driver || Mesa 24.1.6-arch1.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Why is Zed looking for "/home/USER/.config/github-copilot" when copilot has not been configured?

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-23T23:25:11.641038072-04:00 [INFO] ========== starting zed ==========
2024-09-23T23:25:11.895634739-04:00 [INFO] perform;
2024-09-23T23:25:11.895694531-04:00 [INFO] authenticate;
2024-09-23T23:25:11.895758494-04:00 [INFO] read_command;
2024-09-23T23:25:11.895840531-04:00 [INFO] Opening main db
2024-09-23T23:25:11.896307987-04:00 [INFO] new;
2024-09-23T23:25:11.896374682-04:00 [INFO] socket reader;
2024-09-23T23:25:11.897010397-04:00 [INFO] keep_updated;
2024-09-23T23:25:11.898115463-04:00 [INFO] Using git binary path: None
2024-09-23T23:25:11.936903735-04:00 [INFO] initializing context server client
2024-09-23T23:25:11.936974763-04:00 [ERROR] No such file or directory (os error 2) about ["/home/USER/.config/github-copilot"]
2024-09-23T23:25:11.937100581-04:00 [INFO] Registering built-in prompt template: content_prompt
2024-09-23T23:25:11.937452618-04:00 [INFO] Registering built-in prompt template: edit_workflow
2024-09-23T23:25:11.93777419-04:00 [INFO] Registering built-in prompt template: step_resolution
2024-09-23T23:25:11.938248518-04:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-09-23T23:25:11.938643355-04:00 [INFO] No prompt template overrides directory found at /home/USER/.var/app/dev.zed.Zed/data/zed/prompt_overrides. Using built-in prompts.
2024-09-23T23:25:11.9389567-04:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-09-23T23:25:11.941635504-04:00 [INFO] performance metrics display disabled
2024-09-23T23:25:11.94170802-04:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-09-23T23:25:11.941780344-04:00 [INFO] Opening main db
2024-09-23T23:25:11.980199172-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:11.980552319-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:11.980840857-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:11.982020174-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:11.982331116-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.034769965-04:00 [INFO] perform;
2024-09-23T23:25:12.034875071-04:00 [INFO] authenticate;
2024-09-23T23:25:12.034965701-04:00 [INFO] read_command;
2024-09-23T23:25:12.035935892-04:00 [INFO] socket reader;
2024-09-23T23:25:12.045557844-04:00 [INFO] new;
2024-09-23T23:25:12.046666598-04:00 [INFO] keep_updated;
2024-09-23T23:25:12.048379344-04:00 [INFO] set status on client 0: Authenticating
2024-09-23T23:25:12.048759467-04:00 [INFO] perform;
2024-09-23T23:25:12.04883066-04:00 [INFO] authenticate;
2024-09-23T23:25:12.048891812-04:00 [INFO] read_command;
2024-09-23T23:25:12.049501388-04:00 [INFO] socket reader;
2024-09-23T23:25:12.054241478-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.054332364-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.054394745-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.054465295-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.05456194-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.054638126-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:12.058970006-04:00 [INFO] new;
2024-09-23T23:25:12.060096996-04:00 [INFO] keep_updated;
2024-09-23T23:25:12.072897597-04:00 [INFO] building git repository, .git path in the worktree: "00-TXT/GitHub/desktop-tutorial/.git"
2024-09-23T23:25:13.631886651-04:00 [INFO] Enabling Vulkan Portability
2024-09-23T23:25:13.631946838-04:00 [INFO] Enabling color space support
2024-09-23T23:25:13.681179187-04:00 [INFO] Adapter: "Intel(R) UHD Graphics 620 (KBL GT2)"
2024-09-23T23:25:13.681279725-04:00 [INFO] No ray tracing extensions are supported
2024-09-23T23:25:13.722341077-04:00 [INFO] Using surface present mode MAILBOX
2024-09-23T23:25:13.723155537-04:00 [WARN] Unable to forbid exclusive full screen
2024-09-23T23:25:13.723753365-04:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-23T23:25:13.723921996-04:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-23T23:25:13.724101393-04:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-09-23T23:25:13.741642992-04:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "Intel(R) UHD Graphics 620 (KBL GT2)", driver_name: "Intel open-source Mesa driver", driver_info: "Mesa 24.1.6-arch1.1" }
2024-09-23T23:25:13.7457122-04:00 [INFO] set status on client 242941: Connecting
2024-09-23T23:25:13.75049686-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:13.75066577-04:00 [INFO] Opening main db
2024-09-23T23:25:13.775337693-04:00 [INFO] Using surface present mode MAILBOX
2024-09-23T23:25:13.776444226-04:00 [WARN] Unable to forbid exclusive full screen
2024-09-23T23:25:13.777223445-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:13.77734118-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:13.779285567-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:13.780450616-04:00 [INFO] time to first window draw: 2.139954445s
2024-09-23T23:25:13.782541087-04:00 [INFO] Node runtime install_if_needed
2024-09-23T23:25:13.783472343-04:00 [INFO] Opening main db
2024-09-23T23:25:13.939030617-04:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-09-23T23:25:13.966140608-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:13.973098764-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:13.973400634-04:00 [INFO] starting language server. binary path: "/home/USER/.var/app/dev.zed.Zed/data/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/USER/.var/app/dev.zed.Zed/data/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-09-23T23:25:13.975532112-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:13.97565655-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:13.978656942-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:13.978786595-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.031368125-04:00 [INFO] set environment variables from shell:/bin/zsh, path:/home/USER/.nvm/versions/node/v20.8.1/bin:/home/USER/.local/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2024-09-23T23:25:14.090149841-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.090252443-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.090321534-04:00 [INFO] starting language server "tailwindcss-language-server", path: "/home/USER/_dev/GStrategy/html", id: 1
2024-09-23T23:25:14.090411751-04:00 [INFO] starting language server "vscode-html-language-server", path: "/home/USER/_dev/GStrategy/html", id: 2
2024-09-23T23:25:14.091613417-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.091718205-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.09355089-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.093625042-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.093680283-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.093737289-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.093810924-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.09388591-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.093960228-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.10336836-04:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-09-23T23:25:14.103483391-04:00 [INFO] Node runtime install_if_needed
2024-09-23T23:25:14.108645467-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.108729439-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.108808755-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.108938668-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.109024347-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.109162214-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.109227741-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.110359718-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:14.110842498-04:00 [INFO] add connection to peer
2024-09-23T23:25:14.110893847-04:00 [INFO] add_connection;
2024-09-23T23:25:14.110986432-04:00 [INFO] waiting for server hello
2024-09-23T23:25:14.111365015-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:14.111907994-04:00 [INFO] got server hello
2024-09-23T23:25:14.111963489-04:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 543, id: 3413965 })
2024-09-23T23:25:14.112038474-04:00 [INFO] set status on client 242941: Connected { peer_id: PeerId { owner_id: 543, id: 3413965 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-09-23T23:25:14.234776671-04:00 [INFO] Node runtime install_if_needed
2024-09-23T23:25:14.281870505-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.282029536-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.282271752-04:00 [INFO] Initializing default prettier with plugins {}
2024-09-23T23:25:14.282406282-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.282477942-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.282547508-04:00 [INFO] starting language servers for Markdown: 
2024-09-23T23:25:14.282615042-04:00 [INFO] starting language servers for HTML: tailwindcss-language-server, vscode-html-language-server
2024-09-23T23:25:14.30910204-04:00 [WARN] request completed with error: failed to connect to the server
2024-09-23T23:25:14.626290509-04:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-24T03:25:14.617Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-09-24T03:25:14.617Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-09-23T23:25:14.631088283-04:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "2fc8c51c-c661-45fc-a0e4-8d80f0f3f3ed",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-09-23T23:25:14.691709534-04:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-24T03:25:14.642Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-09-24T03:25:14.642Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-09-23T23:25:14.999313948-04:00 [INFO] downloading language server "tailwindcss-language-server"
2024-09-23T23:25:14.999902129-04:00 [INFO] Node runtime install_if_needed
2024-09-23T23:25:15.135587082-04:00 [INFO] starting language server. binary path: "/home/USER/.var/app/dev.zed.Zed/data/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/home/USER/_dev/GStrategy/html", args: ["/home/USER/.var/app/dev.zed.Zed/data/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-09-23T23:25:15.692718873-04:00 [INFO] Node runtime install_if_needed
2024-09-23T23:25:15.807554049-04:00 [INFO] starting language server. binary path: "/home/USER/.var/app/dev.zed.Zed/data/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/home/USER/_dev/GStrategy/html", args: ["/home/USER/.var/app/dev.zed.Zed/data/zed/extensions/work/html/node_modules/@zed-industries/vscode-langservers-extracted/bin/vscode-html-language-server", "--stdio"]
2024-09-23T23:25:16.720587352-04:00 [WARN] unhandled capability registration: Registration { id: "51322d68-4060-4907-b38c-d0391e770938", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-09-23T23:25:17.17286709-04:00 [WARN] unhandled capability registration: Registration { id: "5e8d9767-73b9-4538-ae3e-08e315661117", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
</pre></details>

**Comment by notpeter** [comment] 2024-09-24 17:49
The github-copilot error in the logs is harmless. Duplicate of:
- https://github.com/zed-industries/zed/issues/17831

The `env` settings key is only for terminals (and you should not store secrets in your zed settings):
https://github.com/zed-industries/zed/blob/8a7ef4db59668f9dda841a9550abd1cc78651fa3/assets/settings/default.json#L698-L702

The preferred method is to leverage a keyring and if you have one available Zed will store API keys there when they are entered into the Assistant configuration panel. Do you have a keyring configured (e.g. gnome-keyring)? If you have a keyring setup, perhaps this is a flatak related issue.

Alternatively if you have those environment variables set in the shell when you launch the `zed` command from a terminal (e.g. `export OPENAI_API_KEY="whatever"` in your `.bashrc`) then zed will load secrets from there, but keyring is the preferred configuration method.

**Closed** 2024-09-24 22:16 UTC
Labels: defect, linux, setting, ai, support
