### ISSUE TITLE
Drag & Drop from Finder

### ISSUE THREAD

**Issue by fschlegelone** [zed-industries/zed#8388] opened 2024-02-25 15:17 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In VSC its possible to drag n drop files & directories in the file explorer. In Zed that's not possible yet.

### If applicable, add mockups / screenshots to help present your vision of the feature

![CleanShot 2024-02-25 at 16 15 16@2x](https://github.com/zed-industries/zed/assets/118682177/12542a3d-3428-4361-bbc1-c3a98e4e2669)

**Comment by SomeoneToIgnore** [comment] 2024-02-25 15:25
Duplicate of https://github.com/zed-industries/zed/issues/7386

**Closed by SomeoneToIgnore** 2024-02-25 15:25 UTC
Labels: enhancement, triage, admin read
