### ISSUE TITLE
LSP: diagnostic fixit is not provided with clangd

### ISSUE THREAD

**Issue by hokein** [zed-industries/zed#4757] opened 2023-05-07 22:13 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open a t.cpp with the following content

```
void k(int a) {
  if (a = 1) {
  }
}
```
3. wait for the C++ language server clangd warm up.
4. move the cursor to the diagnostic range `a = 1`, a `Using the result of an assignment as a condition without parentheses (fixes available)` diagnostic is shown. 

There is no way to get and apply the fixit in zed, press `cmd-.` (trigger the code-action) doesn't have any effect.

### Environment

Zed: v0.84.4 (stable)
OS: macOS 13.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I would expect there is a way to view alternative fixes and apply the fix, 

The workflow in VSCode:
1. move the cursor to the diagnostic, a yellow light bulb shown up.
2. click the bulb, we can see all alternative fixes, select one will apply the fix.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/2557445/236704982-ce126742-167f-41e9-b3f2-c2a735e81e3e.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by WeetHet** [comment] 2024-03-27 09:55
> Looking at the clangd log, the range of the diagnostic is wrong (`{0, 0} - {0, 0}`), I believe this is the root cause.
> 
> ```
> // Send:
> {"jsonrpc":"2.0","id":198,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///private/tmp/t.cpp"},"range":{"start":{"line":1,"character":9},"end":{"line":1,"character":9}},"context":{"diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":2,"code":"-Wparentheses","message":""}],"only":["","quickfix","refactor","refactor.extract","source"]}}}
> ```

This is weird, let's look into this. I'll try hardcoding the path to macos' clangd to see if its a problem with the clangd used or zed itself

**Comment by WeetHet** [comment] 2024-03-27 11:52
> Looking at the clangd log, the range of the diagnostic is wrong (`{0, 0} - {0, 0}`), I believe this is the root cause.
> 
> ```
> // Send:
> {"jsonrpc":"2.0","id":198,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///private/tmp/t.cpp"},"range":{"start":{"line":1,"character":9},"end":{"line":1,"character":9}},"context":{"diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":2,"code":"-Wparentheses","message":""}],"only":["","quickfix","refactor","refactor.extract","source"]}}}
> ```

Seems like it yeah. This happens for every language, but clangd seems to be unable to process is correctly

**Comment by WeetHet** [comment] 2024-03-27 11:54
@as-cii, this seems like your area of expertise

**Comment by WeetHet** [comment] 2024-03-27 12:11
This code looks weird:
https://github.com/zed-industries/zed/blob/63f17c50b9f2ca7d8ce0381fd58d5ac9930dfdf3/crates/editor/src/editor.rs#L3725-L3741

Why are code actions requested only for the selection? Is this intended?

**Comment by mrnugget** [comment] 2024-04-10 04:57
This is fixed by #10281, I just confirmed it. Diagnostics won't work without the fix, but with the fix I get this:

![screenshot-2024-04-10-06 54 36@2x](https://github.com/zed-industries/zed/assets/1185253/d6070f65-4651-4af1-bc58-f3c81d0041cc)

**Closed by mrnugget** 2024-04-10 04:57 UTC
Labels: defect, c++, language, c, language server
