### ISSUE TITLE
Overheating Intel Macbook Air when having Zed open on sleep mode/closed lid

### ISSUE THREAD

**Issue by matteoquesada** [zed-industries/zed#17513] opened 2024-09-06 18:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Greetings,
I'm on Zed v: 0.151.2 and MacOS Sonoma 14.6.1.

Seems like there's an issue with Zed on these versions. Me and my friend have MacBook Airs (2019 and 2020) both fully updated to sonoma. Couple of days ago I just closed my Mac as usual and saved it into a protective plastic bag + carrying case to move around uni. I have powernap and other sleeping settings disabled as I just want my device to fully sleep without any weird updates or internet waking things. 

At the moment I had multiple apps (+6) open including Zed. As I went to open up my Mac to use again I found out it was like 105C literally about to burn when I got it out. My battery was at around 52C and other components hovering around 55C, CPU at 105C.

After individually testing which app had sleeping issues I figured out it was Zed. My battery got exposed to high temps for like two hours due to this. Literal damage dude.

PLEASE FIX THIS ISSUE. DUE TO TESTING ITS ALSO PROVEN TO HAPPEN TO 2020 Intel MACBOOK AIRS. PLEASE.

### Environment

Zed: v0.151.2 (Zed)
OS: macOS 14.6.1
Memory: 16GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-09-06 19:37
Duplicate of https://github.com/zed-industries/zed/issues/17305 and https://github.com/zed-industries/zed/issues/16729

That should be fixed in Zed Preview v0.152.1 and Zed Stable v0.151.2 which were released today.
You mention 

> Couple of days ago

so please give it a test now and see how it works.

Will close for now as many other intel-based people reported that it's fixed and the data in the issue is quite confusing (version number that was released today and the issue related to a couple of days ago)

**Closed by SomeoneToIgnore** 2024-09-06 19:37 UTC
Labels: defect, triage, admin read
