### ISSUE TITLE
Zed doesn't open the new instance if one instance is already running

### ISSUE THREAD

**Issue by sonulohani** [zed-industries/zed#16224] opened 2024-08-14 14:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When one instance of zed is already running, if I try to open another instance of zed, it doesn't open. The use case is, If I open 1.txt file and try to open another file 2.txt for example, it doesn't open that until I close the running zed.

### Environment

Zed: v0.147.2 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 31 GiB
Architecture: x86_64
GPU: NVIDIA RTX A2000 8GB Laptop GPU || NVIDIA || 535.183.01

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/790d6809-82e7-4c1d-a134-f0499c0140a7

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-14 14:47
1. Can you provide some explicit reproduction steps so I can see if I can get it to break on my Linux machine?
2. Could you also paste your Zed environment into the description ("zed: copy system specs into clipboard")?

Thanks

**Comment by sonulohani** [comment] 2024-08-14 14:54
> 1. Can you provide some explicit reproduction steps so I can see if I can get it to break on my Linux machine?
> 
>     2. Could you also paste your Zed environment into the description ("zed: copy system specs into clipboard")?
> 
> 
> Thanks

Done, I have added video, Could you please check and let me know if you have understood the issue? Thanks

**Comment by notpeter** [comment] 2024-08-14 17:53
I can reproduce this.  Using "Open With" from my file explorer on Linux (Dophin) works correctly. But if I have an pre-existing Zed Window open, attempting to open a file using "Open With" Zed does nothing.

Thanks for reporting.

**Comment by osiewicz** [comment] 2024-08-14 18:26
This may be related to https://github.com/zed-industries/zed/blob/main/crates/zed/src/zed/only_instance.rs

**Comment by AndydeCleyre** [comment] 2024-10-10 23:06
I just solved this locally by replacing instances of `%U` in the `.desktop` file with `%F` -- see https://specifications.freedesktop.org/desktop-entry-spec/latest/exec-variables.html

**Comment by AndydeCleyre** [comment] 2024-10-11 04:03
Taking a look at the difference between the `.desktop` file and the command line, I see the former uses `~/.local/zed.app/libexec/zed-editor`, while the `zed` in `PATH` is a link to `~/.local/zed.app/bin/zed`.

Using each of those on the command line directly confirms that the former exhibits this issue, while the latter does not.

**Comment by skewty** [comment] 2024-10-26 19:52
Zed does not open an additional file if it is already running.

The expectation is for it to open a new tab with an additional file.

Trying to run the command from my .desktop file in a terminal I get

```shell
/home/myuser/.local/zed.app/libexec/zed-editor anotherfile.py
zed is already running
```

Which means you can only use Zed to edit one file at a time using non Zed GUI / file manager.

Steps to Reproduce
-----------------------
1. Open Nautilus file manager
2. Navigate to a folder with several text files in it.
3. Double click on file1.txt
4. Double click on file2.txt

Zed will open with file1.txt, but not file2.txt.

**Comment by 0xtimsb** [comment] 2024-12-05 09:48
This seems like duplicate of #20070, and it was fixed in [this](https://github.com/zed-industries/zed/pull/21137) PR.

**Comment by skewty** [comment] 2024-12-06 03:46
I just tried opening a few files with a project open in Zed and neither of the files was added as a tab. Seems to still be broken / not fixed.

**Comment by 0xtimsb** [comment] 2024-12-08 12:13
@skewty, it looks like you're using the Stable release. This issue is fixed in the Preview release as of now. If you're already using Preview and still seeing this issue, could you share `.local/share/applications/dev.zed.Zed-Preview.desktop`?

**Comment by skewty** [comment] 2024-12-08 14:40
> @skewty, it looks like you're using the Stable release. This issue is fixed in the Preview release as of now. If you're already using Preview and still seeing this issue, could you share `.local/share/applications/dev.zed.Zed-Preview.desktop`?

Installed preview and it is now working for me.

I believe this issue should now be closed as completed with a link to the commit and or build it was fixed in. This will hopefully provide enough info so others don't expect to see it fixed in current stable as I did.

**Comment by SomeoneToIgnore** [comment] 2024-12-09 11:02
Fixed in https://github.com/zed-industries/zed/pull/21137

**Closed by SomeoneToIgnore** 2024-12-09 11:02 UTC
Labels: bug, needs info / awaiting response, workspace, linux
