### ISSUE TITLE
HTML template string highlighting

### ISSUE THREAD

**Issue by dev-davexoyinbo** [zed-industries/zed#8937] opened 2024-03-06 07:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Good work on the zed editor, I love the minimalist design and speed but I would love to have HTML string highlighting for template strings as I work with html in strings a lot. Check the attached image (Note that in the image I am using vue but with the template strings)
<img width="634" alt="image" src="https://github.com/zed-industries/zed/assets/67616046/257bf901-9a98-4e8c-9cdb-a826dbf28f4d">

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="634" alt="image" src="https://github.com/zed-industries/zed/assets/67616046/ae7e4c65-ef12-4959-84a5-5a97dbed1e49">

**Comment by Moshyfawn** [comment] 2024-03-06 14:07
I believe this is already an existing feature request. I'll close this thread in favour of the other one. Be sure to +👍 it to show your interest and add any additional information that may be missing.

**Comment by Moshyfawn** [comment] 2024-03-06 14:07
Duplicate of
- #4748

**Closed** 2024-03-06 14:07 UTC
Labels: enhancement, triage, admin read
