### ISSUE TITLE
failed to parse Git remote URL

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#19735] opened 2024-10-25 12:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

my project git remote liking: 

```
$ git remote -v
origin	git@gitlab.xx-inc.com:abc_def/abd-def.git (fetch)
origin	git@gitlab.xx-inc.com:abc_def/abd-def.git (push)
```

When I execute `editor: copy permalink to line` action, zed failed as:
![image](https://github.com/user-attachments/assets/9fe4d4c2-a1b4-4164-8ac7-50f310d39b0b)

### Environment

Zed: v0.160.0 (Zed Dev 0173479d18e2526c1f9c8b25ac94ec66b992a2b2)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by dpvpro** [comment] 2024-10-28 13:35
Same

**Comment by collinmurch** [comment] 2024-10-29 02:50
Addressed in https://github.com/zed-industries/zed/pull/19868, let me know if there's anything else I can do or if there are additional comments.

**Comment by collinmurch** [comment] 2024-10-29 03:31
They closed the MR 😢

**Comment by notpeter** [comment] 2024-10-29 04:58
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/18012

Please 👍 that issue if you would like to encourage its prioritization.
You can also subscribe to be notified of progress.
Thanks for reporting.

**Closed by notpeter** 2024-10-29 04:58 UTC
Labels: defect, editor, git
