### ISSUE TITLE
Integrated REST client

### ISSUE THREAD

**Issue by ottob** [zed-industries/zed#21995] opened 2024-12-13 22:08 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I really enjoyed using [Requester](https://kylebebak.github.io/Requester/) in sublime text. And [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) seems to be a similar option for VS code. It would be very useful if zed could offer something similar.

### Environment

Zed 0.165.4 macOS 15.2

**Comment by jansol** [comment] 2024-12-14 00:33
Duplicate of zed-industries/extensions#512

**Closed by jansol** 2024-12-14 00:33 UTC
Labels: enhancement, triage, admin read
