### ISSUE TITLE
New Zed Project Template

### ISSUE THREAD

**Issue by felipetesc** [zed-industries/zed#12936] opened 2024-06-12 17:07 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Add a new list item to the panel which is callable from the command ctrl-shift-p to allow us to create a new blanc project containing .zed folder and all custom json files. 
The list item can be called _**zed: new project**_

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/2336812/bdfeb3ba-3a93-409e-9057-b5eaee1b181f)

**Comment by someone13574** [comment] 2024-06-12 22:10
Duplicate of https://github.com/zed-industries/zed/issues/11280

**Closed** 2024-06-12 23:28 UTC
Labels: enhancement, triage, admin read

**Comment by Moshyfawn** [comment] 2024-06-12 23:56
Be sure to +👍 and follow the other thread.
