### ISSUE TITLE
Bugs after sleep in linux

### ISSUE THREAD

**Issue by indrakhatiwada** [zed-industries/zed#18551] opened 2024-09-30 19:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

  
Multiple Bugs appear on Linux version of Zed. I am going to list some of them here. Most of them appear after the computer is locked. OS:  Ubuntu 24.04.1 LTS x86_64 

 1. Zed Freezes. There is no response from the Editor, You cannot close it from the tray too. 
 2. Opens any software that is recently opened. 
 - Example would be : I have an instance of Zed, and VLC running on the background, when the computer sleeps and i re open it, instead of opeining Zed, it opens VLC, or Firefox on Zed window, pic related
![Screenshot from 2024-10-01 01-16-58](https://github.com/user-attachments/assets/91a94341-794d-414e-8f1e-4952ba250bb5)
3.  The window keeps on Scrolling, the cursor keeps on jumping to the EOF.

### Environment

OS: Ubuntu 24.04.1 LTS x86_64 
   Host: 82B5 Lenovo Legion 5 
Kernel: 6.8.0-45-generic 

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/17195741/Zed.log)

**Comment by JosephTLyons** [comment] 2024-10-03 15:18
Hey @indrakhatiwada,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/18478

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-10-03 15:18 UTC
Labels: defect, linux, freeze
