### ISSUE TITLE
Extension search including descriptions

### ISSUE THREAD

**Issue by brandondrew** [zed-industries/zed#18311] opened 2024-09-24 23:50 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It appears that any searches through extensions only use the names of the Extensions, since a search for "theme" fails to turn up the them that is clearly in my list of uninstalled extensions. 

<img width="887" alt="image" src="https://github.com/user-attachments/assets/632161b8-33f7-425b-b08e-3b64fce709c4">

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/c842a183-5510-4fed-a711-2422ed140bfe">

This would make it much easier to find extensions and themes, in general, but it would also make it easier to filter out themes while we wait for the UI to give us a way to automatically filter between normal extensions and themes. 

(Currently I just install *all* themes in order to remove them from the extensions listed as "Not Installed".  Then I can scroll to the bottom and expect that most new extensions will have a relatively low number of downloads and thus be near the bottom of the list.)

**Comment by brandondrew** [comment] 2024-09-24 23:51
Of course words in the extension's name/title should be given more weight.

**Comment by JosephTLyons** [comment] 2024-10-01 19:51
Hey @brandondrew

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/10340

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-10-01 19:51 UTC
Labels: enhancement, extension infrastructure

**Comment by brandondrew** [comment] 2024-10-02 16:12
@JosephTLyons yes, you're correct!  I'm not sure how I missed that when I was searching--I must have had different search terms in mind when I searched, and then thought of a better description when I wrote the title.
