### ISSUE TITLE
zed  crash when string fuzzy matching

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#21837] opened 2024-12-11 03:46 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

``` sh
[2024-12-11T11:43:47+08:00 DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(35), flags: (0x5: END_HEADERS | END_STREAM) }
Thread "main" panicked with "called `Option::unwrap()` on a `None` value" at crates/fuzzy/src/strings.rs:81:42
   0: backtrace::backtrace::libunwind::trace
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/libunwind.rs:116:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/capture.rs:292:9
   3: backtrace::capture::Backtrace::new
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.74/src/capture.rs:257:22
   4: zed::reliability::init_panic_hook::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/zed/src/reliability.rs:60:29
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2084:9
      std::panicking::rust_panic_with_hook
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:808:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
   7: std::sys::backtrace::__rust_end_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
   8: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   9: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  10: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
  11: core::option::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:2020:5
  12: core::option::Option<T>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/option.rs:970:21
      fuzzy::strings::StringMatch::char_len_at_index
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/fuzzy/src/strings.rs:81:9
  13: fuzzy::strings::StringMatch::ranges::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/fuzzy/src/strings.rs:67:32
  14: <core::iter::sources::from_fn::FromFn<F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/sources/from_fn.rs:69:9
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/map.rs:108:9
  16: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  17: core::iter::adapters::chain::and_then_or_clear
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/chain.rs:333:13
  18: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::next
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/chain.rs:84:9
  19: gpui::style::combine_highlights
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/style.rs:884:31
  20: editor::code_context_menus::CompletionsMenu::render::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/editor/src/code_context_menus.rs:499:42
  21: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/map.rs:89:28
  22: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/enumerate.rs:108:27
  23: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/iter/macros.rs:232:27
  24: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/enumerate.rs:114:9
  25: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/adapters/map.rs:129:9
  26: core::iter::traits::iterator::Iterator::for_each
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/traits/iterator.rs:818:9
  27: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/mod.rs:3113:17
  28: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/spec_extend.rs:26:9
  29: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  30: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/spec_from_iter.rs:33:9
  31: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/mod.rs:2977:9
  32: core::iter::traits::iterator::Iterator::collect
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/iter/traits/iterator.rs:2005:9
  33: editor::code_context_menus::CompletionsMenu::render::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/editor/src/code_context_menus.rs:485:17
  34: gpui::elements::uniform_list::uniform_list::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/uniform_list.rs:40:13
  35: <gpui::window::WindowContext as gpui::VisualContext>::update_view
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:3955:22
  36: gpui::view::View<V>::update
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/view.rs:77:9
  37: gpui::elements::uniform_list::uniform_list::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/uniform_list.rs:39:9
  38: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2084:9
  39: <gpui::elements::uniform_list::UniformList as gpui::element::Element>::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/uniform_list.rs:333:37
  40: gpui::elements::div::Interactivity::prepaint::{{closure}}::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1421:38
  41: gpui::window::WindowContext::with_content_mask
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1854:26
  42: gpui::elements::div::Interactivity::prepaint::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1413:21
  43: gpui::window::WindowContext::with_text_style
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1800:13
  44: gpui::elements::div::Interactivity::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1412:17
  45: gpui::window::WindowContext::with_optional_element_state::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:2189:39
  46: gpui::window::WindowContext::with_element_state
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:2140:35
  47: gpui::window::WindowContext::with_optional_element_state
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:2188:13
  48: gpui::elements::div::Interactivity::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1390:9
  49: <gpui::elements::uniform_list::UniformList as gpui::element::Element>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/uniform_list.rs:253:9
  50: gpui::element::Drawable<E>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:332:21
  51: <gpui::element::Drawable<E> as gpui::element::ElementObject>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:452:9
  52: gpui::element::AnyElement::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:499:9
  53: <gpui::elements::anchored::Anchored as gpui::element::Element>::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/anchored.rs:190:17
  54: gpui::window::WindowContext::with_element_offset
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1876:20
  55: <gpui::elements::div::Div as gpui::element::Element>::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1222:17
  56: gpui::elements::div::Interactivity::prepaint::{{closure}}::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1421:38
  57: gpui::window::WindowContext::with_content_mask
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1858:13
  58: gpui::elements::div::Interactivity::prepaint::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1413:21
  59: gpui::window::WindowContext::with_text_style
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1800:13
  60: gpui::elements::div::Interactivity::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1412:17
  61: gpui::window::WindowContext::with_optional_element_state
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:2195:35
  62: gpui::elements::div::Interactivity::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1390:9
  63: <gpui::elements::div::Div as gpui::element::Element>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1216:9
  64: gpui::element::Drawable<E>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:332:21
  65: <gpui::element::Drawable<E> as gpui::element::ElementObject>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:452:9
  66: gpui::element::AnyElement::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:499:9
  67: <gpui::elements::anchored::Anchored as gpui::element::Element>::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/anchored.rs:190:17
  68: gpui::window::WindowContext::with_element_offset
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1876:20
  69: <gpui::elements::div::Div as gpui::element::Element>::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1222:17
  70: gpui::elements::div::Interactivity::prepaint::{{closure}}::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1421:38
  71: gpui::window::WindowContext::with_content_mask
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1858:13
  72: gpui::elements::div::Interactivity::prepaint::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1413:21
  73: gpui::window::WindowContext::with_text_style
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1800:13
  74: gpui::elements::div::Interactivity::prepaint::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1412:17
  75: gpui::window::WindowContext::with_optional_element_state
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:2195:35
  76: gpui::elements::div::Interactivity::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1390:9
  77: <gpui::elements::div::Div as gpui::element::Element>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/elements/div.rs:1216:9
  78: gpui::element::Drawable<E>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:332:21
  79: <gpui::element::Drawable<E> as gpui::element::ElementObject>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:452:9
  80: gpui::element::AnyElement::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:499:9
  81: <gpui::element::Component<C> as gpui::element::Element>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:201:9
  82: gpui::element::Drawable<E>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:332:21
  83: <gpui::element::Drawable<E> as gpui::element::ElementObject>::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:452:9
  84: gpui::element::AnyElement::prepaint
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/element.rs:499:9
  85: gpui::window::WindowContext::prepaint_tooltip::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1592:71
  86: gpui::window::WindowContext::with_absolute_element_offset
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1897:22
  87: gpui::window::WindowContext::prepaint_deferred_draws
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1620:17
  88: gpui::window::WindowContext::draw_roots
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1518:9
  89: gpui::window::WindowContext::draw
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:1432:9
  90: gpui::window::Window::new::{{closure}}::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:707:33
  91: <gpui::app::AppContext as gpui::Context>::update_window::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/app.rs:1493:26
  92: gpui::app::AppContext::update
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/app.rs:411:22
  93: <gpui::app::AppContext as gpui::Context>::update_window
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/app.rs:1484:9
  94: <gpui::app::async_context::AsyncAppContext as gpui::Context>::update_window
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/app/async_context.rs:91:9
  95: gpui::window::AnyWindowHandle::update
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:4842:9
  96: gpui::window::Window::new::{{closure}}::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:705:25
  97: util::measure
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/util/src/util.rs:199:9
  98: gpui::window::Window::new::{{closure}}
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/window.rs:704:21
  99: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2077:9
 100: gpui::platform::mac::window::step
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/platform/mac/window.rs:1643:9
 101: <unknown>
 102: <unknown>
 103: <unknown>
 104: <unknown>
 105: <unknown>
 106: <unknown>
 107: <unknown>
 108: <unknown>
 109: <unknown>
 110: <unknown>
 111: <unknown>
 112: <unknown>
 113: <unknown>
 114: <unknown>
 115: <unknown>
 116: <() as objc::message::MessageArguments>::invoke
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
 117: objc::message::platform::send_unverified
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27:9
 118: objc::message::send_message
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178:5
      <*mut objc::runtime::Object as cocoa::appkit::NSApplication>::run
             at /Users/alizj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cocoa-0.26.0/src/appkit.rs:628:9
 119: <gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/platform/mac/platform.rs:453:13
 120: gpui::app::App::run
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/gpui/src/app.rs:161:9
 121: zed::main
             at /Users/alizj/go/src/github.com/zed-industries/zed/crates/zed/src/main.rs:248:5
 122: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
 123: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
 124: std::rt::lang_start::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
 125: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
      std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
      std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
      std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
      std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
      std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
      std::rt::lang_start_internal
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
 126: std::rt::lang_start
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
 127: _main


```

### Environment

Zed: v0.166.0 (Zed Dev 28faba12a2799ef535aaf3158f7437f70ff523c8)
OS: macOS 15.1.0
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by 0xtimsb** [comment] 2024-12-11 04:01
Can you provide steps to reproduce?

**Comment by opsnull** [comment] 2024-12-11 07:50
> Can you provide steps to reproduce?

This issue occurs randomly and occasionally causes a panic when performing name or type name auto-completion suggestions.

**Comment by opsnull** [comment] 2024-12-11 12:18
@0xtimsb Please see this GIF crash case:

![Dec-11-2024 20-16-48](https://github.com/user-attachments/assets/0e23e9c2-6491-47f0-b67c-33d5715ac69d)

**Comment by JosephTLyons** [comment] 2024-12-12 17:37
Huh, I'm not able to reproduce - wonder why.

**Comment by 0xtimsb** [comment] 2024-12-12 19:01
I was also not able to reproduce this issue.

@opsnull, it would be helpful if you could provide a minimal example repo to reproduce this, along with the exact characters to type where it breaks for you.

I understand this might be a bit much to ask, but it would really help me figure out what’s going on.

**Comment by s3bba** [comment] 2024-12-14 14:59
> Huh, I'm not able to reproduce - wonder why.

I have spent days trying to find a way to reproduce this with no luck, it just does randomly.

Anyway this [PR](https://github.com/zed-industries/zed/pull/21983) partially solves the problem and [comment](https://github.com/zed-industries/zed/pull/21983#issuecomment-2543138339) I left on it to, fully prevents the crash. 

But! I just created a prevention, someone (who is familiar with fuzzy crate) needs to decide what to do when this occurs because just returning `None` would exclude a potentially correct result just because it contains multi-byte UTF-8 chars - This also might not be 100% correct because I'm not familiar with fuzzy crate.

Good luck :p

**Comment by opsnull** [comment] 2024-12-15 06:10
@s3bba Thank you for taking the time to investigate this issue. I believe you have identified the root cause, which is very helpful for fixing the problem. Looking forward to seeing the Zed team resolve this annoying issue. Thanks again!

**Comment by mgsloan** [comment] 2024-12-15 08:19
Thanks for investigating @s3bba @0xtimsb etc!  #22032 updates it to also not panic if indexing isn't on unicode boundaries.

It is certainly a tricky bug, where #21521 interacted poorly with how completion fuzzy matching works.

* `StringMatchCandidate` is being built from the initial completions list.  Fuzzy match can be restricted to just a portion of the completion label (say, the name of the thing).
* [Here](https://github.com/zed-industries/zed/blob/341e65e12289c355cbea6e91daee5493bbac921f/crates/editor/src/code_context_menus.rs#L604), the fuzzy match results are updated to include the full label, and the fuzzy match result positions are offset to be in the correct place.

#21521 added support for changing the labels on documentation resolve.  When the label of a completion changes this can result in the offset fuzzy match positions to be wrong.

At first I was going to revert that PR.  Part of my thought process was that if the label does get updated then couldn't this cause items to disappear from the list, even your selection might disappear causing inadvertent selections.  However, I realized a solution: refuse to update the label if it changes the fuzzy match text.  This allows display updates but won't affect which completions are displayed.

**Comment by mgsloan** [comment] 2024-12-16 08:22
Found a fix for this that was much less complex than the alternatives I was attempting :)

**Closed** 2024-12-16 08:21 UTC
Labels: bug, panic / crash, editor, autocompletions
