### ISSUE TITLE
Cannot use Language servers when on Company network due to Self Signed Cert in chain

### ISSUE THREAD

**Issue by cyeganeh01248** [zed-industries/zed#9884] opened 2024-03-27 18:28 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When on the my companies network, I'm unable to get the language server features to work properly. The bundled npm will try to install pyright and will fail due to certificate validation. Please add support for reading from the ~/.npmrc file to allow pulling this config and working with custom CA's.

Adding env variables also seems to be ignored. 

### Environment

Specs:
CPU: Apple M2 Max
Memory: 32 GB
OS: macOS Sonoma Version 14.3.1
Zed Version: 0.128.3

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

>>> cat Zed.log
2024-03-27T14:23:59-04:00 [INFO] ========== starting zed ==========
2024-03-27T14:23:59-04:00 [INFO] Opening main db
2024-03-27T14:23:59-04:00 [ERROR] crates/settings/src/keymap_file.rs:89: invalid binding value for keystroke backspace, context Some("ProjectPanel")

Caused by:
    0: Attempting to build action project_panel::Delete
    1: missing field `skip_prompt`
2024-03-27T14:23:59-04:00 [ERROR] crates/settings/src/keymap_file.rs:89: invalid binding value for keystroke delete, context Some("ProjectPanel")

Caused by:
    0: Attempting to build action project_panel::Delete
    1: missing field `skip_prompt`
2024-03-27T14:23:59-04:00 [ERROR] crates/zed/src/zed.rs:622: EOF while parsing a value at line 1 column 0
2024-03-27T14:23:59-04:00 [INFO] Opening main db
2024-03-27T14:23:59-04:00 [INFO] Opening main db
2024-03-27T14:23:59-04:00 [INFO] set status on client 0: Authenticating
2024-03-27T14:23:59-04:00 [INFO] Opening main db
2024-03-27T14:23:59-04:00 [INFO] set status on client 144406: Connecting
2024-03-27T14:23:59-04:00 [INFO] starting language server "pyright", path: "/Users/<MASKED>/Code/TestingStuff/t1-p", id: 1
2024-03-27T14:23:59-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:00-04:00 [INFO] response dropped without fully consuming the response body, connection won't be reused
Aborting a response without fully consuming the response body can result in sub-optimal performance. See https://github.com/sagebind/isahc/wiki/Connection-Reuse#closing-connections-early.
2024-03-27T14:24:00-04:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-03-27T14:24:00-04:00 [INFO] add connection to peer
2024-03-27T14:24:00-04:00 [INFO] waiting for server hello
2024-03-27T14:24:00-04:00 [INFO] got server hello
2024-03-27T14:24:00-04:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 381, id: 28854 })
2024-03-27T14:24:00-04:00 [INFO] set status on client 144406: Connected { peer_id: PeerId { owner_id: 381, id: 28854 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-03-27T14:24:01-04:00 [INFO] set environment variables from shell:/bin/zsh, path:/Users/<MASKED>/.pydir/bin:/Users/<MASKED>/.cargo/bin:/Users/<MASKED>/.pdtm/go/bin:/Users/<MASKED>/go/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/opt/curl-openssl/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/usr/local/laps:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/<MASKED>/.cargo/bin:/Users/<MASKED>/Library/Application Support/JetBrains/Toolbox/scripts
2024-03-27T14:24:01-04:00 [INFO] fetching latest version of language server "pyright"
2024-03-27T14:24:02-04:00 [INFO] starting language server. binary path: "/Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/", args: ["/Users/<MASKED>/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-03-27T14:24:02-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:02-04:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-27T18:24:02.448Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-03-27T18:24:02.448Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-03-27T14:24:02-04:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "0a6338fa-a9f8-4c96-9c36-f5cbacd1adc7",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-03-27T14:24:02-04:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
2024-03-27T14:24:09-04:00 [INFO] downloading language server "pyright"
2024-03-27T14:24:09-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:17-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:24:17-04:00 [ERROR] failed to start language server "pyright": failed to execute npm install subcommand:
stdout: ""
stderr: "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! errno SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_24_10_504Z-debug-0.log\n"
2024-03-27T14:24:17-04:00 [ERROR] server stderr: Some("")
2024-03-27T14:24:17-04:00 [INFO] retrying installation of language server "pyright" in 1s
2024-03-27T14:24:18-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:24:18-04:00 [INFO] About to spawn test binary
2024-03-27T14:24:18-04:00 [WARN] test binary failed to launch
2024-03-27T14:24:18-04:00 [WARN] test binary check failed
2024-03-27T14:24:18-04:00 [INFO] beginning to reinstall server
2024-03-27T14:24:18-04:00 [INFO] deleting server container
2024-03-27T14:24:18-04:00 [INFO] starting language server "pyright", path: "/Users/<MASKED>/Code/TestingStuff/t1-p", id: 2
2024-03-27T14:24:18-04:00 [INFO] fetching latest version of language server "pyright"
2024-03-27T14:24:18-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:26-04:00 [INFO] downloading language server "pyright"
2024-03-27T14:24:26-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:34-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:24:34-04:00 [ERROR] failed to start language server "pyright": failed to execute npm install subcommand:
stdout: ""
stderr: "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! errno SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_24_27_004Z-debug-0.log\n"
2024-03-27T14:24:34-04:00 [ERROR] server stderr: Some("")
2024-03-27T14:24:34-04:00 [INFO] retrying installation of language server "pyright" in 1s
2024-03-27T14:24:35-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:24:35-04:00 [INFO] About to spawn test binary
2024-03-27T14:24:35-04:00 [WARN] test binary failed to launch
2024-03-27T14:24:35-04:00 [WARN] test binary check failed
2024-03-27T14:24:35-04:00 [INFO] beginning to reinstall server
2024-03-27T14:24:35-04:00 [INFO] deleting server container
2024-03-27T14:24:35-04:00 [INFO] starting language server "pyright", path: "/Users/<MASKED>/Code/TestingStuff/t1-p", id: 3
2024-03-27T14:24:35-04:00 [INFO] fetching latest version of language server "pyright"
2024-03-27T14:24:35-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:42-04:00 [INFO] downloading language server "pyright"
2024-03-27T14:24:42-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:50-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:24:50-04:00 [ERROR] failed to start language server "pyright": failed to execute npm install subcommand:
stdout: ""
stderr: "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! errno SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_24_43_499Z-debug-0.log\n"
2024-03-27T14:24:50-04:00 [ERROR] server stderr: Some("")
2024-03-27T14:24:50-04:00 [INFO] retrying installation of language server "pyright" in 1s
2024-03-27T14:24:51-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:24:51-04:00 [INFO] About to spawn test binary
2024-03-27T14:24:51-04:00 [WARN] test binary failed to launch
2024-03-27T14:24:51-04:00 [WARN] test binary check failed
2024-03-27T14:24:51-04:00 [INFO] beginning to reinstall server
2024-03-27T14:24:51-04:00 [INFO] deleting server container
2024-03-27T14:24:51-04:00 [INFO] starting language server "pyright", path: "/Users/<MASKED>/Code/TestingStuff/t1-p", id: 4
2024-03-27T14:24:51-04:00 [INFO] fetching latest version of language server "pyright"
2024-03-27T14:24:51-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:24:59-04:00 [INFO] downloading language server "pyright"
2024-03-27T14:24:59-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:25:07-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:25:07-04:00 [ERROR] failed to start language server "pyright": failed to execute npm install subcommand:
stdout: ""
stderr: "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! errno SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_24_59_995Z-debug-0.log\n"
2024-03-27T14:25:07-04:00 [ERROR] server stderr: Some("")
2024-03-27T14:25:07-04:00 [INFO] retrying installation of language server "pyright" in 1s
2024-03-27T14:25:08-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:25:08-04:00 [INFO] About to spawn test binary
2024-03-27T14:25:08-04:00 [WARN] test binary failed to launch
2024-03-27T14:25:08-04:00 [WARN] test binary check failed
2024-03-27T14:25:08-04:00 [INFO] beginning to reinstall server
2024-03-27T14:25:08-04:00 [INFO] deleting server container
2024-03-27T14:25:08-04:00 [INFO] starting language server "pyright", path: "/Users/<MASKED>/Code/TestingStuff/t1-p", id: 5
2024-03-27T14:25:08-04:00 [INFO] fetching latest version of language server "pyright"
2024-03-27T14:25:08-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:25:15-04:00 [INFO] downloading language server "pyright"
2024-03-27T14:25:15-04:00 [INFO] Node runtime install_if_needed
2024-03-27T14:25:23-04:00 [ERROR] missing executable in directory "/Users/<MASKED>/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js"
2024-03-27T14:25:23-04:00 [ERROR] failed to start language server "pyright": failed to execute npm install subcommand:
stdout: ""
stderr: "npm ERR! code SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! errno SELF_SIGNED_CERT_IN_CHAIN\nnpm ERR! request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_25_16_481Z-debug-0.log\n"
2024-03-27T14:25:23-04:00 [ERROR] server stderr: Some("")
2024-03-27T14:25:23-04:00 [ERROR] Hit 4 reinstallation attempts for "pyright"

>>> cat "/Users/<MASKED>/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_25_16_481Z-debug-0.log"
0 verbose cli /Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node /Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/npm
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/cyeganeh/Library/Application Support/Zed/languages/pyright/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/blank_user_npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/blank_global_npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install pyright@1.1.356
21 verbose argv "install" "--cache" "/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache" "--userconfig" "/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/blank_user_npmrc" "--globalconfig" "/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/blank_global_npmrc" "pyright@1.1.356" "--save-exact" "--fetch-retry-mintimeout" "2000" "--fetch-retry-maxtimeout" "5000" "--fetch-timeout" "5000" "--prefix" "/Users/cyeganeh/Library/Application Support/Zed/languages/pyright"
22 timing npm:load:setTitle Completed in 5ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_25_16_481Z-
26 verbose logfile /Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_25_16_481Z-debug-0.log
27 timing npm:load:logFile Completed in 9ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 timing config:load:flatten Completed in 1ms
32 timing arborist:ctor Completed in 0ms
33 silly logfile start cleaning logs, removing 2 files
34 timing arborist:ctor Completed in 0ms
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 4ms
37 timing idealTree:userRequests Completed in 1ms
38 silly idealTree buildDeps
39 silly fetch manifest pyright@1.1.356
40 silly placeDep ROOT pyright@ OK for:  want: 1.1.356
41 timing idealTree:#root Completed in 7102ms
42 timing idealTree:node_modules/pyright Completed in 0ms
43 timing idealTree:buildDeps Completed in 7103ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 7109ms
46 timing command:install Completed in 7112ms
47 verbose type system
48 verbose stack FetchError: request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain
48 verbose stack     at ClientRequest.<anonymous> (/Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
48 verbose stack     at ClientRequest.emit (node:events:513:28)
48 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
48 verbose stack     at TLSSocket.emit (node:events:525:35)
48 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
48 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
48 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
49 verbose cwd /Users/cyeganeh/Library/Application Support/Zed/languages/pyright
50 verbose Darwin 23.3.0
51 verbose node v18.15.0
52 verbose npm  v9.5.0
53 error code SELF_SIGNED_CERT_IN_CHAIN
54 error errno SELF_SIGNED_CERT_IN_CHAIN
55 error request to https://registry.npmjs.org/pyright failed, reason: self-signed certificate in certificate chain
56 verbose exit 1
57 timing npm Completed in 7144ms
58 verbose unfinished npm timer reify 1711563916508
59 verbose unfinished npm timer reify:loadTrees 1711563916509
60 verbose code 1
61 error A complete log of this run can be found in:
61 error     /Users/cyeganeh/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/cache/_logs/2024-03-27T18_25_16_481Z-debug-0.log

**Comment by Moshyfawn** [comment] 2024-03-27 18:31
This has already been mentioned, so I'm going to close this issue in favour of the other one to keep the conversation in one place. Be sure to +👍 and add any information you feel is relevant to the other thread.

Duplicate of
- #8650

**Closed by Moshyfawn** 2024-03-27 18:31 UTC
Labels: defect, triage, admin read
