### ISSUE TITLE
Show column position in characters not bytes

### ISSUE THREAD

**Issue by xpe** [zed-industries/zed#22417] opened 2024-12-25 13:42 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In the bottom-right, Zed currently shows the column position in bytes instead of characters (apologies if I'm abusing the terms).

While I appreciate the complexities of Unicode and text coordinate systems (see https://zed.dev/blog/zed-decoded-text-coordinate-systems), it seems to me that a Zed user is most likely to want the column indicator to mean "number of characters" not "number of bytes". This matches what other editors do, which in this case I think is also sensible. 

Do others agree?

### Zed Version and System Specs

Zed: v0.167.1 (Zed Preview)
OS: macOS 15.1.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help present your vision of the feature

For example, you can see in this screenshot that the column is reported as 104. That happens to be in bytes I think. In terms of characters, the column position is 50.

<img width="923" alt="image" src="https://github.com/user-attachments/assets/92a8d144-6ee0-47d7-8ddb-b7540a1430d8" />

**Comment by SomeoneToIgnore** [comment] 2024-12-25 14:03
Duplicate of https://github.com/zed-industries/zed/issues/12024

**Closed by SomeoneToIgnore** 2024-12-25 14:03 UTC
Labels: enhancement, triage, admin read
