### ISSUE TITLE
Regex find causes UI text to dissapear

### ISSUE THREAD

**Issue by regexPattern** [zed-industries/zed#9954] opened 2024-03-29 14:09 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Some text elements of the UI (such as tab names and breadcrumbs) dissapear when performing a file search with regex using some regex patterns such as `.` or an OR condition. The issue happens inmediatly after typing the character and seems to happen only when there are many matching patterns or the file is big enough.

### Environment

Zed: v0.129.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/47466248/43dcb185-0feb-470b-a5fe-559bfae95510

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14805097/Zed.log)

**Comment by bennetbo** [comment] 2024-03-29 17:12
Looks like a duplicate of #9792

**Comment by JosephTLyons** [comment] 2024-03-29 18:17
I think so as well @bennetbo, going to close this in favor of that #9792.

**Closed by JosephTLyons** 2024-03-29 18:17 UTC
Labels: defect, triage, admin read
