### ISSUE TITLE
Copy text from doc popup

### ISSUE THREAD

**Issue by Zarathustra2** [zed-industries/zed#12344] opened 2024-05-27 09:08 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,

I am on 0.136.2 

It would be nice if we could highlight & copy text from the doc popup. See attached screenshot. This is currently not possible. 

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="757" alt="image" src="https://github.com/zed-industries/zed/assets/33396162/47614fce-5ca4-4898-830e-0edaf3e56923">

**Comment by Moshyfawn** [comment] 2024-05-27 14:00
This already has a feature request, so I'm going to close this issue. Be sure to +👍 the other thread.

Duplicate of:
- #4606

**Closed by Moshyfawn** 2024-05-27 14:00 UTC
Labels: enhancement, triage, admin read

**Comment by Zarathustra2** [comment] 2024-05-27 14:43
ah damn, didn't see the issue. My bad. thanks for redirecting!
