### ISSUE TITLE
Failed to connect to Open API

### ISSUE THREAD

**Issue by seljabali** [zed-industries/zed#9527] opened 2024-03-19 06:35 UTC
### Check for existing issues

- [X] Completed
- This [ticket](https://github.com/zed-industries/zed/issues/9446) looked close, but not sure where he got setting config to update settings.

### Describe the bug / provide steps to reproduce it

* Was using an older version of Zed
* Added Open AI key by hitting 🪄
* The side bar assistant didn't work, nor inline prompts
* Thought I'd upgrade. Menu `Zed` -> `Check for Updates` (failed nothing happened)
* Uninstalled app
* Reinstalled via Brew
* Click 🪄 to place Chat GPT Key as it used on older version (no longer there)
* Prompt appears
* Enter "help me write hello world in kotlin"
* Error appears: "Failed to connect to Open API"

I don't see how I'm to place/update Open AI keys in the app. Nor can I find docs online to help.

Help please!

### Environment

Zed: v0.126.3 (Zed)
OS: macOS 13.5.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1579" alt="Screenshot 2024-03-18 at 23 13 53" src="https://github.com/zed-industries/zed/assets/1254921/2bc542ef-f254-41a2-bcdb-3f1092aed2b4">

**Comment by Moshyfawn** [comment] 2024-03-19 17:14
This seems like the other report from earlier. I'll close this one in favour of the other. Be sure to +👍 and add any missing information to the other one.

Duplicate of
- #4486

**Closed by Moshyfawn** 2024-03-19 17:14 UTC
Labels: defect, triage, admin read
