### ISSUE TITLE
[Snippet] variables support

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#13456] opened 2024-06-24 08:09 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables

If variable support is implemented, the functionality can be better extended.

Use example

https://stackoverflow.com/questions/65156083/implement-vscode-snippet-for-c-header-guard

**Comment by osiewicz** [comment] 2024-06-24 08:11
Duplicate of: https://github.com/zed-industries/zed/issues/13301

**Closed by osiewicz** 2024-06-24 08:11 UTC
Labels: enhancement, triage, admin read
