### ISSUE TITLE
Prefer recent actions/completions when searching in command palette

### ISSUE THREAD

**Issue by knyazer** [zed-industries/zed#16858] opened 2024-08-26 08:15 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When searching for a command, give large preference to recent/frequent commands (e.g. like a frecency plugin in neovim)

### If applicable, add mockups / screenshots to help present your vision of the feature

[Screencast from 08-26-2024 10:10:29 AM.webm](https://github.com/user-attachments/assets/6c7a8190-5dd0-4a08-9e04-f58585792d17)

Here, I want to restart the LSP; I just did it, and I do it quite frequently, so the suggestion pop-ups as the first one. As soon as I start typing, it disappears, even though I just re-type the suggestion. I would expect it to be stuck as the first one.

From the algorithmic perspective, I would expect you to have a list of all commands, and for each command you have a somehow estimated preference score (e.g. with frecency, or maybe even something smarter?), and then you just filter through them, and on the screen you show only the sorted list. This way the 'frecent' commands will be always on top, and will have consistent positioning.

**Comment by lougreenwood** [comment] 2024-08-26 08:55
100%!

In neovim I used a Telescope plugin called **`smart-open`** - I miss this so much. Especially when doing frequent debugging and repetitively running the same command...

**Comment by notpeter** [comment] 2024-09-02 02:08
Duplicate of: 
- https://github.com/zed-industries/zed/issues/8107

Thanks for reporting, please vote 👍 on that issue for visibility and subscribe to track it's progress.

**Closed by notpeter** 2024-09-02 02:08 UTC
Labels: enhancement, command palette
