### ISSUE TITLE
Scrolling is not 120fps

### ISSUE THREAD

**Issue by jansedlon** [zed-industries/zed#7558] opened 2024-02-08 09:22 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hey, I've noticed that you did some thing to enable 120fps on ProMotion displays. I've tried it out and it's still running on 60fps.

### Environment

Zed: v0.122.1 (Zed Preview)
OS: macOS 14.3.0
Memory: 48 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/13948180/7e4008c3-bb1f-42bf-936c-7d2b4ff06949)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```log
2024-02-08T10:14:03+01:00 [INFO] ========== starting zed ==========
2024-02-08T10:14:03+01:00 [INFO] Opening main db
2024-02-08T10:14:03+01:00 [ERROR] crates/theme/src/settings.rs:326: theme not found: Dainty Pandaa
2024-02-08T10:14:03+01:00 [ERROR] crates/zed/src/zed.rs:519: EOF while parsing a value at line 1 column 0
2024-02-08T10:14:03+01:00 [INFO] Opening main db
2024-02-08T10:14:03+01:00 [INFO] build git repository ".git"
2024-02-08T10:14:03+01:00 [INFO] set status on client 0: Authenticating
2024-02-08T10:14:03+01:00 [INFO] Opening main db
2024-02-08T10:14:03+01:00 [INFO] set environment variables from shell:/bin/zsh, path:/Users/jansedlon/.bun/bin:/Users/jansedlon/Library/Caches/fnm_multishells/32267_1707383643298/bin:/Users/jansedlon/Library/Application Support/fnm:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jansedlon/.cargo/bin:/Users/jansedlon/Library/Application Support/JetBrains/Toolbox/scripts:/Users/jansedlon/.orbstack/bin
2024-02-08T10:14:03+01:00 [INFO] set status on client 81040: Connecting
2024-02-08T10:14:03+01:00 [INFO] Opening main db
2024-02-08T10:14:03+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:14:03+01:00 [INFO] starting language server "json-language-server", path: "/Users/jansedlon/Work/Flixy/flixy", id: 1
2024-02-08T10:14:03+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:14:03+01:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-08T10:14:03+01:00 [INFO] starting language server "typescript-language-server", path: "/Users/jansedlon/Work/Flixy/flixy", id: 2
2024-02-08T10:14:03+01:00 [INFO] starting language server "eslint", path: "/Users/jansedlon/Work/Flixy/flixy", id: 3
2024-02-08T10:14:03+01:00 [INFO] starting language server "tailwindcss-language-server", path: "/Users/jansedlon/Work/Flixy/flixy", id: 4
2024-02-08T10:14:03+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:14:03+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:03+01:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-08T10:14:03+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:14:03+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:14:03+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:14:03+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:14:03+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:14:03+01:00 [ERROR] crates/workspace/src/persistence/model.rs:257: No worktree for path: "/Users/jansedlon/.config/zed/settings.json"
2024-02-08T10:14:03+01:00 [INFO] reload git repository ".git"
2024-02-08T10:14:03+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:03+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:03+01:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-02-08T10:14:04+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:04+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:04+01:00 [INFO] add connection to peer
2024-02-08T10:14:04+01:00 [INFO] waiting for server hello
2024-02-08T10:14:04+01:00 [INFO] got server hello
2024-02-08T10:14:04+01:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 328, id: 136603 })
2024-02-08T10:14:04+01:00 [INFO] set status on client 81040: Connected { peer_id: PeerId { owner_id: 328, id: 136603 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-02-08T10:14:04+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:04+01:00 [INFO] reload git repository ".git"
2024-02-08T10:14:04+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:04+01:00 [INFO] reload git repository ".git"
2024-02-08T10:14:04+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:04+01:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-08T09:14:04.826Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-02-08T09:14:04.826Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-02-08T10:14:04+01:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "7f435683-9bb4-4d2e-beba-0234e2c95543",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-02-08T10:14:04+01:00 [INFO] 3 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "ESLint server running in node v18.15.0"
}
2024-02-08T10:14:04+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/routes/resources+/integrations+/ecomail-integration-card.tsx"
  }
}
2024-02-08T10:14:04+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/features/integrations/ecomail/ecomail-integration-service.server.ts"
  }
}
2024-02-08T10:14:04+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/utils/auth.server.ts"
  }
}
2024-02-08T10:14:04+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/routes/user+/income/details_.$orderId/route.tsx"
  }
}
2024-02-08T10:14:04+01:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/hover
2024-02-08T10:14:05+01:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-08T09:14:05.224Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-02-08T09:14:05.224Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-02-08T10:14:05+01:00 [INFO] Fetching default prettier and plugins: [("prettier-plugin-tailwindcss", "0.5.11"), ("prettier", "3.2.5")]
2024-02-08T10:14:05+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:05+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:05+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:06+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:14:06+01:00 [INFO] 2 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Using Typescript version (user-setting) 5.4.0-beta from path \"/Users/jansedlon/Work/Flixy/flixy/node_modules/typescript/lib/tsserver.js\""
}
2024-02-08T10:14:06+01:00 [INFO] 2 unhandled notification $/typescriptVersion:
{
  "version": "5.4.0-beta",
  "source": "user-setting"
}
2024-02-08T10:14:06+01:00 [INFO] 4 unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2024-02-08T10:14:23+01:00 [INFO] Initialized prettier with plugins: {"prettier-plugin-tailwindcss"}
2024-02-08T10:15:56+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:15:56+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:15:56+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:15:56+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:15:57+01:00 [INFO] ========== starting zed ==========
2024-02-08T10:15:57+01:00 [INFO] Opening main db
2024-02-08T10:15:57+01:00 [ERROR] crates/theme/src/settings.rs:326: theme not found: Dainty Pandaa
2024-02-08T10:15:57+01:00 [INFO] set environment variables from shell:/bin/zsh, path:/Users/jansedlon/.bun/bin:/Users/jansedlon/Library/Caches/fnm_multishells/32547_1707383757759/bin:/Users/jansedlon/Library/Application Support/fnm:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jansedlon/.cargo/bin:/Users/jansedlon/Library/Application Support/JetBrains/Toolbox/scripts:/Users/jansedlon/.orbstack/bin
2024-02-08T10:15:57+01:00 [ERROR] crates/zed/src/zed.rs:519: EOF while parsing a value at line 1 column 0
2024-02-08T10:15:57+01:00 [INFO] Opening main db
2024-02-08T10:15:57+01:00 [INFO] build git repository ".git"
2024-02-08T10:15:57+01:00 [INFO] set status on client 0: Authenticating
2024-02-08T10:15:57+01:00 [INFO] Opening main db
2024-02-08T10:15:57+01:00 [INFO] set status on client 81040: Connecting
2024-02-08T10:15:57+01:00 [INFO] Opening main db
2024-02-08T10:15:57+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:15:57+01:00 [INFO] starting language server "json-language-server", path: "/Users/jansedlon/Work/Flixy/flixy", id: 1
2024-02-08T10:15:57+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:15:57+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:57+01:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-08T10:15:57+01:00 [INFO] starting language server "typescript-language-server", path: "/Users/jansedlon/Work/Flixy/flixy", id: 2
2024-02-08T10:15:57+01:00 [INFO] starting language server "eslint", path: "/Users/jansedlon/Work/Flixy/flixy", id: 3
2024-02-08T10:15:57+01:00 [INFO] starting language server "tailwindcss-language-server", path: "/Users/jansedlon/Work/Flixy/flixy", id: 4
2024-02-08T10:15:57+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:15:57+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:15:57+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:15:57+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:15:57+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:15:57+01:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-08T10:15:57+01:00 [WARN] Skipping path "/Users/jansedlon/Work/Flixy/flixy" that has no prettier dependency and no workspaces section in its package.json
2024-02-08T10:15:58+01:00 [INFO] reload git repository ".git"
2024-02-08T10:15:58+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:58+01:00 [INFO] reload git repository ".git"
2024-02-08T10:15:58+01:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-02-08T10:15:58+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:58+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:58+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:58+01:00 [INFO] add connection to peer
2024-02-08T10:15:58+01:00 [INFO] waiting for server hello
2024-02-08T10:15:58+01:00 [INFO] got server hello
2024-02-08T10:15:58+01:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 328, id: 136957 })
2024-02-08T10:15:58+01:00 [INFO] set status on client 81040: Connected { peer_id: PeerId { owner_id: 328, id: 136957 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-02-08T10:15:58+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:59+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:59+01:00 [INFO] reload git repository ".git"
2024-02-08T10:15:59+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:59+01:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-08T09:15:59.227Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-02-08T09:15:59.227Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-02-08T10:15:59+01:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "e02bd778-a0f5-4ebd-a9a2-6ce7061816c8",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-02-08T10:15:59+01:00 [INFO] 3 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "ESLint server running in node v18.15.0"
}
2024-02-08T10:15:59+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/utils/auth.server.ts"
  }
}
2024-02-08T10:15:59+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/routes/user+/income/details_.$orderId/route.tsx"
  }
}
2024-02-08T10:15:59+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/features/integrations/ecomail/ecomail-integration-service.server.ts"
  }
}
2024-02-08T10:15:59+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/app/routes/resources+/integrations+/ecomail-integration-card.tsx"
  }
}
2024-02-08T10:15:59+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:59+01:00 [INFO] Fetching default prettier and plugins: [("prettier-plugin-tailwindcss", "0.5.11"), ("prettier", "3.2.5")]
2024-02-08T10:15:59+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:59+01:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-08T09:15:59.598Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-02-08T09:15:59.598Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-02-08T10:15:59+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:15:59+01:00 [INFO] Node runtime install_if_needed
2024-02-08T10:16:00+01:00 [INFO] 2 unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Using Typescript version (user-setting) 5.4.0-beta from path \"/Users/jansedlon/Work/Flixy/flixy/node_modules/typescript/lib/tsserver.js\""
}
2024-02-08T10:16:00+01:00 [INFO] 2 unhandled notification $/typescriptVersion:
{
  "version": "5.4.0-beta",
  "source": "user-setting"
}
2024-02-08T10:16:00+01:00 [INFO] Initialized prettier with plugins: {"prettier-plugin-tailwindcss"}
2024-02-08T10:16:00+01:00 [INFO] 4 unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2024-02-08T10:17:46+01:00 [INFO] Initializing default prettier with plugins {}
2024-02-08T10:17:46+01:00 [INFO] 3 unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/jansedlon/Work/Flixy/flixy/node_modules/.pnpm/react-router@6.21.3_react@18.2.0/node_modules/react-router/dist/lib/hooks.d.ts"
  }
}
2024-02-08T10:17:47+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:17:47+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:17:47+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
2024-02-08T10:17:47+01:00 [ERROR] crates/lsp/src/lsp.rs:679: oneshot canceled
```

**Comment by mrnugget** [comment] 2024-02-08 12:34
Thanks for reporting @jansedlon. We're investigating! This is a duplicate of https://github.com/zed-industries/zed/issues/7413 which I've now reopened. I'll close this one, so we have everything in one issue.

**Closed by mrnugget** 2024-02-08 12:34 UTC
Labels: defect, triage, admin read
