### ISSUE TITLE
Zed Unable to run/open in opensuse tumbleweed OS 

### ISSUE THREAD

**Issue by PrethamMuthappa** [zed-industries/zed#20217] opened 2024-11-05 02:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Tried installing zed in opensuse os but it doesnt run/open even by clicking the icon as well as running through terminal

How did I install ?

`sudo zypper addrepo -f https://download.opensuse.org/repositories/editors/openSUSE_Tumbleweed/editors.repo`
`sudo zypper in zed`

I get an error saying `error opening [PathWithPosition { path: "/home/pretham/Documents/key.txt", row: None, column: None }]: NoSupportedDeviceFound`

Then I installed the libvulkan_nouveau for my device 

When i run zed in terminal i get a new error saying 

`error opening [PathWithPosition { path: "/home/pretham/Documents/key.txt", row: None, column: None }]: VulkanError(ERROR_INITIALIZATION_FAILED)`

Also tried using flatpack , same problem even there

Device Has intel as well as nvidia gpu but currently only intel is active and primary

### Environment

```
                                                        OS: openSUSE Tumbleweed 20241017 x86_64
                                                        Host: ROG Strix G512LI_G512LI (1.0)
                                                        Kernel: Linux 6.11.3-1-default
                                                        Uptime: 22 mins
                                                        Packages: 2544 (rpm)
                                                        Shell: bash 5.2.37
                                                        Display (BOE090F): 1920x1080 @ 144 Hz in 16" [Built-in]
                                                        DE: KDE Plasma 6.2.1
                                                        WM: KWin (X11)
                                                        WM Theme: Breeze
                                                        Theme: Breeze (Classic) [Qt], Breeze [GTK2/3]
                                                        Icons: breeze [Qt], breeze [GTK2/3/4]
                                                        Font: Noto Sans (11pt) [Qt], Noto Sans (11pt) [GTK2/3/4]
                                                        Cursor: breeze (24px)
                                                        Terminal: kitty 0.36.4
                                                        Terminal Font: 0xProtoNF-Regular (12pt)
                                                        CPU: Intel(R) Core(TM) i5-10300H (8) @ 4.50 GHz
                                                        GPU 1: NVIDIA GeForce GTX 1650 Ti Mobile
                                                        GPU 2: Intel UHD Graphics @ 1.05 GHz [Integrated]
                                                        Memory: 4.22 GiB / 7.55 GiB (56%)
                                                        Swap: 0 B / 7.55 GiB (0%)
                                                        Disk (/): 22.09 GiB / 137.62 GiB (16%) - btrfs
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/5eb0344d-f841-4ff0-9339-8e549328b1a6)

![image](https://github.com/user-attachments/assets/2407ef22-c72d-4e1d-a7ad-4eb4542de3b4)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-11-05 08:15
> Check for existing issues

https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+ERROR_INITIALIZATION_FAILED

Duplicate of https://github.com/zed-industries/zed/issues/8168

**Closed by SomeoneToIgnore** 2024-11-05 08:15 UTC
Labels: triage, admin read
