### ISSUE TITLE
Display error with huge log files

### ISSUE THREAD

**Issue by Frank1126lin** [zed-industries/zed#15666] opened 2024-08-02 01:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Open a huge log file ( 2.3 G with over 26M lines), when slide the bar into the bottom, the Display shows a kind of error shows as pictures.
By the way, the Ctrl+F function takes too long. Is there any way to accelerate the lookup process? 
![2024-08-02-09-46-45](https://github.com/user-attachments/assets/134113a9-b748-4e03-8d02-d21b3f93563b)

### Environment

OS: ubuntu 22.04
version: 0.146.3

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16464207/Zed.log)

</pre></details>

**Comment by JosephTLyons** [comment] 2024-08-02 15:47
Hey @Frank1126lin,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5355

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-08-02 15:47 UTC
Labels: defect, editor, large projects
