### ISSUE TITLE
Zed crashes when opening with "exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND"

### ISSUE THREAD

**Issue by MrYoutber** [zed-industries/zed#9296] opened 2024-03-13 19:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I followed the guide on building Zed on Windows, but then when I try to open the zed\target\release\Zed.exe it gives me the error "error: process didn't exit successfully: `target\release\Zed.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)" in the console and "The procedure entry point DCompositionWaitForCompositorClock could not be located in the dynamic link library C:\zed\target\release\Zed.exe.".

### Environment

Processor | AMD Ryzen 7 1700X Eight-Core Processor
Video Card | NVIDIA GeForce GTX 1660 Ti
Operating System | Windows 10
RAM | 32 GB DDR4 3200 MHz

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/82754015/4c189888-5491-44a9-9f20-890e7780a546)
![image](https://github.com/zed-industries/zed/assets/82754015/8243d383-eaf7-47aa-8ed2-1bb8c02a3ff5)

**Comment by kazatsuyu** [comment] 2024-03-15 17:34
This is duplicate of #9166

**Closed** 2024-03-15 17:36 UTC
Labels: defect, panic / crash, windows
