### ISSUE TITLE
Staled git status indicator

### ISSUE THREAD

**Issue by musicq** [zed-industries/zed#16269] opened 2024-08-15 02:27 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I make some changes in a git repo, the editor will show the git status gutter correctly. But these indicators won't disappear even after I commit the changes, no matter if close the file or not.

The only way to get them refreshed is to run `workspace: reload`

### Environment

Zed: v0.148.0 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="431" alt="image" src="https://github.com/user-attachments/assets/7c0b23a4-e2f8-452d-bd1d-cd4cb907fd38">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Moshyfawn** [comment] 2024-08-15 13:37
Could be related to
- #14049

**Comment by notpeter** [comment] 2024-08-26 16:04
Closing as duplicate of: 
- https://github.com/zed-industries/zed/issues/13176

**Closed by notpeter** 2024-08-26 16:04 UTC
Labels: defect, editor, git
