### ISSUE TITLE
Status bar: incorrect column number when line contains non-ASCII characters

### ISSUE THREAD

**Issue by fvsch** [zed-industries/zed#21399] opened 2024-12-02 12:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Create a new blank editor
2. Paste the following text:

```
a'b
a"b
a’b
a“b
```

3. Place the cursor at the end of line 1, and look at the line and column numbers displayed in the status bar.
4. Repeat for each line.

Expected result:

```
1:4
2:4
3:4
4:4
```

Actual result:

```
1:4
2:4
3:6
4:6
```

It looks like Zed is looking at the number of UTF-8 _bytes_ in the line before the cursor, instead of the number of UTF-8 _characters_.

### Environment

Zed: v0.163.2 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

**Comment by notpeter** [comment] 2024-12-02 23:05
> It looks like Zed is looking at the number of UTF-8 bytes in the line before the cursor, instead of the number of UTF-8 characters.

You are correct. I believe this is a duplicate of:
- #12024

**Closed by notpeter** 2024-12-02 23:05 UTC
Labels: bug, triage, admin read
