### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by cemoktra** [zed-industries/zed#15254] opened 2024-07-26 04:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure at what action it really crashes. But it seems it happens while navigating around the code with they keyboard

### Environment

Zed: v0.147.0 (Zed Dev b7c6f3e98eb53eb516cba9bb1724ebbbf780cfd4)
OS: Linux Wayland ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.0.5-1ubuntu1

Zed: v0.147.0 (Zed Dev 745d2e4d3b4cd977de8895a18729c3e96fc190b5)
OS: Linux Wayland ubuntu 24.04
Memory: 31.1 GiB
Architecture: x86_64
GPU: Intel(R) UHD Graphics 630 (CFL GT2) || Intel open-source Mesa driver || Mesa 24.0.5-1ubuntu1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>
Thread "<unnamed>" panicked with "index out of bounds: the len is 66 but the index is 18446744073709551610" at crates/rope/src/rope.rs:678:16

**Comment by cemoktra** [comment] 2024-07-26 05:08
It works with `e2113e48953a726ed076f1fd0660ae692308a5ba`

**Comment by cemoktra** [comment] 2024-07-26 06:08
This was introduced in 8631180e43566918742ff85113b47cefda41545d

**Comment by maxdeviant** [comment] 2024-07-26 12:09
This looks like a duplicate of #15218.

**Comment by JosephTLyons** [comment] 2024-07-26 19:52
Closing in favor of:

- https://github.com/zed-industries/zed/issues/15218

**Closed by JosephTLyons** 2024-07-26 19:52 UTC
Labels: defect, panic / crash, duplicate
