### ISSUE TITLE
Format unsaved buffers

### ISSUE THREAD

**Issue by jessevdp** [zed-industries/zed#9773] opened 2024-03-25 12:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I want to be able to run a formatter on a buffer that isn't (yet) saved to a file.

I often grab some output (usually some unformatted JSON straight out of cURL or something) and paste it into my editor to quickly format.

In Zed it seems that I have to save to file to disk before I'm allowed to format it.

### If applicable, add mockups / screenshots to help present your vision of the feature

A quick demo outlining the issue.

As you can see the format command doesn't do anything until I save the new buffer to a file.

https://github.com/zed-industries/zed/assets/15139826/da45c2b1-4492-46e2-a29f-11dedf91c348

**Comment by jessevdp** [comment] 2024-03-25 12:41
cc. @mrnugget 😄

**Comment by JosephTLyons** [comment] 2024-03-26 03:32
Hey @jessevdp,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4529

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-03-26 03:32 UTC
Labels: enhancement, editor, keymap / key binding

**Comment by jessevdp** [comment] 2024-03-26 08:05
My bad. Although that issue references language overrides specifically, which I'm not using.
