### ISSUE TITLE
Failing to copy from one zed workspace and paste in another zed workspace

### ISSUE THREAD

**Issue by amiyatulu** [zed-industries/zed#16950] opened 2024-08-27 14:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It doesn't copy text when I copy from one zed workspace and paste it to another zed workspace

### Environment

Linux
Ubuntu 22.04.4 LTS
Zed  0.149.5

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-27 22:03
Duplicate of:
- https://github.com/zed-industries/zed/issues/16741

**Closed by notpeter** 2024-08-27 22:03 UTC
Labels: defect, triage, admin read
