### ISSUE TITLE
CLI should launch ZED as front window (current order sends it to the very back)

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4818] opened 2023-04-06 19:57 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently when launching ZED through CLI command it opens ZED, but sends it to the very back in the apps/windows order. The behavior should be reversed, the window would appear up front

### If applicable, add mockups / screenshots to help present your vision of the feature

Current behavior:

![back](https://user-images.githubusercontent.com/4711498/230481512-d1752962-426a-4658-97ac-332a717d9fa8.png)

Desired behavior:

![front](https://user-images.githubusercontent.com/4711498/230481571-39d9f10f-f83e-41ca-8085-5d58a3e9ab2e.png)

**Comment by JosephTLyons** [comment] 2024-07-28 05:54
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 05:54 UTC
Labels: enhancement, workspace, cli
