### ISSUE TITLE
`hard_tabs` doesn't affect formatting.

### ISSUE THREAD

**Issue by etzabo** [zed-industries/zed#12760] opened 2024-06-07 03:03 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Although the `hard_tabs` setting appropriately sets the on save formatting applied through the config setting `format_on_save`, it doesn't change the behavior of the `editor: format` command.

### Environment

Zed: v0.138.4 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-06-07 04:56
Can you provide more details on what language do you format with which formatter?
Zed has Prettier (that should use hard_tabs) and LSP formatters (that are all different hence hard_tabs setting is most probably not passed into them).

The latter is known, but I'm curious if there's something else broken.

**Comment by etzabo** [comment] 2024-06-19 02:21
Sorry for the late response. I'm using Rust with all default settings, aside from `hard_tabs` set `true`.

**Comment by SomeoneToIgnore** [comment] 2024-06-19 10:11
Oh, now it's more clear to me, thank you: so the issue is not that `hard_tabs` do not work (which was the case too), but rather the fact that `cargo fmt` does erase the tabs printed by Zed when reformatting?

Does a similar thing work for you on VSCode or other editors?
I am not aware of anything but 
```
rust-analyzer.rustfmt.overrideCommand (default: null)

    Advanced option, fully override the command rust-analyzer uses for formatting. This should be the equivalent of rustfmt here, and not that of cargo fmt. The file contents will be passed on the standard input and the formatted result will be read from the standard output.
```

from https://rust-analyzer.github.io/manual.html

and suspect there's no seamless way to configure `rustfmt` via `Zed`: instead, you'll have to configure both Zed (as done here) and also create the `rustfmt.toml` with `hard_tabs = true` setting.

This makes sense to me, since not every project users is expected to have Zed, but all of them will have `rustfmt`.
I would close the issue, unless I am misunderstanding something here.

**Closed** 2024-06-19 16:43 UTC
Labels: defect, needs info / awaiting response, editor, setting
