### ISSUE TITLE
Option to View Open Tabs as Vertical List on top of Project Panel

### ISSUE THREAD

**Issue by adamseckel** [zed-industries/zed#18443] opened 2024-09-27 14:46 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

One of my favourite layouts VSCode is to hide the horizontal tabs across the top of the editor, and show a vertical list of open editors on top of the file explorer (Project Panel in Zed). In VSCode this space can even be subdivided into the groups if your window is split. This is a really nice way to reduce visual clutter in the centre of your screen where your code is, and move distractions to the side/peripheral vision.

It would be fantastic to have this as a non-default option in Zed.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1026" alt="Screenshot 2024-09-27 at 3 44 35 pm" src="https://github.com/user-attachments/assets/035f54de-ef70-46ac-b382-33fe75d2693a">

**Comment by notpeter** [comment] 2024-10-02 16:25
Duplicate of:
- https://github.com/zed-industries/zed/issues/4331

Thanks for reporting, 👍 and subscribe to track progress on that issue.

**Closed** 2024-10-02 16:25 UTC
Labels: enhancement, triage, admin read

**Comment by ugreg** [comment] 2026-06-01 17:23
As a hack for vertical file list, we can always use Command + P to open a file list in the current project. Easier to scroll through that list than shifting though tabs.

<img width="550" height="456" alt="image" src="https://github.com/user-attachments/assets/285dbcdf-fa70-4235-b163-2158d823f1df" />
