### ISSUE TITLE
add button to disable an extension similar to vscode

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#15810] opened 2024-08-05 14:32 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would be nice if we can disable an extension, _(not in settings)_.
Let's say I want to disable an extension for a while, maybe to test another one like it, a button will be good/useful, instead of uninstalling and reinstalling it again.

### If applicable, add mockups / screenshots to help present your vision of the feature

![disable-ext](https://github.com/user-attachments/assets/fb53fb24-6eb5-4963-89fb-47f1fbe9800f)

**Comment by JosephTLyons** [comment] 2024-08-06 16:25
Hey @sparrowsl,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/10781

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-08-06 16:25 UTC
Labels: enhancement, extension infrastructure
