### ISSUE TITLE
Image Preview doesn't update when image is updated.

### ISSUE THREAD

**Issue by justanotherbyte** [zed-industries/zed#19199] opened 2024-10-14 20:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1) Open a directory in zed with any image, and click on it to open the preview.
2) Update the image programmatically.
3) See that the image hasn't actually changed.

I experienced this personally when working with matplotlib.

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 11.7.10
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-15 16:38
Duplicate of:
- #11529

**Closed by notpeter** 2024-10-15 16:38 UTC
Labels: defect, triage, admin read
