### ISSUE TITLE
Maybe a bug in terminal?

### ISSUE THREAD

**Issue by Gioppix** [zed-industries/zed#10262] opened 2024-04-08 08:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Compile this code

#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

int main(int argc, char **argv) {
  fork();
  fork();
  fork();
  printf("ciao\n");
  fflush(stdout);
  return 0;
}

execute it in the builtin terminal.

As you can see from the screenshot it's formatted very poorly. Mac's terminal gets it right.

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1047" alt="Screenshot 2024-04-08 at 10 46 57" src="https://github.com/zed-industries/zed/assets/83515412/4bacad7a-74f8-4df6-a60c-006438bc6f6c">

**Comment by jansol** [comment] 2024-04-08 13:04
That's a race condition caused by your code and I would expect it to behave exactly like this -- in fact if you try often enough I expect that you'll also see it in the macOS terminal.

The prompt gets printed once the `./main.out` process terminates, but some of the forked processes may or may not still be running in the background (and printing to *their* stdout which is the same terminal as your shell) at that time. They are independent processes so [the fact that the main process terminates does not concern them](https://stackoverflow.com/questions/395877/are-child-processes-created-with-fork-automatically-killed-when-the-parent-is).

If you wanted the main process to wait you'd have to use threads or somehow signal to the parent process that the children are done.

**Comment by Gioppix** [comment] 2024-04-08 17:18
@jansol thanks, you're right. I added "maybe" to the title because I was almost sure it was something wrong on my end. Should I close the issue?

P.s. this is enough: `while (wait(NULL) > 0);`. It waits for all children to finish.

**Comment by jansol** [comment] 2024-04-08 17:30
Yeah, I don't think there is anything Zed should do differently here so do close the issue (unless, of course, you disagree)

**Closed** 2024-04-08 18:33 UTC
Labels: defect, terminal

**Comment by Gioppix** [comment] 2026-01-15 18:16
hey @mikayla-maki , tagging you since I often see you around: do happen to know which theme is this? I was looking at my issues list and I'd like to use the theme again! thx
