### ISSUE TITLE
`0.145.1` broke the `ctrl-d` key functionality for VSCode

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#15213] opened 2024-07-25 16:39 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

lastest update broke the VSCode keymap for `ctrl-d`

highlight any word, and press `ctrl-d` it deletes the word instead of finding the references
without highlighting any word, when I press `ctrl-d` it deletes the letter the cursor is on instead of highlighting the word.

### Environment

Zed 0.145.1 
Linux (Mint)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-25 18:12
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/15160

There is workaround here:
- https://github.com/zed-industries/zed/issues/15160#issuecomment-2250880704

**Closed** 2024-07-25 18:13 UTC
Labels: duplicate
