### ISSUE TITLE
Add "duplicate file or directory" to right-click context menu in File Explorer

### ISSUE THREAD

**Issue by jasongitmail** [zed-industries/zed#8929] opened 2024-03-06 05:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Within the File Explorer panel, add a right-click context menu option for "duplicate file or directory". 

### If applicable, add mockups / screenshots to help present your vision of the feature

For behavior similar to this: https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-duplicate 
i.e. After clicking it, duplicate the item, allow editing the new file name, and confirm it when "enter" is pressed.

**Comment by Moshyfawn** [comment] 2024-03-06 05:50
I believe we've been collecting requests for copy/move actions in the project panel in another thread, so I'm going to close this one in favour of the other. Be sure to +👍 it to show you're interested, and add your request to have the action appear in the right-click actions menu.

**Comment by Moshyfawn** [comment] 2024-03-06 05:50
Duplicate of

- #4983

**Closed by Moshyfawn** 2024-03-06 05:50 UTC
Labels: enhancement, triage, admin read

**Comment by jasongitmail** [comment] 2024-03-06 16:58
That looks different to me

**Comment by JosephTLyons** [comment] 2024-03-07 05:36
There is a subtask in this issue that covers this:

- https://github.com/zed-industries/zed/issues/5119

Maybe that tracking issue should be split out into multiple issues.
