### ISSUE TITLE
Diagnostics Filtering

### ISSUE THREAD

**Issue by brockelmore** [zed-industries/zed#16540] opened 2024-08-20 18:51 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In repos with multiple languages, the diagnostics page forces me to see diagnostics from multiple languages. Most of the time, I am working on *one* part of the codebase. It would be nice to be able to filter diagnostics by language. In some cases, I actually want to filter by directory (similar to project search filter). Either filtering by language or directory for the diagnostics page would work for me.

### If applicable, add mockups / screenshots to help present your vision of the feature

Add this to diagnostics page, or a `Filter Diagnostics` that lets me filter out languages and stretch goal: specific error codes per language. Ideally, specific error codes could actually be filtered as a part of the LSP settings.
<img width="702" alt="Screenshot 2024-08-20 at 11 53 53 AM" src="https://github.com/user-attachments/assets/fcf72373-d7e4-43ae-aa90-2feb8d399794">

**Comment by jansol** [comment] 2024-11-20 15:09
Duplicate of #4475

**Closed by jansol** 2024-11-20 15:09 UTC
Labels: duplicate
