### ISSUE TITLE
Code completion while using github copilot

### ISSUE THREAD

**Issue by Tibor-S** [zed-industries/zed#11100] opened 2024-04-27 16:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If copilot is suggesting an inline hint then code completions won't be shown at all.

Copilot enabled with inline hint:
<img width="278" alt="Screenshot 2024-04-27 at 18 16 34" src="https://github.com/zed-industries/zed/assets/84145807/37e593ac-bb38-434b-bd7c-b73f00690ba8">

Copilot disabled and code completions shown:
<img width="604" alt="Screenshot 2024-04-27 at 18 17 24" src="https://github.com/zed-industries/zed/assets/84145807/8b045a02-ada6-4f14-9a25-3153a04fd30e">

### Environment

Zed: v0.132.2 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-04-27 16:40
While this one is formulated better, I'll close it as a duplicate of https://github.com/zed-industries/zed/issues/8766 as that one has more context and people involved.

**Closed by SomeoneToIgnore** 2024-04-27 16:40 UTC
Labels: defect, triage, admin read

**Comment by SomeoneToIgnore** [comment] 2024-05-05 16:23
Should be fixed in Zed 0.135
