### ISSUE TITLE
feature request: aggregated diagnostics

### ISSUE THREAD

**Issue by andrewbanchich** [zed-industries/zed#20878] opened 2024-11-19 20:38 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

currently, showing project diagnostics is just a list of every single diagnostic item. i'd love to be able to have them aggregated so i can get an overview of the different types of errors and warnings, then filter / expand each as needed. this would allow me to target fixing certain types of diagnostics first.

### Environment

Zed: v0.161.2 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31 GiB
Architecture: x86_64
GPU: Intel(R) Graphics (RPL-U) || Intel open-source Mesa driver || Mesa 24.0.9-0ubuntu0.2

**Comment by jansol** [comment] 2024-11-20 15:07
FWIW The diagnostics multibuffer *does* have a button at the top that lets you limit the shown diagnostics to only errors. But it could indeed be a lot more comprehensive.

**Comment by jansol** [comment] 2024-11-20 15:10
However there is an older issue with a more detailed description so I'll close this in favour of that one:

Duplicate of #4475

**Closed by jansol** 2024-11-20 15:10 UTC
Labels: admin read, duplicate
