### ISSUE TITLE
Supermaven Intializing bug

### ISSUE THREAD

**Issue by kuatroka** [zed-industries/zed#21812] opened 2024-12-10 15:12 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There seems to have already been something similar and the bug solution added a sign out option, but in my case there is no such an option. Nothing happens when I click on the Supermaven button. Only the tooltip saying "initializing..." and the button is greyed out.

### Environment

Zed: v0.164.2 (Zed)
OS: macOS 15.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/370ebe3c-f865-4fec-8330-2278abc9863e)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by Tekipeps** [comment] 2024-12-28 23:19
I also have this issue on

Zed: 1.66.1
OS: Arch Linux
Memory: 32GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-12-28 23:21
Duplicate of https://github.com/zed-industries/zed/issues/15653

**Closed by SomeoneToIgnore** 2024-12-28 23:21 UTC
Labels: bug, ai, inline completion, supermaven
