### ISSUE TITLE
Zed writes multiple characters when typing a character with accent ´ or caron ˇ on slovak keyboard

### ISSUE THREAD

**Issue by olilag** [zed-industries/zed#15327] opened 2024-07-27 11:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When typing a character with accent ´ or caron `ˇ` manualy `´` + character (example `o`) the output is `óóóóóóóóóóóóó` instead of one `ó`, `ˇ` + `c` the output is `čččččččččččččččččččč` instead of  one `č`.

I'm using sk-qwerty keyboard layout.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland fedora 40
Memory: 15 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-28 14:00
I wonder whether this is related or a duplicate of:
- https://github.com/zed-industries/zed/issues/12811

Curious, what is the key sequence you use to type `ó` and `č`?

**Comment by olilag** [comment] 2024-07-28 14:31
On slovak qwerty layout I used combination of `´|ˇ` key (`=|+` key on english layout) and `o` for `ó`, for `č` it's `shift` + `´|ˇ` + `c`.

**Comment by olilag** [comment] 2024-08-02 13:27
Yesterday I installed EndeavourOS with hyprland and on that system I don't have this problem.

So it looks like it maybe has something to do with Fedora.

**Comment by sylbru** [comment] 2024-09-24 10:24
I have that too, and I’m pretty sure it’s very recent or I would have been noticing it in the summer. I’m using French keyboard layouts on Linux, and regardless of whether I’m on the standard Linux "fr-oss" Azerty layout or my day-to-day Bépo layout, this happens.

The weird part is that some diacritics work while others don’t:

```
^a 
`a
˘a
~a
¨a
´a
ⱥ
ą
ạ
ˇa
```

The even weirder part is that among those that seem to work, some of them, when I copy them to this Github comment, appear as two characters instead of one.

Don’t work visibly in Zed:
- circumflex accent `^`
- grave accent `à`
- breve `˘`
- tilde `~`

Seem to work in Zed until I copy them somewhere else:
- caron `ˇ`
- trema `¨`
- acute accent `´`

Seem to work:
- bar/slash `ø`
- cedilla or ogonek `ç`
- underdot `ạ`

But for those who seem to work correctly in Zed, I notice the behaviour is not the native one: after typing the diacritic, while waiting for the following letter, the diacritic itself should be underlined. Here, it’s underlined only when it’s then displayed next to the letter instead of as one single character. It seems to me that Zed is doing here something that should stay in the hands of the OS.

The key sequences I’m doing to type these can be as simple as `^` (direct access) followed by a letter like `a`. Most other examples I gave are under `alt+something` followed by the letter.

**Comment by SylChamber** [comment] 2024-09-28 18:22
I have the same problem, and it's really irritating since I extensively use Markdown and an editor (Zed here) to take notes. I'm using the [Canadian Multilingual keyboard layout (CAN/CSA Z243.200-92)](https://en.wikipedia.org/wiki/CSA_keyboard), where the characters most used in French are directly available on the keyboard:

* `é` is on US layout key /
* `à` is on \
* `ç` is on ]
* `è` is on '
* `ù` is on a 105th key left of Z

When typing **any** international character, they are multiplied way faster than rabbits breed. ;-)  Then there are all the rest of accented French characters, done with a combination of two keys. They also are added multiple times when typing.

* `^` on [, used to make â, ê, î, ô, û
* ` on right alt-[ (the right alt key is special, different from the left one and is called AltGr; it allows typing many other characters), to make other combinations with vowels
* `¨`on shift-[, to make ä, ë, ï, ü
* a few others

In addition to AltGr (right alt), the right control key, CtrlGr, is also a special key which makes possible to type many more characters (e.g. © with Shift-CtrlGr-C, or ™ with Shift-CtrlGr-8). **It would be a good idea not to take into account right control and right alt keys when evaluating keyboard combinations.**

> **NOTE**: I just noticed that this issue does **not** happen when Zed is closed and I launch it to use it (because I just updated to 0.154.3). The issue **happens when I wake my laptop from sleep and Zed was already running**. Closing all instances of Zed and **relaunching** it make the problem disappear - until I put my laptop to sleep.

Zed: v0.154.3 and at least 4 previous versions
OS: Ubuntu 24.04 LTS/Wayland session
Memory: 16 GB
Architecture: x86_64
GPU1: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
GPU2: AMD Radeon Vega Series / Radeon Vega Mobile Series [Integrated]

**Comment by sylbru** [comment] 2024-10-02 09:19
Right now it doesn’t seem to happen anymore on my machine, not sure if it might have been fixed by mistake? (I tried on a fresh startup and after sleep/wakeup, as mentioned in the comment above, it worked correctly in both cases)

Current Zed version is 0.154.4.
@SylChamber (another Sylvain, that’s rare!) maybe you can try with that version?

**Comment by SylChamber** [comment] 2024-10-02 11:51
No, unfortunately, the problem persists on Zed 0.154.4. After wakeup, any Zed instance launched before sleep will produce multiples of any international characters I type. 

@sylbru Yes, most of the other Sylvain I meet are from the same generation as myself! (Gen X) It used to be a pretty common given name.

**Comment by sylbru** [comment] 2024-11-15 10:30
I’m not experiencing the issue anymore, @SylChamber are you still?

**Closed** 2024-11-15 15:15 UTC
Labels: bug, linux, internationalization, keymap / key binding

**Comment by SylChamber** [comment] 2024-11-15 18:04
I'm on stable channel, with Zed v0.161.2, and I'm still experiencing the issue (after the PC wakes from sleep, Zed being open before sleep). I'll see with 0.162 next week.
