### ISSUE TITLE
markdown: source code block elements should not display in outline panel

### ISSUE THREAD

**Issue by opsnull** [zed-industries/zed#19791] opened 2024-10-26 13:58 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I think markdown outline panel should not display source code block elements:

![图片](https://github.com/user-attachments/assets/c9455a20-2fbd-44b4-9420-e4ef056ba135)

### Environment

Zed: v0.160.0 (Zed Dev 03a1c8d2b8c1e1a623702b70796d1c5b1d265aff)
OS: macOS 15.0.1
Memory: 18 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-12-02 18:58
Duplicate of:
- https://github.com/zed-industries/zed/issues/15122

**Closed by notpeter** 2024-12-02 18:58 UTC
Labels: bug, markdown, outline
