### ISSUE TITLE
File with many errors becomes really slow while editing

### ISSUE THREAD

**Issue by Pedrofff23** [zed-industries/zed#17032] opened 2024-08-28 21:37 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After writing a big text in tsx (at the last lines where it should not be part of any function), in a a way where every word becomes an error (i was just saving a text for later), i got 395 errors in this file but I saw that the editor became really slow while scrolling my file or trying so select anything using the mouse in this file.

### Environment

OS:	Ubuntu 24.04.1 LTS
Zed: v0.150.4 (Zed)
Memory: 15.0 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/76011fbb-e041-4c07-8e5c-563debf05de2)

**Comment by osiewicz** [comment] 2024-08-28 21:47
That's already been fixed in the latest Preview (0.151.0); give it a go and let us know whether the issue is fixed for you.

**Closed** 2024-08-29 18:11 UTC
Labels: defect, performance, editor, linux, javascript, language, diagnostics, admin read, linux-x11
