### ISSUE TITLE
Should have remote shell login plugin or extension

### ISSUE THREAD

**Issue by shreyanshjain7174** [zed-industries/zed#9163] opened 2024-03-11 11:21 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Need an extension where I can login to the remote server and change the files there much like VScode have an extension called remote explorer.

**Comment by SomeoneToIgnore** [comment] 2024-03-11 11:30
Duplicate of https://github.com/zed-industries/zed/issues/5347 and some work in that direction also happens around https://github.com/zed-industries/zed/pull/9050

**Closed by SomeoneToIgnore** 2024-03-11 11:30 UTC
Labels: enhancement, triage, admin read
