### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by MONSTER-lion** [zed-industries/zed#13291] opened 2024-06-20 04:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

timeout

### Environment

mac m1 

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-06-20T12:15:35+08:00 [INFO] set status on client 85285: Reauthenticating
2024-06-20T12:15:39+08:00 [INFO] set status on client 85285: Reconnecting
2024-06-20T12:15:44+08:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-06-20T12:15:44+08:00 [INFO] set status on client 85285: ConnectionError
2024-06-20T12:15:44+08:00 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    0: request or operation took longer than the configured timeout time
    1: [28] Timeout was reached
2024-06-20T12:18:39+08:00 [WARN] request completed with error: request or operation took longer than the configured timeout time
2024-06-20T12:18:39+08:00 [ERROR] auto-update failed: error:request or operation took longer than the configured timeout time

**Comment by maxdeviant** [comment] 2024-06-20 11:45
This looks like a duplicate of https://github.com/zed-industries/zed/issues/13283, which you also opened.

**Comment by MONSTER-lion** [comment] 2024-06-20 15:04
如何解决呢？

**Comment by MONSTER-lion** [comment] 2024-06-20 15:04
> 这看起来像是创始人打开过的#13283的重复项。

如何解决呢

**Comment by notpeter** [comment] 2024-06-20 15:21
Closing this as a duplicate of #13283 which you opened 2 hours before this one.

Please do not open multiple issues for the same problem.

**Closed by notpeter** 2024-06-20 15:21 UTC
Labels: defect, triage, admin read
