### ISSUE TITLE
Autocomplete suggestions priority for Python imports doesn't match input accurately

### ISSUE THREAD

**Issue by taimast** [zed-industries/zed#21124] opened 2024-11-24 01:24 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I attempt to import a module in Python using the autocomplete feature (by pressing `Ctrl + Space`), the suggestions in the context menu do not prioritize based on the input accurately.

I expect that the suggestions list will first display options that most closely match the text I've input. For example, when typing `uuid`, the suggestion should prioritize `uuid` as the first option.

### Environment

Zed: v0.164.0 (Zed Dev 75c545aa1e7a9cb01febf2f6dc00536c7271ff2f)
OS: Windows 10.0.22631
Memory: 63.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 5600 XT || AMD proprietary driver || 24.10.27.01 (AMD proprietary shader compiler)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/e7da9a43-e979-420d-8645-ffe0cab3eb0d

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-11-26 13:29
Duplicate of:
- https://github.com/zed-industries/zed/issues/12698
- https://github.com/zed-industries/zed/issues/4327

**Closed by notpeter** 2024-11-26 13:29 UTC
Labels: bug, triage, admin read
