### ISSUE TITLE
Feature Request: Folder copy

### ISSUE THREAD

**Issue by oo00spy00oo** [zed-industries/zed#7490] opened 2024-02-07 10:47 UTC
### Check for existing issues

- [ ] Completed

### Describe the feature

As a developer, I want to copy/duplicate one or many folder(s) in my workspace.

**Comment by JosephTLyons** [comment] 2024-02-08 20:38
Hey @oo00spy00oo,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4983

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-08 20:38 UTC
Labels: enhancement, project panel
