### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by RegonGaming** [zed-industries/zed#14312] opened 2024-07-12 08:58 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

The name says it all. I want my touchscreen to work on zed.

**Comment by RegonGaming** [comment] 2024-07-12 09:01
i just noticed there's a bug report for this but it doesn't have much talk around it so i don't think touchscreen support exists yet.

**Comment by someone13574** [comment] 2024-07-13 02:05
What platform are you on? Windows, Linux/X11, Linux/Wayland, other?

**Comment by RegonGaming** [comment] 2024-07-13 09:07
Arch Linux with KDE and Wayland
(im using thinkpad x390 if that matters)

**Comment by Moshyfawn** [comment] 2024-07-15 13:13
This seems to have been suggested already, so I'll close this thread in favour of the other one. Be sure to +👍 and discuss this feature in the other thread instead.

Duplicate of:
- #13698

**Closed by Moshyfawn** 2024-07-15 13:13 UTC
Labels: enhancement, triage, admin read
