### ISSUE TITLE
Search in terminal doesn't work in preview release

### ISSUE THREAD

**Issue by schpet** [zed-industries/zed#20640] opened 2024-11-13 23:24 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

i frequently command-f in the terminal, but on the [latest preview release](https://zed.dev/releases/preview/0.162.0) command-f doesn't seem to do anything in the terminal. it works in the stable release.

### Environment

Zed: v0.162.0 (Zed Preview)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-14 09:13
This does not mention the language, so hard to do anything useful.
Will close as a duplicate of https://github.com/zed-industries/zed/issues/16619

**Comment by SomeoneToIgnore** [comment] 2024-11-14 10:24
I suspect https://github.com/zed-industries/zed/pull/20579 is the offender, but the most odd thing is that `Nightly` and builds from freshmost `main` work for me with the terminal search (and that functionality from the PR too).

So maybe, there's a wrong/missed cherry-pick to blame? cc @ConradIrwin

**Comment by SomeoneToIgnore** [comment] 2024-11-14 15:52
0.162.1 is our and that seems to have fixed things, can you recheck @schpet ?

**Comment by schpet** [comment] 2024-11-14 16:23
@SomeoneToIgnore yep, thanks!

**Closed** 2024-11-14 16:22 UTC
Labels: bug, triage, admin read
