### ISSUE TITLE
Editor: toggle comment works incorrectly for JSX/TSX

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [zed-industries/zed#16831] opened 2024-08-25 14:07 UTC
### Describe the bug / provide steps to reproduce it

Create a file `hello.jsx` with the following content:
```jsx
let x = <>
  <div>hello</div>
  <div>world</div>
</>
```

Put the cursor on the third line ("world") and hit `Cmd-/` (Editor: toggle comments).

Expected result:
```jsx
let x = <>
  <div>hello</div>
  {/* <div>world</div> */}
</>
```

Actual result:
```jsx
let x = <>
  <div>hello</div>
  // <div>world</div>
</>
```

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-08-25 14:14
https://github.com/zed-industries/zed/issues?q=is%3Aissue+jsx+is%3Aclosed

Closing as a duplicate of https://github.com/zed-industries/zed/issues/16337

**Closed by SomeoneToIgnore** 2024-08-25 14:14 UTC
Labels: defect, triage, admin read
