### ISSUE TITLE
workspace terminal panel doesn't allow split view 

### ISSUE THREAD

**Issue by rkdud007** [zed-industries/zed#16565] opened 2024-08-21 02:00 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When the terminal is placed in the workspace panel, the split view button is not working. The Split Pane should work for both the code base and terminal base.

https://github.com/user-attachments/assets/c45a8efe-1b53-4777-8272-e983c2304db2

 
+ As an aside, I'm curious why you're maintaining both a `terminal_view` and a workspace panel that can contain a terminal. It feels like it might be cleaner to unify these into the workspace panel. Instead of having a dedicated terminal view, you could use the workspace panel, which already supports focus splitting, when creating a new terminal.

**Comment by liouk** [comment] 2024-08-22 11:40
I have the same issue on zed 0.149.3 on linux. I've managed to work around this with the following keymap:

```json
{
	"context": "Workspace",
	"bindings": {
		"ctrl-e": "pane::SplitRight",
		"ctrl-space": "command_palette::Toggle",
		"ctrl-a t": [
			"workspace::SendKeystrokes",
			"ctrl-e ctrl-space new center terminal enter"
		]
	}
}
```

So basically typing `ctrl-a t` basically does the following:
1. splits the current pane to the right (`ctrl-e`)
2. opens the command palette (`ctrl-space`)
3. types `new center terminal`
4. hits `enter`

The result is a split to the right with one buffer and one terminal. Not ideal, as I don't necessarily want the extra buffer, but that's the only way I can currently do it.

**Comment by JosephTLyons** [comment] 2024-08-23 19:46
Hey @rkdud007,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4351

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-08-23 19:46 UTC
Labels: enhancement, terminal
