### ISSUE TITLE
Can't open file with colons or slashes in the name with any means other then File → Open on Mac

### ISSUE THREAD

**Issue by Alazoral** [zed-industries/zed#15957] opened 2024-08-08 06:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Create and save a file with forward slashes in the name, for example a date, like `8/8/2024.txt` in TextEdit, or alternatively, create a file with colons in the UNIX command line, for example with `ls > 12:34PM.txt`
2. Attempt to open that file by any of the following standard methods:
  - dragging it on to an open editor,
  - dragging it on to the Zed icon in the dock
  - right clicking the file in Finder and picking Open With → Zed 
  - setting Zed as the default association for the file type and then double-clicking the file in Finder
  - use the `open` command in Terminal, for instance, `open 8:8:2024.txt -a Zed.app`
3. Notice that instead of opening the file, Zed will create a new buffer named for the first segment before the first slash or colon.

These methods work fine for other apps. File → Open also works fine in either case.

I believe the issue here is related to how Mac OS X and forward escapes path separators. On Mac OS 9 and before, colons were used as path separators. To ensure compatibility with those filenames as well as the new Unix underpinnings, Mac OS X exposes`/` as `:` to the UNIX environment, and vice versa for the Mac OS environment.

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-08-08T06:01:00.439049Z [INFO] open paths ["/Users/alazoral/Repositories/test/passed/file/2024-08-08T04"]
2024-08-08T06:01:00.443398Z [ERROR] failed to canonicalize root path: No such file or directory (os error 2)
</pre></details>

**Comment by notpeter** [comment] 2024-08-09 19:56
I was able to reproduce this.  When I create filenames that have colons in them on MacOS Zed does not handle opening them correctly. Very confusing how MacOS/Finder displays filenames with colons as if they had slashes.  So `12:34PM.txt` on the filesystem shows up as `12/34PM.txt` in Finder.

I think this is potentially a duplicate of:
- https://github.com/zed-industries/zed/issues/14100

Looks like there's also a potential fix in a PR too:
- https://github.com/zed-industries/zed/pull/15777

**Closed by notpeter** 2024-08-09 19:56 UTC
Labels: defect, cli, macOS
