### ISSUE TITLE
Golang Some methods cannot be navigated

### ISSUE THREAD

**Issue by Zev3691** [zed-industries/zed#7192] opened 2024-02-01 07:59 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using Zed on the macOS system, and I'm unable to use cmd + left mouse click to navigate to my own methods. I'm not sure if my description is accurate, so I've attached a GIF image to illustrate the issue.

### Environment

![image](https://github.com/zed-industries/zed/assets/26448696/3e5d3fbf-b3d4-494f-920f-d55b9c60c61e)
![image](https://github.com/zed-industries/zed/assets/26448696/7b603671-6abc-4a04-be8f-429abf265fcf)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![20240201-155142](https://github.com/zed-industries/zed/assets/26448696/e9b0a0d5-51e2-4192-bbb7-a21c31b274aa)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mrnugget** [comment] 2024-02-01 08:00
Since you are already on the definition of `TrimSpace`, where do you expect the click to go?

**Comment by TENX-S** [comment] 2024-02-01 08:21
@Zev3691 I guess Zed doesn't have this feature(cmd+click to find reference(s) on a symbol) for now.

**Comment by Zev3691** [comment] 2024-02-01 08:28
Perhaps I should change the habits I brought from VSCode. wish Zed can support this feature soon.

**Comment by mrnugget** [comment] 2024-02-01 08:30
Yeah, you can right click and select `Find all references`. But we don't support this on click.

Should we close the issue or convert it into a feature request?

**Comment by TENX-S** [comment] 2024-02-01 08:41
+1 for converting it into a FR. Because I have that habit too.

**Comment by Zev3691** [comment] 2024-02-01 08:46
> Yeah, you can right click and select `Find all references`. But we don't support this on click.
> 
> Should we close the issue or convert it into a feature request?

Respecting your arrangement, for now, I can use the right-click as a substitute.

**Comment by JosephTLyons** [comment] 2024-02-01 21:05
Hey, we have an issue tracking this exact feature (I've been wanting this for a long time 😂)

- https://github.com/zed-industries/zed/issues/5351

**Comment by mrnugget** [comment] 2024-02-06 09:41
I'm going to close this since it seems like it is a duplicate of #5351 in its request. (We can reopen if someone disagrees with that!)

**Closed by mrnugget** 2024-02-06 09:41 UTC
Labels: enhancement, language, language server
