### ISSUE TITLE
Zed Font Error

### ISSUE THREAD

**Issue by JoseSanchez54** [zed-industries/zed#11484] opened 2024-05-07 09:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have installed zed, but the source is completely broken and I can't find a solution.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/55786662/8c46e4be-4507-405a-86b0-4c872a2d2a3b)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-05-07T11:49:26+02:00 [INFO] starting language servers for JSON: json-language-server
2024-05-07T11:50:13+02:00 [ERROR] crates/lsp/src/lsp.rs:768: oneshot canceled

2024-05-07T11:53:06+02:00 [INFO] starting language servers for JSON: json-language-server
2024-05-07T11:53:12+02:00 [ERROR] crates/lsp/src/lsp.rs:768: oneshot canceled

**Comment by jansol** [comment] 2024-05-07 11:08
Does your mac happen to have an NVIDIA GPU? Because this looks suspiciously like #5062

**Comment by JoseSanchez54** [comment] 2024-05-07 11:19
> Does your mac happen to have an NVIDIA GPU? Because this looks suspiciously like #5062

mmmm yes my gpu is NVIDIA Geforce 675

**Comment by Moshyfawn** [comment] 2024-05-08 02:02
This seems to be a duplicate issue. I'm going to close this, but be sure to +👍 the other issue and add any missing information to the other thread.

Duplicate of:
- #5062

**Closed by Moshyfawn** 2024-05-08 02:02 UTC
Labels: defect, triage, admin read
