### ISSUE TITLE
FPS and input lag on the MacBook Air M1

### ISSUE THREAD

**Issue by SergeiKanerva** [zed-industries/zed#20759] opened 2024-11-16 08:22 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello everyone,

I'm having performance issue with Zed on M1 MacBook Air.
My input and scrolling feels "laggy", sometimes with (what feels like) significant delay, fps sometimes feels like 10-20.

I've checked available storage for swaps on Mac - I have at least 20GB of free memory
I have 8GB RAM, but the lag is almost constant even if nothing except Zed is open.
OS: macOS 14.5.0

I don't have any technical files to support the issue, but if my research will lead somewhere - I'll update the issue.

### Environment

Zed: v0.161.2 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-11-18 20:37
I'm curious if this varies between languages / language servers / projects, but to be blunt, 8GB can be pretty tight.  You might open Activity monitor, select the memory tab and choose View->All Processes hierarchically to see where memory is being used and see if you can kill some background tasks.

For example, when I'm editing the Zed code base (moderate sized rust project) Zed is pretty steady at 350MB of memory with occasional spikes to 550MB.  But...rust-analyzer is happy to use 3GB+ and other node-based language servers can easily eat up 500MB-1GB or more:
<img width="606" alt="Screenshot 2024-11-18 at 13 40 18" src="https://github.com/user-attachments/assets/5e1ceb03-bac4-41c3-a21a-5e16babc1819">

Given that on my machine Window Server (1.67GB), Finder (340MB), Emoji & Symbols (570MB), Spotlight (230MB), Dock (210MB), mds (200MB), Notification Center (110MB), Control Center (100MB), mds_store (80MB), collectively take 3.3GB + another few hundred MB for other miscellaneous services. That leaves at best 4-5GB of ram for everything else (including file cache).

I'm focused on memory because I know once there is memory pressure things may be getting swapped out to disk.  The SSD on your Macbook is not particularly slow (~2GB/sec sequential read, ~590MB/sec random read) but if Zed needs some memory that is swapped out, it's very easy to imagine a fraction of a second stall while this is swapped back in.  If your dev environment requires exclusive memory (e.g. Docker/podman virtual machine) you're going to be squeezed even further.

Without more information (or a 8GB M1 to try and daily drive) I'm inclined to close this as unactionable.  If you have some specific reproduction cases or some additional traces/measurement that suggest areas or ways we might improve Zed, I'm happy to reopen.

Sorry you're not having a great experience with Zed, but thanks for taking the time to report your experience.

**Closed by notpeter** 2024-11-18 20:37 UTC
Labels: bug, triage, admin read
