### ISSUE TITLE
Input keystrokes are not being registered

### ISSUE THREAD

**Issue by AjithPanneerselvam** [zed-industries/zed#16346] opened 2024-08-16 09:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Input keystrokes are not being registered in the editor, although command inputs are working fine. In the provided screen recording, Vim commands like `o` and `d` in Normal mode function as expected. Additionally, shortcuts for opening the command palette works, but input within the command palette is not registered. This issue persists even when Vim mode is disabled, suggesting it is unrelated to Vim mode. 

To sum up, command inputs (such as Vim commands or shortcuts) are registered correctly, but general input keystrokes are not getting registered.

**Temporary Fix**
- Restarting the editor temporarily resolves the issue, but it reappears after some time.

**My Settings**

```
{
  "theme": "Gruvbox Material",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "vim_mode": true,
  "git": {
    "inline_blame": {
      "enabled": false
    }
  }
}
```

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/6182973c-ba85-46a1-a0a7-48149376f0f6

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

  
0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T15:03:02.019992Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T15:03:02.031672Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T15:03:02.031987Z [INFO] set status on client 213568: Reconnecting
2024-08-15T15:03:02.372764Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T15:03:02.830471Z [INFO] add connection to peer
2024-08-15T15:03:02.830598Z [INFO] add_connection;
2024-08-15T15:03:02.830927Z [INFO] waiting for server hello
2024-08-15T15:03:02.832834Z [INFO] got server hello
2024-08-15T15:03:02.833075Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 2 }, peer id: PeerId { owner_id: 483, id: 203041 })
2024-08-15T15:03:02.833245Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 483, id: 203041 }, connection_id: ConnectionId { owner_id: 0, id: 2 } }
2024-08-15T16:03:32.082305Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.085696Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.085774Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.089141Z [ERROR] content modified
2024-08-15T16:03:32.089257Z [ERROR] content modified
2024-08-15T16:03:32.089331Z [ERROR] content modified
2024-08-15T16:03:32.403536Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.403639Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.403702Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.403766Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.403835Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.403906Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.403972Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.404041Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:03:32.41815Z [ERROR] content modified
2024-08-15T16:03:32.418238Z [ERROR] content modified
2024-08-15T16:03:32.418291Z [ERROR] content modified
2024-08-15T16:03:32.418343Z [ERROR] content modified
2024-08-15T16:03:32.418397Z [ERROR] content modified
2024-08-15T16:03:32.418451Z [ERROR] content modified
2024-08-15T16:03:32.418503Z [ERROR] content modified
2024-08-15T16:03:32.418563Z [ERROR] content modified
2024-08-15T16:04:00.622393Z [INFO] Initializing default prettier with plugins {}
2024-08-15T16:04:00.622952Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:04:12.24295Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:04:12.243466Z [ERROR] content modified
2024-08-15T16:05:18.406763Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:05:18.408738Z [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-08-15T16:05:18.409244Z [ERROR] content modified
2024-08-15T16:05:18.409503Z [ERROR] content modified
2024-08-15T16:07:24.721308Z [INFO] Initializing default prettier with plugins {}
2024-08-15T16:07:24.721885Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.315113Z [INFO] Initializing default prettier with plugins {}
2024-08-15T16:07:36.315394Z [INFO] starting language servers for YAML: yaml-language-server
2024-08-15T16:07:36.315466Z [INFO] starting language server "yaml-language-server", path: "/Users/ajith.panneerselvam/work/ledger", id: 2
2024-08-15T16:07:36.319618Z [INFO] Initializing default prettier with plugins {}
2024-08-15T16:07:36.319699Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.319765Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.31983Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.319893Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.319953Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320012Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320131Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320188Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320246Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320304Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320362Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.32042Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320478Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320535Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320591Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320647Z [INFO] starting language servers for YAML: yaml-language-server
2024-08-15T16:07:36.320703Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320758Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320814Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320869Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320925Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.320981Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.321036Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.321092Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.321148Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.321209Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-15T16:07:36.345294Z [INFO] fetching latest version of language server "yaml-language-server"
2024-08-15T16:07:36.345721Z [INFO] Node runtime install_if_needed
2024-08-15T16:07:36.366193Z [WARN] request completed with error: failed to connect to the server
2024-08-15T16:07:37.560879Z [INFO] downloading language server "yaml-language-server"
2024-08-15T16:07:37.563341Z [INFO] Node runtime install_if_needed
2024-08-15T16:07:38.747662Z [INFO] Node runtime install_if_needed
2024-08-15T16:07:38.885538Z [INFO] starting language server. binary path: "/Users/ajith.panneerselvam/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/ajith.panneerselvam/work/ledger", args: ["/Users/ajith.panneerselvam/Library/Application Support/Zed/languages/yaml-language-server/node_modules/yaml-language-server/bin/yaml-language-server", "--stdio"]
2024-08-15T16:07:39.207141Z [WARN] unhandled capability registration: Registration { id: "6c17be55-d095-4623-b798-1c6a05830532", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-08-15T16:07:39.207297Z [WARN] unhandled capability registration: Registration { id: "f50bc6b7-f00b-4ea0-8f80-96314679ecd0", method: "workspace/didChangeConfiguration", register_options: Some(Object {}) }
2024-08-15T16:08:08.267555Z [INFO] Waiting for default prettier to install
2024-08-15T16:08:08.268368Z [INFO] Starting prettier at path "/Users/ajith.panneerselvam/Library/Application Support/Zed/prettier"
2024-08-15T16:08:08.268485Z [INFO] Node runtime install_if_needed
2024-08-15T16:08:08.567626Z [INFO] starting language server. binary path: "/Users/ajith.panneerselvam/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/ajith.panneerselvam/Library/Application Support/Zed/prettier", args: ["/Users/ajith.panneerselvam/Library/Application Support/Zed/prettier/prettier_server.js", "/Users/ajith.panneerselvam/Library/Application Support/Zed/prettier"]
2024-08-15T16:08:08.650331Z [INFO] Started default prettier in "/Users/ajith.panneerselvam/Library/Application Support/Zed/prettier"
2024-08-15T17:08:26.965574Z [ERROR] connection error: error reading rpc message from socket

Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T17:08:26.969425Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T17:08:26.985414Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T17:08:26.98551Z [INFO] set status on client 213568: Reconnecting
2024-08-15T17:08:27.267968Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T17:08:27.740533Z [INFO] add connection to peer
2024-08-15T17:08:27.740871Z [INFO] add_connection;
2024-08-15T17:08:27.741211Z [INFO] waiting for server hello
2024-08-15T17:08:27.743379Z [INFO] got server hello
2024-08-15T17:08:27.74382Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 3 }, peer id: PeerId { owner_id: 483, id: 270643 })
2024-08-15T17:08:27.743967Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 483, id: 270643 }, connection_id: ConnectionId { owner_id: 0, id: 3 } }
2024-08-15T18:40:50.112931Z [ERROR] connection error: error reading rpc message from socket

Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T18:40:50.117649Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T18:40:50.146817Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T18:40:50.146902Z [INFO] set status on client 213568: Reconnecting
2024-08-15T18:40:50.522509Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T18:40:52.033292Z [INFO] add connection to peer
2024-08-15T18:40:52.033394Z [INFO] add_connection;
2024-08-15T18:40:52.033716Z [INFO] waiting for server hello
2024-08-15T18:40:54.587649Z [INFO] got server hello
2024-08-15T18:40:54.588684Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 4 }, peer id: PeerId { owner_id: 484, id: 4682 })
2024-08-15T18:40:54.589456Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 484, id: 4682 }, connection_id: ConnectionId { owner_id: 0, id: 4 } }
2024-08-15T19:38:04.422672Z [ERROR] connection error: error reading rpc message from socket

Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T19:38:04.427771Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T19:38:04.455593Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T19:38:04.455683Z [INFO] set status on client 213568: Reconnecting
2024-08-15T19:38:04.969347Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T19:38:05.421231Z [INFO] add connection to peer
2024-08-15T19:38:05.421435Z [INFO] add_connection;
2024-08-15T19:38:05.421953Z [INFO] waiting for server hello
2024-08-15T19:38:05.423804Z [INFO] got server hello
2024-08-15T19:38:05.424128Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 5 }, peer id: PeerId { owner_id: 484, id: 38045 })
2024-08-15T19:38:05.424244Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 484, id: 38045 }, connection_id: ConnectionId { owner_id: 0, id: 5 } }
2024-08-15T20:55:06.223238Z [ERROR] connection error: error reading rpc message from socket

Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T20:55:06.227408Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T20:55:06.246596Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T20:55:06.246713Z [INFO] set status on client 213568: Reconnecting
2024-08-15T20:55:06.616666Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T20:55:07.085795Z [INFO] add connection to peer
2024-08-15T20:55:07.085881Z [INFO] add_connection;
2024-08-15T20:55:07.086226Z [INFO] waiting for server hello
2024-08-15T20:55:07.088611Z [INFO] got server hello
2024-08-15T20:55:07.088889Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 6 }, peer id: PeerId { owner_id: 484, id: 79090 })
2024-08-15T20:55:07.089012Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 484, id: 79090 }, connection_id: ConnectionId { owner_id: 0, id: 6 } }
2024-08-15T21:34:46.764216Z [ERROR] connection error: error reading rpc message from socket

Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T21:34:46.767326Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T21:34:46.778849Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T21:34:46.779118Z [INFO] set status on client 213568: Reconnecting
2024-08-15T21:34:47.283992Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T21:34:47.710431Z [INFO] add connection to peer
2024-08-15T21:34:47.710678Z [INFO] add_connection;
2024-08-15T21:34:47.711129Z [INFO] waiting for server hello
2024-08-15T21:34:47.71337Z [INFO] got server hello
2024-08-15T21:34:47.713732Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 7 }, peer id: PeerId { owner_id: 485, id: 6708 })
2024-08-15T21:34:47.714065Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 485, id: 6708 }, connection_id: ConnectionId { owner_id: 0, id: 7 } }
2024-08-15T21:51:33.729405Z [ERROR] connection error: error reading rpc message from socket

Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-08-15T21:51:33.731019Z [INFO] set status on client 213568: ConnectionLost
2024-08-15T21:51:33.737754Z [INFO] set status on client 213568: Reauthenticating
2024-08-15T21:51:33.737989Z [INFO] set status on client 213568: Reconnecting
2024-08-15T21:51:34.098655Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-15T21:51:34.569166Z [INFO] add connection to peer
2024-08-15T21:51:34.56959Z [INFO] add_connection;
2024-08-15T21:51:34.569782Z [INFO] waiting for server hello
2024-08-15T21:51:34.571195Z [INFO] got server hello
2024-08-15T21:51:34.57153Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 8 }, peer id: PeerId { owner_id: 485, id: 15811 })
2024-08-15T21:51:34.57201Z [INFO] set status on client 213568: Connected { peer_id: PeerId { owner_id: 485, id: 15811 }, connection_id: ConnectionId { owner_id: 0, id: 8 } }
2024-08-15T21:55:42.423787Z [ERROR] connection error: error reading rpc message from socket

</pre></details>

**Comment by kascote** [comment] 2024-08-18 00:09
I reported the same issue on v0.136.2 and disappeared around 0.138. I'm using the same version 0.148 and it doesn't happen to me (yet 🤞🏼). ref: #12265

**Comment by notpeter** [comment] 2024-08-22 19:20
Closing as duplicate of 
- #12265

**Closed by notpeter** 2024-08-22 19:20 UTC
Labels: defect, triage, admin read

**Comment by zeelios** [comment] 2025-03-08 15:44
I'm having the same issue, all the number keys are registered normally, but not the alphs
