### ISSUE TITLE
Add language support for flow (the static type checker for javascript)

### ISSUE THREAD

**Issue by acusti** [zed-industries/zed#11478] opened 2024-05-07 03:10 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

i’ve been a little hesitant to request this because flow has been so thoroughly trounced in popularity by typescript, but one of the main codebases i work on is a react-based web application written in flow, and trying to work on it in Zed is a nightmare of blue and red squiggly underlines. in [VSCode](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode), flow support is enabled via the [`flow-for-vscode` LSP](https://github.com/flow/flow-for-vscode), which makes me hopeful that it wouldn’t be too big of a lift to enable it for Zed. one quirk is that flow files all have the `.js` (or `.cjs` or `.mjs`) file extension and are differentiated as being authored with the flow syntax by the presence of the `// @flow` (or `/* @flow */`) preamble.

fwiw, i did recently run into someone else who sometimes works on a flow codebase (one of the JSParty podcast hosts), and the flow project has recently doubled down on being the premiere static type checker for React (with [special component syntax](https://medium.com/flow-type/announcing-component-syntax-b6c5285660d0)), so there are likely others who could benefit from this as well.

**Comment by Moshyfawn** [comment] 2024-05-08 02:05
There's already a community request in the [zed-industries/extensions](https://github.com/zed-industries/extensions) repository to add Flow support. Be sure to upvote it there!

Duplicate of:
- zed-industries/extensions#474

**Closed by Moshyfawn** 2024-05-08 02:05 UTC
Labels: enhancement, triage, admin read

**Comment by acusti** [comment] 2024-05-08 14:54
@Moshyfawn thanks for the heads up! i didn’t think to search for an issue about it there.

**Comment by Moshyfawn** [comment] 2024-05-08 16:02
No problem!
