### ISSUE TITLE
Request for Swift Language Syntax Support

### ISSUE THREAD

**Issue by MerlinHof** [zed-industries/zed#8114] opened 2024-02-21 08:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to request the addition of syntax highlighting support for the Swift programming language in ZED editor. Swift is a powerful and intuitive language that is both open source and cross-platform, making it an essential tool for a wide range of applications. The addition of Swift to ZED's supported languages would greatly enhance the usability of the editor for developers who work with Swift on a regular basis.

Swift's syntax is concise yet expressive, and its modern features facilitate software design patterns that produce clean, reusable code. Integrating Swift syntax highlighting into ZED would not only aid current developers in writing and reviewing code more effectively but also attract new users who are looking for a sophisticated editor that supports the latest programming languages.

By supporting Swift, ZED could position itself as a real alternative to Xcode, especially for developers who face performance issues with Xcode on older machines. Unlike Xcode, which can be notoriously slow on less capable hardware, ZED is renowned for its focus on speed and smooth operation.

Please consider this feature request to accommodate the growing number of developers adopting Swift for its simplicity and performance capabilities.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1433" alt="swift_in_vsc" src="https://github.com/zed-industries/zed/assets/119101408/9e63c68c-2764-43cb-9d1c-4cc2c2cd126f">
<img width="1552" alt="swift_in_zed_sad" src="https://github.com/zed-industries/zed/assets/119101408/e3418903-11d9-494e-9e0a-f7e472570dfb">

**Comment by SomeoneToIgnore** [comment] 2024-02-21 10:27
Duplicate of https://github.com/zed-industries/zed/issues/5278

**Closed by SomeoneToIgnore** 2024-02-21 10:27 UTC
Labels: enhancement, triage, admin read

**Comment by JosephTLyons** [comment] 2024-02-23 17:54
Closing in favor for #5278
