### ISSUE TITLE
Image Viewer: Image may need to be adaptive according to the current size of ZED

### ISSUE THREAD

**Issue by weartist** [zed-industries/zed#10001] opened 2024-03-31 06:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The image preview seems to have made some adaptations, for example, when adjusting the height of the zed window, he will not distort the image, only the truncated part will be displayed, but if the width is adjusted, he will compress the image, maybe it would be better to let the picture automatically adjust the length and width of the display according to the size of the window, I can provide a PR to fix the problem

Expectation: The image will not be captured, compressed, and will resize itself within the current window to show its original resolution

<img width="1536" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/395a40db-0fdd-40fd-8113-612ce6d299cf">

When the height is adjusted, only a portion of the content is displayed:
<img width="1536" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/4781b90f-319e-42b1-9258-10cb972b63ec">

<img width="1977" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/f0e357fe-e4a7-4a1d-8a5d-756b780119aa">
When we adjust the width, the image is compressed horizontally:
<img width="1241" alt="image" src="https://github.com/zed-industries/zed/assets/17105034/e11cc227-8b72-4375-9aa9-5957584b7969">

### Environment

Zed: v0.127.5 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-04-01 02:36
This has already been reported, so I'm going to close this thread in favour of the existing one to keep the conversation in one place. Be sure to +👍 the other issue.

Duplicate of
- #9560

**Closed by Moshyfawn** 2024-04-01 02:36 UTC
Labels: defect, triage, admin read
