### ISSUE TITLE
Mistral.ai support, at least only in the documentation.

### ISSUE THREAD

**Issue by aliresool2001** [zed-industries/zed#22363] opened 2024-12-23 04:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

The same applies to deepseek.

### Zed Version and System Specs

request feature

**Comment by SomeoneToIgnore** [comment] 2024-12-23 09:30
Duplicate of https://github.com/zed-industries/zed/issues/12519

**Closed by SomeoneToIgnore** 2024-12-23 09:30 UTC
Labels: enhancement, triage, admin read
