### ISSUE TITLE
Open settings on linux crashes the editor

### ISSUE THREAD

**Issue by rafakwolf** [zed-industries/zed#15354] opened 2024-07-27 19:19 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried opening the settings

### Environment

![image](https://github.com/user-attachments/assets/322a005c-86d2-47f3-90ac-b020ab9e41a7)
 
OS info:

Ubuntu 22.04.4
 Shell: zsh 5.8.1 
 Resolution: 1920x1080, 1920x1080 
 DE: Plasma 6.1.2 
 Kernel: 6.5.0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16401244/Zed.log)

</pre></details>

**Comment by notpeter** [comment] 2024-07-28 13:36
In your log I'm seeing:
> "Could not start file watcher: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: \"Too many open files\" }), paths: [] }"

Could you check your inotify limits and see if bumping `fs.inotify.max_user_instances` helps? The default on my Ubuntu22 system was 128 which needs to be bumped up.

```
# check the current value
sysctl fs.inotify.max_user_instances
# temporarily bump up the value (until next reboot)
sudo sysctl -w fs.inotify.max_user_instances=131072
# check to see if it works
```

To permanent up the value:
```
# Create a `sysctl.conf` which modifies the value
echo "fs.inotify.max_user_instances = 131072" | sudo tee /etc/sysctl.d/99-inotify.conf
# Re-apply the settings found in the files.
sudo sysctl --system
# check the current value
sysctl fs.inotify.max_user_instances
```

Duplicate of:
- #10310

**Closed by notpeter** 2024-07-28 13:36 UTC
Labels: defect, triage, panic / crash, admin read

**Comment by rafakwolf** [comment] 2024-07-30 14:21
FYI, yes, that solves the issue
thank you!
