### ISSUE TITLE
When Opening a file using the latest version of the src from the zed githiub. the editor will crash when using vscode CTRL+O to open a folder

### ISSUE THREAD

**Issue by charlie-sans** [zed-industries/zed#11404] opened 2024-05-05 15:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

with a folder open already in the code editor, run the vscode Control + O command to open a folder.
find a folder that you want to open and open it. zed will attempt to open the folder and then crash.

### Environment

Zed: v0.135.0 (Zed Dev 14c7782ce67887f9c41fecd01ff5168ada41cb28)
OS: Windows 10.0.22631
Memory: 15.7 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[log.txt](https://github.com/zed-industries/zed/files/15213470/log.txt)

**Comment by Moshyfawn** [comment] 2024-05-05 16:00
This appears to be a duplicate issue. I'm going to close this one in favour of the other; be sure to +👍 and add any additional information that may be missing.

Duplicate of:
- #11094

**Closed by Moshyfawn** 2024-05-05 16:00 UTC
Labels: defect, panic / crash, workspace, windows, admin read
