### ISSUE TITLE
use_center_terminal: <bool> settings for task.json

### ISSUE THREAD

**Issue by JonGretar** [zed-industries/zed#16909] opened 2024-08-26 18:29 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I would love to be able to set the option `"use_center_terminal": true` for tasks. 

This would allow me to create global tasks (and bind keyboard shortcuts) to start tools such as `lazygit`, `posting` and others in the main window. With these tools bound to a shortcut I would not even need a plugin system in Zed.

On a related note. A tasks spawn command on a task already running(where use_new_terminal and allow_concurrent_runs is false) should probably focus on that terminal as it does with new tasks.

### If applicable, add mockups / screenshots to help present your vision of the feature

![LazyGit-Zed](https://github.com/user-attachments/assets/86b1929e-3127-4bc4-b35a-4472329fe631)

**Comment by danielfigueiredo** [comment] 2024-10-07 17:23
any workarounds for this?

**Comment by baldwindavid** [comment] 2024-12-04 23:33
Think this is mostly a duplicate of #9445

**Closed** 2024-12-05 09:23 UTC
Labels: enhancement, terminal, setting, tasks
