### ISSUE TITLE
`workspace::ToggleBottomDock` no-op when Bottom Dock is focused

### ISSUE THREAD

**Issue by plaukiu** [zed-industries/zed#4454] opened 2023-09-23 13:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. from the Main Editor focus, call `workspace::ToggleBottomDock`
-> Bottom Dock opens, is focused.
3. from the Bottom Dock focus, call `workspace::ToggleBottomDock`
-> **Bottom Dock doesn't close**. _expected:_ Bottom Dock closes.
4. focus Main Editor, call `workspace::ToggleBottomDock`
-> Bottom Dock closes.

### Environment

Zed: v0.104.4 (stable)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-03-21 03:29
I believe this is working as intended at this time. I'm going to close this issue, but feel free to reopen it if it's still relevant.

**Closed by Moshyfawn** 2024-03-21 03:29 UTC
Labels: defect, needs info / awaiting response, panel
