### ISSUE TITLE
Highlight files on the sidebar when file has an issue 

### ISSUE THREAD

**Issue by sarzhann** [zed-industries/zed#17259] opened 2024-09-02 07:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When some issues arise in the project and LSP detects them, it's convenient to see which files are affected through the sidebar by coloring them red.

### If applicable, add mockups / screenshots to help present your vision of the feature

example in vscode 
<img width="359" alt="image" src="https://github.com/user-attachments/assets/60c289d6-7ad5-4125-bd8d-64939416e039">

**Comment by bennetbo** [comment] 2024-09-02 08:34
Duplicate of #5016, feel free to upvote that issue (👍🏻 +1)

**Closed by bennetbo** 2024-09-02 08:34 UTC
Labels: enhancement, triage, admin read
