### ISSUE TITLE
Line number spacing has an offset to the actual lines numbers in large files

### ISSUE THREAD

**Issue by hylaride** [zed-industries/zed#14745] opened 2024-07-18 14:51 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After opening a very large log file, I noticed the spacing for line number as well as highlighting is off (this example is a large random text file I generated for privacy reasons `openssl rand -out sample.txt -base64 $(( 2**30 * 3/4 ))`):
![Here](https://github.com/user-attachments/assets/6db4eae9-c535-495a-bba7-f622a00c9531)

At the beginning of the file (and smaller files in general) it's fine:
![Beginning](https://github.com/user-attachments/assets/c7fc3f77-1453-4f06-b954-43f54875ee53)

At first I thought it was due to my custom font/buffer sizes and custom buffer_line_height, but this still happens with the default config:
![Screenshot 2024-07-18 at 10 50 08](https://github.com/user-attachments/assets/e5fb6bee-e58e-49d8-a599-dedce28f129c)

### Environment

Zed: v0.144.3 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment] 2024-07-18 20:19
Hey, that's a duplicate of https://github.com/zed-industries/zed/issues/5371 and https://github.com/zed-industries/zed/issues/5355; tl;dr: floating point precision is at fault here.

**Comment by hylaride** [comment] 2024-07-18 20:21
Ah cool. I'll close this off then.

**Closed** 2024-07-18 20:21 UTC
Labels: defect, triage, admin read
