### ISSUE TITLE
Keyboard shortcuts do not work on non-English keyboard layout

### ISSUE THREAD

**Issue by stz184** [zed-industries/zed#15176] opened 2024-07-25 12:19 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am bilingual user and I have both English (US) and Bulgarian (Cyrillic) keyboard layouts on my Ubuntu 24.04 computer.
When I switch to Bulgarian, I can't use any of the keyboard shortcuts in zed. In other editors (InteliJ, VSCode and gEdit) all shortcuts work no mater of the current keyboard layout used.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland ubuntu 24.04
Memory: 31.2 GiB
Architecture: x86_64

**Comment by SomeoneToIgnore** [comment] 2024-07-25 12:37
Duplicate of https://github.com/zed-industries/zed/issues/10972

This one has a better name after a Linux release, so I've reused it in the original one, thank you.

**Closed by SomeoneToIgnore** 2024-07-25 12:37 UTC
Labels: defect, triage, admin read
