### ISSUE TITLE
( Windows ) zed-nightly successfully compiled, but cannot run

### ISSUE THREAD

**Issue by duytuej1210** [zed-industries/zed#20908] opened 2024-11-20 16:14 UTC
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

zed-nightly has just install by scoop but not working.
The first error is: [ERROR] SHELL environment variable is not assigned so we can't source login environment variables

### Environment

Version: 0.162.0.0
OS: Window 10 64bit 19045
RAM: 8G
Chipset: GTX 1650

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-11-20T23:09:57.0059779+07:00 [INFO] ========== starting zed ==========
2024-11-20T23:09:57.1230774+07:00 [INFO] Use Segoe UI as UI font.
2024-11-20T23:09:57.1245118+07:00 [INFO] Opening main db
2024-11-20T23:09:57.1320313+07:00 [INFO] Opening main db
2024-11-20T23:09:57.1384914+07:00 [INFO] Using git binary path: None
2024-11-20T23:09:57.1394321+07:00 [ERROR] SHELL environment variable is not assigned so we can't source login environment variables

Caused by:
    environment variable not found
2024-11-20T23:09:57.1397007+07:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-11-20T23:09:57.1441247+07:00 [INFO] no tokio runtime found, creating one for Reqwest...
2024-11-20T23:09:57.180446+07:00 [INFO] initializing context server client
2024-11-20T23:09:57.1805912+07:00 [INFO] Registering built-in prompt template: content_prompt
2024-11-20T23:09:57.1807199+07:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-11-20T23:09:57.1811252+07:00 [INFO] Registering built-in prompt template: project_slash_command
2024-11-20T23:09:57.1812206+07:00 [INFO] Registering built-in prompt template: suggest_edits
2024-11-20T23:09:57.1814414+07:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-11-20T23:09:57.1820552+07:00 [INFO] No prompt template overrides directory found at C:\Users\Admin\AppData\Local\Zed\prompt_overrides. Using built-in prompts.
2024-11-20T23:09:57.1823087+07:00 [ERROR] Error("EOF while parsing a value", line: 1, column: 0)
2024-11-20T23:09:57.2045132+07:00 [INFO] Opening main db
2024-11-20T23:09:57.2096645+07:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-11-20T23:09:57.2104683+07:00 [ERROR] Element not found. (0x80070490)
2024-11-20T23:09:57.2107628+07:00 [ERROR] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
2024-11-20T23:09:57.2714654+07:00 [INFO] Enabling Vulkan Portability
2024-11-20T23:09:57.2715603+07:00 [INFO] Enabling color space support


```
</details>

**Comment by kaptcha0** [comment] 2024-11-25 17:49
+1

**Comment by notpeter** [comment] 2024-11-26 17:59
Duplicate of:
- https://github.com/zed-industries/zed/issues/11864

It's almost like you copied the title verbatim 🤔

**Closed by notpeter** 2024-11-26 17:59 UTC
Labels: bug, triage, admin read
