### ISSUE TITLE
Extend AI Support for local LLMs using OpenAI API

### ISSUE THREAD

**Issue by eleaese** [zed-industries/zed#8571] opened 2024-02-28 23:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently Zed only supports OpenAI. Please evaluate the option to enter URL & API Key (optional) to allow Zed to connect to local LLMs using OpenAi API.

**Comment by Moshyfawn** [comment] 2024-02-28 23:50
Duplicate of #4424

**Closed by Moshyfawn** 2024-02-28 23:50 UTC
Labels: enhancement, triage, admin read

**Comment by Moshyfawn** [comment] 2024-02-28 23:53
Make sure to +👍 the initial post if you want to see it happen.
