### ISSUE TITLE
Linux: Unable to share microphone

### ISSUE THREAD

**Issue by reesericci** [zed-industries/zed#14503] opened 2024-07-15 15:59 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I started my first collaboration session & call and was unable to share my microphone and neither was the other participant. It just gave me a red "x" on the microphone with a tooltip that said "Unable to share microphone"

### Environment

Zed: v0.143.7 (Zed)
OS: Linux Wayland fedora 40
Memory: 15.3 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/8fd3d596-211e-41f0-a16c-30ccd18a402f)

### If applicable, attach your Zed.log file to this issue.

Log: https://paste.sr.ht/~reesericci/65ee3f42fc1452abc133f65c170b60d6219c9477

**Comment by reesericci** [comment] 2024-07-15 15:59
cc @polypixeldev

**Comment by joeyjooste** [comment] 2024-07-20 13:39
Having this same issue 

Environment

Zed: v0.143.7 (Zed)
OS: Void Linux X11, DWM, 
Memory: 15.3 GiB
Architecture: x86_64

I installed zed through compiling the flatpak from source.

**Comment by Creepy0964** [comment] 2024-07-23 21:21
having the same issue in 0.144.4 on x86-64 Arch Linux X11 i3-wm with 16 gigs of ram. installed zed through official instruction on zed.dev

**Comment by reesericci** [comment] 2024-07-23 21:52
@Creepy0964: upvote by adding a 👍 to the issue instead of commenting here

**Comment by Ate329** [comment] 2024-07-25 12:15
Same issue with NixOS unstable, zed version 0.141.3.
Environment:
```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.8-zen1, NixOS, 24.11 (Vicuna), 24.11.20240721.68c9ed8`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos, nixpkgs, unstable"`
 - nixpkgs: `/home/ate329/.nix-defexpr/channels/nixpkgs`

```
![image](https://github.com/user-attachments/assets/dff731c3-487d-42a7-b13d-3cabca605854)

**Comment by stvnliu** [comment] 2024-07-26 15:03
This was reproducible on a Windows 11 build of Zed on [this commit](https://github.com/zed-industries/zed/commit/781633fb1ad02cb8ac7f36bf0e9af4a56a49c4e5) with `collab` dependencies installed via `docker compose up -d`, produced the same "Cannot share microphone" message.

**Comment by ahmdsabbir** [comment] 2024-08-08 09:32
Facing the same issue on Ubuntu 24.04. Built following this:

[https://zed.dev/docs/getting-started](https://zed.dev/docs/getting-started)

**Comment by strikerlulu** [comment] 2024-08-08 09:39
<img width="1647" alt="image" src="https://github.com/user-attachments/assets/f12d4ee4-d095-4bef-8f6f-1239c06b3b78">
If you check the source code, you could see that Linux and Windows platforms are not supported yet. :(

**Comment by notpeter** [comment] 2024-08-22 14:54
Duplicate of:
- https://github.com/zed-industries/zed/issues/13714

**Closed by notpeter** 2024-08-22 14:54 UTC
Labels: defect, collaboration, linux, audio
