### ISSUE TITLE
Support diff highlight in markdown

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#20023] opened 2024-10-31 12:29 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Support diff highlight in markdown.

```diff
- println!("Hello word!")
+ println!("Hello world!")
```

It it not supported now

<img width="90" alt="image" src="https://github.com/user-attachments/assets/b5165c78-1fd0-4c5e-bff3-a63b9fe96b16">

**Comment by notpeter** [comment] 2024-10-31 15:00
This is basically a duplicate of:
- https://github.com/zed-industries/zed/issues/19986

Once the highlighting is improved for diffs it will be reflected inside markdown blocks.

**Closed by notpeter** 2024-10-31 15:00 UTC
Labels: enhancement, triage, admin read

**Comment by jaydenseric** [comment] 2025-01-23 06:07
Today, it's not working. Try previewing this markdown:

````markdown
```dif
  abc
- def
+ DEF
```

- Foo
- Bar

  ```dif
    abc
  - def
  + DEF
  ```
- Baz
````

And see the results lack highlighting of diff additions or subtractions:

<img width="250" alt="Image" src="https://github.com/user-attachments/assets/ddbb1ef1-6234-4cb0-90af-780b9dbda651" />

Also, note that it bugs out in real word situations I haven't come up with a minimal reproduction for yet:

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/b38036f3-55eb-4558-b1d7-af1f683f1943" />

See how in the preview, only the first non whitespace chars of changed lines have a strange coloration. If you add extra space indentation in the markdown diff source code, the preview shifts the coloured character column to the right by an equivalent number of spaces:

<img width="688" alt="Image" src="https://github.com/user-attachments/assets/03fa2d83-5d7f-4294-a1e1-6fd8daa7a688" />

**Comment by notpeter** [comment] 2025-01-23 17:51
That just landed in main. It'l be in Preview next wednesday (2025-01-23).

**Comment by jaydenseric** [comment] 2025-01-23 22:00
I just updated to Zed Preview 0.171.1, and it's exactly the same problem.
