### ISSUE TITLE
Restore unsaved buffers when no projectis open

### ISSUE THREAD

**Issue by non-bin** [zed-industries/zed#17051] opened 2024-08-29 02:52 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I often open a new window to quickly take notes, but my computer crashed and I lost my unsaved buffers.
Restoring unsaved files works when I have a folder open in the project panel, but not in a new empty window

Loving Zed so far, thank you <3

**Comment by SomeoneToIgnore** [comment] 2024-08-29 08:50
Will close it as a duplicate of https://github.com/zed-industries/zed/issues/15098

**Closed by SomeoneToIgnore** 2024-08-29 08:50 UTC
Labels: enhancement, triage, admin read

**Comment by non-bin** [comment] 2024-08-29 10:30
Thanks, sorry I didn't see it

**Comment by SomeoneToIgnore** [comment] 2024-08-29 10:34
No worries at all, it's quite hard sometimes for differently named issues.
