### ISSUE TITLE
Control + backtick (Ctrl + `)  producing ESC character instead of executing shortcut.

### ISSUE THREAD

**Issue by jossebv** [zed-industries/zed#13007] opened 2024-06-13 19:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When pressing the combination ctrl + ` a ESC character is placed in the editor instead of applying the keybinding to switch to terminal. This happens with a Spanish ISO distribution, I don't know if it also happens in other distributions. The exact same keybinding works in VSCode, so I deduce that it must be related to Zed.

### Environment

Zed: v0.139.3 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I attach a video with the issue. On it I pressed ctrl+`on an empty file. Then I select the content and copy to the ascii to hex converter, where the ESC character can be seen.

https://github.com/zed-industries/zed/assets/127443992/622e6bb7-4364-4477-92fa-890187f6c167

**Comment by Moshyfawn** [comment] 2024-06-14 14:14
This seems to have been covered in another issue. I'll close this thread in favour of the other one. Be sure to +👍 the other thread.

Duplicate of:
- #5195

**Closed by Moshyfawn** 2024-06-14 14:14 UTC
Labels: defect, workspace, internationalization, keymap / key binding, admin read
