### ISSUE TITLE
Flash nvim behavior for VIM mode

### ISSUE THREAD

**Issue by Benjamin-van-Heerden** [zed-industries/zed#17966] opened 2024-09-17 19:21 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Coming from neovim, the thing I absolutely miss most is flash-nvim (https://github.com/folke/flash.nvim). It is by far the most effective way I have found in navigating, selecting and deleting code. I know this one probably wouldn't be easy, but I am opening a feature and keeping my fingers crossed.

**Comment by ConradIrwin** [comment] 2024-09-27 02:30
Duplicate of #14801.

It's not impossible (we also have requests for easy motion etc.)

**Closed by ConradIrwin** 2024-09-27 02:30 UTC
Labels: enhancement, vim
