### ISSUE TITLE
.env file causes incorrect source command execution

### ISSUE THREAD

**Issue by samurai00** [zed-industries/zed#15949] opened 2024-08-08 02:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

	1. Open a Rust project (other types of projects may also be affected).
	2. Make sure there is a “.env” file in the root directory of the project.
	3. Open the Terminal panel.
	4. You will see `source /path/to/project/.env/bin/activate` running.

### Environment

Zed: v0.147.2 (Zed)
OS: macOS 14.6.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="907" alt="截屏2024-08-08 10 45 43" src="https://github.com/user-attachments/assets/4f5dc284-dc75-4cf1-b9a6-46cd5a40904e">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-08-08T02:33:42.978425Z [INFO] ========== starting zed ==========
2024-08-08T02:33:42.980949Z [INFO] Opening main db
2024-08-08T02:33:42.98478Z [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-08-08T02:33:43.121187Z [ERROR] theme not found: Zedokai Darker (Filter Spectrum)
2024-08-08T02:33:43.124424Z [INFO] extensions updated. loading 11, reloading 0, unloading 0
2024-08-08T02:33:43.159051Z [INFO] Opening main db
2024-08-08T02:33:43.163547Z [WARN] Theme "SynthWave 84 Dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-08-08T02:33:43.164274Z [ERROR] theme not found: Zedokai Darker (Filter Spectrum)
2024-08-08T02:33:43.166399Z [ERROR] theme not found: Zedokai Darker (Filter Spectrum)
2024-08-08T02:33:43.167261Z [INFO] building git repository, `.git` path in the worktree: ".git"
2024-08-08T02:33:43.215573Z [INFO] Opening main db
2024-08-08T02:33:43.247013Z [INFO] set status on client 0: Authenticating
2024-08-08T02:33:43.248908Z [INFO] set status on client 47036: Connecting
2024-08-08T02:33:43.698831Z [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-08-08T02:33:43.742322Z [INFO] set environment variables from shell:/bin/zsh, path:/Users/afon/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/opt/homebrew/opt/curl/bin:/opt/bin:/Users/afon/Developer/bin:/opt/apache-maven-3.8.5/bin:/Users/afon/.composer/vendor/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/Little Snitch.app/Contents/Components:/Users/afon/miniforge3/bin:/Users/afon/miniforge3/condabin:/opt/homebrew/opt/curl/bin:/opt/bin:/Users/afon/Developer/bin:/opt/apache-maven-3.8.5/bin:/Users/afon/.composer/vendor/bin:/Users/afon/.cargo/bin:/opt/homebrew/sbin:/Users/afon/Library/Application Support/JetBrains/Toolbox/scripts:/Users/afon/Developer/flutter/bin:/Users/afon/Library/Android/sdk/cmdline-tools/bin:/Users/afon/Library/Android/sdk/tools:/Users/afon/Library/Android/sdk/tools/bin:/Users/afon/Library/Android/sdk/platform-tools:/Users/afon/.orbstack/bin:/Users/afon/Library/Application Support/JetBrains/Toolbox/scripts:/Users/afon/Developer/flutter/bin:/Users/afon/Library/Android/sdk/cmdline-tools/bin:/Users/afon/Library/Android/sdk/tools:/Users/afon/Library/Android/sdk/tools/bin:/Users/afon/Library/Android/sdk/platform-tools:/Users/afon/.orbstack/bin
2024-08-08T02:33:43.924573Z [INFO] Node runtime install_if_needed
2024-08-08T02:33:44.174355Z [INFO] installing extension html 0.1.2
2024-08-08T02:33:44.622535Z [INFO] add connection to peer
2024-08-08T02:33:44.62296Z [INFO] add_connection;
2024-08-08T02:33:44.62334Z [INFO] waiting for server hello
2024-08-08T02:33:44.668224Z [INFO] got server hello
2024-08-08T02:33:44.668705Z [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 468, id: 341972 })
2024-08-08T02:33:44.669424Z [INFO] set status on client 47036: Connected { peer_id: PeerId { owner_id: 468, id: 341972 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-08-08T02:33:45.289798Z [INFO] starting language server. binary path: "/Users/afon/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/", args: ["/Users/afon/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-08-08T02:33:45.502336Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-08-08T02:33:45.500Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-08-08T02:33:45.500Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-08-08T02:33:45.503518Z [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "a07fc89d-bce6-408f-a5de-eea7fc70f60f",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-08-08T02:33:46.256904Z [WARN] Theme "SynthWave 84 Dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-08-08T02:33:46.260505Z [INFO] rebuilt extension index in 81.166417ms
2024-08-08T02:33:46.260575Z [INFO] extensions updated. loading 0, reloading 0, unloading 1
2024-08-08T02:33:46.295914Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-08-08T02:33:46.293Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-08-08T02:33:46.293Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-08-08T02:33:46.812801Z [WARN] Theme "SynthWave 84 Dark" is using a deprecated style property: scrollbar_thumb.background. Use `scrollbar.thumb.background` instead.
2024-08-08T02:33:46.813594Z [INFO] rebuilt extension index in 63.460916ms
2024-08-08T02:33:46.81367Z [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-08-08T02:34:02.332886Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:34:02.333018Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-08T02:34:02.333085Z [INFO] starting language server "rust-analyzer", path: "/Users/afon/Workspace/rust/zexus", id: 1
2024-08-08T02:34:02.333278Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:34:02.333343Z [INFO] starting language servers for Rust: rust-analyzer
2024-08-08T02:34:02.337653Z [INFO] Opening main db
2024-08-08T02:34:02.339209Z [INFO] fetching latest version of language server "rust-analyzer"
2024-08-08T02:34:03.179975Z [INFO] downloading language server "rust-analyzer"
2024-08-08T02:34:03.186551Z [INFO] starting language server. binary path: "/Users/afon/Library/Application Support/Zed/languages/rust-analyzer/rust-analyzer-2024-08-05", working directory: "/Users/afon/Workspace/rust/zexus", args: []
2024-08-08T02:34:05.078485Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:34:05.078594Z [INFO] starting language servers for TOML: taplo
2024-08-08T02:34:05.078662Z [INFO] starting language server "taplo", path: "/Users/afon/Workspace/rust/zexus", id: 2
2024-08-08T02:34:05.078838Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:34:05.078906Z [INFO] starting language servers for TOML: taplo
2024-08-08T02:34:05.577807Z [INFO] starting language server. binary path: "/Users/afon/Library/Application Support/Zed/extensions/work/toml/taplo-0.9.3/taplo", working directory: "/Users/afon/Workspace/rust/zexus", args: ["lsp", "stdio"]
2024-08-08T02:34:42.77772Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:34:42.778367Z [INFO] starting language servers for TOML: taplo
2024-08-08T02:34:42.799342Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/gateway.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:34:59.752071Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:02.513526Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:02.586385Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:04.547248Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:05.547399Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:14.418753Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:24.656275Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:24.759809Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:24.851794Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:25.30464Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:25.389622Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:25.528382Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:25.67105Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:25.734979Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:25.969836Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:31.643907Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:38.523073Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:38.78835Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:39.19115Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:39.912624Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:40.025952Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:42.784408Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:35:42.976557Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:37:35.410174Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:03.364065Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:03.470926Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:34.516212Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:34.691805Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:35.322462Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:35.456741Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:35.745475Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:35.866538Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:36.068473Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/dev-data/gateway-dev.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:38:45.345972Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:38:45.346169Z [INFO] starting language servers for TOML: taplo
2024-08-08T02:40:39.326572Z [INFO] open paths ["/Users/afon/.config/zed/settings.json"]
2024-08-08T02:40:39.359746Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:40:39.359879Z [INFO] starting language servers for JSONC: json-language-server
2024-08-08T02:40:39.359963Z [INFO] starting language server "json-language-server", path: "/Users/afon/.config/zed/settings.json", id: 3
2024-08-08T02:40:39.360202Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:40:39.360288Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:40:39.360367Z [INFO] starting language servers for TOML: taplo
2024-08-08T02:40:39.360447Z [INFO] starting language servers for JSONC: json-language-server
2024-08-08T02:40:39.367189Z [INFO] fetching latest version of language server "json-language-server"
2024-08-08T02:40:39.367294Z [INFO] Node runtime install_if_needed
2024-08-08T02:40:41.408572Z [INFO] downloading language server "json-language-server"
2024-08-08T02:40:41.417432Z [INFO] Node runtime install_if_needed
2024-08-08T02:40:41.515814Z [INFO] starting language server. binary path: "/Users/afon/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/Users/afon/.config/zed", args: ["/Users/afon/Library/Application Support/Zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-08-08T02:40:44.53135Z [INFO] Language server with id 2 sent unhandled notification taplo/didChangeSchemaAssociation:
{
  "documentUri": "file:///Users/afon/Workspace/rust/zexus/gateway.toml",
  "schemaUri": null,
  "meta": null
}
2024-08-08T02:45:02.694386Z [ERROR] no worktree found for diagnostics path "/Users/afon/.config/zed/settings.json"
2024-08-08T02:45:08.843029Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:45:08.843169Z [INFO] starting language servers for Shell Script: 
2024-08-08T02:45:08.843398Z [INFO] Initializing default prettier with plugins {}
2024-08-08T02:45:08.843486Z [INFO] starting language servers for Shell Script: 

</pre></details>

**Comment by notpeter** [comment] 2024-08-09 19:57
Duplicate of:

- https://github.com/zed-industries/zed/issues/15570

**Closed by notpeter** 2024-08-09 19:57 UTC
Labels: defect, triage, admin read
