### ISSUE TITLE
Discord Presence Extension to Show Status via RPC

### ISSUE THREAD

**Issue by devarshishimpi** [zed-industries/zed#12734] opened 2024-06-06 13:49 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

VSCode has an extension that displays the current status of our open file and workspace on Discord using Rich Presence (RPC). This feature can significantly enhance collaboration and social interaction among developers. Implementing a similar extension for Zed would be a great addition.

![discord-vscode-status-rpc](https://github.com/zed-industries/zed/assets/43378923/fdcbb859-f2ba-4b12-a54e-9a23ddd61879)

### Benefits for Zed Users:

- Improved team collaboration and communication.
- Enhanced community engagement and social interaction.
- Increased productivity through better activity tracking.
- Professional networking and project promotion.

**Comment by Moshyfawn** [comment] 2024-06-07 16:14
There's already a feature request for this, so I'm going to close this issue in favour of the other one to keep the conversation in one place. Be sure to +👍 the other thread.

Duplicate of:
- #499

**Closed by Moshyfawn** 2024-06-07 16:14 UTC
Labels: enhancement, triage, admin read

**Comment by devarshishimpi** [comment] 2024-06-07 16:56
Sure, thank you!

**Comment by Moshyfawn** [comment] 2024-06-07 18:59
That extensions repository I linked is a good place to search for / introduce feature requests related to extensibility.
