### ISSUE TITLE
Zed does not keep up with typing

### ISSUE THREAD

**Issue by jansedlon** [zed-industries/zed#7823] opened 2024-02-15 12:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

You can see in the video that when i type, the autocomplete hardly keeps up. The individual characters are highlighted much slower

### Environment

Zed: v0.123.1 (Zed Preview)
OS: macOS 14.3.1
Memory: 48 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/13948180/100dc1eb-045d-498b-99f6-128d6a31003e

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-16 04:57
Hey @jansedlon,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5166

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-16 04:57 UTC
Labels: defect, performance, typescript, javascript, language, language server

**Comment by jansedlon** [comment] 2024-02-16 05:59
It's probably duplicate, sorry, hard to find similar issues 🙏
