### ISSUE TITLE
Zed cannot open Conda Miniforge installation script

### ISSUE THREAD

**Issue by xpe** [zed-industries/zed#7676] opened 2024-02-11 22:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I found a bug where Zed won't open the following Miniforge installer file:

`https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Darwin-arm64.sh`.

(I didn't hyperlink it because it is 56 MB.)

```console
% ls -alh 
total 115224
drwxr-xr-x   3 hippo_campus  staff    96B Feb 11 17:25 .
drwxr-x---+ 50 hippo_campus  staff   1.6K Feb 11 17:25 ..
-rw-r--r--   1 hippo_campus  staff    56M Feb 11 17:25 Miniforge3-Darwin-arm64.sh
```

Trying to open with zed (with `zed Miniforge3-Darwin-arm64.sh`) fails with this dialog box:

```
Failed to open file

stream did not contain valid UTF-8.
Please try again.
```

<img width="616" alt="image" src="https://github.com/zed-industries/zed/assets/4576329/80b47133-4eb4-4674-87f0-d1e5fa3d0267">

(Obviously, trying again didn't help. :))

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2024-02-11T17:28:51-05:00 [INFO] open paths ["/Users/hippo_campus/temp_miniforge_conda/Miniforge3-Darwin-arm64.sh"]
2024-02-11T17:28:53-05:00 [ERROR] stream did not contain valid UTF-8
```

**Comment by JosephTLyons** [comment] 2024-02-13 19:30
Hey @xpe,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5348

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-13 19:30 UTC
Labels: defect, triage, admin read
