### ISSUE TITLE
Rendering issues on macOS

### ISSUE THREAD

**Issue by pronebird** [zed-industries/zed#8765] opened 2024-03-03 14:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On macOS Big Sur 11.7.10 the bottom part of text is often invisible until I scroll down. As I keep scrolling the text reappears, sometimes character by character, sometimes in chunks. If I scroll down to somewhere in the middle and then go back up, sometimes the text in the middle disappears but the text at the bottom remains visible.

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 11.7.10
Memory: 16 GiB
Architecture: x86_64

Intel mac.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="965" alt="Screen Shot 2024-03-03 at 15 42 24" src="https://github.com/zed-industries/zed/assets/704044/0f689ae1-8923-4647-8d04-106f13e5fb31">

<img width="1023" alt="Screen Shot 2024-03-03 at 15 51 29" src="https://github.com/zed-industries/zed/assets/704044/d42daefa-64f0-4515-ad7b-ee7e79455e53">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-03-03 16:41
Duplicate of #5062

**Comment by Moshyfawn** [comment] 2024-03-03 16:42
Be sure to +👍 the other issue and add any missing information.

**Closed by Moshyfawn** 2024-03-03 16:41 UTC
Labels: defect, triage, admin read
