### ISSUE TITLE
vim: keyboard (vim) binding to scroll the LSP hover

### ISSUE THREAD

**Issue by lucascherzer** [zed-industries/zed#17295] opened 2024-09-03 10:04 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In my vim config, pressing `K` twice while hovering over a code element focuses the documentation pane that appears when pressing `K`the first time in vim mode. From then on, vim motions do not refer to the source code file anymore, but instead they are applied to the documentation pane.
Of course, the buffer is not editable and this can be exited with `:q` or perhaps using `Esc`

### If applicable, add mockups / screenshots to help present your vision of the feature

https://asciinema.org/a/iUyR5IFa292GYjQpSlZSbnIqR

**Comment by ConradIrwin** [comment] 2024-09-05 15:14
Duplicate of #7284

**Closed by ConradIrwin** 2024-09-05 15:14 UTC
Labels: enhancement, vim, popovers

**Comment by xdBronch** [comment] 2024-12-24 21:34
fwiw you can scroll the hover with `<C-d>` and `<C-u>` when its visible, a way to focus the hover like 7284 isnt necessary
