### ISSUE TITLE
Project Diagnostics not disappearing from editor window

### ISSUE THREAD

**Issue by jigyansunanda** [zed-industries/zed#8984] opened 2024-03-07 04:36 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am just testing some `Python` code. When I get some error, going to the red squiggly line word, it prompts me to see diagnostics. When I click it, it shows me the diagnostic and the red text coloured diagnostic stays in the editor window. This is as expected. However when I remove the code completely or just remove the error, and save the red font diagnostic stays.

_(Please find the screenshots of issue reproduced attached below)_

Also I can reproduce the same thing in `C++` as well.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="565" alt="Screenshot 2024-03-07 at 9 25 06 AM" src="https://github.com/zed-industries/zed/assets/62047889/9a63e1ea-5e07-48a0-a036-ccbe812babe9">
[As expected]

<img width="462" alt="Screenshot 2024-03-07 at 9 25 31 AM" src="https://github.com/zed-industries/zed/assets/62047889/8604034c-ed0e-4029-8871-83d074f8cf70">
[Still seeing the diagnostics]

<img width="522" alt="Screenshot 2024-03-07 at 9 47 35 AM" src="https://github.com/zed-industries/zed/assets/62047889/4099a447-b16a-42df-84a7-db43b6896ab0">
[Nothing in the editor]

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

{
  "unregisterations": [
    {
      "id": "47a5af12-e9f4-40ae-a5d7-4ce1706136d7",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:03+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "68ce7647-6b5f-409d-886e-bc95e1ac4952",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:04+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "612c62df-11c4-4ac9-b187-81ef6f521976",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:07+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "6395c61b-2927-45ea-852d-822c1abaecac",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:09+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "a0e623e8-e978-4b69-b4f9-0b1609cdd666",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:11+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "1fa78e93-4e46-4810-bacb-77e5265e6e9b",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:12+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "d785cec6-027f-43ca-902e-2461a6688a4f",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:13+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "716b9056-b6ed-4c3a-bffd-97c063b3e4ac",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:14+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "5938e0fd-0681-4a3f-8680-ea13035cc8ec",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:15+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "2c39ba13-bf6d-4064-aa63-66f9e0c49b16",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:16+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "e4fe0766-c0c1-4a66-8220-1b62d634d949",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:16+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "619ed54f-c404-416d-9d72-2759b6a6da65",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:19+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "28265055-d960-4f74-a520-a228e3622f58",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:20+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "ab6f14f5-9542-4340-bd83-63dad478a171",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:22+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "12813075-9a7e-4dcc-8055-8f8642c2cce0",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:22+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "6e29d2c7-ec66-406a-a0f6-655c6fc09fd8",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:26+05:30 [INFO] open paths ["/Users/jigyansunanda/.config/zed/settings.json"]
2024-03-06T20:16:26+05:30 [INFO] starting language server "json-language-server", path: "/Users/jigyansunanda/.config/zed/settings.json", id: 6
2024-03-06T20:16:26+05:30 [INFO] starting language server. binary path: "/Users/jigyansunanda/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/jigyansunanda/.config/zed", args: ["/Users/jigyansunanda/Library/Application Support/Zed/languages/json-language-server/node_modules/vscode-json-languageserver/bin/vscode-json-languageserver", "--stdio"]
2024-03-06T20:16:26+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "65e67f4a-2499-4e48-a083-76056d025d79",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:16:50+05:30 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-03-06T20:18:12+05:30 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-03-06T20:18:13+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "5f924922-074d-45f0-8abf-aca86363a2b8",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:18:22+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "f19b6e8b-36b3-42a4-8abb-6be32a2f2aa9",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:31:39+05:30 [ERROR] unexpected item event after pane was dropped
2024-03-06T20:31:40+05:30 [ERROR] crates/lsp/src/lsp.rs:684: oneshot canceled
2024-03-06T20:31:40+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "c6287596-a8f1-495c-91a7-e62efc4d996e",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:48:47+05:30 [ERROR] crates/lsp/src/lsp.rs:684: oneshot canceled
2024-03-06T20:48:49+05:30 [INFO] ========== starting zed ==========
2024-03-06T20:48:49+05:30 [INFO] Opening main db
2024-03-06T20:48:49+05:30 [INFO] set environment variables from shell:/bin/zsh, path:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin/
2024-03-06T20:48:49+05:30 [ERROR] crates/theme/src/settings.rs:355: theme not found: Zedokai (Filter Machine)
2024-03-06T20:48:49+05:30 [ERROR] crates/zed/src/zed.rs:555: EOF while parsing a value at line 1 column 0
2024-03-06T20:48:49+05:30 [INFO] Opening main db
2024-03-06T20:48:49+05:30 [INFO] Opening main db
2024-03-06T20:48:49+05:30 [INFO] Opening main db
2024-03-06T20:48:49+05:30 [INFO] starting language server "pyright", path: "/Users/jigyansunanda/Downloads/Self Study/p_prac/", id: 1
2024-03-06T20:48:49+05:30 [INFO] querying GitHub for latest version of language server "pyright"
2024-03-06T20:48:49+05:30 [INFO] Node runtime install_if_needed
2024-03-06T20:48:49+05:30 [INFO] Node runtime install_if_needed
2024-03-06T20:48:50+05:30 [INFO] starting language server. binary path: "/Users/jigyansunanda/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/", args: ["/Users/jigyansunanda/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-03-06T20:48:50+05:30 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-06T15:18:50.304Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-03-06T15:18:50.304Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-03-06T20:48:50+05:30 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "10c037a3-a021-47f6-a6c5-e695834ac154",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-03-06T20:48:50+05:30 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-06T15:18:50.312Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-03-06T15:18:50.312Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-03-06T20:48:51+05:30 [INFO] checking if Zed already installed or fetching version for language server "pyright"
2024-03-06T20:48:51+05:30 [INFO] Node runtime install_if_needed
2024-03-06T20:48:51+05:30 [INFO] starting language server. binary path: "/Users/jigyansunanda/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/jigyansunanda/Downloads/Self Study/p_prac/", args: ["/Users/jigyansunanda/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-03-06T20:48:51+05:30 [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Pyright language server 1.1.352 starting"
}
2024-03-06T20:48:51+05:30 [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/jigyansunanda/Library/Application%20Support/Zed/languages/pyright/node_modules/pyright/dist"
}
2024-03-06T20:48:51+05:30 [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Starting service instance \"\""
}
2024-03-06T20:48:51+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "77129c5c-6bbc-436b-8c63-61a5103f7439",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-06T20:49:54+05:30 [ERROR] crates/lsp/src/lsp.rs:684: oneshot canceled
2024-03-07T08:53:33+05:30 [INFO] ========== starting zed ==========
2024-03-07T08:53:33+05:30 [INFO] Opening main db
2024-03-07T08:53:33+05:30 [ERROR] crates/theme/src/settings.rs:355: theme not found: Zedokai (Filter Machine)
2024-03-07T08:53:33+05:30 [ERROR] crates/zed/src/zed.rs:555: EOF while parsing a value at line 1 column 0
2024-03-07T08:53:33+05:30 [INFO] Opening main db
2024-03-07T08:53:33+05:30 [INFO] Opening main db
2024-03-07T08:53:33+05:30 [INFO] Opening main db
2024-03-07T08:53:33+05:30 [INFO] starting language server "pyright", path: "/Users/jigyansunanda/Downloads/Self Study/p_prac/", id: 1
2024-03-07T08:53:33+05:30 [INFO] Node runtime install_if_needed
2024-03-07T08:53:34+05:30 [INFO] starting language server. binary path: "/Users/jigyansunanda/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/", args: ["/Users/jigyansunanda/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-03-07T08:53:35+05:30 [INFO] set environment variables from shell:/bin/zsh, path:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin/
2024-03-07T08:53:35+05:30 [INFO] querying GitHub for latest version of language server "pyright"
2024-03-07T08:53:35+05:30 [INFO] Node runtime install_if_needed
2024-03-07T08:53:35+05:30 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-07T03:23:35.121Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-03-07T03:23:35.121Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-03-07T08:53:35+05:30 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "53fe6d8e-4663-47f2-a565-85179ab0b0e8",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-03-07T08:53:35+05:30 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-07T03:23:35.129Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-03-07T03:23:35.129Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-03-07T08:53:36+05:30 [INFO] checking if Zed already installed or fetching version for language server "pyright"
2024-03-07T08:53:36+05:30 [INFO] Node runtime install_if_needed
2024-03-07T08:53:36+05:30 [INFO] starting language server. binary path: "/Users/jigyansunanda/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/jigyansunanda/Downloads/Self Study/p_prac/", args: ["/Users/jigyansunanda/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-03-07T08:53:36+05:30 [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Pyright language server 1.1.352 starting"
}
2024-03-07T08:53:36+05:30 [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/jigyansunanda/Library/Application%20Support/Zed/languages/pyright/node_modules/pyright/dist"
}
2024-03-07T08:53:36+05:30 [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Starting service instance \"\""
}
2024-03-07T08:53:36+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "a37223bf-8edd-406c-82f6-d2ddf88477f0",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-07T08:54:07+05:30 [INFO] downloaded update. path:"/var/folders/k4/pyhqtwgj4bg0f_g3ph2x3p480000gn/T/zed-auto-updatei8oMMS/Zed.dmg"
2024-03-07T08:57:48+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "93ac23df-b26d-47ef-a8e6-a604de5a9a3c",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-07T08:57:50+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "7623cad3-b3b2-4bac-a3e7-95436b0d691e",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-03-07T08:57:51+05:30 [INFO] Language server with id 1 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "78efbd29-8804-464e-a355-7fb98c1b08a2",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}

**Comment by jigyansunanda** [comment] 2024-03-07 05:06
> I'd say this is the same core issue as in #8051

Thank you for prompt acknowledgement and reply.

I tried searching with keyword "diagnostics" and did not find any results hence put this forward.
I am not sure whether I should leave it open or not as it is a duplicate issue. Please let me know.

Love Zed.

**Comment by JosephTLyons** [comment] 2024-03-07 05:43
Actually, I think this might be a dupe of:

- https://github.com/zed-industries/zed/issues/5175

I'm going close this one out in favor of that one.

**Closed by JosephTLyons** 2024-03-07 05:43 UTC
Labels: defect, discoverability, editor, diagnostics
