### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by eudziro** [zed-industries/zed#22449] opened 2024-12-27 15:46 UTC
### Check for existing issues

- [X] Completed

### I've just installed proprietary driver for my nvidia GT740M, nvidia-tesla-470-driver, and before that zed shows very bad performance due to lack of vulkan tools on my machine, but when I installed proprietary driver zed shows that:
![Screenshot from 2024-12-27 17-41-39](https://github.com/user-attachments/assets/c6c98ecb-8853-46d5-a1fe-50a31e8bb4f8)
![Screenshot from 2024-12-27 17-41-18](https://github.com/user-attachments/assets/216c0e59-d4ce-4307-8f6a-d9ef94436ca5)
![Screenshot from 2024-12-27 17-43-20](https://github.com/user-attachments/assets/41c0e198-25f2-467d-a240-93c04c11044a)

### It's just hangs like that, and thats all;
****

### Zed Version and System Specs

NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.256.02;
Kernel: 6.1.0-28-amd64
OS: Debian GNU/Linux 12 (bookworm) x86_64
WM: Mutter
zed version: 0.166.1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>
[Zed.log](https://github.com/user-attachments/files/18261659/Zed.log)

**Comment by SomeoneToIgnore** [comment] 2024-12-27 16:27
> Check for existing issues

https://github.com/zed-industries/zed/issues?q=is%3Aissue+is%3Aopen+Rejected+for+device+extension+%22VK_KHR_dynamic_rendering%22+not+supported.+Please+update+the+driver%21+

Duplicate of https://github.com/zed-industries/zed/issues/16428 , also https://github.com/zed-industries/zed/issues/13441 has some mentions of this error too.

Presumably, a driver update is needed, but maybe more answers from those issues will help, https://github.com/zed-industries/zed/issues/16428#issuecomment-2563387581 in particular.

**Closed by SomeoneToIgnore** 2024-12-27 16:27 UTC
Labels: bug, triage, admin read
