### ISSUE TITLE
cannot find file when named parent folder

### ISSUE THREAD

**Issue by sanbox-irl** [zed-industries/zed#8982] opened 2024-03-07 02:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I suspect this is a duplicate, but it's tough to find.

![Screenshot 2024-03-06 at 9 50 40 PM](https://github.com/zed-industries/zed/assets/31973761/5bc55aca-aa4f-4cc2-a67e-e0f0982a4f73)

doing that finds the file no problem.

but inverting it...

![Screenshot 2024-03-06 at 9 54 57 PM](https://github.com/zed-industries/zed/assets/31973761/46ff8039-0dab-4b25-b957-3edb0dd94ca3)

fails to find it.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.1.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-03-07 03:48
There's #4315, which I think we can close this issue in favour of, and #7586 R&D item, which was a preposition to swap the search engine.

**Comment by Moshyfawn** [comment] 2024-03-07 03:50
I'll close this one if you don't mind. Be sure to +👍 the other topic and maybe the research topic to show your interest and to add any additional information that might be missing.

Duplicate of:
- #4315

**Closed by Moshyfawn** 2024-03-07 03:50 UTC
Labels: defect, file finder, admin read
