### ISSUE TITLE
File explorer collapses itself when files changed in terminal

### ISSUE THREAD

**Issue by canadaduane** [zed-industries/zed#14922] opened 2024-07-21 16:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When modifying files outside of zed--for example, via `pnpm install`--the file explorer in the project panel collapses to the top-most folder. I can expand the folder again manually, and it seems to retain open/closed states of sub-folders. It would be nice if it did not auto-collapse.

### Environment

Zed: v0.144.4 (Zed)
OS: macOS 14.3.0
Memory: 48 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/49c0c00a-69e2-49fc-a006-0f4ad1958343

**Comment by JosephTLyons** [comment] 2024-07-23 19:54
Hey @canadaduane,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/13762

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-23 19:54 UTC
Labels: defect, terminal, project panel
