### ISSUE TITLE
right to left text is backwards on windows

### ISSUE THREAD

**Issue by edenhanan** [zed-industries/zed#14507] opened 2024-07-15 17:13 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

right to left text in the program is backwards  in windows 

built zed from repo
added reference  picture from pycharm on the left and zed on the right

### Environment

Zed: v0.144.0 (Zed Dev)
OS: Windows 10.0.22631
Memory: 15.4 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/ec5d584a-9f28-4013-b1e8-403e9e1deaf7)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-17 14:03
Duplicate of:

- https://github.com/zed-industries/zed/issues/7465

**Closed by notpeter** 2024-10-17 14:03 UTC
Labels: defect, windows, internationalization
