### ISSUE TITLE
Huge mouse pointer in Linux Wayland

### ISSUE THREAD

**Issue by HendrikJan** [zed-industries/zed#18802] opened 2024-10-07 10:13 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The mouse pointer has an unusual huge size.

I could not make a screenshot from within Linux that includes the huge pointer, so I made a photo of my screen:
![image](https://github.com/user-attachments/assets/b5957c7b-3390-4124-8e07-950ac3ebec33)

Also the pointing-hand pointer when overing over tabs is huge:
![image](https://github.com/user-attachments/assets/fecfe87b-6462-43ec-83ec-482b36174dcc)

I tried to increase/decrease the font-size (using CTRL-+ and CTRL--) but this doesn't change the pointer size.

### Environment

Hardware model: Dell Inc. Precision 7680
Memory: 32,0 GiB
Processor: 13th Gen Intel® Core™ i7-13850HX × 28
Graphics: Mesa Intel® Graphics (RPL-S) / Mesa Intel® Graphics (RPL-S)
OS Name: Ubuntu 22.04.5 LTS
OS Type: 64-bit
Gnome version: 42.9
Windowing system: Wayland

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is how it looks in VS-Code (and how it should be):
![image](https://github.com/user-attachments/assets/3de53a36-830b-43e8-adc5-f59e88a08762)

**Comment by notpeter** [comment] 2024-10-07 13:23
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/17771
- https://github.com/zed-industries/zed/issues/13258
- https://github.com/zed-industries/zed/issues/15788

There was a partial fix in #17496 but it was reverted
- https://github.com/zed-industries/zed/pull/17496
- https://github.com/zed-industries/zed/pull/18642

**Closed by notpeter** 2024-10-07 13:23 UTC
Labels: defect, triage, admin read

**Comment by HendrikJan** [comment] 2024-10-08 13:45
Oh, I didn't search well enough in existing issues, sorry.
Thanks for finding the other issues that are related.

**Comment by kdipto1** [comment] 2024-10-20 09:01
I still have this issue.
