### ISSUE TITLE
vim mode: repeated "<" command behaves incorrectly 

### ISSUE THREAD

**Issue by distractedm1nd** [zed-industries/zed#12774] opened 2024-06-07 14:05 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using indentation commands <, >, they work as expected when used in isolation.

When prefixing the command with a number, for example, `4>`, it ignores the prefix and only indents once.

When trying to repeat the command using ".", the lines get jumbled with different indentations. This is because after repeating the command, the cursor does not always return to the initial position. It often jumps to a random line within the previous selection.

### Environment

Zed: v0.137.3 (Zed)
OS: macOS 14.1.0
Memory: 32 GiB
Architecture: aarch64

**Comment by janko** [comment] 2024-06-07 14:56
Seems like a duplicate of https://github.com/zed-industries/zed/issues/12351. It will most likely be fixed by https://github.com/zed-industries/zed/pull/12582.

**Comment by Moshyfawn** [comment] 2024-06-08 16:26
I'm going to optimistically close this issue, as it does indeed look like a dupe that might've been fixed by the PR mentioned above. Be sure to follow up if the issue persists and we can reopen it.

Duplicate of:
- #12351

**Closed by Moshyfawn** 2024-06-08 16:26 UTC
Labels: defect, triage, admin read

**Comment by zeux** [comment] 2024-06-17 22:24
This doesn't appear to be a duplicate and should probably be reopened. On latest master, I can confirm that using `.` to repeat indent/deindent does work, but using a number before `<`/`>` still doesn't actually repeat the action specified number of times.
