### ISSUE TITLE
Tooltip item height follows tallest entry

### ISSUE THREAD

**Issue by michewl** [zed-industries/zed#22459] opened 2024-12-28 11:13 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I noticed this in relation to snippets where multi-line descriptions can be added. All items in the suggestion tooltip inherit the tall size of one snippet.

To reproduce it, add a snippet with line breaks in the description and write the trigger text to show the popup.

```json
{
  "tooltiptext": {
    "prefix": "tt",
    "body": ["todo!()"],
    "description": "This demonstrates\n\nthe issue if a snippet has a multi-line description\n\nsince all other entries also seem to\n\ninherit the 'height' from it."
  }
}
```

### Zed Version and System Specs

Zed: v0.166.1 (Zed)
OS: Linux X11 pop 22.04
Memory: 62 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7900 XTX (RADV NAVI31) || radv || Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![image](https://github.com/user-attachments/assets/e1d3d2b6-83ba-4dac-b12d-d724d4093aa0)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-12-28 13:04
Duplicate of https://github.com/zed-industries/zed/issues/21403

**Closed by SomeoneToIgnore** 2024-12-28 13:04 UTC
Labels: bug, triage, admin read
