### ISSUE TITLE
Autocompletion for generic words.

### ISSUE THREAD

**Issue by Siebjee** [zed-industries/zed#12971] opened 2024-06-13 09:01 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I used atom in the past (till it got killed). And switched back to vim.
And with both editors I had the ability to auto complete generic words instead of only the things from an language server.

VIM (9.1.250 (+bunch of addons)):
<img width="370" alt="Screenshot 2024-06-13 at 10 51 04" src="https://github.com/zed-industries/zed/assets/7149591/61762351-cfa2-477d-bb75-b579b0550552">

Zed (0.139.3):
<img width="467" alt="Screenshot 2024-06-13 at 10 51 56" src="https://github.com/zed-industries/zed/assets/7149591/abe82b60-e0e7-4ec9-ae5c-7319781d9652">

The goal of this is to lessen potential "retyping" typing errors.

I've searched the docs, tried different settings, searched here in the issues. But can't find anything that remotely resembles what VIM does for me.

**Comment by notpeter** [comment] 2024-06-13 16:50
That's an interesting use-case, I'm not sure I've seen an editor that does this. What extensions are you using to this now?

At a bare minimum to implement something like this we'd need to support language specific dictionaries (and likely custom dictionaries) for completion which might be available if we had some form of spell check.  See:

- https://github.com/zed-industries/zed/issues/5305

**Comment by Siebjee** [comment] 2024-06-13 16:55
That's a good question. It is part of this stack: https://github.com/Siebjee/vimrc.

But! It's also VIM native (ctrl+n). I think either "youcompleteme" or "coc" is just presenting it in a nice way.

It's not a language server behind it. But rather a language server constructed of all words within the buffer or even all open buffers in VIM.

**Comment by someone13574** [comment] 2024-06-13 23:57
VSCode does this by default based on words in the currently open file.

**Comment by d1y** [comment] 2024-06-14 00:02
Duplicate of https://github.com/zed-industries/zed/issues/4957

**Closed** 2024-06-14 01:09 UTC
Labels: enhancement, editor, autocompletions, duplicate

**Comment by Siebjee** [comment] 2024-06-14 05:38
Sorry about that! I didn't spot that issue. Thanks for referencing it.
