### ISSUE TITLE
Zed does not open very large text files

### ISSUE THREAD

**Issue by viimajesty** [zed-industries/zed#19121] opened 2024-10-12 13:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When trying to open a large .txt file (17000+ lines, 2.1mb), Zed does nothing.
Drag & Drop and Open menu does not do anything, the file does not open. 
Right clicking the file > Open with Zed, gets the tab bar showing the filename but the window stays blank.
<img width="1791" alt="Screenshot 2024-10-12 at 6 47 12 PM" src="https://github.com/user-attachments/assets/e385515e-3f26-4b7a-b3e7-dcff77e1ee7c">

Thanks

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 14.7.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-12T18:38:43.273035+05:30 [INFO] open paths ["/Users/user/Downloads/garfield.txt"]
2024-10-12T18:38:54.091406+05:30 [INFO] open paths ["/Users/user/Downloads/garfield.txt"]
2024-10-12T18:39:01.690352+05:30 [INFO] open paths ["/Users/user/Downloads/garfield.txt"]
</pre></details>

**Comment by JosephTLyons** [comment] 2024-10-12 19:55
Hey @viimajesty, I'm not able to reproduce this. Are you able to provide a file that surfaces the issue?

**Comment by viimajesty** [comment] 2024-10-13 04:21
This is the file http://john.ccac.rwth-aachen.de:8000/ftp/dilbert/garfield.txt

**Comment by brandondrew** [comment] 2024-10-17 18:08
I don't have a solution (sorry!) but a workaround for such situations is to use BBEdit.  I don't find it to be the most pleasant editor to use (based on my UX preferences—YMMV) but it is unbelievably resilient and performant in cases where most editors fall down.

I expect Zed will reach that level of stability and performance some day, since they're building a strong foundation.  But in the mean time it's good to have a reliable backup.

**Comment by osiewicz** [comment] 2024-11-04 11:30
This is a duplicate of https://github.com/zed-industries/zed/issues/16965

**Closed by osiewicz** 2024-11-04 11:30 UTC
Labels: defect, needs info / awaiting response, editor
