### ISSUE TITLE
Can't disable ligatures

### ISSUE THREAD

**Issue by DGolubets** [zed-industries/zed#14178] opened 2024-07-11 09:53 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've added 
```
{
  "buffer_font_features": {
    "calt": false
  }
}
```
to my settings.

But ligatures are still there.

### Environment

Zed: v0.143.6 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 31.1 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by sonathad** [comment] 2024-07-11 10:12
I can confirm that it doesn't work. 

However, in my situation I was using "JetBrainsMono Nerd Font Mono" instead of the no ligatures variant "JetBrainsMonoNL Nerd Font Mono".

**Comment by vgnh** [comment] 2024-07-12 02:42
+1 on this..

Unable to disable ligatures with `"calt": false`.

### Environment
Zed: v0.143.6
OS: Linux Wayland Fedora 40
Architecture: x86_64
Font used: JetBrains Mono

**Comment by Barugon** [comment] 2024-08-06 19:00
Just came here to report this bug but it's already here.

### Environment

Zed: v0.147.2 (Zed Preview)
OS: Linux Wayland fedora 40
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 7800 XT (RADV NAVI32) || radv || Mesa 24.1.5
Font: Zed Plex Mono

**Comment by Barugon** [comment] 2024-08-07 00:01
I saw issue #15752 which states that `buffer_font_features` simply doesn't work on Linux.  https://mutsuntsai.github.io/fontfreeze was offered as a work-around which did the trick for me.

**Comment by notpeter** [comment] 2024-08-12 14:53
I'm closing as a duplicate of 
- #15752 

Thanks for reporting. Please 👍 and subscribe that issue to track it's progress.

**Closed by notpeter** 2024-08-12 14:53 UTC
Labels: defect, setting, font
