### ISSUE TITLE
Zed build for windows but...

### ISSUE THREAD

**Issue by ATWp** [zed-industries/zed#10206] opened 2024-04-05 15:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

cargo run
start Zed.exe in `/zed-main/target/debug/zed.exe`

### Environment

Zed: v0.129.2 (Zed)
OS: Windows 10

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
Zed logs in `~\AppData\Local\Zed\logs` , but no logs in the folder...

[console_log.txt](https://github.com/zed-industries/zed/files/14886936/console_log.txt)

**Comment by Moshyfawn** [comment] 2024-04-05 15:40
The error seems to indicate that #9316 already contains the report for this panic. I'm going to close this issue in favour of the other one, but we can reopen it if it turns out to be a separate issue. Be sure to +👍 the other issue.

Duplicate of
- #9316

**Closed by Moshyfawn** 2024-04-05 15:40 UTC
Labels: defect, triage, panic / crash, admin read

**Comment by ATWp** [comment] 2024-04-05 15:56
> The error seems to indicate that #9316 already contains the report for this panic. I'm going to close this issue in favour of the other one, but we can reopen it if it turns out to be a separate issue. Be sure to +👍 the other issue.
> 
> Duplicate of
> 
> * [[Windows] Failing to read settings file #9316](https://github.com/zed-industries/zed/issues/9316)

Issue #9316 really problem with settings key bindings, but I corrected this error to the one indicated.

My error occurs because when accessing some database, the application does not receive any of the following values:
   `display, window_state,  window_x,  window_y,  window_width,  window_height, fullscreen`
The options below apply to the workspace, not the keyboard settings.
If you understand the application code, write where to find these loaded parameters and set them to the default value?
If you know where to disable the request in the code, please write the file and line of code?
Perhaps you know where the path to the database with these maybe setting parameters is in order to connect to it and fill them in?
