### ISSUE TITLE
hello_world in gpui's example doesn't work

### ISSUE THREAD

**Issue by JusufGaa** [zed-industries/zed#9985] opened 2024-03-30 08:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It compiles fine, but there is no window after running it.

### Environment

cargo run --example hello_world
macOS 12.2.1
Darwin 21.3.0

**Comment by petros** [comment] 2024-03-30 18:33
Just as an extra data point, it runs fine on macOS Sonoma 14.2.1.

**Comment by MatinAniss** [comment] 2024-03-30 21:39
macOS `11.7.10`

Getting no window but this info in console: `invalid pixel format 70`.

This issue seems like it started occurring after #9836 
Probably due to the changes from BGRA8 to RGBA8, not sure why this breaks older mac versions since [MTLPixelFormatRGBA8Unorm](https://developer.apple.com/documentation/metal/mtlpixelformat/mtlpixelformatrgba8unorm) is supported for macOS `10.11+` which is the same as [MTLPixelFormatBGRA8Unorm](https://developer.apple.com/documentation/metal/mtlpixelformat/mtlpixelformatbgra8unorm).

**Comment by JusufGaa** [comment] 2024-04-01 06:48
@MatinAniss @petros  I'm trying to update my macOS to 13.6.6.
I'll let you know later if this works.

**Comment by JosephTLyons** [comment] 2024-04-01 14:37
I'm not sure what we should do here. To my knowledge, GPUI isn't established enough as a standalone library, outside of Zed, for us to have guarantees about which past OSes it supports. We know it works on everything new, as we are constantly using it, but as for past OSes, it isn't clear. Maybe its ok to just close this for now?

**Comment by MatinAniss** [comment] 2024-04-01 22:27
This issue affects 12.2.1 (highest currently confirmed) which is not that old (around 2 years ago), I wouldn't be surprised if this issue would affect a significant amount of existing users. Some of which cannot update to a higher version due to their aging hardware.

**Comment by mikayla-maki** [comment] 2024-04-02 17:18
Hi y'all, any chance y'all could test out https://github.com/zed-industries/zed/pull/10089 and confirm for me that this fixes the issue? Thanks!

**Comment by MatinAniss** [comment] 2024-04-02 23:31
macOS `11.7.10`

@mikayla-maki It is running fine again but now for some reason the size of the window and the rendered size is wrong.

<img width="712" alt="Screen Shot 2024-04-03 at 10 28 45 am" src="https://github.com/zed-industries/zed/assets/76515905/efc2962f-4fbf-4cf6-8b00-4d91f0925f17">

**Comment by mikayla-maki** [comment] 2024-04-02 23:36
That’s correct for the sample code :) It’s not a very stylish hello world yet!

**Closed** 2024-04-02 23:36 UTC
Labels: defect, needs info / awaiting response, documentation, gpui
