### ISSUE TITLE
Zig: failed to start language server "zls"

### ISSUE THREAD

**Issue by edwnjos** [zed-industries/zed#12350] opened 2024-05-27 12:23 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I built from source to test the new patch [Pin ZLS to v0.11.0](https://github.com/zed-industries/zed/pull/12173) but its still giving the following error:

```
[2024-05-27T10:52:28+01:00 ERROR project] failed to start language server "zls": no asset found matching "zls-aarch64-macos.tar.gz"
[2024-05-27T10:52:28+01:00 ERROR project] server stderr: Some("")
[2024-05-27T10:52:29+01:00 ERROR util] crates/language/src/language_registry.rs:880: server container removal

Caused by:
    No such file or directory (os error 2)
[2024-05-27T10:52:29+01:00 ERROR project] failed to start language server "zls": no asset found matching "zls-aarch64-macos.tar.gz"
[2024-05-27T10:52:29+01:00 ERROR project] server stderr: Some("")
[2024-05-27T10:52:30+01:00 ERROR util] crates/language/src/language_registry.rs:880: server container removal

Caused by:
    No such file or directory (os error 2)
[2024-05-27T10:52:31+01:00 ERROR project] failed to start language server "zls": no asset found matching "zls-aarch64-macos.tar.gz"
[2024-05-27T10:52:31+01:00 ERROR project] server stderr: Some("")
[2024-05-27T10:52:32+01:00 ERROR util] crates/language/src/language_registry.rs:880: server container removal

Caused by:
    No such file or directory (os error 2)
[2024-05-27T10:52:32+01:00 ERROR project] failed to start language server "zls": no asset found matching "zls-aarch64-macos.tar.gz"
[2024-05-27T10:52:32+01:00 ERROR project] server stderr: Some("")
[2024-05-27T10:52:33+01:00 ERROR util] crates/language/src/language_registry.rs:880: server container removal

Caused by:
    No such file or directory (os error 2)
[2024-05-27T10:52:34+01:00 ERROR project] failed to start language server "zls": no asset found matching "zls-aarch64-macos.tar.gz"
[2024-05-27T10:52:34+01:00 ERROR project] server stderr: Some("")
[2024-05-27T10:52:34+01:00 ERROR project] Hit 4 reinstallation attempts for "zls"
[2024-05-27T10:53:31+01:00 ERROR util] crates/assistant/src/assistant_panel.rs:153: No such file or directory (os error 2)
[2024-05-27T12:18:35+01:00 ERROR util] crates/assistant/src/assistant_panel.rs:153: No such file or directory (os error 2)
[2024-05-27T12:19:04+01:00 ERROR util] crates/assistant/src/assistant_panel.rs:153: No such file or directory (os error 2)
```

Highlighting works but no suggestions. 

I'm not a rust dev and I have no experience with open source stuff so apologies in advance If I have made any mistakes. 

### Environment

Zed: v0.138.0 (Zed Dev 78aaa29d5b768f09ae393bf3d3f150d9f803f3df)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-05-27 14:29
This has already been reported, so I'll close this issue. Be sure to +👍 the other one.

Duplicate of:
- #11162

**Closed by Moshyfawn** 2024-05-27 14:29 UTC
Labels: defect, triage, admin read

**Comment by edwnjos** [comment] 2024-05-27 19:33
@Moshyfawn I built from source to test the [patch](https://github.com/zed-industries/zed/pull/12173) for that issue which uses v0.11.0 instead v0.12.0. I guess its more appropriate for this to be a comment on that issue rather then be separate.
