### ISSUE TITLE
Please add user snippet support in zed 

### ISSUE THREAD

**Issue by pritam12426** [zed-industries/zed#7891] opened 2024-02-16 05:04 UTC
### Check for existing issues

- [X] Completed

### If applicable, add mockups / screenshots to help present your vision of the feature

![ajax-snippet](https://github.com/zed-industries/zed/assets/84720825/bd34000f-f4cd-4cab-bc3e-c9ffee6efd7f)

**Comment by SomeoneToIgnore** [comment] 2024-02-16 07:27
Seems to be a duplicate of https://github.com/zed-industries/zed/issues/4611

**Closed by SomeoneToIgnore** 2024-02-16 07:27 UTC
Labels: enhancement, triage, admin read
