### ISSUE TITLE
Multi user mac doesen't work

### ISSUE THREAD

**Issue by mannireis** [zed-industries/zed#13771] opened 2024-07-03 09:36 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I use a mac and when I open Zed in one of the users and then go to lock screen login as another user try to open Zed and it doesn't open

### Environment

Mac Mini 
Chip: M2 Pro 
MacOS Version: 14.5 (23F79)

**Comment by SomeoneToIgnore** [comment] 2024-07-03 11:17
Duplicate of https://github.com/zed-industries/zed/issues/4607

**Closed by SomeoneToIgnore** 2024-07-03 11:17 UTC
Labels: defect, triage, admin read
