### ISSUE TITLE
Linux shows mac based terminology in context menus

### ISSUE THREAD

**Issue by james2432** [zed-industries/zed#14257] opened 2024-07-11 20:36 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Right click

See "Reveal in Finder"

### Environment

N/A

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![signal-2024-07-11-16-23-05-700](https://github.com/zed-industries/zed/assets/498547/e77bd566-70b9-4a5d-aaa1-a40448fda6c5)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by tx0dev** [comment] 2024-07-11 20:40
Appear to be a duplicate of #12776

**Closed** 2024-07-11 20:40 UTC
Labels: defect, triage, admin read
