### ISSUE TITLE
Project panel puts file and directories under wrong parent, edge condition

### ISSUE THREAD

**Issue by jojo599k** [zed-industries/zed#14201] opened 2024-07-11 13:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Having two directories which names start with the **same** sequence of digits and end with a dot + any other characters or just nothing else following results in every element seeming to be in the last element (see picture). Only the characters have to be the same. The end of the name can be different to the directories.

Following bash command generates the project setup used in the image below:
```bash
mkdir -p project/01 && \
    touch project/01/a && \
    mkdir project/01.123 && \
    touch project/01.123/b && \
    mkdir project/01.Test && \
    touch project/01.Test/c && \
    mkdir project/01abc && \
    touch project/01abc/d && \
    mkdir project/01234 && \
    touch project/01234/e
```

It did some more testing besides the one shown in the image, but not completely exhaustive. The results strongly suggests that the digits are mandatory and works because of them (+ the combination with the dot).

### Environment

Zed: v0.143.6 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="291" alt="Bildschirmfoto 2024-07-11 um 15 37 47" src="https://github.com/zed-industries/zed/assets/28629015/63ac1f58-1d0c-4b70-b1c5-a8d439ae9296">

### If applicable, attach your Zed.log file to this issue.

n.a.

**Comment by notpeter** [comment] 2024-07-13 06:23
Wow. This is wild. And definitely deserves a video.  Thanks for reporting @jojo599k!

https://github.com/user-attachments/assets/168558d7-4aa0-47f0-8a22-d049f819462a

**Comment by SomeoneToIgnore** [comment] 2024-07-13 10:21
Duplicate of https://github.com/zed-industries/zed/issues/12470

**Closed by SomeoneToIgnore** 2024-07-13 10:21 UTC
Labels: defect, project panel
