### ISSUE TITLE
Saving file without changes doesn't trigger code actions

### ISSUE THREAD

**Issue by garrettg123** [zed-industries/zed#16766] opened 2024-08-23 17:36 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In VSCode I was able to save even if there were no changes just to trigger the eslint fixing.

```json
  "languages": {
    "TypeScript": {
      "formatter": {
        "code_actions": {
          "source.fixAll.eslint": true
        }
      }
    }
  }
```

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by someone13574** [comment] 2024-08-24 12:48
Duplicate of #12091

**Closed** 2024-08-24 13:23 UTC
Labels: defect, triage, admin read
