### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by Tsolmonx** [zed-industries/zed#6963] opened 2024-01-29 05:16 UTC
### Check for existing issues

- [X] Completed

### Language

xml

### Tree Sitter parser link

https 

### Language server link

https://github.com/eclipse/lemminx

### Misc notes

Need xml lsp, syntax highlight etc

**Comment by JosephTLyons** [comment] 2024-01-29 06:54
Hey @Tsolmonx,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4869

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-01-29 06:54 UTC
Labels: enhancement, potential plugin, language, unsupported language
