### ISSUE TITLE
When exactly is the release date for the Windows platform?

### ISSUE THREAD

**Issue by mrbardia72** [zed-industries/zed#17624] opened 2024-09-10 05:53 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When exactly is the release date for the Windows platform?

### If applicable, add mockups / screenshots to help present your vision of the feature

When exactly is the release date for the Windows platform?

**Comment by bitfield** [comment] 2024-09-10 08:26
Duplicate of #5394?

**Closed** 2024-09-10 09:06 UTC
Labels: enhancement, triage, admin read
