### ISSUE TITLE
Support continuation/autocomplete of PHP multiline comments

### ISSUE THREAD

**Issue by nsrosenqvist** [zed-industries/zed#17261] opened 2024-09-02 10:52 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When writing PHPDoc-style docblocks, and if one doesn't have Copilot to complete it for you, it's really annoying having to add additional lines with indentation and asterisks. Ideally, Zed should help you with writing these comment structures.

### If applicable, add mockups / screenshots to help present your vision of the feature

This is how I'd like the autocomplete to function:

Writing`/*` should result in a suggestion of `*/` to end it, and when pressing enter it should expand into:
```php
/*
 * [cursor position]
 */
```
When pressing enter again, additional lines should be correctly indented and prefixed with an asterisk:
```php
/*
 *
 * [cursor position]
 */
```
The same behavior should be applied to PHPDoc-style comments, ie. starting with double asterisk `/**`:
```php
/**
 * [cursor position]
 */
```
Ideally, PHPDoc-style comments should also be possible to get prefilled with the `@param` and `@return` annotations that can be extracted from the native PHP type-hinting (if configured). If this latter feature is added, then being able to configure how spacing, FQN/relative class names, alignment, would be required.
```php
/**
 * @param string $input
 *
 * @return bool
 */
public function myMethod(string $input): bool;

**Comment by notpeter** [comment] 2024-09-02 18:56
Duplicate of:
- https://github.com/zed-industries/zed/issues/13318

Please 👍 on that issue and subscribe to track progress. Thanks for reporting!

**Closed by notpeter** 2024-09-02 18:56 UTC
Labels: enhancement, triage, admin read
