### ISSUE TITLE
rename file: change case not working

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#7196] opened 2024-02-01 09:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

change file name from `a.txt` to `A.txt` doesn't work

<img width="471" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/2417a01e-9d11-4e0c-8fdc-1a14234cca24">

After change file name in file explorer:

<img width="266" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/8b6eb70f-6014-490e-9359-e921f30b4b13">

Zed:

<img width="266" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/7795fb31-644e-4f52-83e6-da26f37bc216">

### Environment

Zed: v0.120.5 (Zed)
OS: macOS 14.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-01 22:26
Hey @kzhui125,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5211

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-01 22:26 UTC
Labels: defect, project panel
