### ISSUE TITLE
Caps Lock only work while holding the key

### ISSUE THREAD

**Issue by vekidev** [zed-industries/zed#14573] opened 2024-07-16 15:01 UTC
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

On Fedora 40, Caps lock only works while holding the key.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 fedora 40
Memory: 15.6 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-16 15:16
Duplicate of: 
- #13936

**Closed by notpeter** 2024-07-16 15:16 UTC
Labels: defect, triage, admin read
