### ISSUE TITLE
clangd: Support for "Call Hierarchy"

### ISSUE THREAD

**Issue by acama** [zed-industries/zed#19883] opened 2024-10-29 09:53 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

On Vscode's clangd extension there is a very useful feature called "Call Hierarchy" which seems to use clangd's `'callHierarchy/incomingCalls'` and `'callHierarchy/outgoingCalls'` to display "callers-of-callers" and "callees-of-callees" until you hit a leaf (in a navigatable manner). It would be really nice if we could have something like this on Zed's clangd.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="277" alt="Screenshot 2024-10-29 at 09 50 21" src="https://github.com/user-attachments/assets/d7e649bf-9262-495b-9a61-afc43055f64a">
<img width="474" alt="Screenshot 2024-10-29 at 09 51 53" src="https://github.com/user-attachments/assets/fb38b182-aa8c-4eb2-9dc6-3502c2abf39b">

**Comment by jansol** [comment] 2024-10-29 14:17
Duplicate of #14203

**Closed by jansol** 2024-10-29 14:17 UTC
Labels: enhancement, triage, admin read
