### ISSUE TITLE
Extensions divide by type

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#10802] opened 2024-04-20 10:42 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

This is the current view of the extensions:

<img width="1439" alt="Screenshot 2024-04-20 alle 12 31 05" src="https://github.com/zed-industries/zed/assets/20476002/f81f7ff5-7026-4456-853e-f677dfd9a653">

But it is not clear what type of extensions they are, whether they are theme extensions or something else.
For example, some of them do not contain the word theme `The Dark Side` in their title and description, you have to go and see the project to understand what type of extension it is.

**Comment by jansol** [comment] 2024-04-20 15:59
Duplicate of #8848

**Comment by Moshyfawn** [comment] 2024-04-20 17:39
Be sure to +👍 and follow the other issue.

Duplicate of:
- #8848

**Closed by Moshyfawn** 2024-04-20 17:39 UTC
Labels: enhancement, triage, admin read
