### ISSUE TITLE
Restore non-project files after relaunching Zed

### ISSUE THREAD

**Issue by VKondakoff** [zed-industries/zed#9851] opened 2024-03-27 10:58 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently Zed restores recently opened project after relaunching. 
Please, allow restoring non-project files as well.
For example: instead of opening a project, I'm loading three files: `one.txt`, `two.txt` and `three.txt`. After quitting and relaunching Zed I want to see all three files, that were loaded before quitting: `one.txt`, `two.txt` and `three.txt`.
Here is related issue (Allow files to be added to Open recent together with folders (projects)): https://github.com/zed-industries/zed/issues/9850

**Comment by Moshyfawn** [comment] 2024-03-27 14:09
This is already a feature request, so I'm going to close this issue in favour of the other one to keep the conversation in one place. Be sure to +👍 it.

Duplicate of
- #4985

**Comment by VKondakoff** [comment] 2024-03-27 14:20
Oops! I was not asking to preserve the `untitled` files between Zed sessions. I'm talking about _real_ named files (say, `one.txt`, `two.txt` and `three.txt`), which just do not belong to any project. Like these (for example):
<img width="1189" alt="Снимок экрана 2024-03-27 в 17 18 05" src="https://github.com/zed-industries/zed/assets/230824/01d7facf-ad6b-4312-a966-3c85892f3df0">
If I close Zed now, these buffers will not be restored.
@Moshyfawn, sorry for bothering you, but are you sure this is a duplicate of `Preserve untitled files`?

**Comment by Moshyfawn** [comment] 2024-03-27 14:39
No no, you're right, my mistake, I didn't read too much into your description, sorry.

**Comment by notpeter** [comment] 2024-07-31 14:37
I believe this is the same as:
- https://github.com/zed-industries/zed/issues/15098

Although your issue older I'm going to close this in favor of that one because it has more upvotes.  Please 👍 and subscribe to that issue to track its progress.

**Closed by notpeter** 2024-07-31 14:37 UTC
Labels: enhancement, workspace, serialization
