### ISSUE TITLE
Please replace paired tags

### ISSUE THREAD

**Issue by vruzin** [zed-industries/zed#10971] opened 2024-04-25 06:11 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Please replace paired tags

<h2>......</h2>
Please make sure that if I change a tag, the second one also changes.

**Comment by elkowar** [comment] 2024-04-27 11:05
@JosephTLyons I think what they're asking for might be zed automatically editing both ends of HTML tags?
as in, if I have
```
<div>
  <foo>stuff</foo>
</div>
```
and then edit the opening <div>, zed automatically also updating the closing tag?

**Comment by ElectricS01** [comment] 2024-05-09 09:51
+1 for this, would be really helpful for html and vue files

**Comment by Moshyfawn** [comment] 2024-05-30 12:51
Hi! This threissuead seems to be a duplicate of another newer issue that has more upvotes, so I'm going to close this one in favour of the other one to keep the conversation in one place. Please be sure to +👍 the other thread instead.

Duplicate of:
- #4535

**Closed by Moshyfawn** 2024-05-30 12:51 UTC
Labels: enhancement, needs info / awaiting response
