### ISSUE TITLE
[BUG] Image File is Not Updating

### ISSUE THREAD

**Issue by Tahinli** [zed-industries/zed#17640] opened 2024-09-10 12:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you open an image inside Zed. Even if you change the image but keep it same name. Zed shows old image. I think you're doing some kind of caching this prevents image file to reopen.

### Environment

Fedora 40 KDE

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-10 15:51
Duplicate of:
- #11529

**Closed by notpeter** 2024-09-10 15:51 UTC
Labels: defect, triage, admin read

**Comment by Tahinli** [comment] 2024-09-10 17:08
sorry
