### ISSUE TITLE
LSP code action menu not scrollable by keystrokes

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4674] opened 2023-06-19 14:11 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

LSP code action menu is not scrollable by keystrokes, but is OK with mouse.

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![output](https://github.com/zed-industries/community/assets/5475262/d2ae6d99-b011-4c6d-9393-4a54a1751ca4)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 06:50
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 06:50 UTC
Labels: defect, popovers
