### ISSUE TITLE
Closing a Workspace or Window Closes All Zed Windows on Wayland (KDE Plasma 6, NixOS)

### ISSUE THREAD

**Issue by pageton** [zed-industries/zed#21351] opened 2024-11-30 00:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When closing a window or workspace in Zed IDE on KDE Plasma 6 running on Wayland (NixOS), all other Zed windows also close unexpectedly. However, when running Zed without Wayland (using X11), this issue does not occur, and the application works normally. The problem, though, is that the display resolution becomes very poor without Wayland.

### Environment

Zed: v0.163.2 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 30.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3070 || NVIDIA || 560.35.03

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```
2024-11-30T03:08:48.802744022+03:00 [INFO] ========== starting zed ==========
2024-11-30T03:08:48.83270022+03:00 [INFO] perform;
2024-11-30T03:08:48.832847512+03:00 [INFO] Opening main db
2024-11-30T03:08:48.832866674+03:00 [INFO] authenticate;
2024-11-30T03:08:48.832895824+03:00 [INFO] read_command;
2024-11-30T03:08:48.833293033+03:00 [INFO] new;
2024-11-30T03:08:48.833318957+03:00 [INFO] socket reader;
2024-11-30T03:08:48.833507068+03:00 [INFO] Opening main db
2024-11-30T03:08:48.833707501+03:00 [INFO] keep_updated;
2024-11-30T03:08:48.834894468+03:00 [INFO] Using git binary path: None
2024-11-30T03:08:48.85279864+03:00 [INFO] No prompt template overrides directory found at /home/rio/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-11-30T03:08:48.853085039+03:00 [INFO] extensions updated. loading 24, reloading 0, unloading 0
2024-11-30T03:08:48.85419184+03:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-11-30T03:08:48.855361407+03:00 [INFO] Opening main db
2024-11-30T03:08:48.855517714+03:00 [INFO] perform;
2024-11-30T03:08:48.855539211+03:00 [INFO] authenticate;
2024-11-30T03:08:48.855572638+03:00 [INFO] read_command;
2024-11-30T03:08:48.85589585+03:00 [INFO] socket reader;
2024-11-30T03:08:48.858193134+03:00 [INFO] new;
2024-11-30T03:08:48.858598517+03:00 [INFO] keep_updated;
2024-11-30T03:08:48.861238456+03:00 [INFO] set status on client 0: Authenticating
2024-11-30T03:08:48.861430284+03:00 [INFO] perform;
2024-11-30T03:08:48.861449076+03:00 [INFO] authenticate;
2024-11-30T03:08:48.861470452+03:00 [INFO] read_command;
2024-11-30T03:08:48.861795127+03:00 [INFO] socket reader;
2024-11-30T03:08:48.864230857+03:00 [INFO] new;
2024-11-30T03:08:48.864567863+03:00 [INFO] keep_updated;
2024-11-30T03:08:48.925789506+03:00 [INFO] Enabling Vulkan Portability
2024-11-30T03:08:48.925814078+03:00 [INFO] Enabling color space support
2024-11-30T03:08:48.9390173+03:00 [INFO] set environment variables from shell:/run/current-system/sw/bin/zsh, path:/home/rio/.bun/bin:/run/wrappers/bin:/home/rio/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/home/rio/.nix-profile/bin:/nix/profile/bin:/home/rio/.local/state/nix/profile/bin:/etc/profiles/per-user/rio/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/rio/go/bin:/home/rio/go/bin
2024-11-30T03:08:48.939289144+03:00 [INFO] Adapter: "NVIDIA GeForce RTX 3070"
2024-11-30T03:08:48.939322441+03:00 [INFO] Ray tracing is supported
2024-11-30T03:08:49.199198642+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:08:49.199233702+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:08:49.207129044+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:08:49.207149799+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:08:49.207166708+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-11-30T03:08:49.212152899+03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 3070", driver_name: "NVIDIA", driver_info: "560.35.03" }
2024-11-30T03:08:49.212574139+03:00 [INFO] set status on client 208666: Connecting
2024-11-30T03:08:49.215037408+03:00 [INFO] Opening main db
2024-11-30T03:08:49.215999041+03:00 [INFO] Opening main db
2024-11-30T03:08:49.320330898+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:08:49.320357393+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:08:49.327773626+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-11-30T03:08:49.332035098+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:08:49.332056114+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:08:49.339200313+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-11-30T03:08:49.372052422+03:00 [ERROR] missing field `name` at line 882 column 1
2024-11-30T03:08:49.376053118+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:08:49.376091594+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:08:49.384389564+03:00 [WARN] unhandled message: Metadata(SupermavenMetadataMessage { dust_strings: None })
2024-11-30T03:08:49.390280721+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-11-30T03:08:49.706740089+03:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-11-30T03:08:50.309546425+03:00 [INFO] add_connection;
2024-11-30T03:08:50.322513133+03:00 [INFO] set status on client 208666: Connected { peer_id: PeerId { owner_id: 616, id: 3936743 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-11-30T03:08:50.370765474+03:00 [WARN] unhandled message: TaskStatus(SupermavenTaskUpdateMessage { task: "Initializing", status: Complete, percent_complete: None })
2024-11-30T03:08:50.370808397+03:00 [WARN] unhandled message: ActiveRepo(SupermavenActiveRepoMessage { repo_simple_name: None })
2024-11-30T03:08:53.549040626+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:08:53.554411429+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:08:53.565135126+03:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-11-30T03:08:53.571339686+03:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-11-30T03:09:02.106810369+03:00 [INFO] Enabling Vulkan Portability
2024-11-30T03:09:02.106835572+03:00 [INFO] Enabling color space support
2024-11-30T03:09:02.124854673+03:00 [INFO] Adapter: "NVIDIA GeForce RTX 3070"
2024-11-30T03:09:02.124892668+03:00 [INFO] Ray tracing is supported
2024-11-30T03:09:02.270610382+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:02.270648518+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:02.277600863+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:09:02.277629032+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:09:02.277650669+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-11-30T03:09:02.282597348+03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 3070", driver_name: "NVIDIA", driver_info: "560.35.03" }
2024-11-30T03:09:02.337597831+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:02.337624036+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:02.345686949+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-11-30T03:09:02.35176347+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:02.351792821+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:02.361340636+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-11-30T03:09:02.391889004+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:02.391916612+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:05.594560104+03:00 [ERROR] window not found
2024-11-30T03:09:08.207520201+03:00 [INFO] ========== starting zed ==========
2024-11-30T03:09:08.238096185+03:00 [INFO] perform;
2024-11-30T03:09:08.238127902+03:00 [INFO] authenticate;
2024-11-30T03:09:08.238160721+03:00 [INFO] read_command;
2024-11-30T03:09:08.238281068+03:00 [INFO] Opening main db
2024-11-30T03:09:08.238576782+03:00 [INFO] new;
2024-11-30T03:09:08.238604011+03:00 [INFO] socket reader;
2024-11-30T03:09:08.238974649+03:00 [INFO] keep_updated;
2024-11-30T03:09:08.239081552+03:00 [INFO] Opening main db
2024-11-30T03:09:08.240374563+03:00 [INFO] Using git binary path: None
2024-11-30T03:09:08.257993132+03:00 [INFO] No prompt template overrides directory found at /home/rio/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-11-30T03:09:08.25826338+03:00 [INFO] extensions updated. loading 24, reloading 0, unloading 0
2024-11-30T03:09:08.259370767+03:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-11-30T03:09:08.260523335+03:00 [INFO] Opening main db
2024-11-30T03:09:08.260683453+03:00 [INFO] perform;
2024-11-30T03:09:08.260705754+03:00 [INFO] authenticate;
2024-11-30T03:09:08.260731921+03:00 [INFO] read_command;
2024-11-30T03:09:08.261135458+03:00 [INFO] socket reader;
2024-11-30T03:09:08.263856876+03:00 [INFO] new;
2024-11-30T03:09:08.264205524+03:00 [INFO] keep_updated;
2024-11-30T03:09:08.34472256+03:00 [INFO] set environment variables from shell:/run/current-system/sw/bin/zsh, path:/home/rio/.bun/bin:/run/wrappers/bin:/home/rio/.local/share/flatpak/exports/bin:/var/lib/flatpak/exports/bin:/home/rio/.nix-profile/bin:/nix/profile/bin:/home/rio/.local/state/nix/profile/bin:/etc/profiles/per-user/rio/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/rio/go/bin:/home/rio/go/bin
2024-11-30T03:09:08.351355761+03:00 [INFO] Enabling Vulkan Portability
2024-11-30T03:09:08.351380686+03:00 [INFO] Enabling color space support
2024-11-30T03:09:08.369544267+03:00 [INFO] Adapter: "NVIDIA GeForce RTX 3070"
2024-11-30T03:09:08.369585932+03:00 [INFO] Ray tracing is supported
2024-11-30T03:09:08.660525033+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:08.660568381+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:08.668768848+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:09:08.668790377+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:09:08.668808309+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-11-30T03:09:08.673940954+03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 3070", driver_name: "NVIDIA", driver_info: "560.35.03" }
2024-11-30T03:09:08.676499337+03:00 [INFO] set status on client 0: Authenticating
2024-11-30T03:09:08.676776577+03:00 [INFO] perform;
2024-11-30T03:09:08.676801051+03:00 [INFO] authenticate;
2024-11-30T03:09:08.676829372+03:00 [INFO] read_command;
2024-11-30T03:09:08.677170297+03:00 [INFO] socket reader;
2024-11-30T03:09:08.67975067+03:00 [INFO] new;
2024-11-30T03:09:08.680090312+03:00 [INFO] keep_updated;
2024-11-30T03:09:08.688883458+03:00 [ERROR] missing field `name` at line 882 column 1
2024-11-30T03:09:08.689010407+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:08.689026987+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:08.696594803+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-11-30T03:09:08.700734708+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:08.700754103+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:08.70879971+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-11-30T03:09:08.718263745+03:00 [INFO] set status on client 208666: Connecting
2024-11-30T03:09:08.71887105+03:00 [INFO] Opening main db
2024-11-30T03:09:08.830556117+03:00 [INFO] Using surface present mode MAILBOX
2024-11-30T03:09:08.830582334+03:00 [WARN] Unable to forbid exclusive full screen
2024-11-30T03:09:08.842866003+03:00 [INFO] Opening main db
2024-11-30T03:09:08.857422331+03:00 [ERROR] missing field `name` at line 882 column 1
2024-11-30T03:09:08.858809943+03:00 [WARN] unhandled message: Metadata(SupermavenMetadataMessage { dust_strings: None })
2024-11-30T03:09:08.860596795+03:00 [WARN] unhandled message: Set(SupermavenSetMessage { key: "disabled", value: Bool(false) })
2024-11-30T03:09:09.19610647+03:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-11-30T03:09:09.828058829+03:00 [INFO] add_connection;
2024-11-30T03:09:09.845239812+03:00 [INFO] set status on client 208666: Connected { peer_id: PeerId { owner_id: 616, id: 3936956 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-11-30T03:09:09.996243234+03:00 [WARN] unhandled message: TaskStatus(SupermavenTaskUpdateMessage { task: "Initializing", status: Complete, percent_complete: None })
2024-11-30T03:09:09.996289828+03:00 [WARN] unhandled message: ActiveRepo(SupermavenActiveRepoMessage { repo_simple_name: None })
2024-11-30T03:09:11.723111476+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:09:11.727439472+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-30T03:09:11.732209867+03:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-11-30T03:09:11.738289432+03:00 [INFO] Creating a descriptor pool for at most 256 sets

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-30 06:12
Duplicate of https://github.com/zed-industries/zed/issues/17005

**Closed by SomeoneToIgnore** 2024-11-30 06:12 UTC
Labels: bug, triage, panic / crash, admin read
