### ISSUE TITLE
Sidebar and editor doesn't show up when editor is closed after remoming a project.

### ISSUE THREAD

**Issue by s4gor** [zed-industries/zed#4805] opened 2023-04-09 21:09 UTC
### Check for existing issues

- [ ] Completed

### Describe the bug / provide steps to reproduce it

The sidebar along with the editor doesn't show up when I open Zed after removing a folder from the project. And also nothing happens when I try to open recent or any files, nothing shows up. But after this occurrence, if I try to reopen the editor, everything shows up just fine. Also sometimes, a removed folder from the project is opened automatically at startup. But I removed the folder earlier. It remains in the project after opening the editor. The terminal opens perfectly. But neither the sider nor the editor is opened. It happens sometimes. For a better understanding, I am attaching a screenshot.

### Environment

Zed: v0.80.5 (stable)
OS: macOS 13.2.0
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2023-04-10 at 3 07 21 AM](https://user-images.githubusercontent.com/32714192/230796554-4affb3d5-1d8d-45a0-aa78-9cb7ae63a2a1.png)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 05:47
I'm unable to reproduce this in current Zed, so I'm going to close this issue out. If you run into it again, please open a new issue!

**Closed by JosephTLyons** 2024-07-28 05:47 UTC
Labels: defect, workspace
