### ISSUE TITLE
Image preview isn't showing the whole image

### ISSUE THREAD

**Issue by mikajed** [zed-industries/zed#17439] opened 2024-09-05 18:00 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open an image preview in Zed it always gets cut off and doesn't show the whole image.

### Environment

Zed: v0.151.1 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1470" alt="Bildschirmfoto 2024-09-05 um 19 55 03" src="https://github.com/user-attachments/assets/e01fd16b-17dc-4490-b76b-fc91ea6d9da1">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-05 19:37
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/9582

See also:
- https://github.com/zed-industries/zed/issues/9584

**Closed by notpeter** 2024-09-05 19:37 UTC
Labels: defect, triage, admin read
