### ISSUE TITLE
Download url broke

### ISSUE THREAD

**Issue by George3d6** [zed-industries/zed#21052] opened 2024-11-22 07:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The download url for macbook on your website seems broken.

Leads to: [https://zed.dev/api/releases/stable/0.162.5/undefined?browserId=19352d65e231e3b-001856e2e2b111-432c2f36-157188-19352d65e2425a9](https://zed.dev/api/releases/stable/0.162.5/undefined?browserId=19352d65e231e3b-001856e2e2b111-432c2f36-157188-19352d65e2425a9) which displaus => `Could not find download URL`

### Environment

-

### If applicable, add mockups / screenshots to help explain present your vision of the feature

-

### If applicable, attach your Zed.log file to this issue.

-

**Comment by osiewicz** [comment] 2024-11-22 12:38
This looks like a regression from https://github.com/zed-industries/zed/pull/21014; it's odd though, since the latest release still had a Zed.dmg assets 🤔

**Comment by osiewicz** [comment] 2024-11-22 12:51
It's now fixed. Thank you for reporting!

**Closed by osiewicz** 2024-11-22 12:51 UTC
Labels: bug, triage, admin read
