### ISSUE TITLE
Disable blank space in the bottom of file after the last line of code

### ISSUE THREAD

**Issue by Jawell** [zed-industries/zed#8426] opened 2024-02-26 08:32 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Add a config property to disable/enable this space as "editor.scrollBeyondLastLine" in VS code. It's really annoying

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1486" alt="Screenshot 2024-02-26 at 10 25 33" src="https://github.com/zed-industries/zed/assets/21054523/12c18319-3b9e-4ac2-be4d-e778dfa8b8c0">

**Comment by Jawell** [comment] 2024-03-01 12:08
@Otterpocket I don't like it 🙂. If you quickly scroll down you will see this blank space, not the end of the code e.g.

**Comment by Moshyfawn** [comment] 2024-03-02 02:15
I'm going to close this issue as a duplicate in favour of the other one, as it has more upvotes and discussion. Be sure to +👍 and add any missing details to the other thread.

**Comment by Moshyfawn** [comment] 2024-03-02 02:16
Duplicate of #4962

**Closed by Moshyfawn** 2024-03-02 02:16 UTC
Labels: enhancement, editor, setting
