### ISSUE TITLE
Some remaps does not work

### ISSUE THREAD

**Issue by o3wiz** [zed-industries/zed#8010] opened 2024-02-19 10:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've attempted to incorporate those two keymaps into my custom keymap, but they don't seem to be functioning; they simply don't respond.
json file:
```json
[
  {
    "context": "Editor",
    "bindings": {
      "ctrl-w": "editor::SelectLargerSyntaxNode",
      "ctrl-shift-w": "editor::SelectSmallerSyntaxNode",
      "alt+j": "editor::MoveLineDown", // does not work
      "alt+k": "editor::MoveLineUp"    // does not work
    }
  }
]
```

### Environment

Mac Mini m2

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment] 2024-02-19 11:45
Looks like a duplicate of https://github.com/zed-industries/zed/issues/7937 with more cases, but leaving open for now, as that one mentions disabling of keybindings (`null`) and here it is a bit of a different thing made (albeit it is most probably the same root cause for both).

**Closed** 2024-02-29 11:27 UTC
Labels: defect, keymap / key binding
