### ISSUE TITLE
kind: Generic("Input watch path is neither a file nor a directory.")

### ISSUE THREAD

**Issue by jefftantan** [zed-industries/zed#19115] opened 2024-10-12 06:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

in Windows ，cargo run  

[2024-10-12T14:37:17+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-12T14:37:18+08:00 ERROR theme] theme not found: Github Light
[2024-10-12T14:37:18+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-12T14:37:18+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-12T14:37:18+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-12T14:37:18+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE | INHERIT
[2024-10-12T14:37:18+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE | INHERIT
[2024-10-12T14:37:18+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE | INHERIT
[2024-10-12T14:37:18+08:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "参数错误。" }
[2024-10-12T14:37:18+08:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "参数错误。" }

### Environment

in  windows 

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-12 06:58
Likely duplicate of:
- https://github.com/zed-industries/zed/issues/18610

**Closed by notpeter** 2024-10-12 06:58 UTC
Labels: defect, triage, admin read
