### ISSUE TITLE
If a file is already openned in Zed, openning anoter file via Zed CLI should open it in a new tab of the same window

### ISSUE THREAD

**Issue by NicoAdrian** [zed-industries/zed#7380] opened 2024-02-05 12:57 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Title says it all. Just like sublime text behaves this way.

**Comment by JosephTLyons** [comment] 2024-02-06 22:14
Hey @NicoAdrian,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4861

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-06 22:14 UTC
Labels: enhancement, triage, admin read
