### ISSUE TITLE
Chinese Line Break Issue in Editor

### ISSUE THREAD

**Issue by csbde** [zed-industries/zed#11719] opened 2024-05-12 11:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When automatically wrapping Chinese text in the editor, it fails to recognize proper line breaks and often wraps the text at odd places.

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-05-12 15:18
This has already been reported in another issue, so I'll close this one in favour of it. Be sure to +👍 the other thread and add any missing information to it.

Duplicate of:
- #11202

**Closed by Moshyfawn** 2024-05-12 15:18 UTC
Labels: defect, triage, admin read
