### ISSUE TITLE
When using autocomplete in javascript duplicate results occur.

### ISSUE THREAD

**Issue by ardhichoiruddin** [zed-industries/zed#13109] opened 2024-06-16 14:07 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using autocomplete in javascript duplicate results occur.

### Environment

Zed: 0.139.3
ProductName: macOS
ProductVersion: 14.4.1
BuildVersion: 23E224

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/33990014/25f85f9a-cf73-4f06-baf0-16625df4db88

**Comment by Moshyfawn** [comment] 2024-06-16 17:07
This seems to have been reported already, so I'm going to close this issue in favour of the existing one. Be sure to +👍 and follow the other thread.

Duplicate of:
- #4929

**Closed by Moshyfawn** 2024-06-16 17:07 UTC
Labels: defect, triage, admin read
