### ISSUE TITLE
Unable to type square and curly brackets in integrated terminal and Python shell on MacBook with German keyboard

### ISSUE THREAD

**Issue by kajen3** [zed-industries/zed#17963] opened 2024-09-17 18:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Description:
I am unable to type square brackets "[" "]" and curly braces "{" "}" in both the integrated terminal and Python shell.

Steps to reproduce:
1. Open the integrated terminal or Python shell
2. Attempt to type a square bracket using Option + 5 (for "[")
3. Attempt to type a curly brace using Option + 8 (for "{")

Expected behavior:
The characters "[", "]", "{", and "}" should appear when typed.

Actual behavior:
- In the integrated terminal: Nothing happens when attempting to type these characters.
- In the Python shell: The characters don't appear, and subsequent keystrokes are repeated. (see screenshots below)

Additional information:
- This issue only occurs in the integrated terminal and Python shell.
- I can type these characters normally in other applications and text editors.

If you have any questions or need additional information, please let me know.

### Environment

Zed: v0.152.4 (Zed)
OS: macOS 14.7.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1861" alt="Screenshot 2024-09-17 at 20 40 27" src="https://github.com/user-attachments/assets/d65d4874-02bd-42b3-8b8a-0ee596d7dcef">
<img width="1911" alt="Screenshot 2024-09-17 at 20 40 34" src="https://github.com/user-attachments/assets/9fd2e0d4-65e7-438b-9849-07a82cb6f2a2">
<img width="1915" alt="Screenshot 2024-09-17 at 20 40 39" src="https://github.com/user-attachments/assets/e820e20c-75ce-48bc-a634-1a7066e84646">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-17T20:39:04.579664+02:00 [INFO] ========== starting zed ==========
﻿﻿2024-09-17T20:39:04.580454+02:00 [INFO] Opening main db
2024-09-17T20:39:04.602458+02:00 [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-09-17T20:39:04.802183+02:00 [INFO] initializing context server client
2024-09-17T20:39:04.802316+02:00 [INFO] Registering built-in prompt template: content_prompt
2024-09-17T20:39:04.802675+02:00 [INFO] Registering built-in prompt template: edit_workflow
2024-09-17T20:39:04.802879+02:00 [INFO] Registering built-in prompt template: step_resolution
2024-09-17T20:39:04.803229+02:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-09-17T20:39:04.803445+02:00 [INFO] No prompt template overrides directory found at /Users/.../.config/zed/prompt_overrides. Using built-in prompts.
2024-09-17T20:39:04.803776+02:00 [INFO] extensions updated. loading 4, reloading 0, unloading 0
2024-09-17T20:39:04.839058+02:00 [INFO] Opening main db
2024-09-17T20:39:04.843826+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-09-17T20:39:04.870498+02:00 [INFO] Opening main db
2024-09-17T20:39:04.905971+02:00 [INFO] set status on client 0: Authenticating
2024-09-17T20:39:04.9158+02:00 [INFO] set status on client 237000: Connecting
2024-09-17T20:39:04.97512+02:00 [INFO] set environment variables from shell:/bin/zsh, path:/Users/.../micromamba/condabin:/Users/.../.pyenv/shims:/Users/.../.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/.../.local/bin
2024-09-17T20:39:05.151067+02:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-09-17T20:39:05.156617+02:00 [INFO] Node runtime install_if_needed
2024-09-17T20:39:05.245953+02:00 [INFO] starting language server. binary path: "/Users/.../Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/", args: ["/Users/.../Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-09-17T20:39:05.463981+02:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-17T18:39:05.461Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-09-17T18:39:05.461Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-09-17T20:39:05.46518+02:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "56943f8c-687b-4d7c-8e4d-3346dd74c678",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-09-17T20:39:05.49042+02:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-17T18:39:05.469Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-09-17T18:39:05.469Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-09-17T20:39:05.581882+02:00 [INFO] add connection to peer
2024-09-17T20:39:05.581995+02:00 [INFO] add_connection;
2024-09-17T20:39:05.58209+02:00 [INFO] waiting for server hello
2024-09-17T20:39:05.61059+02:00 [INFO] got server hello
2024-09-17T20:39:05.610721+02:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 540, id: 10286124 })
2024-09-17T20:39:05.610904+02:00 [INFO] set status on client 237000: Connected { peer_id: PeerId { owner_id: 540, id: 10286124 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }

</pre></details>

**Comment by kajen3** [comment] 2024-09-18 07:03
Solved by this fix: https://github.com/zed-industries/zed/issues/16581#issuecomment-2303999836

**Comment by SomeoneToIgnore** [comment] 2024-09-18 13:38
Will close it as a duplicate of https://github.com/zed-industries/zed/issues/17971 (and some others).
I think, the main question is voiced in https://github.com/zed-industries/zed/issues/17971#issuecomment-2357603088 and that's where we should continue.

**Closed by SomeoneToIgnore** 2024-09-18 13:38 UTC
Labels: defect, triage, admin read
