### ISSUE TITLE
"project panel: collapse all entries" expands collapsed worktrees

### ISSUE THREAD

**Issue by oliverjohns** [zed-industries/zed#10597] opened 2024-04-16 07:46 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when I run

project panel: collapse all entries

it expands (not collapses) all folders in my project view. I assume this is not how its supposed to work?

### Environment

Zed: v0.130.6 (Zed)
OS: macOS 14.1.0
Memory: 18 GiB
Architecture: aarch64

**Comment by JosephTLyons** [comment] 2024-04-16 17:33
This is super strange - Im not able to reproduce. Do you have any custom settings? If so, what happens when you run the action with no custom settings configured?

**Comment by oliverjohns** [comment] 2024-04-17 11:31
My zed settings are very basic:
```
{
  "theme": "Rosé Pine",
  "base_keymap": "VSCode",
  "ui_font_size": 16,
  "buffer_font_size": 16,
  "format_on_save": "on"
}
```
Here is a video showing the problem:

https://github.com/zed-industries/zed/assets/63138155/efe44d1b-c77f-438a-92c9-a488c237ed62

**Comment by osiewicz** [comment] 2024-04-17 15:58
Fix for it will be released with next week's Preview. We could squeeze it into this weeks Preview in theory, but I'd rather have it sit on nightly for a bit.

**Closed** 2024-04-17 20:55 UTC
Labels: defect, project panel, keymap / key binding
