### ISSUE TITLE
Drag and Drop code inside code block

### ISSUE THREAD

**Issue by meutshuk** [zed-industries/zed#8230] opened 2024-02-22 23:40 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

click on the selected line of code and drag it inside a code block similar to vs code drag and drop

### If applicable, add mockups / screenshots to help present your vision of the feature

https://github.com/zed-industries/zed/assets/52316734/c68ca957-c583-4d88-9d08-d4c0efc41e23

**Comment by JosephTLyons** [comment] 2024-02-23 19:28
Hey @meutshuk,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4958

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-23 19:28 UTC
Labels: enhancement, editor
