### ISSUE TITLE
Unstable. Edit my PHP project.The editor started reporting errors 5 minutes after it was opened. Code prompts, jumping to the defined function, and error prompts were abnormal.

### ISSUE THREAD

**Issue by onhao** [zed-industries/zed#20276] opened 2024-11-06 02:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

2024-11-05T18:50:03+08:00 ERROR lsp] cannot read LSP message headers
[2024-11-05T18:50:03+08:00 ERROR project] oneshot canceled
[2024-11-05T18:50:04+08:00 ERROR project] server shut down
[2024-11-05T18:50:04+08:00 ERROR lsp] Broken pipe (os error 32)
[2024-11-05T18:50:04+08:00 ERROR project] server shut down
[2024-11-05T18:50:04+08:00 ERROR editor] server shut down
[2024-11-05T18:50:04+08:00 ERROR editor] server shut down
[2024-11-05T18:50:05+08:00 ERROR project] server shut down
[2024-11-05T18:50:06+08:00 ERROR project] server shut down
[2024-11-05T18:50:06+08:00 ERROR project] server shut down
[2024-11-05T18:50:08+08:00 ERROR project] server shut down
[2024-11-05T18:50:15+08:00 ERROR gpui::platform::linux::x11::client] Unknown x11 button: 25

### Environment

OS: ubuntu 24.04 
Latest test preview
and the latest official version
It's the same problem

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-11-05T18:40:10.370110521+08:00 [INFO] ========== starting zed ==========
2024-11-05T18:40:10.496917572+08:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-11-05T18:40:10.496962271+08:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-11-05T18:40:10.501253539+08:00 [INFO] Try connect ibus
2024-11-05T18:40:10.511251967+08:00 [INFO] perform;
2024-11-05T18:40:10.511275116+08:00 [INFO] authenticate;
2024-11-05T18:40:10.511894979+08:00 [INFO] read_command;
2024-11-05T18:40:10.51664961+08:00 [INFO] socket reader;
2024-11-05T18:40:10.516680317+08:00 [INFO] new;
2024-11-05T18:40:10.517312598+08:00 [INFO] keep_updated;
2024-11-05T18:40:10.531345514+08:00 [INFO] Opening main db
2024-11-05T18:40:10.553521579+08:00 [INFO] Using git binary path: None
2024-11-05T18:40:10.581957213+08:00 [INFO] set environment variables from shell:/bin/bash, path:/home/wuhao/.local/bin:/home/wuhao/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
2024-11-05T18:40:10.638322961+08:00 [ERROR] theme not found: Catppuccin Mocha - No Italics
2024-11-05T18:40:10.654020291+08:00 [INFO] initializing context server client
2024-11-05T18:40:10.656220997+08:00 [INFO] Registering built-in prompt template: content_prompt
2024-11-05T18:40:10.657711503+08:00 [INFO] Registering built-in prompt template: edit_workflow
2024-11-05T18:40:10.657925297+08:00 [INFO] Registering built-in prompt template: step_resolution
2024-11-05T18:40:10.658322184+08:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-11-05T18:40:10.658508077+08:00 [INFO] No prompt template overrides directory found at /home/wuhao/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-11-05T18:40:10.676741774+08:00 [INFO] extensions updated. loading 6, reloading 0, unloading 0
2024-11-05T18:40:10.703411811+08:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-11-05T18:40:10.706449763+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.706503214+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.706518463+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.706532269+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.70792399+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.707954774+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.708728285+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.708760716+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.708774922+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.708964238+08:00 [INFO] Opening main db
2024-11-05T18:40:10.710474012+08:00 [INFO] perform;
2024-11-05T18:40:10.710498241+08:00 [INFO] authenticate;
2024-11-05T18:40:10.710526748+08:00 [INFO] read_command;
2024-11-05T18:40:10.711030409+08:00 [INFO] socket reader;
2024-11-05T18:40:10.712670013+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:10.715931436+08:00 [INFO] Using Visual { id: 119, colormap: 0, depth: 32 }
2024-11-05T18:40:10.715955185+08:00 [INFO] Creating colormap 136314883
2024-11-05T18:40:10.717439188+08:00 [INFO] new;
2024-11-05T18:40:10.71825367+08:00 [INFO] keep_updated;
2024-11-05T18:40:10.733868223+08:00 [INFO] Enabling Vulkan Portability
2024-11-05T18:40:10.733887307+08:00 [INFO] Enabling color space support
2024-11-05T18:40:10.740456027+08:00 [INFO] Adapter: "Intel(R) UHD Graphics 630 (CML GT2)"
2024-11-05T18:40:10.740707067+08:00 [INFO] No ray tracing extensions are supported
2024-11-05T18:40:10.747604225+08:00 [INFO] Using surface present mode MAILBOX
2024-11-05T18:40:10.747654492+08:00 [WARN] Unable to forbid exclusive full screen
2024-11-05T18:40:10.749091161+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-05T18:40:10.749202627+08:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-11-05T18:40:10.749291649+08:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-11-05T18:40:10.920274305+08:00 [INFO] Refreshing at 16666 micros
2024-11-05T18:40:10.944042828+08:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "Intel(R) UHD Graphics 630 (CML GT2)", driver_name: "Intel open-source Mesa driver", driver_info: "Mesa 24.0.9-0ubuntu0.2" }
2024-11-05T18:40:10.978505696+08:00 [INFO] XConnected server on 29360140, transport version: 0.0, TRANSPORT_MAX: 20
2024-11-05T18:40:10.984892376+08:00 [INFO] set status on client 0: Authenticating
2024-11-05T18:40:10.985221904+08:00 [INFO] perform;
2024-11-05T18:40:10.985244773+08:00 [INFO] authenticate;
2024-11-05T18:40:10.985276889+08:00 [INFO] read_command;
2024-11-05T18:40:10.98582701+08:00 [INFO] socket reader;
2024-11-05T18:40:10.992999504+08:00 [INFO] new;
2024-11-05T18:40:10.993828309+08:00 [INFO] keep_updated;
2024-11-05T18:40:10.996755397+08:00 [INFO] set status on client 188502: Connecting
2024-11-05T18:40:10.996825433+08:00 [INFO] Opening main db
2024-11-05T18:40:11.040592273+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:11.040656788+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:11.040689571+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:11.18094457+08:00 [INFO] Initializing default prettier with plugins {}
2024-11-05T18:40:11.182749313+08:00 [INFO] Opening main db
2024-11-05T18:40:11.182779693+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:11.183783246+08:00 [ERROR] no worktrees when constructing ProjectLspAdapterDelegate
2024-11-05T18:40:11.213466016+08:00 [INFO] Initializing default prettier with plugins {}
2024-11-05T18:40:11.214255568+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:11.262637279+08:00 [INFO] Initializing default prettier with plugins {}
2024-11-05T18:40:11.306204794+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:11.716354179+08:00 [INFO] Initializing default prettier with plugins {}
2024-11-05T18:40:11.716894462+08:00 [WARN] request completed with error: failed to connect to the server
2024-11-05T18:40:12.004693844+08:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-11-05T18:40:12.805193378+08:00 [INFO] set status on client 188502: UpgradeRequired
2024-11-05T18:40:12.805592029+08:00 [ERROR] upgrade required
2024-11-05T18:40:28.09192449+08:00 [ERROR] window not found
2024-11-05T18:40:28.091973368+08:00 [ERROR] window not found

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-06 07:15
Duplicate of https://github.com/zed-industries/zed/issues/20249

>  [2024-11-05T18:50:04+08:00 ERROR editor] server shut down

The PHP language server crashes in a loop for some reason.
It would be great to get any logs for it, as it's not very clear what's wrong with it.

**Closed by SomeoneToIgnore** 2024-11-06 07:15 UTC
Labels: bug, triage, admin read

**Comment by SomeoneToIgnore** [comment] 2024-11-06 07:20
Alternatively, please share the project we can repro the issue on.

**Comment by RemcoSmitsDev** [comment] 2024-11-06 15:41
@onhao Do you use the **phpactor** language server? I have the same issue at work, because the project is just too big for **phpactor**. When I switched back to the vscode intelephense language server, it was workable again.
