### ISSUE TITLE
Not all dot files offered in open file dialog

### ISSUE THREAD

**Issue by kellyfelkins** [zed-industries/zed#4302] opened 2023-12-20 18:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using the jetbrains keymap. 

1. I do a cmd-shift-o to search for a project file. 
2. I type ".env". As I type the matching files are listed.

I have 2 files in my project, ".envrc" and ".envrc.template". ".envrc.template" is listed. ".envrc" is not listed.

### Environment

Zed: v0.116.1 (stable)
OS: macOS 12.6.7
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="578" alt="Screen Shot 2023-12-20 at 10 47 25 AM" src="https://github.com/zed-industries/community/assets/37887/c718a271-41a9-4dc7-acc9-a0aded26033b">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

<details><summary>Zed.log</summary><pre>
2023-12-14T18:51:16 [INFO] build git repository "deps/snowflex/.git"
2023-12-14T18:51:16 [INFO] build git repository "deps/snowflex/.git"
2023-12-14T18:51:17 [INFO] build git repository "deps/snowflex/.git"
2023-12-14T18:51:17 [INFO] build git repository "deps/snowflex/.git"
2023-12-14T18:51:17 [INFO] build git repository "deps/snowflex/.git"
2023-12-14T19:03:36 [INFO] reload git repository ".git"
2023-12-14T19:03:37 [INFO] reload git repository ".git"
2023-12-14T19:05:45 [INFO] reload git repository ".git"
2023-12-14T19:05:47 [INFO] reload git repository ".git"
2023-12-14T19:05:47 [INFO] reload git repository ".git"
2023-12-14T19:06:00 [INFO] reload git repository ".git"
2023-12-14T19:06:00 [INFO] reload git repository ".git"
2023-12-14T19:06:01 [INFO] reload git repository ".git"
2023-12-14T19:06:01 [INFO] reload git repository ".git"
2023-12-14T19:07:20 [INFO] reload git repository ".git"
2023-12-14T19:07:21 [INFO] reload git repository ".git"
2023-12-14T19:07:21 [INFO] reload git repository ".git"
2023-12-14T19:07:21 [INFO] reload git repository ".git"
2023-12-14T19:07:21 [INFO] reload git repository ".git"
2023-12-14T19:07:23 [INFO] reload git repository ".git"
2023-12-14T19:07:23 [INFO] reload git repository ".git"
2023-12-14T19:07:38 [INFO] reload git repository ".git"
2023-12-14T19:07:39 [INFO] reload git repository ".git"
2023-12-14T19:07:39 [INFO] reload git repository ".git"
2023-12-14T19:18:07 [WARN] request completed with error: request or operation took longer than the configured timeout time
2023-12-14T19:18:07 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2023-12-14T20:25:28 [WARN] request completed with error: request or operation took longer than the configured timeout time
2023-12-14T20:25:28 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2023-12-14T20:55:13 [WARN] request completed with error: request or operation took longer than the configured timeout time
2023-12-14T20:55:13 [ERROR] request or operation took longer than the configured timeout time

Caused by:
    [28] Timeout was reached
2023-12-14T20:57:56 [INFO] reload git repository ".git"
2023-12-14T20:57:56 [INFO] reload git repository ".git"
2023-12-14T20:57:58 [INFO] reload git repository ".git"
2023-12-14T20:57:58 [INFO] reload git repository ".git"
2023-12-14T20:58:01 [INFO] reload git repository ".git"
2023-12-14T20:58:04 [INFO] reload git repository ".git"
2023-12-14T20:58:04 [INFO] reload git repository ".git"
2023-12-14T20:58:04 [INFO] reload git repository ".git"
2023-12-14T20:58:04 [INFO] reload git repository ".git"
2023-12-14T20:58:05 [INFO] reload git repository ".git"
2023-12-14T20:58:05 [INFO] reload git repository ".git"
2023-12-14T20:58:05 [INFO] reload git repository ".git"
2023-12-14T20:58:05 [INFO] reload git repository ".git"
2023-12-14T20:58:05 [INFO] reload git repository ".git"
2023-12-14T20:58:05 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:06 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:07 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:08 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:09 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:10 [INFO] reload git repository ".git"
2023-12-14T20:58:11 [INFO] reload git repository ".git"
2023-12-14T20:58:11 [INFO] reload git repository ".git"
</pre></details>

**Comment by notpeter** [comment] 2024-06-24 18:07
Hi @kellyfelkins Can you confirm you are still seeing this issue?

I was able to reproduce your issue (certain dot files not suggested) but only if those files were matched by `.gitignore` rules.  Does this match your configuration?

**Comment by notpeter** [comment] 2024-08-16 20:14
Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/4745

**Closed by notpeter** 2024-08-16 20:14 UTC
Labels: defect, file finder
