### ISSUE TITLE
Loading a 1.8 GB json file crashes the OS

### ISSUE THREAD

**Issue by jnathanh** [zed-industries/zed#8680] opened 2024-03-01 16:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Not sure if this is the same memory issue, but I also ran into a memory spike issue. Was trying the editor for the first time and was curious how it would handle opening a large file (1.8 GB json). The app quickly froze up and stopped responding, was using at least 17GB memory, and eventually crashed the OS (I'm on an 8GB system).

I generated the file with this script
```bash
object_size=12
num_objects=$((1024*1024*1024 / $object_size))
output_file=~/Downloads/output.json
{
  printf "[\n"
  for ((i=1; i<num_objects; i++)); do
    printf "{\"data\": \"%d\"},\n" "$i"
  done
  printf "{}\n"
  printf "]\n"
} > "$output_file"
```
<img width="446" alt="Screenshot 2024-02-27 at 6 36 46 PM" src="https://github.com/zed-industries/zed/assets/3442984/be09e422-8470-44d7-a419-a20bca48771c">

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.3.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I think the first priority would be preventing the app from becoming unresponsive (so you could close the file and prevent an OS crash). Ideally zed would control its memory usage to a reasonable level based on what's available on the system. Also, my expectation was that Zed would excel at opening a large file since performance is on of the main features advertised.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-27T10:40:17-08:00 [INFO] ========== starting zed ==========
2024-02-27T10:40:17-08:00 [INFO] Opening main db
2024-02-27T10:40:17-08:00 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-27T10:40:17-08:00 [ERROR] crates/extension/src/extension_store.rs:182: No such file or directory (os error 2)
2024-02-27T10:40:17-08:00 [ERROR] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
2024-02-27T10:40:17-08:00 [INFO] Opening main db
2024-02-27T10:40:18-08:00 [ERROR] crates/zed/src/main.rs:957: Is a directory (os error 21)
2024-02-27T10:40:18-08:00 [ERROR] crates/zed/src/main.rs:957: Is a directory (os error 21)
2024-02-27T10:40:19-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:40:20-08:00 [INFO] set environment variables from shell:/opt/homebrew/bin/bash, path:/var/folders/qg/vcff644x2fv9842kh2zy75j00000gn/T/frum_83905_1709059220389/bin:/Users/nathan/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nathan/go/bin:/Users/nathan/.cargo/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin/:/Users/nathan/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
2024-02-27T10:40:28-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-27T18:40:28.565Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-02-27T18:40:28.565Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-02-27T10:40:28-08:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "561275e9-e2d5-4717-a548-eee5e9a46963",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-02-27T10:40:28-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-27T18:40:28.574Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-02-27T18:40:28.574Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-02-27T10:46:27-08:00 [INFO] build git repository ".git"
2024-02-27T10:46:47-08:00 [INFO] Opening main db
2024-02-27T10:46:47-08:00 [INFO] starting language server "gopls", path: "/Users/nathan/src/replacements-com-scraper", id: 1
2024-02-27T10:47:00-08:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:00-08:00 [INFO] starting language server "vscode-html-language-server", path: "/Users/nathan/src/replacements-com-scraper", id: 2
2024-02-27T10:47:00-08:00 [INFO] starting language server "tailwindcss-language-server", path: "/Users/nathan/src/replacements-com-scraper", id: 3
2024-02-27T10:47:00-08:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:00-08:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:00-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:08-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:08-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:09-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:10-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:10-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:10-08:00 [INFO] Fetching default prettier and plugins: [("prettier-plugin-tailwindcss", "0.5.11"), ("prettier", "3.2.5")]
2024-02-27T10:47:11-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:12-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:15-08:00 [INFO] Initialized prettier with plugins: {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:16-08:00 [INFO] Node runtime install_if_needed
2024-02-27T10:47:25-08:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:25-08:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:25-08:00 [INFO] Initializing default prettier with plugins {"prettier-plugin-tailwindcss"}
2024-02-27T10:47:27-08:00 [INFO] 2 unhandled notification workspace/diagnostic/refresh:
null
2024-02-27T10:47:49-08:00 [ERROR] crates/gpui/src/window.rs:416: window not found
2024-02-27T10:47:49-08:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-02-27T10:47:49-08:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-02-27T10:47:49-08:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-02-27T18:09:38-08:00 [INFO] Got instance handshake
2024-02-27T18:09:59-08:00 [ERROR] crates/gpui/src/window.rs:416: window not found
2024-02-27T18:10:04-08:00 [INFO] ========== starting zed ==========
2024-02-27T18:10:04-08:00 [INFO] Opening main db
2024-02-27T18:10:04-08:00 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-27T18:10:04-08:00 [ERROR] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
2024-02-27T18:10:04-08:00 [INFO] Opening main db
2024-02-27T18:10:05-08:00 [INFO] Node runtime install_if_needed
2024-02-27T18:10:08-08:00 [INFO] set environment variables from shell:/opt/homebrew/bin/bash, path:/var/folders/qg/vcff644x2fv9842kh2zy75j00000gn/T/frum_13852_1709086207800/bin:/Users/nathan/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nathan/go/bin:/Users/nathan/.cargo/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin/:/Users/nathan/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/var/folders/qg/vcff644x2fv9842kh2zy75j00000gn/T/frum_89480_1707966038348/bin:/Users/nathan/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nathan/go/bin:/Users/nathan/.cargo/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/usr/local/bin/:/Users/nathan/bin
2024-02-27T18:10:10-08:00 [INFO] Opening main db
2024-02-27T18:10:12-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-28T02:10:12.790Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-02-28T02:10:12.790Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-02-27T18:10:12-08:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "892469b9-6b76-4266-8b86-5624942b6fb1",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-02-27T18:10:12-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-28T02:10:12.798Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-02-28T02:10:12.798Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-02-27T18:10:24-08:00 [INFO] Initializing default prettier with plugins {}
2024-02-27T18:10:24-08:00 [INFO] starting language server "json-language-server", path: "/Users/nathan/Documents/data/replacements.com/normalized-flatware.jsonl", id: 1
2024-02-27T18:10:25-08:00 [INFO] Node runtime install_if_needed
2024-02-27T18:10:26-08:00 [INFO] Node runtime install_if_needed
2024-02-27T18:10:29-08:00 [INFO] Node runtime install_if_needed
2024-02-27T18:10:51-08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-27T18:11:25-08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-27T18:11:27-08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-27T18:11:41-08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-27T18:11:41-08:00 [ERROR] crates/editor/src/editor.rs:7362: Unhandled method textDocument/definition
2024-02-27T18:11:44-08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-27T18:11:46-08:00 [INFO] Opening main db
2024-02-27T18:12:08-08:00 [ERROR] crates/terminal_view/src/terminal_view.rs:424: error upgrading view
2024-02-27T18:12:19-08:00 [ERROR] crates/terminal_view/src/terminal_view.rs:424: error upgrading view
2024-02-27T18:18:08-08:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-02-27T18:18:08-08:00 [ERROR] crates/project/src/project.rs:4606: Unhandled method workspace/symbol
2024-02-27T18:20:14-08:00 [ERROR] crates/assistant/src/assistant_panel.rs:3052: project is not permissioned for semantic indexing
2024-02-27T18:23:09-08:00 [ERROR] crates/assistant/src/assistant_panel.rs:3052: project is not permissioned for semantic indexing
2024-02-27T18:26:15-08:00 [ERROR] crates/assistant/src/assistant_panel.rs:3052: project is not permissioned for semantic indexing
2024-02-27T18:35:54-08:00 [INFO] Initializing default prettier with plugins {}
2024-02-27T18:35:54-08:00 [INFO] starting language server "json-language-server", path: "/Users/nathan/Downloads/output.json", id: 2
2024-02-27T19:22:22-08:00 [INFO] ========== starting zed ==========
2024-02-27T19:22:22-08:00 [INFO] Opening main db
2024-02-27T19:22:23-08:00 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-27T19:22:23-08:00 [ERROR] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
2024-02-27T19:22:23-08:00 [INFO] Opening main db
2024-02-27T19:22:23-08:00 [INFO] build git repository ".git"
2024-02-27T19:22:23-08:00 [INFO] Opening main db
2024-02-27T19:22:23-08:00 [INFO] Opening main db
2024-02-27T19:22:23-08:00 [INFO] Node runtime install_if_needed
2024-02-27T19:22:23-08:00 [INFO] starting language server "gopls", path: "/Users/nathan/src/replacements-com-scraper", id: 1
2024-02-27T19:22:29-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-28T03:22:29.383Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-02-28T03:22:29.383Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-02-27T19:22:29-08:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "61d66a3f-b687-4cf6-be71-746a8f6823b2",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-02-27T19:22:29-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-02-28T03:22:29.395Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-02-28T03:22:29.395Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-02-27T19:22:30-08:00 [INFO] set environment variables from shell:/opt/homebrew/bin/bash, path:/var/folders/qg/vcff644x2fv9842kh2zy75j00000gn/T/frum_2181_1709090549748/bin:/Users/nathan/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nathan/go/bin:/Users/nathan/.cargo/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin/:/Users/nathan/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
2024-02-27T19:24:44-08:00 [ERROR] crates/gpui/src/window.rs:416: window not found
2024-02-27T19:24:44-08:00 [ERROR] crates/lsp/src/lsp.rs:648: oneshot canceled
2024-03-01T08:51:13-08:00 [INFO] ========== starting zed ==========
2024-03-01T08:51:13-08:00 [INFO] Opening main db
2024-03-01T08:51:13-08:00 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-03-01T08:51:13-08:00 [ERROR] crates/zed/src/zed.rs:524: EOF while parsing a value at line 1 column 0
2024-03-01T08:51:13-08:00 [INFO] Opening main db
2024-03-01T08:51:13-08:00 [INFO] build git repository ".git"
2024-03-01T08:51:13-08:00 [INFO] Opening main db
2024-03-01T08:51:13-08:00 [INFO] Opening main db
2024-03-01T08:51:13-08:00 [INFO] starting language server "gopls", path: "/Users/nathan/src/replacements-com-scraper", id: 1
2024-03-01T08:51:13-08:00 [INFO] Node runtime install_if_needed
2024-03-01T08:51:14-08:00 [INFO] set environment variables from shell:/opt/homebrew/bin/bash, path:/var/folders/qg/vcff644x2fv9842kh2zy75j00000gn/T/frum_9777_1709311874591/bin:/Users/nathan/.nvm/versions/node/v18.14.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/nathan/go/bin:/Users/nathan/.cargo/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin/:/Users/nathan/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
2024-03-01T08:51:22-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-01T16:51:22.249Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-03-01T16:51:22.249Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-03-01T08:51:22-08:00 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "cad0683f-92ae-4694-b27f-00d63eb66f88",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-03-01T08:51:22-08:00 [INFO] 0 unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-03-01T16:51:22.259Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-03-01T16:51:22.259Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-03-01T08:51:27-08:00 [INFO] downloaded update. path:"/var/folders/qg/vcff644x2fv9842kh2zy75j00000gn/T/zed-auto-update1QuBeL/Zed.dmg"

**Comment by Moshyfawn** [comment] 2024-03-01 18:25
Let's bundle this issue with another big file manipulation panic. We can reopen this if we find it's unrelated.

Be sure to +👍 the other thread and feel free to add any additional information.

Duplicate of #8057.

**Comment by Moshyfawn** [comment] 2024-03-01 18:26
Duplicate of #8057.

**Comment by Moshyfawn** [comment] 2024-03-01 18:26
Duplicate of #8057.

**Closed by Moshyfawn** 2024-03-01 18:26 UTC
Labels: defect, triage, panic / crash, admin read
