### ISSUE TITLE
Corrupted view when opening large files

### ISSUE THREAD

**Issue by yay** [zed-industries/zed#17718] opened 2024-09-11 17:01 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed opens this huge ~5GB CSV file http://prod.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-complete.csv from https://www.gov.uk/government/statistical-data-sets/price-paid-data-downloads

But once I scroll halfway through it, the output is corrupted:

<img width="1282" alt="Screenshot 2024-09-11 at 5 55 52 PM" src="https://github.com/user-attachments/assets/ec95dd0a-5ff0-4792-86c4-d3765236f87e">

### Environment

Zed: v0.152.3 (Zed)
OS: macOS 15.0.0 
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

[Zed.log](https://github.com/user-attachments/files/16966996/Zed.log)

**Comment by osiewicz** [comment] 2024-09-12 02:12
Thanks for the report; this is a duplicate of https://github.com/zed-industries/zed/issues/5355

**Closed by osiewicz** 2024-09-12 02:12 UTC
Labels: defect, triage, admin read

**Comment by yay** [comment] 2024-09-12 09:34
Ah, sorry, didn't see this one in my search.
