### ISSUE TITLE
Github Copilot pop up unresponsive and wont go away after opened

### ISSUE THREAD

**Issue by elaminy** [zed-industries/zed#9663] opened 2024-03-21 19:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

press on the github copilot icon in the bottom right

### Environment

Macbook air m1 running macOS Sonoma 14.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/127810733/50adf5cc-a889-4b40-bf9a-c4974c79293a

**Comment by Moshyfawn** [comment] 2024-03-21 19:45
This has been fixed in [`0.128.1`](https://zed.dev/releases/preview/0.128.1).

Duplicate of
- #9596

**Closed** 2024-03-21 19:46 UTC
Labels: defect, triage, admin read

**Comment by elaminy** [comment] 2024-03-21 19:55
@Moshyfawn oops sorry i wasnt aware of that, thanks!

**Comment by Moshyfawn** [comment] 2024-03-21 19:56
> @Moshyfawn oops sorry i wasnt aware of that, thanks!

Np!

**Comment by elaminy** [comment] 2024-03-21 19:58
one last thing, how often does the preview release form into a new "stable" release?

**Comment by Moshyfawn** [comment] 2024-03-21 20:09
> one last thing, how often does the preview release form into a new "stable" release? 

From what I know, it may vary (I'll have to double check), but generally it's around 2 weeks, I believe.
