### ISSUE TITLE
move tmp files to sub directory

### ISSUE THREAD

**Issue by sunliang711** [zed-industries/zed#13772] opened 2024-07-03 11:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hi,I found a lot of tmp files in ~/.config/zed named .tmpXXX, could you move them to a sub directory or other location, because I want to sync ~/.config/zed directory with other Mac

<img width="1765" alt="image" src="https://github.com/zed-industries/zed/assets/16303258/7b6b4310-0d95-4978-93c6-891d4c8259ee">

**Comment by JosephTLyons** [comment] 2024-07-08 17:42
Hey @sunliang711,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7155

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-08 17:42 UTC
Labels: enhancement, macOS
