### ISSUE TITLE
Windows 11 24H2 run zed release after build just flash and off

### ISSUE THREAD

**Issue by aycact** [zed-industries/zed#18740] opened 2024-10-04 16:22 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Windows 11 24H2 Enterprise installed on REFS instead of NTFS run zed after cargo build --release from zed->target->release just flash up the terminal and then off although it still exist in task manager
Last Windows install on 23H2 and NTFS still worked normally

### Environment

Device name	AYCLQT-LAPTOP
Processor	AMD Ryzen 5 5500U with Radeon Graphics            2.10 GHz
Installed RAM	24,0 GB (21,8 GB usable)
Device ID	70F026ED-2DD2-4D21-B78B-891C34F85506
Product ID	00328-90000-00000-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Enterprise
Version	24H2
Installed on	‎29/‎09/‎2024
OS build	26100.1876
Experience	Windows Feature Experience Pack 1000.26100.23.0

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/77f07cbb-f8f8-4e66-bb2d-e38599ccab5b)

**Comment by thelazurite-cell** [comment] 2024-10-04 16:37
also happening for me on a windows 11 machine. I think it's something to do with the new changes around theme background colors
[2024-10-04T17:34:51+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-04T17:34:52+01:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE | INHERIT
[2024-10-04T17:34:52+01:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE | INHERIT
[2024-10-04T17:34:52+01:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE | INHERIT
[2024-10-04T17:34:52+01:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-04T17:34:52+01:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-10-04T17:34:52+01:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }
[2024-10-04T17:34:52+01:00 ERROR assistant] no worktrees when constructing LocalLspAdapterDelegate

**Comment by aycact** [comment] 2024-10-04 16:40
I think it is this issue #18705

**Comment by thelazurite-cell** [comment] 2024-10-04 16:57
Yeah, that seems to line up. I think this may be the same issue as described in #18610 also?

**Comment by aycact** [comment] 2024-10-04 17:01
> Yeah, that seems to line up. I think this may be the same issue as described in #18610 also?
Yes, it is. #18705 is to fix #18610, what we can do now is wait for merge pull request from #18705

**Comment by notpeter** [comment] 2024-10-04 18:55
Closing as duplicate of 
- #18610.

**Closed by notpeter** 2024-10-04 18:55 UTC
Labels: defect, triage, admin read
