### ISSUE TITLE
Sidebar flickering as I move mouse over files in left dock

### ISSUE THREAD

**Issue by noClaps** [zed-industries/zed#9114] opened 2024-03-09 18:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/103803129/c9732670-4972-4b70-8f9b-13050b9d8a52

This only seems to happens when there's a lot of files, like there are for this project.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

[Zed.log](https://github.com/zed-industries/zed/files/14547377/Zed.log)

**Comment by Moshyfawn** [comment] 2024-03-09 18:31
I'm going to close this in favour of the existing issue report. Be sure to +👍 and add any additional information that might be missing.

Duplicate of
- #8598

**Closed by Moshyfawn** 2024-03-09 18:31 UTC
Labels: defect, triage, admin read
