### ISSUE TITLE
Image viewer tabs do not correctly watch for file changes

### ISSUE THREAD

**Issue by olegKusov** [zed-industries/zed#15907] opened 2024-08-07 14:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Im using SVN + MacFuse and ZED show me deleted earlier versions of PNG images. For example, we saved test.png, updated test.png file and in editor we see old version of file. VS Code for example show this file correctly

### Environment

Zed: v0.146.5 (Zed)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-09 20:06
Steps to reproduce:
1. Download mario.png and luigi.png
![mario](https://github.com/user-attachments/assets/62875c95-45d6-44f5-abd3-20b7f8aa32ca)
![luigi](https://github.com/user-attachments/assets/454ac527-c82d-4348-801d-1b22154ad174)
2. Open `mario.png` in Zed.
3. From the command line `cp luigi.png mario.png`

Notice Zed still shows the Mario and not the Luigi!

**Comment by Shr1ftyy** [comment] 2024-08-17 06:12
This is happening to me as well. Using the latest version of Zed Preview, and connected to a remote project. See picture below (left is old text, right is current new text, both from the same file)

![Screenshot 2024-08-17 at 3 42 11 PM](https://github.com/user-attachments/assets/d5c6b6ff-8ee0-40c6-b89b-8fd809e27b22)

**Comment by notpeter** [comment] 2024-08-27 21:05
Duplicate of:
- https://github.com/zed-industries/zed/issues/11529

**Closed by notpeter** 2024-08-27 21:05 UTC
Labels: defect, tabs, image viewer
