### ISSUE TITLE
Terminal window spawns for each opened file on Windows

### ISSUE THREAD

**Issue by everdrone** [zed-industries/zed#21307] opened 2024-11-28 22:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- open a rust project
- cycle through a couple different files

### Environment

Zed: v0.163.0 (Zed Dev 9454f0f1c7361da0344c5c9c3d876084cda1772b)
OS: Windows 10.0.22631
Memory: 63.1 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 4090 || NVIDIA || 566.14

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/cebdbe8c-92a3-4c71-b0f3-f2ca7905d9ab

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by VdanielVPL** [comment] 2024-11-28 22:51
This has been fixed in 95ace03. You can pull the commits and rebuild.

**Closed** 2024-11-28 23:01 UTC
Labels: bug, triage, admin read

**Comment by Moshyfawn** [comment] 2024-11-28 23:02
Duplicate of:
- #18447
