### ISSUE TITLE
Zed stops audio message playback in Signal

### ISSUE THREAD

**Issue by mxlje** [zed-industries/zed#14742] opened 2024-07-18 14:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This seems like a bit of a strange one and it took me a while to figure out this was actually Zed related, I thought it was just a bug in Signal at first.

When I play an audio message in Signal and then switch windows to go to Zed, the audio playback of the message stops. This is not the case with other apps, I can happily switch to any other app from Signal and playback continues. Playback also stops when I switch from any other app back to Zed.

This does not impact "global" audio playback (if there is such a thing, I’m not familiar with the APIs), but Music, Spotify, YouTube etc. all continue playing just fine.

Steps to reproduce:
1. have an audio message in Signal for Mac (doesn’t matter if you sent or received it)
2. start playback
3. switch apps to zed
4. playback of the message stops (but obviously shouldn’t)

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 24 GiB
Architecture: aarch64

**Comment by isosphere** [comment] 2024-07-18 16:33
Not reproducable on Debian Bookworm with Zed 0.144.3 and Signal 7.16.0.

**Comment by notpeter** [comment] 2024-07-19 20:32
I don't think this is Zed specific. On MacOS, I shutdown zed completely and observe this behavior when switching from Signal Desktop to other apps (Chrome, Slack) whereas some apps (Finder, Preview, Spotify, Discord, VScode) audio keeps playing just fine.

I could not reproduce the behavior with Zed, but I totally believe that you've observed it.  Not sure if there's anything we can do to fix this, but open to suggestions.

**Comment by notpeter** [comment] 2024-09-03 13:34
I'm going to close this as I believe it's actually a Signal-specific issue rather than a Zed specific one given that Chrome and Slack also trigger the same behavior.  If anyone discovers what is actually triggers this pause event, we'd be happy to review PRs.

Thanks for reporting @mxlje.

**Closed by notpeter** 2024-09-03 13:34 UTC
Labels: defect, macOS, audio
