### ISSUE TITLE
opengl when?

### ISSUE THREAD

**Issue by TadaHrd** [zed-industries/zed#14665] opened 2024-07-17 16:28 UTC
### Check for existing issues

- [ ] Completed

### Describe the feature

opengl

**Comment by MarcelskyXD** [comment] 2024-07-17 16:39
i agree, my gpu doesnt support vulkan 1.3 i need it

**Comment by someone13574** [comment] 2024-07-17 19:15
Duplicate of https://github.com/zed-industries/zed/issues/13305

**Closed** 2024-07-17 19:18 UTC
Labels: enhancement, triage, admin read
