### ISSUE TITLE
Using legacy mac with newer mac os fails with the gpu

### ISSUE THREAD

**Issue by DonPavlov** [zed-industries/zed#7353] opened 2024-02-04 08:58 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

i am running a macbook 5,3 and am having issues running zed with it under Monterey.
The editor does not even open up. and closes again instantly.
I used open core legacy patcher to run a newer MacOS version with it. Else i would not be able to run the editor at all.
To be honest i only updated it to run Zed, which requires 10.15 to be able to run, and i previously had 10.14 running on it....

### Environment

Editor does not even start....
Modellname:	MacBook Pro
  Modell-Identifizierung:	MacBookPro5,3
  Prozessortyp:	Intel Core 2 Duo
  Prozessorgeschwindigkeit:	2,66 GHz

Systemversion:	macOS 12.7.3 (21H1015)
  Kernel-Version:	Darwin 21.6.0
  Startvolume:	main
  Startmodus:	Normal

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-02-03T21:34:11 [INFO] ========== starting zed ==========
2024-02-03T21:34:11 [INFO] Opening main db
2024-02-03T21:34:11 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
2024-02-03T21:34:12 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:12 [ERROR] crates/zed/src/main.rs:611: No such file or directory (os error 2)
2024-02-03T21:34:13 [ERROR] crates/zed/src/zed.rs:535: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:13 [INFO] Opening main db
2024-02-03T21:34:13 [ERROR] unable to access a compatible graphics device
2024-02-03T21:34:19 [INFO] ========== starting zed ==========
2024-02-03T21:34:19 [INFO] Opening main db
2024-02-03T21:34:19 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
2024-02-03T21:34:19 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:19 [ERROR] crates/zed/src/main.rs:611: No such file or directory (os error 2)
2024-02-03T21:34:19 [ERROR] crates/zed/src/zed.rs:535: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:19 [INFO] Opening main db
2024-02-03T21:34:19 [ERROR] unable to access a compatible graphics device
2024-02-03T21:34:40 [INFO] ========== starting zed ==========
2024-02-03T21:34:40 [INFO] Opening main db
2024-02-03T21:34:40 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
2024-02-03T21:34:41 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:41 [ERROR] crates/zed/src/main.rs:611: No such file or directory (os error 2)
2024-02-03T21:34:41 [ERROR] crates/zed/src/zed.rs:535: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:41 [INFO] Opening main db
2024-02-03T21:34:42 [ERROR] unable to access a compatible graphics device
2024-02-03T21:34:46 [INFO] ========== starting zed ==========
2024-02-03T21:34:46 [INFO] Opening main db
2024-02-03T21:34:47 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
2024-02-03T21:34:47 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:47 [ERROR] crates/zed/src/main.rs:611: No such file or directory (os error 2)
2024-02-03T21:34:47 [ERROR] crates/zed/src/zed.rs:535: EOF while parsing a value at line 1 column 0
2024-02-03T21:34:47 [INFO] Opening main db
2024-02-03T21:34:47 [ERROR] unable to access a compatible graphics device
2024-02-04T08:41:34 [INFO] ========== starting zed ==========
2024-02-04T08:41:34 [INFO] Opening main db
2024-02-04T08:41:34 [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
2024-02-04T08:41:34 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-02-04T08:41:35 [ERROR] crates/zed/src/main.rs:611: No such file or directory (os error 2)
2024-02-04T08:41:35 [ERROR] crates/zed/src/zed.rs:535: EOF while parsing a value at line 1 column 0
2024-02-04T08:41:35 [INFO] Opening main db
2024-02-04T08:41:35 [ERROR] unable to access a compatible graphics device

**Comment by maxdeviant** [comment] 2024-02-05 21:04
It seems like this error is the cause:

> 2024-02-03T21:34:13 [ERROR] unable to access a compatible graphics device

We log this error when we can't detect a Metal device:

https://github.com/zed-industries/zed/blob/a80a3b8706b83e70476ed4a89252b3324edfb391/crates/gpui/src/platform/mac/metal_renderer.rs#L50-L55

@DonPavlov Could you follow the steps [here](https://support.apple.com/en-us/102894#:~:text=Press%20and%20hold%20the%20Option,the%20version%20of%20Metal%20supported.) and share what version of Metal your Mac supports?

**Comment by DonPavlov** [comment] 2024-02-25 20:09
I am not sure it supports metal at all. As mentioned it is a legacy mac. A macbook Pro 5,3
NVIDIA GeForce 9400M:

  Chipsatz-Modell:	NVIDIA GeForce 9400M
  Typ:	GPU
  VRAM (gesamt):	256 MB
  Hersteller:	NVIDIA (0x10de)
  Geräte-ID:	0x0863
  Versions-ID:	0x00b1
  ROM-Version:	3448
  Automatischer Wechsel der Grafikmodi:	Unterstützt
  gMux-Version:	1.8.8

So maybe that might be the simple answer.

**Comment by nicklayb** [comment] 2024-03-15 16:41
I'm having the same problem, I know for a fact that my mac doesn't have Metal support. 

```
AMD Radeon HD 6770M:

  Chipset Model:	AMD Radeon HD 6770M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	512 MB
  Vendor:	AMD (0x1002)
  Device ID:	0x6740
  Revision ID:	0x0000
  ROM Revision:	113-C0170F-170
  VBIOS Version:	113-C2950100-102
  EFI Driver Version:	01.00.544
  Displays:
iMac:
  Display Type:	LCD
  Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
  UI Looks like:	2560 x 1440
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
```

**Comment by sharpchunks** [comment] 2024-03-17 22:48
Tested on MacBook Pro 7,1 (mid 2010), same issue.

Graphics adapter info:
```NVIDIA GeForce 320M:

  Chipset Model:	NVIDIA GeForce 320M
  Type:	GPU
  VRAM (Total):	256 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x08a0
  Revision ID:	0x00a2
  ROM Revision:	3533
  Displays:
Colour LCD:
  Display Type:	LCD
  Resolution:	1280 x 800
  UI Looks like:	1280 x 800
  Framebuffer Depth:	24-Bit Colour (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal
```

**Comment by djotto** [comment] 2024-05-25 18:04
Ditto, 2013 MBP with Sonama hacked on to it via OpenCore Legacy Patcher.

2.3 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2 GB
Intel Iris Pro 1536 MB
Sonama 14.4.1 (23E224)

Obivously not expecting a fix for this completely unsupported setup, just adding it as a data point.

**Comment by notpeter** [comment] 2024-11-04 01:21
I'm going to go ahead and close this.  Zed currently require a GPU which supports Metal2 on MacOS and a GPU which supports Vulkan on Linux. Sorry.

**Closed by notpeter** 2024-11-04 01:21 UTC
Labels: defect, macOS
