### ISSUE TITLE
Windows: Prisma language server path resolve is broken 

### ISSUE THREAD

**Issue by gituser-rs** [zed-industries/zed#19524] opened 2024-10-21 20:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When project and LSP is located on different drives extension uses broken path:

```
Language server error: prisma-language-server

oneshot canceled
-- stderr--
node:internal/modules/cjs/loader:1251
  throw err;
  ^

Error: Cannot find module 'E:\C:\Users\wu\AppData\Local\Zed\extensions\work\prisma\node_modules\.bin\prisma-language-server'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:166:5)
    at node:internal/main/run_main_module:30:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.9.0

```

### Environment

Zed: v0.159.0 (Zed Dev 92c29be74cc2ac09dfe0d71d5a1048121b6ab4c6)
OS: Windows 10.0.26100
Memory: 31.6 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2080 || NVIDIA || 565.90

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-22 18:08
Duplicate of https://github.com/zed-industries/zed/issues/12013

**Closed by SomeoneToIgnore** 2024-10-22 18:08 UTC
Labels: defect, windows, language server failure, prisma
