### ISSUE TITLE
[tree] root files should be same indentation as root directories

### ISSUE THREAD

**Issue by lukeed** [zed-industries/zed#4755] opened 2023-05-08 19:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Root-level files should start at the same indentation level as root-level directories.

Currently (Zed 0.84.4), they're indented 1 level, which makes them appear to be part of the last directory's contents. This is shown in the second screenshot, where it's unclear where `util`'s contents ends and the root-level files begin

### Environment

Zed: v0.84.4 (stable)
OS: macOS 12.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="162" alt="Screen Shot 2023-05-08 at 12 34 48 PM" src="https://user-images.githubusercontent.com/5855893/236917029-8ba04552-8ba7-488c-ba75-6fa9468c2cfb.png">
<img width="84" alt="Screen Shot 2023-05-08 at 12 35 48 PM" src="https://user-images.githubusercontent.com/5855893/236917034-ff65d098-5b84-438c-96db-8a7e36ff4b7e.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 06:25
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

<img width="236" alt="SCR-20240728-czsm" src="https://github.com/user-attachments/assets/147353a6-d5ba-4a46-96dd-c2dfdd9ee1d2">

**Closed by JosephTLyons** 2024-07-28 06:25 UTC
Labels: defect, design, project panel
