### ISSUE TITLE
Terminal: ability to split the terminal horizontally

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/zed#10977] opened 2024-04-25 09:53 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Would be great if there was a way to split the terminal vertically, like in other Terminals (VSCode allows it, iTerm on mac, etc...).

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1350" alt="Screenshot 2024-04-25 at 11 51 24" src="https://github.com/zed-industries/zed/assets/199648/7bc91c7b-9538-4c65-ba97-57c47669e4a7">

**Comment by SomeoneToIgnore** [comment] 2024-04-25 11:47
Duplicate of https://github.com/zed-industries/zed/issues/4351

**Closed by SomeoneToIgnore** 2024-04-25 11:47 UTC
Labels: enhancement, triage, admin read
