### ISSUE TITLE
file manager opens behind zed on [save as]

### ISSUE THREAD

**Issue by SamiyelF** [zed-industries/zed#14891] opened 2024-07-21 01:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When saving a new file (or selecting "save file as..."), you are asked to choose a path; this opens the file explorer _behind_ the main Zed window. 
I often dont notice this, and they stack up 
![image](https://github.com/user-attachments/assets/9da60209-044d-44ad-8261-17f0de07ed95)

### Environment

Zed: v0.144.4 (Zed)
OS: Linux X11 zorin 17
Memory: 31.3 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Just want the file explorer to open on top.
![image](https://github.com/user-attachments/assets/154dfc6b-df4f-4927-8cb8-b2517d43bcf2)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by apricotbucket28** [comment] 2024-07-21 11:21
Duplicate of https://github.com/zed-industries/zed/issues/14301, could you thumbs up and comment on that issue?
Also, can you reproduce this issue on Wayland or is it exclusive to X11?

(PS even though the issue is about the open dialogues they work the same way)

**Closed** 2024-07-25 17:52 UTC
Labels: duplicate
