### ISSUE TITLE
save auto format invalid

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#11964] opened 2024-05-17 10:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If the current file has not been modified, but the tab_size setting is different from the current file, turning on Save AutoFormat does not work.

https://github.com/zed-industries/zed/assets/19868292/46e8e015-11d6-4178-82f1-21bb61699c4b

### Environment

Zed: v0.136.0 (Zed Dev 3c0f49b9447b87f9cbad081f307d4432e215aad7)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by 0x2CA** [comment] 2024-05-17 10:18
Also, if you change the value of hard_tabs, reformatting the current file won't work, but it will work for newly typed tabs.

**Comment by 0x2CA** [comment] 2024-05-17 10:19
By the way if I want to reformat the whole project what should I do?

**Comment by notpeter** [comment] 2024-11-05 23:30
If you change your settings.json to alter the tab_size, when you save it triggers prettier to reformat the buffer in question before it writes the file. The file is then written, which triggers Zed to reload the settings.json from the contents of the newly modified file.  The change to the tab_size isn't picked up till the second save.

So closing as duplicate of this:
- https://github.com/zed-industries/zed/issues/16351

For the hard tabs thing: 
- See: https://github.com/zed-industries/zed/issues/19961

And if you want to reformat the whole project, I suggest you run `prettier --write` from the command line.

Thanks for reporting!

**Closed by notpeter** 2024-11-05 23:30 UTC
Labels: bug, triage, editor, setting, admin read
