### ISSUE TITLE
Display issue of large log file

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#22273] opened 2024-12-20 02:39 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening a large log file like, starting from some lines the display is weird. 

The whole file is 50M lines, the issue starts from line 16777217 and lasts for all the following lines.

<img width="1482" alt="image" src="https://github.com/user-attachments/assets/21db267a-9b57-46ac-9d25-700f3228b8ea" />

### Zed Version and System Specs

Zed: v0.167.1 (Zed Preview)
OS: macOS 15.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-12-20 08:37
Duplicate of https://github.com/zed-industries/zed/issues/5355

**Closed by SomeoneToIgnore** 2024-12-20 08:37 UTC
Labels: bug, triage, admin read
