### ISSUE TITLE
Revent projects modal shows action names instead of the bindings

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20411] opened 2024-11-08 13:27 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It happens every time I open Zed without a project open and sometimes when I have a project open.
The message `menu::Confirm appears`...

![image](https://github.com/user-attachments/assets/291cbfb0-8ba3-4631-82a6-c1eb92c9487b)

While the regular view has to be

<img width="571" alt="image" src="https://github.com/user-attachments/assets/95d401b5-e353-4093-a33c-134b41eb09d2">

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-08 14:49
It's not a message but the tooptip inside the picker menu.
It had been there for a long while since https://github.com/zed-industries/zed/pull/7528 at least and helps to indicate that we have two ways to open the window.

So, works as intended and we're not planning to update that.

**Comment by SomeoneToIgnore** [comment] 2024-11-08 14:54
It's an action

**Comment by SomeoneToIgnore** [comment] 2024-11-08 14:54
Ooh, I see, you mean the keybinds are missing compared to previous versions.
It's so hard to understand you all the time, can you write more elaborately?

What's your keymap?

**Comment by SomeoneToIgnore** [comment] 2024-11-08 14:57
https://github.com/zed-industries/zed/blob/8cc3ce1f17a313d60589b8d87207efcfb4100c90/assets/keymaps/default-macos.json#L19-L21

This should come out of that.

If it's the default you have, I cannot reproduce this.
Please provide more details, your entire keymap and the settings.

**Comment by SomeoneToIgnore** [comment] 2024-11-08 15:00
> your entire keymap and the settings

**Comment by SomeoneToIgnore** [comment] 2024-11-08 15:09
To note, I'm pretty clueless as even after applying those two shared jsons instead of my configs, I see the keybindings properly.
I guess we miss something else but I have no clue what.

**Comment by SomeoneToIgnore** [comment] 2024-11-08 15:18
Then we wait for more info or more reports.

Meanwhile, you can check the local build and debug things starting from here (if you can):
https://github.com/zed-industries/zed/blob/8cc3ce1f17a313d60589b8d87207efcfb4100c90/crates/recent_projects/src/recent_projects.rs#L187-L202

Alas, I cannot help much since as stated, 

> even after applying those two shared jsons instead of my configs, I see the keybindings properly.

**Comment by SomeoneToIgnore** [comment] 2024-11-08 15:25
I actually did not, sorry, it was an older Preview that have not been updated for some reason — working Nightly got me confused.
Indeed it broke there but https://github.com/zed-industries/zed/pull/20367 has a fix.

That will come in the next Preview hotfix quite soon today, so I'll close this again.
Sorry for the confusion.

**Closed by SomeoneToIgnore** 2024-11-08 15:25 UTC
Labels: bug, triage, needs info / awaiting response, admin read
