### ISSUE TITLE
Keyboard shortcuts don't work in Cyrillic

### ISSUE THREAD

**Issue by kyborq** [zed-industries/zed#14444] opened 2024-07-14 13:05 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Keyboard shortcuts only work on the English keyboard layout. If you use a different input method, such as Russian (Cyrillic), some combinations, like copy, paste, and the command palette may stop working.

### Environment

Zed: v0.143.7 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 15.4 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Randommist** [comment] 2024-07-15 17:08
I also encountered this problem on Wayland Arch

**Comment by AndyDroid10X** [comment] 2024-07-16 11:55
Duplicate of #14053

**Closed** 2024-07-16 11:58 UTC
Labels: defect, triage, admin read
