### ISSUE TITLE
Tailwind Autocomplete not working in Vuejs

### ISSUE THREAD

**Issue by hbilal9** [zed-industries/zed#8117] opened 2024-02-21 11:48 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Tailwind css autocomplete not working in vuejs, also i expect tag auto renaming

<img width="1148" alt="Screenshot 2024-02-21 at 4 43 51 PM" src="https://github.com/zed-industries/zed/assets/25703314/89e2db38-d67a-4ce4-9fe1-5cb6b772392f">

### Environment

MacOs Sonoma 14.0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SherKhan32** [comment] 2024-02-22 11:55
I am also experiencing this issue.

**Comment by JosephTLyons** [comment] 2024-02-23 17:43
Hey @hbilal9,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4403

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-23 17:43 UTC
Labels: defect, language, tailwind css, vue
