### ISSUE TITLE
The at sign (@) can't be typed in Zed buffer, editor, terminal or chat 

### ISSUE THREAD

**Issue by DiegoHerreraGre** [zed-industries/zed#19099] opened 2024-10-11 21:07 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Maybe it is a small error, even for a rarely used symbol like the at sign @, but I find it quite annoying not being able to write the at sign to send emails. I realized this error configuring nodemailer.

My OS specifications if are needed or useful:

MacOS Sequoia.
M2 Chip.
MacBook Air. 

I tried uninstalling Zed, also tried installing the universal bin. Not luck. 

### Environment

Zed buffer, editor, terminal, chat, etc.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by mikayla-maki** [comment] 2024-10-11 22:50
Are you using a specific keyboard? This works on my personal macbook with the U.S. keyboard layout.

**Comment by DiegoHerreraGre** [comment] 2024-10-11 23:13
> Are you using a specific keyboard or layout? This works on my personal macbook with the U.S. keyboard layout.

Im using LATAM keyboard. I bought this MBA in Chile. To type the at sign we use ctrl-Q.

**Comment by DiegoHerreraGre** [comment] 2024-10-12 00:09
To add some more details, all other special characters like €∑®†¥¨¨ı©ƒ∂≈ç∫~ƒ∂ works just fine in Zed, is only focused on the @ sign…which is weird. I figure maybe there is a keymap or some macros that is embedded with ctrl-Q which would affect LATAM keyboard dist.

**Comment by JosephTLyons** [comment] 2024-10-12 19:45
Hey @DiegoHerreraGre, I think this is a duplicate of:

- https://github.com/zed-industries/zed/issues/18929

So I'm going to close this one out in favor of that one. Feel free to upvote with a 👍.

That being said, there seems to be a workaround mentioned here:

- https://github.com/zed-industries/zed/issues/18607

Let me know if this helps you out.

**Closed by JosephTLyons** 2024-10-12 19:45 UTC
Labels: defect, internationalization

**Comment by DiegoHerreraGre** [comment] 2024-10-12 22:43
> Hey @DiegoHerreraGre, I think this is a duplicate of:
> 
> * [Can't type '@' character on Latin America keyboard #18929](https://github.com/zed-industries/zed/issues/18929)
> 
> So I'm going to close this one out in favor of that one. Feel free to upvote with a 👍.
> 
> That being said, there seems to be a workaround mentioned here:
> 
> * [Cannot insert ‘@’ symbol with Latin American keyboard layout on MacBook Pro after version 0.154.4 #18607](https://github.com/zed-industries/zed/issues/18607)
> 
> Let me know if this helps you out.

Thanks!! These issues resolved my issue. In fact, I was actually putting in bindings alt-q: null but only in Editor context and not the Workspace or Terminal, so I just added the latter and back to normal.
