### ISSUE TITLE
Clicking intellisense JSDoc `@link` unexpectedly opens VS Code

### ISSUE THREAD

**Issue by jaydenseric** [zed-industries/zed#18719] opened 2024-10-04 03:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With this `demo.mjs` file in a TypeScript project:

```js
// @ts-check

/** @typedef {boolean} Foo */

/** {@link Foo} */
const a = true;
```

Hover on the `a`:

<img width="481" alt="Screenshot 2024-10-04 at 1 34 03 pm" src="https://github.com/user-attachments/assets/24e7bde1-c8dc-4420-b651-b7b1bb02994f">

With VS Code also installed, click on the intellisense link `Foo`. Notice that instead of navigating to the target in the Zed editor, VS Code unexpectedly opens to the module (but interestingly not to the relevant location in the module).

### Environment

Zed: v0.156.0 (Zed Preview)
OS: macOS 15.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by vitallium** [comment] 2024-10-04 15:28
I think this is related to https://github.com/zed-industries/zed/issues/18641

**Comment by notpeter** [comment] 2024-10-04 20:19
Yep. I am able to reproduce and I think it's a duplicate of:
- https://github.com/zed-industries/zed/issues/18641

For me it opens Sublime which is my default association for `.mjs` files.

**Closed by notpeter** 2024-10-04 20:19 UTC
Labels: defect, triage, admin read
