### ISSUE TITLE
installing new dependency does not get recognized

### ISSUE THREAD

**Issue by shahriyardx** [zed-industries/zed#7765] opened 2024-02-14 10:14 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

So when I am working on a python project and install a new dependency, the editor does not recognize that I installed new dependency, so when I write
```py
import x
```

it says cannot resolve x, I have to quit the app and reopen to make it work

### Environment

Zed: v0.121.7 (Zed)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="284" alt="Screenshot 2024-02-14 at 4 13 59 PM" src="https://github.com/zed-industries/zed/assets/40076722/aa5ecbed-e404-40f8-aaed-f242da09beac">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-16 05:12
Hey @shahriyardx,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7296

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-16 05:12 UTC
Labels: defect, python, language
