### ISSUE TITLE
Vim: `vip` and `vap` are not selecting paragraphs

### ISSUE THREAD

**Issue by jacksonSingleton** [zed-industries/zed#8548] opened 2024-02-28 18:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using Vim the command `vip` selects content within a paragraph (CRLF delimited text), and `vap` should select the paragraph with surrounding whitespace. However, in vim mode, this behavior does not occur.,

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![ScreenRecording2024-02-28at12 30 37PM-ezgif com-video-to-gif-converter](https://github.com/zed-industries/zed/assets/17009633/9316ce13-ed81-4fb3-97ae-3d322e8024dd)

GIF shows the functionality working in neovim, and then nothing occurring in Zed.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by jacksonSingleton** [comment] 2024-02-28 18:42
Checked for existing issues, but the initial search didn't catch #7687

**Comment by Moshyfawn** [comment] 2024-02-28 18:44
Duplicate of #7687

**Closed by Moshyfawn** 2024-02-28 18:44 UTC
Labels: defect, vim, admin read
