### ISSUE TITLE
Copilot suggetion labels will remain after disabling suggestions

### ISSUE THREAD

**Issue by PimMeulenkamp** [zed-industries/zed#8995] opened 2024-03-07 09:42 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

# Problem
When disabling suggestions while getting a suggestions, the latest suggestion will stay for evey open

# How to reproduce
1. Get a copilot suggestion
2. Disable suggestions

https://github.com/zed-industries/zed/assets/55128050/3b2f8b9f-4c58-4e93-8204-0fb224281c34

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2024-03-07 at 10 33 27@2x](https://github.com/zed-industries/zed/assets/55128050/c2f244be-916c-4ee6-b487-a31247de6d19)

**Comment by JosephTLyons** [comment] 2024-03-07 18:03
Hey @PimMeulenkamp,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/6793

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-03-07 18:03 UTC
Labels: defect, editor, copilot, ai
