### ISSUE TITLE
An action named `:update` of unknown use in command palette

### ISSUE THREAD

**Issue by g1eny0ung** [zed-industries/zed#14799] opened 2024-07-19 09:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I used the command palette to check for updates, I found an action called `:update`, but nothing happened after I clicked it. Is this a bug?

### Environment

Zed: v0.144.3 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="601" alt="image" src="https://github.com/user-attachments/assets/7e4430da-21dd-43f4-9a0e-a3e2d37760b6">

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-07-19 10:37
Looks like it, but curious to to know more details on how did you get to it.

I see nothing in my Zed 0.144.3:
![image](https://github.com/user-attachments/assets/142b5ad0-9d14-4dda-9dd1-f514bc153d0e)

so a list of plugins, logs and a language you've tried on is interesting to know if you can reliably reproduce this.

**Comment by versecafe** [comment] 2024-07-19 20:34
Doesn't seem to be in the active nightly release or current main when building from source

**Comment by JosephTLyons** [comment] 2024-07-23 18:40
This is strange - but I'm also not seeing it on stable, preview, or nightly - I think we will just close it out and see if it comes up again.

**Closed by JosephTLyons** 2024-07-23 18:40 UTC
Labels: defect, command palette

**Comment by g1eny0ung** [comment] 2024-09-28 15:06
Hi guys, sorry for the late reply. I've already fixed this problem by deleting the config folder in `~/.config/zed` and restart zed. After Zed recreates the config folder, the `:update` disappears from the palette.
