### ISSUE TITLE
Zed search regex does not count newlines as whitespace

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/zed#11531] opened 2024-05-08 03:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With this regex search, I get 33 results:
```
from\('sites'\)
```

If I add `\s` (any whitespace character), I get no results at all:
```
from\('sites'\)\s
```

Just to check, I tried `\S` (any non-whitespace character) as well. The 33 results aren't here either:
```
from\('sites'\)\S
```

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 13.6.4
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="667" alt="image" src="https://github.com/zed-industries/zed/assets/11315492/e5744ede-6e58-4e8a-8820-5926517d29f1">

<img width="675" alt="image" src="https://github.com/zed-industries/zed/assets/11315492/6f5e54dd-709f-43bf-af3c-bbe988923966">

<img width="665" alt="image" src="https://github.com/zed-industries/zed/assets/11315492/bb0e104e-6786-4e9f-a9b9-549c73734d80">

**Comment by notpeter** [comment] 2024-10-29 15:01
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/19184

Which was fixed in:
- https://github.com/zed-industries/zed/pull/19241

Thanks for reporting.

**Closed by notpeter** 2024-10-29 15:01 UTC
Labels: defect, editor, search / project search
