### ISSUE TITLE
A terminal window pops up and disappears immediately

### ISSUE THREAD

**Issue by xgfone** [zed-industries/zed#20569] opened 2024-11-13 05:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On windows, when opening a file, such as a Go or Rust file, a terminal window pops up and disappears immediately.

### Environment

Zed: v0.162.0 (Zed Dev 466d3316a01528c4e7d1fd300e0d19be2b86b465)
OS: Windows 10.0.22631
Memory: 15.7 GiB
Architecture: x86_64
GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
```
</details>
[Zed.log](https://github.com/user-attachments/files/17726934/Zed.log)

**Comment by lca85** [comment] 2024-11-14 02:08
> ### Check for existing issues
> * [x]  Completed
> 
> ### Describe the bug / provide steps to reproduce it
> On windows, when opening a file, such as a Go or Rust file, a terminal window pops up and disappears immediately.
> 
> ### Environment
> Zed: v0.162.0 (Zed Dev [466d331](https://github.com/zed-industries/zed/commit/466d3316a01528c4e7d1fd300e0d19be2b86b465)) OS: Windows 10.0.22631 Memory: 15.7 GiB Architecture: x86_64 GPU: Intel(R) Iris(R) Xe Graphics || Intel Corporation || Intel driver
> 
> ### If applicable, add mockups / screenshots to help explain present your vision of the feature
> _No response_
> 
> ### If applicable, attach your Zed.log file to this issue.
> Zed.log
> [Zed.log](https://github.com/user-attachments/files/17726934/Zed.log)

The same behavior occurs on my Windows 10 PC. Interestingly, I have another PC running Windows 11 with the same version of ZED, but it does not exhibit this behavior.

**Comment by wanlufun** [comment] 2024-11-18 02:07
> Interestingly, I have another PC running Windows 11 with the same version of ZED, but it does not exhibit this behavior.

This issue occurs on my Windows 11 system. I believe it's likely because when Windows launches a subprocess, it also opens a command line window. However, this behavior doesn't happen on Linux or macOS. Ideally, this window should be hidden.
For this issue, I will submit a PR to fix it.

**Comment by SomeoneToIgnore** [comment] 2024-11-18 07:56
Will close it as a duplicate of https://github.com/zed-industries/zed/issues/18371 as the underlying issues is the same.

The PR to fix this is in https://github.com/zed-industries/zed/pull/18447

**Closed by SomeoneToIgnore** 2024-11-18 07:56 UTC
Labels: bug, terminal, windows
