### ISSUE TITLE
Closing one zed instance close all the other instances

### ISSUE THREAD

**Issue by TheSgtPepper23** [zed-industries/zed#17863] opened 2024-09-16 01:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm working on two projects at the same time, so I open a zed instance for each. When Im done with one project and close the window, the window with the other project its closed as well.

### Environment

Zed: v0.152.3 (Zed)
OS: Linux Wayland arch unknown
Memory: 31.3 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3060 Ti || NVIDIA || 560.35.03

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-15T19:18:18.100805654-06:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-09-15T19:18:18.101588873-06:00 [INFO] Enabling Vulkan Portability
2024-09-15T19:18:18.101626684-06:00 [INFO] Enabling color space support
2024-09-15T19:18:18.107939924-06:00 [INFO] Adapter: "NVIDIA GeForce RTX 3060 Ti"
2024-09-15T19:18:18.107995636-06:00 [INFO] Ray tracing is supported
2024-09-15T19:18:18.258036759-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:18.25809284-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:18.263358847-06:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-15T19:18:18.263400068-06:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-15T19:18:18.263436909-06:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-09-15T19:18:18.268333986-06:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 3060 Ti", driver_name: "NVIDIA", driver_info: "560.35.03" }
2024-09-15T19:18:18.268605522-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:18.268645253-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.268683664-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:18.272196349-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:18.274617447-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.274668458-06:00 [INFO] starting language server "gopls", path: "/home/andres/code/GreenLibrary", id: 2
2024-09-15T19:18:18.274783781-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:18.274821242-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:18.282785784-06:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-09-15T19:18:18.287815604-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:18.287857465-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.287895596-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:18.28806531-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.288387598-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:18.288425648-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:18.29512998-06:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-09-15T19:18:18.299773261-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:18.299815162-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.299847743-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:18.299947996-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.300246983-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:18.300266453-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.300284374-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:18.300372006-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.300598701-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:18.300616691-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:18.316925423-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:18.316987585-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:18.317020395-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:18.3180644-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.319169527-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:18.319264949-06:00 [INFO] fetching latest version of language server "gopls"
2024-09-15T19:18:18.731343336-06:00 [INFO] downloading language server "gopls"
2024-09-15T19:18:18.73151469-06:00 [INFO] using CLI environment for language server "gopls", id: 2
2024-09-15T19:18:18.731558261-06:00 [INFO] starting language server. binary path: "/home/andres/.local/share/zed/languages/gopls/gopls_0.16.2", working directory: "/home/andres/code/GreenLibrary", args: ["-mode=stdio"]
2024-09-15T19:18:18.829875812-06:00 [WARN] unhandled capability registration: Registration { id: "workspace/didChangeConfiguration", method: "workspace/didChangeConfiguration", register_options: None }
2024-09-15T19:18:22.123066898-06:00 [ERROR] oneshot canceled
2024-09-15T19:18:26.348817852-06:00 [INFO] ========== starting zed ==========
2024-09-15T19:18:26.380822555-06:00 [INFO] perform;
2024-09-15T19:18:26.380876226-06:00 [INFO] authenticate;
2024-09-15T19:18:26.380947038-06:00 [INFO] read_command;
2024-09-15T19:18:26.380993159-06:00 [INFO] Opening main db
2024-09-15T19:18:26.381265475-06:00 [INFO] new;
2024-09-15T19:18:26.381319056-06:00 [INFO] socket reader;
2024-09-15T19:18:26.381774377-06:00 [INFO] keep_updated;
2024-09-15T19:18:26.382504824-06:00 [INFO] Using git binary path: None
2024-09-15T19:18:26.403073668-06:00 [ERROR] No such file or directory (os error 2) about ["/home/andres/.config/github-copilot"]
2024-09-15T19:18:26.403248542-06:00 [INFO] initializing context server client
2024-09-15T19:18:26.403324854-06:00 [INFO] Registering built-in prompt template: content_prompt
2024-09-15T19:18:26.40355872-06:00 [INFO] Registering built-in prompt template: edit_workflow
2024-09-15T19:18:26.403750704-06:00 [INFO] Registering built-in prompt template: step_resolution
2024-09-15T19:18:26.404075902-06:00 [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-09-15T19:18:26.404217725-06:00 [INFO] No prompt template overrides directory found at /home/andres/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-09-15T19:18:26.404552273-06:00 [INFO] extensions updated. loading 6, reloading 0, unloading 0
2024-09-15T19:18:26.405627109-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.40567265-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.40570948-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.405745361-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.405792002-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.406454448-06:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-09-15T19:18:26.452457889-06:00 [INFO] perform;
2024-09-15T19:18:26.452520741-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.452569592-06:00 [INFO] authenticate;
2024-09-15T19:18:26.452592943-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.452615763-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.452638574-06:00 [INFO] read_command;
2024-09-15T19:18:26.452660514-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.452865209-06:00 [INFO] socket reader;
2024-09-15T19:18:26.455246975-06:00 [INFO] new;
2024-09-15T19:18:26.455587573-06:00 [INFO] keep_updated;
2024-09-15T19:18:26.455626144-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.455719137-06:00 [INFO] Opening main db
2024-09-15T19:18:26.456440644-06:00 [INFO] set status on client 0: Authenticating
2024-09-15T19:18:26.456625368-06:00 [INFO] perform;
2024-09-15T19:18:26.456645468-06:00 [INFO] authenticate;
2024-09-15T19:18:26.456668029-06:00 [INFO] read_command;
2024-09-15T19:18:26.45668909-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.457000937-06:00 [INFO] socket reader;
2024-09-15T19:18:26.459150778-06:00 [INFO] new;
2024-09-15T19:18:26.459515586-06:00 [INFO] keep_updated;
2024-09-15T19:18:26.512188434-06:00 [INFO] Enabling Vulkan Portability
2024-09-15T19:18:26.512215215-06:00 [INFO] Enabling color space support
2024-09-15T19:18:26.517629893-06:00 [INFO] Adapter: "NVIDIA GeForce RTX 3060 Ti"
2024-09-15T19:18:26.517663714-06:00 [INFO] Ray tracing is supported
2024-09-15T19:18:26.55242982-06:00 [INFO] set environment variables from shell:/bin/bash, path:/home/andres/.local/bin:/home/andres/.local/bin:/home/andres/.nvm/versions/node/v20.17.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/go/bin:/usr/local/go/bin
2024-09-15T19:18:26.766426724-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:26.766463355-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:26.77176905-06:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-15T19:18:26.77179177-06:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-15T19:18:26.77180993-06:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-09-15T19:18:26.777711029-06:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce RTX 3060 Ti", driver_name: "NVIDIA", driver_info: "560.35.03" }
2024-09-15T19:18:26.778851206-06:00 [INFO] set status on client 235688: Connecting
2024-09-15T19:18:26.780420913-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.780456894-06:00 [INFO] Opening main db
2024-09-15T19:18:26.781859887-06:00 [INFO] Opening main db
2024-09-15T19:18:26.81899423-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.819354288-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:26.819379099-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:26.825688478-06:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-09-15T19:18:26.830573862-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:26.830595183-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:26.836511642-06:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-09-15T19:18:26.8411191-06:00 [INFO] Using surface present mode MAILBOX
2024-09-15T19:18:26.841140381-06:00 [WARN] Unable to forbid exclusive full screen
2024-09-15T19:18:26.853544173-06:00 [INFO] Node runtime install_if_needed
2024-09-15T19:18:26.853595784-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.853640655-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.853672446-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.857241319-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:26.85727557-06:00 [INFO] starting language server "gopls", path: "/home/andres/code/greenMigration", id: 1
2024-09-15T19:18:26.857356882-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:26.858313974-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.858852547-06:00 [ERROR] No path or contents found for buffer
2024-09-15T19:18:26.862712138-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:26.865622287-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.86575484-06:00 [INFO] fetching latest version of language server "gopls"
2024-09-15T19:18:26.881795827-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:26.882904743-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:26.883022016-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:26.883046326-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:26.883068257-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:26.885221708-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:26.925163527-06:00 [INFO] starting language server. binary path: "/home/andres/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/andres/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-09-15T19:18:26.997636372-06:00 [INFO] downloading language server "gopls"
2024-09-15T19:18:26.997792415-06:00 [INFO] using CLI environment for language server "gopls", id: 1
2024-09-15T19:18:26.997837517-06:00 [INFO] starting language server. binary path: "/home/andres/.local/share/zed/languages/gopls/gopls_0.16.2", working directory: "/home/andres/code/greenMigration", args: ["-mode=stdio"]
2024-09-15T19:18:27.084603492-06:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-09-15T19:18:27.084876968-06:00 [INFO] starting language servers for Go: gopls
2024-09-15T19:18:27.084905929-06:00 [INFO] starting language servers for Shell Script: 
2024-09-15T19:18:27.08492446-06:00 [INFO] starting language servers for Go Mod: gopls
2024-09-15T19:18:27.085899703-06:00 [WARN] request completed with error: failed to connect to the server
2024-09-15T19:18:27.096054701-06:00 [WARN] unhandled capability registration: Registration { id: "workspace/didChangeConfiguration", method: "workspace/didChangeConfiguration", register_options: None }
2024-09-15T19:18:27.211792345-06:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-16T01:18:27.209Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-09-16T01:18:27.209Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-09-15T19:18:27.213178528-06:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "b86f0993-0202-465b-ae38-27f96cd0df72",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-09-15T19:18:27.237738755-06:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-16T01:18:27.217Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-09-16T01:18:27.217Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-09-15T19:18:27.433533958-06:00 [INFO] add connection to peer
2024-09-15T19:18:27.433562089-06:00 [INFO] add_connection;
2024-09-15T19:18:27.4336177-06:00 [INFO] waiting for server hello
2024-09-15T19:18:27.443224365-06:00 [INFO] got server hello
2024-09-15T19:18:27.443253866-06:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 540, id: 8570053 })
2024-09-15T19:18:27.443320848-06:00 [INFO] set status on client 235688: Connected { peer_id: PeerId { owner_id: 540, id: 8570053 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-09-15T19:18:28.421718865-06:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-15T19:18:28.426453425-06:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-09-15T19:18:28.431168746-06:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-09-15T19:18:28.438342624-06:00 [INFO] Creating a descriptor pool for at most 256 sets
</pre></details>

**Comment by notpeter** [comment] 2024-09-16 13:00
I think this may be a duplicate of:
- https://github.com/zed-industries/zed/issues/17684

A user in another thread reported [commented that they are having a similar issue](https://github.com/zed-industries/zed/issues/17129#issuecomment-2350800472):
> `DRI_PRIME=1` comes with a catch. If you have multiple windows open and try to close one of them, zed crashes.

**Closed by notpeter** 2024-09-16 13:00 UTC
Labels: defect, triage, admin read

**Comment by TheSgtPepper23** [comment] 2024-09-16 17:45
@notpeter Thank you! i didnt think of it as a crash,  maybe thats why i didnt find the listed issue.
