### ISSUE TITLE
Keyboard input layout independent hotkeys

### ISSUE THREAD

**Issue by DevNulPavel** [zed-industries/zed#8368] opened 2024-02-25 06:28 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hello

I have custom key bindings for formatting, but it does not work when i change my keyboard language layout from "Eng" to my language

<img width="457" alt="Screenshot 2024-02-25 at 09 28 08" src="https://github.com/zed-industries/zed/assets/14924622/94a7c4ff-2a5f-4b52-9176-dc04adcb2a2c">

**Comment by Moshyfawn** [comment] 2024-02-25 06:38
Possibly related #7688

**Comment by JosephTLyons** [comment] 2024-02-27 18:56
Thanks @Moshyfawn. @DevNulPavel, does #7688 cover what you are mentioning here?

**Comment by DevNulPavel** [comment] 2024-03-17 09:15
> Thanks @Moshyfawn. @DevNulPavel, does #7688 cover what you are mentioning here?

Yes, i think it covers

**Comment by Moshyfawn** [comment] 2024-03-19 21:17
I'll close this issue in favour of the other one, thanks Pavel. Be sure to +👍 and add any missing information.

Duplicate of
- #7688

**Closed by Moshyfawn** 2024-03-19 21:17 UTC
Labels: enhancement, internationalization, keymap / key binding
