### ISSUE TITLE
Update unfolds all folded files and forgets state

### ISSUE THREAD

**Issue by Cheirnomus** [zed-industries/zed#12692] opened 2024-06-05 18:01 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Anytime a Zed update is applied all folds in open text files are unfolded. This same situation is also true when Zed is closed then opened again. VSCode does not have this problem and it remembers it fold state.

Also, when Zed restarts after a update or is opened again it does not automatically recognize .txt files. I need to manually tell Zed that these are Plain Text files. VSCode did not have this issue.

### Environment

This happens on my Mac laptop.

**Comment by JosephTLyons** [comment] 2024-06-05 20:36
Hey @Cheirnomus,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/11626

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-06-05 20:36 UTC
Labels: defect, workspace, serialization
