### ISSUE TITLE
opening file from terminal does not go to correct line

### ISSUE THREAD

**Issue by extrawurst** [zed-industries/zed#4557] opened 2023-08-03 10:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

clicking an compiler error in my terminal (iTerm on Mac) it jut opens the file in Zed but does not go to the right line/colum:

<img width="427" alt="Screenshot 2023-08-03 at 12 52 36" src="https://github.com/zed-industries/community/assets/776816/04ad1bb4-1947-4b1f-a5f5-e2d4daab85fd">

### Environment

Zed: v0.97.5 (stable)
OS: macOS 13.4.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2023-08-03T10:53:53 [INFO] ========== starting zed ==========
2023-08-03T10:53:53 [INFO] Opening main db
2023-08-03T10:53:53 [ERROR] crates/settings/src/keymap_file.rs:86: invalid binding value for keystroke cmd-ctrl-t, context Some("Workspace")

Caused by:
    unknown action semantic_search::Toggle
2023-08-03T10:53:53 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/opt/python@3.9/libexec/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/stephan/.cargo/bin:/Users/stephan/.fzf/bin
2023-08-03T10:53:53 [INFO] Opening main db
2023-08-03T10:53:53 [INFO] build git repository ".git"
2023-08-03T10:53:53 [INFO] Opening main db
2023-08-03T10:53:53 [INFO] installing Node runtime
2023-08-03T10:53:53 [INFO] starting language server "rust-analyzer", path: "/Users/stephan/code/gitui", id: 0
2023-08-03T10:53:54 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "9fe24d66-5e7a-4681-a67b-edc696e6e2c9",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2023-08-03T10:53:54 [INFO] 0 unhandled notification experimental/serverStatus:
{
  "health": "ok",
  "quiescent": false,
  "message": null
}
2023-08-03T10:53:57 [INFO] 0 unhandled notification experimental/serverStatus:
{
  "health": "ok",
  "quiescent": true,
  "message": null
}
2023-08-03T10:54:36 [ERROR] oneshot canceled
2023-08-03T10:54:36 [ERROR] oneshot canceled
2023-08-03T10:54:58 [INFO] ========== starting zed ==========
2023-08-03T10:54:58 [INFO] Opening main db
2023-08-03T10:54:58 [ERROR] crates/settings/src/keymap_file.rs:86: invalid binding value for keystroke cmd-ctrl-t, context Some("Workspace")

Caused by:
    unknown action semantic_search::Toggle
2023-08-03T10:54:58 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/opt/python@3.9/libexec/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/stephan/.cargo/bin:/Users/stephan/.fzf/bin
2023-08-03T10:54:58 [INFO] Opening main db
2023-08-03T10:54:58 [INFO] installing Node runtime
2023-08-03T10:54:58 [INFO] Opening main db
2023-08-03T10:54:58 [INFO] starting language server "rust-analyzer", path: "/Users/stephan/code/gitui/src/components/diff.rs", id: 0
2023-08-03T10:54:59 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "786e9a9f-8583-43df-95ea-f1deadd6fd45",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2023-08-03T10:54:59 [INFO] 0 unhandled notification experimental/serverStatus:
{
  "health": "ok",
  "quiescent": false,
  "message": null
}
2023-08-03T10:55:01 [INFO] 0 unhandled notification experimental/serverStatus:
{
  "health": "ok",
  "quiescent": true,
  "message": null
}
2023-08-03T10:55:02 [ERROR] oneshot canceled
2023-08-03T10:55:02 [ERROR] oneshot canceled
2023-08-03T10:55:20 [INFO] ========== starting zed ==========
2023-08-03T10:55:20 [INFO] Opening main db
2023-08-03T10:55:20 [ERROR] crates/settings/src/keymap_file.rs:86: invalid binding value for keystroke cmd-ctrl-t, context Some("Workspace")

Caused by:
    unknown action semantic_search::Toggle
2023-08-03T10:55:20 [INFO] set environment variables from shell:/bin/zsh, path:/opt/homebrew/opt/python@3.9/libexec/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/stephan/.cargo/bin:/Users/stephan/.fzf/bin
2023-08-03T10:55:20 [INFO] Opening main db
2023-08-03T10:55:20 [INFO] Opening main db
2023-08-03T10:55:20 [INFO] starting language server "rust-analyzer", path: "/Users/stephan/code/gitui/src/components/diff.rs", id: 0
2023-08-03T10:55:20 [INFO] installing Node runtime
2023-08-03T10:55:21 [INFO] 0 unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "eaa830be-5b11-4639-830e-73658fc80d79",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2023-08-03T10:55:21 [INFO] 0 unhandled notification experimental/serverStatus:
{
  "health": "ok",
  "quiescent": false,
  "message": null
}
```

**Comment by JosephTLyons** [comment] 2024-07-28 07:14
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 07:14 UTC
Labels: defect, terminal
