### ISSUE TITLE
linux: Squiggles are thin, not completely smooth and hard to see

### ISSUE THREAD

**Issue by cyberphantom52** [zed-industries/zed#12823] opened 2024-06-09 16:27 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Squiggles are not properly rendered on Linux.

![Screenshot from 2024-06-09 21-55-32](https://github.com/zed-industries/zed/assets/22079654/24a9e773-0052-4d92-80e4-737bf646af37)

![Screenshot from 2024-06-09 21-55-16](https://github.com/zed-industries/zed/assets/22079654/79e9a2e9-a790-4aa8-973a-76e9d27d9512)

### Environment

# System Details Report
---

## Report details
- **Date generated:**                              2024-06-09 21:56:35

## Hardware Information:
- **Hardware Model:**                              ASUSTeK COMPUTER INC. ROG Zephyrus G15 GA503QM_GA503QM
- **Memory:**                                      16.0 GiB
- **Processor:**                                   AMD Ryzen™ 9 5900HS with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            GA503QM.416
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.11-300.fc40.x86_64

**Comment by Moshyfawn** [comment] 2024-06-10 00:43
This seems to be a platform-independent problem, as reported in another thread. I'm going to close this issue in favour of the other one; be sure to +👍 the other thread and add any missing information to it. However, if you feel this is unrelated, feel free to let us know so we can reopen it.

Duplicate of:
- #7436

**Closed by Moshyfawn** 2024-06-10 00:43 UTC
Labels: defect, triage, admin read
