### ISSUE TITLE
horizontal scroll bar might be need

### ISSUE THREAD

**Issue by CharlesChen0823** [zed-industries/zed#12413] opened 2024-05-29 06:21 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

as the title, current zed lack horizontal scroll bar implement.

**Comment by Moshyfawn** [comment] 2024-05-29 15:34
This has already been requested, so I'm going to close this issue to keep the conversation in one place. Be sure to +👍 the other thread.

Duplicate of:
- #4427

**Closed by Moshyfawn** 2024-05-29 15:34 UTC
Labels: enhancement, triage, admin read
