### ISSUE TITLE
Language server agnostic snippets

### ISSUE THREAD

**Issue by failable** [zed-industries/zed#4611] opened 2023-07-21 00:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Other editors have the ability to define snippet without setting up in the LSP. For example, one can still define snippets for editing plain text files and that does not require user to setup initialization options of a LSP. (And we don't generally have a LSP for plain text files.)

Also some snippets might shared across different file types/LSPs.

### If applicable, add mockups / screenshots to help present your vision of the feature

![output](https://github.com/zed-industries/community/assets/5475262/91f85431-98e0-4687-be68-9355c19a6d7f)

**Comment by xtian** [comment] 2024-01-24 18:21
One example use-case is authoring HTML embedded in a string/template within another language. By default, Sublime maps <kbd>Ctrl+W</kbd> to an insert tag snippet which makes this very easy and provides a consistent workflow across languages.

**Comment by miknyko** [comment] 2024-03-13 04:24
Hi, when will this happen?

**Comment by thoreg** [comment] 2024-04-06 05:14
Is there any ongoing work on this feature? Would be happy to join/support here

**Comment by sevignator** [comment] 2024-04-26 15:22
+1 for requesting this feature. It's a huge time saver!

**Comment by Mateiadrielrafael** [comment] 2024-05-01 19:45
A very important feature for me is `luasnip`'s auto snippets. Snippets marked as "auto" will trigger the moment the prefix is typed out, without having to select the snippet in the autocomplete menu and press enter. While this might sound useless, it's super handy when having to type LaTeX quickly (i.e.: when taking live notes during a lecture)

**Comment by osiewicz** [comment] 2024-06-19 12:38
Snippet support is now available as snippet extension in the store. Give it a go!
You can now store your snippets in `~/.config/zed/snippets` subdirectory. Language-agnostic snippets should reside in `snippets.json` file; you can also have snippets that apply only to a specific language, in which case the file should be named after that language (e.g. `python.json`). 
I'd recommend checking out [friendly-snippets](https://github.com/rafamadriz/friendly-snippets) for starters.

Under the hood we use our own [fork](https://github.com/zed-industries/simple-completion-language-server) of [simple-completion-language-server](https://github.com/estin/simple-completion-language-server).

**Comment by JoshDPT** [comment] 2024-06-19 13:02
I have added the zed/snippets/snippets.json - and when I restarted Zed the snippet is showing with typing the prefix in a hovering selector (awesome!)- but when I press enter or click the option it is not populating into the buffer - is there a specific command for populating the snippet from the options?

**Comment by osiewicz** [comment] 2024-06-19 13:06
Can you share your snippets file?

**Comment by JoshDPT** [comment] 2024-06-19 13:14
> Can you share your snippets file? It should work just like normal completions, so you shouldn't have to do anything special.

{
  "getVars": {
    "prefix": "var",
    "body": "${getVars({ name : '' })}"
  }
}

**Comment by osiewicz** [comment] 2024-06-19 13:23
I'm not sure if that's a valid syntax; does it work for you in other editors, e.g. VSC?

**Comment by JoshDPT** [comment] 2024-06-19 13:48
I think it is bad syntax on my part (${} is used for arguments for snippets it looks like)- thanks!

**Comment by osiewicz** [comment] 2024-06-19 15:43
Hey @failable, 
Currently we can only launch a language server for a known subset of languages (we don't have an ability to launch a language server for any file); we've simply missed Dockerfile in [a list](https://github.com/zed-industries/zed/blob/main/extensions/snippets/extension.toml#L11).
I'll try to figure out if we could lift that limitation somehow by the next weeks release; I realize the current approach is not really scalable.

**Comment by ottob** [comment] 2024-06-20 12:27
I copied my snippets over from VS code and they did not show up at first either. But then I validated the json of the file and it had errors. When I had fixed those errors and I restarted Zed, the snippets appeared.

Thanks for adding this feature.

**Comment by fuzenco** [comment] 2024-06-21 17:46
How do we trigger snippets? For instance, here’s one I have:

`{
  "Horizontal Rule": {
    "prefix": "---",
    "body": ["- - - "],
    "description": "Add horizontal rule"
  }
}
`

**Comment by huhu415** [comment] 2024-06-22 01:11
How can I use this feature? I've put the following code in ~/.config/zed/snippets/snippets.json, but it doesn't work..
```
{
"Create new md file": {
    "prefix": "md",
    "body": [
      "+++",
      "title = '$1'",
      "categories = ['LearnOn${2:line}']",
      "tags = ['${3:go}']",
      "date = 2024-$4-$5",
      "draft = true",
      "+++"
    ],
    "description": "Create new md file"
  }
  }
  ```

**Comment by failable** [comment] 2024-06-22 13:36
@fuzenco It seems the current implementation only works if the `prefix` is provided in the completion menu while `prefix`s like `---` are not provided in the menu. 

@osiewicz It would also nice to have customizable key binding to trigger snippets manually.

**Comment by fuzenco** [comment] 2024-06-22 14:42
> @fuzenco It seems the current implementation only works if the `prefix` is provided in the completion menu while `prefix`s like `---` are not provided in the menu.

@failable thanks but where can I find the completion menu?

**Comment by fuzenco** [comment] 2024-06-22 14:51
> > @fuzenco It seems the current implementation only works if the `prefix` is provided in the completion menu while `prefix`s like `---` are not provided in the menu.
> 
> @failable thanks but where can I find the completion menu?

@failable Disregard. I’d been working on newly opened files which I didn’t have language formatting applied to it. Once I saved my file as .md, the snippet appeared. Works very nicely too. Great job Zed team!

**Comment by ivansigmund** [comment] 2024-06-25 09:34
I'm encountering an issue with Zed snippets in LaTeX files. The same snippet works fine in Markdown but fails to trigger when writing LaTeX files. Here's an example:
I've added the following snippet to both markdown.json and latex.json:


> `{ "Horizontal Rule": { "prefix": "---", "body": ["- - - "], "description": "Add horizontal rule" } } `

When writing Markdown files, the snippet triggers as expected. However, when writing LaTeX files, no snippet is triggered at all.
Has anyone else experienced this issue or know how to resolve it? Any help would be appreciated.

**Comment by sci-phi** [comment] 2024-06-25 20:40
I had to **restart Zed** before the snippet in the added `markdown.json` file would work…

**Comment by ivansigmund** [comment] 2024-06-26 09:27
> I had to **restart Zed** before the snippet in the added `markdown.json` file would work…

this works for mardown, but not for latex for me. also i am using the latex extension, maybe there is some clash?

**Comment by osiewicz** [comment] 2024-06-26 09:56
@failable there's a `editor: show completions` action.
@ivansigmund see https://github.com/zed-industries/zed/issues/4611#issuecomment-2179009910, LaTeX has to be added to the list manually for now.

**Comment by failable** [comment] 2024-06-26 09:59
@osiewicz Hello! I mean trigger expansion directly when prefix is inserted instead of showing the completion menu.

**Comment by ivansigmund** [comment] 2024-06-26 11:51
> @failable there's a `editor: show completions` action. @ivansigmund see [#4611 (comment)](https://github.com/zed-industries/zed/issues/4611#issuecomment-2179009910), LaTeX has to be added to the list manually for now.

thanks!

**Comment by ivansigmund** [comment] 2024-06-26 11:54
> @osiewicz Hello! I mean trigger expansion directly when prefix is inserted instead of showing the completion menu.

yes, for example writing --- immediately to show the snippet proposal. it works in markdown as expected, in latex i need to press ctrl-space and then enter

**Comment by ivansigmund** [comment] 2024-06-26 12:07
Issue: Backslashes are removed in snippet expansion

When using the following snippet in Zed:

```json
{
  "equation": {
    "prefix": "BEQ",
    "body": "\\begin{equation}\n\t$0\n\\end{equation}",
    "description": "equation environment"
  }
}
```
Expected behavior:
Typing "BEQ" should expand to:
```
\begin{equation}

\end{equation}
```
Actual behavior:
Typing "BEQ" expands to:
```
begin{equation}

end{equation}
```
The backslashes are missing in the expanded snippet.
Steps to reproduce:

Add the above snippet to Zed
In a new file, type "BEQ" and trigger snippet expansion

Possible cause: The backslashes might be getting escaped or removed during snippet processing.

**Comment by alecmarcus** [comment] 2024-06-27 21:19
@osiewicz Thank you for this! Some things I think would be really useful:

1. The docs should mention the required nomenclature somewhere:
> Hey @failable, Currently we can only launch a language server for a known subset of languages (we don't have an ability to launch a language server for any file); we've simply missed Dockerfile in [a list](https://github.com/zed-industries/zed/blob/main/extensions/snippets/extension.toml#L11). I'll try to figure out if we could lift that limitation somehow by the next weeks release; I realize the current approach is not really scalable.

Took me like 30 minutes of fumbling around locally/searching the web to find your comment and discover how to properly set things up (`.tsx` snippets needing to go in `typescriptreact.json` in particular).

2. Would be great for QoL if servers for superset languages automatically included the snippets of subset languages — for example, I'd expect my `snippets/javascript.json` file to apply to `.ts` files, instead of having to duplicate everything into my `snippets/typescript.json` file. Likewise with `js` → `tsx` and `ts` → `tsx`.

3. Noticed that comments do invalidate JSON here. Not always the case these days so maybe worth calling out

**Comment by brittof** [comment] 2024-07-01 01:40
Is it possible to use variables like in VSCode, like `TM_FILENAME_BASE`? My attempts failed.

**Comment by osiewicz** [comment] 2024-07-01 09:06
@brittof No, not yet. See https://github.com/zed-industries/zed/issues/13456 and https://github.com/zed-industries/zed/issues/13301

**Comment by osiewicz** [comment] 2024-07-01 09:08
Heads up everybody, we're most likely going to deprecate snippets extension and bring it directly into core Zed editor. That way they'll work with all languages out of the box and extensions will be able to provide their own snippets.
It would probably also fix #13636

**Comment by fuzenco** [comment] 2024-07-05 20:01
> Heads up everybody, we're most likely going to deprecate snippets extension and bring it directly into core Zed editor. That way they'll work with all languages out of the box

Thank you! Can you make sure snippets work with Plain Text files too. I have a shortcut I like to use with Markdown and Plain Text but as of right now I can only use it in .md files.

**Comment by davidwebca** [comment] 2024-07-08 18:12
Mmm was anything dropped in the last update? My snippets - that were working - now won't work anymore. 🤔  Files are saved with a syntax selected where it was already working but now it doesn't. Am I insane?

**Comment by failable** [comment] 2024-07-11 01:01
@osiewicz  Works like a charm. 

But it's a bit unclear how to name the snippet file especially when there is whitespace in the language name.

For example,

- For `Plain Text`, `plaintext.json` works while `plain_text.json` and `plain text.json` don't.
- While for `Git Ignore`, `git ignore.json` works while `gitignore.json` and `git_ignore.json` don't.

**Comment by michTheBrandofficial** [comment] 2024-07-19 23:39
I tried using the snippets but the dont work at all

**Comment by JosephTLyons** [comment] 2024-07-23 01:36
I created a pretty small document for getting started with configuring snippets here.

- https://zed.dev/docs/snippets

Ill add documentation on how to bundle snippets via an extension soon.

I think we likely have a bit more work to do to make snippets discoverable and easily editable, but the core is all in place, so I think I will close out this issue. Feel free to open up new issues for feature requests about snippets. If you need help building something out, please do so in our Q&A Discussions section

- https://github.com/zed-industries/zed/discussions/categories/q-a

**Closed by JosephTLyons** 2024-07-23 01:36 UTC
Labels: enhancement, editor, setting, priority request

**Comment by fuzenco** [comment] 2024-07-23 01:46
Thank you. This is a perfect start. I’m loving Snippets in Zed.

**Comment by alejodelosrios** [comment] 2024-08-15 01:43
> I tried using the snippets but they do not work at all

Same here, I have javascript.json and typescript.json saved on the zed/snippets folder, and it doesn't work. 
I've restarted Zed before try and nothing. Would anyone be able to help me?

**Comment by huhu415** [comment] 2024-08-15 01:50
as this code , you need write `blog` in `.md`, when you want to get the body content  in `.md`.      
`{
  "Create new md file": {
    "prefix": "blog",
    "body": [
      "+++",
      "title = '$1'",
      "categories = ['LearnOn${2:line}']",
      "tags = ['${3:go}']",
      "date = 2024-$4-$5",
      "draft = true",
      "+++"
    ],
    "description": "Create new md file"
  }
}`

**Comment by alejodelosrios** [comment] 2024-08-15 01:55
I imagine you already have a file called markdown.json stored in zed/snippets.  In my case, I´m trying to get snippets for .ts and .tsx files doing the same. I have a typescript.json and typescriptreact.json files in that folder. 

Then, when I write the prefix on a file with the extension .ts or .tsx, nothing happens.  The autocomplete menu doesn´t offer me the snippet. What I´m doing wrong?

**Comment by huhu415** [comment] 2024-08-15 01:58
lol, why? then, i donot know, lol.

**Comment by alejodelosrios** [comment] 2024-08-15 23:35
I can confirm that it is working for javascript & typescript files using the (javascript.json,typescript.json) files. Still doesn't work for React Native files with the typescriptreact.json  
If anyone knows how to do it, I would appreciate the help!

**Comment by huhu415** [comment] 2024-08-16 00:56
then you can use snippets.json, that will works in all files

**Comment by florinpatrascu** [comment] 2024-08-16 14:46
I think this _small_ question might just help me climb to the top of the hit list, lol. Is there a way to set the order of the items in the snippet pop-up?

**Comment by davidwebca** [comment] 2024-08-16 15:05
That's my main problem too right now. My snippets don't end up first and I can't get it there. At first I thought if I repeatedly used them, there would be a "preference" ranking, but to no avail.

**Comment by alejodelosrios** [comment] 2024-08-16 15:45
> then you can use snippets.json, that will works in all files

Thanks @huhu415, this works like a charm!!!

**Comment by itsmikesharescode** [comment] 2024-08-25 05:12
Is this possible now in zed latest version?

**Comment by auspy** [comment] 2024-09-03 07:26
can we use filename as variable when defining snippets. for example: in vscode I used to type "slr" and it created a component with the filename. `//example.jsx creates
const example = ()=>{return <></>}; export default example;
`

**Comment by ottob** [comment] 2024-09-09 12:01
I copied a snippet from VS code containing this that didn't work in zed. It would be nice if this was supported too.

`${1:$TM_FILENAME_BASE}`

**Comment by mocenigo** [comment] 2024-09-21 11:35
> Heads up everybody, we're most likely going to deprecate snippets extension and bring it directly into core Zed editor. That way they'll work with all languages out of the box and extensions will be able to provide their own snippets. It would probably also fix #13636

This would be great! Any info on whether extensions can also have theur own settings.json that has precedence on the global one in case there is a clashy? (priority should be: global lowest, extension hogher, then project highest)

**Comment by romanzipp** [comment] 2024-11-22 09:57
For me, there were no snippets available due to syntax errors. Zed just fails silently.

Via command prompt, open "zed: open log". There should be some kind of Snippet error.

**Comment by TheKinng96** [comment] 2025-02-02 02:13
anyone misunderstood the ~/.config like i do?
I tot it is in my project file but ended up not

a simpler way to target the correct directory is CMD + shift + p, then type `snippets`
choose `configure snippets` and pick your language there

**Comment by IvanIsak2000** [comment] 2025-02-05 14:05
Lol

I just pasted a [vscode snippet](https://github.com/golang/vscode-go/blob/baab7be148eeba4f130bfaa077f5a401adea61dd/extension/snippets/go.json) for Golang in `go.json`:

![Image](https://github.com/user-attachments/assets/fc9b0e8d-ab94-4415-8d9b-ea275fcd9121)

And when I command CMD + shift + p and select snippets and select Golang I'm moved in the snippet file:

![Image](https://github.com/user-attachments/assets/0232a799-5315-4f68-8b3a-4f3392dc5bf3)


But Zed doesn't see new snippets :( 

![Image](https://github.com/user-attachments/assets/35fdceb2-39e0-4291-bbe5-2facdf189bc8)


### OS: arch linux
### Zed: 0.171.6

What do you think, guys?
