### ISSUE TITLE
Unable to save untitled files after update

### ISSUE THREAD

**Issue by darkoceans** [zed-industries/zed#4635] opened 2023-07-07 11:37 UTC
[https://github.com/zed-industries/zed/issues/4635](https://github.com/zed-industries/zed/issues/4635)

<sub>From [SyncLinear.com](https://synclinear.com) | [Z-2696](https://linear.app/zed-industries/issue/Z-2696/unable-to-save-untitled-files-after-update)</sub>

**Comment by JosephTLyons** [comment] 2024-07-28 06:59
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 06:59 UTC
Labels: defect, workspace
