### ISSUE TITLE
Support LSP extensions in Zed language extensions

### ISSUE THREAD

**Issue by valentinegb** [zed-industries/zed#21133] opened 2024-11-24 08:49 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Allow Zed language extensions to handle Language Server Protocol extensions should a language server implement them.

For example, [Eclipse JDT Language Server], the language server the [Java Zed extension] uses, implements [several LSP extensions]. The [Java Zed extension]'s inability to handle these LSP extensions is a frequently brought up limitation and surpassing this limitation is crucial to making Java development with Zed at least close to on-par with Java IDEs (or even just VSCode).

[Eclipse JDT Language Server]: https://github.com/eclipse-jdtls/eclipse.jdt.ls
[Java Zed extension]: http://github.com/zed-extensions/java
[several LSP extensions]: https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Language-Server-Protocol-Extensions

### Environment

Zed: v0.163.2 (Zed Preview)
OS: macOS 15.2.0
Memory: 8 GiB
Architecture: aarch64

**Comment by notpeter** [comment] 2024-11-25 20:45
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/20042

If not, please comment and I'm happy to reopen.

**Closed by notpeter** 2024-11-25 20:45 UTC
Labels: enhancement, triage, admin read
