### ISSUE TITLE
Commenting JSX code is broken

### ISSUE THREAD

**Issue by bmamouri** [zed-industries/zed#16922] opened 2024-08-26 22:42 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When performing "Toggle Line Comment" action on a JSX block of code, the `//` is used. But commenting a React block should be done using `{/* ... */}` syntax.

<img width="542" alt="image" src="https://github.com/user-attachments/assets/ac150ed9-c504-4463-b586-32ee96e76b7e">

### Environment

Zed: v0.150.3 (Zed Preview)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-08-27 07:05
Duplicate of https://github.com/zed-industries/zed/issues/5291

**Closed by SomeoneToIgnore** 2024-08-27 07:05 UTC
Labels: defect, triage, admin read
