### ISSUE TITLE
Inline git diff cannot be closed

### ISSUE THREAD

**Issue by Peiffap** [zed-industries/zed#13992] opened 2024-07-09 13:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using the git inline diff functionality, there is no (clearly visible) way to close the diff.

### Environment

Zed: v0.142.6 (Zed)
OS: macOS 12.7.5
Memory: 8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/25282854/c9782312-b940-48cc-961d-5450fabcbf29

### If applicable, attach your Zed.log file to this issue.

N/A

**Comment by notpeter** [comment] 2024-07-09 14:14
Yep.  You can use `esc` or `cmd-'` (`editor::ToggleHunkDiff`) with the keyboard but we should probably have something visual to toggle it with the mouse as well.

**Comment by SomeoneToIgnore** [comment] 2024-07-09 14:21
Duplicate of https://github.com/zed-industries/zed/issues/12404

**Closed by SomeoneToIgnore** 2024-07-09 14:21 UTC
Labels: enhancement, design, mouse interaction, editor, git
