### ISSUE TITLE
Development extensions are uninstalled/replaced when updating Zed

### ISSUE THREAD

**Issue by paperdave** [zed-industries/zed#11639] opened 2024-05-10 02:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. install a dev extension. in my case it is a edit of the Zig extension
2. update zed / wait time. haven't 100% confirmed its due to updates.
3. **bug**: the extension is replaced with the zed built-in version

### Environment

Zed: v0.134.4 (Zed)
OS: macOS 13.6.2
Memory: 64 GiB
Architecture: aarch64

**Comment by notpeter** [comment] 2024-11-06 00:02
I am unable to reproduce and so I am going to close it as unactionable.
If you have observed this more recently or have a set of steps that reproduces the error, please comment below and I'm happy to reopen.

Thanks for reporting.

**Closed by notpeter** 2024-11-06 00:02 UTC
Labels: bug, triage, admin read, extension infrastructure
