### ISSUE TITLE
Add option to disable breadcrumbs bar

### ISSUE THREAD

**Issue by diocletiann** [zed-industries/zed#6845] opened 2024-01-27 07:26 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Love the editor, really don't like the breadcrumbs bar. It's right where my eyes land naturally (on the laptop screen), it wastes space, and it keeps changing as a navigate, causing me to constantly glance it at for no reason. 

I commented out the lines that draw it and I greatly prefer this version.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1512" alt="image" src="https://github.com/zed-industries/zed/assets/14058796/e19ac6cd-b2b1-4530-b988-fd4d7e9e1e48">

**Comment by JosephTLyons** [comment] 2024-01-29 22:22
Hey @diocletiann,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4756

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-01-29 22:22 UTC
Labels: enhancement, workspace, setting
