### ISSUE TITLE
Unable to correctly select a folder in the directory to create a new file or directory.

### ISSUE THREAD

**Issue by seventhse** [zed-industries/zed#17188] opened 2024-08-31 05:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After repeatedly creating subdirectories, I am unable to freely choose which directory level to create files in.

https://github.com/user-attachments/assets/c3bc2ed0-0b8b-45ea-9d80-efcfdbc21560

### Environment

Zed: v0.150.4 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

The correct implementation of this feature should allow the user to accurately select a specific directory level and perform operations normally.

The directory collapsing feature might sometimes make it difficult for users to distinguish the current directory structure and lead to inconvenient operations.
If a configuration option could be added to allow users to control whether the directory tree should be collapsed, giving them the freedom to choose, I believe this would meet the needs of most users

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-09-02 12:57
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/17252

Thanks for reporting.

**Closed by notpeter** 2024-09-02 12:57 UTC
Labels: defect, triage, admin read
