### ISSUE TITLE
Opening an image does not reveal the file in project panel

### ISSUE THREAD

**Issue by jsardev** [zed-industries/zed#18327] opened 2024-09-25 09:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Opening a code file does reveal the file location in the project panel. This does not happen when opening e.g. images. I only checked `*.png` and `*.webp` files.

### Environment

Zed: v0.153.7 (Zed)
OS: macOS 14.4.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment] 2024-10-03 02:42
I just ran into this myself when trying to find the location of an image that I opened via file finder!

**Comment by notpeter** [comment] 2024-10-08 14:27
Duplicate of:
- https://github.com/zed-industries/zed/issues/9897

**Closed by notpeter** 2024-10-08 14:26 UTC
Labels: defect, project panel, image viewer
