### ISSUE TITLE
Unable to compile on Windows

### ISSUE THREAD

**Issue by IITuxtmuxII** [zed-industries/zed#14977] opened 2024-07-22 18:50 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

After trying to compile on win10 for windows I get this issue and it wont start up.

```
   Compiling go_to_line v0.1.0 (C:\Users\Paul\Downloads\zed-main\zed-main\crates\go_to_line)
   Compiling outline_panel v0.1.0 (C:\Users\Paul\Downloads\zed-main\zed-main\crates\outline_panel)
   Compiling journal v0.1.0 (C:\Users\Paul\Downloads\zed-main\zed-main\crates\journal)
    Finished `release` profile [optimized + debuginfo] target(s) in 21m 01s
     Running `target\release\zed.exe`
error: process didn't exit successfully: `target\release\zed.exe` (exit code: 0xc000041d)
```

### Environment

Windows 10 l
atest rust

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by MichaelRehberg** [comment] 2024-07-22 20:01
Seeing the same behaviour on windows 11 23h2 build 22631.3880 with rustc 1.79.0

**Comment by JunkuiZhang** [comment] 2024-07-23 09:34
> Seeing the same behaviour on windows 11 23h2 build 22631.3880 with rustc 1.79.0

I am using the same Windows version as you, and it runs without any issues. That's strange.

![Screenshot 2024-07-23 173229](https://github.com/user-attachments/assets/bd3b845e-f901-4c3f-a4ee-154e36c1ca71)

**Comment by Polygons1** [comment] 2024-07-23 11:13
I think that https://github.com/zed-industries/zed/issues/13575 is related

**Comment by MichaelRehberg** [comment] 2024-07-24 21:04
Short update from my side:

```rust
PS C:\development\Git\zed> cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.36s
     Running `target\debug\zed.exe`
[2024-07-24T22:59:39+02:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-07-24T22:59:39+02:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-07-24T22:59:39+02:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-07-24T22:59:39+02:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-07-24T22:59:39+02:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-07-24T22:59:39+02:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-07-24T22:59:39+02:00 ERROR fs.rs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
Thread "main" panicked with "GPU error Initialization of an object has failed" at C:\Users\osmre\.cargo\git\checkouts\blade-ea462a0faa3f9995\7e497c5\blade-graphics\src\vulkan\command.rs:446:27
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: git_smart_subtransport_git
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: DispatchMessageW
  30: CallWindowProcW
  31: wglSwapBuffers
  32: DispatchMessageW
  33: DispatchMessageW
  34: GetClassLongW
  35: KiUserCallbackDispatcher
  36: NtUserDispatchMessage
  37: DispatchMessageW
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: <unknown>
  48: git_smart_subtransport_git
  49: BaseThreadInitThunk
  50: RtlUserThreadStart

error: process didn't exit successfully: `target\debug\zed.exe` (exit code: 0xffffffff)
``` 
Tried updating the graphics driver (avoiding the classic case of an outdated graphics driver!) 
No luck with that :-( still get the same error, but maybe that helps to get into the right direction.

**Comment by ilya-trifonov** [comment] 2024-08-21 14:53
Hi! I have the same problem. Do you have a solution?

**Comment by just-ero** [comment] 2024-10-04 12:28
Similar issue here, but I'm getting
```
Wasmtime's runtime is being compiled for an architecture that it does not support
```
when just running `cargo run --release`. There are more errors, for example in `html_to_markdown v0.1.0` and `dashmap v5.5.3` with a symbol not being found within its current scope.

**Comment by notpeter** [comment] 2024-11-26 18:04
There seems to be multiple unrelated compilation failures and crashes on windows here with multiple likely root causes (video drives, minigw, etc).  Closing as unactionable.

**Closed by notpeter** 2024-11-26 18:04 UTC
Labels: bug, panic / crash, windows, open source
