### ISSUE TITLE
Mirror VS Code key bindings

### ISSUE THREAD

**Issue by timkgh** [zed-industries/zed#9124] opened 2024-03-09 23:11 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Default VS Code key bindings are a mix of VS Code and Sublime. I think they should be cleaned up to truly mirror VS Code. Examples:

| Description | Key |
|--|--|
Delete Line | ⇧⌘K
Move Line Down | ⌥↓
Move Line Up | ⌥↑ 
Copy Line Down | ⇧⌥↓ 
Copy Line Up | ⇧⌥↑

There is a list on this page and many more in VS Code itself.
https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing

### Environment

macOS Zed 0.125.3

**Comment by Moshyfawn** [comment] 2024-03-10 00:16
This has already been discussed in several other threads. Let's close this one in favour of one of the others to keep the upvotes and discussions localised. Be sure to +👍 and add any missing information.

Duplicate of
- #4652

**Closed by Moshyfawn** 2024-03-10 00:16 UTC
Labels: defect, triage, admin read
