### ISSUE TITLE
markdown preview support within the assistant panel

### ISSUE THREAD

**Issue by zazaji** [zed-industries/zed#15937] opened 2024-08-08 00:13 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

 Implement a markdown preview feature in the assistant panel. and support 
file upload
Rationale: This would allow users to see a live preview of their markdown content as they type, making it easier to format and style text without having to switch contexts or tabs.

### Benefits:

Improved productivity for users who use assistant to input or output image content.
Improved coding perview.
Enhanced user experience by providing a more integrated development environment.

### Proposed Solution
Add a toggle button to the assistant panel that switches between the markdown editor and the preview mode.
Ensure the image preview in the markdown virew content.
Optionally, include syntax highlighting in the editor to further aid in markdown composition.

**Comment by universalmind303** [comment] 2024-08-08 01:47
duplicate of https://github.com/zed-industries/zed/issues/15862

**Comment by kunalnanda** [comment] 2024-10-03 06:37
This would be really handy for better readability of AI respones.

**Closed** 2024-10-15 18:36 UTC
Labels: duplicate
