### ISSUE TITLE
Autosave to a scratchpad/buffered file

### ISSUE THREAD

**Issue by ifsheldon** [zed-industries/zed#15584] opened 2024-08-01 03:41 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hi! I'd like to propose a new autosave method and I'd like to see it implemented. Now I see 4 different methods of autosave in Zed, but these will modify the file on the users' behalf. 

What I want (since when I was using VSCode) is:
1. Autosave my changes to a file somewhere else the original file, preferably in a persistent file, not in memory. So if the editor or my computer crashes, I can still recover my changes. 
2. The original file is not changed until I hit `Cmd + S`. 

This works like a git, but without a long history and complicated version control commands. It's kind of reminiscent like what Word does.

Use case:

Me for example, one time I was writing a Python script. That was one-off code so I don't want to init a git repo etc. When it went a bit long, I found it a bit hard to keep track of what had been changed, which was when my computer crashed..... I lost my changes because I didn't enable autosave as I don't want the editor to save incomplete changes for me. Even if I had enabled autosave, I would have a hard time to find out where were the incomplete changes which are buggy.

### If applicable, add mockups / screenshots to help present your vision of the feature

Implementation:
I'm not very familiar with Zed internals, but I think we can reuse some code logics.

1. (New) create a `.filename.extension` scratchpad file for a `filename.extension` file
2. (Existing) Enable autosave, but autosave to the scratchpad file instead.
3. (Existing) When the user explicitly save the changes, save them to the actual file.

**Comment by notpeter** [comment] 2024-08-01 20:19
Closing as a duplicate of:
- https://github.com/zed-industries/zed/issues/15045

**Closed by notpeter** 2024-08-01 20:19 UTC
Labels: enhancement, triage, admin read
