### ISSUE TITLE
Pasting from another project is not working

### ISSUE THREAD

**Issue by Bishwas-py** [zed-industries/zed#13634] opened 2024-06-28 10:14 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I copy text from one project (p1) in Zed to another project (p2), the copied text doesn't get pasted. But after focusing on something that is not a zed program (terminal, browser or something else), and pasting on p2 the text gets pasted. I dunno the actual reason, maybe you guys can find it out.

### Environment

me@fedora ~ $ uname -a
Linux fedora 6.8.7-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:21:08 UTC 2024 x86_64 GNU/Linux
me@fedora ~ $ zed -v
Zed  dev 0.142.0 – /home/me/.local/zed-dev.app/libexec/zed-editor

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/42182303/634e3593-85d1-412b-a85c-982ba2ffb917

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-06-28T15:54:48+05:45 [INFO] ignoring macOS specific set_edited
2024-06-28T15:54:48+05:45 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-28T15:54:48+05:45 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-28T15:54:48+05:45 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-28T15:54:48+05:45 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-28T15:54:48+05:45 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-28T15:54:48+05:45 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-06-28T15:54:56+05:45 [INFO] ignoring macOS specific set_edited
2024-06-28T15:54:56+05:45 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 1,
  "message": "[INFO] [ghostText] [2024-06-28T10:09:56.267Z] Found inline suggestions locally",
  "metadataStr": "[INFO] [ghostText] [2024-06-28T10:09:56.267Z]",
  "extra": [
    "Found inline suggestions locally"
  ]
}
2024-06-28T15:54:57+05:45 [INFO] ignoring macOS specific set_edited
2024-06-28T15:54:59+05:45 [INFO] ignoring macOS specific set_edited
2024-06-28T15:55:00+05:45 [INFO] ignoring macOS specific set_edited
2024-06-28T15:55:00+05:45 [INFO] new;
2024-06-28T15:55:00+05:45 [INFO] keep_updated;
2024-06-28T15:55:00+05:45 [INFO] new;

**Comment by notpeter** [comment] 2024-08-27 21:53
Although this issue is older, closing as duplicate of 
- https://github.com/zed-industries/zed/issues/16741
Because it has more upvotes.  Thanks for reporting. Please 👍 over there.

**Closed by notpeter** 2024-08-27 21:53 UTC
Labels: defect, linux
