### ISSUE TITLE
Inline suggestions doesn't show the path the value comes from

### ISSUE THREAD

**Issue by eidriahn** [zed-industries/zed#10204] opened 2024-04-05 14:39 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As seen in the screenshot, while in a .tsx file and trying to import a React component I can't see the path it is coming from. 

### Environment

Zed: v0.129.2 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/zed/assets/45937542/97132185-8946-4f00-a2bb-0bad98e0ce13)

**Comment by JosephTLyons** [comment] 2024-04-05 15:44
Hey @eidriahn,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4457

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-05 15:44 UTC
Labels: defect, typescript, language, popovers, autocompletions
