### ISSUE TITLE
malfunctioning "ctrl + enter" and "ctrl + shift + enter" keymaps on linux 

### ISSUE THREAD

**Issue by mohamedeliwa** [zed-industries/zed#14633] opened 2024-07-17 08:44 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

while focusing the **editor**
expected behaviour:
The `ctrl + enter`  keymap should create a newline below the cursor and moves the cursor to it. 
The `ctrl + shift + enter` keymap shoud create a newline above the cursor and moves the cursor to it.

actual behaviour:
The `ctrl + enter`  keymap doesn't do anything. 
The `ctrl + shift + enter` keymap creates a newline below the cursor and moves the cursor to it.

### Environment

Ubuntu 22.04.4 LTS

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-17 15:43
I think this is a duplicate of these two:
- #9891 
- https://github.com/zed-industries/zed/issues/14290

**Closed** 2024-07-17 15:43 UTC
Labels: defect, triage, admin read

**Comment by mohamedeliwa** [comment] 2024-07-17 16:18
@notpeter  
yes it's a duplicate, sorry, I already searched the open issues before I create this one.
but I didn't find those two issues.

I'm new to rust and also new to open source contribution
do you think this issue is good for beginners ? 
 
 if it's so , can I take it ? and with little guidance I can solve the issue ?

**Comment by Ahmed-E-86** [comment] 2025-02-05 10:59
This issue still exists and it is not fixed.
