### ISSUE TITLE
hover documentation/tooltip support markdown

### ISSUE THREAD

**Issue by kingwingfly** [zed-industries/zed#12278] opened 2024-05-25 11:16 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'm using a Rust crate called `dirs`. Its function document is arranged as a table:

![Screenshot 2024-05-25 at 19 02 02](https://github.com/zed-industries/zed/assets/38573173/fbfdc129-721d-4f75-b057-608063da32dc)

However, when I hover cursor on it, it looks in a mess:

<img width="1440" alt="Screenshot 2024-05-25 at 19 02 08" src="https://github.com/zed-industries/zed/assets/38573173/bef183c8-758a-46b0-a9e5-f58cb0df2f7d">

In vscode, it renders well:

<img width="1440" alt="Screenshot 2024-05-25 at 19 14 04" src="https://github.com/zed-industries/zed/assets/38573173/bfbf38ab-bf2b-424c-918f-fc6ed3f6e112">

# expected

Hover tooltip to support markdown rendering.

**Comment by bennetbo** [comment] 2024-05-25 11:29
Hey, this looks like a duplicate of #5386 (the popup actually supports markdown rendering, but it does not handle tables correctly)

**Closed by bennetbo** 2024-05-25 11:29 UTC
Labels: enhancement, triage, admin read
