### ISSUE TITLE
UI breaks after resizing Terminal and scorlling through it

### ISSUE THREAD

**Issue by AppearedOne** [zed-industries/zed#9031] opened 2024-03-07 18:49 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I simply resized the terminal window to be pretty large, colliding with some UI components possibly and now, whenever I move my mouse the ui glitches and reveals some icons and imediately hides them again. 
I restarted and the issue persisted, as long as the terminal is resized, so that its just below the tabs. When I eventually manage to move it back down its all fine again.

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 14.1.2
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://streamable.com/1q1vfp

**Comment by Moshyfawn** [comment] 2024-03-07 19:39
Duplicate of
- Bottom dock(terminal) trigger cmd wrong height rendering (flickering)

**Closed by Moshyfawn** 2024-03-07 19:39 UTC
Labels: defect, triage, admin read
