### ISSUE TITLE
Crash when opening a second Zed instance

### ISSUE THREAD

**Issue by Tahinli** [zed-industries/zed#22336] opened 2024-12-21 20:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

There was a Zed instance then I opened a local folder to edit my other project. It crashed after opening second instance of Zed.

### Environment

Zed: v0.166.1 (Zed)
OS: Linux Wayland fedora 41
Memory: 31.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1660 Ti || NVIDIA || 565.77

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-21T23:53:36.942371963+03:00 [INFO] new;
2024-12-21T23:53:36.944630266+03:00 [INFO] keep_updated;
2024-12-21T23:53:36.944786318+03:00 [INFO] new;
2024-12-21T23:53:40.759634376+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:53:40.759821446+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:01.909872263+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:01.910075282+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:03.208172279+03:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-12-21T23:54:03.222059341+03:00 [INFO] Enabling Vulkan Portability
2024-12-21T23:54:03.222105099+03:00 [INFO] Enabling color space support
2024-12-21T23:54:03.243440013+03:00 [INFO] Adapter: "NVIDIA GeForce GTX 1660 Ti"
2024-12-21T23:54:03.243505969+03:00 [INFO] No ray tracing extensions are supported
2024-12-21T23:54:03.34166516+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:03.341711351+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:03.34638983+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-21T23:54:03.346425162+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-21T23:54:03.346455519+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-12-21T23:54:03.352583917+03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1660 Ti", driver_name: "NVIDIA", driver_info: "565.77" }
2024-12-21T23:54:03.359392531+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:03.359439853+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:03.364489323+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-12-21T23:54:03.372057924+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:03.372107137+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:03.405516954+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:03.405555408+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:03.410897993+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:03.410936618+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:03.420589396+03:00 [INFO] attempting to start language server "rust-analyzer", path: "/home/tahinli/Documents/Code/Rust/LearnRust", id: 2
2024-12-21T23:54:03.503865477+03:00 [INFO] using project environment variables shell launched in "/home/tahinli/Documents/Code/Rust/LearnRust". PATH="/home/tahinli/.local/bin:/home/tahinli/.cargo/bin:/home/tahinli/.local/bin:/home/tahinli/.cargo/bin:/home/tahinli/.cargo/bin/:/home/tahinli/.local/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/tahinli/.dotnet/tools"
2024-12-21T23:54:03.503978604+03:00 [INFO] found rust-analyzer in PATH. trying to run `rust-analyzer --help`
2024-12-21T23:54:03.540883451+03:00 [INFO] found user-installed language server for rust-analyzer. path: "/home/tahinli/.cargo/bin/rust-analyzer", arguments: []
2024-12-21T23:54:03.541001344+03:00 [INFO] starting language server process. binary path: "/home/tahinli/.cargo/bin/rust-analyzer", working directory: "/home/tahinli/Documents/Code/Rust/LearnRust", args: []
2024-12-21T23:54:04.867931592+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:04.867975891+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:07.862170631+03:00 [INFO] ========== starting zed ==========
2024-12-21T23:54:07.872324985+03:00 [INFO] Opening main db
2024-12-21T23:54:07.87240086+03:00 [INFO] perform;
2024-12-21T23:54:07.872438616+03:00 [INFO] authenticate;
2024-12-21T23:54:07.872484081+03:00 [INFO] read_command;
2024-12-21T23:54:07.872525967+03:00 [INFO] send_secondary_commands;
2024-12-21T23:54:07.872744669+03:00 [INFO] new;
2024-12-21T23:54:07.872796727+03:00 [INFO] socket reader;
2024-12-21T23:54:07.873161013+03:00 [INFO] keep_updated;
2024-12-21T23:54:07.876510871+03:00 [INFO] Opening main db
2024-12-21T23:54:07.8776887+03:00 [INFO] Using git binary path: None
2024-12-21T23:54:07.909793811+03:00 [INFO] No prompt template overrides directory found at /home/tahinli/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-12-21T23:54:07.910117209+03:00 [INFO] extensions updated. loading 9, reloading 0, unloading 0
2024-12-21T23:54:07.911510216+03:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-12-21T23:54:07.912466277+03:00 [INFO] Opening main db
2024-12-21T23:54:07.912700588+03:00 [INFO] perform;
2024-12-21T23:54:07.912749316+03:00 [INFO] authenticate;
2024-12-21T23:54:07.912806544+03:00 [INFO] read_command;
2024-12-21T23:54:07.913265165+03:00 [INFO] socket reader;
2024-12-21T23:54:07.919306992+03:00 [INFO] new;
2024-12-21T23:54:07.919952841+03:00 [INFO] keep_updated;
2024-12-21T23:54:07.922189206+03:00 [INFO] set status on client 0: Authenticating
2024-12-21T23:54:07.922245006+03:00 [ERROR] No such file or directory (os error 2) about ["/home/tahinli/.config/github-copilot"]
2024-12-21T23:54:07.922449609+03:00 [INFO] perform;
2024-12-21T23:54:07.922509952+03:00 [INFO] authenticate;
2024-12-21T23:54:07.922571757+03:00 [INFO] read_command;
2024-12-21T23:54:07.922859752+03:00 [INFO] socket reader;
2024-12-21T23:54:07.923818739+03:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-12-21T23:54:07.936379947+03:00 [INFO] new;
2024-12-21T23:54:07.936991214+03:00 [INFO] keep_updated;
2024-12-21T23:54:07.959048624+03:00 [INFO] set environment variables from shell:/bin/zsh, path:/home/tahinli/.local/bin:/home/tahinli/.cargo/bin:/home/tahinli/.cargo/bin/:/home/tahinli/.local/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/tahinli/.dotnet/tools
2024-12-21T23:54:07.99367054+03:00 [INFO] Enabling Vulkan Portability
2024-12-21T23:54:07.9937117+03:00 [INFO] Enabling color space support
2024-12-21T23:54:08.013286641+03:00 [INFO] Adapter: "NVIDIA GeForce GTX 1660 Ti"
2024-12-21T23:54:08.013365717+03:00 [INFO] No ray tracing extensions are supported
2024-12-21T23:54:08.116167999+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:08.116218212+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:08.120905369+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-21T23:54:08.120947515+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-21T23:54:08.120979638+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: PreMultiplied }
2024-12-21T23:54:08.128285541+03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1660 Ti", driver_name: "NVIDIA", driver_info: "565.77" }
2024-12-21T23:54:08.128617706+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:08.128654985+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:08.136150722+03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-12-21T23:54:08.141972798+03:00 [INFO] set status on client 187298: Connecting
2024-12-21T23:54:08.146031902+03:00 [INFO] Opening main db
2024-12-21T23:54:08.149940246+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:08.150013306+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:08.166517465+03:00 [ERROR] missing field `name` at line 37 column 1
2024-12-21T23:54:08.166663682+03:00 [INFO] Opening main db
2024-12-21T23:54:08.172083225+03:00 [INFO] Using surface present mode MAILBOX
2024-12-21T23:54:08.172173425+03:00 [WARN] Unable to forbid exclusive full screen
2024-12-21T23:54:08.286181042+03:00 [INFO] using project environment variables from CLI. PATH="/home/tahinli/.cargo/bin/:/home/tahinli/.local/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
2024-12-21T23:54:08.313473287+03:00 [INFO] attempting to start language server "rust-analyzer", path: "/home/tahinli/Documents/Code/Rust/LearnRust", id: 1
2024-12-21T23:54:08.316404092+03:00 [INFO] found rust-analyzer in PATH. trying to run `rust-analyzer --help`
2024-12-21T23:54:08.353627556+03:00 [INFO] found user-installed language server for rust-analyzer. path: "/home/tahinli/.cargo/bin/rust-analyzer", arguments: []
2024-12-21T23:54:08.353783427+03:00 [INFO] starting language server process. binary path: "/home/tahinli/.cargo/bin/rust-analyzer", working directory: "/home/tahinli/Documents/Code/Rust/LearnRust", args: []
2024-12-21T23:54:08.69001619+03:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-12-21T23:54:09.310281265+03:00 [INFO] add_connection;
2024-12-21T23:54:09.323438034+03:00 [INFO] set status on client 187298: Connected { peer_id: PeerId { owner_id: 629, id: 2501459 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-12-21T23:54:15.269819679+03:00 [ERROR] No such file or directory (os error 2) about ["/home/tahinli/.config/rust-analyzer"]
2024-12-21T23:54:19.537944054+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-21T23:54:19.550325638+03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-21T23:54:19.562901538+03:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-12-21T23:54:19.57655149+03:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-12-21T23:54:30.915827497+03:00 [ERROR] No such file or directory (os error 2) about ["/home/tahinli/.config/rust-analyzer"]
2024-12-21T23:54:30.977018111+03:00 [WARN] Generic lsp request to rust-analyzer failed: content modified
2024-12-21T23:54:30.977108593+03:00 [ERROR] inlay hint update task for range failed: Error {
    context: "inlay hint fetch task",
    source: Error {
        context: "inlay hints LSP request",
        source: "content modified",
    },
}
```
</details>

**Comment by Tahinli** [comment] 2024-12-30 09:14
https://github.com/user-attachments/assets/30434bec-694d-4371-bbc6-2d6e77cd2704

Okay here is how you can reproduce it:

Open Zed.
Open another instance.
Close first instance.

Then Zed crashes.

I thought it's about tiling but no. It crashes even with floating window.

**Comment by SomeoneToIgnore** [comment] 2024-12-30 12:42
So, it crashes not "when opening a second Zed instance" but rather when closing some instance after opening another one.

Then, this is a duplicate of https://github.com/zed-industries/zed/issues/17005 fixed with https://github.com/zed-industries/zed/pull/20853

This is in Zed Preview now, but not in Zed Stable yet, presumably will be released this Wednesday.

**Closed by SomeoneToIgnore** 2024-12-30 12:42 UTC
Labels: bug, triage, panic / crash, admin read
