### ISSUE TITLE
Toggle comment and project search keybindings are malfunctioning

### ISSUE THREAD

**Issue by drochag** [zed-industries/zed#20926] opened 2024-11-20 20:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When auto updated to 0.162.3 keybindings stopped working, cmd+shift+f opens the file to the side OR goes to the start or end of the nearest bracket

### Environment

Zed: v0.161.1 / 0.162.3 (Zed)
OS: macOS 15.0.1
Memory: 32 GiB
Architecture: x86_64

**Comment by LostKobrakai** [comment] 2024-11-20 20:55
I'm seeing `cmd+/` no longer working by pressing cmd + shift + 7 on my german layout keyboard.

**Comment by bendiksolheim** [comment] 2024-11-20 20:58
I am having problems as well. As an example, I have this in my keybindings, which have suddenly stopped working:
```json
  {
    "context": "Editor || Dock || Terminal",
    "bindings": {
      "' /": "pane::SplitRight",
      "' -": "pane::SplitDown",
      "' k": ["workspace::ActivatePaneInDirection", "Up"],
      "' j": ["workspace::ActivatePaneInDirection", "Down"],
      "' h": ["workspace::ActivatePaneInDirection", "Left"],
      "' l": ["workspace::ActivatePaneInDirection", "Right"],
      "' f": "workspace::ToggleZoom",
      "' d": "pane::CloseAllItems"
    }
  },
```
Others, such as `"space /": ["task::Spawn", { "task_name": "Search project" }],` opens up the "search current file" section, which is the same behavior as if I just press `/` alone. Could it be that key sequences are not working the way they used to?

**Comment by thisislvca** [comment] 2024-11-20 21:52
> I'm seeing `cmd+/` no longer working by pressing cmd + shift + 7 on my german layout keyboard.

It also doesn't work in my Italian layout. Before last update it worked, tried on another mac as well to be sure.

**Comment by alvvaro** [comment] 2024-11-20 23:19
Keybindings are completely broken when using the Spanish ISO layout, ⌘ + X shortcuts do not work or behave incorrectly.

For instance, ⌘F is supposed to bring up the Find/Buffer Search UI. While it is rightly indicated as such in the menu bar, it is missing from the command menu. And pressing the combination splits the editor horizontally:

![ScreenRecording2024-11-21at00 13 30-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/b0b7054c-1bd1-4fce-bc4b-700549b6ed93)

Other shortcuts, such as ⌘N, ⌘O or ⌘T seem to do nothing at all.

Researching this, I found a weird looking "not found" in this line while reading the changelog info, which might be to blame?
https://github.com/zed-industries/zed/blob/33bed8d680ffcf0c19ebf442a44e4223099da02f/crates/settings/src/key_equivalents.rs#L70-L73

**Comment by theproducer** [comment] 2024-11-21 03:45
> I'm having issues where it will autocomplete with the name of the key.
> 
> i.e: in an empty buffer, press shift, then hit tab, and it will write 'shift'.
> 
> Is this just me? (on version 0.163.0)

I can confirm this exact behavior following these steps, but in a different version.

Zed 0.162.3
macOS 15.1.1

**Comment by KhazAkar** [comment] 2024-11-21 08:59
I have also issues with keybindings. With VIM mode enabled, I no longer can invoke code actions using `ctrl + .` on linux :/

**Comment by ArturGalstyan1** [comment] 2024-11-21 11:44
I think this issue might be related:


https://github.com/user-attachments/assets/7a4be515-d310-4431-904f-48f9926e6e8d

Pressing `$` to get to the end of the line doesn't work anymore either.

**Comment by hedefalk** [comment] 2024-11-21 12:28
>I'm seeing cmd+/ no longer working by pressing cmd + shift + 7 on my german layout keyboard.

plus one on Swedish locale.

**Comment by ConradIrwin** [comment] 2024-11-21 15:27
Thanks for this! We definitely intended to change things, but not break them!

There are a few different things going on here.

### Expected from #20425
* For German `cmd-/` is now `cmd-ß`. This is a deliberate breaking change. The goal here is so that every shortcut in Zed can be typed without option on every keyboard (see https://zed.dev/blog/keyboard-localization for the approach we took). 
* For Italian, `cmd-/` is now `cmd-.` Same as above.
* For Swedish, it is `cmd-\``

I know changing shortcuts is disruptive, and sorry for not being loud enough to let you know this was about to happen. For all of these, we could make some changes to the mappings over the next few days if we can find an alternative that works more like how you'd all expect from other apps.

### Unsure
* @drochag `cmd-shift-f` should not have changed at all, unless you require an `option` key to type f? Can you please let me know which keyboard layout you use, and I'll investigate.
* @bendiksolheim Vim mode should be working fine, unless you're on nightly?
* @KhazAkar `cmd-.` on Linux shouldn't have changed - I am aware of other problems with Linux shortcuts, but I wasn't expecting their behavior to change recently. Will investigate more.

### Known bugs
* @kernel-io The `shift` behavior will be fixed in the next preview release. This happens when you have a binding to `shift shift`.
* @ArturGalstyan1 On latest nightly I broke vim bindings that require shift with no letter (as part of fixing the `shift` bug). This shouldn't be shipped to preview or stable yet.
* The Spanish ISO layout is an oversight on my part, thanks for tracking that down, will fix.

**Comment by LostKobrakai** [comment] 2024-11-21 15:36
> For German cmd-/ is now cmd-ß. This is a deliberate breaking change. 

If that's the case how do I bind it back? Changing defaults is one thing. Preventing the defaults to be changed back is a another one.

**Comment by tmjoen** [comment] 2024-11-21 15:47
> ### Expected from #20425
> * For German `cmd-/` is now `cmd-ß`. This is a deliberate breaking change. The goal here is so that every shortcut in Zed can be typed without option on every keyboard (see https://zed.dev/blog/keyboard-localization for the approach we took).
> * For Italian, `cmd-/` is now `cmd-.` Same as above.
> * For Swedish, it is `cmd-``

The way I read the change was that it was to get rid of using alt as a modifier for these, but on norwegian keyboards `cmd`-`/` is `cmd`+`shift`+`7`. There's no alt in the mix. This combo just opens the "help search" menu now

**Comment by KhazAkar** [comment] 2024-11-21 15:59
In my case, I have Polish Programmer keyboard layout set, which is quite universally used in Poland. And `ctrl-.`doesn't work. Maybe it's also connected here?

**Comment by hedefalk** [comment] 2024-11-21 16:18
>The way I read the change was that it was to get rid of using alt as a modifier for these, but on norwegian keyboards cmd-/ is cmd+shift+7. There's no alt in the mix. This combo just opens the "help search" menu now

Basically same here, but does nothing. But cmd-shift-7 === cmd-/ and does nothing anymore, but used to be ToggleComments. Neither:

"cmd-shift-7": ["editor::ToggleComments", { "advance_downwards": false }]
"cmd-/": ["editor::ToggleComments", { "advance_downwards": false }]
 
makes any difference. I can open the command pallete and trigger it there:

<img width="564" alt="image" src="https://github.com/user-attachments/assets/9de24153-3555-451f-9b2a-5a96a9b89f81">

but the shortcut listed is basically a blunt "lie" at this point.

**Comment by ConradIrwin** [comment] 2024-11-21 16:22
@LostKobrakai You can bind this back in your settings with either:

Because shift-7 types / on your layout:
```
{
  "use_layout_keys": true,
  "bindings": {"cmd-/": "editor::ToggleComments"}
}
```

Or, because shortcuts bound to & are remapped to / on a German keyboard:
```
{
  "bindings": {"cmd-&": "editor::ToggleComments"}
}
```

**Comment by drochag** [comment] 2024-11-21 16:23
@ConradIrwin not sure what specific info you need, but it's set up like tis on macOS

<img width="641" alt="Screenshot 2024-11-21 at 10 20 41 a m" src="https://github.com/user-attachments/assets/327ce77f-4a10-4ec9-a4cd-e5c87892e6c2">

I also have `"base_keymap": "SublimeText"` and no other specific key maps

here is a video where you can see what `cmd-F` and `cmd-shit-F` does on both v0.161.1 and 0.162.3 versions


Uploading Screen Recording 2024-11-21 at 10.17.14 a.m..mov…

**Comment by hedefalk** [comment] 2024-11-21 16:26
I have the setting:

"cmd-/": ["editor::ToggleComments", { "advance_downwards": false }]

but cmd-/ === cmd-shift-7 does nothing. Its also not showing this when opening the command pallete, but the default one instead. That's at least something even though not the one I want. At least I have somewhat of a workaround:

<img width="576" alt="image" src="https://github.com/user-attachments/assets/2039b9ba-810f-4f08-9774-d7d3e2c1c6fa">

**Comment by ConradIrwin** [comment] 2024-11-21 16:50
@drochag Thanks! We had a bug in our Spanish keyboard, fix incoming: https://github.com/zed-industries/zed/pull/20995

**Comment by alvvaro** [comment] 2024-11-21 16:59
@ConradIrwin thank you for your hard work, I cannot begin to imagine how difficult this might be to tackle, since it's basically an exhibition of edge cases.

Bugs aside, I'm fine with any change as long as there's consistency between the menu bar hint, the command palette hint and the editor proper.

Please comment again when there's a nightly or a preview version we can try and give feedback of!

**Comment by ConradIrwin** [comment] 2024-11-21 17:31
:+1: Main should be fixed as of a few minutes ago, and I'll ship a preview when it's built in ~45minutes.

Assuming that feels right, I'll release a stable in an hour or two.

**Comment by drochag** [comment] 2024-11-21 18:30
thank you so much @ConradIrwin 
as for the v0.163.0-pre tag, seeing the same issues

* `cmd+F` opens the file to the side when focusing the editor but opens the search field when focusing the file tree, it should open the search field when focusing the editor as well
* `cmd+shift+F` does nothing while focusing the file tree, goes from the beginning and the end of the nearest curly braces (not sure what functionality is this)

**Comment by daniele-solutiontech** [comment] 2024-11-21 18:43
> For Italian, cmd-/ is now cmd-. Same as above.

Hi @ConradIrwin,

On an Italian keyboard, neither `Cmd-/` nor `Cmd-.` seem to work as intended. Could someone with an Italian keyboard layout confirm if they are experiencing the same issue?

**Comment by drochag** [comment] 2024-11-21 18:43
That one works great for me, thanks for your hard work @ConradIrwin

**Comment by ConradIrwin** [comment] 2024-11-21 18:54
@daniele-solutiontech hmm, I think I gave you bad advice; actually enabling the keyboard on macOS, I see there are two:

* Italian. For me typing cmd-shift-7 toggles comments here (should be notated as `cmd-/`)
* Italian QZERTY. For me typing `cmd-shift-)` toggles comments (should be notated as `cmd-7`)

if neither is working for you, could you please confirm which keyboard layout you're using? If you want to see Zed's view of it, open the key context debug view with `cmd-shift-p debug key view` and look for `keyboard_layout = com.apple.keylayout.XXXX` or similar.

Also, if you type `toggle comments` into the command palette what does it show? (On Italian QZERTY, this is what I see: 
<img width="792" alt="Screenshot 2024-11-21 at 11 53 33" src="https://github.com/user-attachments/assets/b6877d24-2cdd-4710-8ae3-072c1290dc1d">)

**Comment by bendiksolheim** [comment] 2024-11-21 19:39
> @bendiksolheim Vim mode should be working fine, unless you're on nightly?

Vim mode itself works fine! There are just some specific keybindings that are not working at all. I am using a Norwegian keyboard layout, so I guess I might have the same problems as a few others in this thread that `/` is `cmd+shift+7`?

I just tried adding `"use_layout_keys": true` to my keybindings, as I have seen others mentioned here, and this makes my keybindings work again. But I definitely have a QWERTY keyboard, so I don’t exactly understand why it helps. As an example, this keybinding only works with `"use_layout_keys": true`:

```json
"space /": ["task::Spawn", { "task_name": "Search project" }]
```

Without the `use_layout_key` setting, pressing `space /` just opens up the regular "search in file" dialog.

**Comment by ConradIrwin** [comment] 2024-11-21 19:46
@bendiksolheim thanks! I can reproduce this on a Norwegian layout, but I'm not yet sure why, will investigate.

**Comment by daniele-solutiontech** [comment] 2024-11-21 19:48
Thank you for the quick reply, @ConradIrwin!
My keyboard layout is com.apple.keylayout.Italian-Pro, and the correct keybinding is `cmd-'`

**Comment by ConradIrwin** [comment] 2024-11-21 19:52
@bendiksolheim Sorry my mistake, it is "working as intended" to require the `use_layout_keys` in this context (Though I'm now regretting making that opt-in instead of opt-out; maybe we should flip that).

Currently the way this works for Latin keyboards that require the `option` key to type some of the ASCII range is that we perform key-equivalent mapping: https://github.com/zed-industries/zed/blob/841d3221b34fa5786d85fb7c2cd7e9cc3ae51c15/crates/settings/src/key_equivalents.rs#L860-L884

This means that every shortcut defined in the ASCII range is moved to a key you can hit without using option, so that we can bind to `cmd-@` and `cmd-option-@` on a US keyboard, and you can type `cmd-"` or `cmd-option-"`. (If we used @ on a Norwegian layout, there'd be no way to type cmd-@ without option). This is similar to how macOS handles it: https://zed.dev/blog/keyboard-localization.

**Comment by bendiksolheim** [comment] 2024-11-21 20:14
> @bendiksolheim Sorry my mistake, it is "working as intended" to require the use_layout_keys in this context (Though I'm now regretting making that opt-in instead of opt-out; maybe we should flip that).

Hey, I’m happy as long as there is a way for me to get my keybindings to work 😄 I’m not gonna pretend to understand all of this, but I can definitely live with just specifying this property. Thanks for taking the time to help!

**Comment by KhazAkar** [comment] 2024-11-21 20:21
For the record, I've tried `use_layout_keys` myself and shortcuts like `ctrl+.` started working again. @ConradIrwin

**Comment by drochag** [comment] 2024-12-03 10:54
not sure something has changed on 0.164.1, but now having the same issue as @hedefalk , @ConradIrwin 😢 
[this](https://github.com/zed-industries/zed/issues/20926#issuecomment-2491683455) and [this](https://github.com/zed-industries/zed/issues/20926#issuecomment-2491701436)

**Comment by drochag** [comment] 2024-12-03 10:58
also no completions being shown when pressing `ctrl-space` despite having the default

```
"ctrl-space": "editor::ShowCompletions",
```

**Comment by ConradIrwin** [comment] 2024-12-03 18:10
@drochag I am not able to reproduce problems with ctrl-space on either preview or nightly. What are the other problems you're seeing on 0.164.1?

**Comment by schmurfy** [comment] 2024-12-04 16:11
Not sure if that's related but I was using "cmd+shift+/" to toggle comments on a french keyboard and it no longer works :(

**Comment by ConradIrwin** [comment] 2024-12-04 17:15
@schmurfy toggle comments should now be cmd-: on an AZERTY keyboard

**Comment by schmurfy** [comment] 2024-12-05 09:32
> @schmurfy toggle comments should now be cmd-: on an AZERTY keyboard

That's the default and it works but I want is command and shift, I tried: `cmd-shift-:` without any luck :(

**Comment by ConradIrwin** [comment] 2024-12-06 23:50
I am going to close this now #21662 has landed; but feel free to keep asking for help with bindings.

**Closed by ConradIrwin** 2024-12-06 23:50 UTC
Labels: bug, internationalization, keymap / key binding

**Comment by thraizz** [comment] 2025-03-13 09:24
I still have a similar issue, I think. I use a custom keyboard layout (https://github.com/xv0x7c0/osx-us-altgr-intl) to get the good old AltGr dead keys on macOS. If I select the normal US layout, all keyboard shortcuts using the cmd key work. If I select the custom layout, they do not. I've tried fixing it with `"use_layout_keys"`, but to no avail. Any hints or insights would be appreciated!
