### ISSUE TITLE
Source Control tab

### ISSUE THREAD

**Issue by jacobtt21** [zed-industries/zed#8132] opened 2024-02-21 17:10 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

one of my favorite features in VSCode is the source control tab or whatever you call it. I like to be able to see the changes I've staged, I like that I can revert to the last commit if I need to, etc. I think Zed could really benefit from it and I would make the switch.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="329" alt="Screenshot 2024-02-21 at 11 10 45 AM" src="https://github.com/zed-industries/zed/assets/55421470/2c752f2e-9ea7-4f3d-92b2-018969b4b5b5">

**Comment by CurbaiCode** [comment] 2024-02-21 20:13
This is a duplicate of #4367.

**Closed** 2024-02-21 21:09 UTC
Labels: enhancement, triage, admin read

**Comment by JosephTLyons** [comment] 2024-02-23 17:22
Thanks @CurbaiCode - going to close this in favor of #4367, add your 👍 reactions to that issue. :)
