### ISSUE TITLE
find all references in vim mode open

### ISSUE THREAD

**Issue by maan2003** [zed-industries/zed#13678] opened 2024-06-30 05:05 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`g a` on anything, the editor now opens the multi buffer in **visual mode**. This is new behavior from previous releases.
Earlier it was in normal mode.

I suspect 
- https://github.com/zed-industries/zed/pull/13424.

### Environment

Zed: v0.141.3 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 7.4 GiB
Architecture: aarch64

**Comment by notpeter** [comment] 2024-07-01 14:36
Good morning @maan2003.  I attempted to track down if this was a regression when it broke, but had no immediate success. I checked with some old releases and this has been the behavior since at least v0.134.4 (2024-05-09) so it may just always have been incorrect behavior.

**Comment by maan2003** [comment] 2024-07-03 16:21
I might be misremembering, but it is still incorrect behaviour.

**Comment by ConradIrwin** [comment] 2024-08-21 22:43
Fixed by #16477

**Closed by ConradIrwin** 2024-08-21 22:43 UTC
Labels: defect, vim, search / project search
