### ISSUE TITLE
Recent projects strange behavior

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#13985] opened 2024-07-09 12:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/20476002/52183232-15cd-4e36-9e87-25e45321dc65

### Environment

```
Zed: v0.143.4 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-07-09 12:53
Duplicate of https://github.com/zed-industries/zed/issues/13595

**Closed by SomeoneToIgnore** 2024-07-09 12:53 UTC
Labels: defect, triage, admin read
