### ISSUE TITLE
Smooth movement when scrolling with a clicky mouse wheel

### ISSUE THREAD

**Issue by jansol** [zed-industries/zed#9696] opened 2024-03-22 13:33 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

E.g. Firefox scrolls in increments like Zed, but it applies a smooth acceleration/deceleration curve instead of instantly snapping to the new position like Zed does. Scrolling over several ticks seems to work additively wrt scrolling speed somehow. (Simply summing up the curves for all "in flight" scrolls at the current time?)

This acceleration/deceleration is more visually pleasing and makes unlocked Logitech "Fast Scroll" wheels (no physical ticks but still sends the same events) feel much more correct.

**Comment by Moshyfawn** [comment] 2024-03-22 22:31
I think this has already been discussed, so I'm going to close this thread in favour of the other one to keep the conversation in one place. Be sure to +👍 and add any additional information to the other thread.

Duplicate of
- #4355

**Closed by Moshyfawn** 2024-03-22 22:31 UTC
Labels: enhancement, triage, admin read
