### ISSUE TITLE
display of large files on mac errors after 16ish millionis of lines

### ISSUE THREAD

**Issue by rushrtb2112** [zed-industries/zed#21249] opened 2024-11-27 19:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have a csv file that has 17,215,111 lines and is about 3.4 GB.  After right click -> open in zed.  The file opens very quickly and all lines from 1 - 16,777,216 display correctly.  I am able to click each of these lines and edit as needed.  The lines are are not lined up the correct way though, as in the line number to the left is pixels higher than the actual text of the line.   I cannot give the complete file due to proprietary issues, but i have created a file that has the same number of lines with the same line lengths but with random chars instead and it is failing the same way.  I don't want to drop the 3.4GB file here so I'll include a screenshot of the issue.

<img width="2384" alt="Screenshot 2024-11-27 at 2 35 47 PM" src="https://github.com/user-attachments/assets/a5ef866f-1b85-404b-86b3-d8b527c02bfc">

opening this file in vim looks fine. I've included a screenshot of the same number of lines to compare.

<img width="2348" alt="Screenshot 2024-11-27 at 2 38 48 PM" src="https://github.com/user-attachments/assets/2226b27c-6a3a-4da6-b269-2ce963a3dc44">

### Environment

Mac MBP M1 Max 64GB Sonoma 14.6.1
Zed 0.157.5 6192aa14692a24f279888e0b5f781ce204bda57b

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-27 19:51
Duplicate of https://github.com/zed-industries/zed/issues/5355

**Closed by SomeoneToIgnore** 2024-11-27 19:51 UTC
Labels: bug, triage, admin read
