### ISSUE TITLE
Change HTML tags in Vim mode using multibuffers

### ISSUE THREAD

**Issue by jostjonas** [zed-industries/zed#16442] opened 2024-08-18 22:37 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

When using Zed in Vim mode and I select (ga) and change (c) multiple HTML tags at once the first character stroke behaves as expected. From the second one on, it duplicates every character for each key stroke. 

![vim-multibuffer-html-tag](https://github.com/user-attachments/assets/f271fd6e-6ef2-4e8a-a7b6-badf6c4ed307)

### Environment

Zed: v0.146.5 (Zed)
OS: Linux X11 manjaro unknown
Memory: 31 GiB
Architecture: x86_64
GPU: NVIDIA T500 || NVIDIA || 550.107.02

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-23 15:45
I know we recently fixed some bugs relating to linked edits of closing tags and you're running an older version of Zed. Could you download Zed Preview and see if the issue is still there?

**Closed** 2024-08-23 15:51 UTC
Labels: defect, vim, editor, html

**Comment by jostjonas** [comment] 2024-09-03 22:32
Seems to be working fine now. Sorry for the late response.
