### ISSUE TITLE
Improve the file explorer (left dock)

### ISSUE THREAD

**Issue by Spoutnik97** [zed-industries/zed#11433] opened 2024-05-06 12:38 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Stick the parent folder in the project panel

For big project tree (with same folder names), it is very useful to see the direct parents of the current file (like in VSCode).
The parents and grandparents are stuck on the top of the panel when I scroll down

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="176" alt="image" src="https://github.com/zed-industries/zed/assets/30442116/f31f0887-af2a-4e93-9291-0962961ec8ba">

**Comment by JosephTLyons** [comment] 2024-05-06 19:50
Hey @Spoutnik97,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/7243

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-05-06 19:50 UTC
Labels: enhancement, project panel

**Comment by Spoutnik97** [comment] 2024-05-06 21:37
Yes exactly the same. Sorry I didn't find it. Maybe the title has not the right keywords ? @JosephTLyons

**Comment by JosephTLyons** [comment] 2024-05-07 18:22
No worries - they aren't always easy to find.
