### ISSUE TITLE
Comment broken on .tsx files when using cmd + / shortcut

### ISSUE THREAD

**Issue by andrebrito16** [zed-industries/zed#16802] opened 2024-08-24 15:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When using shortcut to comment some part of code on `.tsx` files the comment should be `{/* comment */} but the editor uses `//` to comment, which is incorrect.

### Steps to reproduce:

Open any `.tsx` file and use cmd + / to comment some part of the code.

### Environment

Zed: v0.149.5 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-08-24 16:19
Duplicate of https://github.com/zed-industries/zed/issues/16337

**Closed by SomeoneToIgnore** 2024-08-24 16:19 UTC
Labels: defect, triage, admin read
