### ISSUE TITLE
In vim mode, in a CSS file, searching for next instance with `*` is broken when the word is preceded by a dash

### ISSUE THREAD

**Issue by nunoki** [zed-industries/zed#20482] opened 2024-11-10 21:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Create new file
- Set language to CSS
- Paste the following content:

```
div {
	--color: red;
}

span {
	color: var(--color);
}
```

- Set cursor somewhere within `--color`
- Press `*`

Instead of going to the next instance of either `color` or `--color`, it seems to try to search for `\-\-color` but finds nothing. (even though manually searching for `\-\-color` with `/` does find it).

This *seems* to only affect CSS files. If the language mode in this same example is changed to plain text, then it works as expected.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/1e3911ea-973b-4b9f-bebd-2cf4537957fa)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by ConradIrwin** [comment] 2024-12-03 21:04
Duplicate of #20584

**Closed by ConradIrwin** 2024-12-03 21:04 UTC
Labels: bug, vim, editor, css
