### ISSUE TITLE
Makefile support

### ISSUE THREAD

**Issue by coolcoder613eb** [zed-industries/zed#6463] opened 2024-01-25 04:48 UTC
### Check for existing issues

- [X] Completed

### Language

Makefile

### Tree Sitter parser link

https://github.com/alemuller/tree-sitter-make

**Comment by JosephTLyons** [comment] 2024-01-25 06:25
Hey @coolcoder613eb ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5366

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-01-25 06:25 UTC
Labels: enhancement, potential plugin, language, unsupported language
