### ISSUE TITLE
Error coloring of files in sidebar

### ISSUE THREAD

**Issue by AndrewJSchoen** [zed-industries/zed#10624] opened 2024-04-16 14:50 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

One nice feature of VSCode is that when a file fails a lint test, has a syntax error, or a build error, it colors the file name in the left sidebar for easy identification. Is this a feature that could be added for support in themes?
(See photos for comparison)

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="218" alt="zed" src="https://github.com/zed-industries/zed/assets/5341396/71485495-4186-4e2d-81f6-961bd7ce50ae">
<img width="207" alt="vs-code" src="https://github.com/zed-industries/zed/assets/5341396/5b277053-ae18-4ee5-822d-89d610aa020c">

**Comment by bennetbo** [comment] 2024-04-16 15:24
Hey, this looks like a duplicate of #5016, please upvote (👍🏻) this issue

**Closed by bennetbo** 2024-04-16 15:24 UTC
Labels: enhancement, triage, admin read
