### ISSUE TITLE
Menu highlights follow the cursor when another tooltip is above

### ISSUE THREAD

**Issue by shbfy** [zed-industries/zed#9570] opened 2024-03-20 10:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Menu highlights follow the cursor when another tooltip is above. Best seen and understood from the following screenshot: 

![CleanShot 2024-03-20 at 10 24 07@2x](https://github.com/zed-industries/zed/assets/26031153/a6492091-747f-4c01-8317-8515804f2d09)

I would not expect the highlight on the project view to follow the highlight in the tooltip above.

To recreate right click in the project view and move the cursor around. Obvserve how the highlighting follows both the tooltip and project view underneath.

### Environment

Zed: v0.126.3 (Zed)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

**Comment by slymax** [comment] 2024-03-20 11:11
duplicate of #9519

**Comment by Moshyfawn** [comment] 2024-03-20 14:25
Let's close this one in favour of the one already created. Make sure you +👍 the other one and add any missing information.

Duplicate of
- #9519

**Closed by Moshyfawn** 2024-03-20 14:25 UTC
Labels: defect, triage, admin read
