### ISSUE TITLE
Zed crashes after trying to make a calling

### ISSUE THREAD

**Issue by Spell28** [zed-industries/zed#7547] opened 2024-02-08 07:39 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I attempt to trying to make a call any people from my contacts Zed immediately crashes.

**Steps i take:**
1. run Zed
2. Click to Collab panel
3. Choose my contact
4. Click to '...' button
5. Click to 'Call ${UserName}

### Environment

- Zed: Preview 0.122.1
- OS: macOS 11.7.10
- Memory: 8 GiB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

**MacOS bug report:**
1. Make a call from preview to stable version of Zed: https://gist.github.com/Spell28/43dcd6046e3414a63e2d17650a631285
2. Make a call from preview to preview version of Zed: https://gist.github.com/Spell28/f54efd503047b2e95fb29b4ab311e9b0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment] 2024-02-08 21:58
Thanks for reporting this, and sorry this is crashing!

We've seen a similar issue where the service we use for calls (LiveKit) crashes on Catalina; it looks like you're on BigSur, so I suspect it is the same problem.

We will try to track this down and get it fixed, but a workaround for now may be to update your version of macOS.

**Comment by gabydd** [comment] 2024-02-08 21:58
Yeah seems to be the same panic as https://github.com/zed-industries/zed/issues/5384

**Comment by ConradIrwin** [comment] 2024-02-08 22:06
Duplicate of #5384

**Closed by ConradIrwin** 2024-02-08 22:06 UTC
Labels: defect, collaboration, panic / crash
