### ISSUE TITLE
Delete file/directory should move it to Trash instead of permanent deletion

### ISSUE THREAD

**Issue by EstebanBorai** [zed-industries/zed#10009] opened 2024-03-31 15:21 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When deleting a file currently, such file is permanently deleted without prompting the user.
It should be nice to prompt before permanently deleting the file or move to system's _trash_.

**Comment by Moshyfawn** [comment] 2024-04-01 02:55
This has already been suggested, so I'm going to close this topic in favour of the other one. Be sure to +👍 the other feature request.

Duplicate of
- #5094

**Closed by Moshyfawn** 2024-04-01 02:55 UTC
Labels: enhancement, triage, admin read
