### ISSUE TITLE
[Windows] Unable to start Zed.

### ISSUE THREAD

**Issue by kurohuji** [zed-industries/zed#18791] opened 2024-10-06 18:53 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I built Zed on a windows 11 machine.
“cargo run --release” ran without error and then target/release/zed.exe was maked.
But when I run zed.exe, Zed does not start.
However, I can see the Zed process in Task Manager.

### Environment

Windows 11 Home 23H2
rust 1.81.0

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by wqyg18** [comment] 2024-10-06 19:14
I've encountered the same issue as well. When I tried to compile the debug version, I got the following error messages:
[2024-10-07T03:11:53+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T03:11:53+08:00 ERROR theme] theme not found: macOS Classic Light
[2024-10-07T03:11:53+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T03:11:54+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-07T03:11:54+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-07T03:11:54+08:00 ERROR blade_graphics::hal::init] No composite alpha flag for transparency: OPAQUE
[2024-10-07T03:11:54+08:00 ERROR fs] Error { kind: Generic("Input watch path is neither a file nor a directory."), paths: [] }
[2024-10-07T03:11:54+08:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "参数错误。" }
[2024-10-07T03:11:54+08:00 ERROR gpui] Error { code: HRESULT(0x80070057), message: "参数错误。" }
[2024-10-07T03:11:54+08:00 ERROR assistant] no worktrees when constructing LocalLspAdapterDelegate
[2024-10-07T03:12:15+08:00 ERROR lsp] oneshot canceled

**Comment by AFellowSpeedrunner** [comment] 2024-10-06 22:48
#18705 is what you're looking for I believe.

**Comment by SomeoneToIgnore** [comment] 2024-10-06 23:37
Also duplicate of https://github.com/zed-industries/zed/issues/18610

**Closed by SomeoneToIgnore** 2024-10-06 23:37 UTC
Labels: defect, triage, admin read
