### ISSUE TITLE
Add read-only mode

### ISSUE THREAD

**Issue by zzhaolei** [zed-industries/zed#18197] opened 2024-09-22 12:31 UTC
### Check for existing issues

- [X] Completed

### Describe the feature
The most classic scenario is: `jump to source code`. Don't want to accidentally change the contents of files outside your workspace

### If applicable, add mockups / screenshots to help present your vision of the feature
Similar to  https://github.com/Microsoft/vscode/issues/4873.

**Comment by SomeoneToIgnore** [comment] 2024-09-22 15:07
Duplicate of https://github.com/zed-industries/zed/issues/5105

**Closed by SomeoneToIgnore** 2024-09-22 15:07 UTC
Labels: enhancement, triage, admin read
