### ISSUE TITLE
Per-tab tab_size and heuristically guessing tab_size

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [zed-industries/zed#16739] opened 2024-08-23 11:14 UTC
Different codebases use different tab sizes. When casually touching a new codebase, setting up a project-local tab_size configuration is too much ceremony.

In the prefect world, tab_size would be a property associated with each individual editor tab. When opening a file, tab_size could be guessed from the structure of the indents in the file. And if the guess was incorrect, there would be an option to manually override it for a specific editor tab.

Both Sublime Text and VSCode have this.

----
Sublime Text thingie from the status bar at the bottom:
<img width="398" alt="image" src="https://github.com/user-attachments/assets/a99b8492-b985-40dc-ab8b-e2874760144b">

**Comment by notpeter** [comment] 2024-09-02 01:46
Duplicate of:
- https://github.com/zed-industries/zed/issues/4681
- https://github.com/zed-industries/zed/issues/4867

**Closed by notpeter** 2024-09-02 01:46 UTC
Labels: enhancement, editor
