### ISSUE TITLE
Using vim mode. Ctrl-c in normal mode copies the current line to the clipboard.

### ISSUE THREAD

**Issue by JonathanSteininger** [zed-industries/zed#14311] opened 2024-07-12 08:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This is in vim mode.
I have set `"vim" { "use_system_clipbaord": "never"}` in my settings.json. This specifies that the system clipboard will only be used if register + or * is explicitly used.

All the named registers are working as expected until you paste from the `+` register. 
Each time you copy something on the system (outside of vim mode) the registers behave normally.
But when you use the `+` register all pastes from any registry will cause the resulting line from the paste to be copied to the system clipboard.

### Example

The system clipboard is empty so `+` is empty.
we want to copy `Hello World` from our browser. Into the "" marks in zed. using the below json example

```json
[
"testvar"=""
]
```

We copy the text `Hello World` from our browser. And paste it into the "" marks using the `+` register.
We do this with `"+p`
This will make this result:

```json
[
"testvar"="Hello World"
]
```

This is the correct result. However the system clipboard now looks like this `"testvar"="Hello World"`
And now any subsequent pastes from any registry will do the same thing. Where the resulting line gets copied to the clipboard.
if you were to copy  `testvar` from within zed by doing `^yi"` everything works correctly. But if you were to paste anywhere on the current line. The result will again be copied to the system clipboard.

We paste `testvar` at the beginning of the `Hello World` with `^fHP`.  Result:

```json
[
"testvar"="testvarHello World"
]
```
System clipboard: `"testvar"="testvarHello World"`

This behavior goes away when you copy something from the system again. (copy text from browser etc)

This makes manually using the `+` registry impossible since it breaks everything. I use that registry to gain access to my system clipboard in neovim. I like to use the named registry system. But this makes that impossible.

### Environment

Zed: v0.143.6 (Zed)
OS: Linux Wayland arch unknown
Memory: 125.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Register `+` should behave very similarly to a named register. But is shared with the system clipboard.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

```

  "buffer_font_size"ttimeimettimeimebuffer_font_size: 14,
2024-07-12T19:33:27+12:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-12T19:33:27+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T19:33:27+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T19:33:27+12:00 [INFO] Language server with id 5 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/Aureus/Source/Hazy/hazy.js"
  }
}
2024-07-12T19:33:38+12:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-12T19:33:38+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T19:33:38+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T19:33:38+12:00 [INFO] Language server with id 5 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/Aureus/Source/Hazy/hazy.js"
  }
}
2024-07-12T19:33:50+12:00 [ERROR] expected `,` or `}` at line 20 column 7
2024-07-12T19:34:22+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:34:25+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:34:29+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:34:39+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:34:41+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:34:45+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:35:01+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:43:34+12:00 [ERROR] expected `,` or `}` at line 19 column 7
2024-07-12T19:49:05+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:49:13+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:49:34+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:49:36+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:49:37+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T19:49:47+12:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-07-12T20:06:19+12:00 [INFO] Using surface present mode MAILBOX
2024-07-12T20:06:19+12:00 [WARN] Unable to forbid exclusive full screen
2024-07-12T20:07:50+12:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-12T20:07:50+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T20:07:50+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T20:07:50+12:00 [INFO] Language server with id 5 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/Aureus/Source/Hazy/hazy.js"
  }
}
2024-07-12T20:08:45+12:00 [ERROR] key must be a string at line 22 column 3
2024-07-12T20:08:45+12:00 [INFO] starting language servers for JavaScript: vtsls, tailwindcss-language-server, eslint
2024-07-12T20:08:45+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T20:08:45+12:00 [INFO] starting language servers for JSONC: json-language-server
2024-07-12T20:08:45+12:00 [INFO] Language server with id 5 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///home/Aureus/Source/Hazy/hazy.js"
  }
}
```

No errors about my issue.

</pre></details>

**Comment by ConradIrwin** [comment] 2024-07-17 03:19
@JonathanSteininger Thanks for reporting this.

I cannot reproduce this with:
* In firefox copy "blah" with `ctrl-c`
* In zed `"+p` will paste "blah" as expected
* In Firefox paste with `ctrl-v`, "blah" will be pasted again (not testvar="blah" as you report).

Did I get the reproduction steps wrong? Do you use a clipboard manager or anything else that might be getting in the way?

Also, in the mode indicator you should see `"+` if vim currently has the register selected. Is it possible that somehow you can get it into a state where `"+` stays permanently so all paste operations are using the system buffer?

Zed does write to the primary clipboard on selection, so if you selected the line it should write to the primary clipboard, but that shouldn't affect further paste operations...

**Comment by JonathanSteininger** [comment] 2024-07-20 07:25
I have done some more testing and it seem muscle memory got the better of me. I have found that my initial test were wrong and that the actual issue was with the bind `ctrl+c`. 

For come reason. If in normal mode. ctrl+c will copy the line your cursor is on to the clipboard.

Due to ctrl+c being the key bind to go to normal mode. I often press this when returning from thought or pasting/copying text. This lead me to believe that copying/pasting named registers had an issue. 

### Example of ctrl+c copying to clipboard.

The top-right window is watching the output of the system clipboard.

https://github.com/user-attachments/assets/9bf403d3-b3be-4cbd-b266-c265bc81bd70

**Comment by JonathanSteininger** [comment] 2024-07-20 07:47
In vim `ctrl-c` is meant to abort any pending commands. So its a pretty common button to press.

Shouldn't it default to not copying the line?

`ctrl-c` does still cancel any pending commands after setting it to null. (unless Im missing something)

I am altering the title to match what I have discovered.

**Comment by ConradIrwin** [comment] 2024-07-23 03:19
@JonathanSteininger Thanks for confirming! I noticed a similar bug while implementing #14942 and it should be fixed on latest main (will hit preview on Wednesday)

**Closed by ConradIrwin** 2024-07-23 03:19 UTC
Labels: defect, vim, editor
