### ISSUE TITLE
Strange behavior open remote folder

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#21339] opened 2024-11-29 15:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I open recent projects this happens:

https://github.com/user-attachments/assets/c70c4366-8917-4b09-82f3-85ffbfa8187f

### Environment

```
Zed: v0.164.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-12-02 19:16
I cannot reproduce. Do you perhaps have a custom keybind or some non-default settings which are necessary to trigger this behavior?

**Comment by notpeter** [comment] 2024-12-03 16:52
I've spawned the Open Recent dialog via menu, via command palette, keyboard shortcut and clicking on the menu bar -- on open projects, empty projects and remote projects -- but have had no luck triggering this behavior. Even with you settings and a `[]` keymap so I'm stumped. 🤷 

Let me know if you can provide more specific steps or anything notable about your environment which might help us reproduce the issue.

**Comment by notpeter** [comment] 2024-12-16 06:44
Happy to reopen if you or someone else can find steps to reproduce. 
In the meantime closing this as unactionable.

**Closed by notpeter** 2024-12-16 06:44 UTC
Labels: bug, needs info / awaiting response, remote dev, design papercut
