### ISSUE TITLE
Unable to use fonts with hyphens in their name

### ISSUE THREAD

**Issue by astatide** [zed-industries/zed#14854] opened 2024-07-20 08:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello!  On a recent Linux build, I attempted to set the `buffer_font_family` to a font name that has a ~~dash~~ hyphen-minus in it; while the autocompletion and validation works, there's no actual change in the font used, instead reverting to what is the default font.  Using another font without a hyphen (even one with a space) seems to work fine.

Please let me know if I can provide any more details or help!

EDIT: It's not _super_ easy to tell the fonts are different in the screenshots, so I added a non mono font to really make it clear.

EDIT2: based on a little trial+error/searching, it looks like the actual character is the "hyphen-minus", not one of the various flavors of dash: https://www.compart.com/en/unicode/U+002D

### Environment

Zed: v0.144.4 (Zed)
OS: Linux Wayland fedora 40
Memory: 62.7 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Default (I think) font:
![image](https://github.com/user-attachments/assets/fdf45a83-5bdb-49d5-8ed9-f4bc73e7d082)

Font with dash with no change in appearance:
![image](https://github.com/user-attachments/assets/dda8a445-2f6e-40bf-a13a-c23e803d964e)

Font without dash, with expected changes:
![image](https://github.com/user-attachments/assets/46790ce7-d936-4b97-a5ac-3828633f8de9)

Non monospaced font without dash (to emphasize the visual difference):
![image](https://github.com/user-attachments/assets/0496030d-b627-4658-9dc4-b03a0d5956cd)

Non monospaced font with dash (Inter-Bold is not a fixed width font) to help show that it is not working as expected:
![image](https://github.com/user-attachments/assets/f743c4dc-ff34-426b-83dc-f9aa4a6c1e12)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by astatide** [comment] 2024-07-20 08:25
Ah, I think I should have searched for "buffer_font_family", as I suspect this is related to the following bug report:

https://github.com/zed-industries/zed/issues/14096

**Comment by JunkuiZhang** [comment] 2024-07-20 12:31
Generally speaking, font names should not include a char like `-`.

**Comment by JosephTLyons** [comment] 2024-07-23 18:34
Thanks @astatide - I think you're right in that this is a dupe of:

- https://github.com/zed-industries/zed/issues/14096

I'll close this one out. Feel free to 👍 the aforementioned issue.

**Closed by JosephTLyons** 2024-07-23 18:34 UTC
Labels: defect, setting, font
