### ISSUE TITLE
build on ubuntu 22.04 : crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by aohanhongzhi** [zed-industries/zed#11424] opened 2024-05-06 08:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

build on ubuntu 22.04

```rust
   Compiling command_palette v0.1.0 (/home/eric/Project/Rust/zed/crates/command_palette)
   Compiling project_symbols v0.1.0 (/home/eric/Project/Rust/zed/crates/project_symbols)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 5m 13s
     Running `target/debug/Zed`
[2024-05-06T16:03:33+08:00 ERROR util] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
[2024-05-06T16:03:35+08:00 ERROR util] crates/zed/src/zed.rs:663: EOF while parsing a value at line 1 column 0
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: ERROR_INITIALIZATION_FAILED" at /home/eric/.cargo/git/checkouts/blade-b2bcd1de1cf7ab6a/e82eec9/blade-graphics/src/vulkan/init.rs:842:18
   0: Zed::reliability::init_panic_hook::{closure#0}
             at crates/zed/src/reliability.rs:83:29
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   7: <core::result::Result<ash::vk::definitions::SwapchainKHR, ash::vk::enums::Result>>::unwrap
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
      <blade_graphics::hal::Context>::resize
             at /home/eric/.cargo/git/checkouts/blade-b2bcd1de1cf7ab6a/e82eec9/blade-graphics/src/vulkan/init.rs:839:13
   8: <gpui::platform::blade::blade_renderer::BladeRenderer>::new
             at crates/gpui/src/platform/blade/blade_renderer.rs:373:28
   9: <gpui::platform::linux::x11::window::X11WindowState>::new
             at crates/gpui/src/platform/linux/x11/window.rs:254:23
  10: <gpui::platform::linux::x11::window::X11Window>::new
             at crates/gpui/src/platform/linux/x11/window.rs:310:41
  11: <gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::open_window
             at crates/gpui/src/platform/linux/x11/client.rs:595:22
  12: <gpui::platform::linux::x11::client::X11Client as gpui::platform::Platform>::open_window
             at crates/gpui/src/platform/linux/platform.rs:212:9
  13: <gpui::window::Window>::new
             at crates/gpui/src/window.rs:608:35
  14: <gpui::app::AppContext>::open_window::<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#8}>::{closure#0}
             at crates/gpui/src/app.rs:498:30
  15: <gpui::app::AppContext>::update::<gpui::window::WindowHandle<workspace::Workspace>, <gpui::app::AppContext>::open_window<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#8}>::{closure#0}>
             at crates/gpui/src/app.rs:363:22
  16: <gpui::app::AppContext>::open_window::<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#8}>
             at crates/gpui/src/app.rs:495:9
  17: <gpui::app::async_context::AsyncAppContext>::open_window::<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#8}>
             at crates/gpui/src/app/async_context.rs:154:12
  18: <workspace::Workspace>::new_local::{closure#0}::{closure#0}
             at crates/workspace/src/workspace.rs:978:17
  19: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>>> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  20: <<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>>>> as core::future::future::Future>::poll
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/async-task-4.7.0/src/runnable.rs:455:26
  21: <async_task::raw::RawTask<<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>>>>, core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>, <gpui::executor::ForegroundExecutor>::spawn::inner<core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>::{closure#0}, ()>>::run
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/async-task-4.7.0/src/raw.rs:557:17
  22: <async_task::runnable::Runnable>::run
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/async-task-4.7.0/src/runnable.rs:781:18
  23: <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}
             at crates/gpui/src/platform/linux/x11/client.rs:115:17
  24: <core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events::{closure#0}
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/mod.rs:327:61
  25: <calloop::sources::channel::Channel<async_task::runnable::Runnable> as calloop::sources::EventSource>::process_events::<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events::{closure#0}>::{closure#0}
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/channel.rs:187:32
  26: <calloop::sources::ping::eventfd::PingSource as calloop::sources::EventSource>::process_events::<<calloop::sources::channel::Channel<async_task::runnable::Runnable> as calloop::sources::EventSource>::process_events<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events::{closure#0}>::{closure#0}>::{closure#0}
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/ping/eventfd.rs:138:21
  27: <calloop::sources::generic::Generic<calloop::sources::ping::eventfd::ArcAsFd> as calloop::sources::EventSource>::process_events::<<calloop::sources::ping::eventfd::PingSource as calloop::sources::EventSource>::process_events<<calloop::sources::channel::Channel<async_task::runnable::Runnable> as calloop::sources::EventSource>::process_events<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events::{closure#0}>::{closure#0}>::{closure#0}>
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/generic.rs:290:9
  28: <calloop::sources::ping::eventfd::PingSource as calloop::sources::EventSource>::process_events::<<calloop::sources::channel::Channel<async_task::runnable::Runnable> as calloop::sources::EventSource>::process_events<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events::{closure#0}>::{closure#0}>
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/ping/eventfd.rs:127:9
  29: <calloop::sources::channel::Channel<async_task::runnable::Runnable> as calloop::sources::EventSource>::process_events::<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events::{closure#0}>
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/channel.rs:184:9
  30: <core::cell::RefCell<calloop::sources::DispatcherInner<calloop::sources::channel::Channel<async_task::runnable::Runnable>, <gpui::platform::linux::x11::client::X11Client>::new::{closure#0}>> as calloop::sources::EventDispatcher<gpui::platform::linux::x11::client::X11Client>>::process_events
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/sources/mod.rs:326:9
  31: <calloop::loop_logic::EventLoop<gpui::platform::linux::x11::client::X11Client>>::dispatch_events
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/loop_logic.rs:445:31
  32: <calloop::loop_logic::EventLoop<gpui::platform::linux::x11::client::X11Client>>::dispatch::<core::option::Option<core::time::Duration>>
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/loop_logic.rs:559:9
  33: <calloop::loop_logic::EventLoop<gpui::platform::linux::x11::client::X11Client>>::run::<<gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::run::{closure#0}, core::option::Option<core::time::Duration>>
             at /home/eric/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/calloop-0.12.4/src/loop_logic.rs:596:13
  34: <gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::run
             at crates/gpui/src/platform/linux/x11/client.rs:722:9
  35: <gpui::platform::linux::x11::client::X11Client as gpui::platform::Platform>::run
             at crates/gpui/src/platform/linux/platform.rs:129:9
  36: <gpui::app::App>::run::<Zed::init_ui::{closure#3}>
             at crates/gpui/src/app.rs:142:9
  37: Zed::init_ui
             at crates/zed/src/main.rs:233:5
  38: Zed::main
             at crates/zed/src/main.rs:445:9
  39: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  40: std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  41: std::rt::lang_start::<()>::{closure#0}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  42: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  43: std::rt::lang_start::<()>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  44: main
  45: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  46: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  47: _start


```

![image](https://github.com/zed-industries/zed/assets/37319319/c081a109-093c-4909-a644-fe4ddf259af1)

### Environment

ubuntu 22.04

**Comment by huacnlee** [comment] 2024-05-06 11:18
This is not by `settings_file.rs:76: EOF while parsing a value`, it is by `ERROR_INITIALIZATION_FAILED` `blade-graphics/src/vulkan/init.rs:842:18`.

Same issue as #11319

**Comment by Moshyfawn** [comment] 2024-05-12 00:36
This seems to be a duplicate of another issue that's being actively discussed. Be sure to +👍 and add any missing information to the other thread.

Duplicate of:
- #8168

**Closed by Moshyfawn** 2024-05-12 00:36 UTC
Labels: defect, panic / crash, linux
