### ISSUE TITLE
Vanishing pointer.

### ISSUE THREAD

**Issue by mshashikanth7** [zed-industries/zed#8676] opened 2024-03-01 16:08 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

the cursor usually vanishes as soon as we start typing on mac but this dosen't happen in zed

**Comment by Moshyfawn** [comment] 2024-03-01 18:33
Duplicate of #4461

**Comment by Moshyfawn** [comment] 2024-03-01 18:34
Make sure you +👍 the other thread and add any additional information that may be missing.

**Closed by Moshyfawn** 2024-03-01 18:33 UTC
Labels: enhancement, triage, admin read
