### ISSUE TITLE
"Close all tabs" closes even pinned tabs

### ISSUE THREAD

**Issue by DevNulPavel** [zed-industries/zed#20662] opened 2024-11-14 10:59 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello

When i pin the tab i expect that it will not be closed after `Close all tabs` command. But now it closes all tabs without pin checking.

### Environment

Zed: v0.161.1 (Zed)
OS: macOS 15.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-11-14 11:15
Can reproduce in Zed Stable; Zed Preview and Nightly + fresh `main` build have no such bug.

**Comment by SomeoneToIgnore** [comment] 2024-11-14 11:16
Oh, of course, this is due to https://github.com/zed-industries/zed/pull/19593 being merged a week ago only, hence only arriving into the Preview for now.

So, I'll close this as "fixed" in this PR, please consider switching over to https://zed.dev/releases/preview or waiting another week for the fix to come to Stable.

**Comment by SomeoneToIgnore** [comment] 2024-11-14 11:18
Sorry for the noise, I am not thinking well today apparently.
The minified comment was correct, so I'll post it again:

----------------

Oh, of course, this is due to https://github.com/zed-industries/zed/pull/19593 being merged a week ago only, hence only arriving into the Preview for now.

So, I'll close this as "fixed" in this PR, please consider switching over to https://zed.dev/releases/preview or waiting another week for the fix to come to Stable.

**Closed by SomeoneToIgnore** 2024-11-14 11:18 UTC
Labels: bug, triage, admin read
