### ISSUE TITLE
[Windows] Unable to uninstall extensions

### ISSUE THREAD

**Issue by Reynard-HanSkin** [zed-industries/zed#21501] opened 2024-12-04 02:13 UTC
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

Hello!

First, I apologize as my English might not be very fluent since it's not my native language.

I'm experiencing an issue with Zed where after installing any extension and trying to uninstall it, it doesn't work properly.

When I check the logs, I see the following error:
[ERROR] The process cannot access the file because it is being used by another process. (os error 32)

I've been continuously pulling the latest code to check, but I still can't delete the extension.

### Environment

Zed: v0.165.0 (Zed Dev 3019960f83e6852a5b9ce3706f88addce3aa2983)
OS: Windows 10.0.19045
Memory: 15.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GT 1030 || NVIDIA || 566.03

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-04T11:05:32.0283802+09:00 [INFO] installing extension html latest version
2024-12-04T11:05:33.6748545+09:00 [INFO] rebuilt extension index in 5.5295ms
2024-12-04T11:05:33.6750142+09:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-12-04T11:05:36.8208218+09:00 [ERROR] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다. (os error 32)
2024-12-04T11:05:43.4529518+09:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-04T11:05:43.4620356+09:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-04T11:05:43.4765403+09:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-12-04T11:05:43.490909+09:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-12-04T11:05:55.2053363+09:00 [ERROR] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다. (os error 32)
2024-12-04T11:05:58.2284683+09:00 [ERROR] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다. (os error 32)
2024-12-04T11:06:32.653957+09:00 [ERROR] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다. (os error 32)
2024-12-04T11:06:32.8043736+09:00 [ERROR] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다. (os error 32)
2024-12-04T11:06:32.9387693+09:00 [ERROR] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다. (os error 32)
2024-12-04T11:06:37.406537+09:00 [ERROR] oneshot canceled
2024-12-04T11:06:37.5106173+09:00 [INFO] Creating buffer 0x2eb234c4e50 of size 323232, name 'chunk-17', handle 21
2024-12-04T11:06:37.5216498+09:00 [INFO] Creating buffer 0x2ed6fbca8b0 of size 344848, name 'chunk-18', handle 22
```
</details>

**Comment by SomeoneToIgnore** [comment] 2024-12-04 07:02
Duplicate of https://github.com/zed-industries/zed/issues/18153

**Closed by SomeoneToIgnore** 2024-12-04 07:02 UTC
Labels: bug, triage, admin read

**Comment by Reynard-HanSkin** [comment] 2024-12-04 07:16
Ok. Thank you so much.

I hope this issue resolves soon :)
