### ISSUE TITLE
Partial text rendering during scrolling

### ISSUE THREAD

**Issue by xshapira** [zed-industries/zed#8374] opened 2024-02-25 09:15 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

First and foremost, thanks for all your hard work on Zed! 🚀

When scrolling through code in the editor, I'm facing an issue where the text does not fully render or appears partially until scrolling stops. This behavior disrupts the flow of code review and editing, as chunks of code are temporarily hidden or only partially shown.

https://github.com/zed-industries/zed/assets/48856190/7b1caafe-25c7-4b08-9719-c204093948dd

## Steps to Reproduce:
1. Open any file with a substantial amount of code.
2. Scroll through the file using the mouse wheel, trackpad, or scrollbar.
3. Observe the behavior of text rendering during the scrolling action.

## Expected Behavior:
The text/code should always render in full smoothly, without any delay or partial visibility.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 12.7.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by bennetbo** [comment] 2024-02-25 09:20
Looks like this could be a duplicate of #7411

**Comment by xshapira** [comment] 2024-02-25 09:48
@bennetbo You're definitely right.

**Closed** 2024-02-25 15:22 UTC
Labels: defect, triage, admin read
