### ISSUE TITLE
key binding "ctrl+`" creates an invalid character

### ISSUE THREAD

**Issue by Spoutnik97** [zed-industries/zed#4624] opened 2023-07-16 09:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I would like to open the terminal panel with the keybinding "ctrl+`" 'like on VSCode, but instead of opening a new panel, Zed write an "invalid character" in the current file. This character is invisible on Zed, but visible on VsCode 
<img width="91" alt="image" src="https://github.com/zed-industries/community/assets/30442116/f21c99c3-ba48-4c63-8b00-479fdcf25e1f">

I don't understand how to debug this

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by juliangarnier** [comment] 2024-09-19 14:35
I have a similar problem when typing `"ctrl-`"` on an AZERTY french keyboard on macos, I can't see the character, but some invisible characters are being added to the document (you can see the characters count go up)

https://github.com/user-attachments/assets/09a0fdfd-f729-4e18-8b61-283c4e04fd53

## Temporary solution

The solution was to actually type "ctrl-<" as listed in the "View" menu, even if the default key bindings is configured with :

```json
"ctrl-`": "terminal_panel::ToggleFocus",
```
![Screenshot 2024-09-19 at 16 31 22](https://github.com/user-attachments/assets/b34e0ad6-d9f1-4f8e-a01e-f3c2a568d71d)

![Screenshot 2024-09-19 at 16 24 52](https://github.com/user-attachments/assets/e4e72247-d89d-4b9c-87c2-65dff55b75a4)

Pretty sure this is a duplicate of #5195 and 5196.

Could this be resolved by #17031?

**Comment by notpeter** [comment] 2024-12-03 21:34
The original issue here (`` ctrl-` `` creates an invalid character) should be fixed in recent Zed versions.  If I am mistaken, please comment below with reproduction instructions (this does not reproduce for me in AZERTY, Spanish or US English).

If you have a similar issue please search the existing issues to see if you issue has already been reported:
- [zed issues: keybindings + internationalization](https://github.com/zed-industries/zed/issues?q=is%3Aopen+label%3A%22keymap+%2F+key+binding%22+label%3Ainternationalization)

Thanks for reporting!

**Closed by notpeter** 2024-12-03 21:34 UTC
Labels: bug, workspace
