### ISSUE TITLE
Support different sorting for project pane

### ISSUE THREAD

**Issue by reesmanp** [zed-industries/zed#8210] opened 2024-02-22 17:42 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, the project pane sorts everything alphabetically however I am coming from Jetbrains land where they have directories first then files and then things are sorted alphabetically. Having this as a settings option would be ideal.

### If applicable, add mockups / screenshots to help present your vision of the feature

![Screenshot 2024-02-22 at 9 42 25 AM](https://github.com/zed-industries/zed/assets/5932381/ae6a102c-ad75-4062-818a-2deb98d3ae90)

**Comment by SomeoneToIgnore** [comment] 2024-02-22 19:27
https://github.com/zed-industries/zed/blob/991c9ec441711a4c0b10ce595f3025f430123800/crates/project_panel/src/project_panel.rs#L1171-L1195

Here's the sorting part, one can add another setting toggle and do it differently.

**Comment by crbellis** [comment] 2024-02-25 08:41
started working on this one [here](https://github.com/crbellis/zed/tree/project-panel/dirs-first). Will comment here and submit PR once complete

**Comment by JosephTLyons** [comment] 2024-02-26 22:06
I think this is a duplicate of:

- https://github.com/zed-industries/zed/issues/4533

So Im going to close this one out.

**Closed by JosephTLyons** 2024-02-26 22:06 UTC
Labels: enhancement, project panel, setting, good first issue
