### ISSUE TITLE
vim:PageUp doesn't move cursor

### ISSUE THREAD

**Issue by jasontwong** [zed-industries/zed#17160] opened 2024-08-30 14:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When in vim mode and you page up via `ctrl-b`, the cursor does not move. When you page down via `ctrl-f`, the cursor moves.

### Environment

Zed: v0.151.0 (Zed Preview)
OS: macOS 14.6.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by ConradIrwin** [comment] 2024-09-05 15:25
Thanks for reporting this! If you'd like to pair with me on a fix: https://calendly.com/conradirwin/pairing

**Comment by haasn** [comment] 2024-09-21 16:03
This seems to be a regression, it started affecting me after updating from 150.4 to 152.3.

**Comment by ConradIrwin** [comment] 2024-09-23 15:03
I believe this is fixed in v0.154 (currently in preview). #17808

**Closed by ConradIrwin** 2024-09-23 15:03 UTC
Labels: defect, vim, editor, keymap / key binding
