### ISSUE TITLE
Gopls formatter times out when encountering a project within a project

### ISSUE THREAD

**Issue by 0sm0s1z** [zed-industries/zed#11112] opened 2024-04-27 22:04 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing go code in a subordinate working directory the gopls "timed out waiting for formatting". This issue does not exist when working against the same code but where the go.mod file is in the root of the project working directory.

```
The issue seems to me to be related to: 2024-04-27T14:41:22-07:00 [INFO] starting language server. binary path: "/Users/oz/go/bin/gopls", working directory: "/Users/oz/Projects/alistair", args: ["-mode=stdio"]
```

A workaround I've found is to call the formatter externally to the editor with something like air.

air.toml
```
cmd = "goimports -w .; go build -o ./tmp/main ."
```

![image](https://github.com/zed-industries/zed/assets/11495216/b7b7c0d2-0654-4c59-8858-33eb78367d6f)

### Environment

Zed: v0.132.3 (Zed)
OS: macOS 14.4.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

Logs:
```
2024-04-27T14:41:22-07:00 [INFO] stopping language server gopls
2024-04-27T14:41:22-07:00 [ERROR] crates/lsp/src/lsp.rs:768: oneshot canceled
2024-04-27T14:41:22-07:00 [WARN] Generic lsp request to gopls failed: oneshot canceled
2024-04-27T14:41:22-07:00 [WARN] Generic lsp request to gopls failed: oneshot canceled
2024-04-27T14:41:22-07:00 [INFO] starting language server "gopls", path: "/Users/oz/Projects/alistair", id: 16
2024-04-27T14:41:22-07:00 [ERROR] crates/project/src/project.rs:6892: oneshot canceled
2024-04-27T14:41:22-07:00 [ERROR] crates/editor/src/editor.rs:3852: oneshot canceled
2024-04-27T14:41:22-07:00 [INFO] found user-installed language server for Go. path: "/Users/oz/go/bin/gopls", arguments: ["-mode=stdio"]
2024-04-27T14:41:22-07:00 [INFO] starting language server. binary path: "/Users/oz/go/bin/gopls", working directory: "/Users/oz/Projects/alistair", args: ["-mode=stdio"]
2024-04-27T14:41:23-07:00 [INFO] Language server with id 16 sent unhandled notification client/unregisterCapability:
{
  "unregisterations": [
    {
      "id": "workspace/didChangeWatchedFiles-0",
      "method": "workspace/didChangeWatchedFiles"
    }
  ]
}
2024-04-27T14:42:55-07:00 [WARN] timed out waiting for formatting
2024-04-27T14:42:58-07:00 [WARN] timed out waiting for formatting
```

**Comment by Moshyfawn** [comment] 2024-04-29 13:01
Does #10224 sound like your use-case?

**Comment by 0sm0s1z** [comment] 2024-04-29 15:14
Yes, I think this is the same issue. I can reproduce the same errors in the log as that issue as well. Feel free to merge/remove this one.

**Comment by Moshyfawn** [comment] 2024-04-29 15:16
Be sure to +👍 the other issue and possibly add any additional information to the other thread if needed.

Duplicate of:
- #10224

**Closed by Moshyfawn** 2024-04-29 15:16 UTC
Labels: defect, needs info / awaiting response, language, go, admin read, language server
