### ISSUE TITLE
Format selection (but not the entire file)

### ISSUE THREAD

**Issue by ThomasGysemans** [zed-industries/zed#13969] opened 2024-07-09 07:17 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'm new at Zed and I have noticed that there is no way to just format a selection. The only solution to re-format code is to re-format the entire file. I'd like to use the equal sign "=" to format a selection just like I do in Vim

### If applicable, add mockups / screenshots to help present your vision of the feature

![selection](https://github.com/zed-industries/zed/assets/65554138/768d93c0-0c67-4a3e-96e4-af57442e58a2)

**Comment by notpeter** [comment] 2024-07-09 20:49
Duplicate of 
- #5026

Please vote 👍 on that issue and subscribe to track it's progress.

**Closed by notpeter** 2024-07-09 20:49 UTC
Labels: enhancement, editor
