### ISSUE TITLE
Transparent Window Border when Zed not focused (Linux)

### ISSUE THREAD

**Issue by aritlh** [zed-industries/zed#17333] opened 2024-09-04 02:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/9525ff32-d214-405e-8455-e5b1483192df)

I found a bug in the zed window border. when I focus on another window, the top zed window border looks transparent.

### Environment

```bash
Linux domainstire 6.6.48-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 17:56:14 +0000 x86_64 GNU/Linux
model name	: Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
```

**Comment by jansol** [comment] 2024-09-04 09:02
Update your copy of Zed: #15709

**Comment by notpeter** [comment] 2024-09-04 19:01
Thank you @jansol, this is likely a duplicate of 
- https://github.com/zed-industries/zed/pull/15709

@aritlh In the future please follow the github issue template. We definitely don't need /proc/cpuinfo for each of your processor cores, but we do need a copy of version information from you can get from inside Zed by running ctrl-shift-p, "copy system specs to clipboard".  Thanks.

**Closed by notpeter** 2024-09-04 19:01 UTC
Labels: defect, triage, admin read

**Comment by aritlh** [comment] 2024-09-04 22:26
> Thank you @jansol, this is likely a duplicate of 
> - https://github.com/zed-industries/zed/pull/15709
> 
> @aritlh In the future please follow the github issue template. We definitely don't need /proc/cpuinfo for each of your processor cores, but we do need a copy of version information from you can get from inside Zed by running ctrl-shift-p, "copy system specs to clipboard".  Thanks.


Thank you for your advice. Sorry if I'm still a newbie in reporting a bug.
