### ISSUE TITLE
Information popup stays open when you hover away from the identifier

### ISSUE THREAD

**Issue by RemcoSmitsDev** [zed-industries/zed#7670] opened 2024-02-11 14:12 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The information popup keeps over when you hover away to a place that does not contain text. It will hide again when you hover over an identifier or click somewhere.

https://github.com/zed-industries/zed/assets/62463826/5efcc449-60b5-4e92-a855-93c2ab500356

### Environment

Zed: v0.122.2 (Zed Preview)
OS: macOS 14.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by RemcoSmitsDev** [comment] 2024-03-05 17:56
https://github.com/zed-industries/zed/issues/8340

**Comment by Moshyfawn** [comment] 2024-03-05 18:05
I'm going to close this issue in favour of the other one, simply because the latter has gained a bit more traction and still covers tooltip hover behaviour in general.

**Comment by Moshyfawn** [comment] 2024-03-05 18:05
Duplicate of #8340

**Closed by Moshyfawn** 2024-03-05 18:05 UTC
Labels: defect, popovers
