### ISSUE TITLE
Support hide window bar and status bar

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#6862] opened 2024-01-27 13:34 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

same https://github.com/zed-industries/zed/issues/4382
I know it can be used `shift+esc`, but I want to hide these two locations
<img width="1535" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/893d6266-4c30-462d-887b-bbe49ec6ee36">

**Comment by eur2** [comment] 2024-02-11 16:57
Hi, it would be fantastic to have the possibility to hide the different top bar with the filename. By default, it's showing it three times. It's also taking the space of 3 cm height on my laptop ;)
<img width="258" alt="Capture d’écran 2024-02-11 à 17 51 50" src="https://github.com/zed-industries/zed/assets/28712725/b8376d6d-996b-4331-86c7-5c3f1beec941">

**Comment by JosephTLyons** [comment] 2024-03-10 03:07
Hey @d1y,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5120

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-03-10 03:07 UTC
Labels: enhancement, workspace, setting, status bar

**Comment by battall** [comment] 2024-03-24 21:27
> Hi, it would be fantastic to have the possibility to hide the different top bar with the filename. By default, it's showing it three times. It's also taking the space of 3 cm height on my laptop ;) <img alt="Capture d’écran 2024-02-11 à 17 51 50" width="258" src="https://private-user-images.githubusercontent.com/28712725/303934152-b8376d6d-996b-4331-86c7-5c3f1beec941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMTQ3NTIsIm5iZiI6MTcxMTMxNDQ1MiwicGF0aCI6Ii8yODcxMjcyNS8zMDM5MzQxNTItYjgzNzZkNmQtOTk2Yi00MzMxLTg2YzctNWMzZjFiZWVjOTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDIxMDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNDM5MDEwYzQyMDI2MmZmNDgxOGIyNTM2YzRmZDI4OWY2ZWE3YjM0MTIwNjgzZmNhZWM2MjFiNTcyOTFhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TM4v6sHgIGCDNMK9aMLDJv6GbNsLmoUu3ZYSXdRvMR0">

it is unrelated and worse place on earth to ask i know but which theme is this? looks so nice

**Comment by Moshyfawn** [comment] 2024-03-24 21:39
> it is unrelated and worse place on earth to ask i know but which theme is this? looks so nice

Pretty sure it's one of the recently added theme extensions: [Vesper](https://github.com/bdsqqq/vesper-zed/tree/26f78e7a84515a658614fede8889e3c8b4646795).

<img width="1394" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/22ea34fa-6aa2-4444-a5d6-2b5540bad19e">
