### ISSUE TITLE
basic key function is not working

### ISSUE THREAD

**Issue by vs11official** [zed-industries/zed#12722] opened 2024-06-06 08:27 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I try to delete a line, it selects the line and I am unable to move to the next line by pressing Return. Instead, everything seems to be working when I press Shift Command and basic keys are working properly.

### Environment

Zed: v0.138.4 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-06-07 14:40
This does sound like the IME pre-edit issue mentioned above. I'm going to optimistically close this issue in favour of the other one, but feel free to let us know if it's unrelated and we can re-open it. Otherwise, be sure to follow up if the above commit has fixed your problem, either in the next release or by building Zed from source with it.

Duplicate of:
- #11829

**Closed by Moshyfawn** 2024-06-07 14:40 UTC
Labels: defect, triage, admin read
