### ISSUE TITLE
exclude specific file from prompt /file command

### ISSUE THREAD

**Issue by MaxThom** [zed-industries/zed#21012] opened 2024-11-21 19:46 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I have a prompt library with the following:
```
/file mir-go/book/src/
/file mir-go/examples/
```

I currently hit a context of 400 000 tokens. But in all those files and folder, 2 svg files take about 350k tokens. It it possible to exclude file or folders ?

### Environment

EndeavorOS (ArchLinux)

**Comment by notpeter** [comment] 2024-12-05 20:12
Duplicate of:
- https://github.com/zed-industries/zed/issues/19725

**Closed by notpeter** 2024-12-05 20:12 UTC
Labels: enhancement, triage, admin read
