### ISSUE TITLE
press `control + H` in editor crashes in Remote Development in macOS

### ISSUE THREAD

**Issue by tibitTW** [zed-industries/zed#21158] opened 2024-11-25 10:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. connect to an remote environment and open a file
2. press `control` + `H`
3. zed will crash

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 15.1.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary>

[Zed.log](https://github.com/user-attachments/files/17901409/Zed.log)
</details>

**Comment by notpeter** [comment] 2024-11-25 16:19
I am not able to reproduce this with Zed `v0.162.5`.
Can you provide more details reproduction steps?
You panics shows it happening in `multi_buffer.rs` are you searching or doing an LSP action (find all references, etc) when it crashes?

<details><summary>example panic</summary>

```
2024-11-25T18:36:11.190477+08:00 [ERROR] {
  "thread": "main",
  "payload": "offset is out of range",
  "location_data": {
    "file": "crates/multi_buffer/src/multi_buffer.rs",
    "line": 5059
  },
  "backtrace": [
    "backtrace::capture::Backtrace::create",
    "backtrace::capture::Backtrace::new",
    "zed::reliability::init_panic_hook::{{closure}}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "editor::Editor::select_autoclose_pair",
    "editor::Editor::backspace",
    "editor::element::register_action::{{closure}}",
    "gpui::window::WindowContext::dispatch_action_on_node",
    "gpui::window::WindowContext::dispatch_event",
    "gpui::window::Window::new::{{closure}}",
    "gpui::platform::mac::window::handle_key_event",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "gpui::app::App::run",
    "zed::main",
    "std::sys::backtrace::__rust_begin_short_backtrace",
    "std::rt::lang_start::{{closure}}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.162.5",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "15.1.1",
  "architecture": "aarch64",
  "panicked_on": 1732530971190,
  "system_id": "cc04815f-9b4b-4ef5-9f52-6a2f7316f432",
  "installation_id": "a8ed9431-c09d-43b1-b1f3-f14de416fcad",
  "session_id": "3e39af03-e4c1-44d0-91b4-adf3addcd3da"
}
```

</details>

Do you have a custom keybind for `ctrl-h`?  The default `ctrl-h` keybinds are:
https://github.com/zed-industries/zed/blob/385c447bbe7c2fb40fef0296aef7a4d1725fbbf4/assets/keymaps/default-macos.json#L47

And if you are in vim literal mode:
https://github.com/zed-industries/zed/blob/385c447bbe7c2fb40fef0296aef7a4d1725fbbf4/assets/keymaps/vim.json#L488

**Comment by tibitTW** [comment] 2024-11-26 03:48
@notpeter Hi, there're some information I can offer

> I am not able to reproduce this with Zed `v0.162.5`. Can you provide more detailed reproduction steps?

I noticed that may happens when the editor cursor is at the beginning of file, it seems fit the error payload

> You panics shows it happening in `multi_buffer.rs` are you searching or doing an LSP action (find all references, etc) when it crashes?

No, I just open a file and didn't do any action manually

> Do you have a custom keybind for `ctrl-h`? The default `ctrl-h` keybinds are:
> 
> https://github.com/zed-industries/zed/blob/385c447bbe7c2fb40fef0296aef7a4d1725fbbf4/assets/keymaps/default-macos.json#L47
> 
> And if you are in vim literal mode:
> 
> https://github.com/zed-industries/zed/blob/385c447bbe7c2fb40fef0296aef7a4d1725fbbf4/assets/keymaps/vim.json#L488

I keep the keybind as default, and i didn't enter the literal mode

I tried the same keybind in other position of the file, it do backspace and didn't crash, so I think this may only happens when the cursor at beginning of file

I also tried in local project and didn't meet this issue

Hope these information may help you!

**Comment by notpeter** [comment] 2024-11-26 18:50
Closing in favor of this:
- https://github.com/zed-industries/zed/issues/14961

Because it has repro instructions.
Thanks for reporting.

**Closed by notpeter** 2024-11-26 18:50 UTC
Labels: bug, panic / crash, remote dev
