### ISSUE TITLE
"hover" menu does not properly render whitespace in docstrings

### ISSUE THREAD

**Issue by universalmind303** [zed-industries/zed#16296] opened 2024-08-15 14:44 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

if i have a docstring that has indentation, it is rendered as `&nbsp` 

```py
def hello():
    """lorem ipsum dolor sit amet, consectetur adipiscing elit.
    
    Args:
        arg_1: lorem ipsum
    
    Returns:      
        
        Foo: lorem ipsum dolor sit amet
    
    """
    ...


hello()
```

![image](https://github.com/user-attachments/assets/2e0f6ef4-1ca7-4c14-b1b9-78503f78fdec)

for a more detailed example, here is a short clip showing the error in a popular dataframe library. 

https://github.com/user-attachments/assets/7cba8088-477f-4860-8745-d19d3d92cad2

### Environment

Zed: v0.148.1 (Zed)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by failable** [comment] 2024-08-15 14:47
Related: https://github.com/zed-industries/zed/issues/15463

**Comment by notpeter** [comment] 2024-08-15 15:38
Closing as a duplicate of:
- https://github.com/zed-industries/zed/issues/15463
- https://github.com/zed-industries/zed/issues/16296

**Closed by notpeter** 2024-08-15 15:38 UTC
Labels: defect, triage, admin read
