### ISSUE TITLE
Hide certain visual elements

### ISSUE THREAD

**Issue by photex** [zed-industries/zed#4963] opened 2023-03-12 12:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Howdy!

First thing I tried to find in the settings was a way to hide tabs and line numbers. Second was to hide the current line highlight (or caret row highlight). 

I’d love to see these settings show up in an update (or I’d love to find out I just missed them and they’re already available).

**Comment by ConradIrwin** [comment] 2024-02-23 03:38
Closing this as a duplicate of https://github.com/zed-industries/zed/issues/4382.

In good news, line number hiding will ship in zed `0.125.0`, you can add this to your settings:

`"gutter": {"line_numbers": false,    "code_actions": false,    "folds": false}`

**Closed by ConradIrwin** 2024-02-23 03:38 UTC
Labels: enhancement, tabs, setting
