### ISSUE TITLE
org.freedesktop.portal.Error.NotFound

### ISSUE THREAD

**Issue by viktorandreevichmorozov** [zed-industries/zed#12877] opened 2024-06-11 06:30 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Does not start on linux 

```
git clone https://github.com/zed-industries/zed.git
rustup update
./script/linux
cargo build --release
WAYLAND_DISPLAY='' ./target/release/zed
```

### Environment

Linux code 5.15.0-105-generic #115~20.04.1-Ubuntu SMP Mon Apr 15 17:33:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

XDG_SESSION_TYPE=x11

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
[2024-06-11T09:17:47+03:00 ERROR util] crates/gpui/src/platform/linux/platform.rs:110: Portal request failed: org.freedesktop.portal.Error.NotFound: Requested setting not found
Thread "main" panicked with "called `Result::unwrap()` on an `Err` value: NotSupportedError" at crates/gpui/src/platform/linux/x11/window.rs:348:14
   0: zed::reliability::init_panic_hook::{closure#0}
             at crates/zed/src/reliability.rs:54:29
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   7: <core::result::Result<blade_graphics::hal::Context, blade_graphics::NotSupportedError>>::unwrap
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
      <gpui::platform::linux::x11::window::X11WindowState>::new
             at crates/gpui/src/platform/linux/x11/window.rs:338:13
      <gpui::platform::linux::x11::window::X11Window>::new
             at crates/gpui/src/platform/linux/x11/window.rs:431:41
      <gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::open_window
             at crates/gpui/src/platform/linux/x11/client.rs:930:22
   8: <gpui::window::Window>::new
             at crates/gpui/src/window.rs:624:35
   9: <gpui::app::AppContext>::open_window::<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#13}>::{closure#0}
             at crates/gpui/src/app.rs:497:30
      <gpui::app::AppContext>::update::<gpui::window::WindowHandle<workspace::Workspace>, <gpui::app::AppContext>::open_window<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#13}>::{closure#0}>
             at crates/gpui/src/app.rs:362:22
      <gpui::app::AppContext>::open_window::<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#13}>
             at crates/gpui/src/app.rs:494:9
      <gpui::app::async_context::AsyncAppContext>::open_window::<workspace::Workspace, <workspace::Workspace>::new_local::{closure#0}::{closure#0}::{closure#13}>
             at crates/gpui/src/app/async_context.rs:154:17
      <workspace::Workspace>::new_local::{closure#0}::{closure#0}
             at crates/workspace/src/workspace.rs:998:17
  10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>>> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
      <<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>>>> as core::future::future::Future>::poll
             at /home/code/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:455:26
      <async_task::raw::RawTask<<async_task::runnable::Builder<_>>::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>>>>, core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>, <gpui::executor::ForegroundExecutor>::spawn::inner<core::result::Result<(gpui::window::WindowHandle<workspace::Workspace>, alloc::vec::Vec<core::option::Option<core::result::Result<alloc::boxed::Box<dyn workspace::item::ItemHandle>, anyhow::Error>>>), anyhow::Error>>::{closure#0}, ()>>::run
             at /home/code/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:557:17
  11: <calloop::loop_logic::EventLoop<gpui::platform::linux::x11::client::X11Client>>::dispatch_idles
             at /home/code/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/loop_logic.rs:542:13
      <calloop::loop_logic::EventLoop<gpui::platform::linux::x11::client::X11Client>>::dispatch::<core::option::Option<core::time::Duration>>
             at /home/code/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/loop_logic.rs:560:9
      <calloop::loop_logic::EventLoop<gpui::platform::linux::x11::client::X11Client>>::run::<<gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::run::{closure#0}, core::option::Option<core::time::Duration>>
             at /home/code/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/loop_logic.rs:596:13
      <gpui::platform::linux::x11::client::X11Client as gpui::platform::linux::platform::LinuxClient>::run
             at crates/gpui/src/platform/linux/x11/client.rs:1094:9
  12: <gpui::platform::linux::x11::client::X11Client as gpui::platform::Platform>::run
             at crates/gpui/src/platform/linux/platform.rs:146:9
  13: <gpui::app::App>::run::<zed::main::{closure#2}>
             at crates/gpui/src/app.rs:141:9
  14: zed::main
             at crates/zed/src/main.rs:328:5
  15: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
      std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  16: std::rt::lang_start::<()>::{closure#0}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  18: main
  19: __libc_start_main
             at /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
  20: _start
```

**Comment by someone13574** [comment] 2024-06-11 17:42
You need to have a desktop portal installed: https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces

**Comment by JosephTLyons** [comment] 2024-06-11 21:16
Let us know if that fixes it for your, @viktorandreevichmorozov!

**Comment by igorsol** [comment] 2024-06-11 21:43
I have the same issue on Ubuntu 20.04.
xdg-desktop-portal and xdg-desktop-portal-gtk packages are installed

**Comment by tmke8** [comment] 2024-06-12 11:08
I'm guessing the portal that's running doesn't support the `appearance` setting?

https://github.com/zed-industries/zed/blob/ec95a33d8cfc2ccbf59764d8cd00a779bdb63928/crates/gpui/src/platform/linux/platform.rs#L110

Does this succeed?
```
busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings ReadOne ss "org.freedesktop.appearance" "color-scheme"
```
On my machine this returns
```
v u 0
```

**Comment by igorsol** [comment] 2024-06-12 11:13
```
$ busctl --user call org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings ReadOne ss "org.freedesktop.appearance" "color-scheme"
Call failed: No such method “ReadOne”
```

**Comment by tmke8** [comment] 2024-06-12 11:16
I believe [Darkman](https://gitlab.com/WhyNotHugo/darkman) provides that dbus setting; see implementation here:

https://gitlab.com/WhyNotHugo/darkman/-/blob/239e08b4ec94fe9f76ede2468cba51a0ceb6cccf/portal.go#L200-203

So, you could try installing Darkman.

But anyway, Zed should not crash if the dbus setting can't be found.

**Comment by tmke8** [comment] 2024-06-12 12:19
Sorry, `xdg-desktop-portal-gtk` actually supports `org.freedesktop.appearance` [since version 1.12.0](https://github.com/flatpak/xdg-desktop-portal-gtk/blob/32e118649766b92b3a220ece31208dab82339fef/NEWS#L47). So, either your version is too old or it's not running correctly.

**Comment by igorsol** [comment] 2024-06-12 13:53
Well, I have `xdg-desktop-portal-gtk` version 1.6.0 on this system

**Comment by apricotbucket28** [comment] 2024-06-15 23:39
The issue here is not the missing color-scheme portal (the log is benign, it defaults to the light color scheme in case the portal is missing). In this case the error seems to be that Blade initialization failed.

**Comment by ConradIrwin** [comment] 2024-06-25 17:23
I think this is a duplicate of #13441, and we need some more tools to deal with GPU errors.

**Closed by ConradIrwin** 2024-06-25 17:23 UTC
Labels: defect, panic / crash, needs info / awaiting response, linux
