### ISSUE TITLE
Why does UI act strange?

### ISSUE THREAD

**Issue by essamamdani** [zed-industries/zed#13330] opened 2024-06-20 19:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![Screen Shot 2024-06-21 at 12 19 23 AM](https://github.com/zed-industries/zed/assets/413629/08fab517-995b-416c-88a2-4dce60e79cb1)

### Environment

![Screen Shot 2024-06-21 at 12 21 12 AM](https://github.com/zed-industries/zed/assets/413629/16a2545d-9f96-4dea-a6e7-956bcd2da008)
![Screen Shot 2024-06-21 at 12 21 25 AM](https://github.com/zed-industries/zed/assets/413629/41e3edef-27b9-4eb6-a8fa-25f809396db7)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by bennetbo** [comment] 2024-06-20 19:32
Hey, this looks like a duplicate of #6853?

**Comment by notpeter** [comment] 2024-06-20 20:17
Closing this as duplicate of #6853.

It appears to be an issue isolated to Intel Macs with Nvidia graphics cards. Hopefully we can track that one down.  Please 👍 to vote on that issue and subscribe to track progress.

**Closed by notpeter** 2024-06-20 20:17 UTC
Labels: defect, triage, admin read
