### ISSUE TITLE
Images not updating / still cached

### ISSUE THREAD

**Issue by patrick-schuster** [zed-industries/zed#19089] opened 2024-10-11 19:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After creating a PNG file using the attached code, opening it in zed, and creating another PNG with the same name but different content, zed does not update the picture in the editor, even after closing the image and opening it again.

Reproduce using the following steps:
1. Compile image.c (e.g. gcc image.c)
2. Execute the compiled program
3. Open image.png in zed (should show a transparent image)
4. Change the hex code in image.c from 0x0 to 0xFFFFFFFF
5. Recompile image.c
6. Execute the compiled program
7. Zed will still show the old image (transparent) instead of the new image (white), even after closing and opening it

Source code: [src.zip](https://github.com/user-attachments/files/17346580/src.zip)

### Environment

Zed: v0.156.1 (Zed)
OS: macOS 15.0.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-11 19:12
Duplicate of:
- #11529

**Closed by notpeter** 2024-10-11 19:12 UTC
Labels: defect, triage, admin read
