### ISSUE TITLE
Defining Workspace behavior

### ISSUE THREAD

**Issue by wgordon17** [zed-industries/zed#9887] opened 2024-03-27 19:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, when closing Zed, it retains the last used workspace. I would like the option to have a clean workspace upon every start, and only open a workspace if provided on the terminal

**Comment by Moshyfawn** [comment] 2024-03-27 20:05
Related #9874

**Comment by notpeter** [comment] 2024-06-27 17:21
I'm going to close this as a duplicate of:
- #7759

Please 👍 that issue to vote and subscribe there to track the progress.
If this is in error, please leave a comment and/or reopen with clarification.

**Closed by notpeter** 2024-06-27 17:21 UTC
Labels: enhancement, workspace, setting, serialization
