### ISSUE TITLE
Not able to format some JSON files

### ISSUE THREAD

**Issue by amesas** [zed-industries/zed#7227] opened 2024-02-01 16:26 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I try to format some medium sized json files, the format command does nothing.

Syntax Highliting works, just JSON does not get formatted.

### Environment

Zed 0.121

### If applicable, add mockups / screenshots to help explain present your vision of the feature

JSON should get formatted.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by matejcerny** [comment] 2024-02-05 10:14
From my experiments it looks like only saved files can be formatted, which is a bummer 😞

**Comment by eproxus** [comment] 2024-03-04 09:37
This is tracked in #4529 (I think)

**Comment by Moshyfawn** [comment] 2024-03-05 02:39
Saved files are formatted correctly and @eproxus is right (thanks!), the issue is already being tracked.

**Comment by Moshyfawn** [comment] 2024-03-05 02:40
Duplicate of #4529

**Closed by Moshyfawn** 2024-03-05 02:40 UTC
Labels: defect, json, language

**Comment by KaKi87** [comment] 2024-12-21 17:07
Hello,
I don't understand how the linked issue solves this ?
I'm not trying to install a custom formatter.
Thanks
