### ISSUE TITLE
Set file syntax for code highlighting from command palette

### ISSUE THREAD

**Issue by mattgiles** [zed-industries/zed#10020] opened 2024-03-31 23:25 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

[[Update: I did just find the language selector at the bottom right of the window! Great! I would still love to be able to do this by searching the command palette and without memorizing some hot key beyond CTRL+SHIFT+P.]]

Often times I just need a buffer for temporary code. Maybe because I want the editor's multi-cursor, or because I want to paste in some snippet as an example to have on screen for reference, or because I'm going to ultimately put/save/run the code elsewhere and just need the buffer to type it out (e.g. a SQL query or Markdown text).

Other times I will ultimately want to save to a file with a file extension that will tell Zed what's up, but I don't want to have to worry about the order of operations / don't always know that what I'm scribbling down will be worth saving etc.

Although I use Zed as my primary editor at this point, in these cases I still reach for Sublime.

And that is because, in Sublime, from the command palette, I can reap the benefits of code highlights in my ephemeral buffer with:

```
`Set Syntax: {language}`
```

It would be awesome to be able to do this in Zed.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1010" alt="image" src="https://github.com/zed-industries/zed/assets/4960227/057be1fd-8a4c-4028-a96e-9592c12ac4aa">

<img width="995" alt="image" src="https://github.com/zed-industries/zed/assets/4960227/9e9feacd-01b8-4670-a2bf-3e3a7a0d2d9a">

**Comment by Moshyfawn** [comment] 2024-04-01 02:16
Although there are 2 context menus instead of 1 as in Sublime, there is a `language selector: toggle` command in the Command Palette that you can select to switch the language of your files. Does that suffice your use-case?

**Comment by mattgiles** [comment] 2024-04-02 01:45
Yes. For sure it does. Thanks!

I haven't put much thought into what it must mean to govern the main context menu, but it might make sense to hoist the language-specific keywords of the second context menu into the main context menu, or to alias "language" with things cognate with syntax or highlighting. Something so this would be more discoverable.

**Comment by Moshyfawn** [comment] 2024-04-02 03:05
> I haven't put much thought into what it must mean to govern the main context menu, but it might make sense to hoist the language-specific keywords of the second context menu into the main context menu, or to alias "language" with things cognate with syntax or highlighting. Something so this would be more discoverable.

There is a feature request for the behaviour you describe. Let's move this conversation to the other thread to keep it in one place, but feel free to add your thoughts and +👍 to show your interest.

Duplicate of
- #8814

**Closed by Moshyfawn** 2024-04-02 03:05 UTC
Labels: enhancement, needs info / awaiting response, editor, admin read
