### ISSUE TITLE
gpu hung. freeze then blackscreen

### ISSUE THREAD

**Issue by deng232** [zed-industries/zed#17216] opened 2024-08-31 19:33 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

not certain. just open a workspace and freeze in anytime

### Environment

Nixos, unstable channel. Hyprland window manager

Zed: v0.149.6 (Zed)
OS: Linux Wayland nixos 24.11
Memory: 31.2 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 3080 Ti || NVIDIA || 560.35.03

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-08-31T15:15:03.303396446-04:00 [INFO] Using surface present mode MAILBOX
2024-08-31T15:15:03.303436516-04:00 [WARN] Unable to forbid exclusive full screen
2024-08-31T15:15:03.665690988-04:00 [INFO] Using surface present mode MAILBOX
2024-08-31T15:15:03.665822533-04:00 [WARN] Unable to forbid exclusive full screen
2024-08-31T15:15:10.026667423-04:00 [INFO] Using surface present mode MAILBOX
2024-08-31T15:15:10.02681667-04:00 [WARN] Unable to forbid exclusive full screen
2024-08-31T15:15:10.058178467-04:00 [INFO] Initializing default prettier with plugins {}
2024-08-31T15:15:10.05821714-04:00 [INFO] starting language servers for TOML: taplo
2024-08-31T15:15:10.058236-04:00 [INFO] starting language server "taplo", path: "/home/deng/rust-env/ppgen", id: 2
2024-08-31T15:15:10.058354427-04:00 [INFO] Initializing default prettier with plugins {}
2024-08-31T15:15:10.058374106-04:00 [INFO] Initializing default prettier with plugins {}
2024-08-31T15:15:10.058391754-04:00 [INFO] starting language servers for TOML: taplo
2024-08-31T15:15:10.058409519-04:00 [INFO] starting language servers for Rust: rust-analyzer
2024-08-31T15:15:10.059276959-04:00 [WARN] request completed with error: failed to connect to the server
2024-08-31T15:15:10.253735696-04:00 [INFO] Using surface present mode MAILBOX
2024-08-31T15:15:10.253786419-04:00 [WARN] Unable to forbid exclusive full screen
2024-08-31T15:15:10.422500585-04:00 [INFO] starting language server. binary path: "/home/deng/.local/share/zed/extensions/work/toml/taplo-0.9.3/taplo", working directory: "/home/deng/rust-env/ppgen", args: ["lsp", "stdio"]
2024-08-31T15:15:10.663214399-04:00 [INFO] Initializing default prettier with plugins {}
2024-08-31T15:15:10.663391332-04:00 [INFO] starting language servers for TOML: taplo
2024-08-31T15:15:10.677469688-04:00 [INFO] Using surface present mode MAILBOX
2024-08-31T15:15:10.677545051-04:00 [WARN] Unable to forbid exclusive full screen
2024-08-31T15:15:25.769934836-04:00 [ERROR] GPU hung
</pre></details>

**Comment by notpeter** [comment] 2024-09-02 02:57
Perhaps duplicate of:
- https://github.com/zed-industries/zed/issues/17129

**Closed** 2024-09-02 02:58 UTC
Labels: defect, triage, admin read
