### ISSUE TITLE
Line is indented when backspacing

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5018] opened 2023-02-05 03:11 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I found this by running the `open licenses` command, scrolling to the very bottom, and quickly backspacing until the cursor lines on the divider line.

### Environment

Zed: v0.72.0 (preview)
OS: macOS 13.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/19867440/216799532-69f689dd-0e86-4d91-9d31-dbd58d27e51a.mov

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by notpeter** [comment] 2024-06-21 17:19
I can't reproduce this behavior. Closing.

**Closed by notpeter** 2024-06-21 17:19 UTC
Labels: defect, editor
