### ISSUE TITLE
"Open Recent" Action for Files

### ISSUE THREAD

**Issue by bbb651** [zed-industries/zed#14902] opened 2024-07-21 09:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently there is an "Projects: Open Recent" action that shows a picker for recently opened projects.
I suggest adding a "Workspace: Open Recent" action, that similarly shows a picker but for recently opened files rather than recently opened projects, and should also be on the menubar under files/hamburger menu the same way recent projects are.

I'm on linux where the dock isn't implemented, but from what I understand from the `Platform` trait and #12068 the dock shows recent file entries, this feature is different and solves a different use case (mainly opening recent files in the same workspace while you're already in the editor, with the dock you're probably not going to have the editor focused and it might make sense to open as a new workspace) but it does solve the question of "when is a file considered open?" (in my opinion, it should be anything that is explicitly opened with "Workspace: Open", dragged into editor, or opened from the cli, but filter out files that belong to a currently open projects and Zed related files like the settings and keymap).

**Comment by notpeter** [comment] 2024-07-26 14:01
Duplicate of
- https://github.com/zed-industries/zed/issues/4663

**Closed by notpeter** 2024-07-26 14:01 UTC
Labels: enhancement, triage, admin read
