### ISSUE TITLE
`AddSelectionAbove` and `AddSelectionBelow` skip lines shorter than cursor column

### ISSUE THREAD

**Issue by neunato** [zed-industries/zed#15728] opened 2024-08-03 09:38 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Recurrence of https://github.com/zed-industries/zed/issues/1046

### Environment

Zed: v0.146.4 (Zed)
OS: Linux X11 arch unknown
Memory: 62.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 with Max-Q Design || NVIDIA || 555.58.02

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/b63c81dd-0117-45fa-b055-48e6560b1600

**Comment by JosephTLyons** [comment] 2024-08-06 16:08
Hey @neunato,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5255

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-08-06 16:08 UTC
Labels: defect, editor
