### ISSUE TITLE
Auto close tag

### ISSUE THREAD

**Issue by Xtramemium** [zed-industries/zed#10072] opened 2024-04-02 10:56 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Hello! Want request the auto close tag feature. I suggest feature can be enabled/disabled in settings

Example: When you typing any tag like `<div>` Zed automatically closing `</div>` or any HTML tag, suppose it must work with any JS framework

I think its can significantly improve developing speed.

**Comment by widersky** [comment] 2024-04-02 14:50
https://github.com/zed-industries/zed/issues/5267

**Comment by Moshyfawn** [comment] 2024-04-02 15:03
Thanks! I'm going to close this issue in favour of the already existing one, to keep the conversation in one place. Be sure to +👍 the other feature request.

Duplicate of
- #5267

**Closed by Moshyfawn** 2024-04-02 15:03 UTC
Labels: enhancement, triage, admin read
