### ISSUE TITLE
hard to select end of long line

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#9319] opened 2024-03-14 06:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

for example, I want to select and copy "long line":

VSCode:

<img width="695" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/281abf97-9632-4816-87ab-343fd0a62cda">

Zed:

<img width="797" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/fea1c816-7baf-48bc-9a3c-020a9d53de73">

the cursor after `line` is overlapped by the scroll, I can't click the end of `line`

This is because VSCode has margin after `line`.

### Environment

Zed: v0.126.2 (Zed)
OS: macOS 14.4.0
Memory: 32 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-03-14 17:45
This has already been noticed in another issue, so I'm gling to close this one. Be sure to +👍 and add any missing information.

Duplicate of
- #7098

**Closed by Moshyfawn** 2024-03-14 17:45 UTC
Labels: defect, triage, admin read

**Comment by JosephTLyons** [comment] 2024-03-14 19:14
A workaround here might be a triple click, to highlight the whole line.
