### ISSUE TITLE
The Rust autocomplete window doesn't show up

### ISSUE THREAD

**Issue by Iovans** [zed-industries/zed#9942] opened 2024-03-28 23:07 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when i start type in zed using the rust language the autocomplete window dont shows up!

### Environment

Zed: v0.129.1 (Zed Preview)
OS: macOS 14.4.1
Memory: 8 GiB
Architecture: x86_64

**Comment by osiewicz** [comment] 2024-03-29 08:47
Hey,
It's hard to tell what's going on without a proper repro, but is the indexing finished at the time you start typing? i.e. can you see text with a `rust-analyzer:` prefix in the status bar like so:
![image](https://github.com/zed-industries/zed/assets/24362066/315d733b-a884-4fb5-92df-2048dd474b64)

**Comment by Iovans** [comment] 2024-03-29 15:09
after the rust-analyzer has finished the indexing the window still dont show up

**Comment by mmtftr** [comment] 2024-04-03 07:41
Have you checked the language server logs? For me, sometimes the language server crashes, which disables autocomplete.

**Comment by Iovans** [comment] 2024-04-03 07:45
It works now i dont know why but at some point It worked

**Comment by mmtftr** [comment] 2024-04-03 07:51
If the issue is fixed, you may want to close this. You can always open another issue in the future.

**Comment by Iovans** [comment] 2024-04-03 07:57
Okay thank you

**Closed** 2024-04-03 07:57 UTC
Labels: defect, rust, language, popovers

**Comment by stefanodecillis** [comment] 2024-05-09 12:55
Not working on my side. I have the latest version of Zed and rust analyzer is working well. I don't get types for my variables and methods suggestion when typing

**Comment by colingraydon** [comment] 2024-05-22 04:33
Currently experiencing the same issue on Mac Sonoma 14.4.1

I deleted Zed and reinstalled. I also deleted my rust analyzer and redownloaded that when I opened a rust file. I have the standard settings.json file and have a disabled copilot. This is a critical feature for me, anyone have any success fixing it?
