### ISSUE TITLE
Add scrollbar in terminal

### ISSUE THREAD

**Issue by Moosems** [zed-industries/zed#12220] opened 2024-05-23 20:47 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I couldn't find any related issues but I would really love a scrollbar on the terminal because there are times I get a lot of lines of varying input, then the same, and so on and I can't tell where I am when scrolling through the parts that are all the same.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="1552" alt="Screenshot 2024-05-23 at 4 47 16 PM" src="https://github.com/zed-industries/zed/assets/95927277/efab5e62-8c8c-4bb1-b411-1fc2b6c978c5">
<img width="1552" alt="Screenshot 2024-05-23 at 4 46 58 PM" src="https://github.com/zed-industries/zed/assets/95927277/9a8164de-d079-481e-989a-b289f1e8ced3">

**Comment by JosephTLyons** [comment] 2024-05-23 20:52
Hey @Moosems ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4798

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-05-23 20:52 UTC
Labels: enhancement, terminal, scrollbar, duplicate

**Comment by Moosems** [comment] 2024-05-23 20:55
@JosephTLyons I seem to have missed that in my search, thanks!
