### ISSUE TITLE
I'm seeing the editor's shadow only.

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [zed-industries/zed#14956] opened 2024-07-22 10:22 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

installed zed using curl as per instructions on install page.
Ubuntu 22.04
glibc 2.35
vkcube says Selected GPU 2: NVIDIA GeForce GTX 1650 Ti, type: 2 and spins fine, 
Dual screen setup (2x1920x1080)

### Environment

Sorry, can't get to the command palette with only a shadow showing. See above.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot from 2024-07-22 11-11-35](https://github.com/user-attachments/assets/08377b12-b2b0-4534-a08c-5d85708ec453)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-22T11:21:57.150152428+01:00 [INFO] ========== starting zed ==========
2024-07-22T11:21:57.235112121+01:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-07-22T11:21:57.235161207+01:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-07-22T11:21:57.24034375+01:00 [INFO] Try connect ibus
2024-07-22T11:21:57.240966283+01:00 [INFO] perform;
2024-07-22T11:21:57.241038916+01:00 [INFO] read_command;
2024-07-22T11:21:57.241120656+01:00 [INFO] read_command;
2024-07-22T11:21:57.241221075+01:00 [INFO] Opening main db
2024-07-22T11:21:57.241298927+01:00 [INFO] socket reader;
2024-07-22T11:21:57.241769669+01:00 [INFO] new;
2024-07-22T11:21:57.242332163+01:00 [INFO] keep_updated;
2024-07-22T11:21:57.242551221+01:00 [INFO] Using git binary path: None
2024-07-22T11:21:57.274698966+01:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-07-22T11:21:57.274779058+01:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-07-22T11:21:57.274818506+01:00 [INFO] Opening main db
2024-07-22T11:21:57.308792773+01:00 [INFO] XConnected server on 29360140, transport version: 0.0, TRANSPORT_MAX: 20
2024-07-22T11:21:57.308914652+01:00 [INFO] perform;
2024-07-22T11:21:57.308954147+01:00 [INFO] read_command;
2024-07-22T11:21:57.309026305+01:00 [INFO] read_command;
2024-07-22T11:21:57.309126209+01:00 [INFO] socket reader;
2024-07-22T11:21:57.309265455+01:00 [INFO] Using Visual { id: 35, colormap: 0, depth: 32 }
2024-07-22T11:21:57.309311424+01:00 [INFO] Creating colormap 100663299
2024-07-22T11:21:57.350573209+01:00 [INFO] Enabling color space support
2024-07-22T11:21:57.381124833+01:00 [WARN] Rejecting Intel for not presenting when Nvidia is present (on Linux)
2024-07-22T11:21:57.381808416+01:00 [INFO] Adapter "llvmpipe (LLVM 15.0.7, 256 bits)"
2024-07-22T11:21:57.381834671+01:00 [INFO] No ray tracing extensions are supported
2024-07-22T11:21:57.389760411+01:00 [INFO] Using surface present mode MAILBOX
2024-07-22T11:21:57.38990064+01:00 [WARN] Unable to forbid exclusive full screen
2024-07-22T11:21:57.390135016+01:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-22T11:21:57.390173012+01:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-07-22T11:21:57.390204707+01:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-07-22T11:21:57.543219854+01:00 [INFO] Refreshing at 16666 micros
2024-07-22T11:21:57.5516371+01:00 [INFO] set environment variables from shell:/bin/bash, path:/home/mrjb/.local/bin:/home/mrjb/bin:/home/mrjb/.nvm/versions/node/v14.13.0/bin:/home/mrjb/.cargo/bin:/home/mrjb/.local/bin:/home/mrjb/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
2024-07-22T11:21:57.6304455+01:00 [INFO] Using surface present mode MAILBOX
2024-07-22T11:21:57.630503176+01:00 [WARN] Unable to forbid exclusive full screen
2024-07-22T11:21:57.700079474+01:00 [INFO] Node runtime install_if_needed
2024-07-22T11:21:57.754303738+01:00 [INFO] Initializing default prettier with plugins {}
2024-07-22T11:21:58.107270981+01:00 [INFO] starting language server. binary path: "/home/mrjb/.local/share/zed/node/node-v18.15.0-linux-x64/bin/node", working directory: "/", args: ["/home/mrjb/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-22T11:21:58.671800791+01:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-22T10:21:58.667Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-22T10:21:58.667Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-22T11:21:58.673720051+01:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "b08e527a-de57-4766-a370-33a56e14beb0",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-22T11:21:58.706943456+01:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-22T10:21:58.679Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-22T10:21:58.679Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-07-22T11:22:00.360176085+01:00 [WARN] Unknown request DestroyIcReply { input_method_id: 6, input_context_id: 63 }

</pre></details>

**Comment by marcbrevoort-cyberhive** [comment] 2024-07-22 10:27
I'm thinking this might be similar to https://github.com/zed-industries/zed/issues/14805

**Comment by marcbrevoort-cyberhive** [comment] 2024-07-22 10:30
Confirming also that if I type Ctrl-O in this state, the file open dialog does pop up.

**Comment by marcbrevoort-cyberhive** [comment] 2024-07-22 10:38
On a different Window manager ("Unity" instead of "Ubuntu"), I see the editor's outline and a title bar.

![Screenshot from 2024-07-22 11-36-57](https://github.com/user-attachments/assets/4ada9215-dea5-4fd6-b828-92d74e2e8258)

**Comment by judemvm** [comment] 2024-07-22 21:39
Duplicate of https://github.com/zed-industries/zed/issues/14648

**Closed** 2024-07-23 15:24 UTC
Labels: defect, triage, admin read
