### ISSUE TITLE
[macOS] Zed instantly closes if one user has Zed running and another user tries to launch it

### ISSUE THREAD

**Issue by lumap** [zed-industries/zed#14513] opened 2024-07-15 19:11 UTC
### Check for existing issues

- [X] Completed

## Requirements
- Have 2+ users logged in
- Make sure Zed is in the `/Applications` folder

## Steps
- As one user, launch Zed
- Switch to another user without logging off of the first user
- Try to launch Zed
  - If done through the Finder, the app will appear for a split second in the Dock before closing.
  - If done through the CLI, the command will never stop running *and* the app will appear for a split second in the Dock before closing.

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

2024-07-15T21:04:30+02:00 [INFO] ========== starting zed ==========
2024-07-15T21:04:30+02:00 [INFO] Opening main db
2024-07-15T21:04:30+02:00 [INFO] Got instance handshake
</pre></details>

**Comment by notpeter** [comment] 2024-07-15 19:22
I believe this is a duplicate of:
- #7362 

Please subscribe to that issue to track it's progress.
Thanks for reporting.

**Closed by notpeter** 2024-07-15 19:22 UTC
Labels: defect, triage, panic / crash, admin read
