### ISSUE TITLE
Weird Overlapping text

### ISSUE THREAD

**Issue by zoozoox** [zed-industries/zed#14481] opened 2024-07-15 10:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when I'm trying to type out something, in the suggestion pop up, sometimes the suggestions overlap

### Environment

Zed: v0.143.7 (Zed)
OS: macOS 14.5.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/user-attachments/assets/9059e490-ea7e-4418-9171-f6d0a1ad7c49)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-08 13:33
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/15038

And was likely fixed by:
- https://github.com/zed-industries/zed/pull/15087

I'm going to close, but if you are still experiencing this with the current version of Zed, please comment below and I'm happy to reopen. Thanks for reporting!

**Closed by notpeter** 2024-10-08 13:33 UTC
Labels: defect, typescript, javascript, language, popovers, autocompletions
