### ISSUE TITLE
Undo and Redo in Edit menu are always gray.

### ISSUE THREAD

**Issue by acanton77** [zed-industries/zed#19710] opened 2024-10-25 02:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Undo and Redo in Edit menu are always gray.

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 12.7.6
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-26 00:49
Duplicate of https://github.com/zed-industries/zed/issues/12335

**Closed by SomeoneToIgnore** 2024-10-26 00:49 UTC
Labels: defect, triage, admin read
