### ISSUE TITLE
Add support for typos-lsp

### ISSUE THREAD

**Issue by hnbnh** [zed-industries/zed#9686] opened 2024-03-22 08:05 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice if Zed has support for https://github.com/tekumara/typos-lsp

**Comment by Moshyfawn** [comment] 2024-03-22 22:27
I think the general idea of a spell checker in Zed has already been raised in #5305, where `typos` was also mentioned as a solution. Let's close this issue in favour of the ongoing discussion to keep the conversation in one place. Be sure to +👍 and add any information to the other thread.

Duplicate of
- #5305

**Closed by Moshyfawn** 2024-03-22 22:27 UTC
Labels: enhancement, triage, admin read

**Comment by notpeter** [comment] 2024-09-24 05:51
FYI there is now an "typos" extension that integrates typos-lsp:

https://github.com/BaptisteRoseau/zed-typos
