### ISSUE TITLE
json file color preview

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#12317] opened 2024-05-26 13:02 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="125" alt="Screenshot 2024-05-26 alle 14 56 33" src="https://github.com/zed-industries/zed/assets/20476002/27922a84-ccd3-487a-be18-cb526dc26ac2">

<img width="303" alt="Screenshot 2024-05-26 alle 14 53 43" src="https://github.com/zed-industries/zed/assets/20476002/89c2342b-a82a-4929-8f96-47c91d8a3aaa">

It would be useful if next to the line indicating the color you could see a preview of it, and if necessary also be able to modify it using a picker that is activated when you click on the color.

**Comment by znycheporuk** [comment] 2024-05-26 18:03
This issue appears to be a duplicate of: https://github.com/zed-industries/zed/issues/4678

**Comment by 0x2CA** [comment] 2024-05-27 01:50
I think it's the same requirement, just a matching rule that may allow a color preview to be displayed in any file

**Comment by iamnbutler** [comment] 2024-05-27 18:14
Agreed. I clarified that issue title and added a comment. Closing this out as a dupe of #4678.

Thanks for the feedback!

**Comment by iamnbutler** [comment] 2024-05-27 18:14
Agreed. I clarified that issue title and added a comment. Closing this out as a dupe of https://github.com/zed-industries/zed/issues/4678.

Thanks for the feedback!

**Closed by iamnbutler** 2024-05-27 18:14 UTC
Labels: enhancement, editor, json, language
