### ISSUE TITLE
filetree collapses upon change from terminal

### ISSUE THREAD

**Issue by Duclearc** [zed-industries/zed#14488] opened 2024-07-15 11:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

whenever I trigger a change to the filetree from the terminal (e.g. `rm -rf folder1 folder2` or `npm install`) the filetree collapses.
I'm using an M1 Max Macbook Pro w/ 16gb RAM and 4TB storage. My Zed version is 0.143.6.

### Environment

Zed: v0.143.6 (Zed)
OS: macOS 14.5.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/5f7a9e7e-10a1-4ebb-a4d0-de03354c0d79

**Comment by osiewicz** [comment] 2024-07-15 12:41
Hey, this is a duplicate of: https://github.com/zed-industries/zed/issues/13762; I'm gonna close out this issue in favour of the other one.

**Closed by osiewicz** 2024-07-15 12:41 UTC
Labels: defect, triage, admin read
