### ISSUE TITLE
TODO List feature

### ISSUE THREAD

**Issue by huacnlee** [zed-industries/zed#10546] opened 2024-04-15 09:44 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

More details, visit this link:

https://subscription.packtpub.com/book/web-development/9781849693981/1/ch01lvl1sec23/making-a-todo-list-(should-know)

**Is this acceptable for Zed built-in feature?**

If it is certain, I can to try to add this feature. I think search all comments to match in project is a hard part.

For example, currently in Zed source code, we have 297 todos.

<img width="1441" alt="image" src="https://github.com/zed-industries/zed/assets/5518/3f9ded97-4c54-45d7-885b-2ab025105f7f">

-----

## Features

1. Search comments that the prefix matched `TODO`, `FIXME`, `CHANGED`, `RADAR` in all file in projects.
    > I don't know what means of `CHANGED`, `RADAR`,
3. Add a bottom panel to show the TODO list like this.

    ![image](https://github.com/zed-industries/zed/assets/5518/02d5152b-439e-40aa-8475-70731b0ffc9a)

4. Add like when click on the TODO item to go to the line/col of the comment.
5. Allows to add custom prefix in user setting.
6. Maybe add an icon in status bar near the Task icon to open Todo list?

**Comment by 0x2CA** [comment] 2024-04-15 09:56
https://marketplace.visualstudio.com/items?itemName=ExodiusStudios.comment-anchors

**Comment by Moshyfawn** [comment] 2024-04-15 15:26
I'm going to close this one in favour of the one that already exists. Be sure to +👍 the other one.

Duplicate of:
- #523

**Closed by Moshyfawn** 2024-04-15 15:26 UTC
Labels: enhancement, triage, admin read

**Comment by brokenthorn** [comment] 2025-10-01 07:10
Oh man! I so wished [TODO Tree](https://github.com/Gruntfuggly/todo-tree) could have been integrated into Zed. It's using ripgrep, so it's (almost) all Rust and fast, and very configurable... I mean it's grep after all...

EDIT: There is an extension now, but it's not in the official store: https://crates.io/crates/zed-todo-tree

**Comment by boozook** [comment] 2026-06-23 11:44
```json
// search TODOs in entier workspace -> multibuffer:
"cmd-5": [
	"action::Sequence",
	[
		[
			"pane::DeploySearch",
			{
				"included_files": "*.rs",
				// "excluded_files": ".*" ,
				"query": "(?://(?:!|/)?(?!\\n)|(?:/\\*(!|\\*)?(?!.*\\*/)(?:\\w+?|\\s+?|\\n+?)*)).*?\\b(?:todo|fixme|xxx|bug|hack|note)\\b:",
				"regex": true,
				"case_sensitive": true,
				"include_ignored": false,
				"replace_enabled": false,
			},
		],
		["workspace::SendKeystrokes", "enter"],
	],
],
// search TODOs in current buffer:
"cmd-alt-5": [
	"action::Sequence",
	[
		["buffer_search::Deploy", { "focus": true, "selection_search_enabled": true, "replace_enabled": false }],
		"search::ToggleRegex", // optional, if your default is regex=off
		[
			"workspace::SendKeystrokes",
			"(?://(?:!|/)?(?!\\n)|(?:/\\*(!|\\*)?(?!.*\\*/)(?:\\w+?|\\s+?|\\n+?)*)).*?\\b(?:todo|fixme|xxx|bug|hack|note)\\b: enter",
		],
	],
]
```

This workaround works, but incorrectly for any wrapping syntax-nodes like `"just \* TODO: ... *\ string"`, could be better to filter by syntax-node and so search only in comments.
