### ISSUE TITLE
double popups on JS/TS files when I hover on variable

### ISSUE THREAD

**Issue by sparrowsl** [zed-industries/zed#14941] opened 2024-07-22 05:19 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

basically I get double of these suggestions.
![double-popups](https://github.com/user-attachments/assets/ba1ea7c7-2326-48f1-93f3-36cd38aaf6e9)
I have `vtsls` disabled in my config.
```json
  "languages": {
    "JavaScript": {
      "language_servers": ["!eslint", "!prettier", "!vtsls", "..."]
    }
  }
```

### Environment

Linux Mint 21.3
Zed 0.144.4

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![double-popups](https://github.com/user-attachments/assets/ba1ea7c7-2326-48f1-93f3-36cd38aaf6e9)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by wrnrlr** [comment] 2024-07-22 23:10
I've got the same issue on Mac with 0.144.4

**Comment by JosephTLyons** [comment] 2024-07-23 19:52
Hey @sparrowsl,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/14161

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-23 19:52 UTC
Labels: defect, popovers
