### ISSUE TITLE
`hard_tabs` config setting not taken into account by the "format on save" feature

### ISSUE THREAD

**Issue by pygy** [zed-industries/zed#8817] opened 2024-03-04 11:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've set `hard_tabs` to true in my local config, and was a bit surprised that the default "format on save" feature simply ignored it (even though it does that `tab_size` into account).

### Environment

Zed: v0.124.7 (Zed)
OS: macOS 12.6.2
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/54515/d2ac5511-3974-4d3c-81d2-b60f6ff72575

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

These entries may be relevant, not sure:
```
2024-03-04T12:41:55+01:00 [INFO] Language server with id 3 sent unhandled notification eslint/noLibrary:
{
  "source": {
    "uri": "file:///Users/pygy/dev/test.js"
  }
}
2024-03-04T12:41:55+01:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
2024-03-04T12:42:01+01:00 [ERROR] unexpected item event after pane was dropped
2024-03-04T12:42:33+01:00 [ERROR] unexpected item event after pane was dropped
2024-03-04T12:42:33+01:00 [WARN] Generic lsp request to node failed: Unhandled method textDocument/definition
```

The log is full of similar entries.

**Comment by Moshyfawn** [comment] 2024-03-04 14:50
Duplicate of #7656

**Closed by Moshyfawn** 2024-03-04 14:50 UTC
Labels: defect, triage, admin read

**Comment by pyronaur** [comment] 2024-03-31 04:56
Since this hasn't been fixed still, does that mean that majority of developers are using spaces for indentation?

This issue is probably the sole reason I haven't switched to Zed yet.
