### ISSUE TITLE
Hard tabs are replaced by spaces when typing a semicolon in JS/TS.

### ISSUE THREAD

**Issue by matubu** [zed-industries/zed#14499] opened 2024-07-15 15:01 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you type a semicolon in JS/TS, all the hard tabs of that line are replaced by spaces, even though the config specifies hard tabs.

### Environment

Zed: v0.144.2 (Zed Preview)
OS: Linux Wayland fedora 39
Memory: 3.8 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Screencast from 2024-07-15 16-59-19.webm](https://github.com/user-attachments/assets/4256956e-1092-445f-b689-a528e60961be)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-15 20:23
I think this is a dupe of
- https://github.com/zed-industries/zed/issues/14499

Please 👍 to vote and subscribe to be notified of progress.

P.S. Your title was better :P

**Closed by notpeter** 2024-07-15 20:23 UTC
Labels: defect, triage, admin read

**Comment by matubu** [comment] 2024-07-15 22:12
A duplicate of which issue? I think you linked my issue.
