### ISSUE TITLE
Half the visible content is cut off

### ISSUE THREAD

**Issue by panchalkalpesh** [zed-industries/zed#8718] opened 2024-03-02 16:35 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When opening any file type, only half the content is visible. 
Try opening any file of your choice, scroll and observe the editor's behaviour. 
Check screenshots.

> My first impression after installing and using Zed: _**Unusable**_

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 11.7.10
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1552" alt="Screen Shot 2024-03-02 at 11 28 45 AM" src="https://github.com/zed-industries/zed/assets/1808686/30aa8541-1312-4ef5-9524-b1e172c670c3">
<img width="1552" alt="Screen Shot 2024-03-02 at 11 28 20 AM" src="https://github.com/zed-industries/zed/assets/1808686/7854dcf3-4ab7-47e4-8569-ca9206998987">
<img width="1552" alt="Screen Shot 2024-03-02 at 11 27 16 AM" src="https://github.com/zed-industries/zed/assets/1808686/02e1572e-864e-4453-a7a3-a14a742881b3">
<img width="1552" alt="Screen Shot 2024-03-02 at 11 26 42 AM" src="https://github.com/zed-industries/zed/assets/1808686/277b3b70-ac22-487e-8c97-466406ba6f38">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/zed/files/14470062/Zed.log)

**Comment by Moshyfawn** [comment] 2024-03-02 16:40
I'm going to close this thread in favour of another that already describes this behaviour. Be sure to +👍 the other thread, and add any additional information it may be missing.

**Comment by Moshyfawn** [comment] 2024-03-02 16:40
Duplicate of #5062

**Closed by Moshyfawn** 2024-03-02 16:40 UTC
Labels: defect, triage, admin read
