### ISSUE TITLE
[Linux] Zed panic bacause linux::wayland::client::CursorState>>::borrow_mut failure

### ISSUE THREAD

**Issue by golanguage** [zed-industries/zed#9536] opened 2024-03-19 14:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

cargo run, move mouse into zed window, zed crash soon.
May it related with PR#8632 "linux: wayland: implement cursor style handling"
  
```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.87s
     Running `target/debug/Zed`
[2024-03-19T20:41:10+08:00 ERROR util] crates/settings/src/keymap_file.rs:89: invalid binding value for keystroke backspace, context Some("ProjectPanel")

Caused by:
    0: Attempting to build action project_panel::Delete
    1: missing field `skip_prompt`
[2024-03-19T20:41:10+08:00 ERROR util] crates/settings/src/keymap_file.rs:89: invalid binding value for keystroke delete, context Some("ProjectPanel")

Caused by:
    0: Attempting to build action project_panel::Delete
    1: missing field `skip_prompt`
[2024-03-19T20:41:11+08:00 ERROR util] crates/zed/src/zed.rs:615: EOF while parsing a value at line 1 column 0
[2024-03-19T20:41:11+08:00 ERROR util] crates/zed/src/main.rs:694: No such file or directory (os error 2)
[2024-03-19T20:41:11+08:00 ERROR util] crates/fs/src/repository.rs:101: Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }
[2024-03-19T20:41:11+08:00 ERROR util] crates/fs/src/repository.rs:101: Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }
Thread "main" panicked with "already borrowed: BorrowMutError" at crates/gpui/src/platform/linux/wayland/client.rs:316:56
   0: Zed::init_panic_hook::{closure#0}
             at crates/zed/src/main.rs:598:29
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: core::cell::panic_already_borrowed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/cell.rs:761:5
   7: <core::cell::RefCell<gpui::platform::linux::wayland::client::CursorState>>::borrow_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/cell.rs:1051:25
   8: <gpui::platform::linux::wayland::client::WaylandClient as gpui::platform::linux::client::Client>::set_cursor_style
             at crates/gpui/src/platform/linux/wayland/client.rs:316:32
   9: <gpui::platform::linux::platform::LinuxPlatform as gpui::platform::Platform>::set_cursor_style
             at crates/gpui/src/platform/linux/platform.rs:355:9
  10: <gpui::window::WindowContext>::reset_cursor_style
             at crates/gpui/src/window.rs:1090:13
  11: <gpui::window::WindowContext>::dispatch_mouse_event
             at crates/gpui/src/window.rs:1233:13
  12: <gpui::window::WindowContext>::dispatch_event
             at crates/gpui/src/window.rs:1218:13
  13: <gpui::window::Window>::new::{closure#7}::{closure#0}
             at crates/gpui/src/window.rs:521:46
  14: <gpui::app::AppContext as gpui::Context>::update_window::<gpui::window::DispatchEventResult, <gpui::window::Window>::new::{closure#7}::{closure#0}>::{closure#0}
             at crates/gpui/src/app.rs:1274:26
  15: <gpui::app::AppContext>::update::<core::result::Result<gpui::window::DispatchEventResult, anyhow::Error>, <gpui::app::AppContext as gpui::Context>::update_window<gpui::window::DispatchEventResult, <gpui::window::Window>::new::{closure#7}::{closure#0}>::{closure#0}>
             at crates/gpui/src/app.rs:354:22
  16: <gpui::app::AppContext as gpui::Context>::update_window::<gpui::window::DispatchEventResult, <gpui::window::Window>::new::{closure#7}::{closure#0}>
             at crates/gpui/src/app.rs:1265:9
  17: <gpui::app::async_context::AsyncAppContext as gpui::Context>::update_window::<gpui::window::DispatchEventResult, <gpui::window::Window>::new::{closure#7}::{closure#0}>
             at crates/gpui/src/app/async_context.rs:70:9
  18: <gpui::window::AnyWindowHandle>::update::<gpui::app::async_context::AsyncAppContext, gpui::window::DispatchEventResult, <gpui::window::Window>::new::{closure#7}::{closure#0}>
             at crates/gpui/src/window.rs:2717:9
  19: <gpui::window::Window>::new::{closure#7}
             at crates/gpui/src/window.rs:520:17
  20: <alloc::boxed::Box<dyn core::ops::function::FnMut<(gpui::interactive::PlatformInput,), Output = gpui::window::DispatchEventResult>> as core::ops::function::FnMut<(gpui::interactive::PlatformInput,)>>::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2022:9
  21: <gpui::platform::linux::wayland::window::WaylandWindowState>::handle_input
             at crates/gpui/src/platform/linux/wayland/window.rs:240:17
  22: <gpui::platform::linux::wayland::client::WaylandClientState as wayland_client::event_queue::Dispatch<wayland_client::protocol::wl_pointer::WlPointer, ()>>::event
             at crates/gpui/src/platform/linux/wayland/client.rs:877:17
  23: wayland_client::event_queue::queue_callback::<wayland_client::protocol::wl_pointer::WlPointer, (), gpui::platform::linux::wayland::client::WaylandClientState>
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/wayland-client-0.31.2/src/event_queue.rs:656:5
  24: <wayland_client::event_queue::EventQueue<gpui::platform::linux::wayland::client::WaylandClientState>>::dispatching_impl
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/wayland-client-0.31.2/src/event_queue.rs:478:13
  25: <wayland_client::event_queue::EventQueue<gpui::platform::linux::wayland::client::WaylandClientState>>::dispatch_pending
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/wayland-client-0.31.2/src/event_queue.rs:384:9
  26: <gpui::platform::linux::wayland::client::WaylandClient>::new::{closure#1}
             at crates/gpui/src/platform/linux/wayland/client.rs:205:17
  27: <core::cell::RefCell<calloop::sources::DispatcherInner<calloop_wayland_source::WaylandSource<gpui::platform::linux::wayland::client::WaylandClientState>, <gpui::platform::linux::wayland::client::WaylandClient>::new::{closure#1}>> as calloop::sources::EventDispatcher<()>>::process_events::{closure#0}
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-0.12.4/src/sources/mod.rs:327:61
  28: <calloop_wayland_source::WaylandSource<gpui::platform::linux::wayland::client::WaylandClientState>>::loop_callback_pending::<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop_wayland_source::WaylandSource<gpui::platform::linux::wayland::client::WaylandClientState>, <gpui::platform::linux::wayland::client::WaylandClient>::new::{closure#1}>> as calloop::sources::EventDispatcher<()>>::process_events::{closure#0}>
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-wayland-source-0.2.0/src/lib.rs:245:19
  29: <calloop_wayland_source::WaylandSource<gpui::platform::linux::wayland::client::WaylandClientState> as calloop::sources::EventSource>::process_events::<<core::cell::RefCell<calloop::sources::DispatcherInner<calloop_wayland_source::WaylandSource<gpui::platform::linux::wayland::client::WaylandClientState>, <gpui::platform::linux::wayland::client::WaylandClient>::new::{closure#1}>> as calloop::sources::EventDispatcher<()>>::process_events::{closure#0}>
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-wayland-source-0.2.0/src/lib.rs:154:9
  30: <core::cell::RefCell<calloop::sources::DispatcherInner<calloop_wayland_source::WaylandSource<gpui::platform::linux::wayland::client::WaylandClientState>, <gpui::platform::linux::wayland::client::WaylandClient>::new::{closure#1}>> as calloop::sources::EventDispatcher<()>>::process_events
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-0.12.4/src/sources/mod.rs:326:9
  31: <calloop::loop_logic::EventLoop<()>>::dispatch_events
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-0.12.4/src/loop_logic.rs:445:31
  32: <calloop::loop_logic::EventLoop<()>>::dispatch::<core::option::Option<core::time::Duration>>
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-0.12.4/src/loop_logic.rs:559:9
  33: <calloop::loop_logic::EventLoop<()>>::run::<<gpui::platform::linux::platform::LinuxPlatform as gpui::platform::Platform>::run::{closure#0}, core::option::Option<core::time::Duration>>
             at /home/test/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/calloop-0.12.4/src/loop_logic.rs:596:13
  34: <gpui::platform::linux::platform::LinuxPlatform as gpui::platform::Platform>::run
             at crates/gpui/src/platform/linux/platform.rs:131:9
  35: <gpui::app::App>::run::<Zed::main::{closure#3}>
             at crates/gpui/src/app.rs:142:9
  36: Zed::main
             at crates/zed/src/main.rs:121:5
  37: <fn() as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  38: std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  39: std::rt::lang_start::<()>::{closure#0}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  40: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  41: std::rt::lang_start::<()>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  42: main
  43: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  44: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  45: _start
 
```

### Environment

Ubuntu 23.10/24.04,  wayland

**Comment by jansol** [comment] 2024-03-19 16:27
Duplicate of #9295

**Comment by Moshyfawn** [comment] 2024-03-19 17:12
I'm going to close this issue in favour of the existing one. Be sure to +👍 and add any missing information.

Duplicate of
- #9295

**Closed by Moshyfawn** 2024-03-19 17:12 UTC
Labels: defect, triage, admin read
