### ISSUE TITLE
"Open Recent" should be available with no open windows

### ISSUE THREAD

**Issue by igorgusarov** [zed-industries/zed#10101] opened 2024-04-03 03:39 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently if you close all windows of Zed and try to open a recent project, the "File / Open Recent" menu item is disabled. It should be available even when no windows are open.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="377" alt="Screenshot 2024-04-02 at 20 38 17" src="https://github.com/zed-industries/zed/assets/2374205/607c1765-a8a0-40af-bceb-ff40cefa1258">

**Comment by osiewicz** [comment] 2024-04-03 09:36
For the reference, this is probably being greyed out due to `recent_projects::OpenRecent` being registered on a workspace and not as a global action; the code responsible for greying out menu items checks for action availability: https://github.com/zed-industries/zed/blob/main/crates/gpui/src/platform/app_menu.rs#L104

However, I don't think we have a precedent for having modals without a workspace associated with them, so this might require a deeper cut.

**Comment by JosephTLyons** [comment] 2024-04-04 19:03
I wonder if we could fall back to just showing the recents in the menu, if a workspace isn't avaiable, 

<img width="870" alt="SCR-20240404-niia" src="https://github.com/zed-industries/zed/assets/19867440/5dbe41d8-ec5c-436a-8569-4164a77c3b0b">

but maybe that would be weird, having two different mechanisms. I do like custom version because I prefer being able to filter down via text.

**Comment by porsager** [comment] 2024-11-15 06:14
> I wonder if we could fall back to just showing the recents in the menu, if a workspace isn't avaiable, as VS Code does, but maybe that would be weird, having two different mechanisms. I do like custom version because I prefer being able to filter down via text.
> 
> Side note, I'm positive I have an issue about this lying around, but I cannot find it, for the life of me. 🤣

Might you be thinking of this https://github.com/zed-industries/zed/issues/4357 @JosephTLyons ?

**Comment by notpeter** [comment] 2024-11-15 17:09
That's it.  Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/4357

**Closed by notpeter** 2024-11-15 17:09 UTC
Labels: enhancement, workspace
