### ISSUE TITLE
Zed is SPAMMING github for the same URL

### ISSUE THREAD

**Issue by a-non-a-mouse** [zed-industries/zed#19460] opened 2024-10-19 13:37 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

See the log.  It's a deleted username

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-19T15:36:39.249679+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.255001+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.265615+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.266767+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.449604+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.454223+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.499714+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.506786+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.516168+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.521787+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.532817+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.534262+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.783011+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.78593+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:39.999693+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.007658+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.016195+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.017263+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.035762+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.043303+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.049441+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.052266+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.316225+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.319694+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.349804+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.354279+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.5001+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.508739+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.516124+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.51799+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.566564+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.571066+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.782666+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }
2024-10-19T15:36:40.787115+02:00 [ERROR] BadStatus { uri: "https://github.com/VoiceNPO.png?size=128", status: 404, body: "Not Found" }

</pre></details>

**Comment by a-non-a-mouse** [comment] 2024-10-19 13:41
Also, I'm not sure where it's getting it from.  I grepped the folder I'm working on, and the config, and there's no longer any reference to it

**Comment by CharlesChen0823** [comment] 2024-10-19 14:13
git commit history, query git blame user icon

**Comment by a-non-a-mouse** [comment] 2024-10-19 14:22
There is no commit history on this project.  I initialized it, but haven't pushed it yet or committed anything.  I then renamed my account, and zed started freaking out and trying to pull the image 30x/second for however long until I noticed it

**Comment by a-non-a-mouse** [comment] 2024-10-19 14:24
it's doing it on a new empty directory as well.  And ~/.config/zed also has no reference to that username

**Comment by a-non-a-mouse** [comment] 2024-10-19 15:16
And I blew away ~/.config/zed, ~/Library/Application Support/Zed, and even reinstalled it.  And it's still doing it.

**Comment by a-non-a-mouse** [comment] 2024-10-19 16:51
Okay, so I fixed it by signing out on zed.dev.  I believe it has something to do with your collab editing channel, which I've never used:

https://github.com/zed-industries/zed/blob/e8207288e554e3619dd0a8186e93b83047719bf1/crates/collab/src/db/queries/channels.rs#L730

**Comment by notpeter** [comment] 2024-10-21 15:03
There are a couple places where we load GitHub avatars, for your username if you log into Zed (upper right hand corner),  Collab icons are another, but we also do it for `git blame` which by default displays a dimmed "Anon A Mouse, 3 Months Ago" and will show an avatar on hover.

I think this is basically a duplicate of:
- https://github.com/zed-industries/zed/issues/19207

So I'm closing in favor of that issue.  Thanks for reporting.

**Closed by notpeter** 2024-10-21 15:03 UTC
Labels: defect, triage, admin read
