### ISSUE TITLE
Panel drag available under Project Panel menu items

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/zed#10017] opened 2024-03-31 20:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As in #9501, the `drag` crusor type is displayed when the mouse pointer is over a file actions menu and dragging the panel is available. The expected behaviour would be to disable panel dragging when the menu is open.

### Environment

Zed: v0.130.0 (Zed Nightly 3c8b3767640a32625db05dd05f733e6111c9e20c)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="412" alt="zed-hover-propagate" src="https://github.com/zed-industries/zed/assets/16290753/e4ce1b9b-e599-4e5e-980f-b45ceefaf921">

**Comment by Moshyfawn** [comment] 2024-03-31 20:09
I can't seem to reproduce this in the latest Preview, so I'll add the `regression` label as well.

**Comment by bennetbo** [comment] 2024-04-01 09:34
Looks like #9911 caused the regression

**Comment by bennetbo** [comment] 2024-04-01 10:16
Thanks for the report, should be fixed in #10035.

**Closed** 2024-04-01 10:31 UTC
Labels: defect, regression, mouse-interaction, workspace, menus, admin read
