### ISSUE TITLE
Markdown preview: checkbox shown in the wrong line when in a list

### ISSUE THREAD

**Issue by marcospb19** [zed-industries/zed#17220] opened 2024-08-31 21:07 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Markdown rendering renders checklists in the wrong line.

### Example 1:

input:
```
- [x] ownership
  - references
    - Move semantics
    - Copy e Clone
    - hi
```

![image](https://github.com/user-attachments/assets/3cbe1cb2-b8db-4078-a211-d0c2dee0af16)

### Example 2:

also, here two checklists show as just one, might be the same problem idk.

input:
```
- hey
- [x] oie
  - [x] asd
  - tudo bao
```

![image](https://github.com/user-attachments/assets/822fc006-a5a0-492e-b1cf-5c64b1d3592a)

### Environment

Zed: v0.150.4 (Zed)
OS: Linux X11 arch unknown
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6750 XT || AMD open-source driver || 2024.Q3.1 (LLPC)

**Comment by JosephTLyons** [comment] 2024-10-03 16:02
Hey @marcospb19,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/12515

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-10-03 16:02 UTC
Labels: defect, markdown, markdown renderer
