### ISSUE TITLE
[vim] Prompt Library Unable to input

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/zed#12923] opened 2024-06-12 08:54 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/zed/assets/19868292/f77ec175-4944-4b73-a7bf-87a6549c5422

### Environment

Zed: v0.140.0 (Zed Dev d2565ef523383fa61bc5dfba40f8ed942570ebb9)
OS: macOS 14.5.0
Memory: 32 GiB
Architecture: aarch64

**Comment by notpeter** [comment] 2024-06-12 12:57
Thanks for reporting this, I believe this is a duplicate of this issue:

- https://github.com/zed-industries/zed/issues/12732

You can vote 👍 and subscribe to that issue to track its progress.

**Closed by notpeter** 2024-06-12 12:57 UTC
Labels: defect, vim, ai, duplicate
