### ISSUE TITLE
Add scrollbars to Outline pane and Markdown Preview pane

### ISSUE THREAD

**Issue by RichardJECooke** [zed-industries/zed#17492] opened 2024-09-06 11:00 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

The Outline pane and Markdown Preview pane do not have a scrollbar. Nor do arrow keys or page up/down keys work in the preview. 

This means we have to tediously scroll a few lines at a time with the mousewheel (which is much worse for causing repetitive strain injuries as it uses small muscles off the hand) and cannot navigate quickly to the desired area of the the document using a scrollbar.

Please add scrollbars to every pane in the app that has content that can exceed the length of the window.

**Comment by notpeter** [comment] 2024-09-06 16:07
Duplicate of 
- #15324

**Closed by notpeter** 2024-09-06 16:07 UTC
Labels: enhancement, triage, admin read
