### ISSUE TITLE
Save untitled buffers between restarts

### ISSUE THREAD

**Issue by BretFisher** [zed-industries/zed#8958] opened 2024-03-06 18:12 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In Sublime this is called "hot exit". In other macOS apps (pages, textedit, maybe others) it's considered Auto Save, where you can create new buffers (tabs), never save them, and when you exit, the app doesn't prompt to create new files, it just saves the exact state of each untitled buffer and brings them back on next start.

This doesn't replace autosave or save on quit, which would then only be triggered for files that have a file path.

This is immensely useful for when you're taking temp notes, starting a file but not ready to save it to the project, using buffers for copy/paste, etc.

In Sublime, it auto-titles the tab based on the first line of text, to help distinguish between all the untitled tabs.

**Comment by Moshyfawn** [comment] 2024-03-06 21:33
This is probably the same request as #4985

**Comment by Moshyfawn** [comment] 2024-03-06 21:35
Be sure to +👍 the other request to show your interest and add any missing information.

Duplicate of
- #4985

**Closed by Moshyfawn** 2024-03-06 21:35 UTC
Labels: enhancement, triage, workspace, serialization, admin read

**Comment by BretFisher** [comment] 2024-03-07 01:57
Oops, thanks!
