### ISSUE TITLE
Completion popover is hidden when ai tries to autocomplete

### ISSUE THREAD

**Issue by nervenes** [zed-industries/zed#20318] opened 2024-11-06 21:11 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I enabled copilot, and now whenever i write code where copilot suggests code zed doesn't show the completion popover. This prevents me from seeing what's available and what not, i checked how the behavior is in xcode and vscode and they seem to work fine.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 15.1.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/4fa5b39f-5bf3-48b7-9bdb-f0bc3bbe5fea

https://github.com/user-attachments/assets/e4966f08-6e9b-4b6f-802d-e028c4a6229f

**Comment by osiewicz** [comment] 2024-11-11 03:29
Cross-posting https://github.com/zed-industries/zed/pull/20471#issuecomment-2467160671 as I think this is most likely what's going on there.

**Comment by osiewicz** [comment] 2024-11-11 22:19
Duplicate of https://github.com/zed-industries/zed/issues/8766

**Comment by nervenes** [comment] 2024-11-11 22:25
@osiewicz the issue you linked seem to describe another problem though? this issue is about zed not showing the autocomplete popover when copilot suggests an inline completion.

**Comment by osiewicz** [comment] 2024-11-14 09:06
Sorry, yeah, I think these two issues are mostly about the same problem. Would you expect the completion popover to trigger on any word character? (e.g. 'a', 'b' etc.)?  If so we can probably reopen

**Comment by nervenes** [comment] 2024-11-14 10:22
Yep

**Comment by nervenes** [comment] 2024-12-11 18:35
@osiewicz are there any news about this one? i'd really like to use copilot but i've been refraining due to the lsp completion list being blocked from the inline completions, as mentioned vscode shows both just fine

**Comment by nervenes** [comment] 2024-12-17 15:28
https://github.com/zed-industries/zed/issues/20318#issuecomment-2536827166

**Closed** 2024-12-17 15:28 UTC
Labels: bug, popovers, ai, autocompletions, inline completion
