### ISSUE TITLE
Rust LSP: docs.rs link

### ISSUE THREAD

**Issue by PolpOnline** [zed-industries/zed#9925] opened 2024-03-28 17:07 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have a link to open docs.rs on hover, like JetBrains product do

### If applicable, add mockups / screenshots to help present your vision of the feature

[LSP support post on Reddit](https://www.reddit.com/r/rust/comments/w7cf7d/rustanalyzer_tip_open_docsrs_for_the_symbol_under/)

How Intellij shows it (bottom of the popup):

![image_2024-03-28_18-06-04](https://github.com/zed-industries/zed/assets/53786619/1c9aff96-a2a0-4ad6-bc54-26ce9da0a0e2)

**Comment by Moshyfawn** [comment] 2024-03-28 17:11
There's already a feature request for this, so I'm going to close this issue in favour of the other one. Be sure to +👍 it.

Duplicate of
- #4713

**Closed** 2024-03-28 17:11 UTC
Labels: enhancement, triage, admin read

**Comment by PolpOnline** [comment] 2024-03-28 17:15
Sorry, couldn't find that, mb

**Comment by Moshyfawn** [comment] 2024-03-28 18:02
Np!
