### ISSUE TITLE
Remember unsaved changes

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/zed#4683] opened 2023-06-18 22:28 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I'd like Zed to remember my unsaved changes for next time I open the app. This is useful to protect against crashes, but also when you just want to restart without saving.

When you close apps like VSCode, TextEdit and Pages, you're not asked at all if you want to save unsaved changes.

I often use unsaved files for todo lists and dealing with some temporary data files.

Related:
- https://github.com/zed-industries/zed/issues/4985

**Comment by porsager** [comment] 2024-02-05 07:59
Even though this issue: https://github.com/zed-industries/zed/issues/4985 is newer, it has more upvotes, so perhaps close this as duplicate?

**Comment by probablykasper** [comment] 2024-02-05 08:02
This issue is broader in scope than that one

**Comment by muja** [comment] 2024-05-08 04:20
Agree that it might lead to confusion, initially thought they are duplicates as well. However, saving changes universally seems a lot more complicated than starting out with untitled files. I believe the issues can co-exist.

**Comment by jcalvopinam** [comment] 2024-07-20 16:06
wow! the long awaited feature has been merged in #13546, any idea when it will be released?

**Comment by muja** [comment] 2024-07-21 14:42
While I *love* that this has been added and was the major blocker for seriously considering zed, I just realized that the implementation of unsaved changes has two considerations:

1. If the file changes in the meantime via another source, should the user be notified?
2. Since no undo history is stored, will it be possible to revert changes? For example in VSCode, there is no way to restore a dirty file that was closed without saving which IMO is not a bug but a... bad feature.

The untitled files has no drawbacks though.

**Comment by mrnugget** [comment] 2024-07-22 07:47
> wow! the long awaited feature has been merged in #13546, any idea when it will be released?

It's going to be released in the Preview release on Wednesday, normal release next week — pending any bugs.

---

> 1. If the file changes in the meantime via another source, should the user be notified?

Yeah, I don't know yet. What happens right now is that the "dirty"-content that Zed has saved will kept and the file still marked as dirty. But the user can throw that away by closing the tab and reopening it.


> 2\. Since no undo history is stored, will it be possible to revert changes? For example in VSCode, there is no way to restore a dirty file that was closed without saving which IMO is not a bug but a... bad feature.

If you close a dirty file explicitly (i.e. closing the tab), you get the choice to `Save`/`Discard`/`Cancel`. If you `Discard`, there's no way to get back to the dirty contents.

I wouldn't call it a "bad feature" for that, because the user made an explicit choice to Discard the changes and, IMHO, at a certain point when thinking about different variations and attributes of the "restore unsaved buffers" feature, the question pops up of why not use the file system and actually save files?

I don't think this feature is supposed to re-implement version-controlled files. For that, there's the file system and version control.

**Comment by muja** [comment] 2024-07-22 15:06
If I close an unsaved file, a dialog will ask to either save, discard or cancel. If I close the entire application, the file will remain dirty and once reopened it will ignore intermittent changes and display the stale buffer, the only way being to close+discard. "Bad feature" is a bit much but it's not ergonomic when the user forgets to save and becomes confused why there is a dirty flag with no easy way to figure it out, with the two easy ways to recover from this leading to progress loss (either by ctrl+s overwriting or by ctrl+w->discard)

For me it doesn't really matter since the "unsaved file" feature will definitely not be used (except accidentally), but was just meant as a heads up

**Comment by mrnugget** [comment] 2024-07-22 17:45
> If I close the entire application, the file will remain dirty and once reopened it will display the possibly stale buffer (ignoring intermittent changes), the only way out being to close+discard.

Is the issue the ignoring of the intermittent changes? Because otherwise it sounds like you just don't want to use the feature, no?

**Comment by muja** [comment] 2024-07-22 18:25
The feature is not really interesting for me because when I change a file in my editor and don't press Save, it's mostly because I forgot, so I'd prefer it if the application warned me when I try to close it.

> Is the issue the ignoring of the intermittent changes?

The user opening Zed may be confused that their open files are dirty, unless very short time has passed, in the presence as well as absence of intermittent changes -- they differ only in their resulting consequences

**Comment by mrnugget** [comment] 2024-07-23 09:13
> so I'd prefer it if the application warned me when I try to close it.

It does — when you close the file/tab/buffer. Just not when you quit the application.

**Comment by porsager** [comment] 2024-07-23 09:27
> It does — when you close the file/tab/buffer. Just not when you quit the application.

But only because it will still be there when zed is opened again right?

**Comment by mrnugget** [comment] 2024-07-23 17:31
Yep, exactly. You can see that at the end of the demo video in here: https://github.com/zed-industries/zed/pull/13546

**Comment by JosephTLyons** [comment] 2024-07-24 16:12
The following PRs have added quite a bit to the workspace serialization story:

- https://github.com/zed-industries/zed/pull/13546
- https://github.com/zed-industries/zed/pull/14965

There are a few known missing bits here, but I think its best that we close this issue out, in favor of new issues that describe those missing bit, so that we can get a clear understanding of how important these bits are to you all, now that most of the functionality has landed. Here are the new issues (upvote via 👍):

- https://github.com/zed-industries/zed/issues/15098
- https://github.com/zed-industries/zed/issues/15097

Killer work @mrnugget!

**Closed by JosephTLyons** 2024-07-24 16:12 UTC
Labels: enhancement, editor, serialization, priority request
