### ISSUE TITLE
`editor::ShowCompletions` menu should stay on while typing

### ISSUE THREAD

**Issue by osa1** [zed-industries/zed#15596] opened 2024-08-01 09:50 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

With `"show_completions_on_input": false` setting, `editor::ShowCompletions` menu disappears with every character inserted.

It does **not** disappear when I move cursor left/right with arrow keys.

For example, in settings.json, I press `ctrl-space` (mapped to `editor::ShowCompletions`) after typing `"sho` and it shows me a bunch of settings, such as `"show_whites"`, `"show_wrap_guides"` etc.

If I enter any character, such as `w`, the auto completion menu disappears. I have to press `ctr-space` after every character I type to be able to see new completions.

Instead `editor::ShowCompletions` should show the completion menu until it's closed explicitly, for example with ESC, so that I can keep typing while seeing the completions.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux X11 ubuntu 22.04
Memory: 62.5 GiB
Architecture: x86_64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-08-01 20:58
duplicate of:
- https://github.com/zed-industries/zed/issues/15549

**Closed by notpeter** 2024-08-01 20:58 UTC
Labels: defect, triage, admin read

**Comment by notpeter** [comment] 2024-08-01 21:01
unrelated: @osa1, I'm sure this unintentional, but currently when you link from https://github.com/osa1/rcbackup/issues/2 to Zed issues it shows up as a mention in each individual github issues (see above).  Would you be willing to move to move this to an issue on a private github repo or some other forum where GitHub won't be so "helpful" in cross-linking issues. Thanks
