### ISSUE TITLE
Image preview doesn't allow to resize the image, neither to scroll

### ISSUE THREAD

**Issue by dimeeentor** [zed-industries/zed#10697] opened 2024-04-17 21:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Open any image that is too large
You will see how Zed clips the image and doesn't allow to scroll.
To my mind, would be better if the user could zoom out, in order to properly see the image.

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1624" alt="Screenshot 2024-04-17 at 23 01 57" src="https://github.com/zed-industries/zed/assets/32683179/bc50fb7b-d7b5-46c8-88c4-731c6e6dd70e">

**Comment by dimeeentor** [comment] 2024-04-17 21:07
Image dimensions: 1025 × 1600

**Comment by Moshyfawn** [comment] 2024-04-17 21:31
There's already a feature request for panning / scrolling and zooming the image in the viewer. I'm going to close this thread in favour of the other one to keep the conversation in one place. Be sure to +👍 it and add any additional information.

Duplicate of
- #9584

**Closed by Moshyfawn** 2024-04-17 21:31 UTC
Labels: defect, triage, admin read
