### ISSUE TITLE
"Go to Line/Column" does not respect multibyte characters

### ISSUE THREAD

**Issue by andreymal** [zed-industries/zed#16193] opened 2024-08-14 01:36 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It seems the "Go to Line/Column" button calculates UTF-8 bytes instead of Unicode code points

### Environment

Zed: v0.147.2 / v0.148.0-pre
OS: Linux X11 arch unknown
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

(Kate demonstrates the expected behavior)

![zed-column](https://github.com/user-attachments/assets/6a1004e5-d132-4ead-b5e5-6fc2cb4131c8)

**Comment by notpeter** [comment] 2024-08-15 18:26
Duplicate of:
- https://github.com/zed-industries/zed/issues/12024

**Closed by notpeter** 2024-08-15 18:26 UTC
Labels: defect, editor, internationalization

**Comment by andreymal** [comment] 2024-08-15 18:29
I couldn't find that issue because it doesn't even mention "column"

**Comment by notpeter** [comment] 2024-08-15 19:07
> Damn, I couldn't find that issue because it doesn't even mention "column"

It does now. :P
