### ISSUE TITLE
Can't open Zed on WSL2

### ISSUE THREAD

**Issue by MarcoGorelli** [zed-industries/zed#17229] opened 2024-09-01 10:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Here's what I ran:
```console
marcogorelli@DESKTOP-U8OKFP3:~/formulaic-dev$ curl -f https://zed.dev/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4327  100  4327    0     0   9517      0 --:--:-- --:--:-- --:--:--  9530
Downloading Zed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   565  100   565    0     0    394      0  0:00:01  0:00:01 --:--:--   394
100 59.2M  100 59.2M    0     0  7080k      0  0:00:08  0:00:08 --:--:-- 9072k
Zed has been installed. Run with 'zed'
marcogorelli@DESKTOP-U8OKFP3:~/formulaic-dev$ zed

```

The last command just hangs forever

### Environment

> Run the copy system specs into clipboard command palette action

what's this?

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

$ cat ~/.local/share/zed/logs/Zed.log
2024-09-01T10:43:54.976289035+01:00 [INFO] ========== starting zed ==========
2024-09-01T10:44:17.718585119+01:00 [INFO] ========== starting zed ==========
2024-09-01T10:44:27.129328268+01:00 [INFO] ========== starting zed ==========
2024-09-01T10:45:31.543485252+01:00 [INFO] ========== starting zed ==========
2024-09-01T10:46:04.688947567+01:00 [INFO] ========== starting zed ==========
2024-09-01T11:08:34.56020585+01:00 [INFO] ========== starting zed ==========

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-09-01 13:58
https://github.com/zed-industries/zed/issues?q=is%3Aissue+wsl2+is%3Aclosed
https://github.com/zed-industries/zed/issues?q=is%3Aissue+wsl2+is%3Aopen

Shows plenty of WSL2-related issues, tracks lead https://github.com/zed-industries/zed/issues/14173 and lead here in the end: https://github.com/zed-industries/zed/issues/16428

I'll close this as a duplicate of already existing issues, as it's pretty generic and we don't have an official Windows support yet.

**Closed by SomeoneToIgnore** 2024-09-01 13:58 UTC
Labels: defect, triage, admin read
