### ISSUE TITLE
Command text prepended to shell output

### ISSUE THREAD

**Issue by azkarim** [zed-industries/zed#20603] opened 2024-11-13 15:52 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

In terminal, command text gets prepended to shell output. It doesn't happen on local shell. My shell is zsh.

### Environment

Zed: v0.160.7 (Zed)
OS: macOS 14.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-11-13 at 9 42 54 PM](https://github.com/user-attachments/assets/c00685d3-4c84-4db7-a1e5-5f8bafe89ac2)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-11-14 21:43
Can you try setting `DISABLE_AUTO_TITLE="true"` and see if that helps? [link](https://stackoverflow.com/questions/30940299/zsh-repeats-command-in-output)

I think this may be zsh attempting to set the tab title and Zed not correctly handling the control characters. 

If so, I think it may be a duplicate of:
- https://github.com/zed-industries/zed/issues/17721

**Comment by azkarim** [comment] 2024-11-15 14:04
The issue seems to be solved with recent update. I didn't need to apply the fix.

**Closed** 2024-11-15 14:16 UTC
Labels: bug, terminal, needs info / awaiting response

**Comment by bhb603** [comment] 2024-11-15 17:53
I'm having the same issue, but just discovered an interesting caveat:

- When I launch zed from a tmux session (executing `zed .`), the issue occurs
- When I launch zed outside of tmux, either from a regular terminal session, or clicking the MacOS app, the issue is not present

It seems that the value of `TERM` is being inherited by the Zed terminal, so I can reproduce the issue just be setting `TERM=tmux-256color`, which is the value when launched from a tmux session:

<img width="305" alt="image" src="https://github.com/user-attachments/assets/dfecf15f-5088-4580-92b9-b13f160faee1">

Any thoughts?  For reference, it seems that VS Code does NOT inherit the environment from tmux, ie I can launch `code .` from a tmux session, and VS Code terminal has `TERM=xterm-256color` and behaves normally.

**Comment by azkarim** [comment] 2024-11-15 17:57
The issue has returned or rather it **only** happens on a git repo.

**Comment by azkarim** [comment] 2024-11-15 18:08
It happens **only when** Zed is launched with `zed .` command.
