### ISSUE TITLE
When the number of lines in a file is too large, the selected text blocks will be misplaced

### ISSUE THREAD

**Issue by ZeroHawkeye** [zed-industries/zed#15370] opened 2024-07-28 10:27 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

When the number of lines in a file is too large, the selected text blocks will be misplaced

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/user-attachments/assets/9afa187d-abe9-434d-a933-07d58f2f88e7)

**Comment by notpeter** [comment] 2024-07-28 14:16
I think this is a duplicate of:
- https://github.com/zed-industries/zed/issues/5355

Basically in very large files (like your >10million line file) we have some floating point precision issues.

See also:
- https://github.com/zed-industries/zed/issues/5183

**Closed by notpeter** 2024-07-28 14:16 UTC
Labels: enhancement, triage, admin read
