### ISSUE TITLE
ico file is still the old preview after replaced by. In fact, the file has been replaced

### ISSUE THREAD

**Issue by jizhi0v0** [zed-industries/zed#16851] opened 2024-08-26 02:25 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Just drag a same name image file then replace it. like 「favicon.ico」

### Environment

Zed: v0.150.3 (Zed)
OS: macOS 15.1
Memory: 36 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by jizhi0v0** [comment] 2024-08-26 02:27
Even if I delete the file first and then copy it, it still happens

**Comment by notpeter** [comment] 2024-08-27 20:50
Duplicate of
- https://github.com/zed-industries/zed/issues/15907

**Closed by notpeter** 2024-08-27 20:50 UTC
Labels: defect, triage, admin read
