### ISSUE TITLE
Touch-screen on Wayland doesn't work at all

### ISSUE THREAD

**Issue by GildedHonour** [zed-industries/zed#17828] opened 2024-09-14 14:51 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It doesn't respond to any touch

### Environment

Arch Linux, Wayland

**Comment by notpeter** [comment] 2024-09-17 20:29
Duplicate of:
- https://github.com/zed-industries/zed/issues/13698

**Closed by notpeter** 2024-09-17 20:29 UTC
Labels: defect, triage, admin read
