### ISSUE TITLE
Zed repaint, from transparent to blinking on Fedora 40 and humble laptop

### ISSUE THREAD

**Issue by buahaha** [zed-industries/zed#15274] opened 2024-07-26 12:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Install Zed for Linux (using command from zed.dev on Fedora 40)
2. Open Zed
3. Blinking, transparent, on move, sometimes still - overwhelmingly not pleasant to an eye

See in movie:
[zed-repaint.webm](https://github.com/user-attachments/assets/3b4bc811-65ef-42a0-9a2f-d789822e72d8)

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland fedora 40
Memory: 3.6 GiB
Architecture: x86_64

Intel UHD Graphics 600 64M DVMT Pre-Allocated

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Usable on most hardware that support Rust and on Fedora

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by buahaha** [comment] 2024-07-26 17:14
https://github.com/user-attachments/assets/99657793-4f94-49a3-9e50-c3456880e918

**Comment by notpeter** [comment] 2024-07-28 16:08
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/14101

**Closed by notpeter** 2024-07-28 16:08 UTC
Labels: defect, triage, admin read
