### ISSUE TITLE
Closing tab after "Go to Definition" should return to previous tab

### ISSUE THREAD

**Issue by Dagunov** [zed-industries/zed#19352] opened 2024-10-17 09:53 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If I remember correctly, this behaviour worked right some time ago.

1. Multiple tabs opened, not last tab opened (tab A).
2. Select some symbol and go to definition.
3. Close newly opened tab.

**Actual behaviour:**
Tab closes, tab right to tab A is selected.

**Expected behaviour:**
Tab closes, tab A is selected.

### Environment

Zed: v0.157.5 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-10-17 20:33
- Duplicate of: https://github.com/zed-industries/zed/issues/19036
- Fixed here: https://github.com/zed-industries/zed/pull/19150

It is available in Zed Preview as of yesterday and will be available in Zed Stable next Wednesday (2024-10-23).
Thanks for reporting.

**Closed by notpeter** 2024-10-17 20:33 UTC
Labels: defect, triage, admin read
