### ISSUE TITLE
Add the expand all code

### ISSUE THREAD

**Issue by toplyb** [zed-industries/zed#14542] opened 2024-07-16 06:39 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

I want to add shortcuts to collapse and expand all of my code. For example, `JetBrains` uses `command & Shift & -` or `command & Shift & +` to expand and shrink all code.

Also, when I write css code like this, the left side can't show the fold button.
<img width="184" alt="image" src="https://github.com/user-attachments/assets/2a0a44e7-626a-4898-b16c-ecc8d1717625">

**Comment by notpeter** [comment] 2024-07-16 19:03
I believe this is a duplicate of:
- #5142

**Comment by JosephTLyons** [comment] 2024-07-16 19:25
I think so as well, let's go ahead and close this out in favor of #5142. @toplyb, make sure to upvote (👍) on the other issue!

**Closed by JosephTLyons** 2024-07-16 19:25 UTC
Labels: enhancement, needs info / awaiting response, editor
