### ISSUE TITLE
Shortcuts doesn't work with non-latin active keyboard layout

### ISSUE THREAD

**Issue by OlegAndreych** [zed-industries/zed#15008] opened 2024-07-23 11:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Shortcuts doesn't work with non-latin active keyboard layout.

E.g. cannot select all text by `Ctrl+A`.

### Environment

Manjaro Linux 24.0.4

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by notpeter** [comment] 2024-07-25 23:11
Likely a duplicate of:
- https://github.com/zed-industries/zed/issues/14053

**Closed** 2024-07-25 23:13 UTC
Labels: defect, triage, admin read
