### ISSUE TITLE
Replace text by '\n' (newline)

### ISSUE THREAD

**Issue by cdc-lst** [zed-industries/zed#9863] opened 2024-03-27 13:23 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

In VS Code and other editors, it's possible to replace text by newline characters (usually when RegExp matching is enabled in Find/Replace). At the moment, Zed always inserts literal '\n' characters instead of new lines when inputting '\n' as replacement text.

Example: In the text "This text is one line", replacing /\s/ (space) by '\n' should yield
"This
text
is
one
line".

At the moment, you will get "This\ntext\nis\none\nline".

### If applicable, add mockups / screenshots to help present your vision of the feature

Setup:
![before](https://github.com/zed-industries/zed/assets/125039568/e2a7954d-334a-4188-bf56-f44377220c97)

What happens currently:
![after_now](https://github.com/zed-industries/zed/assets/125039568/8589b845-5771-483b-a3ac-c5fc7e7089fb)

What should happen:
![after_should](https://github.com/zed-industries/zed/assets/125039568/9bd27945-13c1-450b-8100-75804721facf)

**Comment by VKondakoff** [comment] 2024-03-27 13:56
Duplicate of https://github.com/zed-industries/zed/issues/7645

**Comment by Moshyfawn** [comment] 2024-03-27 14:46
It looks like it was fixed in the other issue a few days ago. It should be in Preview today. Closing this in the meantime.

Duplicate of
- #7645

**Closed by Moshyfawn** 2024-03-27 14:46 UTC
Labels: enhancement, triage, admin read
