### ISSUE TITLE
Quick search functionality is not performing as expected when I use Chromium repo

### ISSUE THREAD

**Issue by balaji-sivasakthi** [zed-industries/zed#8629] opened 2024-02-29 19:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Clone the Chromium Repo (https://chromium.googlesource.com/chromium/src/+/main/docs/mac_build_instructions.md)
2. Open Repo in Zed
3. Quick file search (devtool)
4. Hold down and up 
5. down one by one 

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://www.loom.com/share/bc5d6276487c43af8d908671e43ea573?sid=7ab3a142-d268-4b6c-a0d4-236d6e4f2793

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2024-03-01T00:07:16+05:30 [INFO] ========== starting zed ==========
2024-03-01T00:07:16+05:30 [INFO] Opening main db
2024-03-01T00:07:16+05:30 [ERROR] crates/settings/src/settings_file.rs:76: EOF while parsing a value at line 1 column 0
2024-03-01T00:07:16+05:30 [ERROR] crates/extension/src/extension_store.rs:181: No such file or directory (os error 2)
2024-03-01T00:07:16+05:30 [ERROR] crates/zed/src/zed.rs:555: EOF while parsing a value at line 1 column 0
2024-03-01T00:07:16+05:30 [INFO] Opening main db
2024-03-01T00:07:17+05:30 [ERROR] crates/zed/src/main.rs:980: Is a directory (os error 21)
2024-03-01T00:07:17+05:30 [ERROR] crates/zed/src/main.rs:980: Is a directory (os error 21)
2024-03-01T00:07:19+05:30 [INFO] set environment variables from shell:/bin/zsh, path:/Users/balajisivasakthi/.rbenv/shims:/Users/balajisivasakthi/.yarn/bin:/Users/balajisivasakthi/.config/yarn/global/node_modules/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/balajisivasakthi/Library/Android/sdk/emulator:/Users/balajisivasakthi/Library/Android/sdk/platform-tools:/Users/balajisivasakthi/chromium/depot_tools

**Comment by hferreiro** [comment] 2024-03-01 11:42
Related: https://github.com/zed-industries/zed/issues/7504

**Comment by Moshyfawn** [comment] 2024-03-02 02:20
I'm going to close this thread in favour of the other one. Let me know if you want to reopen it, otherwise be sure to +👍 the other topic and add any additional information to the other thread.

**Comment by Moshyfawn** [comment] 2024-03-02 02:20
Duplicate of #7504

**Closed by Moshyfawn** 2024-03-02 02:20 UTC
Labels: defect, file finder
