### ISSUE TITLE
Modifier keys are lost in multiple successive keystrokes

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/zed#4802] opened 2023-04-10 22:44 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If you press multiple alphanumeric characters, they're correctly inputted. For example, hit `a`, then hit `b` while still holding `a`. The editor enters `ab`. That's great.

If you press `Right Arrow`, then `Backspace` while still holding `Right Arrow`, the `Backspace` keypress is swallowed and lost. So when you're typing quickly, deleting multiple characters in different places, keystrokes are just randomly lost.

I can't figure out exactly which keys do and don't work like this.

### Environment

Zed: v0.80.5 (stable)
OS: macOS 13.1.0
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-07-28 05:43
I'm not able to reproduce this in current Zed, so I'm going to close this issue out. If you run into this again, feel free to open a new issue!

**Closed by JosephTLyons** 2024-07-28 05:43 UTC
Labels: defect, keymap / key binding
