### ISSUE TITLE
elixir-ls stopped working

### ISSUE THREAD

**Issue by dm7r33** [zed-industries/zed#15877] opened 2024-08-06 19:47 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Elixir language server fails to start. My guess is the update that shipped fine - elixir-ls just worked fine last week.

### Environment

archlinux:latest

zed 0.146.5

using fish

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-08-06T21:41:21.407288841+02:00 [INFO] starting language server. binary path: "/home/dmtr/.local/share/zed/extensions/work/elixir/elixir-ls-v0.23.0/language_server.sh", working directory: "/home/dmtr/Projects/elixirlang/islands_engine", args: []
2024-08-06T21:41:21.407996122+02:00 [ERROR] failed to start language server "elixir-ls": failed to spawn command. path: "/home/dmtr/.local/share/zed/extensions/work/elixir/elixir-ls-v0.23.0/language_server.sh", working directory: "/home/dmtr/Projects/elixirlang/islands_engine", args: []
2024-08-06T21:41:21.408102528+02:00 [ERROR] server stderr: Some("")
2024-08-06T21:41:21.408197152+02:00 [INFO] retrying installation of language server "elixir-ls" in 1s
2024-08-06T21:41:22.408352415+02:00 [INFO] About to spawn test binary
2024-08-06T21:41:22.408490559+02:00 [WARN] test binary failed to launch
2024-08-06T21:41:22.408592146+02:00 [WARN] test binary check failed
2024-08-06T21:41:22.408693623+02:00 [INFO] beginning to reinstall server
2024-08-06T21:41:22.408805779+02:00 [INFO] deleting server container
2024-08-06T21:41:22.408999215+02:00 [ERROR] server container removal

Caused by:
    No such file or directory (os error 2)
</pre></details>

**Comment by benswift** [comment] 2024-08-07 01:08
I'm seeing the same error. My logs, if they're helpful:

```log
2024-08-07T01:06:56.937263Z [INFO] starting language server "elixir-ls", path: "/Users/ben/Documents/edex/panic/panic", id: 2
2024-08-07T01:06:56.950021Z [INFO] starting language server. binary path: "/Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/language_server.sh", working directory: "/Users/ben/Documents/edex/panic/panic", args: []
2024-08-07T01:06:56.955138Z [ERROR] cannot read LSP message headers
2024-08-07T01:06:56.95523Z [ERROR] failed to start language server "elixir-ls": oneshot canceled
2024-08-07T01:06:56.955305Z [ERROR] server stderr: Some("Running /Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/launch.sh\n/Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/language_server.sh: line 23: /Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/launch.sh: Permission denied\n/Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/language_server.sh: line 23: exec: /Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/launch.sh: cannot execute: Undefined error: 0\n")
2024-08-07T01:06:56.955385Z [INFO] retrying installation of language server "elixir-ls" in 1s
2024-08-07T01:06:56.955452Z [ERROR] Broken pipe (os error 32)
2024-08-07T01:06:56.95551Z [ERROR] server shut down
```

**Comment by benswift** [comment] 2024-08-07 01:59
An update from me: it does seem to be a permissions issue, as noted in #15802.

In the `~/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0` directory, doing

    chmod +x debug_adapter.* exec.* language_server.* launch.sh
    
did the trick and fixed the issue.

**Comment by benswift** [comment] 2024-08-07 06:08
One more update (sorry for the spam) - the above `chmod` fix helped the LS start without crashing, but it's still being much flakier than usual - crashing even on basic things like providing autocompletion. An excerpt from my `elixir-ls` logs:

```log
Received client configuration via workspace/configuration
%{}
Registering for workspace/didChangeConfiguration notifications
Starting build with MIX_ENV: test MIX_TARGET: host
client/registerCapability succeeded
Registering for workspace/didChangeWatchedFiles notifications
client/registerCapability succeeded
Received workspace/didChangeConfiguration
Loaded DETS databases in 121ms
Compiling 37 files (.ex)
Loaded DETS databases in 102ms
Generated panic app
Compile took 2619 milliseconds
Starting build with MIX_ENV: test MIX_TARGET: host
[ElixirLS WorkspaceSymbols] Indexing...
[ElixirLS WorkspaceSymbols] Module discovery complete
[ElixirLS WorkspaceSymbols] 613 symbols added to index in 18ms
Compile took 1233 milliseconds
Updating incremental PLT
Incremental PLT updated in 9870ms, changed 9 modules, analyzed 18, 0 warnings found
Loaded PLT info in 971ms
Dialyzer analysis is up to date
Received workspace/didChangeConfiguration
Starting build with MIX_ENV: test MIX_TARGET: host
Loaded DETS databases in 95ms
Compile took 1507 milliseconds
Updating incremental PLT
Incremental PLT updated in 1556ms, changed 0 modules, analyzed 0, 0 warnings found
Loaded PLT info in 939ms
Dialyzer analysis is up to date
Starting build with MIX_ENV: test MIX_TARGET: host
Compile took 801 milliseconds
[ElixirLS WorkspaceSymbols] Updating index...
[ElixirLS WorkspaceSymbols] 0 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 symbols added to index in 0ms
Updating incremental PLT
Incremental PLT updated in 1606ms, changed 0 modules, analyzed 0, 0 warnings found
Loaded PLT info in 930ms
Dialyzer analysis is up to date
Starting build with MIX_ENV: test MIX_TARGET: host
Compile took 809 milliseconds
[ElixirLS WorkspaceSymbols] Updating index...
Starting build with MIX_ENV: test MIX_TARGET: host
[ElixirLS WorkspaceSymbols] 0 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 symbols added to index in 0ms
Compile took 1273 milliseconds
Updating incremental PLT
Incremental PLT updated in 1539ms, changed 0 modules, analyzed 0, 0 warnings found
Loaded PLT info in 919ms
Dialyzer analysis is up to date
Starting build with MIX_ENV: test MIX_TARGET: host
Compile took 871 milliseconds
[ElixirLS WorkspaceSymbols] Updating index...
[ElixirLS WorkspaceSymbols] 0 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 symbols added to index in 0ms
Updating incremental PLT
Incremental PLT updated in 1563ms, changed 0 modules, analyzed 0, 0 warnings found
Loaded PLT info in 940ms
Dialyzer analysis is up to date
Starting build with MIX_ENV: test MIX_TARGET: host
Compile took 820 milliseconds
[ElixirLS WorkspaceSymbols] Updating index...
Starting build with MIX_ENV: test MIX_TARGET: host
[ElixirLS WorkspaceSymbols] 0 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 symbols added to index in 0ms
Compile took 1267 milliseconds
Updating incremental PLT
Incremental PLT updated in 1566ms, changed 0 modules, analyzed 0, 0 warnings found
Loaded PLT info in 907ms
Dialyzer analysis is up to date
Starting build with MIX_ENV: test MIX_TARGET: host
Compile took 861 milliseconds
[ElixirLS WorkspaceSymbols] Updating index...
Starting build with MIX_ENV: test MIX_TARGET: host
[ElixirLS WorkspaceSymbols] 0 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 symbols added to index in 0ms
Compile took 1250 milliseconds
[ElixirLS WorkspaceSymbols] Updating index...
Starting build with MIX_ENV: test MIX_TARGET: host
[ElixirLS WorkspaceSymbols] 0 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 symbols added to index in 0ms
Compile took 1260 milliseconds
Updating incremental PLT
Incremental PLT updated in 1531ms, changed 0 modules, analyzed 0, 0 warnings found
Loaded PLT info in 933ms
Dialyzer analysis is up to date
Process #PID<0.50.0> raised an exception
** (MatchError) no match of right hand side value: :error
    (kernel 10.0.1) code_server.erl:1184: :code_server.reply_loading/4
    (kernel 10.0.1) code_server.erl:1415: :code_server.finish_on_load_2/3
    (kernel 10.0.1) code_server.erl:1397: :code_server.finish_on_load/3
    (kernel 10.0.1) code_server.erl:183: :code_server.loop/1
** (exit) exited in: GenServer.call(ElixirLS.LanguageServer.JsonRpc, {:packet, %{"jsonrpc" => "2.0", "method" => "textDocument/didChange", "params" => %{"contentChanges" => [%{"range" => %{"end" => %{"character" => 24, "line" => 55}, "start" => %{"character" => 24, "line" => 55}}, "text" => "c"}], "textDocument" => %{"uri" => "file:///Users/ben/Documents/edex/panic/panic/test/test_helper.exs", "version" => 50}}}}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.17.2) lib/gen_server.ex:1121: GenServer.call/3
    (elixir 1.17.2) lib/stream.ex:482: anonymous fn/4 in Stream.each/2
    (elixir 1.17.2) lib/stream.ex:1717: Stream.do_element_resource/6
    (elixir 1.17.2) lib/stream.ex:1891: Enumerable.Stream.do_each/4
    (elixir 1.17.2) lib/stream.ex:690: Stream.run/1
    /Users/ben/Library/Application Support/Zed/extensions/work/elixir/elixir-ls-v0.23.0/launch.exs:18: (file)
    (elixir 1.17.2) lib/code.ex:1491: Code.require_file/2
```

**Comment by JosephTLyons** [comment] 2024-08-09 20:28
I think this is a duplicate of:

- https://github.com/zed-industries/zed/issues/15802

So I'm going to close this one out. I you think I'm wrong, feel free to comment and I'll reopen!

**Closed by JosephTLyons** 2024-08-09 20:28 UTC
Labels: defect, elixir, language, language server
