### ISSUE TITLE
Multiselect files and folders in the explorer

### ISSUE THREAD

**Issue by swaroopRajwal** [zed-industries/zed#11061] opened 2024-04-26 17:46 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm not sure if this is an enhancement or a bug

There are two types of multi select files/folders
1. Single select multiple files - `Ctrl + click` or `Command + click` 
2. Range select multiple files - `Shift + click` 

I guess I won't need to explain `Shift + click` & `Cmd + click` 

This doesn't seem to be happening in Zed rn
When I do `Shift+click` nothing happens, just the file opens up in the editor area or the folder un-collapses/collapses
And when I do `Cmd+click` it opens the file in new section in the editor

I went through the docs and keymaps in Zed's settings, wasn't able to figure out how to enable this 😅 

Zed is amazing 🙌🏻 

### Environment

Zed: v0.132.2 (Zed)
OS: macOS 14.1.2
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/zed/assets/72123851/ebae7715-4838-4de6-a510-7b1a10c06248

Sorry I wasn't able to include key strokes while recording the video
But in the first part while clicking on the files and folders I'm pressing shift and in the other half, I'm pressing control

**Comment by JosephTLyons** [comment] 2024-04-26 18:12
Hey @swaroopRajwal,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4983

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-04-26 18:12 UTC
Labels: defect, project panel
