### ISSUE TITLE
order completion by most used

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#11057] opened 2024-04-26 14:50 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

it would be great if the completion could be ordered by how common they are used. 

For example (in rust) complete "Re" should have as a first result "Result" and not "AsRef"

**Comment by Moshyfawn** [comment] 2024-04-26 14:55
This has already been brought up, especially for Rust, so I'm going to close this thread in favour of the existing one, to avoid parallel conversations, and to avoid creating broad topics that go on for a long time. Be sure to +👍 the existing topic.

Duplicate of:
- #9342

**Closed by Moshyfawn** 2024-04-26 14:55 UTC
Labels: enhancement, triage, admin read
