### ISSUE TITLE
Cmd-K not working in terminal with Sublime Text key bindings

### ISSUE THREAD

**Issue by christianh104** [zed-industries/zed#15517] opened 2024-07-31 01:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Cmd-K is not working to clear the terminal with Sublime Text key bindings, unless pressed twice. I'm fairly certain this was introduced by #13792, Cmd-K then Cmd-B to toggle left dock. It seems pressing Cmd-K causes Zed to wait for another key command. This seems inappropriate for the terminal.

The next key input is ignored as well. For example, if I want to clear the terminal and run the previous command, I would normally press Cmd-K, up, enter. Now I have to do Cmd-K, Cmd-K, up, up, enter.

Setting the binding to null does not work:
```
{
  "context": "Workspace",
  "bindings": {
    "cmd-k cmd-b": null
  }
}
```

If I set the binding to another action, it does override the default, so not sure what's going on with that.

### Environment

Zed: v0.146.3 (Zed Preview)
OS: macOS 14.5.0
Memory: 48 GiB
Architecture: aarch64

**Comment by notpeter** [comment] 2024-07-31 18:40
Duplicate of: 
- https://github.com/zed-industries/zed/issues/10176

**Closed by notpeter** 2024-07-31 18:40 UTC
Labels: defect, triage, admin read
