### ISSUE TITLE
Markdown preview: "not enough space in Arena"

### ISSUE THREAD

**Issue by kud1ing** [zed-industries/zed#10824] opened 2024-04-21 16:10 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When i try to open the preview on a Markdown file (2600 lines, 99 kB) it "crashes".

### Environment

Zed: v0.131.6 (Zed)
OS: macOS 14.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

2024-04-21T18:00:49+02:00 [INFO] ========== starting zed ==========
2024-04-21T18:00:49+02:00 [INFO] Opening main db
2024-04-21T18:00:49+02:00 [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-04-21T18:00:49+02:00 [INFO] set environment variables from shell:/bin/zsh, [...]
2024-04-21T18:00:49+02:00 [ERROR] crates/zed/src/zed.rs:628: EOF while parsing a value at line 1 column 0
2024-04-21T18:00:49+02:00 [INFO] Opening main db
2024-04-21T18:00:49+02:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-04-21T18:00:49+02:00 [INFO] Opening main db
2024-04-21T18:00:49+02:00 [INFO] Opening main db
2024-04-21T18:00:49+02:00 [INFO] Initializing default prettier with plugins {}
2024-04-21T18:00:49+02:00 [INFO] Initializing default prettier with plugins {}
2024-04-21T18:00:49+02:00 [INFO] starting language server "rust-analyzer", path: "[...]", id: 1
2024-04-21T18:00:49+02:00 [INFO] Initializing default prettier with plugins {}
2024-04-21T18:00:49+02:00 [INFO] fetching latest version of language server "rust-analyzer"
2024-04-21T18:00:50+02:00 [INFO] downloading language server "rust-analyzer"
2024-04-21T18:00:50+02:00 [INFO] starting language server. binary path: "[...]", args: []
2024-04-21T18:01:02+02:00 [ERROR] {
  "thread": "main",
  "payload": "not enough space in Arena",
  "location_data": {
    "file": "/Users/administrator/actions-runner-2/_work/zed/zed/crates/gpui/src/arena.rs",
    "line": 80
  },
  "backtrace": [
    "<backtrace::capture::Backtrace>::create",
    "<backtrace::capture::Backtrace>::new",
    "Zed::init_panic_hook::{closure#0}",
    "std::panicking::rust_panic_with_hook",
    "std::panicking::begin_panic_handler::{{closure}}",
    "std::sys_common::backtrace::__rust_end_short_backtrace",
    "_rust_begin_unwind",
    "core::panicking::panic_fmt",
    "<gpui::element::AnyElement>::new::<gpui::elements::div::Div>",
    "<gpui::elements::div::Div as gpui::element::ParentElement>::children::<gpui::elements::div::Div, alloc::vec::Vec<gpui::elements::div::Div>>",
    "markdown_preview::markdown_renderer::render_markdown_block",
    "markdown_preview::markdown_renderer::render_markdown_block",
    "markdown_preview::markdown_renderer::render_markdown_block",
    "<markdown_preview::markdown_preview_view::MarkdownPreviewView>::new::{closure#0}::{closure#0}",
    "<gpui::elements::list::StateInner>::layout_items",
    "<gpui::elements::list::List as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::list::List> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::view::AnyView as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::view::AnyView> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::element::AnyElement>::layout",
    "<gpui::view::AnyView as gpui::element::Element>::after_layout::{closure#0}",
    "<gpui::view::AnyView as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::view::AnyView> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::element::Drawable<gpui::element::AnyElement> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}::{closure#0}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}::{closure#1}",
    "<gpui::elements::div::Interactivity>::after_layout::<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}",
    "<gpui::window::element_cx::ElementContext>::with_element_state::<gpui::elements::div::InteractiveElementState, core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Interactivity>::after_layout<core::option::Option<gpui::window::element_cx::Hitbox>, <gpui::elements::div::Div as gpui::element::Element>::after_layout::{closure#0}>::{closure#0}>::{closure#0}",
    "<gpui::elements::div::Div as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::elements::div::Stateful<gpui::elements::div::Div>> as gpui::element::ElementObject>::after_layout",
    "<gpui::view::AnyView as gpui::element::Element>::after_layout",
    "<gpui::element::Drawable<gpui::view::AnyView> as gpui::element::ElementObject>::after_layout",
    "<gpui::element::AnyElement>::layout",
    "<gpui::window::WindowContext>::draw",
    "<gpui::window::Window>::new::{closure#2}::{closure#1}",
    "<gpui::window::Window>::new::{closure#2}",
    "gpui::platform::mac::window::step",
    "<gpui::platform::mac::platform::MacPlatform as gpui::platform::Platform>::run",
    "<gpui::app::App>::run::<Zed::main::{closure#3}>",
    "Zed::main",
    "std::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>",
    "std::rt::lang_start::<()>::{closure#0}",
    "std::rt::lang_start_internal",
    "_main"
  ],
  "app_version": "0.131.6",
  "release_channel": "Zed",
  "os_name": "macOS",
  "os_version": "14.4.1",
  "architecture": "aarch64",
  "panicked_on": 1713715262955,
  "installation_id": "3327696a-d413-48cd-bda3-89ea824f123c",
  "session_id": "d88aae04-421d-4132-8932-70ff4f4f1eb1"
}

**Comment by bennetbo** [comment] 2024-04-21 18:14
Hey,
I cannot reproduce this even with larger markdown documents (> 10000 lines). Is there any possibility that you could share the contents of the file you are trying to preview?

**Comment by kud1ing** [comment] 2024-04-22 04:10
Hi Bennet,

the content is unfortunately private. I’ll try to bisect it. For the time being: it’s basically a long nested list with checkboxes.

**Comment by bennetbo** [comment] 2024-04-22 07:58
Thanks for the information, I managed to reproduce the panic when a markdown file contains a LOT of checkboxes (for me it starts to panic when it has to render ~1100 checkboxes)

**Comment by bennetbo** [comment] 2024-04-22 15:05
Hey, just put up #10852 which should also fix your issue. Would be great if you could build from source and try to open your document (if possible)

**Comment by kud1ing** [comment] 2024-04-22 16:58
Thank you. Yes, that indeed prevents  the problem.

If you wonder: the context is, I have a GTD style tickler file with generated task for each year. So that's about 365 * 5 checkboxes.

**Comment by bennetbo** [comment] 2024-04-24 12:14
> Thank you. Yes, that indeed prevents the problem. I hope the fix is not too exotic.
> 
> If you wonder: I have a GTD style tickler file with generated tasks for each year. So that's about 365 * 5 checkboxes.

Great to hear and thanks for testing :+1:

**Comment by JosephTLyons** [comment] 2024-05-01 19:37
A fix for this should be availabe in [0.134.0-pre](https://zed.dev/releases/preview/0.134.0).

**Closed by JosephTLyons** 2024-05-01 19:37 UTC
Labels: defect, panic / crash, markdown, language

**Comment by kud1ing** [comment] 2024-05-02 11:11
Thank you all.

**Comment by sc0rp10** [comment] 2024-11-10 20:46
The same issue with huge (100MB) JSON file
