### ISSUE TITLE
Editor Maxes out at 1025 Columns When 'soft_wrap' Is Set to 'none'

### ISSUE THREAD

**Issue by danremollino** [zed-industries/zed#14980] opened 2024-07-22 19:41 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I needed to deal with some base64 encoded file strings and found that I could not interact with characters past 1025 columns. Characters exists beyond this point and can be selected and edited with the keyboard, but the curser stops at 1025 columns and you can't scroll past that point.

### Environment

Zed: v0.144.4 (Zed)
OS: macOS 14.5.0
Memory: 36 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

`"soft_wrap:" "none"`
![Screenshot 2024-07-22 at 3 35 17 PM](https://github.com/user-attachments/assets/70db614a-686a-4fc1-9a3d-bee9eb070350)
`"soft_wrap": "editor_width",`
![Screenshot 2024-07-22 at 3 35 31 PM](https://github.com/user-attachments/assets/f7d5f241-94e8-481b-93f1-628c7e631b54)

**Comment by JosephTLyons** [comment] 2024-07-23 20:41
Hey @danremollino,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/12666

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-23 20:41 UTC
Labels: defect, editor, setting
