### ISSUE TITLE
Project Panel: Folders automatically collapse

### ISSUE THREAD

**Issue by andrebaerlocher** [zed-industries/zed#13782] opened 2024-07-03 15:11 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Sometimes the tree view of the folders in the Project Panels collapses, but reopens when I change to a file tab.

It happens...
- when I create a new file
- when I type, but not always 
- perhaps at random time intervals

That started only a few days ago, before it was working fine. I couldn't even point it to an update or something.

It happened also to other people, one answer that was given to that problem was:
"Try to open another project. I removed from my project cspell.json github-actions and biome from my project and it solves the issue. I don't know which one exactly solves the issue"

I could not fix the issue with that suggestion.

### Environment

Zed: v0.141.3 (Zed)
OS: macOS 14.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by osiewicz** [comment] 2024-07-03 15:25
I believe this is a duplicate of https://github.com/zed-industries/zed/issues/13762

**Comment by andrebaerlocher** [comment] 2024-07-03 15:28
It is, I didn't search for shrink but collapse, thanks for pointing it out!

**Comment by osiewicz** [comment] 2024-07-03 15:29
Yeah, we should probably change the title of that issue. I'm gonna close out yours for now. Thanks for taking the time to report this issue though!

**Closed by osiewicz** 2024-07-03 15:29 UTC
Labels: defect, triage, admin read
