### ISSUE TITLE
allow `Zed file.txt` even if zed is already running

### ISSUE THREAD

**Issue by jyn514** [zed-industries/zed#12548] opened 2024-06-01 02:33 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

VScode allows running `code file.txt` to open a file or directory in the editor. if vscode is already running, it opens a new window (or possibly a new tab in an existing window, if it recognizes the directory the file is in).

Zed instead gives a hard error:
```
; Zed ~/src/example
zed is already running
```
it would be nice if it also supported this.

as an aside, https://github.com/zed-industries/zed/issues/4906 mentions "using the macOS Finder dialog from menubar" but i'm not sure how to get this working outside macOS; "Open With" on linux doesn't work.

**Comment by SomeoneToIgnore** [comment] 2024-06-01 07:26
Duplicate of https://github.com/zed-industries/zed/issues/11770#issue-2293889996 
(TL;DR — there's a confusion between `Zed` the editor binary and `zed` the cli binary that is capable of doing what's requested in this issue)

Opening a single file via cmd-o is also a nice thing to get fixed on Linux, but that seems to be a separate issue discussed somewhere (failed to find it now alas).

On macOS, drag and drop is also a way to open a file, but not sure it's supported in Linux builds yet.

**Closed by SomeoneToIgnore** 2024-06-01 07:26 UTC
Labels: enhancement, triage, admin read

**Comment by jyn514** [comment] 2024-06-01 14:35
yes, that fixed it, thank you!

for anyone running across this in the future, i'm on linux so there's no prebuilt binaries and `cargo build --release` doesn't actually build the cli by default. you can set up `zed` to run the cli as follows:
```sh
binaries=$(cargo build --release --all | jq 'select(.reason = "[+2.818|10:32:01]") | .executable | select(. != null)' -r)
cd ~/.local/bin  # this path doesn't actually matter, as long as it's in PATH and not in `target/`
mkdir zed-impl
cp $binaries ~/.local/bin/zed-impl
ln -s zed-impl/cli zed
```
(you can also set up the desktop file with `DO_STARTUP_NOTIFY=true APP_ICON=$(realpath crates/zed/resources/app-icon.p[+0.060|10:35:36]envsubst < crates/zed/resources/zed.desktop.in > ~/.local/share/applications/zed.desktop`)
