### ISSUE TITLE
Hunk discard strange behavior

### ISSUE THREAD

**Issue by Angelk90** [zed-industries/zed#20606] opened 2024-11-13 16:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

As you can see from the video by modifying a line without saving the file, then canceling via hunk controls via Hunk discard, it asks to save the file.

But the file has never been saved, as you can see modifications, I wonder if it is a normal behavior.

https://github.com/user-attachments/assets/c0904247-de25-4b5f-88e8-af3da4a0e60e

### Environment

```
Zed: v0.161.0 (Zed Preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by wanlufun** [comment] 2024-11-18 11:05
Are you referring to the situation where, after editing but leaving the content the same as before, the editor still prompts you to save?
If so, this should be considered normal behavior because the buffer state has changed.

**Comment by notpeter** [comment] 2024-12-16 06:43
This entire hunk accept/reject, git interface and underlying architecture is currently being reworked and so this will not be fixed as-is.  Please open new issues once that has landed if you run into trouble.

In the future please take the time to write out explicit steps to reproduce in addition to providing a video.  Thanks.

**Closed by notpeter** 2024-12-16 06:43 UTC
Labels: bug, editor, git
