### ISSUE TITLE
[Windows] double drive prefix in the path

### ISSUE THREAD

**Issue by quinn** [zed-industries/zed#18416] opened 2024-09-26 22:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am getting this error:

Error: Cannot find module 'C:\C:\Users\quinn\AppData\Local\Zed\extensions\work\html\node_modules\@zed-industries\vscode-langservers-extracted\bin\vscode-html-language-server'

this dir is actually correct, but the double `C:\C:\` is whats causing the error. Other extensions seem to work. 

### Environment

Zed: v0.156.0 (Zed Dev 7eea1a6f51b11bd56150203809f21da7e8b5530d)
OS: Windows 10.0.22631
Memory: 127.1 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 SUPER || NVIDIA || 552.12

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by SomeoneToIgnore** [comment] 2024-10-22 18:08
Duplicate of https://github.com/zed-industries/zed/issues/12013

**Closed by SomeoneToIgnore** 2024-10-22 18:08 UTC
Labels: defect, windows, language server failure, language server
