### ISSUE TITLE
right click folder: remove "Add Folder to Project" menu

### ISSUE THREAD

**Issue by kzhui125** [zed-industries/zed#8104] opened 2024-02-21 06:21 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I right click folder, "New File" should be the first option, "Add Folder to Project" should be removed.

When right click the blank area, "New File" and "New Folder" should be the first menu. since they are mostly used.

<img width="493" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/2eabeeab-fa23-48a3-9b71-d342d0518f5e">

<img width="366" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/63690905-e131-41d8-a8c8-8f3e187eb073">

for example, here is VSCode:

<img width="560" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/7183546c-ea97-4a28-9ffe-27fc43d8d7c5">

<img width="583" alt="image" src="https://github.com/zed-industries/zed/assets/11925432/32c219fe-b22f-46aa-8bd3-0f18dc84b8ce">

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-05-30 18:47
The expected behaviour described in the original post seems to be the current behaviour, so I'm going to close this issue as resolved. Be sure to let us know if you still see the problem.

<img width="1398" alt="image" src="https://github.com/zed-industries/zed/assets/16290753/536ee6f0-b113-4af3-b055-c82cfa4cd396">

**Closed by Moshyfawn** 2024-05-30 18:47 UTC
Labels: defect, project panel
