### ISSUE TITLE
YAML formatting in Zed is breaking Helm YAML parsing

### ISSUE THREAD

**Issue by Dmarcotrigiano** [zed-industries/zed#9129] opened 2024-03-10 01:53 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When saving my templated yaml file, zed formats the curly braces like shown below:

<img width="1327" alt="Screen Shot 2024-03-09 at 8 38 29 PM" src="https://github.com/zed-industries/zed/assets/79153083/d308f736-2d20-49ba-9bd7-ba3de78cb534">

The error in the terminal is resolved if I edit the file contents to remove the spaces in between curly braces, but when saving the file in Zed, the spaces are automatically added.

<img width="674" alt="Screen Shot 2024-03-09 at 8 45 00 PM" src="https://github.com/zed-industries/zed/assets/79153083/39d4f735-d433-4db6-b1f5-a8ca0f94033f">

After fixing the formatting on the braces, installing the helm chart works as expected.

<img width="1334" alt="Screen Shot 2024-03-09 at 8 46 10 PM" src="https://github.com/zed-industries/zed/assets/79153083/9c7c8530-6480-4c08-84d4-728d9b66d327">

Create a helm template, and add a templated value such as 
```yaml
{{ .Values.name }}
```

Save the file and observe that it is changed to:

```yaml
{ { .Values.name } }
```

### Environment

Zed: v0.125.3 (Zed)
OS: macOS 12.7.3
Memory: 32 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-03-10 02:14
This is already being tracked in another issue. I'll close this one in favour of the other.

Duplicate of
- #8487

**Closed by Moshyfawn** 2024-03-10 02:14 UTC
Labels: defect, triage, admin read

**Comment by RichardJECooke** [comment] 2024-09-12 08:06
This fixed YAML problems in `settings.json`:

```yaml
  "languages": {
    "YAML": {
      "format_on_save": "off"
    }
  }
```
