### ISSUE TITLE
Linux: Zed freezes especially when saving

### ISSUE THREAD

**Issue by SethDusek** [zed-industries/zed#12331] opened 2024-05-26 23:02 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I save/:w in Zed, the editor freezes briefly during which time I can't perform any interaction with the UI. I assumed this might be an LSP bug but it seems to be related to https://github.com/zed-industries/zed/pull/12266 after bisecting since it doesn't happen before this commit. 

This also happens at the start when LSP is checking all the crates which makes this strange. 

I thought this might be the same issue as https://github.com/zed-industries/zed/issues/9448, but that issue predates the PR above being merged.

Zed also appears to freeze longer on larger repositories. The issue also occurs if I "de-git" the repo by renaming .git

### Environment

Zed: v1.0.0 (Zed Dev ddb551c794345538dbef112c5bcc2ae99f27b07f)
OS: Linux 1.0.0
Memory: 15.5 GiB
Architecture: x86_64

**Comment by Moshyfawn** [comment] 2024-05-27 00:02
Related:
- #11535

**Comment by CharlesChen0823** [comment] 2024-05-27 05:39
IMO, the main reason is zed watch whole workspace. I tested, if i manual modify `fs:watch` with `unwatch` `target` directory within zed code base, the unresponse will decrease remarkable. So IMO, we should ignore watch some directory, e.g. `.git` or `target` in start watcher.

**Comment by mbrea-c** [comment] 2024-05-28 20:11
> @SethDusek (or anyone else who is newly experiencing this issue after #12266) can you share any details about the repository that you're working in? Is there an open source repository in which this reproduces reliably?

[bevy_animation_graph](https://github.com/mbrea-c/bevy_animation_graph) reliably reproduces the issue for me. It doesn't happen at all on the last commit before #12266 though, so that's what I've been using for now.

**Comment by maxbrunsfeld** [comment] 2024-05-28 20:22
Does there happen to be a git repository in an ancestor directory of the one where you're working?

**Comment by maxbrunsfeld** [comment] 2024-05-28 21:58
I can't yet reproduce the problem. Would you be willing to run a main build of Zed with a non-default log level and reproduce the problem?

```
RUST_LOG=worktree=debug path/to/zed bevy_animation_graph
```

After saving a file, while `cargo check` is running, you should see a lot of messages like this:

```
[2024-05-28T14:53:59-07:00 DEBUG worktree] ignoring event "target/debug/build/serde_json-6ef5dda57c49a908/build-script-build" within unloaded directory
[2024-05-28T14:53:59-07:00 DEBUG worktree] ignoring event "target/debug/build/serde_json-6ef5dda57c49a908/build_script_build-6ef5dda57c49a908" within unloaded directory
[2024-05-28T14:53:59-07:00 DEBUG worktree] ignoring event "target/debug/build/wgpu-407d4d12700928aa/build-script-build" within unloaded directory
[2024-05-28T14:53:59-07:00 DEBUG worktree] ignoring event "target/debug/build/wgpu-407d4d12700928aa/build_script_build-407d4d12700928aa" within unloaded directory
[2024-05-28T14:53:59-07:00 DEBUG worktree] ignoring event "target/debug/build/wgpu-core-3142ef2fb2f0f477/build-script-build" within unloaded directory
```

These messages indicate that Zed is not bothering to handle FS events that occur within the `target` directory.

**Comment by mbrea-c** [comment] 2024-05-28 22:02
> Does there happen to be a git repository in an ancestor directory of the one where you're working (like your home folder)?

No, `git status` on the parent directory does not find anything:
```
fatal: not a git repository (or any of the parent directories): .git
```
> I can't yet reproduce the problem. Would you be willing to run a main build of Zed with a non-default log level and reproduce the problem?

Yep. It's late now but I'll try that tomorrow. Thanks for debugging this!

**Comment by CharlesChen0823** [comment] 2024-05-29 01:35
@maxbrunsfeld as i previous say, I can easy reproduce, using zed code base with zed editor. 

1. might because my machine performance is poor, but in vscode, ui response not hang. 
```
Zed: v1.0.0 (Zed Dev 82a57a121a6b7d024ae30951c8d81ad31bd8bc44)
OS: Linux 1.0.0
Memory: 7.4 GiB
Architecture: x86_64
```
2. But if i manual add code 
```
diff --git a/crates/fs/src/fs.rs b/crates/fs/src/fs.rs
index 33357539a..2d7b090ac 100644
--- a/crates/fs/src/fs.rs
+++ b/crates/fs/src/fs.rs
@@ -436,6 +436,9 @@ impl Fs for RealFs {
             .watch(path, notify::RecursiveMode::Recursive)
             .ok(); // It's ok if this fails, the parent watcher will add it.
 
+        let target_path = path.join("target");
+        file_watcher.unwatch(&target_path).log_err();
+
         let mut parent_watcher = notify::recommended_watcher({
             let watched_path = path.to_path_buf();
             let tx = tx.clone();
```
can decrease hang remarkable.

3. In vscode, there using [excludes](https://github.com/microsoft/vscode/blob/50f2b2eca8d5c6e19ec95f9d46a59f623e60cac3/src/vs/platform/files/node/watcher/parcel/parcelWatcher.ts#L203) to unwatch some directory, these might can decrease unless watch.

**Comment by SethDusek** [comment] 2024-05-29 13:20
> @SethDusek (or anyone else who is newly experiencing this issue after #12266) can you share any details about the repository that you're working in? Is there an open source repository in which this reproduces reliably?

Hi, I can reproduce this on [sigma-rust](https://github.com/ergoplatform/sigma-rust). Here are worktree logs when saving (or anything else that freezes Zed): https://gist.github.com/SethDusek/027fbfeac916acf5fe4b6997d13905b2.


Also FWIW I can completely freeze Zed for around a minute if I cargo clean in the above repository and then type something in causing the LSP to start building from scratch during which time I get lots of events from the target directory. This might help you in reproducing it.

**Comment by maxbrunsfeld** [comment] 2024-05-29 15:47
Thanks everyone for following up with more info.

**Comment by SethDusek** [comment] 2024-05-29 16:56
> Does this branch improve things for you? #12436

Yup, definitely. Stuttering on save/other actions that were previously problematic seems to be completely gone. Thank you!

**Comment by maxbrunsfeld** [comment] 2024-05-29 17:03
Ok great, that is going out in the preview release today. Thanks so much for the follow-up.

**Comment by maxbrunsfeld** [comment] 2024-05-29 17:03
I'm going to optimistically close this out, but we can reopen if other folks are still seeing the problem.

**Closed by maxbrunsfeld** 2024-05-29 17:03 UTC
Labels: defect, needs info / awaiting response, workspace, editor, freeze, large projects
