### ISSUE TITLE
Git global ignore not work

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#11916] opened 2024-05-16 14:42 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`~/.gitconfig`

```
[core]
	excludesfile = /Users/d1y/.gitignore
```

`~/.gitignore`

```gitignore
.DS_Store
bun.lockb

audit.json
```

Look `audio.json` not is ignore theme(ghost)

<img width="201" alt="image" src="https://github.com/zed-industries/zed/assets/45585937/81bf5485-2749-466a-aa1b-a405184c367f">

### Environment

Zed: v0.137.0 (Zed Dev fa67428c5371785811f7a5d9b613e234facaafa5)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

**Comment by SomeoneToIgnore** [comment] 2024-05-16 15:14
Duplicate of https://github.com/zed-industries/zed/issues/4824

**Closed by SomeoneToIgnore** 2024-05-16 15:14 UTC
Labels: defect, git
