### ISSUE TITLE
nixos: github login; Error:authentication failed

### ISSUE THREAD

**Issue by lalishansh** [zed-industries/zed#14028] opened 2024-07-09 21:03 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Create a minimal OS instance (NixOS in my case) with just the window compositor (DWL in my case).
2. launch zed and click `Sign in` at top right corner
3. see `Error: Authentication failed`

```log
[2024-07-00T02:00:00+00:00 ERROR gpui::platform::linux::platform] failed to open uri: "https://zed.dev/native_app_signin?native_app_port=35907&native_app_public_key=XXXXXXXX-L_XXXXXXXX-XXXXXXXX_XXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=", last error: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

### Environment

```fastfetch
ilal@NixOS-Laptop
-----------------
OS: NixOS 24.11.20240705.4284c2b (Vicuna) x86_64
Host: OMEN Laptop 15-en1xxx
Kernel: Linux 6.6.36
Uptime: 2 hours, 14 mins
Packages: 872 (nix-system)
Shell: bash 5.2.26
Display (LGD05FE): 1920x1080 @ 144Hz (as 960x540) [Built-in]
Display (MSI3DB6): 3440x1440 @ 50Hz [External]
WM: dwl (Wayland)
Terminal: foot 1.17.2
Terminal Font: monospace (8pt)
CPU: AMD Ryzen 7 5800H (16) @ 4.46 GHz
GPU 1: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]
GPU 2: AMD Radeon Vega Series / Radeon Vega Mobile Series @ 0.40 GHz [Integrated]
Memory: 2.86 GiB / 14.98 GiB (19%)
Swap: Disabled
Disk (/): 10.17 GiB / 737.16 GiB (1%) - ext4
Local IP (enp6s0f3u1): 192.168.164.192/24 *
Battery: 99% [AC Connected]
Locale: en_IN
```

### If applicable, add mockups / screenshots to help explain present your vision of the feature

A manual authentication method for places where zed fails to locate browser etc. but is connected to internet

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[2024-07-00T02:00:00+00:00 ERROR gpui::platform::linux::platform] failed to open uri: "https://zed.dev/native_app_signin?native_app_port=35907&native_app_public_key=XXXXXXXX-L_XXXXXXXX-XXXXXXXX_XXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=", last error: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" })
</pre></details>

**Comment by lalishansh** [comment] 2024-07-09 21:06
To do a manual authentication
1. run 'zed --foreground'
2. copy the failed to open url ''https://zed.dev/native_app_signin..."
3. paste it in your browser

zed will pick it up from there.

**Comment by HKalbasi** [comment] 2024-07-11 19:59
There is no failed to open url ''https://zed.dev/native_app_signin..." log for me.

**Comment by lalishansh** [comment] 2024-07-11 21:05
> There is no failed to open url ''https://zed.dev/native_app_signin..." log for me.

Is nix able to access internet ?

**Comment by praveen70140** [comment] 2024-07-12 10:34
i am not able to find any log related to failed to open url

**Comment by coder3112** [comment] 2024-07-12 21:08
I am on Arch + XMonad. Same error as described above by @lalishansh including steps of reproduction. The relevant output after running `zen --foreground`` and then clicking on the "Sign in" button is:

```
[2024-07-12T23:03:25+02:00 ERROR client] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
[2024-07-12T23:03:25+02:00 ERROR gpui] Zbus(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 30, body: Signature("s"), fds: [] }))
```

Got a similar output as @joeyjooste , but the message is different. It says: The name is not activatable. I also do NOT get any links in the logs which I can use to sign in.

**Comment by Joel-Ostos** [comment] 2024-07-12 21:17
```
[2024-07-12T16:15:58-05:00 ERROR client] DBus error service error org.freedesktop.zbus.Error: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)
[2024-07-12T16:15:58-05:00 ERROR workspace::notifications] timed out waiting on hello message from server
```

This is what I'm getting when running zed with --foreground flag on Archlinux, with Sway. Zed wast installed through the official repos of Archlinux.

**Comment by Joel-Ostos** [comment] 2024-07-12 21:35
> I am on Arch + XMonad. Same error as described above by @lalishansh including steps of reproduction. The relevant output after running `zen --foreground`` and then clicking on the "Sign in" button is:
> 
> ```
> [2024-07-12T23:03:25+02:00 ERROR client] DBus error service error org.freedesktop.zbus.Error: The name is not activatable
> [2024-07-12T23:03:25+02:00 ERROR gpui] Zbus(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 30, body: Signature("s"), fds: [] }))
> ```
> 
> Got a similar output as @joeyjooste , but the message is different. It says: The name is not activatable. I also do NOT get any links in the logs which I can use to sign in.

HI, I had the same problem on archlinux, the `gnome-keyring-daemon -r -d` did the magic, once the keyring restarted and entered in Zed all the git/authentication related things worked

**Comment by coder3112** [comment] 2024-07-13 08:48
> HI, I had the same problem on archlinux, the `gnome-keyring-daemon -r -d` did the magic, once the keyring restarted and entered in Zed all the git/authentication related things worked

I am not running gnome, and don't think I have any keyrings otherwise installed. Also, what did you mean by "entered in Zed"? Do we need to manually add Zed to the keyring?

**Comment by joeyjooste** [comment] 2024-07-13 11:35
I ran ```gnome-keyring-daemon -r -d``` 
Then when opening zed, gnome keyring opens and prompts me for a login password for zed. (this seems to be a keyring specific thing not the actual zed login) then after entering a password it goes away and zed behaves the same as before. Where it gives an error when clicking the Sign-In button.

![image](https://github.com/user-attachments/assets/96bbf1ff-b6c9-476c-a50d-8f4e952fcc21)

**Comment by coder3112** [comment] 2024-07-13 15:23
> I ran `gnome-keyring-daemon -r -d` Then when opening zed, gnome keyring opens and prompts me for a login password for zed. (this seems to be a keyring specific thing not the actual zed login) then after entering a password it goes away and zed behaves the same as before. Where it gives an error when clicking the Sign-In button.
> 
> ![image](https://private-user-images.githubusercontent.com/72280325/348468941-96bbf1ff-b6c9-476c-a50d-8f4e952fcc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4ODQ0NzIsIm5iZiI6MTcyMDg4NDE3MiwicGF0aCI6Ii83MjI4MDMyNS8zNDg0Njg5NDEtOTZiYmYxZmYtYjZjOS00NzZjLWE1MGQtOGY0ZTk1MmZjYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDE1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTk3ZTcyM2JlY2I0ZWYwMGIwMmU5NjRkNzNmZmRkMTA0MTZjMTY4ZmY3OTMzYmIyNzE0NmJkZWE5NzA2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6pv6LrviCz8JPu2lyjfHkvKNC1Vn3tMIY2k11AvJDk)

I have also received this error on several occasions, but I am not sure what the steps to reproduce in my case are. Simply opening the app does not do it for me. I cannot reproduce it consistently, but click the buttons and close it enough times, and I do get it.

**Comment by lalishansh** [comment] 2024-07-14 00:04
I am able to resolve the issue with switching to gnome-keyring for secrets and encryption. `gnome-keyring-daemon -r -d` is required after login (for my setup) because this service depends on graphical-session-pre.target and graphical-session.target.
And for my minimal set it doesn't launch. (Using greetd-tuigreet, dwl  (to keep user session WM separate, will do somthing about it)) 

I was also getting extension error not being able to execute. Fixed it with nix-ld as just like flatpaks, nix packages are sandboxed but need FHS compliance, so instead we make necessary deps available.

[Current tree for my dotfiles](https://github.com/lalishansh/Nix-Dotfiles/tree/bc1a5d610a9ff710e10c042326cb2b198f60cb37)

**Comment by coder3112** [comment] 2024-07-14 10:11
> I am able to resolve the issue with switching to gnome-keyring (😑) for secrets and encryption. `gnome-keyring-daemon -r -d` is required after login (for my setup) because this service depends on graphical-session-pre.target and graphical-session.target. And for my minimal set it doesn't launch. (Using greetd-tuigreet, dwl (to keep user session WM separate, will do somthing about it))
> 
> I was also getting extension error not being able to execute. Fixed it with nix-ld as just like flatpaks, nix packages are sandboxed but need FHS compliance, so instead we make necessary deps available. Src https://nixos.wiki/wiki/Jetbrains_Tools
> 
> [Current tree for my dotfiles](https://github.com/lalishansh/Nix-Dotfiles/tree/bc1a5d610a9ff710e10c042326cb2b198f60cb37)

After installing gnome-keyring and running the command, did you do anything special for Zed?

**Comment by coder3112** [comment] 2024-07-14 20:46
Essentially, after doing the gnome-keyring/dbus config, Zed sign in prompts me to create a new keychain, and I enter the password and press continue. But then, I again get the error:
```
[2024-07-14T22:44:26+02:00 ERROR gpui] Zbus(MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 40, body: Signature("s"), fds: [] }))
```

**Comment by coder3112** [comment] 2024-07-15 05:06
Fix was installing GTK properly and then using gnome-keyring. Apparently my GTK paths were broken.

**Comment by danielpizarrotadres** [comment] 2024-07-16 02:03
> Fix was installing GTK properly and then using gnome-keyring. Apparently my GTK paths were broken.

How did you fix the issue ?  I ran `gnome-keyring-daemon -r -d` but nothing happens

**Comment by lalishansh** [comment] 2024-07-16 12:04
> > Fix was installing GTK properly and then using gnome-keyring. Apparently my GTK paths were broken.
> 
> How did you fix the issue ? I ran `gnome-keyring-daemon -r -d` but nothing happens

what did it told you ??

**Comment by coder3112** [comment] 2024-07-17 15:29
> > Fix was installing GTK properly and then using gnome-keyring. Apparently my GTK paths were broken.
> 
> How did you fix the issue ? I ran `gnome-keyring-daemon -r -d` but nothing happens

1. (Re)Install xdg-desktop-portal-impl and xdg-desktop-portal. (or equivalent on your distro)
2. The file /usr/share/xdg-desktop-portal/portals/gnome-keyring.portal should be:
```
[portal]
DBusName=org.freedesktop.secrets
Interfaces=org.freedesktop.impl.portal.Secret
UseIn=gnome;gtk;
```
3. Run the commands:
	1. `dbus-update-activation-environment --all`
	2. `dbus-update-activation-environment DISPLAY XAUTHORITY`
	3. `gnome-keyring-daemon -r -d`

I do not know which of these was the actual fix, or whether all of them were needed. But, running all of them did work...

**Comment by notpeter** [comment] 2024-08-22 14:53
@lalishansh Please follow the instructions provided by community members to fix your installation.  If you are still having issues, comment and I'll reopen.  Thanks.

**Closed by notpeter** 2024-08-22 14:53 UTC
Labels: defect, collaboration, linux

**Comment by peonynopes** [comment] 2026-07-03 15:54
So, I have a very similar environment to the original author, except my log looks like this:
```
INFO  [client] set status on client 0: Authenticating
```
and that's it, it doesn't throw any errors or does anything besides authenticate forever, despite me being connected to the internet.

Not even a timeout or anything.

It seems I was using an awfully out-of-date version of Zed, however the issue still persists on 1.9.0.
