### ISSUE TITLE
pages of references  are repetitive

### ISSUE THREAD

**Issue by bestgopher** [zed-industries/zed#15668] opened 2024-08-02 06:08 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

![image](https://github.com/user-attachments/assets/accc81c1-3f92-409e-b4da-dda81f4d0bae)

### Environment

macos; m1

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment] 2024-08-02 17:16
Hey @bestgopher, can you give me more details about what happened here? Did you get 2 reference tabs when running one `find all references` action? Or did you run that action twice and just get a duplicate tab? The second one is expected, as we don't try to detect if any changes happened since it was last ran to know if we can simply use the original references tab.

**Comment by bestgopher** [comment] 2024-08-03 05:19
> Or did you run that action twice and just get a duplicate tab

Maybe we can delete last one and open a newest tab? Now there are to many duplicate tab and I must delete they manually.

**Comment by zeux** [comment] 2024-09-05 06:01
This can be fixed via config:

```
	"preview_tabs": {
		"enable_preview_from_code_navigation": true
	}
}
```

(I think this should be the default but at least there's an option)

**Comment by bestgopher** [comment] 2024-09-05 07:01
> This can be fixed via config:
> 
> ```json
> 	"preview_tabs": {
> 		"enable_preview_from_code_navigation": true
> 	}
> ```
> 
> (I think this should be the default but at least there's an option)

I believe the issue is that when enable_preview_from_code_navigation is set to false, the referenced page repeats.

**Comment by notpeter** [comment] 2024-11-26 19:49
I think the underlying issue is that "Find All References" is very slow so that it is possible to trigger the same thing multiple times.

Closing as a duplicate of:
- https://github.com/zed-industries/zed/issues/12422

**Closed by notpeter** 2024-11-26 19:49 UTC
Labels: bug, needs info / awaiting response, language, tabs, language server
