### ISSUE TITLE
Cannot remap editor::ConfirmCompletion from "tab" to another keystroke to insert Copilot suggestions

### ISSUE THREAD

**Issue by wufe** [zed-industries/zed#8712] opened 2024-03-02 14:43 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Might be related to #8707

Since "tab" is performing both tabs insertion and confirmation of copilot suggestions, I wanted to differentiate between the two operations.

To add a tab I provided this binding:

```
{
        "bindings": {
            "tab": ["workspace::SendKeystrokes", "\t"]
        }
    }
```

To confirm the copilot completion I tried all the following bindings (trying both `ctrl-cmd-k` and `ctrl-cmd-tab`), but none of them is working:

```
{
        "context": "Editor && mode == full",
        "bindings": {
            "alt-\\": null,
            "ctrl-cmd-s": "copilot::Suggest",
            "ctrl-cmd-n": "copilot::NextSuggestion",
            "ctrl-cmd-p": "copilot::PreviousSuggestion",
            "ctrl-cmd-tab": "editor::ConfirmCompletion",
            "ctrl-cmd-k": "editor::ConfirmCompletion"
        }
    },
    {
        "context": "Editor && showing_completions",
        "bindings": {
            "ctrl-cmd-tab": "editor::ConfirmCompletion",
            "ctrl-cmd-k": "editor::ConfirmCompletion"
        }
    },
    {
        "context": "Editor && copilot_suggestion",
        "bindings": {
            "ctrl-cmd-tab": "editor::ConfirmCompletion",
            "ctrl-cmd-k": "editor::ConfirmCompletion"
        }
    },
    {
        "bindings": {
            "tab": ["workspace::SendKeystrokes", "\t"],
            "ctrl-cmd-tab": "editor::ConfirmCompletion",
            "ctrl-cmd-k": "editor::ConfirmCompletion"
        }
    }
```

So it seems like the `editor::ConfirmCompletion` is not the right action, because `ctrl-cmd-n` and `ctrl-cmd-p` are working fine

### Environment

Zed: v0.124.8 (Zed)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2024-03-02 at 15 42 21](https://github.com/zed-industries/zed/assets/7671694/e2d5a99c-2d7d-4ba3-b925-9599c6e4fe65)

Trying to hit `ctrl-cmd-k` or `ctrl-cmd-tab` does not insert the suggested snippet from copilot

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Moshyfawn** [comment] 2024-03-02 17:10
The other question is about the autocomplete confirmation for the copilot, so let's close this one in favour of the other one. Be sure to +👍 it and add any additional information that might be missing.

**Comment by Moshyfawn** [comment] 2024-03-02 17:10
Duplicate of #8707

**Closed by Moshyfawn** 2024-03-02 17:10 UTC
Labels: defect, triage, admin read
