### ISSUE TITLE
wrap_guides are only working on markdown files

### ISSUE THREAD

**Issue by rauann** [zed-industries/zed#8392] opened 2024-02-25 15:56 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Even setting up the `show_wrap_guides` and `wrap_guides` globally, Zed only shows guides on Markdown files and does not allow to disable them.

### Environment

Zed: v0.123.6 (Zed)
OS: macOS 14.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Settings.json
```json
{
  "soft_wrap": "editor_width",
  "show_wrap_guides": true,
  "wrap_guides": [80],
  "languages": {
    "Markdown": {
      "soft_wrap": "none",
      "show_wrap_guides": false
    },
    "Elixir": {
      "tab_size": 2,
      "soft_wrap": "editor_width",
      "show_wrap_guides": true,
      "wrap_guides": [80, 120]
    },
    "YAML": {
      "tab_size": 2,
      "show_wrap_guides": true,
      "soft_wrap": "preferred_line_length"
    }
  },
  "preferred_line_length": 80,
}
```

Markdown and Elixir files:
![image](https://github.com/zed-industries/zed/assets/14976415/4f23512c-52d4-4faf-8b4b-477115e6e539)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-27 19:05
Huh, this is a strange one that I'm not able to reproduce, even with pasting your settings over mine. 🤔

**Comment by JosephTLyons** [comment] 2024-02-27 19:06
What happens if you change your theme?

**Comment by rauann** [comment] 2024-02-27 22:06
@JosephTLyons I have the same behavior with all themes:

https://github.com/zed-industries/zed/assets/14976415/5d1181fc-a584-44cb-b830-eb27c9a24c5c

Also, I reinstalled Zed and the issue is the same 😞

**Comment by rauann** [comment] 2024-03-01 12:04
@JosephTLyons I noticed that the whitespaces config is not working as well (same behaviour with other themes):
![image](https://github.com/zed-industries/zed/assets/14976415/3a8083c1-0838-41c0-b824-5fbd7f7d6217)

This is the entire settings that I am using:
```json
{
  "preferred_line_length": 80,
  "soft_wrap": "editor_width",
  "show_wrap_guides": true,
  "wrap_guides": [80, 120],
  "languages": {
    "Markdown": {
      "soft_wrap": "none",
      "show_wrap_guides": false
    },
    "Elixir": {
      "tab_size": 2,
      "soft_wrap": "editor_width",
      "show_wrap_guides": true,
      "wrap_guides": [80, 120]
    },
    "Rust": {
      "tab_size": 2,
      "show_wrap_guides": true
    },
    "YAML": {
      "tab_size": 2,
      "show_wrap_guides": true,
      "soft_wrap": "preferred_line_length"
    }
  },
  "theme": "macOS Classic Dark",
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "toolbar": {
    "breadcrumbs": false,
    "quick_actions": false
  },
  "project_panel": {
    "default_width": 350,
    "indent_size": 10
  },
  "auto_update": true,
  "confirm_quit": true,
  "ui_font_size": 14,
  "ui_font_features": {
    "calt": true
  },
  "assistant": {
    "default_width": 540
  },
  "features": {
    "copilot": true
  },
  "show_copilot_suggestions": true,
  "show_whitespaces": "all",
  "vim_mode": true,
  "relative_line_numbers": true,
  "base_kewymap": "VSCode",
  "buffer_font_size": 14,
  "buffer_font_family": "Iosevka Term",
  "buffer_line_height": "comfortable",
  "buffer_font_features": {
    "calt": true
  },
  "ui_font_family": "Iosevka Term",
  "autosave": "off",
  "format_on_save": "on",
  "ensure_final_newline_on_save": true,
  "scrollbar": {
    "show": "never"
  },
  "tab_size": 2,
  "tabs": {
    "git_status": true
  },
  "git_status": true,
  "git": {
    "git_gutter": "tracked_files"
  },
  "remove_trailing_whitespace_on_save": true,
  "terminal": {
    "font_size": 14,
    "font_family": "Iosevka Term",
    "font_features": {
      "calt": true
    },
    "blinking": "on"
  },
  "show_completions_on_input": true,
  "enable_language_server": true,
  "elixir": {
    "lsp": "elixir_ls"
  },
  "language_overrides": {
    "Elixir": {
      "format_on_save": {
        "external": {
          "command": "mix",
          "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
        }
      }
    }
  }
}
```

**Comment by JosephTLyons** [comment] 2024-03-04 23:11
> @JosephTLyons I noticed that the whitespaces config is not working as well (same behaviour with other themes): ![image](https://private-user-images.githubusercontent.com/14976415/309253195-3a8083c1-0838-41c0-b824-5fbd7f7d6217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1OTMwNDYsIm5iZiI6MTcwOTU5Mjc0NiwicGF0aCI6Ii8xNDk3NjQxNS8zMDkyNTMxOTUtM2E4MDgzYzEtMDgzOC00MWMwLWI4MjQtNWZiZDdmN2Q2MjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDIyNTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDE1ZTIwMzY4OGRkNWVlZGIyYTg1NWYyMmM4NTQ5OTI3MWZkM2ZiYWFmZmMzYzQ5ZGE1ZTUyYzJkYmRmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qeC3FMJFxPGrLtHlUiGMNYFruj70cE_3lAwTr8LZai0)
> 
> This is the entire settings that I am using:
> 
> ```json
> {
>   "preferred_line_length": 80,
>   "soft_wrap": "editor_width",
>   "show_wrap_guides": true,
>   "wrap_guides": [80, 120],
>   "languages": {
>     "Markdown": {
>       "soft_wrap": "none",
>       "show_wrap_guides": false
>     },
>     "Elixir": {
>       "tab_size": 2,
>       "soft_wrap": "editor_width",
>       "show_wrap_guides": true,
>       "wrap_guides": [80, 120]
>     },
>     "Rust": {
>       "tab_size": 2,
>       "show_wrap_guides": true
>     },
>     "YAML": {
>       "tab_size": 2,
>       "show_wrap_guides": true,
>       "soft_wrap": "preferred_line_length"
>     }
>   },
>   "theme": "macOS Classic Dark",
>   "telemetry": {
>     "diagnostics": false,
>     "metrics": false
>   },
>   "toolbar": {
>     "breadcrumbs": false,
>     "quick_actions": false
>   },
>   "project_panel": {
>     "default_width": 350,
>     "indent_size": 10
>   },
>   "auto_update": true,
>   "confirm_quit": true,
>   "ui_font_size": 14,
>   "ui_font_features": {
>     "calt": true
>   },
>   "assistant": {
>     "default_width": 540
>   },
>   "features": {
>     "copilot": true
>   },
>   "show_copilot_suggestions": true,
>   "show_whitespaces": "all",
>   "vim_mode": true,
>   "relative_line_numbers": true,
>   "base_kewymap": "VSCode",
>   "buffer_font_size": 14,
>   "buffer_font_family": "Iosevka Term",
>   "buffer_line_height": "comfortable",
>   "buffer_font_features": {
>     "calt": true
>   },
>   "ui_font_family": "Iosevka Term",
>   "autosave": "off",
>   "format_on_save": "on",
>   "ensure_final_newline_on_save": true,
>   "scrollbar": {
>     "show": "never"
>   },
>   "tab_size": 2,
>   "tabs": {
>     "git_status": true
>   },
>   "git_status": true,
>   "git": {
>     "git_gutter": "tracked_files"
>   },
>   "remove_trailing_whitespace_on_save": true,
>   "terminal": {
>     "font_size": 14,
>     "font_family": "Iosevka Term",
>     "font_features": {
>       "calt": true
>     },
>     "blinking": "on"
>   },
>   "show_completions_on_input": true,
>   "enable_language_server": true,
>   "elixir": {
>     "lsp": "elixir_ls"
>   },
>   "language_overrides": {
>     "Elixir": {
>       "format_on_save": {
>         "external": {
>           "command": "mix",
>           "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
>         }
>       }
>     }
>   }
> }
> ```

Hey @rauann, for some reason, this section

```json
"language_overrides": {
    "Elixir": {
      "format_on_save": {
        "external": {
          "command": "mix",
          "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
        }
      }
    }
  }
```

is causing the issue - I'm not sure why yet. Removing that section brings the wrap guides back. That's not a fix though - still a bug here.

That being said, I think your settings can be simplified a bit. In the command palette, if you look for `zed: open default settings` and check out what we have set by default, you could remove any of your custom settings that we already set to the same value by default.

Another confusing this is that we have both `languages` and `language_overrides`, and I think these both override the same internal thing, so I *think* you can combine these sections.

I'll get back on the markdown.

I might've missed something here, but here's a rough idea of how much reduction could be done:

```json
{
  "soft_wrap": "editor_width",
  "wrap_guides": [80, 120],
  "theme": "macOS Classic Dark",
  "telemetry": {
    "diagnostics": false,
    "metrics": false
  },
  "toolbar": {
    "breadcrumbs": false,
    "quick_actions": false
  },
  "project_panel": {
    "default_width": 350,
    "indent_size": 10
  },
  "confirm_quit": true,
  "ui_font_size": 14,
  "ui_font_features": {
    "calt": true
  },
  "show_whitespaces": "all",
  "vim_mode": true,
  "relative_line_numbers": true,
  "buffer_font_size": 14,
  "buffer_font_family": "Iosevka Term",
  "buffer_font_features": {
    "calt": true
  },
  "ui_font_family": "Iosevka Term",
  "scrollbar": {
    "show": "never"
  },
  "tab_size": 2,
  "tabs": {
    "git_status": true
  },
  "terminal": {
    "font_size": 14,
    "font_family": "Iosevka Term",
    "font_features": {
      "calt": true
    },
    "blinking": "on"
  },
  "language_overrides": {
    "Markdown": {
      "soft_wrap": "none",
      "show_wrap_guides": false
    },
    "Elixir": {
      "tab_size": 2,
      "format_on_save": {
        "external": {
          "command": "mix",
          "arguments": ["format", "--stdin-filename", "{buffer_path}", "-"]
        }
      }
    },
    "Rust": {
      "tab_size": 2
    },
    "YAML": {
      "soft_wrap": "preferred_line_length"
    }
  }
}
```

**Comment by rauann** [comment] 2024-03-06 14:08
Thanks a lot @JosephTLyons! I will apply your suggestions 👍🏽.

**Comment by notpeter** [comment] 2024-08-01 21:03
I'm going to close this as I believe it has been fixed. Thanks!

**Closed by notpeter** 2024-08-01 21:03 UTC
Labels: defect, editor, setting
