### ISSUE TITLE
Selected theme not being saved for follow up ZED execution/re-launch

### ISSUE THREAD

**Issue by krstp** [zed-industries/zed#4714] opened 2023-06-02 17:28 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Latest release with other bug fixed does not preserve last selected theme returning back to default setup.

### Environment

Zed: v0.88.6 (stable)
OS: macOS 13.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

- Launch ZED
- Select custom/diff theme
- Quit ZED
- Relaunch ZED
- Theme will return to default not to the selected theme

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by oliverjohns** [comment] 2024-05-15 06:41
I have similar issue:
1. I switch theme
2. It works for a couple of seconds, then it reverts back to the old theme
3. Inspecting the settings.json files shows the **new** theme, but it is not being respected by the application.

**Comment by KMJ-007** [comment] 2024-06-06 05:52
facing same issue

**Comment by KMJ-007** [comment] 2024-06-06 05:52
after debugging little

it is changing the workspace theme but not the default theme

**Comment by notpeter** [comment] 2024-07-03 14:49
I believe this is caused by:
- https://github.com/zed-industries/zed/issues/12389

If you have an error in your settings.json we don't immediately revert to the default settings, we leave your last working settings in place.  When Zed is reopened we revert to default because don't keep a cached copy of the last good.  Closing here in favor of that issue. Please 👍 and subscribe to track that issue.

**Closed by notpeter** 2024-07-03 14:49 UTC
Labels: defect, theme, setting
