### ISSUE TITLE
Not Detecting .py files in the Same Folder

### ISSUE THREAD

**Issue by Swaymaw** [zed-industries/zed#9562] opened 2024-03-20 05:29 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed is unable to detect the utils.py file that is in the same folder as lr_grad_desc.py and when I am trying to import the file functions in the lr_grad_desc file it highlight the import as an error that no module found. However the code works fine without any errors. This also restricts the code completion capabilities as it is unable to detect the file contents  of utils.py which reduced the coding productivity. 

<img width="613" alt="Screenshot 2024-03-20 at 10 53 04 AM" src="https://github.com/zed-industries/zed/assets/87603098/cc1dfafb-9327-4593-8eae-3d5dd8d43b9a">

### Environment

Zed: v0.126.3 (Zed)
OS: macOS 14.3.1
Memory: 8 GiB
Architecture: aarch64

**Comment by Moshyfawn** [comment] 2024-03-20 05:38
Does #8541 look like the problem you're experiencing, @Swaymaw?

**Comment by Swaymaw** [comment] 2024-03-21 02:42
Yeah, that is the same issue I am facing. Sorry, I missed that.

**Comment by Moshyfawn** [comment] 2024-03-21 03:18
No problem and thank you!

I'm going to close this issue in favour of the other one. Be sure to +👍 the other issue and add any missing information.

Duplicate of
- #8541

**Closed by Moshyfawn** 2024-03-21 03:18 UTC
Labels: defect, needs info / awaiting response, python, language, admin read, language server
