### ISSUE TITLE
Cannot open Windows registry files on macOS 

### ISSUE THREAD

**Issue by showier-drastic** [zed-industries/zed#17225] opened 2024-09-01 06:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Inside this file.zip, there're two files, one named `1.reg` and another named `strange.txt`. Both of them are Windows registry export files. When I drag them to Zed editor on mac (or use File -> Open to open them), nothing happens.

[file.zip](https://github.com/user-attachments/files/16827739/file.zip)

### Environment

Zed: v0.149.6 (Zed)
OS: macOS 14.6.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-09-01T06:54:00.358256Z [INFO] ========== starting zed ==========
2024-09-01T06:54:00.359426Z [INFO] Opening main db
2024-09-01T06:54:00.363178Z [INFO] Using git binary path: Some("/Applications/Zed.app/Contents/MacOS/git")
2024-09-01T06:54:00.380985Z [INFO] set environment variables from shell:/bin/zsh, path:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/user/.cargo/bin:/opt/homebrew/bin
2024-09-01T06:54:00.526061Z [INFO] initializing context server client
2024-09-01T06:54:00.526178Z [INFO] Registering built-in prompt template: content_prompt
2024-09-01T06:54:00.526414Z [INFO] Registering built-in prompt template: edit_workflow
2024-09-01T06:54:00.526629Z [INFO] Registering built-in prompt template: step_resolution
2024-09-01T06:54:00.527027Z [INFO] Registering built-in prompt template: terminal_assistant_prompt
2024-09-01T06:54:00.527236Z [INFO] No prompt template overrides directory found at /Users/user/.config/zed/prompt_overrides. Using built-in prompts.
2024-09-01T06:54:00.527751Z [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-09-01T06:54:00.528671Z [INFO] performance metrics display disabled
2024-09-01T06:54:00.57Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.570092Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.570181Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.57024Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.570451Z [INFO] Opening main db
2024-09-01T06:54:00.570634Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.5707Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.570757Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.57082Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.570889Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.572178Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.620642Z [INFO] time to first window draw: 262.723542ms
2024-09-01T06:54:00.621186Z [INFO] Opening main db
2024-09-01T06:54:00.621276Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.621465Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.621528Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.621585Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.640071Z [INFO] Initializing default prettier with plugins {}
2024-09-01T06:54:00.64248Z [INFO] Initializing default prettier with plugins {}
2024-09-01T06:54:00.643016Z [INFO] Opening main db
2024-09-01T06:54:00.643168Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.643261Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.643346Z [ERROR] no worktrees when constructing ProjectLspAdapterDelegate
2024-09-01T06:54:00.659179Z [INFO] Initializing default prettier with plugins {}
2024-09-01T06:54:00.661441Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.684385Z [INFO] Initializing default prettier with plugins {}
2024-09-01T06:54:00.685159Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:00.69691Z [INFO] Initializing default prettier with plugins {}
2024-09-01T06:54:00.698589Z [WARN] request completed with error: failed to connect to the server
2024-09-01T06:54:01.50358Z [INFO] Node runtime install_if_needed
2024-09-01T06:54:01.641095Z [INFO] starting language server. binary path: "/Users/user/Library/Application Support/Zed/node/node-v22.5.1-darwin-arm64/bin/node", working directory: "/", args: ["/Users/user/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-09-01T06:54:01.880309Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-01T06:54:01.872Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-09-01T06:54:01.872Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-09-01T06:54:01.88041Z [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "dcb29672-51d0-4ba4-b262-c82513657dcf",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-09-01T06:54:01.907272Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-09-01T06:54:01.883Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-09-01T06:54:01.883Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-09-01T06:54:06.184531Z [INFO] open paths ["/Users/user/strange.txt"]
2024-09-01T06:54:10.412917Z [INFO] open paths ["/Users/user/1.reg"]
</pre></details>

**Comment by notpeter** [comment] 2024-09-01 19:04
We only currently support UTF-8 text files.  For more info, see:
- https://github.com/zed-industries/zed/issues/16965

I was able to see this by running `file -I 1.reg` which reported `text/x-ms-regedit; charset=utf-16le`

The lack of an error message is a duplicate of:
- https://github.com/zed-industries/zed/issues/5348

Which is fixed in Zed Preview today and will be available in the next Zed Stable (out on Wednesday). Thanks for reporting.

**Closed by notpeter** 2024-09-01 19:04 UTC
Labels: defect, triage, admin read
