### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by gsk-gits** [zed-industries/zed#7463] opened 2024-02-06 21:18 UTC
### Check for existing issues

- [ ] Completed

### Language

cmake

### Tree Sitter parser link

https://github.com/uyha/tree-sitter-cmake

### Language server link

https://github.com/regen100/cmake-language-server

**Comment by JosephTLyons** [comment] 2024-02-06 22:07
Hey @gsk-gits,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/5102

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-06 22:07 UTC
Labels: enhancement, triage, potential plugin, language, unsupported language, admin read

**Comment by jansol** [comment] 2024-03-07 16:14
Alternative LSP, seems to be more actively developed: https://github.com/Decodetalkers/neocmakelsp
