### ISSUE TITLE
jsonc formatter adds trailing commas and triggers warnings

### ISSUE THREAD

**Issue by matthewmueller** [zed-industries/zed#21303] opened 2024-11-28 20:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Create a jsonc file like, e.g. `config.jsonc`

```jsonc
// This is a dot schema file. It defines the server configuration for your project.
// For more information, visit https://dot.io/docs/schema
{
  // Application name
  "name": "", // e.g., "my-app"
  // Domains for the app (leave empty for local development)
  // Example: ["example.com", "api.example.com"]
  "domains": [],
  // Host servers to deploy to
  "hosts": {
    "main": {
      "host": "localhost:2222",
      "admin": "ubuntu",
      "user": "dot"
    }
  },
}
```

Then hit save, the formatter will append trailing commas, leading to warnings.

### Environment

Zed: v0.162.5 (Zed)
OS: macOS 14.6.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Quick video:

https://github.com/user-attachments/assets/b49eb435-00f3-43c0-a8bf-62b33c52d90c

I'd expect the formatter to not generate trailing commas. This also matches what VSCode does.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```

```
</details>

**Comment by notpeter** [comment] 2024-12-03 20:51
This is an upstream prettier issue:
- https://github.com/prettier/prettier/issues/15956

Duplicate of:
- https://github.com/zed-industries/zed/issues/17487

Explicitly called out in the [Zed JSON Language Docs](https://zed.dev/docs/languages/json#jsonc-prettier-formatting).

**Closed by notpeter** 2024-12-03 20:51 UTC
Labels: duplicate
