### ISSUE TITLE
Flatpak Version of Zed

### ISSUE THREAD

**Issue by ntua-el19019** [zed-industries/zed#11594] opened 2024-05-09 05:59 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Can one make a flatpak build of Zed and maintain it accordingly? Are there any requirements from you guys or licensing/legal problems of distributing a flatpak version of Zed? I would love to be involved in a flatpak distribution.

**Comment by someone13574** [comment] 2024-05-09 11:11
Duplicate of #6687

**Closed** 2024-05-09 16:13 UTC
Labels: enhancement, triage, admin read
