### ISSUE TITLE
Failing to install `zls`

### ISSUE THREAD

**Issue by willus10245** [zed-industries/zed#11493] opened 2024-05-07 15:05 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I installed the Zig extension, but when I am using it, I get no language server features. The logs show that it is failing to install zls. 

This appears to be because it's looking for a `.gz` extension, but the releases on the `zls` repo have `.xz` extensions.

### Environment

Zed: v0.133.7 (Zed)
OS: macOS 14.3.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

`2024-05-07T10:43:17-04:00 [ERROR] failed to start language server "zls": no asset found matching "zls-aarch64-macos.tar.gz"`

**Comment by maxdeviant** [comment] 2024-05-08 14:35
This looks like a dupe of https://github.com/zed-industries/zed/issues/11162.

**Closed** 2024-05-08 17:11 UTC
Labels: defect, language, admin read, zig, extension infrastructure
