### ISSUE TITLE
User menu icon jumps and flashes

### ISSUE THREAD

**Issue by d1y** [zed-industries/zed#8457] opened 2024-02-27 01:34 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It flashes after opening it, and it will be fine after a while. Then trigger inlay-hint and start flashing again.

https://github.com/zed-industries/zed/assets/45585937/7c2ea172-a220-4fb4-bf33-45842f356f12

### Environment

Zed: v0.124.6 (Zed Preview)
OS: macOS 14.3.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment] 2024-02-27 18:41
I think this is likely a duplicate of:

- https://github.com/zed-industries/zed/issues/8050

So I will close this out for now. If it feels different, ping me and I will reopen.

**Closed by JosephTLyons** 2024-02-27 18:41 UTC
Labels: defect, workspace
