### ISSUE TITLE
ghost window

### ISSUE THREAD

**Issue by louyo** [zed-industries/zed#14805] opened 2024-07-19 12:06 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Installed via curl in Debian 12.5 virtual machine. Window is a ghost

### Environment

Debian 12.5, virtual machine, up to date. 

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Zed.log](https://github.com/user-attachments/files/16311634/Zed.log)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by JosephTLyons** [comment] 2024-07-19 19:31
Hey @louyo, is this the same sort of issue you are seeing?

- https://github.com/zed-industries/zed/issues/14204

No worries if not, just trying to deduplicate things if possible.

**Comment by forkinesis** [comment] 2024-07-19 19:47
No, I get a window outline with the desktop (or whateve was on the monitor) filling it. No menu, icons or controls.

**Comment by forkinesis** [comment] 2024-07-19 19:47
Oops, different log on. Sorry.
Louyo

**Comment by RickyWanga** [comment] 2024-07-19 23:34
I have the same issue, I'm getting a transparent window and see that zed is running in the dock, I'm using the latest popOS with gnome, I'm running a ryzen 9 and rtx 4090. The "ghost" window keeps the background of what it had underneath at the moment of launch.

**Comment by louyo** [comment] 2024-07-20 14:09
Retried on a new (VM) install of LMDE6, running Mate desktop, same result, Ghost.
Tried same LMDE6 system with Cinnamon (ugh) on Wayland, experimental, and it runs. 
Must require Wayland on Debian systems? 
I run Debian 12.5 on my workstation, all others are virtual, including a Debian 12.5 VM for testing. No intelligent person would test my programs on a "real" system!
Lou

**Comment by JosephTLyons** [comment] 2024-07-22 17:11
Hey @louyo,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/14648

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-07-22 17:11 UTC
Labels: defect, needs info / awaiting response, workspace, linux
