### ISSUE TITLE
Invalid keys in language-specific settings cause other settings not to be respected

### ISSUE THREAD

**Issue by Huliiiiii** [zed-industries/zed#17551] opened 2024-09-07 23:40 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Maybe cause #5280?

https://github.com/user-attachments/assets/75e7b056-e551-47b8-a325-a9db9800e1aa

### Environment

Zed: v0.153.0 (Zed Dev eecff753fbd5ab7eecc886122cd509cb45a97326)
OS: Windows 10.0.22631
Memory: 31.9 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 || NVIDIA || 556.12

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

</pre></details>

**Comment by Huliiiiii** [comment] 2024-09-19 10:27
1. `code_actions` conflicts with `external`, we can only have one of them at the sametime, otherwise it will breaks some other settings. 
2. Any invalid key-value also will breaks some other settings.

**Comment by notpeter** [comment] 2024-09-19 22:21
Thanks for digging up #5280: I think that and your issue are one and the same. Closing as duplicate of:
- https://github.com/zed-industries/zed/issues/16876
- https://github.com/zed-industries/zed/issues/5280

It's crazy to think that this bug has been quietly lurking for >2years.

**Closed** 2024-09-19 22:22 UTC
Labels: defect, triage, admin read
