### ISSUE TITLE
Multiple User Support

### ISSUE THREAD

**Issue by init-self** [zed-industries/zed#7362] opened 2024-02-04 19:10 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Currently, editor opens for one user on the system. This can be challenging when using the same code editor for multiple users. 

#### Reproduce the issue
(P.S. - I am using Mac OS)
1. Open Zed editor for one user
2. login to another user on the system
3. try to open on the editor. It will not open. Will show an animation of opening application provided from OS but the application will not open.

**Comment by JosephTLyons** [comment] 2024-02-06 20:09
Hey @init-self,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/zed/issues/4607

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Closed by JosephTLyons** 2024-02-06 20:09 UTC
Labels: enhancement, triage, admin read
