### ISSUE TITLE
Golang LSP not showing snippets

### ISSUE THREAD

**Issue by JeetChhatrala** [zed-industries/zed#10436] opened 2024-04-11 17:57 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Did found the issue related, but was asked to open a new issue.

LSP not showing placeHolder snippets. Attaching folder structure, GOPATH, etc.

<img width="743" alt="image" src="https://github.com/zed-industries/zed/assets/75415216/04928595-f796-410f-a9da-11a8249be8da">

### Environment

Using 1.22.2 darwin/arm64 golang
zed version 1.30.5
Macbook Pro 14"
M2 Pro
16GB
1TB

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="743" alt="image" src="https://github.com/zed-industries/zed/assets/75415216/454c174e-2b40-4cd9-aca8-967e821c8477">

snippets for if not showing up.

`2024/04/11 23:10:09 go info for /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
(view type GoWorkView)
(root dir /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend)
(go version go version go1.22.2 darwin/arm64)
(build flags: [])
(go env: {GOOS:darwin GOARCH:arm64 GOCACHE:/Users/jeetchhatrala/Library/Caches/go-build GOMODCACHE:/Users/jeetchhatrala/go/pkg/mod GOPATH:/Users/jeetchhatrala/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.2 darwin/arm64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])
2024/04/11 23:10:13 go/packages.Load #1
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/... builtin]
	packages=9
2024/04/11 23:10:13 go/packages.Load #1: updating metadata for 338 packages
2024/04/11 23:10:13 go info for /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
(view type GoWorkView)
(root dir /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend)
(go version go version go1.22.2 darwin/arm64)
(build flags: [])
(go env: {GOOS:darwin GOARCH:arm64 GOCACHE:/Users/jeetchhatrala/Library/Caches/go-build GOMODCACHE:/Users/jeetchhatrala/go/pkg/mod GOPATH:/Users/jeetchhatrala/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.2 darwin/arm64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])
2024/04/11 23:10:13 go/packages.Load #2
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/... builtin]
	packages=9
2024/04/11 23:10:13 go/packages.Load #2: updating metadata for 338 packages
2024/04/11 23:10:26 go/packages.Load #4
	snapshot=4
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[file=/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/service/service.go]
	packages=1
2024/04/11 23:10:26 go/packages.Load #4
	snapshot=4
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/service"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/service/service.go /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/service/service_gen.go]
2024/04/11 23:10:26 go/packages.Load #4: updating metadata for 1 packages
2024/04/11 23:10:27 go/packages.Load #5
	snapshot=4
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[auth/cmd auth/cmd/service]
	packages=2
2024/04/11 23:10:27 go/packages.Load #5
	snapshot=4
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/cmd/service"
	files=[]
2024/04/11 23:10:27 go/packages.Load #5
	snapshot=4
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/cmd"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
2024/04/11 23:10:27 go/packages.Load #5: updating metadata for 1 packages
2024/04/11 23:10:43 imports fixes: AllImportsFixes: /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go:8:1: expected operand, found '}' (and 5 more errors)
	file="/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go"
2024/04/11 23:10:43 background imports cache refresh starting
2024/04/11 23:10:43 background refresh finished after 5.776166ms
2024/04/11 23:10:46 no completions found: column is beyond end of line
	position=5:3
2024/04/11 23:11:16 background imports cache refresh starting
2024/04/11 23:11:16 background refresh finished after 13.185292ms
2024/04/11 23:11:45 go info for /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
(view type GoWorkView)
(root dir /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend)
(go version go version go1.22.2 darwin/arm64)
(build flags: [])
(go env: {GOOS:darwin GOARCH:arm64 GOCACHE:/Users/jeetchhatrala/Library/Caches/go-build GOMODCACHE:/Users/jeetchhatrala/go/pkg/mod GOPATH:/Users/jeetchhatrala/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.2 darwin/arm64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])
2024/04/11 23:11:45 go/packages.Load #6
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/... builtin]
	packages=9
2024/04/11 23:11:45 go/packages.Load #6: updating metadata for 338 packages
2024/04/11 23:12:04 background imports cache refresh starting
2024/04/11 23:12:04 background refresh finished after 11.870375ms
2024/04/11 23:12:08 go info for /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
(view type GoWorkView)
(root dir /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend)
(go version go version go1.22.2 darwin/arm64)
(build flags: [])
(go env: {GOOS:darwin GOARCH:arm64 GOCACHE:/Users/jeetchhatrala/Library/Caches/go-build GOMODCACHE:/Users/jeetchhatrala/go/pkg/mod GOPATH:/Users/jeetchhatrala/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.2 darwin/arm64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])
2024/04/11 23:12:09 go/packages.Load #7
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/... builtin]
	packages=9
2024/04/11 23:12:09 go/packages.Load #7: updating metadata for 338 packages
2024/04/11 23:12:27 go info for /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
(view type GoWorkView)
(root dir /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend)
(go version go version go1.22.2 darwin/arm64)
(build flags: [])
(go env: {GOOS:darwin GOARCH:arm64 GOCACHE:/Users/jeetchhatrala/Library/Caches/go-build GOMODCACHE:/Users/jeetchhatrala/go/pkg/mod GOPATH:/Users/jeetchhatrala/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.2 darwin/arm64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])
2024/04/11 23:12:27 go/packages.Load #9
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[file=/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/database/db/query.sql.go]
	packages=1
2024/04/11 23:12:27 go/packages.Load #9
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/database/db"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/database/db/db.go /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/database/db/models.go /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/database/db/query.sql.go]
2024/04/11 23:12:27 go/packages.Load #9: updating metadata for 147 packages
2024/04/11 23:12:27 go/packages.Load #8
	snapshot=0
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/... builtin]
	packages=9
2024/04/11 23:12:27 go/packages.Load #8: updating metadata for 191 packages
2024/04/11 23:13:09 background imports cache refresh starting
2024/04/11 23:13:09 background refresh finished after 107.422667ms
2024/04/11 23:13:18 go/packages.Load #10
	snapshot=7
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[file=/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
	packages=1
2024/04/11 23:13:18 go/packages.Load #10
	snapshot=7
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/cmd"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
2024/04/11 23:13:18 go/packages.Load #10: updating metadata for 1 packages
2024/04/11 23:13:18 go/packages.Load #11
	snapshot=7
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[file=/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
	packages=1
2024/04/11 23:13:18 go/packages.Load #11
	snapshot=7
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/cmd"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
2024/04/11 23:13:18 go/packages.Load #11: updating metadata for 0 packages
2024/04/11 23:13:19 go/packages.Load #13
	snapshot=8
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[file=/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
	packages=1
2024/04/11 23:13:19 go/packages.Load #13
	snapshot=8
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/cmd"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
2024/04/11 23:13:19 go/packages.Load #13: updating metadata for 1 packages
2024/04/11 23:13:19 go/packages.Load #14
	snapshot=8
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	query=[file=/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
	packages=1
2024/04/11 23:13:19 go/packages.Load #14
	snapshot=8
	directory=file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend
	package="auth/cmd"
	files=[/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go]
2024/04/11 23:13:19 go/packages.Load #14: updating metadata for 0 packages
2024/04/11 23:13:43 background imports cache refresh starting
2024/04/11 23:13:43 background refresh finished after 9.657459ms
2024/04/11 23:18:41 imports fixes: AllImportsFixes: /Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go:8:1: expected operand, found '}' (and 5 more errors)
	file="/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go"
2024/04/11 23:19:08 background imports cache refresh starting
2024/04/11 23:19:08 background refresh finished after 14.614375ms
2024/04/11 23:19:14 no completions found: column is beyond end of line
	position=5:3
2024/04/11 23:19:15 no completions found: column is beyond end of line
	position=5:3
2024/04/11 23:19:42 background imports cache refresh starting
2024/04/11 23:19:42 background refresh finished after 12.065709ms`

above are the LSP server logs.

Expected output i expect is just like mentioned in #7523 issue.

Please tell me if more information is required

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
2024-04-11T23:10:05+05:30 [INFO] add connection to peer
2024-04-11T23:10:05+05:30 [INFO] waiting for server hello
2024-04-11T23:10:05+05:30 [INFO] got server hello
2024-04-11T23:10:05+05:30 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 387, id: 3812436 })
2024-04-11T23:10:05+05:30 [INFO] set status on client 99746: Connected { peer_id: PeerId { owner_id: 387, id: 3812436 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-04-11T23:10:08+05:30 [INFO] Opening main db
2024-04-11T23:10:08+05:30 [INFO] starting language server "gopls", path: "/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend", id: 1
2024-04-11T23:10:09+05:30 [INFO] found user-installed language server for Go. path: "/Users/jeetchhatrala/go/bin/gopls", arguments: ["-mode=stdio"]
2024-04-11T23:10:09+05:30 [INFO] starting language server. binary path: "/Users/jeetchhatrala/go/bin/gopls", working directory: "/Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend", args: ["-mode=stdio"]
2024-04-11T23:10:31+05:30 [WARN] Generic lsp request to gopls failed: no package data for file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go
2024-04-11T23:10:31+05:30 [ERROR] crates/project/src/project.rs:6699: no package data for file:///Users/jeetchhatrala/Documents/Projects/Goldenbird/kapi-trader/kapi_backend/auth/cmd/main.go
2024-04-11T23:10:36+05:30 [WARN] Generic lsp request to gopls failed: failed to resolve import "auth/cmd/service"
2024-04-11T23:10:36+05:30 [WARN] Generic lsp request to gopls failed: failed to resolve import "auth/cmd/service"
2024-04-11T23:11:18+05:30 [ERROR] unexpected item event after pane was dropped
2024-04-11T23:11:45+05:30 [INFO] open paths ["/Users/jeetchhatrala/.config/zed/settings.json"]
2024-04-11T23:11:45+05:30 [INFO] Initializing default prettier with plugins {}
2024-04-11T23:11:45+05:30 [INFO] starting language server "json-language-server", path: "/Users/jeetchhatrala/.config/zed/settings.json", id: 2
2024-04-11T23:11:45+05:30 [INFO] fetching latest version of language server "json-language-server"
2024-04-11T23:11:45+05:30 [INFO] Node runtime install_if_needed
2024-04-11T23:11:47+05:30 [INFO] downloading language server "json-language-server"
2024-04-11T23:11:47+05:30 [INFO] Node runtime install_if_needed
2024-04-11T23:11:47+05:30 [INFO] starting language server. binary path: "/Users/jeetchhatrala/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/jeetchhatrala/.config/zed", args: ["/Users/jeetchhatrala/Library/Application Support/Zed/languages/json-language-server/node_modules/vscode-json-languageserver/bin/vscode-json-languageserver", "--stdio"]
2024-04-11T23:12:06+05:30 [INFO] installing extension dockerfile latest version
2024-04-11T23:12:08+05:30 [INFO] rebuilt extension index in 18.300709ms
2024-04-11T23:12:08+05:30 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2024-04-11T23:12:27+05:30 [ERROR] crates/lsp/src/lsp.rs:728: oneshot canceled
2024-04-11T23:12:57+05:30 [ERROR] unexpected item event after pane was dropped
2024-04-11T23:12:58+05:30 [ERROR] unexpected item event after pane was dropped
2024-04-11T23:12:58+05:30 [ERROR] unexpected item event after pane was dropped
2024-04-11T23:13:15+05:30 [WARN] Generic lsp request to gopls failed: no package data for import "auth/cmd/service"
2024-04-11T23:13:15+05:30 [ERROR] crates/project/src/project.rs:6699: no package data for import "auth/cmd/service"

```

**Comment by mrnugget** [comment] 2024-04-15 13:23
Closing this as a duplicate of https://github.com/zed-industries/zed/issues/9417 because these are not `gopls` snippets, but `vscode-go` snippets:

https://github.com/golang/vscode-go/blob/9330b086651a8969c6a8b7a508cf3d8c37f1aae1/extension/snippets/go.json#L113-L117

If you turn on tracing for vscode-go, you can see that when you type `if` you also only get that import back as a completion:

![screenshot-2024-04-15-15 23 03@2x](https://github.com/zed-industries/zed/assets/1185253/2539eaf3-c1af-411d-8e09-681e1eafa50c)

**Closed by mrnugget** 2024-04-15 13:23 UTC
Labels: defect, language, go, language server
