### ISSUE TITLE
Assistant configuration panel does not scroll down

### ISSUE THREAD

**Issue by orballo** [zed-industries/zed#16314] opened 2024-08-15 19:55 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

While trying to find the options to configure the new feature `Added tool calling capabilities to OpenAI and Ollama models.` I opened the assistant configuration panel:

1. Open commands menu with `Cmd + Shift + P`
2. Go to `assistant: show configuration`.
3. Once the panel is open, try to scroll down.

### Environment

Zed: v0.148.0 (Zed)
OS: macOS 14.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is as low as I can see on the configuration panel:

![Screenshot 2024-08-15 at 13 04 02](https://github.com/user-attachments/assets/9ae247c7-31b8-40d5-ab2a-fbb99afc93e5)

**Comment by Moshyfawn** [comment] 2024-08-17 16:18
This has already been addressed in [`0.148.1`](https://zed.dev/releases/stable/0.148.1). Let us know if the update has fixed it for you.

Duplicate of:
- #16280

**Closed by Moshyfawn** 2024-08-17 16:18 UTC
Labels: defect, triage, admin read

**Comment by orballo** [comment] 2024-08-17 21:31
Working now. Thanks :) Sorry for the duplicate!

**Comment by kapitaali** [comment] 2025-03-09 19:07
Not fixed on Linux 0.176.3. I click down, page down etc. Nothing happens.
