### ISSUE TITLE
Vim mode - commands for search and replace

### ISSUE THREAD

**Issue by inagumanov** [zed-industries/zed#15014] opened 2024-07-23 14:48 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Entered the search and replace command in the editor:

```
:28,8s/^/\/\//
```

Expected behaviour: will perform search and replace
Actual behaviour: the editor crashed

### Environment

Environment
Zed: Zed 0.144.4 
OS: MacOS 14.5 (23F79)
Memory: 16 GiB 
Architecture: M1

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16350561/Zed.log)

</pre></details>

**Comment by ConradIrwin** [comment] 2024-07-23 15:38
Duplicate of #9428.

If you want to pair with me on this: https://calendly.com/conradirwin/pairing

**Closed** 2024-07-23 15:38 UTC
Labels: defect, triage, panic / crash, admin read
