### ISSUE TITLE
When creating new file/folder in project panel, `a` key does not work

### ISSUE THREAD

**Issue by yizshi** [zed-industries/zed#14766] opened 2024-07-18 20:20 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When creating new file or folder or renaming file or folder in editor UI, the `a` key will stop working.

### Environment

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac15,11
      Model Number: MRW33LL/A
      Chip: Apple M3 Max
      Total Number of Cores: 14 (10 performance and 4 efficiency)
      Memory: 36 GB
      System Firmware Version: 10151.121.1
      OS Loader Version: 10151.121.1
      Serial Number (system): J45F6D7MW6
      Hardware UUID: A0883CD9-10CB-5D83-9A93-38C2EDF1DAB9
      Provisioning UDID: 00006034-000211260244001C
      Activation Lock Status: Disabled

Software:

    System Software Overview:

      System Version: macOS 14.5 (23F79)
      Kernel Version: Darwin 23.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day, 7 hours, 7 minutes

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/user-attachments/assets/6154f1f0-0145-48ff-a74d-ed1595fb2e22

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

```
2024-07-18T20:17:24.146684Z [INFO] starting language server. binary path: "/Users/yizshi/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/", args: ["/Users/yizshi/Library/Application Support/Zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-07-18T20:17:24.362917Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-18T20:17:24.357Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-07-18T20:17:24.357Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-07-18T20:17:24.363223Z [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "e5516539-ec94-4426-b78c-655d11c83fc6",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-07-18T20:17:24.69545Z [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-07-18T20:17:24.693Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-07-18T20:17:24.693Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-07-18T20:17:25.185235Z [INFO] set environment variables from shell:/bin/zsh, path:/Users/yizshi/.pyenv/shims:/Users/yizshi/.nvm/versions/node/v16.17.0/bin:/opt/homebrew/bin:/usr/local/sbin:/Users/yizshi/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/yizshi/.cargo/bin:/Users/yizshi/bin/:/Users/yizshi/.dotnet/tools:/Users/yizshi/golang/bin:/Users/yizshi/src/ZT-trustedpath/ddi:/Users/yizshi/Library/Python/3.9/bin
2024-07-18T20:17:25.185434Z [INFO] fetching latest version of language server "pyright"
2024-07-18T20:17:25.185566Z [INFO] Node runtime install_if_needed
2024-07-18T20:17:25.787365Z [INFO] downloading language server "pyright"
2024-07-18T20:17:25.788095Z [INFO] Node runtime install_if_needed
2024-07-18T20:17:26.000795Z [INFO] starting language server. binary path: "/Users/yizshi/Library/Application Support/Zed/node/node-v18.15.0-darwin-arm64/bin/node", working directory: "/Users/yizshi/src/bug_report", args: ["/Users/yizshi/Library/Application Support/Zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-07-18T20:17:26.096925Z [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Pyright language server 1.1.372 starting"
}
2024-07-18T20:17:26.097072Z [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Server root directory: file:///Users/yizshi/Library/Application%20Support/Zed/languages/pyright/node_modules/pyright/dist"
}
2024-07-18T20:17:26.099214Z [INFO] Language server with id 1 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "Starting service instance \"\""
}
2024-07-18T20:17:26.425968Z [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 5bce37a1-ae1b-43f8-b8f3-9f616a55d14f
2024-07-18T20:18:00.280439Z [INFO] starting language servers for Python: pyright
2024-07-18T20:18:06.892142Z [INFO] starting language servers for Python: pyright
```
</pre></details>

**Comment by notpeter** [comment] 2024-07-18 20:24
What version of Zed are you running?  I believe this is a duplicate of this issue:
- #13655 
Which was released two weeks ago as part of Zed v0.142.6 (current Zed Stable is v0.144.x)

**Comment by yizshi** [comment] 2024-07-18 20:27
Hi, I just updated Zed this morning. My current version is 0.144.3 (549de5cea4c380f40e24a22fc2bd08043ca08d6d)
<img width="264" alt="Screenshot 2024-07-18 at 16 26 41" src="https://github.com/user-attachments/assets/cbc859f6-af19-4830-af87-fdc2f401108e">

**Comment by yizshi** [comment] 2024-07-18 20:29
Just tested with 0.144.3, I can use `a` key to create new file when I have the right click menu up front

**Comment by notpeter** [comment] 2024-07-24 18:17
I am not able to reproduce.

1. Which `base_keymap` are you using? (VScode, Atom, JetBrains, etc)
2. Are you using `vim_mode`?
3. Can you check your `~/.config/zed/keymap.json` for any custom bindings to `"a"`? Perhaps with an incorrect/overly broad `context`?

**Closed** 2024-07-24 18:21 UTC
Labels: keymap / key binding, support
