### ISSUE TITLE
Font rendering issue related to PC sleeping

### ISSUE THREAD

**Issue by doopty** [zed-industries/zed#15362] opened 2024-07-27 23:17 UTC
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The fonts on Zed have some kind of rendering bug that seems to occur when the computer goes to sleep. Every time I've ever noticed it is after closing the laptop and coming back to it later while Zed is still running. I've tried to replicate the issue by manually putting the computer to sleep and it still occurs, all though a bit differently.

### Environment

Zed: v0.145.1 (Zed)
OS: Linux Wayland endeavouros unknown
Memory: 15.5 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Leaving Zed open and allowing the computer too sleep leads to strange rendering bugs. Typically the one I got looks like this 
![Desktop](https://github.com/user-attachments/assets/0521846f-5ba7-410e-9966-a5fed22eae02)
After a couple times of seeing this, I tried to purposefully recreate by putting the computer to sleep manually and opening it back up while Zed is running. Then I got this 
![replicate](https://github.com/user-attachments/assets/214489db-b120-492b-bb3b-41834611af22)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16401703/Zed.log)

</pre></details>

**Comment by notpeter** [comment] 2024-07-28 16:04
I believe this is a duplicate of:
- https://github.com/zed-industries/zed/issues/12827

Can you add a comment with your system/GPU/driver details?

**Closed by notpeter** 2024-07-28 16:04 UTC
Labels: defect, triage, admin read
