### ISSUE TITLE
Shortcut to run selected code from editor in terminal

### ISSUE THREAD

**Issue by soumyaray** [zed-industries/zed#8656] opened 2024-03-01 09:34 UTC
### Check for existing issues

- [X] Completed

### Describe the feature

Would like a keyboard shortcut mapping to take the code selected in an editor and try to run it in the terminal. This is helpful for shell commands that you you would have to copy/paste into terminal. Also helpful for interpreted languages (Ruby/Python/etc.) where you might have a REPL running in terminal and you want to run selected code there directly without using copy/paste. If no code is selected, the current line is run/pasted into terminal.

[VSCode call this command `runSelectedText`](url) and can be mapped to a keybinding by users (I use `cmd-ctrl-enter` on MacOS).

**Comment by Moshyfawn** [comment] 2024-03-01 18:57
Duplicate of #8344

**Comment by Moshyfawn** [comment] 2024-03-01 18:57
Make sure you +👍 the other thread and add any additional information that may be missing.

**Closed by Moshyfawn** 2024-03-01 18:57 UTC
Labels: enhancement, triage, admin read
